### ISSUE TITLE
[ISSUE]:  help !! my volume is 0.0000 and nothing helps!!!! how do i fix this??

### ISSUE THREAD

**Issue by sssofqq** [w-okada/voice-changer#1002]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.16a

### Operational System

Windows 10

### GPU

NVIDIA GeForce RTX 3060 (12GB)

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

MMVC

### Issue Description

this is what mmy settings look like and i still can't figure out what to do 

### Application Screenshot

![image](https://github.com/w-okada/voice-changer/assets/151232281/eb920a23-52c7-459f-9517-a1539bde2714)

### Logs on console

,

**Comment by sssofqq** [comment]
and also my volume is zero not because i forgot to click "start" !!

**Comment by GMCMeowstic** [comment]
since this issue is closed by you, did you fix it if so how
