### ISSUE TITLE
 AI VOICE CHANGER does not start, please help me

### ISSUE THREAD

**Issue by Nekilsior** [w-okada/voice-changer#1015]
### Voice Changer Version

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.17 

### Operational System

Windows 10

### GPU

RX 580 8GB

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.17 

### Issue Description

After opening the "start_http" file it starts the installation and everything goes well, but then it tells me an error. What can't connect

I tried installing 5 different versions and the problem is the same everywhere, I don’t know what to do.
I spent 4 hours on this, please help me

I searched for similar problems, they say delete the file "stored_setting.json"
But I don't have it

### Application Screenshot

![Безымянный](https://github.com/w-okada/voice-changer/assets/151862159/56f052b1-da57-4890-aa3b-fa02251090aa)

### Logs on console

C:\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[VCClient] wait web server...10 http://127.0.0.1:18888/
[VCClient] wait web server...20 http://127.0.0.1:18888/
[VCClient] wait web server...30 http://127.0.0.1:18888/
[VCClient] wait web server...40 http://127.0.0.1:18888/
[VCClient] wait web server...50 http://127.0.0.1:18888/
[VCClient] wait web server...60 http://127.0.0.1:18888/
[VCClient] wait web server...70 http://127.0.0.1:18888/
[VCClient] wait web server...80 http://127.0.0.1:18888/
[VCClient] wait web server...90 http://127.0.0.1:18888/
[VCClient] wait web server...100 http://127.0.0.1:18888/
[VCClient] wait web server...110 http://127.0.0.1:18888/
[VCClient] wait web server...120 http://127.0.0.1:18888/
[VCClient] wait web server...130 http://127.0.0.1:18888/
[VCClient] wait web server...140 http://127.0.0.1:18888/
[VCClient] wait web server...150 http://127.0.0.1:18888/
[VCClient] wait web server...160 http://127.0.0.1:18888/
[VCClient] wait web server...170 http://127.0.0.1:18888/
[VCClient] wait web server...180 http://127.0.0.1:18888/
[VCClient] wait web server...190 http://127.0.0.1:18888/
[VCClient] wait web server...200 http://127.0.0.1:18888/
[VCClient] wait web server...210 http://127.0.0.1:18888/
[VCClient] wait web server...220 http://127.0.0.1:18888/
[VCClient] wait web server...230 http://127.0.0.1:18888/
[VCClient] wait web server...240 http://127.0.0.1:18888/
[VCClient] wait web server...250 http://127.0.0.1:18888/
[VCClient] wait web server...260 http://127.0.0.1:18888/
[VCClient] wait web server...270 http://127.0.0.1:18888/
[VCClient] wait web server...280 http://127.0.0.1:18888/
[VCClient] wait web server...290 http://127.0.0.1:18888/
[VCClient] wait web server...300 http://127.0.0.1:18888/
[VCClient] wait web server...310 http://127.0.0.1:18888/
[VCClient] wait web server...320 http://127.0.0.1:18888/
[VCClient] wait web server...330 http://127.0.0.1:18888/
[VCClient] wait web server...340 http://127.0.0.1:18888/
[VCClient] wait web server...350 http://127.0.0.1:18888/
[VCClient] wait web server...360 http://127.0.0.1:18888/
[VCClient] wait web server...370 http://127.0.0.1:18888/
[VCClient] wait web server...380 http://127.0.0.1:18888/
[VCClient] wait web server...390 http://127.0.0.1:18888/
[VCClient] wait web server...400 http://127.0.0.1:18888/
[VCClient] wait web server...410 http://127.0.0.1:18888/
[VCClient] wait web server...420 http://127.0.0.1:18888/
[VCClient] wait web server...430 http://127.0.0.1:18888/
[VCClient] wait web server...440 http://127.0.0.1:18888/

**Comment by exciar** [comment]
reinstall and make sure you have okay internet connection when starting

**Comment by Nekilsior** [comment]
> reinstall and make sure you have okay internet connection when starting


The program is running on another computer in the next room, the only difference is that it is INVIDIA.
Before asking for help here, I downloaded 5 different versions from 11 to 17 and none of them started for me

Please help me. I tried disabling the antivirus and firewall - that didn't help either.

**Comment by Nekilsior** [comment]
I asked for an INVIDIA video card for a while to check if the program would run on my computer. I just did this - the program started, everything works. It’s a pity that it doesn’t want to start on my AMD video card
( I know that for AMD you need to download the onnxdirectML version)

**Comment by Nekilsior** [comment]
Guys, the problem is solved. I swapped INVIDIA for my AMD graphics card and was able to access the app

**Comment by exciar** [comment]
ok please close issue

**Comment by blastkerbal** [comment]
im having similar problem and it says model_dir does not exist
