### ISSUE TITLE
[ISSUE]: I used it for Discord voice chat, And it worked really well but I've faced one problem.

### ISSUE THREAD

**Issue by AyatsuruMisao** [w-okada/voice-changer#1033]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.17b.zip

### Operational System

Windows 11

### GPU

NVIDIA GeForce RTX4080

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [X] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

Hello!
I use this program for Discord.
And It works really well. Really Thanks!
But I've faced one problem.
That is... whenever I say something, It change that to other voice,
but it changes other people's voice in the voice channel(Screen sharing)...

For example,
I : Hi, there, Glad to meet you!
Kiriko voice : Hi, there, Glad to meet you!
Man A : Yeah! Nice to meet you too! 
Kiriko voice : Yeah! Nice to meet you too!
Man A : Huh?

So It's like...
my mic sensed Man A's Voice and change that to Kiriko's voice.

![happened](https://github.com/w-okada/voice-changer/assets/153376962/5d1f3f9c-6e0c-4806-a5c3-856271ce24b2)

And it happened any models.
not only one model.

Ah, And I'm using VB CABLE for discord.

I really tried solving this problem, But I couldn't...
What Should I do?

Please Help me!
Thanks!

### Application Screenshot

![screenshot](https://github.com/w-okada/voice-changer/assets/153376962/3fc2fe0b-e56c-4354-ab19-951e9ca23177)
![client](https://github.com/w-okada/voice-changer/assets/153376962/ee651748-aab6-4805-b6c5-d7cb7941ac16)
![Client2](https://github.com/w-okada/voice-changer/assets/153376962/e187e0da-86f3-4b82-ba11-12e75525179a)
![Client3](https://github.com/w-okada/voice-changer/assets/153376962/c30800fc-629d-49e9-958f-9a4ca4f1bc87)
![advanced setting](https://github.com/w-okada/voice-changer/assets/153376962/3492692e-8193-4b0d-8b38-88fd99edd299)

### Logs on console

    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0004_t.json
[Voice Changer] download sample catalog. samples_0004_o.json
[Voice Changer] download sample catalog. samples_0004_d.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[VCClient] wait web server...10 http://127.0.0.1:18888/
[VCClient] wait web server...20 http://127.0.0.1:18888/
[VCClient] wait web server...30 http://127.0.0.1:18888/
[VCClient] wait web server...40 http://127.0.0.1:18888/
[VCClient] wait web server...50 http://127.0.0.1:18888/
[Voice Changer] Loading index...
Try loading... model_dir\5\model.index
[VCClient] wait web server... done 200
[2023-12-09 23:00:58] connet sid : U8xTkpF8OvxW2SXnAAAC
[2023-12-09 23:00:58] connet sid : rQvrk5Ci38pXpyz0AAAD
[Voice Changer] update configuration: modelSlotIndex 1702133946008
Pipeline has been deleted
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\8\model.index
[Voice Changer] update configuration: modelSlotIndex 1702133952008
Pipeline has been deleted
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\8\model.index

**Comment by exciar** [comment]
turn off echo cancellation
use a different audio cable 
use headphones

make sure the sound from the other people in the discord doesn't leak into your mic

**Comment by AyatsuruMisao** [comment]
First of all, Thanks for the advices!

And....
Um, I'm really sorry for disturbing you again,

But now I found what the problem is. Maybe....

If I play a music file, VCC sings the song with kiriko voice.
If Discord is ringing, It says the ring with the kiriko voice too.

I really don't know why.
Because even if I set "input" "Microphone" on this program,
It still says "system sound(What I hear in PC)" too.

I add some settings of mine below. 

![001](https://github.com/w-okada/voice-changer/assets/153376962/98f296d6-44e8-45cc-b402-920f89b1e421)
This is the setting of this program.
OUTPUT : CABLE-A

![002](https://github.com/w-okada/voice-changer/assets/153376962/a3fd403a-e0b4-43be-8d4a-5cdec8cad945)
This is the setting of the Discord.
INPUT : CABLE-A

![003](https://github.com/w-okada/voice-changer/assets/153376962/c32b3def-ca64-463b-8766-85f6ff27033e)
This is the Sound Mixer of the Windows 11

![004](https://github.com/w-okada/voice-changer/assets/153376962/e4fccd5a-bffc-4fc7-a538-ae5cf77363e0)
And This is the sound option of the Windows 11.

To solve the problem(VCC says system sounds, other people's sound), 
I tried to set input device of the system "CABLE-B (VB)"
(But whether I set that "CABLE-B" or "Microphone", It doesn't work.)

What is my problem..? or mistake?

Thanks!
I really appreciate your feedback and all of your advices.

**Comment by AyatsuruMisao** [comment]
Haha, I solved this problem.

**The problem** was VCC says system sound(music file, messenger alarm, other users' voice) with a character voice.
And the solution I used is...

![solution](https://github.com/w-okada/voice-changer/assets/153376962/e5218eb7-fee4-4a67-8648-32ec05bd547f)

Yes!
**Just change client -> server!**
It solved the problem!

Thanks!

p.s. Anyone who is suffered by this problem, just try this!
It will help you!
