### ISSUE TITLE
how to export rmvpe model to onnx

### ISSUE THREAD

**Issue by liziru** [w-okada/voice-changer#1040]
### Voice Changer Version

master

### Operational System

ubuntu 20.04

### GPU

1080ti

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [X] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

Thanks for your great job! I tried to export the entire rmvpe process model(including mel_extractor&mel2hidden&decode parts) to onnx model like the onnx model you provided in this project, but failed. I found this project [https://github.com/yxlllc/RMVPE/blob/main/export.py](url) but no weights are provided, I also tried to load your frozen weights using this project but failed to match layers. Can you give me some advice on exporting the entire rmvpe models? I will appreciate any help.
Looking forward to the replay.

### Application Screenshot

![image](https://github.com/w-okada/voice-changer/assets/34911790/3ae449b8-1d57-4deb-9d73-d19e152b96dc)

### Logs on console

![image](https://github.com/w-okada/voice-changer/assets/34911790/e65d575d-6a05-43b6-a4d2-f1d1ff91b475)

**Comment by w-okada** [comment]
Sorry, I'm not sure. Please reach out to the owner of the https://github.com/yxlllc repository. 

Close.
