### ISSUE TITLE
[Question]: Linux and Nvidia support?

### ISSUE THREAD

**Issue by konstantin1722** [w-okada/voice-changer#1060]
### In a few words, describe your idea

Hi, as of 02.01.2024, what is the status of Linux and Nvidia graphics card support?  I can't find any clear documentation. And there are no obvious links (in a prominent place) to configure on Linux with Nvidia. I only found a link to a manual with AMD video cards.

**Comment by RamenSlayer** [comment]
You can follow this instruction with anaconda:
https://github.com/w-okada/voice-changer/blob/master/README_dev_en.md
Also there's a video by ZachAR3 on youtube.
