### ISSUE TITLE
[ISSUE]: Looks like there's a bit of a problem.

### ISSUE THREAD

**Issue by neurogreedy** [w-okada/voice-changer#1069]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.17b.zip

### Operational System

Windows 10

### GPU

RTX 3070

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

MMVC

### Issue Description

when I run the program I get a sign, I press start and this error immediately appears. It worked before, I downloaded it again but it doesn't work now.

### Application Screenshot

![Снимок экрана (1)](https://github.com/w-okada/voice-changer/assets/101376168/6d8035ad-876e-4eda-a9aa-9891e8d2551d)

### Logs on console

C:\Users\SystemX\Downloads\Compressed\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0004_t.json
[Voice Changer] download sample catalog. samples_0004_o.json
[Voice Changer] download sample catalog. samples_0004_d.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2024-01-09 18:49:40] connet sid : O0arCtCD5OsanICNAAAB
[2024-01-09 18:49:40] connet sid : NTye2g_C3YGDK_VlAAAD
[7804:0109/184941.028:ERROR:ssl_client_socket_impl.cc(978)] handshake failed; returned -1, SSL error code 1, net_error -101
[7804:0109/184941.167:ERROR:ssl_client_socket_impl.cc(978)] handshake failed; returned -1, SSL error code 1, net_error -101
[7804:0109/184941.271:ERROR:ssl_client_socket_impl.cc(978)] handshake failed; returned -1, SSL error code 1, net_error -101
[7804:0109/184941.431:ERROR:ssl_client_socket_impl.cc(978)] handshake failed; returned -1, SSL error code 1, net_error -101
[2024-01-09 18:56:21] connet sid : 8NuWMwkOuTiBqHHpAAAG
[2024-01-09 18:56:21] connet sid : dcsfbYBg98D27LTjAAAH
[2024-01-09 18:56:37] connet sid : XsERHBKrkijKFJgjAAAK
[2024-01-09 18:56:37] connet sid : jVEcWCP2rWzg7jv2AAAL

**Comment by neurogreedy** [comment]
i'll be glad if you'll help me with it

**Comment by tekek03** [comment]
makesure you allow  privat connection

**Comment by blastkerbal** [comment]
i have exact same problem what do i do to fix
