### ISSUE TITLE
[ISSUE]: start_http.bat not opening

### ISSUE THREAD

**Issue by Yoda-Lol** [w-okada/voice-changer#1075]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.17b.zip

### Operational System

Windows 10

### GPU

NVIDIA GeForce GTX 1060 6GB

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

Double-clicking the start_http/https.bat files will not open the application

### Application Screenshot

https://drive.google.com/file/d/1fbASvLbpYNNtaZm2kGeoifSUZWcp7ukQ/view?usp=sharing

here is a link to a video of the issue

### Logs on console

no console logs as the application wont open

**Comment by Yoda-Lol** [comment]
I was able to fix it after some troubleshooting on  my own

**Comment by ChillzFN** [comment]
can you help me then?

**Comment by help-needed** [comment]
if you can, can you look into mine im really confused
![Screenshot 2024-03-21 185454](https://github.com/w-okada/voice-changer/assets/164440084/8cd6be6f-758c-4e59-bf1e-28fe48b0aed4)
