### ISSUE TITLE
[ISSUE]: [VCClient] wait web server...0 http://127.0.0.1:18888/

### ISSUE THREAD

**Issue by Woxic591** [w-okada/voice-changer#1135]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.17b.zip

### Operational System

windows 11

### GPU

RTX 3070

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [X] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

i tried deleting the stored setting.json

### Application Screenshot

 [Voice Changer] loading sample failed Expecting value: line 1 column 1 (char 0)
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
[VCClient] wait web server...10 http://127.0.0.1:18888/
[VCClient] wait web server...20 http://127.0.0.1:18888/
[VCClient] wait web server...30 http://127.0.0.1:18888/
[VCClient] wait web server...40 http://127.0.0.1:18888/
[VCClient] wait web server...50 http://127.0.0.1:18888/
[VCClient] wait web server...60 http://127.0.0.1:18888/
[VCClient] wait web server...70 http://127.0.0.1:18888/
[VCClient] wait web server...80 http://127.0.0.1:18888/
[VCClient] wait web server...90 http://127.0.0.1:18888/
[VCClient] wait web server...100 http://127.0.0.1:18888/
[VCClient] wait web server...110 http://127.0.0.1:18888/
[VCClient] wait web server...120 http://127.0.0.1:18888/
[VCClient] wait web server...130 http://127.0.0.1:18888/
[VCClient] wait web server...140 http://127.0.0.1:18888/
Traceback (most recent call last):
  File "MMVCServerSIO.py", line 258, in <module>
  File "subprocess.py", line 1209, in wait
  File "subprocess.py", line 1506, in _wait
KeyboardInterrupt

### Logs on console

 [Voice Changer] loading sample failed Expecting value: line 1 column 1 (char 0)
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
[VCClient] wait web server...10 http://127.0.0.1:18888/
[VCClient] wait web server...20 http://127.0.0.1:18888/
[VCClient] wait web server...30 http://127.0.0.1:18888/
[VCClient] wait web server...40 http://127.0.0.1:18888/
[VCClient] wait web server...50 http://127.0.0.1:18888/
[VCClient] wait web server...60 http://127.0.0.1:18888/
[VCClient] wait web server...70 http://127.0.0.1:18888/
[VCClient] wait web server...80 http://127.0.0.1:18888/
[VCClient] wait web server...90 http://127.0.0.1:18888/
[VCClient] wait web server...100 http://127.0.0.1:18888/
[VCClient] wait web server...110 http://127.0.0.1:18888/
[VCClient] wait web server...120 http://127.0.0.1:18888/
[VCClient] wait web server...130 http://127.0.0.1:18888/
[VCClient] wait web server...140 http://127.0.0.1:18888/
Traceback (most recent call last):
  File "MMVCServerSIO.py", line 258, in <module>
  File "subprocess.py", line 1209, in wait
  File "subprocess.py", line 1506, in _wait
KeyboardInterrupt

**Comment by Woxic591** [comment]
Found the issue, it has to do with the hugging face servers that are down.

**Comment by BlueAmulet** [comment]
Should probably reopen this, this client shouldn't break if huggingface goes down and you've already downloaded the files.

The files in question for me were:
```
samples_0003_d2.json
samples_0003_o2.json
samples_0003_t2.json
```

I found a secondary copy of them on my computer, put them over, and marked them as readonly. Otherwise they were being replaced with a html 503 page.

**Comment by oivio** [comment]
I just come across same issue. 
Why it require connect to huggingface?

**Comment by dareksan3KY** [comment]
im simply deleted Beatrice-JVS from model_dir_static and now working... for me selecting this caused these similar problems.

**Comment by MiaurXs2** [comment]
> im simply deleted Beatrice-JVS from model_dir_static and now working... for me selecting this caused these similar problems.

Thanks! Now it work.
