### ISSUE TITLE
[ISSUE]: Can't connect MMVC server from remote pc

### ISSUE THREAD

**Issue by Kieaer** [w-okada/voice-changer#1170]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.18a.zip

### Operational System

Both Windows 11

### GPU

RTX 3080, RX 6600M

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [X] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Logs on console

![image](https://github.com/w-okada/voice-changer/assets/44261958/ab0c8bf7-ea66-4428-bc0f-38fb8fc42951)

**Comment by mengmengdm** [comment]
you have to use https rather than http before your url

**Comment by Kieaer** [comment]
@mengmengdm Firefox browser - SSL_ERROR_RX_RECORD_TOO_LONG
Chrome/Edge browser - ERR_SSL_PROTOCOL_ERROR

**Comment by Kieaer** [comment]
solved using http_server.bat

**Comment by sinneDeeL** [comment]
> solved using http_server.bat

I am having the same issue trying to access port 18888 on another local PC. I can not find the http_server.bat file anywhere.
