### ISSUE TITLE
[ISSUE]: MMVCServerSIO Wont Open 

### ISSUE THREAD

**Issue by golf-wangg47** [w-okada/voice-changer#1174]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.18a.zip

### Operational System

Windows 10 Pro

### GPU

RTX 3060 

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

everytime i open it with the start https it opens and just shows a blank application of the vc client look under for more info

### Application Screenshot

![Screenshot (62)](https://github.com/w-okada/voice-changer/assets/166239029/ff0a3891-f64a-4206-b36f-3d7a5a0e74fe)
![Screenshot (63)](https://github.com/w-okada/voice-changer/assets/166239029/40bc71fe-9b39-4e35-8436-5c824029af1f)
![Screenshot (64)](https://github.com/w-okada/voice-changer/assets/166239029/c91e20d9-fa68-44b1-bff4-6904c6eee5f7)
![Screenshot (61)](https://github.com/w-okada/voice-changer/assets/166239029/714e91b7-64f8-4146-bd34-9668dddb01e0)

### Logs on console

C:\Users\Home\Downloads\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0004_t.json
[Voice Changer] download sample catalog. samples_0004_o.json
[Voice Changer] download sample catalog. samples_0004_d.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] Web Server Launch Exception, Expecting value: line 1 column 1 (char 0)
[VCClient] wait web server...10 http://127.0.0.1:18888/
[VCClient] wait web server...20 http://127.0.0.1:18888/

**Comment by andreasdotorg** [comment]
I have the same issue. The software worked for me, until after playing with some settings, it stopped working and now shows the above beviour. What was the solution in this case?
