### ISSUE TITLE
[ISSUE]: There's no uninstall option.

### ISSUE THREAD

**Issue by lolwut11** [w-okada/voice-changer#1204]
### Voice Changer Version

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.15.zip

### Operational System

Windows 11

### GPU

RTX 4070

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [X] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

MMVC

### Issue Description

There's no instructions in how to uninstall it in a safe way. Some say ''just delete the folder'', but I doubt that if it took some minutes to be properly installed, will take just a ''delete folder'' to uninstall it completely. There's something wrong and suspicious about this.

### Logs on console

No console log required.

**Comment by KitsuneShan** [comment]
Definitely, the software downloads everything inside of the uncompressed folder. So, yeah, a simple deletion of the folder deletes everything, including settings, because there isn't actually any installation going on. You simply decompress the software and the bat file that you run for the first time downloads some necessary files within the same folder.
If you do not trust it then you shouldn't be here using the software at all.

**Comment by lolwut11** [comment]
It's not about trust only, it's about lack of information/instructions regarding a basic thing of any software: uninstallation. It should be somehwere in the readme or in the software info. github page. That's the issue.

**Comment by KitsuneShan** [comment]
There is no uninstallation information because there is no installation either. It's just that simple. You download a zip file that you can decompress so to get rid of it you can just delete it.

**Comment by lolwut11** [comment]
Understandable, and this issue post will serve as help for the many others wondering about this specific topic, which after youtube videos about this software started to increase. KitsuneShan was great help explaining the key piece in the answer above.

**Comment by lolwut11** [comment]
Understandable, and this issue post will serve as help for the many others wondering about this specific topic, which after youtube videos about this software started to increase. KitsuneShan was great help explaining the key piece in the answer above.

**Comment by burner-208** [comment]
i am also concerned here, ive deleted all files but after the program accessing my terminal i am worried of something left behind. is there a way to ensure all settings and files are removed?
