### ISSUE TITLE
Unable to hear others while the app is open, and can't hear anything on my PC

### ISSUE THREAD

**Issue by Sky49081** [w-okada/voice-changer#1215]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.18a.zip

### Operational System

Windows 10

### GPU

NVIDIA Geforce RTX 4060

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [X] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

When I launch up the application, all the sounds on my PC stop until I close the app, YT won't play video as it just says "Audio Render error, please restart your computer", even though once I close the voice changer, it works like nothing happened, can't hear Discord notifications, other people can hear me while I can't hear them, the voice changer works, changed the audio output to VB Audio, just had to close the app to hear it when I recorded audio using Audacity, passthrough doesn't work because of the audio problem

### Application Screenshot

![problem](https://github.com/w-okada/voice-changer/assets/167769312/dbb41416-146e-4eeb-9fe1-0f6b4d2b2f3a)
![problem 2](https://github.com/w-okada/voice-changer/assets/167769312/b7efdea4-2146-4700-abc0-18a92ae9b9ff)

### Logs on console

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] model slot is changed -1 -> 4
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[VCClient] wait web server...10 http://127.0.0.1:18888/
2024-05-25 06:20:20.7292192 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-05-25 06:20:20.7394927 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] Loading index...
Try loading... model_dir\4\model.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x0000025BA30F3D60>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000025BBE1B1060>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x0000025BBE1B1090>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings serverReadChunkSize:448
[Voice Changer][RVC]: update_settings modelSlotIndex:1716634696004
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2024-05-25 06:21:05] connet sid : 6UOql9khN8M1YEmbAAAC
[2024-05-25 06:21:05] connet sid : AREwgJ5jkLDwgyWyAAAD
[2024-05-25 06:25:11] connet sid : BvZ4yAXO4609d4idAAAG
[2024-05-25 06:25:11] connet sid : 2nV2a9xo0xwK_Hu-AAAH

**Comment by KuukoShan** [comment]
Don't use the software in server mode, only client mode.
Uninstall vb audio cable and install virtual audio cable (VAC).
Restart the computer and give it a try again.

**Comment by Sky49081** [comment]
Can you send the link to download VAC so I don't get the wrong one?

**Comment by Sky49081** [comment]
> Don't use the software in server mode, only client mode. Uninstall vb audio cable and install virtual audio cable (VAC). Restart the computer and give it a try again.

Can you send the link to download VAC so I don't get the wrong one?, and how do I uninstall VB, went to my apps to delete it and it wasn't there?

**Comment by KuukoShan** [comment]
You go to the start menu, type "add or remove programs" then look for vb cable installation and uninstall it. If you can't find it there, then try reinstalling it again so you can uninstall it properly.

You can download VAC right here: https://software.muzychenko.net/freeware/vac470lite.zip

**Comment by Sky49081** [comment]
> You go to the start menu, type "add or remove programs" then look for vb cable installation and uninstall it. If you can't find it there, then try reinstalling it again so you can uninstall it properly.
> 
> You can download VAC right here: https://software.muzychenko.net/freeware/vac470lite.zip

![problem 3](https://github.com/w-okada/voice-changer/assets/167769312/26e768fd-0f0a-4ac9-ab82-e0ffb5ed0da2)

**Comment by KuukoShan** [comment]
If you can't uninstall it using the remove driver button or the control panel looking for the add or remove programs option then try to remove it manually.
Open the "device manager" then scroll down to "Sound, video and game controllers". Locate "VB-Audio Virtual Cable", double-click on it, and go to the "Driver" tab. There is a button at the bottom that says "Uninstall Device". After uninstalling it, scroll up on the device manager and find the "Audio inputs and outputs" category. If everything went fine, you shouldn't have the CABLE Input/output (VB-Audio Virtual Cable) devices. If you still have those then repeat the same process to uninstall them. Restart your computer, install VAC, and restart again. RVC should work fine now using VAC. Just remember to keep it in client mode and not server mode.

**Comment by Sky49081** [comment]
> If you can't uninstall it using the remove driver button or the control panel looking for the add or remove programs option then try to remove it manually. Open the "device manager" then scroll down to "Sound, video and game controllers". Locate "VB-Audio Virtual Cable", double-click on it, and go to the "Driver" tab. There is a button at the bottom that says "Uninstall Device". After uninstalling it, scroll up on the device manager and find the "Audio inputs and outputs" category. If everything went fine, you shouldn't have the CABLE Input/output (VB-Audio Virtual Cable) devices. If you still have those then repeat the same process to uninstall them. Restart your computer, install VAC, and restart again. RVC should work fine now using VAC. Just remember to keep it in client mode and not server mode.

K, do I also select the check box on the uninstall?

**Comment by KuukoShan** [comment]
Which checkbox? Could you be a bit more specific? If it's the checkbox to also remove the driver from the computer, yes. If it's something else then share a screenshot or explain briefly.

**Comment by Sky49081** [comment]
> Which checkbox? Could you be a bit more specific? If it's the checkbox to also remove the driver from the computer, yes. If it's something else then share a screenshot or explain briefly.

![uninstall](https://github.com/w-okada/voice-changer/assets/167769312/6afe678b-3738-4fac-848f-0d7505b6f118)

gonna sleep so, sorry if I respond late, but here, this is what I was talking about

**Comment by KuukoShan** [comment]
So yeah it was already answered on my comment from before.

**Comment by Sky49081** [comment]
> So yeah it was already answered on my comment from before.

It fixed nothing, still having the same problems after installing VAC

**Comment by KuukoShan** [comment]
Which audio devices are you using for the input and output?

**Comment by KuukoShan** [comment]
I am not asking about that, I am asking about which audio devices do you use for input and output on your computer. Basically, which microphone, headset and/or speakers are you using. The screenshot only shows "usb audio device". Send a screenshot of the device manager showing every input and output listed there.

**Comment by Sky49081** [comment]
> I am not asking about that, I am asking about which audio devices do you use for input and output on your computer. Basically, which microphone, headset and/or speakers are you using. The screenshot only shows "usb audio device". Send a screenshot of the device manager showing every input and output listed there.

Oh, I use my headset for both mic and audio, so USB

**Comment by KuukoShan** [comment]
I know, but you are not telling me which one are you using neither showing me a screenshot of them on the device manager.

**Comment by Sky49081** [comment]
> I know, but you are not telling me which one are you using neither showing me a screenshot of them on the device manager.

![Screenshot 2024-05-26 090136](https://github.com/w-okada/voice-changer/assets/167769312/45b23cdd-4e3d-49e1-a986-263dab8aa7cf)
![Screenshot 2024-05-26 090208](https://github.com/w-okada/voice-changer/assets/167769312/911ffd72-1a1c-4b6f-bffc-5e5bda0756d8)

**Comment by KuukoShan** [comment]
Just like I though, you're using the generic Windows drivers hence why is actually not showing the proper name and brand of the devices and just (USB Audio Device). I recommend going into the brand of the headset and download the right drivers for them. You may be able to fix that issue since I believe windows is having a hard time right now trying to figure out the priorities for them. Let me know if that fixes the issues. Otherwise we can tackle different solutions since I do not think that it's 100% related with RVC. You can try, however, try older versions of the software to see if the same issue still there. Try with a quite old one rather than just the prior one.

**Comment by Sky49081** [comment]
> Just like I though, you're using the generic Windows drivers hence why is actually not showing the proper name and brand of the devices and just (USB Audio Device). I recommend going into the brand of the headset and download the right drivers for them. You may be able to fix that issue since I believe windows is having a hard time right now trying to figure out the priorities for them. Let me know if that fixes the issues. Otherwise we can tackle different solutions since I do not think that it's 100% related with RVC. You can try, however, try older versions of the software to see if the same issue still there. Try with a quite old one rather than just the prior one.

I don't remember the brand name as I got these headphones years ago with my PC, so I might just give up on trying, I really don't talk in games alot anyways, but thank you for your assistance and trying to help

**Comment by KuukoShan** [comment]
If you don't mind, you could take some photos of your headset from fronts, side and back. Specially the sides as there may be a hint of the brand and model. I'll find the brand and model for you.
