### ISSUE TITLE
[ISSUE]: VC v2 installing issue

### ISSUE THREAD

**Issue by KarinMiku** [w-okada/voice-changer#1227]
### Voice Changer Version

vcclient_win_cuda_2.0.16-alpha

### Operational System

Windows 10

### GPU

RTX 4070

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

Was about to try the new v2 cuda of the program, but this error happens:
![image](https://github.com/w-okada/voice-changer/assets/51896289/3fc6d400-61e4-45b2-940a-8f0ee3f2300d)

after that, the cmd closes itself. Later, when trying to re-open the program again, it launches, but it shows an error message and it doesn't seem to work:
![image](https://github.com/w-okada/voice-changer/assets/51896289/077c1662-6885-4dd8-a737-a76c464e9ba2)

### Logs on console

i already have shown the console log in the description ^ (cant copy / paste the letters cuz the cmd closes itself very fast)

**Comment by w-okada** [comment]
We are unable to replicate the issue in our environment, so we can't be certain if the measures have resolved the problem. However, a new version has been released. Could you please test it and let us know?

vcclient_win_cuda_2.0.18-alpha

**Comment by KuukoShan** [comment]
> We are unable to replicate the issue in our environment, so we can't be certain if the measures have resolved the problem. However, a new version has been released. Could you please test it and let us know?
> 
> vcclient_win_cuda_2.0.18-alpha

Sorry for the interrupting the subject but, where can I find info about the client cuda 2.0.x version in regards to changes, improvements, etc? I never heard of it before and would like to know in details what's new and better with older versions. Thank you 💛

**Comment by KarinMiku** [comment]
> We are unable to replicate the issue in our environment, so we can't be certain if the measures have resolved the problem. However, a new version has been released. Could you please test it and let us know?
> 
> vcclient_win_cuda_2.0.18-alpha

than you for the answer!, i jsut tried that version but the issue seems to be the same, this time however, the error is less bigger:
![image](https://github.com/w-okada/voice-changer/assets/51896289/877f2639-73e5-4fd1-a48a-ab3d434c6f52)

when i try to open the start_http.bat again, the program looks exactly as before:
![image](https://github.com/w-okada/voice-changer/assets/51896289/3c74c416-78b4-483d-9cb9-3b1967e12e8b)

**Comment by w-okada** [comment]
@KarinMiku 

I might have figured out the cause. I've placed a countermeasure, so please try using it.

2.0.20-alpha

**Comment by KarinMiku** [comment]
> @KarinMiku
> 
> I might have figured out the cause. I've placed a countermeasure, so please try using it.
> 
> 2.0.20-alpha

i just tried 2.0.20-alpha cuda version and everything was installed without issues, however whenever i press the "start" button, this error message appears at the cmd:
![image](https://github.com/w-okada/voice-changer/assets/51896289/0f7ed276-405c-47c3-838e-f3471b38ec49)

i can hear my voice but it is very laggy / cuts off a lot (i guess due to the error, the program is trying to use my cpu instead of the gpu)

**Comment by KarinMiku** [comment]
> you may not install cuda and cudnn correctly. If you can not install them because of some reaosen, try to use dml version. And if you install only cuda and not install cudnn, torch_cuda can be also avaliable

it seems i don't have cuda installed, tried to use the command "nvcc --version" on cmd and didn't get a result, do you know which cuda version do i need to have? 
and im kinda confuse btw, cuz in the other hand, it seems that i do have torch_cuda (?) since i was able to use the vcclient_win_cuda_torch_cuda_2.0.20-alpha version without errors

**Comment by w-okada** [comment]
https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements

**Comment by KarinMiku** [comment]
sorry for the late reply, I think this issue is now resolved, I installed the latest version of cuda+cudnn and the program is running smoothly, however the quality seems to be worse than the previous v1. I guess this is something to be expected due to the program being an alpha release 😅. Thanks btw!
