### ISSUE TITLE
[help]Cannot hear the changed voice on (Mac m1 ProMax 64g )

### ISSUE THREAD

**Issue by zsq2010** [w-okada/voice-changer#1249]
verison:
 MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.17b.zip
mac os:14.4 sonoma

<img width="570" alt="图片" src="https://github.com/w-okada/voice-changer/assets/4374659/30c74c21-2dfb-47b6-a7c8-704694233919">

<img width="760" alt="图片" src="https://github.com/w-okada/voice-changer/assets/4374659/40e55454-145d-46af-a57c-2fbcab5e311d">

**Comment by zsq2010** [comment]
for about many minutes,stop,but seems executing...

**Comment by zsq2010** [comment]
whats wrong with these kids...
<img width="570" alt="图片" src="https://github.com/w-okada/voice-changer/assets/4374659/744427eb-f6ff-4628-a73a-eba59ec7a5d1">

**Comment by zsq2010** [comment]
changed to a Bluetooth speaker,cannnot hear,either
<img width="760" alt="图片" src="https://github.com/w-okada/voice-changer/assets/4374659/56736ad9-6cf6-4ab6-b007-850bf6e35a29">

**Comment by zsq2010** [comment]
when passthru,can hear the sound unconverted, it means the sound input hardware--microphone works well

**Comment by KuukoShan** [comment]
Not a Mac user but you should start by copying the console text and pasting it into a message for better review of what's happening. Screenshots may not show the full log.

**Comment by w-okada** [comment]
how about [v.2](https://github.com/w-okada/voice-changer/tree/v.2)

**Comment by zsq2010** [comment]
> how about [v.2](https://github.com/w-okada/voice-changer/tree/v.2)

appreciate for helpful infomation,tried and works now❤

**Comment by Mcudll929** [comment]
What is the latency if the service is configured on a Mac?

**Comment by Kuuko-fokkusugaru** [comment]
> What is the latency if the service is configured on a Mac?

The latency depends on the performance capabilities of the computer and the size set for the buffer. The bigger it is, the higher the quality. So setting the quality to 0.5 seconds will be better than 0.1 but you won't get less latency than 0.5 regardless of the performance of the computer.
