### ISSUE TITLE
[ISSUE for v2]: Colab edition does not work. 

### ISSUE THREAD

**Issue by Mega404** [w-okada/voice-changer#1258]
### Voice Changer Version

2.0.26-alpha colab

### Operational System

Windows 10

### GPU

none

### CUDA Version

none

### Read carefully and check the options

- [ ] If you use win_cuda_torch_cuda edition, setup cuda? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use win_cuda edition, setup cuda and cudnn? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use mac edition, client is not launched automatically. Use chrome to open application.?
- [X] I've tried to change the Chunk Size
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RMVPE_ONNX, DIO

### Issue Description

I'm having negative DB despite the mic working normally, tested with/without RVC on Discord and when RVC is on it produces no sound other than a few words and choppy, how can I solve this as I have outdated Hardware and wanted to use RVC 

### Application Screenshot

![Screenshot 2024-06-27 132730](https://github.com/w-okada/voice-changer/assets/173989937/c3033fa3-cbca-4089-b549-bb1c264b5136)

### Logs on console

None

**Comment by w-okada** [comment]
In VCClient, Decibels Full Scale is used, so it's normal for the values to be negative.

**Comment by w-okada** [comment]
While the Colab edition does not heavily rely on the performance of your PC, if your PC is very old, it might not be able to play audio. Which CPU are you using?
Also, could you check the CPU load using the performance monitor?

Additionally, the network speed greatly affects the performance. How fast is your network speed?
Could you check it using something like [SpeedTest](https://www.speedtest.net/ja/result/16426533671)?

**Comment by KuukoShan** [comment]
I am not as proficient and smart as Okada but I can see DIO selected for the F0 detection. If I remember correctly, DIO make use of the CPU but you need to use the GPU so try rmvep_onnx instead. You also need to check that in Google collab settings the performance is set to use the GPU and not the CPU.

As a side note VB cable often produces noisy and choppy results. Try to use VAC (Virtual Audio Cable) instead which also has a free version limited to a single cable. I ran into this issue myself with Discord, it doesn't work with vb cable but it does with VAC. I never ran into any issue with VAC while VB would sound choppy in certain games and apps.

**Comment by Mega404** [comment]
> While the Colab edition does not heavily rely on the performance of your PC, if your PC is very old, it might not be able to play audio. Which CPU are you using? Also, could you check the CPU load using the performance monitor?
As for my CPU, an i7-6820HQ, I haven't checked the performance yet as I'm at work as we speak.
> Additionally, the network speed greatly affects the performance. How fast is your network speed? Could you check it using something like [SpeedTest](https://www.speedtest.net/ja/result/16426533671)?
Speed test is fine to me so I don't think it because of the wifi

**Comment by Mega404** [comment]
> I am not as proficient and smart as Okada but I can see DIO selected for the F0 detection. If I remember correctly, DIO make use of the CPU but you need to use the GPU so try rmvep_onnx instead. You also need to check that in Google collab settings the performance is set to use the GPU and not the CPU.

I see
> As a side note VB cable often produces noisy and choppy results. Try to use VAC (Virtual Audio Cable) instead which also has a free version limited to a single cable. I ran into this issue myself with Discord, it doesn't work with vb cable but it does with VAC. I never ran into any issue with VAC while VB would sound choppy in certain games and apps.

Thank for the recommendation, I'll try it once I get back home and will update the situation.

**Comment by kazumi371** [comment]
> In VCClient, Decibels Full Scale is used, so it's normal for the values to be negative.

mine cant install i keep get this [Errno 2] No such file or directory: '/content/drive/MyDrive/vcclient/eae1b7592ec7c44b88730d2044b7bd9a'
/content

**Comment by w-okada** [comment]
use this.
https://github.com/w-okada/voice-changer/blob/v.2/w_okada's_Voice_Changer_version_2_x.ipynb

**Comment by kazumi371** [comment]
> use this. https://github.com/w-okada/voice-changer/blob/v.2/w_okada's_Voice_Changer_version_2_x.ipynb

I still can't upload any models

**Comment by w-okada** [comment]
no response. close.
