### ISSUE TITLE
[ISSUE for v2]: colab one not working

### ISSUE THREAD

**Issue by kazumi371** [w-okada/voice-changer#1261]
### Voice Changer Version

vcclient

### Operational System

windows 10

### GPU

none

### CUDA Version

none

### Read carefully and check the options

- [ ] If you use win_cuda_torch_cuda edition, setup cuda? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use win_cuda edition, setup cuda and cudnn? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use mac edition, client is not launched automatically. Use chrome to open application.?
- [ ] I've tried to change the Chunk Size
- [ ] I've tried to set the Index to zero
- [ ] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Does pre-installed model work?

No

### Model Type

rvc

### Issue Description

i keep getting this its not givving a link

### Application Screenshot

![how do i fix this](https://github.com/w-okada/voice-changer/assets/127456791/93ddee63-7ae9-4f83-aff9-42e28f279864)

### Logs on console

GPU is available
GPU Name: Tesla T4
Welcome to ColabMod
Mounted at /content/drive
Checking latest version...
current_version_hash: None
latest version hash eae1b7592ec7c44b88730d2044b7bd9a
hash not match -> download latest version
% Total
% Received %
Xferd
Average
Speed
Time
Time
Time
Current
100
1157
100
1157 0
Dload
Upload
Total
Spent
Left
Speed
100 3028M
100 3028M 0
0 6859
00:00:40
0:00:40
::
6886
Download is done.
0 75.1M
0 -:--:--::::--
74.0M
[Errno 2] No such file or directory: '/content/drive/MyDrive/vcclient/eae1b7592ec7c44b88730d2044b7bd9a' /content
chmod: cannot access 'vcclient_latest_for_colab': No such file or directory Installing modules... Install is done

 Waiting for server... elapsed: 109sec
/bin/bash: line 1: ./vcclient_latest_for_colab: No such file or directory

**Comment by w-okada** [comment]
New version is released. try it.
No longer ngrok is needed.(experimental)

**Comment by kazumi371** [comment]
> New version is released. try it. No longer ngrok is needed.(experimental)

Do you have a link

**Comment by w-okada** [comment]
Same.

https://github.com/w-okada/voice-changer/blob/v.2/w_okada's_Voice_Changer_version_2_x.ipynb

**Comment by kazumi371** [comment]
> Same.
> 
> https://github.com/w-okada/voice-changer/blob/v.2/w_okada's_Voice_Changer_version_2_x.ipynb

It works but I keep getting the upload failed when I upload a model

**Comment by w-okada** [comment]
Ah,,ok. I'll release bugfixed version. soon. please wait

**Comment by w-okada** [comment]
New version has been released.

**Comment by kazumi371** [comment]
> New version has been released.

Can I get the link

**Comment by kazumi371** [comment]
> > New version has been released.
> 
> Can I get the link

The link that was on the page doesn't work
