### ISSUE TITLE
[REQUEST for V2]: Using GPU on Mac (Apple Silicon)

### ISSUE THREAD

**Issue by Ghostkwebb** [w-okada/voice-changer#1262]
### In a few words, describe your idea

Utilising the GPU's on apple silicon macs to boost the performance of the voice changer as there are small performance issues here and there which make it unrealistic.

### More information

There is no doubt that V2 works great with CPU but there are still some stutters and performance issues on the Apple silicon Macs. 

Is there a way to utilize the GPU in Apple silicon to boost the performance and improve it overall in V2?

**Comment by w-okada** [comment]
V2 already uses mps.

**Comment by Ghostkwebb** [comment]
> V2 already uses mps.

Sorry for my lack of knowledge but could you tell me what you mean?

**Comment by Ghostkwebb** [comment]
nvm

**Comment by Ghostkwebb** [comment]
I assumed that as it didn't show Apple silicon GPU in the app it didn't use it but MPS or Metal Performance Shaders were being used when I tested and wasn't being brain dead and asked here for the feature request :)
