### ISSUE TITLE
[REQUEST]:  Dynamic Voice Volume Output

### ISSUE THREAD

**Issue by KuukoShan** [w-okada/voice-changer#1266]
### In a few words, describe your idea

I would like if the output volume could change with the input volume

### More information

I love RVC but I have noticed that, when speaking, the voice volume does not change.
I think it would be really interesting if the output gain could consider the input's volume. So if I speak louder or scream, the voice output could also be sent with a higher volume. In the same way, if I speak with a lower voice, the output gain would lower the gain too. We should still be able to set the different gains for input and output volumes but with an extra multiplier and optional setting to link them. Conversations with the capability of talking in different volumes could make them more dynamic and realistic. As of right now, the tone of the voice is monotonous which makes it hard to express different feelings and emotions.

I think it could be an interesting feature which shouldn't require too much changes to the software.
Thank you! 💛

**Comment by w-okada** [comment]
Please try v2.0.36

**Comment by KuukoShan** [comment]
> Please try v2.0.36

I have been using v1 for a long time and I started using v2 recently. But I didn't notice that this feature is present. Do I need to change something to make it work? For the volume is always the same even if I scream or speak low. Sorry.

**Comment by w-okada** [comment]
That's right. It wasn't implemented in v2, but I intended to implement it in v2.0.36. Is it not working?

**Comment by KuukoShan** [comment]
Oh! I didn't read about it in the release notes, sorry.
I will test it tomorrow and report back.
Thank you!

**Comment by KuukoShan** [comment]
> That's right. It wasn't implemented in v2, but I intended to implement it in v2.0.36. Is it not working?

Hi again!
I have been testing thoroughly the three versions that I have and made a screenshot to compare all of them.

The first audio on top is the original audio. The three first chunks of audio are at different volumes so you can see that the first one is smaller, the second one a bit bigger and the third one way bigger because I was speaking very loud.
The second audio is v1 (you can read it in the name of the track.
The third audio is v2.0.24.
The third audio is 2.0.36.

I have tried to match the settings between all the tests. I used an audio file as a source to make sure that the results can be compared properly. I use a gain of 2 for the output and 1 for the input. The differences in volume are very similar to v1 so I do not notice if this feature is working properly or not. There is also a lack of control over it. I can't enable or disable to test it properly. There is also no slider option to act as a multiplier so I can make even a bigger difference between low and loud volume (for example, min gain 1 and max gain 1 would be equal to the source volume but min gain 1 and max gain 3 would mean that the output would have a higher range of volume and reach an even louder output than the input).

I do understand some of the limitations though, but I definitely would like to see a difference in volume more clear than actual one as it's almost impossible to notice.

By the way, I did all the tests with PTH file. For v1 I used RMVPE while for v2 I used RMVPE_ONNX. In v2, if I use ONNX voice model instead of PTH, the result is of very low quality, distorted, and robotic. This is a different issue but I do not know if there is a thread already opened about it. I will try to find it. Thank you.

![Screenshot 2024-07-06 180810](https://github.com/w-okada/voice-changer/assets/55133451/c1ab7e21-ddc7-44d1-b530-2da1cf09e15f)

**Comment by w-okada** [comment]
> I do understand some of the limitations though, but I definitely would like to see a difference in volume more clear than actual one as it's almost impossible to notice.

Wouldn't it be like that if you increase the gain of the output?


> By the way, I did all the tests with PTH file. For v1 I used RMVPE while for v2 I used RMVPE_ONNX. In v2, if I use ONNX voice model instead of PTH, the result is of very low quality, distorted, and robotic. 

please post as new issue.

**Comment by KuukoShan** [comment]
> > I do understand some of the limitations though, but I definitely would like to see a difference in volume more clear than actual one as it's almost impossible to notice.
> 
> Wouldn't it be like that if you increase the gain of the output?
> 
> > By the way, I did all the tests with PTH file. For v1 I used RMVPE while for v2 I used RMVPE_ONNX. In v2, if I use ONNX voice model instead of PTH, the result is of very low quality, distorted, and robotic.
> 
> please post as new issue.

You can check the first track, the first portion has 3 different levels of volume, that's why the wave graph goes from small to very big. And then you can compare v1 with v2024 and v2036. There is no difference so I don't think the volume difference is working at all. The wave graph looks identical to v1 after all. I don't know why 2024 has a higher volume than 2036 though. But I still don't see what I meant. Maybe I just explained wrongly the feature that I wanted (sorry, English is not my main language).
What I wanted is a feature that changes the output volume with my real input volume. So if I scream, RVC volume goes really high, and if I speak with very low volume, RVC volume goes really low. In all the versions the volume seems to be identical and the variation between low and high volume is almost non-existent. 
![image](https://github.com/w-okada/voice-changer/assets/55133451/762d0906-4684-48ad-b0c5-1b5f911c28f2)

**Comment by w-okada** [comment]
I think I understand what you mean.

However, it seems like there are slight variations in volume in the three portions.

There is a big difference between "almost no difference" and "not working at all." In this case, are you saying that the volume does change according to the input audio, but the differences are very minimal?

If that's the case, then increasing the gain of the output audio might make the differences more noticeable. Did that not work?


![image](https://github.com/w-okada/voice-changer/assets/48346627/a8ec878d-b327-4431-b1d3-c05ee0e76aed)


> I don't know why 2024 has a higher volume than 2036 though
Because 2.0.24 don't have volume control process. This process is implemented at 2.0.36.

I said this.
> It wasn't implemented in v2, but I intended to implement it in v2.0.36. Is it not working?

**Comment by KuukoShan** [comment]
> I think I understand what you mean.
> 
> However, it seems like there are slight variations in volume in the three portions.
> 
> There is a big difference between "almost no difference" and "not working at all." In this case, are you saying that the volume does change according to the input audio, but the differences are very minimal?
> 
> If that's the case, then increasing the gain of the output audio might make the differences more noticeable. Did that not work?
> 
> ![image](https://private-user-images.githubusercontent.com/48346627/346294030-a8ec878d-b327-4431-b1d3-c05ee0e76aed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMDcxMjcsIm5iZiI6MTcyMDMwNjgyNywicGF0aCI6Ii80ODM0NjYyNy8zNDYyOTQwMzAtYThlYzg3OGQtYjMyNy00NDMxLWIxZDMtYzA1ZWUwZTc2YWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDIzMDAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExZThjOWNlZmVkNzY5ZTkxZDA5ZWRkM2Y1ZDU5M2E5YWI3YTg2NTAwOGYxNzYwNTQxYjQ3YWE4ZDk3ZDIyZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-kAubXOnhPTxGdg0qk0MdeTuOSGzmr9VzpXug-uN5eU)
> 
> > I don't know why 2024 has a higher volume than 2036 though
> > Because 2.0.24 don't have volume control process. This process is implemented at 2.0.36.
> 
> I said this.
> 
> > It wasn't implemented in v2, but I intended to implement it in v2.0.36. Is it not working?

But I though that this feature was new on 2.0.36 but on v1 the volume levels are the same. Was this feature always present on v1? Because I never noticed. Maybe I just expected a bigger difference because I though it was new for RVC on version 2.0.36 only and not in older versions (including v1).

**Comment by KuukoShan** [comment]
When I requested this feature, I was using v1 mainly because the quality in v2 seems a bit bad. So I truly didn't know that this feature was already present in v1.
If this feature was always in v1 then maybe my request is an option to make the volume difference more noticeable. If I change gain, everything gets more volume, even low volume input. But I want to increase the difference between low and high. Because if I use the mic without RVC, it's easier to notice a bigger difference between low and high volume. It was only an idea so it's OK if isn't possible. Since I am not programmer, my request may be a bit weird, sorry 🙏😅

**Comment by w-okada** [comment]
@KuukoShan 
please try v.2.0.40-alpha

**Comment by Mcudll929** [comment]
why Im not found this function in the default “master” version？

**Comment by Mcudll929** [comment]
> 请尝试 v.2.0.40-alpha

why Im not found this function in the default “master” version？

**Comment by Mcudll929** [comment]
> @KuukoShan please try v.2.0.40-alpha
I found out that the v2 version is available on the colab platform, but how do I deploy it to my own server? @w-okada

**Comment by w-okada** [comment]
https://huggingface.co/wok000/vcclient000/resolve/main/vcclient_mac_2.0.40-alpha.zip?download=true

**Comment by Mcudll929** [comment]
> https://huggingface.co/wok000/vcclient000

Sorry, do this project can be used in remote server?

**Comment by w-okada** [comment]
@KuukoShan 
"Did you check version 2.0.40-alpha?

**Comment by Mcudll929** [comment]
Yes.
I mean I want to connect a windows PC to a linux server, similar to v1, but
v2 doesn't seem to have this function？


w-okada ***@***.***>于2024年7月12日 周五16:04写道：

**Comment by KuukoShan** [comment]
@w-okada sorry I was busy. I will test it later and report back. Thank you for your hard work!

**Comment by KuukoShan** [comment]
@w-okada I did test today 2.0.40 but PTH files aren't working when using GPU mode. They work in CPU mode but the voice stops every second so it's impossible to test properly. I am attaching the logs file.

Also, I can't use ONNX files to test because they are still broken and sound very bad, robotic, and monotone. This also happens with the included ONNX voices.
[logs.txt](https://github.com/user-attachments/files/16235578/logs.txt)

**Comment by KuukoShan** [comment]
@w-okada The volume difference seems to work fine though. There are some popping and crackling sounds in certain moments of silence as if a microphone were disconnected. But so far the difference in volume seems to be very good and believable.
The top one is v2.0.40, the bottom one is v1.5.3.18a
![image](https://github.com/user-attachments/assets/f96e0672-dff6-45e2-b8b9-c87d1c632b8a)

**Comment by w-okada** [comment]
@KuukoShan 
We have identified areas that might be causing the deterioration in audio quality.
These issues have been corrected, so please try the new version (v.2.0.44-alpha).

Additionally, we have prepared several methods for adjusting the volume, so please give them a try.
![image](https://github.com/user-attachments/assets/0d552cac-7f71-4e09-842d-02590593e064)

**Comment by w-okada** [comment]
move to: 
https://github.com/w-okada/voice-changer/issues/1266
https://github.com/w-okada/voice-changer/issues/1287
