### ISSUE TITLE
[ISSUE for v2]: Is it possible to implement the V2 version to be deployed on a cloud server? I would like to experience the dynamic voice volume output feature

### ISSUE THREAD

**Issue by Mcudll929** [w-okada/voice-changer#1276]
### Voice Changer Version

vcclient_win_std_2.0.40-alpha.zip

### Operational System

Ubuntu 20.04

### GPU

2080ti

### CUDA Version

10.8

### Read carefully and check the options

- [ ] If you use win_cuda_torch_cuda edition, setup cuda? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [X] If you use win_cuda edition, setup cuda and cudnn? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use mac edition, client is not launched automatically. Use chrome to open application.?
- [X] I've tried to change the Chunk Size
- [X] I've tried to set the Index to zero
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Does pre-installed model work?

YES

### Model Type

RVC

### Issue Description

Is it possible to implement the V2 version to be deployed on a cloud server? I would like to experience the dynamic voice volume output feature

### Application Screenshot

none

### Logs on console

none

**Comment by w-okada** [comment]
try colab version.

**Comment by w-okada** [comment]
no response close.
