### ISSUE TITLE
Models that important dont work

### ISSUE THREAD

**Issue by vexcader** [w-okada/voice-changer#1278]
### Voice Changer Version

vcclient_win_cuda_2.0.40-alpha

### Operational System

Windows 11

### GPU

4060

### CUDA Version

12.1

### Read carefully and check the options

- [ ] If you use win_cuda_torch_cuda edition, setup cuda? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [X] If you use win_cuda edition, setup cuda and cudnn? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use mac edition, client is not launched automatically. Use chrome to open application.?
- [X] I've tried to change the Chunk Size
- [X] I've tried to set the Index to zero
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Does pre-installed model work?

YES

### Model Type

RVC

### Issue Description

ANY MODEL THAT I important just doesnt work i dont hear a thing

### Application Screenshot

![image](https://github.com/user-attachments/assets/ca8d8ad3-2f9f-4ace-9288-3660bef965f9)

### Logs on console

none

**Comment by KuukoShan** [comment]
PTH voice models do not work with that version. The issue was already reported here:

https://github.com/w-okada/voice-changer/issues/1274

**Comment by w-okada** [comment]
see 

https://github.com/w-okada/voice-changer/issues/1274


close this issue
