### ISSUE TITLE
[ISSUE for v2]:  Choppy only on discord and other apps 

### ISSUE THREAD

**Issue by vexcader** [w-okada/voice-changer#1280]
### Voice Changer Version

doesnt matter for this

### Operational System

Windows 11

### GPU

4060

### CUDA Version

12.1

### Read carefully and check the options

- [ ] If you use win_cuda_torch_cuda edition, setup cuda? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [X] If you use win_cuda edition, setup cuda and cudnn? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use mac edition, client is not launched automatically. Use chrome to open application.?
- [X] I've tried to change the Chunk Size
- [X] I've tried to set the Index to zero
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Does pre-installed model work?

YES

### Model Type

RVC

### Issue Description

i try the mic on just the okada play back AND IT IS PERFECT but on discord or any othr voice chat it is so choppy like it works but mid way it  will just chop

### Application Screenshot

![image](https://github.com/user-attachments/assets/e9d25d1e-c164-499c-a648-c7da17aa425f)

### Logs on console

none

**Comment by KuukoShan** [comment]
Replace vb-cable with Virtual Audio Cable (VAC).

**Comment by KuukoShan** [comment]
Also, if you set the N. Gate too high, you may have issues with the software hearing your speech if you lower the volume below the threshold.  Try lowering it to the default -110 value, -41 seems quite high and you may need to talk very loud. If you are afraid of noise being caught by the software, use sup1 to suppress normal ambient noise like computer fans. Use sup2 together with sup1 if there is louder noise like a fan stand in your room or if the software gets the noise of your keyboard typing.
The most important part is still replacing vb cable with VAC, as vb cable is not compatible with Discord and you will get a huge amount of stutter.

**Comment by vexcader** [comment]
Tried vac still cutting out and the threshold doesn’t matter I put it down our up it just stutters out like I can’t say a sentence without it cutting off

**Comment by vexcader** [comment]
Did all of they already changed threshold and got vac I can say a few words but it cuts for like half a second and glitches out witch ruins it

**Comment by KuukoShan** [comment]
If the exit works when testing out inside of RVC but not on other software like Discord, the issue is directly related to the virtual cable used in between. You can check this if you set the output to VAC and the monitor to your headset/speakers so that you can listen to yourself. The exit should be the same for both. Remember to set the output and input correctly. 

Also, when the audio cuts and stutter, which is the "res" or "convert" value shown on RVC window while you speak? It should increase while speaking so let me know what's the highest value that it shows while speaking and having stutter.

**Comment by KuukoShan** [comment]
VAC have a free version that you only need to install and forget. You don't need to configure change anything.

**Comment by w-okada** [comment]
see 
https://rentry.co/VoiceChangerGuide#discord-crackle-fixes

**Comment by w-okada** [comment]
no reponse close
