### ISSUE TITLE
Хоррор

### ISSUE THREAD

**Issue by afkmen** [w-okada/voice-changer#1282]
Всё было хорошо до того момента, пока я не начал слышать какие то звуки/дыхание/шаги, когда выключаю микрофон, всё пропадает, когда включаю, всё повторяется. Сижу, и не понимаю происходящего. От испуга я удалил всё это, но звуки остались, помогите....

**Comment by KuukoShan** [comment]
> Всё было хорошо до того момента, пока я не начал слышать какие то звуки/дыхание/шаги, когда выключаю микрофон, всё пропадает, когда включаю, всё повторяется. Сижу, и не понимаю происходящего. От испуга я удалил всё это, но звуки остались, помогите....

Программное обеспечение RVC может выбрать любой фоновый шум и преобразовать его в «голос».  В результате шум вокруг вас, такой как шум вентиляторов, шум печатной машинки, проезжающей мимо машины и т. д., будет преобразован в фонемы.  Вот почему вы будете слышать такие звуки, как дыхание или разговор, даже когда вы не говорите.  Чтобы устранить эту проблему, отметьте опцию «sup1».  Если проблема остается, также отметьте опцию «sup2».  Вы также можете настроить настройку «Шумовой порог» или «Шумоподавитель», чтобы увеличить громкость, необходимую для разговора, и исключить фоновый шум при меньшей громкости.  Я не русский, поэтому воспользовался переводчиком, извините за плохой перевод.

**Comment by afkmen** [comment]
Это значит что меня не взломали, или что-то по типу этого? Извините за такие вопросы, просто сижу в испуге)

**Comment by afkmen** [comment]
спасибо, я понял проблему, теперь боюсь шума из микрофона!) Удачи мне не стать заикой

**Comment by KuukoShan** [comment]
Это программное обеспечение очень безопасно.  Многие люди используют его ежедневно без проблем.  Я не понимаю, почему на вашем компьютере все еще есть звуки, но это может быть ошибка в ваших аудиодрайверах.  Вы можете попробовать перезагрузить компьютер.  Возможно, что-то застряло в виртуальном аудиокабеле.

**Comment by afkmen** [comment]
хорошо, спасибо вам что помогли, я вам благодарен
