### ISSUE TITLE
[ISSUE for v2]:  volume tune type not workting with PTH models on v2.0.44 alpha cuda

### ISSUE THREAD

**Issue by Kuuko-fokkusugaru** [w-okada/voice-changer#1286]
### Voice Changer Version

vcclient_win_cuda_2.0.44-alpha.zip

### Operational System

Windows 11 Pro

### GPU

3080Ti

### CUDA Version

12.5.78

### Read carefully and check the options

- [ ] If you use win_cuda_torch_cuda edition, setup cuda? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use win_cuda edition, setup cuda and cudnn? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use mac edition, client is not launched automatically. Use chrome to open application.?
- [ ] I've tried to change the Chunk Size
- [ ] I've tried to set the Index to zero
- [x] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [x] I've tried to extract to another folder (or re-extract) the .zip file

### Does pre-installed model work?

Yes

### Model Type

RVC PTH

### Issue Description

The latest volume tune type setting does not work with PTH models. When switching to something other than sqrt, there is no output. Changing back to sqrt brings back the output and continues to work normally. ONNX models do not have this issue.

### Logs on console

[logs.txt](https://github.com/user-attachments/files/16321290/logs.txt)

**Comment by w-okada** [comment]
please try 2.0.45 alpha

**Comment by w-okada** [comment]
no response close.
