### ISSUE TITLE
[ISSUE for v2]: 

### ISSUE THREAD

**Issue by Kuuko-fokkusugaru** [w-okada/voice-changer#1287]
### Voice Changer Version

vcclient_win_cuda_2.0.44-alpha.zip

### Operational System

Windows 11 Pro

### GPU

3080Ti

### CUDA Version

12.5.78

### Read carefully and check the options

- [ ] If you use win_cuda_torch_cuda edition, setup cuda? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use win_cuda edition, setup cuda and cudnn? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use mac edition, client is not launched automatically. Use chrome to open application.?
- [ ] I've tried to change the Chunk Size
- [ ] I've tried to set the Index to zero
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Does pre-installed model work?

YES

### Model Type

RVC ONNX

### Issue Description

The new volume tune type works well but there are some artifacts introduced at certain points of silenced input. There is a "pop" sound as if a microphone were disconnected when low or zero volume zones happen. I include 3 audio clips, the same as the screenshot, where the glitch sound can be heard on linear ratio and sqrt ratio. It does not happen on sqrt. I marked on the screenshot where the glitch happened more noticeably.
[volume tune type comparison glitch.zip](https://github.com/user-attachments/files/16321400/volume.tune.type.comparison.glitch.zip)

### Application Screenshot

![image](https://github.com/user-attachments/assets/859b2d2b-26a4-4201-9671-e42212768568)

### Logs on console

Not needed

**Comment by w-okada** [comment]
In 2.0.45 alpha, there are new volume tune type. try it.
(linear-ratio, sqrt-ratio will be removed)

**Comment by w-okada** [comment]
no response. close

**Comment by Kuuko-fokkusugaru** [comment]
Testing takes time, and I have been busy.
Please be patient.
