### ISSUE TITLE
[REQUEST]: Could we have a dark mode for V2?

### ISSUE THREAD

**Issue by Mikey-Mikey** [w-okada/voice-changer#1306]
### In a few words, describe your idea

I want to not get flashbanged due to a white UI.

### More information

The UI is not bad don't get me wrong, it's just the color scheme should have a dark theme for people who want it. I actually did this myself by changing the CSS file manually and I think I got it looking pretty good but I pretty much hardcoded these values because all of the CSS classes were random letters and numbers:

![image](https://github.com/user-attachments/assets/1366bc7d-a93e-4a91-90f6-aa8baa178e2a)
![image](https://github.com/user-attachments/assets/2b1c28f7-6c9a-4269-b05a-2f0a35f9c98a)

Notice how the icons in the top left are still black. I couldn't change just the color of these since the icons were made black in the image file for each of them.

If you want my CSS file I will gladly give it to you guys. Just be aware that the CSS is not very nice. I would also like the ability to make proper themes by maybe having like a theme.json or something, y'know to easily create themes like my dark theme.

As an extra feature that's unrelated to the title of this post. Having the ability to change each voice icon inside the UI would be nice. I had to do it manually by changing the .json. Unless this is already a feature and I just neglected to read about it.

I'm REALLY loving V2 so far and the performance has improved a crap ton. (Also in the bottom right you misspelt Voice Changer Info wrong, "Voice Changaer Info")

**Comment by Mikey-Mikey** [comment]
I think I messed up the passthru button since it's not supposed to be dark when off. (It's supposed to be brighter like the start button in the first image.)

**Comment by Kuuko-fokkusugaru** [comment]
You can change the icons of each voice if you click on the edit button, look for the voice that you want to change the icon and click the icon which will prompt to search a image. When you add a voice the icon is always blank but your screenshot shows images. Doesn't that means that you already did change their icons??

A darker UI is a good idea so I am in with it. I would like also for the window size to adapt a bit better to the UI's content. It's often smaller than the content which results in navigation bars and me having to resize the window. It's not a huge deal though, only a little detail.

**Comment by Mikey-Mikey** [comment]
The edit button says it's not implemented yet when clicking on it. Btw I'm on the latest version 2.0.58-alpha cuda

**Comment by Kuuko-fokkusugaru** [comment]
How did you add the voices without the edit button? 🤔

**Comment by Mikey-Mikey** [comment]
I used the upload button?
Also to get the images on I changed the .json file for each one manually.

**Comment by Mikey-Mikey** [comment]
I think I said that in the post.

**Comment by Kuuko-fokkusugaru** [comment]
Isn't the upload button the one that you click after you click edit though? I think we are thinking about two different edit buttons. I mean this one:
![Screenshot_20240809-010836106](https://github.com/user-attachments/assets/ea34139d-043b-4dfa-b693-6d8be26e57fe)

**Comment by Mikey-Mikey** [comment]
Oh yea of course I went into that edit one. I mean't the edit button on each model, my bad.

**Comment by Kuuko-fokkusugaru** [comment]
> Oh yea of course I went into that edit one. I mean't the edit button on each model, my bad.


https://github.com/user-attachments/assets/21e36cf5-8cf7-4938-b523-7713bc2e0f1c

**Comment by Mikey-Mikey** [comment]
Bruh I didn't know that that was even there bruh xd.

**Comment by Mikey-Mikey** [comment]
my bad

**Comment by Mikey-Mikey** [comment]
Btw most of the theme I created used #202020 and #000 for the dark color values along with #d3d3d3 for the white text. Just in case you wanted to know. Also I'm guessing that the CSS was auto-generated, if so, what did you use?

**Comment by Kuuko-fokkusugaru** [comment]
> Bruh I didn't know that that was even there bruh xd.

Yeah it took me a bit to figure out the first time hehe

**Comment by Mikey-Mikey** [comment]
Also I'm pretty sure the big image for the selected model is the wrong aspect ratio, it's not square.

**Comment by Mikey-Mikey** [comment]
Fixed it on my end by setting object-fit: contain on it.

**Comment by Mikey-Mikey** [comment]
![image](https://github.com/user-attachments/assets/dee10cba-7e5f-4860-9c9a-1c389d0289fb)

**Comment by w-okada** [comment]
In the latest version v.2.0.60-alpha, we have added support for Dark Mode.
Please give it a try.

Thank you for your continued cooperation.

https://github.com/user-attachments/assets/e2de14d2-1bc6-4f6f-a42b-26beca6a2fdc

**Comment by Kuuko-fokkusugaru** [comment]
Thank you!

**Comment by Mikey-Mikey** [comment]
Thank you so much! I'm now closing this issue as it isn't relevant anymore!
