### ISSUE TITLE
[REQUEST]: Questions about S.thresh and N.gate

### ISSUE THREAD

**Issue by 1N4612** [w-okada/voice-changer#1318]
### In a few words, describe your idea

VCC experience is not as good as MMVC, I guess it might have something to do with n.gate

### More information

My experience with the “MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.18a” version is very good! I think the reason for the good results may be s.thresh, but of course it may not be! But the new VCC isn't as good at real-time voice changes. On the face of it, it's just a change from s.thresh to n.gate, and the actual experience is really quite different, so I really hope you can make VCC a bit better! Please!

**Comment by Kuuko-fokkusugaru** [comment]
That setting controls how loud you have to speak before picking it. It's only a filter to avoid noise and low sounds from being picked and converted by the software.
Whats exactly your issue between the two?
"Not being as good" is a vague explanation. Please provide more details as to what exactly is worse.

**Comment by w-okada** [comment]
no update. close
