### ISSUE TITLE
beatrice_trainer训练报错

### ISSUE THREAD

**Issue by yuanqiyinpin** [w-okada/voice-changer#1326]
### Voice Changer Version

1.5.3.7

### Operational System

win10

### GPU

4090

### CUDA Version

12.1

### Read carefully and check the options

- [X] If you use win_cuda_torch_cuda edition, setup cuda? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use win_cuda edition, setup cuda and cudnn? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use mac edition, client is not launched automatically. Use chrome to open application.?
- [ ] I've tried to change the Chunk Size
- [ ] I've tried to set the Index to zero
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Does pre-installed model work?

No

### Model Type

beatrice_trainer

### Issue Description

  File "/root/beatrice_trainer/beatrice_trainer/__main__.py", line 2657, in <module>
    assert loss_mel.isfinite().all()
AssertionError
root@autodl-container-9682448904-4fcb7b66:~/beatrice_trainer#这是为什么，每次训练到20万步就会出现这个问题

### Application Screenshot

  File "/root/beatrice_trainer/beatrice_trainer/__main__.py", line 2657, in <module>
    assert loss_mel.isfinite().all()
AssertionError
root@autodl-container-9682448904-4fcb7b66:~/beatrice_trainer#这是为什么，每次训练到20万步就会出现这个问题

### Logs on console

  File "/root/beatrice_trainer/beatrice_trainer/__main__.py", line 2657, in <module>
    assert loss_mel.isfinite().all()
AssertionError
root@autodl-container-9682448904-4fcb7b66:~/beatrice_trainer#这是为什么，每次训练到20万步就会出现这个问题

**Comment by Kuuko-fokkusugaru** [comment]
Please, try a more up to date version.
For v1, the latest one is v1.5.3.18a
For v2, at time of writing may be 2.0.60 alpha. V2 also comes with an updated Beatrice version. 
You can download both in the same download link:

https://huggingface.co/wok000/vcclient000/tree/main

**Comment by w-okada** [comment]
Sorry, this is not for beatrcie trainer.
close this issue.
