### ISSUE TITLE
[REQUEST]: I want it to be possible to select any audio in "Merge Lab"

### ISSUE THREAD

**Issue by Rakkyotan** [w-okada/voice-changer#1329]
### In a few words, describe your idea

Add a checklist to the audio you want to synthesize in "Merge Lab"

### More information

Thank you as always.

Currently, when merging audio with "Merge Lab", everything that has been uploaded or "Marged" is targeted.
If you set the voice you do not want to select to "0", an error will occur.
I think it would be possible to merge any audio you want by leaving the audio you don't want to merge as 0, or by using checkboxes, etc.
![スクリーンショット 2024-08-23 101801](https://github.com/user-attachments/assets/42eef682-6d2c-46cd-ac99-ee78ba932905)
![スクリーンショット 2024-08-23 101900](https://github.com/user-attachments/assets/f356e2b7-a843-416e-a00a-df851a23a7c5)

**Comment by w-okada** [comment]
Sorry, this is bug.

I fixed this. 
please try v.2.0.61-alpha

**Comment by Rakkyotan** [comment]
Thank you very much.
It's done
