### ISSUE TITLE
[ISSUE]: CPU being used instead of GPU (WITH VIDEO PROOF)

### ISSUE THREAD

**Issue by RealGSCGAMING** [w-okada/voice-changer#1333]
### Voice Changer Version

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.18a.zip

### Operational System

Windows 11

### GPU

AMD RX 6700 XT

### Read carefully and check the options

- [x] I've tried to Clear Settings
- [X] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

CPU usage spikes while talking and goes down while not talking. GPU usage is a flat line. I have the GPU0 option selected, not CPU, so it should be using my GPU instead of my CPU, but it's not. Please watch the video below where I explain the problem in detail.

#### If the video is muted, you may need to unmute it.

https://github.com/user-attachments/assets/59737ed9-9d99-40e3-822d-22b4aa414831

### Logs on console

C:\Users\Gavin\Documents\VoiceChanger\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0004_t.json
[Voice Changer] download sample catalog. samples_0004_o.json
[Voice Changer] download sample catalog. samples_0004_d.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
[VCClient] wait web server... done 200
[2024-08-29 16:37:59] connet sid : 4fUtPIa4oVJEEGoWAAAC
[2024-08-29 16:37:59] connet sid : n_Hx8A7-h0Z5r1_DAAAD
[Voice Changer] update configuration: modelSlotIndex 1724974682004
Pipeline has been deleted
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\4\added_IVF1170_Flat_nprobe_1_trump_v2.index
Pipeline has been deleted
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\4\added_IVF1170_Flat_nprobe_1_trump_v2.index
Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
[Voice Changer] exporting onnx... gpu_id:0 gpu_mem:0
[Voice Changer] Warning!!! onnx export with float32. maybe size is doubled.
gin_channels: 256 self.spk_embed_dim: 109
============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

paramDict {'voiceChangerType': 'RVC', 'slot': 5, 'isSampleMode': False, 'sampleId': None, 'files': [{'name': 'trump_simple.onnx', 'kind': 'rvcModel', 'dir': ''}], 'params': {}}
RVC:: slotInfo.modelFile trump_simple.onnx
[Voice Changer] ONNX Model: Official v2 like
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='trump_simple', description='', credit='', termsOfUseUrl='', iconFile='', speakers={0: 'target'}, modelFile='trump_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=48000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='', version='v2.1')
[Voice Changer] update configuration: modelSlotIndex 1724974777005
Pipeline has been deleted
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
[Voice Changer] update configuration: tran 1
[Voice Changer] update configuration: tran 2
[Voice Changer] update configuration: modelSlotIndex 1724974821001
Pipeline has been deleted
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
[Voice Changer] update configuration: tran 13
[Voice Changer] update configuration: tran 13
[Voice Changer] update configuration: tran 12
[Voice Changer] update configuration: tran 12
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: tran 9
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: tran 7
[Voice Changer] update configuration: tran 6
[Voice Changer] update configuration: tran 6
[Voice Changer] update configuration: tran 0
[Voice Changer] update configuration: tran 0
[Voice Changer] update configuration: tran 1
[Voice Changer] update configuration: tran 3
[Voice Changer] update configuration: tran 4
[Voice Changer] update configuration: tran 6
[Voice Changer] update configuration: tran 6
[Voice Changer] update configuration: tran 7
[Voice Changer] update configuration: tran 7
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: tran 9
[Voice Changer] update configuration: tran 9
[Voice Changer] update configuration: tran 9
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: modelSlotIndex 1724974880000
Pipeline has been deleted
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
[Voice Changer] update configuration: tran 15
[Voice Changer] update configuration: tran 15
[Voice Changer] update configuration: tran 13
[Voice Changer] update configuration: tran 12
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: tran 9
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: tran 9
[Voice Changer] update configuration: tran 9
[Voice Changer] update configuration: modelSlotIndex 1724974893003
Pipeline has been deleted
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
[Voice Changer] update configuration: tran -1
[Voice Changer] update configuration: tran 0
[Voice Changer] update configuration: tran 2
[Voice Changer] update configuration: tran 4
[Voice Changer] update configuration: tran 4
[Voice Changer] update configuration: tran 5
[Voice Changer] update configuration: tran 5
[Voice Changer] update configuration: tran 6
[Voice Changer] update configuration: tran 7
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: tran 9
[Voice Changer] update configuration: tran 9
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: tran 12
[Voice Changer] update configuration: tran 12
[Voice Changer] update configuration: tran 12
[Voice Changer] update configuration: modelSlotIndex 1724974907002
Pipeline has been deleted
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
[Voice Changer] update configuration: tran -8
[Voice Changer] update configuration: tran -8
[Voice Changer] update configuration: tran -7
[Voice Changer] update configuration: tran -7
[Voice Changer] update configuration: tran -6
[Voice Changer] update configuration: tran -3
[Voice Changer] update configuration: tran -1
[Voice Changer] update configuration: tran 2
[Voice Changer] update configuration: tran 4
[Voice Changer] update configuration: tran 5
[Voice Changer] update configuration: tran 6
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: tran 12
[Voice Changer] update configuration: tran 13
[Voice Changer] update configuration: tran 13
[Voice Changer] update configuration: tran 13
[Voice Changer] update configuration: tran 13
[Voice Changer] update configuration: tran 13
[Voice Changer] update configuration: modelSlotIndex 1724974937001
Pipeline has been deleted
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
[Voice Changer] update configuration: modelSlotIndex 1724975012005
Pipeline has been deleted
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
SlotInfo::: RVCModelSlot(slotIndex=5, voiceChangerType='RVC', name='trump_simple', description='', credit='', termsOfUseUrl='', iconFile='', speakers={'0': 'that one guy'}, modelFile='trump_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=48000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='', version='v2.1')
paramDict {'voiceChangerType': 'RVC', 'slot': 4, 'isSampleMode': False, 'sampleId': None, 'files': [{'name': 'OGegrill.pth', 'kind': 'rvcModel', 'dir': ''}], 'params': {}}
RVC:: slotInfo.modelFile OGegrill.pth
[Voice Changer] Official Model(pyTorch) : v2
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='OGegrill', description='', credit='', termsOfUseUrl='', iconFile='', speakers={0: 'target'}, modelFile='OGegrill.pth', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=False, modelType='pyTorchRVCv2', samplingRate=32000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='', version='v2')
[Voice Changer] update configuration: modelSlotIndex 1724975049004
Pipeline has been deleted
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
Pipeline has been deleted
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
[Voice Changer] exporting onnx... gpu_id:0 gpu_mem:0
[Voice Changer] Warning!!! onnx export with float32. maybe size is doubled.
gin_channels: 256 self.spk_embed_dim: 109
============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

paramDict {'voiceChangerType': 'RVC', 'slot': 4, 'isSampleMode': False, 'sampleId': None, 'files': [{'name': 'dude idk.onnx', 'kind': 'rvcModel', 'dir': ''}], 'params': {}}
RVC:: slotInfo.modelFile dude idk.onnx
[Voice Changer] ONNX Model: Official v2 like
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='dude idk', description='', credit='', termsOfUseUrl='', iconFile='', speakers={0: 'target'}, modelFile='dude idk.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=32000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='', version='v2.1')
[Voice Changer] update configuration: tran 1
[Voice Changer] update configuration: tran 2
[Voice Changer] update configuration: tran 3
[Voice Changer] update configuration: tran 3
[Voice Changer] update configuration: tran 4
[Voice Changer] update configuration: tran 4
[Voice Changer] update configuration: tran 5
[Voice Changer] update configuration: tran 6
[Voice Changer] update configuration: tran 6
[Voice Changer] update configuration: tran 7
[Voice Changer] update configuration: tran 7
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: tran 9
[Voice Changer] update configuration: tran 9
[Voice Changer] update configuration: tran 10
[2024-08-29 16:51:45] connet sid : pLWqmuSipRwnIpB9AAAF
[2024-08-29 16:51:45] connet sid : 5M9A75HuS5z5giT-AAAH
[Voice Changer] update configuration: tran 9
[Voice Changer] update configuration: tran 9
[Voice Changer] update configuration: tran 12
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: modelSlotIndex 1724975521001
Pipeline has been deleted
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
[Voice Changer] update configuration: modelSlotIndex 1724975721003
Pipeline has been deleted
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
[Voice Changer] update configuration: tran 1
[Voice Changer] update configuration: tran 4
[Voice Changer] update configuration: tran 6
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: tran 9
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: tran 12
[Voice Changer] update configuration: tran 12
[Voice Changer] update configuration: tran 12
[Voice Changer] update configuration: tran 13
[Voice Changer] update configuration: tran 13
[Voice Changer] update configuration: tran 13
[Voice Changer] update configuration: tran 15
[Voice Changer] update configuration: tran 15

**Comment by Kuuko-fokkusugaru** [comment]
Did you try switching gpu? I know it should be gpu0 but I recall someone having to switch to gpu1 to make use of their actual gpu.

If that doesn't work, and considering that v1 is pretty much deprecated, you could try v2 from the following link and report back your cpu and gpu usage to compare the two.

https://huggingface.co/wok000/vcclient000/tree/main

**Comment by RealGSCGAMING** [comment]
Thank you for your help. V2 is reporting significantly lower CPU usage (and runs faster). I will send a screenshot when I get back to my PC. However, I can’t select my GPU in the menu. This is likely due to the fact that it’s designed for NVIDIA GPUs, but if there’s something that I’m doing wrong thats causing the GPU to not show up, please let me know! (I downloaded the latest cuda version)

**Comment by Kuuko-fokkusugaru** [comment]
Please, download the version vcclient_win_std_2.0.61-alpha.zip which doesn't rely on CUDA.

**Comment by RealGSCGAMING** [comment]
With that version, my GPU is now being used properly and all settings are available. Thank you again for your help!
