### ISSUE TITLE
[ISSUE for v2]: Hi, I got a warning message on Cmd, can you look at it?

### ISSUE THREAD

**Issue by 4i0i062** [w-okada/voice-changer#1334]
### Voice Changer Version

vcclient_win_cuda_2.0.61-alpha

### Operational System

windows 10

### GPU

Nvidia Geforce rtx 3060

### CUDA Version

vcclient_win_cuda_2.0.61-alpha

### Read carefully and check the options

- [ ] If you use win_cuda_torch_cuda edition, setup cuda? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use win_cuda edition, setup cuda and cudnn? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use mac edition, client is not launched automatically. Use chrome to open application.?
- [ ] I've tried to change the Chunk Size
- [ ] I've tried to set the Index to zero
- [ ] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Does pre-installed model work?

No

### Model Type

RVC rmvpe

### Issue Description

![cmd](https://github.com/user-attachments/assets/92bf3c88-f6d4-44b1-8ee9-efbc0c5ccae2)

First of all, thank you very much for adding rmvpe. I bow down and sincerely thank you

When I set the pth and index of the learned model and run the client, 

I see such a message in the cmd window, is there any problem?

And once again, thank you so much for adding rmvpe

### Logs on console

![1](https://github.com/user-attachments/assets/6fe64206-2c60-49ab-b2a4-1122c9285476)
![2](https://github.com/user-attachments/assets/40af8d40-2c21-40d9-97b8-f625d1a93f4d)
![3](https://github.com/user-attachments/assets/093cadb0-ffe0-46e1-9374-1755ed05e35e)
![4](https://github.com/user-attachments/assets/0e13e0a7-197b-402f-88ee-cd2e26b6d552)

**Comment by Kuuko-fokkusugaru** [comment]
Did you try decompressing to a new folder and trying to use the default models without uploading new ones? Like don't change much settings other than input and output and give it a try using rmvpe_onnx with a default model. Then try using rmvpe with the same model. If both works, try now uploading your own model. Then we can identify if the issue is a general one or if it's related with importing models or maybe that one specific model.

**Comment by 4i0i062** [comment]
As you said, when I used the basic model only in the first state, the cmd window didn't get an error message. Then, when I added the model I was using, I got an error message in the cmd window. When I checked, it was not only in win_cuda_2.0.61, but also in win_cuda_2.0.60. The error message appears, but it works for now, is there any problem?

**Comment by 4i0i062** [comment]
As you said, when I used the base model only in the first state, the cmd window didn't get an error message. Then, when I added the model I was using, I got an error message in the cmd window. When I checked, it was not only in win_cuda_2.0.61, but also in win_cuda_2.0.60. The error message appears, but it works for now. The model I used called the same model that I've been using since v.1.5.3.18a

**Comment by Kuuko-fokkusugaru** [comment]
I am not sure about that error. If it works then that's good! Let's wait for @w-okada answer to your question.

**Comment by 4i0i062** [comment]
Thanks

**Comment by w-okada** [comment]
There's no issue if this message is displayed. Please ignore it.
