### ISSUE TITLE
Remote use in Colab, but browser is heavy. Colabで遠隔使用しているが、ブラウザが重い。

### ISSUE THREAD

**Issue by Koikaiko** [w-okada/voice-changer#1338]
Thank you for all your help. It is very helpful.

First of all, I am not a programmer.
### Why is the vc-client so heavy?
I use vc-client in Colaboratory to VTuber, and the CPU usage used to send and receive audio in the browser is more than 60% of that compared to the VTuber app (a somewhat heavy app running image recognition and 3D). (This is not the entire browser process, only the vc-client.)
I have tried various versions, browsers and environments, but all with similar results.

Why does it take so much CPU load to just send and receive audio?

Is this a problem that only occurs to me in the first place?
### Also, is there any way to make it run a little lighter?
If there is a possibility to lighten the load, I would like to try any method.

Best regards.

Translated by DeepL

# Original in Japanese
## Colabで遠隔使用しているが、ブラウザが重い。
いつもありがとうございます。大変助かっています。

まず、私はプログラマーではありません。
### vc-clientはなぜこんなに重いのですか？
私はVTuberをするのにColaboratoryでvc-clientを使っているのですが、ブラウザで音声を送受信するのに使うCPU使用率がVTuberアプリ(画像認識や3Dを動かす多少重いアプリ)と比べてその60%以上になります。(ブラウザ全体のプロセスではなく、vc-clientのみのプロセスです。)
バージョンやブラウザ、環境は色々試しましたが、どれも同様の結果でした。

ただの音声の送受信にここまでCPU負荷がかかるのはなぜですか？

そもそもこれは私だけに生じている問題ですか？
### また、少しでも動作軽くする方法はありませんか？
軽くできる可能性があるのであれば、どんな方法であっても試してみたいです。
よろしくお願いします。

**Comment by Kuuko-fokkusugaru** [comment]
Which version of the software?
Do you run RVC software on your computer or through Google Colab?

**Comment by Koikaiko** [comment]
Sorry. Self-resolved.
I was using the latest version of v1 on Colab, but when I used v2 it was lighter.
Thank you so much.

失礼しました。自己解決しました。
Colabでv1の最新版を使っていたのですが、v2を使ったら軽くなりました。
本当にありがとうございます。

**Comment by w-okada** [comment]
Thanks.

ご連絡、ありがとうございます。今後ともよろしくお願いします。
