### ISSUE TITLE
[ISSUE for v2]: Error:1 validation error for VoiceChangerConfiguration

### ISSUE THREAD

**Issue by cookienommienom** [w-okada/voice-changer#1352]
### Voice Changer Version

vcclient_win_std_2.0.61-alpha.zip

### Operational System

Windows 10

### GPU

RTX 4090

### CUDA Version

Build cuda_11.8.r11.8/compiler.31833905_0

### Read carefully and check the options

- [X] If you use win_cuda_torch_cuda edition, setup cuda? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [X] If you use win_cuda edition, setup cuda and cudnn? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use mac edition, client is not launched automatically. Use chrome to open application.?
- [ ] I've tried to change the Chunk Size
- [ ] I've tried to set the Index to zero
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Does pre-installed model work?

No

### Model Type

RVC

### Issue Description

Trying to start via start_http.bat and it results in the errors shown in the logs section of this result. No GUI appears

### Application Screenshot

![a88dbdb157d14d76dab6c2608b316aac](https://github.com/user-attachments/assets/bb5257dc-04f1-44b3-a367-22d7ae011e0a)

### Logs on console

 Application | http://localhost:18000
 Log(rich)   | http://localhost:18000/?app_mode=LogViewer
 Log(text)   | http://localhost:18000/vcclient.log
 API         | http://localhost:18000/docs
 License(js) | http://localhost:18000/licenses-js.json
 License(py) | http://localhost:18000/licenses-py.json
----------------------------------------------------------
Please press Ctrl+C once to exit vcclient.
Error:1 validation error for VoiceChangerConfiguration
  Invalid JSON: expected value at line 1 column 1 [type=json_invalid, input_value='\x00\x00\x00\x00\x00\x00...x00\x00\x00\x00\x00\x00', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/json_invalid
terminate vcclient...
vcclient is terminating...
vcclient is terminated.[18000]
msg:  Error:1 validation error for VoiceChangerConfiguration
  Invalid JSON: expected value at line 1 column 1 [type=json_invalid, input_value='\x00\x00\x00\x00\x00\x00...x00\x00\x00\x00\x00\x00', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/json_invalid

**Comment by cookienommienom** [comment]
Nevermind, the settings file decided to make itself empty for some odd reason. deleting the empty settings file fixed it.

**Comment by Kuuko-fokkusugaru** [comment]
> Nevermind, the settings file decided to make itself empty for some odd reason. deleting the empty settings file fixed it.

I'd recommend, having an nvidia card, to use the CUDA version instead.
