### ISSUE TITLE
[REQUEST]: XLR or USB Mic for Higher Quality using RVC?

### ISSUE THREAD

**Issue by kiraraenjoyer** [w-okada/voice-changer#1359]
### In a few words, describe your idea

Does anyone know the difference in quality between XLR and USB mics for AI RVC?

### More information

I couldn't find any information regarding how USB and XLR mics perform with AI compared against one another. What might be the better option normally might not be the case with using AI or if there is any difference. I wasn't sure and this seemed to be the more appropriate place to ask this question. 

I'm guessing that XLR might have better interpretation from being analog and having the ability to EQ your voice before using RVC?

Thank you for your patience, I know this place isn't exactly meant for these questions but I didn't know where else to be honest...

**Comment by Kuuko-fokkusugaru** [comment]
RVC replaces what you say so the quality of the mic isn't much important. As long as it can understand what you say without glitches or noises, the result will be the same from a cheap mic than from the highest quality mic.

**Comment by kiraraenjoyer** [comment]
> RVC replaces what you say so the quality of the mic isn't much important. As long as it can understand what you say without glitches or noises, the result will be the same from a cheap mic than from the highest quality mic.

oh ok cool, I thought the difference in information sent from analog vs digital would change something. I'm still learning about RVC and I didn't want to buy something just to test out my theories. I'm pretty happy with what I got but I'm always looking for ways to make it better.

Your feedback was helpful thank you :3

**Comment by Kuuko-fokkusugaru** [comment]
Usually a higher quality mic also picks the slightly little sound around. RVC tries to translate every sound into phonemes. So people that have these types of mics are more prone to get sounds like breathing, typing, etc into RVC which will convert them into sounds made with mouth lol. It's easy to fix with noise filters so it only picks what's needed but it would be a waste of money unless you already own one. I myself just use the one that comes with my headset which is good but not professional grade at all and it works perfectly fine.
The only situation where a mic would be "bad" is one where the quality would be bad enough to create extra sounds like glitches or distort your voice too much to be understandable.
I hope you enjoy RVC and let me know if you need something else :3
