### ISSUE TITLE
[ISSUE for v2]: Windows hang indefinitely when allowing domain networks to access this app

### ISSUE THREAD

**Issue by jntesai** [w-okada/voice-changer#1360]
### Voice Changer Version

vcclient_win_cuda_2.0.61-alpha.zip

### Operational System

Windows 11

### GPU

RTX A1000

### CUDA Version

12.6

### Read carefully and check the options

- [X] If you use win_cuda_torch_cuda edition, setup cuda? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [X] If you use win_cuda edition, setup cuda and cudnn? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use mac edition, client is not launched automatically. Use chrome to open application.?
- [ ] I've tried to change the Chunk Size
- [ ] I've tried to set the Index to zero
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Does pre-installed model work?

No

### Model Type

RVC

### Issue Description

Windows hang indefinitely when allowing domain networks to access this app

### Logs on console

The system detected an overrun of a stack-based buffer in this application. This overrun could potentially allow a malicious user to gain control of this application.

**Comment by w-okada** [comment]
It is probably due to the environment of your PC or the network environment. We cannot address this on our end.
