### ISSUE TITLE
[ISSUE for v2]: 設定を初期化したらモデルデータが消えた

### ISSUE THREAD

**Issue by HaleyHalcyon** [w-okada/voice-changer#1364]
### Voice Changer Version

vcclient_win_cuda_2.0.61-alpha.zip

### Operational System

Windows 10 

### GPU

NVIDIA GeForce GTX 1080

### CUDA Version

?

### Read carefully and check the options

- [ ] If you use win_cuda_torch_cuda edition, setup cuda? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [X] If you use win_cuda edition, setup cuda and cudnn? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use mac edition, client is not launched automatically. Use chrome to open application.?
- [ ] I've tried to change the Chunk Size
- [ ] I've tried to set the Index to zero
- [ ] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Does pre-installed model work?

No

### Model Type

RVC

### Issue Description

Native Client の "initialize" ボタンを押したら、デフォルトのモデルも、追加したモデルも、model_dirディレクトリー内のファイル自体消えてしまいました。

### Application Screenshot

![image](https://github.com/user-attachments/assets/3179eda3-45df-4ef7-983b-2d3709df955b)

### Logs on console

D:\Downloads\MMVCServerSIO>main.exe cui --https true --no_cui True
checking the modules...

                          vcclient

--------------------------------------------------------------
 Application | https://192.168.0.10:18000
 Log(rich)   | https://192.168.0.10:18000/?app_mode=LogViewer
 Log(text)   | https://192.168.0.10:18000/vcclient.log
 API         | https://192.168.0.10:18000/docs
 License(js) | https://192.168.0.10:18000/licenses-js.json
 License(py) | https://192.168.0.10:18000/licenses-py.json
--------------------------------------------------------------
Please press Ctrl+C once to exit vcclient.

**Comment by Kuuko-fokkusugaru** [comment]
Decompress to a new folder, open start_http.bat, and wait for the downloads to finish. Add more models through the UI with the upload button.

**Comment by HaleyHalcyon** [comment]
> Decompress to a new folder, open start_http.bat, and wait for the downloads to finish. Add more models through the UI with the upload button.

How would that restore my deleted model?

**Comment by HaleyHalcyon** [comment]
> I have never had issues with RVC deleting my models but, maybe they are still in the models' folder? For me, they are inside of "dist\main\model_dir". There are folders with numbers, each number is one of the models. Hopefully, your models have been deleted from the configuration file, and not from the folder.

The contents of that folder got cleared. The model is now gone for good then. Okay.

**Comment by w-okada** [comment]
I’m afraid you are right. Initialization is just like that, I believe.
