### ISSUE TITLE
[ISSUE]: electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by TH36R0N008** [w-okada/voice-changer#1368]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.2.9e

### Operational System

Windows 10

### GPU

NVIDIA GeForce GTX 1060 6 GB

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

I am doing everything right and it still doesn't want to run properly.

### Application Screenshot

![image](https://github.com/user-attachments/assets/b4f528f3-496f-4cbb-ab36-ff827f3fdab5)

### Logs on console

![image](https://github.com/user-attachments/assets/82839225-4500-4b79-83aa-57cce72dc4fb)

**Comment by Kuuko-fokkusugaru** [comment]
Update your RVC version. That one is super ancient.

**Comment by TH36R0N008** [comment]
> Update your RVC version. That one is super ancient.

How do I do that?

**Comment by Kuuko-fokkusugaru** [comment]
You can head to the downloads page or just use this link where you can find the latest versions for v1 and v2:

https://huggingface.co/wok000/vcclient000/tree/main
