### ISSUE TITLE
[REQUEST]: Eminem 

### ISSUE THREAD

**Issue by Waran-kd1** [w-okada/voice-changer#1376]
### In a few words, describe your idea

Say singers song

### More information

![Screenshot_2024-10-09-17-26-03-857_com google android googlequicksearchbox](https://github.com/user-attachments/assets/7f223eb4-e853-4dd8-9cb8-ea6e97325196)

https://github.com/user-attachments/assets/b347984e-7d8b-40b5-819e-97ec6124b668

**Comment by Kuuko-fokkusugaru** [comment]
This is not a place to make requests. If you want a song with RVC, do it yourself or request it somewhere else.
