### ISSUE TITLE
start_http.bat not starting 

### ISSUE THREAD

**Issue by kapl228** [w-okada/voice-changer#1383]
### Voice Changer Version

d

### Operational System

win 11 

### GPU

 rtx 2080 super

### CUDA Version

ddddd

### Read carefully and check the options

- [X] If you use win_cuda_torch_cuda edition, setup cuda? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [X] If you use win_cuda edition, setup cuda and cudnn? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use mac edition, client is not launched automatically. Use chrome to open application.?
- [ ] I've tried to change the Chunk Size
- [ ] I've tried to set the Index to zero
- [x] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Does pre-installed model work?

No

### Model Type

c

### Issue Description

when i try to open the file it opens the commender for a split half a sec and just closes and i cant find a way to fix it 

### Application Screenshot

s

### Logs on console

s

**Comment by Kuuko-fokkusugaru** [comment]
Please, kindly specify the version.

**Comment by w-okada** [comment]
no response.
