### ISSUE TITLE
Index doesn't work

### ISSUE THREAD

**Issue by yukiarimo** [w-okada/voice-changer#1385]
Only running model (both RVC and ONNX) without index work

**Comment by Kuuko-fokkusugaru** [comment]
Does your model contain a valid index file?

**Comment by yukiarimo** [comment]
Yes, it does. It works in all RVC pipelines, except for the w-okada for the real-time stuff :(

**Comment by asr-aditya** [comment]
@yukiarimo how did you check that the index file is not working?

**Comment by Kuuko-fokkusugaru** [comment]
It's hard to help with so much info lacking. When you open an issue you get a form to fill with necessary info to help you which has been skipped. There is no version number, log, screenshot, details of the model used, GPU and CPU, operating system, etc. Kindly provide all that and a detailed explanation of what exactly doesn't work.

**Comment by w-okada** [comment]
no respinse.
