### ISSUE TITLE
[ISSUE]: Voice changer works but won't project through the mic

### ISSUE THREAD

**Issue by RubyTheKnife** [w-okada/voice-changer#1389]
### Voice Changer Version

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.18a

### Operational System

Windows 11

### GPU

Nvidia GEFORCE 4070 SUPER

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

I had download this because a friend showed me, it's great and the voice changer works perfectly... But the problem I'm having is that it doesn't project through my mic. I can hear myself with the voice changer but the voice changer isn't actually going through the mic I select, I've tried reinstalling, waiting for updates, gone through all the settings and sat through almost every tutorial and I cannot find a solution, I even tried installing Voice Meter but that was to no avail.

### Logs on console

C:\Users\skull\Downloads\MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.18a\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0004_t.json
[Voice Changer] download sample catalog. samples_0004_o.json
[Voice Changer] download sample catalog. samples_0004_d.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
Try loading... model_dir\4\added_IVF4551_Flat_nprobe_1_GawrGura_v2.index
[VCClient] wait web server... done 200
[2024-10-27 01:11:39] connet sid : Cgwno3ULfdqkcwMfAAAC
[2024-10-27 01:11:39] connet sid : 7OvZixfnuLlWzSQCAAAD
[Voice Changer] update configuration: enableServerAudio 0
[Voice Changer] update configuration: enableServerAudio 1
[Voice Changer] update configuration: serverAudioStated 1
Devices:
  [Input]: ServerAudioDevice(kind='audioinput', index=3, name='Microphone (SYN Pro Air)', hostAPI='MME', maxInputChannels=2, maxOutputChannels=0, default_samplerate=44100.0, available_samplerates=[]) None
  [Output]: ServerAudioDevice(kind='audiooutput', index=6, name='Speakers (SYN Pro Air)', hostAPI='MME', maxInputChannels=0, maxOutputChannels=2, default_samplerate=44100.0, available_samplerates=[]) None
  [Monitor]: None None
Sample Rate:
  [Model]: 32000
  [Input]: 48000 -> True
  [Output]: 48000 -> True
[Voice Changer] server audio performance [0, 0, 0, 0]
                status: started:1, model_sr:32000, chunk:384
                input  : id:3, sr:48000, ch:2
                output : id:6, sr:48000, ch:2
[Voice Changer] server audio performance [0, 0, 0, 0]
                status: started:1, model_sr:32000, chunk:384
                input  : id:3, sr:48000, ch:2
                output : id:6, sr:48000, ch:2
[Voice Changer] server audio performance [0, 0, 0, 0]
                status: started:1, model_sr:32000, chunk:384
                input  : id:3, sr:48000, ch:2
                output : id:6, sr:48000, ch:2
[Voice Changer] server audio performance [0, 0, 0, 0]
                status: started:1, model_sr:32000, chunk:384
                input  : id:3, sr:48000, ch:2
                output : id:6, sr:48000, ch:2
[Voice Changer] server audio performance [0, 0, 0, 0]
                status: started:1, model_sr:32000, chunk:384
                input  : id:3, sr:48000, ch:2
                output : id:6, sr:48000, ch:2
[Voice Changer] update configuration: serverAudioStated 0
[Voice Changer] server audio performance [0, 0, 0, 0]
                status: started:0, model_sr:32000, chunk:384
                input  : id:3, sr:48000, ch:2
                output : id:6, sr:48000, ch:2
serverAudioStarted Changed: 0

**Comment by Kuuko-fokkusugaru** [comment]
Show screenshot of your configuration please.
Also, download the proper version, the CUDA one and not the directML version since you will use your GPU.

**Comment by RubyTheKnife** [comment]
I have now downloaded the right version, unfortunately it didn't fix the issue but here's this
![3aff828ba27aa19a17fdb68abbc0b980](https://github.com/user-attachments/assets/868f7eaf-a965-4bd1-8695-c6e2b61c485f)

**Comment by Kuuko-fokkusugaru** [comment]
It's not an issue, it is just wrongly configured.
Output is where you would put voice meter output so the audio goes through voice meter input (though, all VB software is known to give issues with certain games and Discord so I would recommend the free Lite version of VAC (Virtual Audio Cable instead). If you want to listen to yourself, use monitor instead. I am not sure if you are intentionally running it in server mode, but I guess you are not, given the other wrong configurations. I would suggest using it in client mode instead so you don't get headaches with audio issues coming from other applications and games.

**Comment by w-okada** [comment]
no response.
