### ISSUE TITLE
[ISSUE]: Web server is not opening

### ISSUE THREAD

**Issue by mrrewilh** [w-okada/voice-changer#1403]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.18a.zip

### Operational System

Windows 10

### GPU

Geforce RTX 4060

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [x] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

Web server is not opening, GUI is visible but buttons, images aren't.

### Application Screenshot

![image](https://github.com/user-attachments/assets/900faa65-0275-4f7c-b4d6-4da089ddfa84)

### Logs on console

[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] Web Server Launch Exception, Expecting value: line 1 column 1 (char 0)
[VCClient] wait web server...10 http://127.0.0.1:18888/
[VCClient] wait web server...20 http://127.0.0.1:18888/
[VCClient] wait web server...30 http://127.0.0.1:18888/
[VCClient] wait web server...40 http://127.0.0.1:18888/
[VCClient] wait web server...50 http://127.0.0.1:18888/
[VCClient] wait web server...60 http://127.0.0.1:18888/
[VCClient] wait web server...70 http://127.0.0.1:18888/
[VCClient] wait web server...80 http://127.0.0.1:18888/
[VCClient] wait web server...90 http://127.0.0.1:18888/
[VCClient] wait web server...100 http://127.0.0.1:18888/
[VCClient] wait web server...110 http://127.0.0.1:18888/
[VCClient] wait web server...120 http://127.0.0.1:18888/
[VCClient] wait web server...130 http://127.0.0.1:18888/
[VCClient] wait web server...140 http://127.0.0.1:18888/
[VCClient] wait web server...150 http://127.0.0.1:18888/
[VCClient] wait web server...160 http://127.0.0.1:18888/

**Comment by Kuuko-fokkusugaru** [comment]
Make sure that firewall isn't blocking the application. Add it to the exception (the main executable file, not the bat).
Run the software through start_http.bat. If still does not work, download the software again but this time decompress it in a new folder inside of the root of a driver other than C (if possible).

**Comment by mrrewilh** [comment]
The application is in firewall exceptions. I ran the software from the "start_http.bat" file. It did not solve the problem.

**Comment by mrrewilh** [comment]
I tried to decompress and run software inside of the root of a driver other than C. It didnt solve the problem too

**Comment by Kuuko-fokkusugaru** [comment]
Download the latest v2
