### ISSUE TITLE
[ISSUE for v2]: Even if I raise the pitch and format of “Beatrice”, the voice is not converted.

### ISSUE THREAD

**Issue by Rakkyotan** [w-okada/voice-changer#1404]
### Voice Changer Version

vcclient_win_cuda_2.0.72-beta

### Operational System

Windows 11

### GPU

NVIDIA Geforce RTX 4070 Ti

### CUDA Version

12.6

### Read carefully and check the options

- [X] If you use win_cuda_torch_cuda edition, setup cuda? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [X] If you use win_cuda edition, setup cuda and cudnn? [see here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements)
- [ ] If you use mac edition, client is not launched automatically. Use chrome to open application.?
- [X] I've tried to change the Chunk Size
- [X] I've tried to set the Index to zero
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Does pre-installed model work?

YES

### Model Type

2.0.69

### Issue Description

Regarding “Beatrice,” in the previous version, the voice changed when you moved the pitch or formant, but in this version, there was no reaction at all when you moved the bar.

### Logs on console

No　log

**Comment by w-okada** [comment]
Oh, this is a bug. I'll fix it soon. Thanks for reporting it.

**Comment by Rakkyotan** [comment]
It had been fixed.
