### ISSUE TITLE
[ISSUE]: Stuttering Problems (When using voice calls, others)

### ISSUE THREAD

**Issue by Bitroast** [w-okada/voice-changer#1418]
### Voice Changer Version

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.18a.zip

### Operational System

Windows 10

### GPU

AMD Radeon RX 6600

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [x] Sample/Default Models are working
- [x] I've tried to change the Chunk Size
- [x] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

When I record audio from within the program, it works completely smoothly. There are no issues at all. However, when I speak live on Discord or any other application, I experience a lot of stutter problems.

### Logs on console

C:\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0004_t.json
[Voice Changer] download sample catalog. samples_0004_o.json
[Voice Changer] download sample catalog. samples_0004_d.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] model slot is changed -1 -> 7
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:False, onnx_device:CPU-DML)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
Try loading... model_dir\7\added_IVF1751_Flat_nprobe_1_VenomMovieRetrainV1_v2 (1).index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x000001951FEB0B80>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000019522FC8A30>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x0000019522FC8A60>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings serverReadChunkSize:192
[Voice Changer][RVC]: update_settings extraConvertSize:32768
[Voice Changer][RVC]: update_settings f0Detector:rmvpe_onnx
[Voice Changer][RVC]: update_settings silentThreshold:0
[Voice Changer][RVC]: update_settings enableServerAudio:0
[Voice Changer][RVC]: update_settings serverInputDeviceId:24
[Voice Changer][RVC]: update_settings serverOutputDeviceId:19
[Voice Changer][RVC]: update_settings serverMonitorDeviceId:-1
[Voice Changer][RVC]: update_settings serverAudioSampleRate:96000
[Voice Changer][RVC]: update_settings modelSlotIndex:1734468559007
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2024-12-18 19:20:32] connet sid : 92fsgNhItUW9vUvRAAAC
[2024-12-18 19:20:32] connet sid : lH5Z7CC2UgqgIS9cAAAD

**Comment by Bitroast** [comment]
But there's no stuttering issue with the default Japanese voices in the program. When I listen to my own voice through Discord, I can hear it without any stutters.

**Comment by Bitroast** [comment]
But, for example, when I tried the Venom voice model, the female voice model I downloaded from somewhere else works fine in the program's recording. However, it always glitches on Discord or other programs.

**Comment by Bitroast** [comment]
https://streamable.com/in1m4v

**Comment by Kuuko-fokkusugaru** [comment]
When you use a voice changer, you need to account for a couple of things on the final end side, which in this case is discord.
Disable any noise reduction, you don't need it since the audio output shouldn't have noise.
Disable any kind of sound or noise threshold. The voice changer volume is very monotonous you don't need to filter small noises or low volume dialogues from the background so reduce this to the minimum until is pretty much turned off.
If, after all this still happens, uninstall vb cable as it doesn't work properly with discord. The reason why some voices works and some doesn't it's because vb cable isn't good at managing different frequencies properly. Instead, install virtual audio cable (VAC). There is a lite version which is free (not the demo version). It works the same as vb cable except that it works properly and you haven't to configure or tweak anything.
Let me know if that fixes your issue.

**Comment by Bitroast** [comment]
> When you use a voice changer, you need to account for a couple of things on the final end side, which in this case is discord. Disable any noise reduction, you don't need it since the audio output shouldn't have noise. Disable any kind of sound or noise threshold. The voice changer volume is very monotonous you don't need to filter small noises or low volume dialogues from the background so reduce this to the minimum until is pretty much turned off. If after all this still happens, uninstall vb cable as it doesn't work properly with discord. The reason why some voices works and some doesn't it's because vb cable isn't good at managing different frequencies properly. Instead, install virtual audio cable (VAC). There is a lite version which is free (not the demo version). It works the same as vb cable except that it works properly and you haven't to configure or tweak anything. Let me know if that fixes your issue.

Actually, I had done everything you said, but the issue wasn't resolved. However, I tested the one in the link below, and this problem was solved.
https://github.com/deiteris/voice-changer

**Comment by Bitroast** [comment]
fixed when im using this;
https://github.com/deiteris/voice-changer
