### ISSUE TITLE
How can I train a voice in a different language?

### ISSUE THREAD

**Issue by pierluigizagaria** [w-okada/voice-changer#143]
Hi, I want to have fun with voice-conversion technology. 
Your project seems to be the easiest one to set up.
However I don't understand how I could "train" a voice. 
Can I use ~20 minutes of recording in a different language to actually get a good result with this tool? 

Sorry for my ignorance, I'm a simple developer with no AI knowledge. There are some closed-source real-time conversion tools, but I want to use an open source one.

**Comment by w-okada** [comment]
I have never tried other than japanese, but MMVC is only 100 sentence is OK for training for japanese. I don't know but, it maybe ok for other language. MMVC community have slack server and for english channel. How about visit it?

https://github.com/isletennos/MMVC_Trainer

**Comment by w-okada** [comment]
And this repository not for training AI model. So I couldn't answer anything difinitly.

**Comment by w-okada** [comment]
OK, I found you asking at MMVC slack server. close in here.
