### ISSUE TITLE
Conda installation instructions outdated

### ISSUE THREAD

**Issue by Tenkoni** [w-okada/voice-changer#146]
Hi. I've been trying to install through Conda but the video became outdated after a refactor.
I found a requirements.txt inside the server folder, but after installing them there are still missing dependencies and is not possible to run the server.

Is it possible to get an updated requirements.txt or some short instructions on the voice-changer installation? (assuming conda has already been setup).

Thanks!

**Comment by w-okada** [comment]
Sorry for the long wait. We are pleased to inform you that the documentation has been updated.

https://github.com/w-okada/voice-changer/blob/master/README_dev_en.md

https://github.com/w-okada/voice-changer/blob/master/README_dev_ja.md
