### ISSUE TITLE
v.1.5.1.9 onnxExecutionProvider is not mutalbe variable or unknown variable

### ISSUE THREAD

**Issue by yeaherer** [w-okada/voice-changer#148]
MMVCServerSIO_win_onnxdirectML_cuda_v.1.5.1.9
MMVCServerSIO_win_onnxgpu_cuda_v.1.5.1.9
--
tested both versions above
Using ONNX to report an error when the GUI starts
--
Device: RTX3090 driver version 528.02
System: win11
--
start_https_so-vits-svc_40v2.bat
--
post_update_setteings framework ONNX
post_update_setteings onnxExecutionProvider CUDAExecutionProvider
onnxExecutionProvider is not mutalbe variable or unknown variable!

**Comment by w-okada** [comment]
Currently for 4.0v2, onnx is not supported. Because some of opts used in model is not supported in onnx. 
I have walk around but it is dirty way, so currently I have no plan to release it. Please wait onnx support it.

unsupported ops: isftf

https://github.com/onnx/onnx/issues/4777
