### ISSUE TITLE
[Help] wav size not multiple of hopsize / Passthrough is not supported, GL is disabled, ANGLE is

### ISSUE THREAD

**Issue by TwistedTale** [w-okada/voice-changer#150]
OS Version: W10 22H2

GPU: RTX 3090 531.41 Cuda 12.1

Python version: 3.10.9

PyTorch version: 1.13.1+cu117

When trying to start the program, I get this error:

```
INFO:root:Loaded checkpoint 'C:\Users\xxxx\AppData\Local\Temp\tmppp1pr5vh\upload_dir\G_63200.pth' (iteration 1037)
Generated Strengths: for prev:(1024,), for cur:(1024,)
 !!! !!! !!! wav size not multiple of hopsize: 29.3984375
 !!! !!! !!! wav size not multiple of hopsize: 58.796875
 !!! !!! !!! wav size not multiple of hopsize: 88.1953125
[8928:0401/003325.817:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
```
 
I m not sure what I m doing wrong, I tried multiple different models and the result is the same. I m suspecting input samplerate but I tried changing them and nothing.

**Comment by w-okada** [comment]
That message is not severe. It appears when there is not enough data needed to begin conversion. If you wait a little bit, it will be solved (although it won't disappear from the console). Is the voice conversion being done?

**Comment by TwistedTale** [comment]
I did try to wait it out and nothing happens

**Comment by TwistedTale** [comment]
```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-263' coro=<AsyncServer._handle_event_internal() done, defined at socketio\asyncio_server.py:522> exception=AttributeError("'SoVitsSvc40' object has no attribute 'hps'")>
Traceback (most recent call last):
  File "socketio\asyncio_server.py", line 524, in _handle_event_internal
  File "socketio\asyncio_server.py", line 569, in _trigger_event
  File "socketio\asyncio_namespace.py", line 37, in trigger_event
  File "sio\MMVC_Namespace.py", line 34, in on_request_message
  File "voice_changer\VoiceChangerManager.py", line 36, in changeVoice
  File "voice_changer\VoiceChanger.py", line 159, in on_request
  File "voice_changer\SoVitsSvc40\SoVitsSvc40.py", line 189, in get_processing_sampling_rate
AttributeError: 'SoVitsSvc40' object has no attribute 'hps'
```

Ok I just tried it again doing the same thing as before, now I m getting this

**Comment by w-okada** [comment]
please set content vec model on your folder as the same place of the .bat.

```
To use so-vits-svc 4.0/so-vits-svc 4.0v2 or tsukuyomi-chan, you need the content vec model. Please download the ContentVec_legacy 500 model from [this repository](https://github.com/auspicious3000/contentvec), and place it in the same folder as startHttp_xxx.command or start_http_xxx.bat to run.
```

**Comment by TwistedTale** [comment]
> I did try to wait it out and nothing happens

I m really sorry for the message spam, but I just tried really waiting it out, the voice changer does actually work, however, the output is completely illegible with extremely extremely heavy digital noise whiles having a delay of 20 to infinite seconds, I m also getting this when it starts "working"

```
post request handler error
Traceback (most recent call last):
  File "engineio\asyncio_server.py", line 289, in handle_request
  File "engineio\asyncio_socket.py", line 109, in handle_post_request
  File "engineio\payload.py", line 13, in __init__
  File "engineio\payload.py", line 44, in decode
ValueError: Too many packets in payload
ERROR:engineio.server:post request handler error
Traceback (most recent call last):
  File "engineio\asyncio_server.py", line 289, in handle_request
  File "engineio\asyncio_socket.py", line 109, in handle_post_request
  File "engineio\payload.py", line 13, in __init__
  File "engineio\payload.py", line 44, in decode
ValueError: Too many packets in payload
<class 'str'>
51-/test,["request_message",[1680332575693,{"_placeholder":true,"num":0}]]
message async handler error
Traceback (most recent call last):
  File "engineio\asyncio_server.py", line 456, in _trigger_event
  File "socketio\asyncio_server.py", line 592, in _handle_eio_message
  File "socketio\packet.py", line 43, in __init__
  File "socketio\packet.py", line 77, in decode
ValueError: invalid literal for int() with base 10: b'\xe9'
ERROR:engineio.server:message async handler error
Traceback (most recent call last):
  File "engineio\asyncio_server.py", line 456, in _trigger_event
  File "socketio\asyncio_server.py", line 592, in _handle_eio_message
  File "socketio\packet.py", line 43, in __init__
  File "socketio\packet.py", line 77, in decode
ValueError: invalid literal for int() with base 10: b'\xe9'
```

thank you so much for your patience

**Comment by TwistedTale** [comment]
> please set content vec model on your folder as the same place of the .bat.
> 
> ```
> To use so-vits-svc 4.0/so-vits-svc 4.0v2 or tsukuyomi-chan, you need the content vec model. Please download the ContentVec_legacy 500 model from [this repository](https://github.com/auspicious3000/contentvec), and place it in the same folder as startHttp_xxx.command or start_http_xxx.bat to run.
> ```

I already did that unfortunately

**Comment by w-okada** [comment]
Which file did you download?

**Comment by TwistedTale** [comment]
> Which file did you download?

The third one, legacy 500

**Comment by w-okada** [comment]
sorry, I meant file of vcclient. which one?

Is framework  "ONNX(cpu,cuda), PyTorch(cpu,cuda)" ?  please tell me file name you downloaded from this repo.

**Comment by TwistedTale** [comment]
> sorry, I meant file of vcclient. which one?
> 
> Is framework "ONNX(cpu,cuda), PyTorch(cpu,cuda)" ? please tell me file name you downloaded from this repo.

ONNX(cpu,cuda), PyTorch(cpu,cuda) : "MMVCServerSIO_win_onnxgpu_cuda_v.1.5.1.11"

**Comment by w-okada** [comment]
Have you try to increase input chunk num?
Set it to 512. 

If you have a trouble yet.
Set GPU to -1 and keep input chunk num 512.

**Comment by TwistedTale** [comment]
> Have you try to increase input chunk num? Set it to 512.
> 
> If you have a trouble yet. Set GPU to -1 and keep input chunk num 512.

ok i just tried this, still the exact same thing as before, only difference is that theres isnt the 2 minute delays anymore

**Comment by TwistedTale** [comment]
> > Have you try to increase input chunk num? Set it to 512.
> > If you have a trouble yet. Set GPU to -1 and keep input chunk num 512.
> 
> ok i just tried this, still the exact same thing as before, only difference is that theres isnt the 2 minute delays anymore

Ok let me but this in a more clear way since all the thing I said are all scattered:

It "works", but by work I mean when it detects an input, it spit out an output at like 1% the volume thats completely illegible when the input chunk is set to 512 and GPU to 0.

If the input chunk is set to anything beside 512 or GPU is set to -1, the same issue still happens but this time there will be an minute long delay for the noise to come out. 

I tried all the fixes suggested

I noticed that when resetting up the voicechanger after a full delete, settings remain. where is the local data stored? Maybe i can try to wipe it completely

thank you so much for your patience for keeping with me, bless you

**Comment by w-okada** [comment]
uum... Maybe gpu is not found in the app.

Anyway, at first about storage.
Storage is the chrome indexed db. If you want to clean up by your hand, open the developer console.
And open Application tab, then you can see the IndexedDB item in the menu at the left side.

Second, 
If your GPU is not found in the app, the app execute pytorch with cpu. This is very slow.
Tsukuyomi-chan, or other character package use ONNX insteadof PyTorch. It is more light. If you have chance, try them.

**Comment by TwistedTale** [comment]
the funny thing is that I did try them, same problem. 

Also at this very moment, I just noticed something interesting that might help, Whenever I press start for the voice-changer (with all default setting and a working model), my VRAM get pinned to the wall like instantly 22-23GB usage out of 24 and it will stay like that even when I pause the voice-changer, only when closing the cmd that the VRAM get freed

**Comment by w-okada** [comment]
In my environment, that does not happen.
Use only 1~2GB.(before vc client launched, 4GB is used.)

![image](https://user-images.githubusercontent.com/48346627/229333639-75ea92a8-3c81-464d-942a-8ad545cd1d51.png)

**Comment by TwistedTale** [comment]
Yeah that would be closer to what id expect, meanwhile here 

![image](https://user-images.githubusercontent.com/76758164/229333875-d1d65554-4ea9-48f8-b963-7ad9c61b3019.png)

**Comment by TwistedTale** [comment]
Thank you so much for taking the time to help me, I see that 1.5.1.12 is out but the google drive link isn't working, I'll be gone for now and see tomorrow if maybe the new version will help.

**Comment by TwistedTale** [comment]
Sorry, didn't have the time the last few days to fiddle, I just tried the newest version and the exact same issue still persists. 😢

**Comment by SirBitesalot** [comment]
I have the same issue with the app using almost all of 24GB of my RTX 4090

**Comment by SirBitesalot** [comment]
So i think this is an issue with VRAM is either newer driver versions or having newer cuda version on the system. As the issue only started after changing my RTX 3080 for a 4090 and in that process updating my GPU Driver and CUDA to
Driver Version: 531.41
CUDA Version: 12.1
Sadly I dont know which versions my RTX 3080 was using...

I "fixed" the issue by creating a second python environment and installing pytorch 2.0.0 with cu118. And copying all cuda related dlls from `{conda_env}\Lib\site-packages\torch\lib` to `MMVCServerSIO\torch\lib` it now uses way less VRAM and seems to be quite a bit faster as well (can also be because its no longer running out of VRAM).
The model uploading now gets stuck at 96.5% but as inference works and produces good audio i guess this is only a visual thing and the model is loaded.
![grafik](https://user-images.githubusercontent.com/22932734/230750467-b356bb33-23fa-4efe-b174-bb4739ba39ba.png)

**Comment by TwistedTale** [comment]
> So i think the issue with the app using all VRAM is either newer driver versions or having newer cuda version on the system. As the issue only started after changing my RTX 3080 for a 4090 and in that process updating my GPU Driver and CUDA to Driver Version: 531.41 CUDA Version: 12.1 Sadly I dont know which versions my RTX 3080 was using...
> 
> @TwistedTale I "fixed" the issue by creating a second python environment and installing pytorch 2.0.0 with cu118. And copying all cuda related dlls from `{conda_env}\Lib\site-packages\torch\lib` to `MMVCServerSIO\torch\lib` it now uses way less VRAM and seems to be quite a bit faster as well (can also be because its no longer running out of VRAM). The model uploading now gets stuck at 96.5% but as inference works and produces good audio i guess this is only a visual thing and the model is loaded. ![grafik](https://user-images.githubusercontent.com/22932734/230750467-b356bb33-23fa-4efe-b174-bb4739ba39ba.png)
> 
> I think its possible that for newer cards/drivers pytorch 2.0.0 with cu118 is neccessary. Since I am on windows and could not get WSL to work correctly I was unable to set up my dev environment to check how hard it is to ugrade the pytorch version.
> 
> But I hope this information is usefull for others and maybe a prebuilt version with newer pytorch and cuda versions can be provided in the future. For now my workaround seems to be enough to make it work for me.
> 
> The full list of DLLs i copied (Its possible that not all are needed):
> 
> * cublas64_11.dll
> * cublasLt64_11.dll
> * cudart64_110.dll
> * cudnn_adv_infer64_8.dll
> * cudnn_adv_train64_8.dll
> * cudnn_cnn_infer64_8.dll
> * cudnn_cnn_train64_8.dll
> * cudnn_ops_infer64_8.dll
> * cudnn_ops_train64_8.dll
> * cudnn64_8.dll

Thanks for the tips, I m still pretty new to this so can I just update to cuda 11.8 and PT 2.0 since I think it might be simpler. If that's a bad idea, is there a easy way to setup a new python environment 🙏

**Comment by SirBitesalot** [comment]
@TwistedTale 
I think currently it is not fully compatible with Pytorch 2.0 atleast from my testing the training code will need adjustments. I dont know if the Voice Changer will work but i would guess there are adjustments neccessary as well.

I would recommend using anaconda to create a new environment (install anaconda and inside the anaconda prompt run):
`conda create -n temp_env python=3.10`
and then just install pytorch with cuda 11.8 inside of it using pip and the install command from the official website: 
https://pytorch.org/get-started/locally/
Then copy over the dlls like i did above. It might be enough to copy `cudnn64_8.dll`
If you dont know where your environment is saved run:
`conda info --envs`

**Comment by w-okada** [comment]
no update close
