### ISSUE TITLE
Respond time increase infinitively

### ISSUE THREAD

**Issue by MamboJiang** [w-okada/voice-changer#151]
I'm using real-time voice change on M2 MacBookPro, but the response time keeps increasing, Did I do something wrong?
<img width="572" alt="截屏2023-04-02 16 02 02" src="https://user-images.githubusercontent.com/60293500/229340284-c7830b5d-322e-4998-9a72-edc4eba7965a.png">
<img width="775" alt="截屏2023-04-02 16 02 54" src="https://user-images.githubusercontent.com/60293500/229340324-6c443dc0-ae53-4629-83b9-21b19d37739b.png">

**Comment by w-okada** [comment]
Please increase input chunk num.
At first  512, then if response time is lower than buffering time, you can decrease it.

**Comment by MamboJiang** [comment]
Thank you!
