### ISSUE TITLE
周期的にブツッブツッと切れた音声が出力される

### ISSUE THREAD

**Issue by nukora** [w-okada/voice-changer#154]
はじめまして。
RVCを使用しているのですが、周期的にブツッブツッと切れた音声が出力されてしまいます。

マイク→オーディオインターフェイス→VC Client→VoiceMeeter Banana→Audacity
という流れで録音した音声が以下となります。
(VoiceMeeterを使わずスピーカーに直接出力しても同じような出力になります)
【文章を読み上げたサンプル】
https://user-images.githubusercontent.com/15606184/230758825-264a8bcc-46d4-4569-8ed9-f96265501f4a.mp4

【伸ばした音のサンプル】
https://user-images.githubusercontent.com/15606184/230758838-3499e5cc-a8bc-4b11-9f0d-917e0b7e6e0e.mp4

また、これはVC ClientのDevice Setting→output record機能を使用すると発生しません。
【文章を読み上げたサンプル】
https://user-images.githubusercontent.com/15606184/230758850-55b386c6-2591-499f-ba04-95975834084e.mp4

【伸ばした音のサンプル】
https://user-images.githubusercontent.com/15606184/230758856-105353f6-99d3-4176-baf7-0a942cf38587.mp4

こちら解決する方法はありますでしょうか？

よろしくお願いします。

【環境】
使用方法: 
事前ビルド済みBinary v.1.5.1.15b win ONNX(cpu,cuda), PyTorch(cpu,cuda)
start_http_RVC.bat

OS: Windows 11 Pro 22H2
CPU: i9-10850K
GPU: GeForce RTX 3080
RAM: 32GB

**Comment by frodo821** [comment]
@nukora Converter Settingからバッファ(Input Chunk Num)を伸ばせば解決します。ただし、バッファを伸ばすとラグが大きくなるので、ここはトレードオフになってしまいます。Extra Data Lengthを小さくするとラグは多少減ります。

**Comment by w-okada** [comment]
元はmultiprocessingで動いてたんですけど、Winネイティブ化(pyinstaller)だったか、Colab対応だったかでシングルスレッドにしないとうまく動かなくなってしまったんですよね。どっちだったか忘れたけど、Colab対応が原因だったらColabはそろそろ切ってmultiprocessingに戻してもよいかなと考えています。

**Comment by frodo821** [comment]
@w-okada 多分pyinstallerが原因ですね。multiprocessingの機能を利用する前に適当なところで `multiprocessing.freeze_support()` を呼んでやるとおそらく動くと思います。

参考: https://qiita.com/npkk/items/cc4c46181c06ff41bdf3

**Comment by nukora** [comment]
Input Chunk Numを増やして試してみたところ、無音が発生する間隔は長くなりましたが、やはり周期的に無音が挟まってしまいます。
こちらもmultiprocessingで解決するものなのでしょうか？

(内部処理が理解できていないため的外れな事を言ってるかもしれませんが、とりあえず起こっている現象を貼っておきます)

【Input Chunk Num = 512】
https://user-images.githubusercontent.com/15606184/230818433-1cb7de89-ae56-45a3-a3d7-92fa1cb76d2b.mp4

【Input Chunk Num = 1024】
https://user-images.githubusercontent.com/15606184/230818449-de75a541-54a0-4f1d-b371-c066f1f970b9.mp4

**Comment by frodo821** [comment]
@w-okada とりあえず変換処理だけmultiprocessingでぶん回すように直しました。

https://github.com/w-okada/voice-changer/pull/158

この問題を解決するには、多分再生側もプロセスを分けるなり変換処理と同じプロセスでやるなりしないといけないような気がします。

**Comment by frodo821** [comment]
@nukora
> Input Chunk Numを増やして試してみたところ、無音が発生する間隔は長くなりましたが、やはり周期的に無音が挟まってしまいます。

現在のコードでは、バッファごとに変換し、その再生が終わるまで次のバッファの変換処理が走らないようになっています。なので、あるバッファの再生が終わったタイミングから次のバッファの再生の準備が整うまで音が途切れてしまいます。そこで、Input Chunk Numを大きくするとバッファが増えるので、その分バッファあたりの再生時間が伸びます。つまり、おっしゃるように無音時間の発生間隔が伸びるということです。
multiprocessingを利用すればバッファの再生中に次のバッファの変換処理を走らせることができるため、無音時間が発生しなくなるのではないかという推測をしています。

**Comment by nukora** [comment]
なるほどです
詳しく解説していただきありがとうございます
私の環境ですとバッファの継ぎ目がどうしても目立ってしまうので、対応していただけると助かります……！

**Comment by w-okada** [comment]
原因はよくわかりませんが論理的には、
ひとつ前の音の再生時間よりも、現在の音声の変換時間が十分短ければ音の変換が遅れて問題が出ることはない
という、考え方で作っています。この考え方が正しければ、パイプライン処理で解決する問題ではないかもしれません。
別のところで説明するために作ったスライドを添付しておきます。


![image](https://user-images.githubusercontent.com/48346627/231028122-0e260405-53f8-4e4a-8156-454066ff752d.png)

![image](https://user-images.githubusercontent.com/48346627/231028161-91a5d79e-d2a0-44b2-8e39-de9e923ad7b2.png)

**Comment by w-okada** [comment]
あ、前提として、バッファリングはブラウザでやって、変換はサーバ側でやる作りです。
なので、そういう意味ではもともとマルチプロセスで動いています。

**Comment by w-okada** [comment]
なお、同じ現象かわかりませんが、こういう報告もありました。

![image](https://user-images.githubusercontent.com/48346627/231029387-cf7fc109-13e6-44a0-a656-c3bb7e48bc25.png)

**Comment by nukora** [comment]
> なお、同じ現象かわかりませんが、こういう報告もありました。
> 
> ![image](https://user-images.githubusercontent.com/48346627/231029387-cf7fc109-13e6-44a0-a656-c3bb7e48bc25.png)

まさにこちらが原因でした。
オーディオインターフェイスの設定でサンプリングレートを48kHzに設定した所、問題が発生しなくなりました。

私の環境ですと、48kHzより大きくても小さくても正常に動かなくなるようです。

ご教示いただきありがとうございました！
