### ISSUE TITLE
does this support sovits4v2 and sovits5 models https://github.com/justinjohn0306/so-vits-svc-4.0-v2 https://github.com/PlayVoice/so-vits-svc-5.0

### ISSUE THREAD

**Issue by Pickymarker** [w-okada/voice-changer#159]
does this support sovits4v2 and sovits5 models https://github.com/justinjohn0306/so-vits-svc-4.0-v2 https://github.com/PlayVoice/so-vits-svc-5.0

**Comment by w-okada** [comment]
so-vits-svc4.0v2 -> yes
so-vits-svc5.0 -> not yet

**Comment by ms903x1** [comment]
”So vits svc5.0 "is not maintained by the original developer" innnky "and the current" svc development team "community. The" so vits svc 4.0v2 "released by the original developer" innnky "before deleting the library is currently the latest known version of" so vits svc "

**Comment by w-okada** [comment]
Colse.

**Comment by Pickymarker** [comment]
does it matter if sovits5 is not made by sovits creators if sovits5 is superior in quality with accent support and stuff and better then sovits4v2 then then who cares who made it as long as its still based off sovits
