### ISSUE TITLE
rvc「onnx」モデルのインポート推論時報エラー

### ISSUE THREAD

**Issue by ms903x1** [w-okada/voice-changer#160]
「onnx」のサポートがまだ完全ではないか？
 error：
![image](https://user-images.githubusercontent.com/108673569/231434264-bb1e22c1-d52b-4e40-96ad-cf6b802ef526.png)

gui設定：
![image](https://user-images.githubusercontent.com/108673569/231434460-e23dc3de-1fd8-477f-8c31-8b75c2d16652.png)

「onnx」モデルは、「rvc」倉庫の「export _ onnx.py」を使用してエクスポートされます

**Comment by w-okada** [comment]
export _ onnx.py generate custom network for the other app.And I don't know how to use it. So I have no plan support it. Instead, I develop my onnx export integrated with VC Client. Maybe it will release in a few days.

**Comment by ms903x1** [comment]
I see ， close this issue.
