### ISSUE TITLE
Improve the sound quality of real-time voice changer with better stitching algorithm

### ISSUE THREAD

**Issue by yxlllc** [w-okada/voice-changer#163]
I noticed that the crossfades used by the project now is the classic OLA (overlap-add) method.  However, this method has the problem of fundamental harmonic breakage, because if the phase difference of the two harmonics to be spliced is very large, cross-fading will introduce beat frequency, resulting in unstable amplitude.

Now, the built-in gui of [DDSP-SVC](https://github.com/yxlllc/DDSP-SVC/blob/master/gui.py) and [RVC](https://github.com/liujing04/Retrieval-based-Voice-Conversion-WebUI/blob/main/gui.py) both use a so-called SOLA (synchronized-overlap-add) algorithm, and it is found through experiments that it can solve the above fundamental harmonic breakage problem. Its core idea is to slide the stitching position (generally less than one fundamental harmonic period) and calculate the autocorrelation, and then cross-fade at the position of the maximum autocorrelation.

SOLA can use torch's conv1d function to accelerate autocorrelation calculations using gpu, and it has been tested to cause almost no additional delay (on the order of 1ms). Relevant codes have been implemented in the above two guis. I expect this project can also use SOLA or even more advanced stitching algorithms.

**Comment by yxlllc** [comment]
Yes, sola is clearer and has less noise. You can also adjust the correlation search length of sola. I tested it for about 0.01s and it works well.

**Comment by w-okada** [comment]
I have implemented SOLA for this project. Close this issue. 
Thanks!!
