### ISSUE TITLE
Webページへのアクセス時に常にエラーが発生します

### ISSUE THREAD

**Issue by ojaoja** [w-okada/voice-changer#165]
Webベージ上でほとんどの操作（ボタンを押した場合など）にエラーが出力されます
環境:windows11、v.1.5.2.1
HTTP・HTTPS両方でエラーが発生
exeをダウンロードしたものを実行した場合と、wsl上にてpythonで実行した場合両方とも発生
（エラーはHTTPSで実行した時のみ出力されるログから）

"POST /model_type HTTP/1.1" 500 Internal Server Error
このエラーが常に発生します。

また、wsl上で実行している時は
"GET /socket.io/?EIO=4&transport=websocket&sid=34WZQS9uBQ9HCJtXAAAB HTTP/1.1" 500 Internal Server Error
"GET /socket.io/?EIO=4&transport=websocket&sid=Cb0uqkceL5WBkBnIAAAA HTTP/1.1" 500 Internal Server Error

こちらのエラーも発生しています。
なお、ファイアウォール等のセキュリティソフトは全て切ってあります。
原因と対応としては何が考えられますでしょうか。

**Comment by w-okada** [comment]
再現しないのでわかりません。他に同じような現象の方はおられるでしょうか？

**Comment by ojaoja** [comment]
最新バージョンで実行したところエラーの詳細が解りましたので
追記させていただきます。何か解決の糸口がありましたらよろしくお願いいたします。

環境：Windows11,v.1.5.2.2

◎WSLからPythonで起動の場合
1)準備としてクローン後にServerフォルダのREADMEの起動方法を実行

2)起動後に何かを押すとエラー発生
INFO:     127.0.0.1:41038 - "GET /socket.io/?EIO=4&transport=websocket&sid=BNRDArEh8t8MRV9EAAAA HTTP/1.1" 500 Internal Server Error
WARNING:  Unsupported upgrade request.
WARNING:  No supported WebSocket library detected. Please use 'pip install uvicorn[standard]', or install 'websockets' or 'wsproto' manually.
ERROR:    Exception in ASGI application

3)'pip install uvicorn[standard]'を実行

4)その後、トップページで各ボタンを押すといずれもこのエラー発生
INFO:     127.0.0.1:55584 - "POST /model_type HTTP/1.1" 500 Internal Server Error

ボタン毎のエラーの内容は以下の通りです

MMVCv13 : ModuleNotFoundError: No module named 'symbols'
MMVCv15 : ModuleNotFoundError: No module named 'models'
s-vits-svc-40 : ModuleNotFoundError: No module named 'models'
s-vits-svc-40v2 : ModuleNotFoundError: No module named 'models'
RVC : ModuleNotFoundError: No module named 'parselmouth'

※parselmouth は pip でのインストールを行えましたが、その後は
ModuleNotFoundError: No module named 'config'
に変化しました。

◎exeファイルで起動の場合
※HTTPSで起動

1)初回起動時はエラー出力は無いが、何かボタンを押すと
「ちょっと問題が起きたみたいです。」の画面に切り替わります。
（※ここに記載した全エラー時に参照画像の画面になります）
![error](https://user-images.githubusercontent.com/1327328/232321676-78f115c4-8da7-4216-8266-e364b7467a88.png)

2)最初に「アプリを初期化」ボタンを押した後、何かボタンを押すと以下のエラーが出ます

INFO:     127.0.0.1:65354 - "POST /model_type HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
...(中略)...
NameError: name '_imp' is not defined

3)「アプリを初期化」ボタンを押した２回目以降は、最後に出るエラーが以下に変わります
（その後はずっとこのままです）

sniffio._impl.AsyncLibraryNotFoundError: unknown async library, or not in async context

**Comment by w-okada** [comment]
情報ありがとうございます。
すみません、、ちょっと今のところ分からないのですが、
別の方から、マイクが接続されていないとエラーが出るという情報がありました。
マイクは接続されていますでしょうか？

**Comment by ojaoja** [comment]
ご確認ありがとうございます。マイクは接続して使用しておりますので、その点は大丈夫だと思います。

**Comment by ojaoja** [comment]
確認しなおしたところ、使用時にマイクの接続が切れていた事がわかりました。
大変お騒がせいたしました。アドバイスありがとうございます。
なお、各サポート VC を選択した時にブラウザから「マイクを使用します」という許可が
表示されていれば何かしらのマイクデバイスが認識されている事になると思います。
これが出ていないで同じような状況の方がいましたら、改めて接続を確認してみて下さい。

**Comment by w-okada** [comment]
Anaconda環境での立上げ方をマニュアルにしました。（開発者向けと同じ）
もしよろしければ、こちらでどうなるかお試しいただけると助かります。

https://github.com/w-okada/voice-changer/blob/master/README_dev_ja.md

**Comment by ojaoja** [comment]
マニュアル通り一通りやってみましたところ、問題なく動作いたしました。
ご丁寧に対応して頂きありがとうございました。
