### ISSUE TITLE
add direct ml support to this for amd gpus

### ISSUE THREAD

**Issue by Pickymarker** [w-okada/voice-changer#166]
add direct ml support to this for amd gpus

**Comment by w-okada** [comment]
Support for ONNX? Yes, I used to release it. I stopped because multiple packages would confuse users. Let me think about it.

**Comment by Pickymarker** [comment]
if you release the amd version you can say and indicate the current one is for nvidia gpus and the other one is for other gpus like deepfacelive does

**Comment by Pickymarker** [comment]
i just want to be able to fully use my amd gpu to use this like i can for deepfacelive

**Comment by Pickymarker** [comment]
when is the directlml version coming out

**Comment by w-okada** [comment]
v.1.5.2.8 is released.(not tested)

**Comment by Pickymarker** [comment]
The link with directml is not working
