### ISSUE TITLE
MMVC使用時のspeakerID

### ISSUE THREAD

**Issue by katoubudoutou** [w-okada/voice-changer#167]
100~103まではプルダウンで選べるが自分で学習させた上記以外のidにすることが出来るのか。
わからないので質問しました。

**Comment by w-okada** [comment]
MMVC のVersionを教えてください。

**Comment by katoubudoutou** [comment]
返信ありがとうございます。verはv1.3.2.2です

**Comment by katoubudoutou** [comment]
ちなみにスピーカーIDは108で学習させていました。

**Comment by w-okada** [comment]
こちらを参照してください。
https://zenn.dev/wok/books/0002_vc-helper-v_1_3/viewer/004-2_voice-changer

**Comment by katoubudoutou** [comment]
解決しました、ありがとうございます！
