### ISSUE TITLE
logのpthを読み込ませたいんだけど。

### ISSUE THREAD

**Issue by w-okada** [w-okada/voice-changer#176]
https://twitter.com/DannadoriYellow/status/1647411077251223552?s=20

**Comment by jojonki** [comment]
こちら横から失礼します．
Twitterで指摘されている方法でいけましたので共有します．私はRVCは配布されているバイナリではなく RVCの本リポジトリの最新版を使っているので一部英語になっていますが，配布されているバイナリ版（ `RVC-beta.7z` ）でも同様な気がします．

- 一番右の `ckpt processing.` タブを選択
- 一番下の"模型提取..."のところ を見る
- 左上の `Model path` で `./logs/$exp_name/G_XXXX.pth` でフルパスを指定．デフォルトで `E:\codes..\G_23333.pth` とある所．
- その下の `Save Name (保存名)` で 適当なファイル名を指定． 
-  右側の `Extract` ボタンを押す
- 一番右の `Output information` に `Success.` とでる
- `weights/` 以下に `.pth` ファイルが生成されるのでそれをVC Clientで使ったところ問題なく動作した．

ちなみに環境は以下です．
- https://github.com/liujing04/Retrieval-based-Voice-Conversion-WebUI/ はUbuntu上で動かしています ( `71bf6a415631` )
- VC Clientも同じUbuntu上で動かしています． (`707096b48c` )


実装は結構単純そうですね．
https://github.com/liujing04/Retrieval-based-Voice-Conversion-WebUI/blob/0719b4aa5eae1f18bfb3e87648bd1acd4abdc0a9/train/process_ckpt.py#L97

**Comment by w-okada** [comment]
情報ありがとうございます。Twitterの相手の方もできたようです。クローズします。
