### ISSUE TITLE
v.1.5.2.2windowsにてso-vits-SVC4.0のモデルのアップロードが不能

### ISSUE THREAD

**Issue by Nul700** [w-okada/voice-changer#177]
エラーメッセージ
EXCEPTION during loading hubert/contentvec model 'NoneType' object has no attribute 'replace'
load
INFO:root:Loaded checkpoint 'D:\Temp\tmpvzuq0yqv\upload_dir\G_64000.pth' (iteration 942)

ファイル配置は正しく行われているはず
D:\me\MMVCServerSIO\MMVCServerSIO.exe
D:\me\MMVCServerSIO\checkpoint_best_legacy_500.pt
‪D:\me\MMVCServerSIO\hubert_base.pt
D:\me\MMVCServerSIO\file\vits\G_64000.pth
D:\me\MMVCServerSIO\file\vits\config.json

**Comment by Nul700** [comment]
どうやら応えていただけないようですね。残念です
あなたに期待した私が馬鹿でした。もっとも動いても多くの点で残念な仕様ですが

**Comment by w-okada** [comment]
もう少し情報をいただけますか？
コンソールの情報などあると調べやすいです。
また、もし可能であればバージョンを上げて再度確認いただけると助かります。

**Comment by w-okada** [comment]
これと同じ現象かもしれません。
https://github.com/w-okada/voice-changer/issues/200

**Comment by w-okada** [comment]
no res close
