### ISSUE TITLE
hubert読み込んでくれません。

### ISSUE THREAD

**Issue by w-okada** [w-okada/voice-changer#180]
.exeで起動ですると発生する場合があります。
.batで起動してください。

**Comment by Pickymarker** [comment]
i started it with http and its still happening 
![image](https://user-images.githubusercontent.com/74084396/232347181-d435fe88-be62-4f4e-b914-d505fddac5b9.png)

**Comment by w-okada** [comment]
Are you copy hubert_base.pt in the same folder as .bat ?

**Comment by Pickymarker** [comment]
how do i do that and i using this version because its the latest directml version

**Comment by w-okada** [comment]
Please tell me more information about your situation. How to start the application?

And let me say up front that this application desn't support onnx for so-vits-svc40. In other words, directML cannot be used.

**Comment by Pickymarker** [comment]
then why does it say directml on that version if not all of it supports it on that version and it should only say direct ml supported if sovits supports it because barely anyone uses the other ones compared to sovits and sovits has the most public models out of all of them

**Comment by w-okada** [comment]
Uh, sorry if I gave you the wrong impression.
I'm just stating the framework I'm using, not saying it will work with it. so-vits-svc40 is supported by pytorch.

**Comment by Pickymarker** [comment]
what about it having this in the sovits folder 
![image](https://user-images.githubusercontent.com/74084396/232370481-417c2d7e-ea04-4f36-b439-a4e87bc511a0.png)
