### ISSUE TITLE
solaが機能しない？

### ISSUE THREAD

**Issue by goodshuma** [w-okada/voice-changer#182]
コマンドラインに「no sola buffer」と表示され音がブツブツ途切れる現象が起きています。
オーディオインターフェイスのサンプリングレートやinput chunk numなど試してみましたが改善されません。
これは友達の環境で起こっているもので、私の環境では「no sola buffer」とは表示されず、ブツブツ切れることもありません。
なぜ「no sola buffer」が表示されるのかと、解決法があれば教えていただけますか。

**Comment by w-okada** [comment]
Sola Bufferは最初は存在しないので、一度は出ると思います。その後バッファが生成されるのでメッセージが出なくなると思います。その場合は別の原因で音が途切れることが発生していると考えたほうがいいです。

音がぶつぶつ切れる問題はこちらのissueを代表として、いくつか対策が議論されているので、まずはご確認ください。
https://github.com/w-okada/voice-changer/issues/154

**Comment by goodshuma** [comment]
既にissueに書かれているものは一通り試しており、貼っていただいたissueも検証済みです。
貼っていただいたissue内であった「録音するとプチプチでは無い」状態です。
サンプリングレートの違うデバイスがひとつでもあったらボイチェンで使っていないデバイスでもダメなのでしょうか？

**Comment by w-okada** [comment]
うーむ、そんなことはないとは思うのですが、全ての機器を確認したわけではないのでわからないです。。。
