### ISSUE TITLE
Speed up DDSP-SVC when extracting f0 or using enhancer 

### ISSUE THREAD

**Issue by yxlllc** [w-okada/voice-changer#184]
Thanks for supporting DDSP-SVC, I found that you did not set the 'silence_front' parameter to speed up both f0 extraction (F0_Extractor.extract function) and vocoder enhancement (Enhancer.enhance function)

You can try to set it as follows：
silence_front = self.settings.extraConvertSize / self.sampling_rate

The principle of this acceleration is that DDSP-SVC will treat the extraConvertSize part of the audio as silence, so as not to perform f0 extraction and vocoder enhancement. After all, it is the result of "extra" sampling points that do not affect the final real-time sound change.

However, these extra sampling points are not useless, it will be used to extract hubert features (very fast with a graphics card), because hubert needs sufficient length (greater than 1s) to obtain the most accurate semantic information.

There are also some small suggestions, such as the 'adaptive_key' of the Enhancer.enhance function can be set to 'auto' (recently updated code), so that there is no need to adjust it. Also, if the speedup trick above is used, it is actually possible to use slow but better f0 extraction algorithms such as 'harvest' and 'crepe' while maintaining low latency.

All of the above are implemented in the built-in GUI of DDSP-SVC. I recently communicated with the developers of So-VITS-SVC and RVC how to do calculation acceleration. It is very likely that these models will also support similar technologies in the future: the extra sampling points are only used to extract semantic information, not to participate in other synthesis pipeline. Maybe in the future we will have the opportunity to work together to promote more advanced AI voice changer technology.

**Comment by w-okada** [comment]
Thank you. Very useful and wise advice! I would like to implement this in the next version. Please wait about one week.

**Comment by w-okada** [comment]
I supported silence-front for DDSP-SVC and RVC.

https://github.com/w-okada/voice-changer/blob/75ebbe890cf8b9fbbd9f2b86d775ee38120b7174/server/voice_changer/RVC/custom_vc_infer_pipeline.py#L30

https://github.com/w-okada/voice-changer/blob/75ebbe890cf8b9fbbd9f2b86d775ee38120b7174/server/voice_changer/DDSP_SVC/DDSP_SVC.py#L201

https://github.com/w-okada/voice-changer/blob/75ebbe890cf8b9fbbd9f2b86d775ee38120b7174/server/voice_changer/DDSP_SVC/DDSP_SVC.py#L290
