### ISSUE TITLE
バージョンの確認をアプリケーション上で行えるようにしてほしいです

### ISSUE THREAD

**Issue by seiyuami** [w-okada/voice-changer#187]
いつもお世話になっております。

表題の件につきまして、例えばGUI上の何処かに記載頂くことは可能でしょうか。
精力的にバージョンアップをされておられますので、ユーザーが確認する方法をご用意頂けますと幸いです。

余談にはなりますが、v.1.5.2.2が一番安定して利用できておりますので愛用しております。

**Comment by w-okada** [comment]
検討します。

**Comment by w-okada** [comment]
最新版から出るようになりました。
v.1.5.3.3b
