### ISSUE TITLE
Tuningの調整に直接文字を打ち込めるようにして欲しいです

### ISSUE THREAD

**Issue by seiyuami** [w-okada/voice-changer#188]
いつもお世話になっております。

表題の件につきまして、チューニング時にマウスで左右にスライドさせているのですが
微調整がとても困難になることが多々あり、文字入力や矢印キーなどで1づつ上げ下げ出来る仕様をご検討いただけますと幸いです。

**Comment by w-okada** [comment]
既にスライダーを選択したあと左右矢印でできると思いますが、OSやブラウザなど情報を教えていただけますか？

**Comment by seiyuami** [comment]
早速のご確認ありがとうございます。

こちらで改めて確認したところ、確かに矢印キーで増減することを確認しました。
キーボードに不具合があったようで正しく動作しなかったようです。

お手数をおかけいたしました。重ねてお礼申し上げます。
