### ISSUE TITLE
my friend gets this error when loading a model and has hubert and content vec legacy base in main folder 

### ISSUE THREAD

**Issue by Pickymarker** [w-okada/voice-changer#190]
my friend gets this error when loading a model and has hubert and content vec legacy base in main folder 
![image](https://user-images.githubusercontent.com/74084396/233376696-6fc3cc25-a868-4c47-973c-e1488138e493.png)

**Comment by w-okada** [comment]
plz more info....
which vc? which file used to run? and give me full text in your console.

**Comment by Pickymarker** [comment]
sovits 4.0 and the model he used had only a config file and a pytorch file

**Comment by w-okada** [comment]
PLEASE MORE INFO.
OS:
VCCLIENT VERSION:
HOW TO INVOKE: (which .bat ?)
VC:(RVC, so-vits-svc-40 or so)
FULL CONSOLE MESSAGE:


AND if you use old version of VCClinet please use the latest (currently v.1.4.2.4a)

**Comment by Tybost** [comment]
Fixed.

You're getting that error because you need to drag checkpoint_best_legacy_500.pt into MMVCServerSIO_win_onnxgpu-cuda_v.1.5.2.4a\MMVCServerSIO\so-vits-svc-40\cluster

The next error you'll face requires you to edit **start_http** (Notepad++) and change --content_vec_500_onnx_on true to false

Example model used: https://huggingface.co/OlivineEllva/so-vits-svc-4.0-models/tree/main/LyraBonHearts
G_37000, config(lyra), lyra_kmeans_2853

**Comment by Pickymarker** [comment]
> Fixed.
> 
> You're getting that error because you need to drag checkpoint_best_legacy_500.pt into MMVCServerSIO_win_onnxgpu-cuda_v.1.5.2.4a\MMVCServerSIO\so-vits-svc-40\cluster
> 
> The next error you'll face requires you to edit **start_http** (Notepad++) and change --content_vec_500_onnx_on true to false
> 
> Make sure you're using Pytorch and not ONYX mode
> 
> Example model used: https://huggingface.co/OlivineEllva/so-vits-svc-4.0-models/tree/main/LyraBonHearts G_37000, config(lyra), lyra_kmeans_2853
> 
> Edit: In case your model doesn't properly load (fails at 50%) then change 0 to 1 model slot. This is happening to me on v.1.5.2.4a

didn't help him 
![image](https://user-images.githubusercontent.com/74084396/234397604-1b2c1117-7fc9-45bb-9317-561e4aae8747.png)

**Comment by Tybost** [comment]
Very strange errors (we initially had the same error but not anymore)
You should tell him to download the new version v.1.5.2.5 since the fixes were automatically applied.
_He's using the Windows version right?_

**Comment by w-okada** [comment]
@Pickymarker 
plz use the latest version.

**Comment by w-okada** [comment]
no res close
