### ISSUE TITLE
where can i get the trained model and config file on your video?

### ISSUE THREAD

**Issue by hjliag** [w-okada/voice-changer#191]
The program says that it needs config file and he model but I can't find it on the repository. 
Where can I get the G_326000.onnx and config.json file on your video?
and i'd like to know where i can get other models for RVC.
or do i need to train it myself? 
thank you

**Comment by w-okada** [comment]
RVC official repo is here
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI
