### ISSUE TITLE
Unable to load RVC models

### ISSUE THREAD

**Issue by Chrisyk** [w-okada/voice-changer#192]
I am running a WSL2 conda environment on Windows and the model upload always stops at 99% and gives me this error. 
```shell
[Voice Changer] RVC loading... slot: 0
EXCEPTION during loading hubert/contentvec model Model file not found: weights/hubert_base.pt
[Voice Changer] Model Load Error! Check your model is valid. 'config'
``` 
This is my weights directory
![image](https://user-images.githubusercontent.com/80287817/233507726-3f7772d6-d4fc-4926-82e2-da8d968822a2.png)

Launch command:
```shell
python3 MMVCServerSIO.py -p 18888 --https true   --content_vec_500 weights/checkpoint_best_legacy_500.pt   --hubert_base weights/hubert_base.pt   --hubert_soft weights/hubert-soft-0d54a1f4.pt   --nsf_hifigan weights/nsf_hifigan/model 
```

**Comment by Chrisyk** [comment]
Path seems to work fine using "/" when using cd. I tried changing the delimiter to "\" and I got this error:

```shell
python3 MMVCServerSIO.py -p 18888 --https true   --content_vec_500 weights\checkpoint_best_legacy_500.pt   --hubert_base weights\hubert_base.pt   --hubert_soft weights\hubert-soft-0d54a1f4.pt   --nsf_hifigan weights\nsf_hifigan\model
``` 

```shell
[Voice Changer] RVC loading... slot: 0
EXCEPTION during loading hubert/contentvec model Model file not found: weightshubert_base.pt
[Voice Changer] Model Load Error! Check your model is valid. 'config'
INFO:     127.0.0.1:58310 - "POST /load_model HTTP/1.1" 200 OK
INFO:     127.0.0.1:58310 - "GET /info HTTP/1.1" 200 OK
```

**Comment by w-okada** [comment]
Sorry, I think "/" is better. Because, "EXCEPTION during loading hubert/contentvec model Model file not found: weightshubert_base.pt" doesn't contain correct file path "weights/hubert_base.pt". 
By the way, which version you use? V.1.5.2.3a include some bugs. Please use v.1.5.2.4a.

**Comment by Chrisyk** [comment]
I found out the issue with weights was just a simple misspelling. I wrote 'weigths' by accident.
I don't get that error anymore, but it still can't load the model after updating to V.1.5.2.4a. This is the error I get now:
```shell
[Voice Changer] RVC loading... slot: 0
[Voice Changer] Prepare Model of slot: 0
[Voice Changer] Model Load Error! Check your model is valid. 'config'
INFO:     127.0.0.1:34112 - "POST /load_model HTTP/1.1" 200 OK
INFO:     127.0.0.1:34112 - "GET /info HTTP/1.1" 200 OK
``` 
I tried 3 different pt models from hugging face, but none seem to work. This is how I'm loading them:

![image](https://user-images.githubusercontent.com/80287817/233820355-88b6181a-c543-4dc9-8188-ac5f50acbbdd.png)

**Comment by w-okada** [comment]
Maybe you upload wrong file. Please use the .pth file in weights folder. (not G_xxx.pth)

**Comment by Tybost** [comment]
> I tried 3 different pt models from hugging face, but none seem to work. This is how I'm loading them:

Make sure you're using custom voice models trained by RVC: https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI

ie. https://booth.pm/en/items/4706454

**Comment by Chrisyk** [comment]
That seems to have worked. The model can be uploaded now, but I'm getting a separate issue when starting the program:

```shell
[Voice Changer] RVC loading... slot: 0
[Voice Changer] Prepare Model of slot: 0
gin_channels: 256 self.spk_embed_dim: 109
INFO:     127.0.0.1:53016 - "POST /load_model HTTP/1.1" 200 OK
INFO:     127.0.0.1:53016 - "GET /info HTTP/1.1" 200 OK
Generated Strengths: for prev:(1024,), for cur:(1024,)
/home/chris/anaconda3/envs/vcclient-dev/lib/python3.10/site-packages/scipy/signal/_signaltools.py:1551: UserWarning: kernel_size exceeds volume extent: the volume will be zero-padded.
  warnings.warn('kernel_size exceeds volume extent: the volume will be '
Could not load library libcudnn_cnn_infer.so.8. Error: libcuda.so: cannot open shared object file: No such file or directory
```

**Comment by w-okada** [comment]
Maybe you failed to install cuda.

**Comment by Chrisyk** [comment]
I will open a new issue for this problem

**Comment by Th3Heavy** [comment]
> Le problème a été résolu. libcuda.so n'était pas sur la lib/cache wsl, c'est pourquoi il m'a donné cette erreur.


can you give the steps for installing this library please?
