### ISSUE TITLE
AttributeError: 'RVC' object has no attribute 'hubert_model'

### ISSUE THREAD

**Issue by xxxxsssssx** [w-okada/voice-changer#193]
VC PROCESSING!!!! EXCEPTION!!! 'RVC' object has no attribute 'hubert_model'
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 236, in on_request_sola
  File "voice_changer\RVC\RVC.py", line 291, in inference
  File "voice_changer\RVC\RVC.py", line 251, in _pyTorch_inference
AttributeError: 'RVC' object has no attribute 'hubert_model'

windows v.1.5.2.3aのRVC(Retrieval-based-Voice-Conversion)での操作でのエラーです。
pthファイルのアップロードはできているのですが
startを押すとこのようなエラーが出てしまいます。

**Comment by w-okada** [comment]
hubertが読み込めていないみたいです。
1.5.2.3aは一度間違えたバージョンをupしてしまったことがあるので、
それを使われているかもしれません。

お手数ですが最新版で再度お試しいただけますでしょうか。

**Comment by xxxxsssssx** [comment]
お疲れ様です。
確かにverは1.5.2.3.aでした。
後ほどver.1.5.2.4を試してみます。
また進捗があり次第御報告させていただきます。
ご迷惑をおかけし申し訳ございません。

**Comment by xxxxsssssx** [comment]
お疲れ様です。
ver1.5.2.4を試したのですが今度はpthファイルのuploadが上手く行かなかくなってしまいました。
エラーメッセージは以下の通りです。
post_update_settings crossFadeOffsetRate 0.1
post_update_settings crossFadeEndRate 0.8
post_update_settings crossFadeOverlapSize 1024
post_update_settings framework PyTorch
post_update_settings onnxExecutionProvider CPUExecutionProvider
Onnx is not enabled. Please load model.
onnxExecutionProvider is not mutable variable or unknown variable!
post_update_settings f0Factor 1
f0Factor is not mutable variable or unknown variable!
post_update_settings f0Detector harvest
post_update_settings tran 10
post_update_settings silentThreshold 0.00001
post_update_settings extraConvertSize 32768
post_update_settings clusterInferRatio 0.1
clusterInferRatio is not mutable variable or unknown variable!
post_update_settings modelSamplingRate 40000
post_update_settings silenceFront 1
post_update_settings inputSampleRate 48000

Onnx is not enabled.などとありますが原因がこちらではよくわからずといった感じです。
度々申し訳ございません。

**Comment by w-okada** [comment]
うまくいかないというのはどういう状況でしょうか？

また、これ以外のメッセージは出ていないですか？

**Comment by xxxxsssssx** [comment]
申し訳ございません。補足させていただきます。
Model　Settingのuploadボタンを押しても、uploading...の読み込んでる様子は出てるのですが
Server ControlのSwicth Modelに反映されない状態です。
また最後の一文のエラーメッセージが抜けていました。お手数をおかけします。
[25244:0422/185225.831:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is

**Comment by xxxxsssssx** [comment]
追加の補足です。これらのエラーメッセージはuploadボタンを押さなくても起動後しばらくしても発生したのでおそらくuploadと直接関係ないと思われます。
またuploadを押した際のメッセージは何も出てきませんでした。
そのままダメもとでstartを押したときのエラーメッセージは以下の通りです。
VC PROCESSING!!!! EXCEPTION!!! 'RVC' object has no attribute 'slot'
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 235, in on_request_sola
  File "voice_changer\RVC\RVC.py", line 354, in inference
AttributeError: 'RVC' object has no attribute 'slot'

**Comment by w-okada** [comment]
すみません、バグにあたっている可能性があります。
こちらお試しいただけますでしょうか。
https://twitter.com/DannadoriYellow/status/1649976189715648513?s=20
