### ISSUE TITLE
model upload error

### ISSUE THREAD

**Issue by gororo111** [w-okada/voice-changer#196]
I always get upload error in Linux and windows,

INFO:     172.17.0.6:33882 - "POST /load_model HTTP/1.1" 422 Unprocessable Entity
the model can't be mounted on VC client,
I've tried RVC, sovits 4.0 and sovits 4.0 v2

with all preparation and enviroment setting completed, I still meet with such like report
![screencapture-localhost-18888-2023-04-23-10_03_24](https://user-images.githubusercontent.com/120551950/233815450-7ca51874-308e-4be2-8f6f-67f82fa5801d.png)
such like report

I wonder why, however the same model is valid in sovits 4.0 or RVC program respectively
expect your help!

**Comment by w-okada** [comment]
Thanks.

I have already received reports of similar phenomena and there are cases that have been solved. Could you try the following? 

Before uploading the model, do the following two things: 
(1) Toggle the half-precision checkbox on/off
(2) Move the default tuning slider

**Comment by w-okada** [comment]
Can I close?

**Comment by Tybost** [comment]
Model mounting is bugged for So-vits. Change model slot from 0 to 1 and you'll get passed 50%.

**If you face any other errors:**

1) You need to edit start_http (Notepad++) and change --content_vec_500_onnx_on true to false (at least for V1)
2) Drag checkpoint_best_legacy_500.pt to MMVCServerSIO_win_onnxgpu-cuda_v.1.5.2.4a\MMVCServerSIO\so-vits-svc-40\cluster (or 40v2 cluster for V2)
