### ISSUE TITLE
vol(rms) is not recognized on RVC mode

### ISSUE THREAD

**Issue by r3coder** [w-okada/voice-changer#197]
vol(rms) value not increasing, audio input was set correctly

Environment
 - Used "(2) Usage with pre-built binaries" - version v.1.5.2.4 Windows build
 - OS: Windows 10
 - CPU: Ryzen 5800x
 - GPU: RTX 3070 Ti - Latest Nvidia driver version (531.68)

We've got an error message on the console message:
`Could not locate cudnn_ops_infer64_8.dll. Please make sure it is in your library path!`

What we've tried:
We've Google the error, and it seems to be an error with zlib. so we tried this fix: [link](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#install-zlib-windows).
Since we don't know where the PATH is, we put the DLL file on Windows/System32, Windows/SysWOW64. -> still didn't work.

**Comment by w-okada** [comment]
This is it?

https://www.architectryan.com/2018/08/31/how-to-change-environment-variables-on-windows-10/

BTW, Your problem is not for this repository. Please ask microsoft or Nvidia.

**Comment by r3coder** [comment]
Since somebody worked and somebody didn't work while using the same method to execute the binary, I thought there was something wrong with this repository. I'll try to find the necessary binaries and include in the path. Thank you for your response!
