### ISSUE TITLE
no attribute 'hubert_model'

### ISSUE THREAD

**Issue by iljung1106** [w-okada/voice-changer#200]
VC PROCESSING!!!! EXCEPTION!!! 'SoVitsSvc40v2' object has no attribute 'hubert_model'
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 229, in on_request_sola
  File "voice_changer\SoVitsSvc40v2\SoVitsSvc40v2.py", line 244, in generate_input
  File "voice_changer\SoVitsSvc40v2\SoVitsSvc40v2.py", line 201, in get_unit_f0
AttributeError: 'SoVitsSvc40v2' object has no attribute 'hubert_model'

No matter what vc I use, this error appears.

**Comment by w-okada** [comment]
Did you set hubert_base.pt in the folder?

**Comment by Tybost** [comment]
Tossing my hat into the ring as well (been trying for a week now).
RVC itself works fine but when trying the other options (So-vits-svc-40 + So-vits-svc-40v2) it keep popping up the same error.

> Did you set hubert_base.pt in the folder?
Hubert_base.pt is placed in the main folder (Any other steps that need to be taken?)

**Comment by w-okada** [comment]
@Tybost 
Thanks and you are great!. I couldn't find the reason of this situation, but you found. 
I Think that's it. --content_vec_500_onnx_on should be false.

**Comment by w-okada** [comment]
New version is up. v.1.5.2.5
At this version, I fixed the problem about .bat. Please use this.
