### ISSUE TITLE
SOLAのオプションについて

### ISSUE THREAD

**Issue by iseesince2021** [w-okada/voice-changer#207]
SOLAのオプションが使えるようになった、というブログの記事を読んだので、1.5.2.5のWin事前ビルドの画面を探したのですが、Adbanced Settingの項目に見当たりませんでした。
ドキュメントの更新履歴を追うと、1.5.2.3で全モデルで利用可能になった、という記載があったのですが、その後デフォルト有効になったとか、そういう経緯があるのでしょうか？

他に何か条件で画面に出る出ないなどございましたらご教授ください。

![image](https://user-images.githubusercontent.com/83894751/235026335-18a42a9b-e0f6-4310-8289-5e5419a0d86d.png)

**Comment by w-okada** [comment]
SOLAはデフォルトでONになっており、解除できない仕様に変更されています。

**Comment by iseesince2021** [comment]
早速のコメントありがとうございます。内容承知いたしました。
