### ISSUE TITLE
Passthrough is not supported, GL is disabled, ANGLE is

### ISSUE THREAD

**Issue by XueBi520** [w-okada/voice-changer#210]
Passthrough is not supported, GL is disabled, ANGLE is

[Voice Changer] RVC loading... slot: 0
[Voice Changer] Prepare Model of slot: 0
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] no sola buffer. (You can ignore this.)
[4716:0429/213736.103:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
post_update_settings tran 3

**Comment by XueBi520** [comment]
Yesterday everything was fine, after restarting the computer, today open on this, the voice became hoarse with electric sound

**Comment by w-okada** [comment]
Maybe clearsetting help you. But, currently, clear setting has a bug no to clear all setting. I am fixing it. Please wait.

**Comment by w-okada** [comment]
v.1.5.2.8 is released. you can export onnx with cpu. try it.

**Comment by w-okada** [comment]
no response. close.
