### ISSUE TITLE
サンプリングレートの認識問題

### ISSUE THREAD

**Issue by kogoto3** [w-okada/voice-changer#213]
・全マイクのサンプリングレートは24ビット48kHz
・既定のスピーカーのサンプリングレートのみ24ビット192kHz

上記の環境でAudioInputが192kHzから48kHzへの変換が行われているようで、AnalyzerによるとInputの時点で4倍ほどの音声時間に間延びしてしまいます。これはAudioInputをFileを含めたどの入力形態にしても同様にInput時点で間延びしてしまいます。

既定のスピーカー以外のデバイスのサンプリングレートは影響せず、既定のスピーカーのサンプリングレートをマイクに合わせるとこの問題は改善します。実際に設定するOutputDeviceやInputDeviceのサンプリングレートとは関係がない模様です。

当方の環境では物理マイク以外のすべてのデバイスを24ビット192kHzにしたHDオーディオに設定しているので、改善されると非常に助かります！

**Comment by w-okada** [comment]
ありがとうございます。
これって、出力側のサンプリングレートが入力に影響してそうってことですよね。
いまのところどうしてそうなるのか理解できていませんが、
この観点はありませんでしたので、ちょっと考えてみます。
