### ISSUE TITLE
ddPn08氏のwebuiによる.indexと.npyについて

### ISSUE THREAD

**Issue by goomy63** [w-okada/voice-changer#214]
ddPn08氏のwebuiを使って生成したindexとnpyファイルを読み込もうとすると下記画像のエラーが出て使用ができませんでした。どちらか片方のみ読み込む場合は使えました。
![image](https://user-images.githubusercontent.com/132665310/236440398-5cd5fa8f-2f46-460a-b39c-f3a8b3a17c25.png)

**Comment by w-okada** [comment]
index, npyのファイルサイズが大きいと発生する可能性があります。ファイルサイズを教えていただけますか？

**Comment by goomy63** [comment]
npyが1.57GB、indexが1.62GBです。ずんだもんのROHAN4600を100epochで学習させています。

**Comment by w-okada** [comment]
なるほど。大きいですね。現在は、おそらくモデルも含め合計で２Gを超えると動かない仕様になっていると思います（裏のDBの仕様）。対策方法はDBを変え必要がありますが、それなりの開発が必要となるため、現時点では対応するか未定です。

**Comment by goomy63** [comment]
了解いたしました、対応ありがとうございました！
