### ISSUE TITLE
Index file cannot be located on Mac despite having the right extension

### ISSUE THREAD

**Issue by kalomaze** [w-okada/voice-changer#217]
![image](https://user-images.githubusercontent.com/66376113/236648500-b435a66e-05ec-4bf0-b33e-5b6dc3ef032b.png)
Possibly related to the RVC overhaul on April 28th which deprecated total_fea.npy

**Comment by w-okada** [comment]
I' check a few days later, because I have no enviroment to use mac.

**Comment by w-okada** [comment]
I checked but It's work fine. Can you re-recheck?

**Comment by kalomaze** [comment]
I submitted this on the behalf of another user (3lli3#3193 on Discord). I do not have the ability to reproduce in detail. For more information you can contact them

**Comment by kalomaze** [comment]
I contacted them again and they said they resolved the issue on their own, so this can be closed. My apologies for the false report
