### ISSUE TITLE
Model Load Error

### ISSUE THREAD

**Issue by Syobe** [w-okada/voice-changer#219]
.pthファイルを.onnxファイルにエクスポートした後、アップロードするとModel Load Errorが発生します
Windows10 / VC Client v.1.5.2.8 / cpuでエクスポートしました
AMD GPU/CPUを使用中です

**Comment by Syobe** [comment]
D:\VOICE\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 checkpoint_best_legacy_500.pt     --content_vec_500_onnx checkpoint_best_legacy_500.onnx     --content_vec_500_onnx_on false     --hubert_base hubert_base.pt     --hubert_base_jp rinna_hubert_base_jp.pt     --hubert_soft hubert-soft-0d54a1f4.pt     --nsf_hifigan nsf_hifigan/model
    Booting PHASE :__main__
    Voice Changerを起動しています。
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
VoiceChanger Initialized (GPU_NUM:0, mps_enabled:False)
[2023-05-09 07:48:55] connet sid : _IJpjvJHcOu7q2M1AAAC
[2023-05-09 07:48:55] connet sid : Ph5xciaJ0JiCCL3sAAAD
2023-05-09 07:48:56 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-05-09 07:48:56 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-05-09 07:48:56 | INFO | faiss.loader | Loading faiss.
2023-05-09 07:48:56 | INFO | faiss.loader | Successfully loaded faiss.
RVC initialization:  VoiceChangerParams(content_vec_500='checkpoint_best_legacy_500.pt', content_vec_500_onnx='checkpoint_best_legacy_500.onnx', content_vec_500_onnx_on=0, hubert_base='hubert_base.pt', hubert_base_jp='rinna_hubert_base_jp.pt', hubert_soft='hubert-soft-0d54a1f4.pt', nsf_hifigan='nsf_hifigan/model')
[Voice Changer] update configuration: dstId 1
[Voice Changer] update configuration: gpu -1
[Voice Changer] update configuration: crossFadeOffsetRate 0.1
CHAGE TO NEW PIPELINE False
[Voice Changer] update configuration: crossFadeEndRate 1
[Voice Changer] update configuration: crossFadeOverlapSize 1024
[Voice Changer] update configuration: framework PyTorch
[Voice Changer] update configuration: onnxExecutionProvider CPUExecutionProvider
[Voice Changer] update configuration: f0Detector harvest
[Voice Changer] update configuration: f0Factor 1
[Voice Changer] update configuration: silentThreshold 0.00001
f0Factor is not mutable variable or unknown variable!
[Voice Changer] update configuration: extraConvertSize 32768
onnxExecutionProvider is not mutable variable or unknown variable!
[Voice Changer] update configuration: clusterInferRatio 0.1
clusterInferRatio is not mutable variable or unknown variable!
[Voice Changer] update configuration: indexRatio 1
[Voice Changer] update configuration: modelSamplingRate 48000
[Voice Changer] update configuration: inputSampleRate 48000
[Voice Changer] update configuration: silenceFront 1
[Voice Changer] update configuration: enableDirectML 1
[Voice Changer] RVC new model is uploaded,0 {'pyTorchModelFile': None, 'onnxModelFile': 'C:\\Users\\ADM\\AppData\\Local\\Temp\\tmplxr4qkoz\\upload_dir\\0\\Sakura_voice_simple.onnx', 'featureFile': None, 'indexFile': None, 'defaultTrans': 0, 'isONNX': True, 'modelType': <EnumInferenceTypes.onnxRVCNono: 'onnxRVCNono'>, 'samplingRate': 48000, 'f0': False, 'embChannels': 256, 'deprecated': False, 'embedder': <EnumEmbedderTypes.hubert: 'hubert_base'>}
[Voice Changer] Prepare Model of slot: 0
[Voice Changer] exception! loading inferencer 'OnnxRVCInferencerNono' object has no attribute 'onnx_model'
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 24, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 20, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 56, in loadInferencer
  File "voice_changer\RVC\inferencer\OnnxRVCInferencerNono.py", line 19, in loadModel
AttributeError: 'OnnxRVCInferencerNono' object has no attribute 'onnx_model'
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 131, in loadModel
  File "voice_changer\RVC\RVC.py", line 86, in loadModel
  File "voice_changer\RVC\RVC.py", line 154, in prepareModel
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 54, in createPipeline
UnboundLocalError: local variable 'inferencer' referenced before assignment

[Voice Changer] Model Load Error! Check your model is valid. local variable 'inferencer' referenced before assignment







初期実行時にこのようなエラーも発生しますが、これが関連しているのでしょうか？


D:\VOICE\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 checkpoint_best_legacy_500.pt     --content_vec_500_onnx checkpoint_best_legacy_500.onnx     --content_vec_500_onnx_on false     --hubert_base hubert_base.pt     --hubert_base_jp rinna_hubert_base_jp.pt     --hubert_soft hubert-soft-0d54a1f4.pt     --nsf_hifigan nsf_hifigan/model
    Booting PHASE :__main__
    Voice Changerを起動しています。
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
 55%|██████████████████████████████████████████▌                                   | 98.6M/181M [00:01<00:01, 67.6MB/s]did-fail-load█▍                                                                     | 39.2M/361M [00:01<00:07, 43.9MB/s]
(node:12524) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
                                                                                                                       did-fail-load███████████████████████████████████████████████████████▎                 | 281M/361M [00:04<00:00, 111MB/s]
(node:12524) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
                                                                                                                       VoiceChanger Initialized (GPU_NUM:0, mps_enabled:False)

**Comment by Syobe** [comment]
確認してみたら正常に作動します！ ありがとうございました！
DirectML対応も期待します :D

**Comment by chuan6v** [comment]
ブラウザで次のURLを開いてください.
    https://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    https://localhost:18888/
    https://192.168.2.19:18888/
    Booting PHASE :MMVCServerSIO
VoiceChanger Initialized (GPU_NUM:1, mps_enabled:False)
这个是什么意思
