### ISSUE TITLE
Could you please tell me how to convert the source code in this repository into pre-compiled binaries?

### ISSUE THREAD

**Issue by g0m40** [w-okada/voice-changer#220]
Hello,

I hope this message finds you well. I came across your repository and I'm interested in building the source code to obtain pre-compiled binaries, such as the exe file and the "start_https.bat" script, etc. However, I'm not very familiar with the build process and I'm looking for detailed instructions.

I saw the [Checklist.md](https://github.com/w-okada/voice-changer/blob/master/Checklist.md) file in the repository that describes the release process, but it only provides a rough outline of the steps involved. I was wondering if you could help me out by providing more specific guidance on how to build the source code and generate the pre-compile binaries like [this](https://drive.google.com/uc?id=16wqbKi8F0tt2MqtgScA_STecpvaOgBIg&export=download).

Thank you in advance for your time and assistance.

**Comment by w-okada** [comment]
Currently I have not pushed the build script. under developing.
If you want to use this repository with your modification you can use this repository with Linux environment including wls2.
