### ISSUE TITLE
Non-matching sample rate causes gaps

### ISSUE THREAD

**Issue by MysteryPancake** [w-okada/voice-changer#223]
My microphone has a sample rate of 48,000 Hz
The model I'm using has a sample rate of 40,000 Hz.

I notice there are regular gaps in the output, even though my res time is much less than buf time.
This occurs when recording as well. The recording stays at 40,000, which causes it to go out of time.
The pitch also doesn't match up, it is a few semitones off (about as much as the sample rate difference).

I suspect this may be an issue due to the sample rate mismatch not being handled.

**Comment by w-okada** [comment]
Which VC do you use? RVC or so vits svc?
Both of them, I convert sampe rate.
https://github.com/w-okada/voice-changer/blob/e6938250b6a01920918006c27691dbbbd5f1aeba/server/voice_changer/VoiceChanger.py#L381

**Comment by MysteryPancake** [comment]
I tried both, RVC and so vits 4.

I noticed it happens even when the original model has a matching sample rate like 44100.
I tried time stretching the result and it caused the pitch to match up exactly.

I'm not sure what could be causing this. I am on windows, maybe it's a windows issue only.

**Comment by MysteryPancake** [comment]
This only affects "client device", "server device" works perfectly. I will use it instead for now :)

**Comment by w-okada** [comment]
OK. Close this issue.
