### ISSUE TITLE
プログラムで使用するモデルの選択を変更する際の問題

### ISSUE THREAD

**Issue by KBYSHanahira** [w-okada/voice-changer#224]
![image](https://github.com/w-okada/voice-changer/assets/85464400/db8184db-fe50-45b7-a144-08bc40ccbbdb)
型番0のみ使用可能です。
型番1・2を切り替えて使用することはできません。 モデル0は動作するだけで十分です。

Windows v.1.5.2.9b

**Comment by w-okada** [comment]
v.1.5.2.9cで修正しました。
