### ISSUE TITLE
weird lag with rvc

### ISSUE THREAD

**Issue by Fanlovegames** [w-okada/voice-changer#225]
When using the analyze feature, the voice sounds fine. But when output to a speaker or mixer, it starts to lag every 1 second or so. I am using a 1660s, don't know if it has anything to do with it.

**Comment by w-okada** [comment]
1660 is not high performance GPU.
Set your configuration for such GPU.
- Set input chunk num to 512 or more higher. 
- If not modified, set F0Detector to dio.

**Comment by Fanlovegames** [comment]
Thanks a lot. What kind of computer setup do your recommand? I'll go purchase a new computer for this.

**Comment by Fanlovegames** [comment]
also, i noticed that gpu is not used. It says
 [8516:0514/084334.336:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is

**Comment by w-okada** [comment]
the message is not from voice conversion AI model, but from GUI. You can ignore that.

detail is [here](https://stackoverflow.com/questions/67501093/passthrough-is-not-supported-gl-is-disabled), if you are interested in.

**Comment by w-okada** [comment]
no res. close
