### ISSUE TITLE
load rvc model wrong

### ISSUE THREAD

**Issue by theMilkyWay300** [w-okada/voice-changer#227]
![QQ截图20230514143902](https://github.com/w-okada/voice-changer/assets/83131829/f79e9ad7-1227-48c2-9ebb-523e6f60732c)
![QQ截图20230514144044](https://github.com/w-okada/voice-changer/assets/83131829/8cac5e5d-962c-442b-916d-11dc5d07718a)

**Comment by w-okada** [comment]
hubert seems to be not loaded correctly.
please re-install the package.

**Comment by w-okada** [comment]
close
