### ISSUE TITLE
音声変換時，やけに音が速い&途切れ途切れになる

### ISSUE THREAD

**Issue by cantflykite** [w-okada/voice-changer#229]
以下の動画のような症状です．
初期状態で撮っています．どのモデルでもこの症状が出ます．
"Output Record"で録音した音声では途切れることはないものの，やはり速いです．
https://youtu.be/5e6t9W7kmTw

念のためPC環境:
R7 5800X3D 
RTX 2080Ti 11GB
DDR4 8GBx4 32GB
windows 11 Pro

**Comment by cantflykite** [comment]
一日ただ起動しっぱなしにしていたら何故か直りました．
原因不明です...

**Comment by w-okada** [comment]
情報アップデートありがとうございます。
うーむ、謎ですね。。。とりあえず、解決としてcloseします。再発したら再オープンしてください。
