### ISSUE TITLE
複数スレッドからのfaiss呼び出しを回避する

### ISSUE THREAD

**Issue by nadare881** [w-okada/voice-changer#237]
faissは複数threadからバッチ実行を呼ぶ際、CPUコアよりも多くのスレッドが作成され非効率的になります。
https://github.com/facebookresearch/faiss/wiki/Threads-and-asynchronous-calls#performance-of-search

これを回避するために、`faiss.omp_set_num_threads()`関数を使ってスレッド数を適切に制限することでパフォーマンスを安定化させるのを提案します。
デフォルトではnum_threadsは論理プロセッサ数(os.cpu_count()の値)に設定されていますが、これを半分かそれ以下に制限することでパフォーマンスを向上できると思います。

自分のPCで行った実験結果です。
複数スレッドでindex.searchを実行すると、順番に実施した場合は各100ms x 24で2.4秒で終わるコードも、オーバーヘッドの影響により実行時間が増えていきます。
![実験結果](https://github.com/w-okada/voice-changer/assets/23290400/2e460927-7756-4989-aaad-a2151b0a60ff)

indexの高速化を行ってもCPU負荷があまり減らないのを疑問に思っていましたが、これの影響はありそうです。

**Comment by nadare881** [comment]
実際に組み込んで試したわけではないので、パフォーマンス変わらなかったら無視してください

**Comment by w-okada** [comment]
良いか悪いか別として歴史的な経緯などで、複数のスレッドで同時に音声変換は動けないようになっています。(起動時にuvicornにworkersを渡していないのでデフォルトで1になっていると思ってる。)

https://www.uvicorn.org/

マルチスレッドにしていない理由は、
単一のTorchモデルを複数のスレッドから触れない(と思ってるけど違ってたらすみません)からです。

Torchに食わせる前処理や、後処理をパイプライン的にしてTorchと関係ないところをマルチスレッド化することは考えられますが、今のところはそこまで作れていないですし、Torchの推論が前処理、後処理より遅いとそこで律速するので、マルチスレッド化する意味はあまりメリットがないかなと考えています。

なので、前処理、推論、後処理がすべてシングルスレッド内で実行されており、おそらく「複数スレッドでindex.searchを実行する」という状況になっていないのではないかと思います。

**Comment by nadare881** [comment]
ご回答いただきありがとうございます。
以前multiprocessingでのPRがあり、そこから勘違いしていました。

今回は、faissのindexを軽いものに変更してもCPU使用率があまり変わらないことや、処理時間のうちfaissは10%くらいなのにCPU使用率が一定になっているのが気になっていました。
処理を軽くできないかまた調べてみます。引き続きよろしくお願いいたします。
