### ISSUE TITLE
[Voice Changer] Index is None, not used

### ISSUE THREAD

**Issue by Jeffrey-deng** [w-okada/voice-changer#244]
**[Voice Changer] Index is None, not used**

First of all, thank you for the very useful tool.
I have set  `.pth` and `.index` file.
Voice changer is working, but it shows this in the log, are there any problems ?

```
[Voice Changer] update configuration: modelSlotIndex 1684754480000
[Voice Changer] Prepare Model of slot: 0
load inf models\rvc\0\1030zhiyan.pth
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] Loading index...
[Voice Changer] Index is None, not used
[Voice Changer] Prepare done.
[Voice Changer] Switch model 1 -> 0
[Voice Changer] Switching model..
[Voice Changer] Switching model..done
[Voice Changer] update configuration: modelSlotIndex 1684754481001
[Voice Changer] Prepare Model of slot: 1
```

### params.json

`{"defaultTune": 11, "defaultIndexRatio": 1, "sampleId": "", "files": {"rvcModel": "models\\rvc\\0\\1030zhiyan.pth", "rvcIndex": "models\\rvc\\0\\added_IVF1851_Flat_nprobe_1.index"}}`

![屏幕截图 2023-05-22 192928](https://github.com/w-okada/voice-changer/assets/21701421/0c5eb567-2e13-4f6f-973b-a31bde15c7fa)

**Comment by w-okada** [comment]
This software need npy too. Upload it.

**Comment by kassandr594** [comment]
> **[Voice Changer] Index is None, not used**
> 
> First of all, thank you for the very useful tool. I have set `.pth` and `.index` file. Voice changer is working, but it s
```javascript

``` `
> ```
> 
> ### pa

**Comment by w-okada** [comment]
For the next version, there will be no need to upload .npy files. Please wait.

**Comment by w-okada** [comment]
npy reconstruction is released. please use the latest version.
