### ISSUE TITLE
Methods of generating the client in the binaries

### ISSUE THREAD

**Issue by sunset1234321** [w-okada/voice-changer#247]
https://drive.google.com/uc?id=1m791W_wEx6TO135mEPNGngYBL4RLQvDO&export=download 

I guess the whole folder Is generated using some packager such as pyinstaller In the directory /server.

```
 if sys.platform.startswith("win"):
                process = subprocess.Popen(
                    [NATIVE_CLIENT_FILE_WIN, "-u", f"http://localhost:{PORT}/"]
                )
                return_code = process.wait()
```

From your code, it seems that this NATIVE_CLIENT_FILE_WIN will be inside sys._MEIPASS?  
However, I don't have this file in my sys._MEIPASS.

May you teach me how to prepare the client?

**Comment by w-okada** [comment]
??
Client is included in the package...
What is your issue?

**Comment by w-okada** [comment]
It looks like the file might be damaged. Could you try downloading it again?
