### ISSUE TITLE
server deviceが表示されません

### ISSUE THREAD

**Issue by vcusr** [w-okada/voice-changer#249]
![server_device_none](https://github.com/w-okada/voice-changer/assets/134348265/043c7bbd-8f77-47da-9635-6b1e89a9b8cd)

vc client楽しく使わせていただいております。
動作を軽くするためにBinary版からWSL2 + Aanaconda環境に移行しようと試行錯誤していたところ、
無事に起動まではたどり着けたのですが、server deviceモードに切り替えた際にデバイスが表示されない症状が
発生しました。

コンソールにも特にエラーは見当たらず、設定を切り替えた際にも
enableServerAudioの値が０、１で切り替わっているのが確認できます。

考えられる対策があればご教示いただきたいです。よろしくお願いいたします。

**Comment by w-okada** [comment]
おそらく、WSL2にマイクデバイスを認識させる必要があります。

やったことないですが、
https://learn.microsoft.com/ja-jp/windows/wsl/connect-usb
とかが参考になるのかもしれません。

**Comment by vcusr** [comment]
w-okada 様

早速のご回答ありがとうございます。
教えていただいたURLを基に試してみましたが、USBオーディオデバイスでは音が流せないようです。
別の方法でVCを利用させていただこうと思います。

応援しています、頑張ってください！
