### ISSUE TITLE
動作エラーについて

### ISSUE THREAD

**Issue by airoi** [w-okada/voice-changer#250]
初回起動時は問題なく使用できたのですが、2回目起動以降ボイスチェンジャーが機能しなくなりました。
monitor項目のvol,buf,resのうちvolの数値が0.0000から変わらないため正常に動作してないと思われます。
コマンドプロンプト上では
[16264:0523/221821.473:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
というエラーがでています。
エラーをchatGPTに投げたところグラフィック関連のエラーのようです。
使用した環境はGeforeceのRTX3060です。
正常に動作しないのはRTX3060ではスペック不足ということでしょうか？
ドライバは最新のものにしてあります。
それとも何か他に原因があるのでしょうか？
また最初に起動した時は正常に動作したことからフォルダごと削除してまた新しく構築すれば動作するかもと思ったのですが機能しませんでした。

**Comment by w-okada** [comment]
Passthrough is not supported, GL is disabled, ANGLE is
これはGUI画面からのメッセージで処理に関係はないです。

clear settingはしてみましたか？

**Comment by w-okada** [comment]
> monitor項目のvol,buf,resのうちvolの数値が0.0000から変わらない
ということはbuf,resは変わっているということでしょうか？

https://github.com/w-okada/voice-changer/blob/master/tutorials/trouble_shoot_communication_ja.md

どこまで正常に動いているか確認してみてください。

**Comment by airoi** [comment]
clear setiingも行いました。
![キャプチャ](https://github.com/w-okada/voice-changer/assets/134397947/697c599a-ec44-402f-8533-c04210eb1117)
buf,resは変動しています。
動作してた時はvolの数値も変動していました。
ドキュメントをみて動作確認してみましたが(1),(2),(3)いずれも音声が確認できませんでした。
録音できていないのかファイルの長さが0:00と表示されました。

コマンドプロンプトを再度確認してみたのですが、
(node:6492) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
という記述の部分が疑わしいと思いました。
ブラウザ上でURLにアクセスしようとすると拒否されましたという文がでます。
Windows Diffenderに引っかかってたりするのでしょうか？

**Comment by w-okada** [comment]
bufとresが変わっていて（１）がでないというのは、なかなか考えにくいです。。。
一つあり得るのはディスクの空き容量が無くて音声が録音できないとか？？？くらいしか思いつかない。
あとは、マイク設定間違ってないか、ですかね。

一度確認してみてもらえますか？

**Comment by airoi** [comment]
解決しました！
RVCでマイクの音声が認識できてなかったのが原因のようです。
マイク(audio Input)→RVCのところを
マイク(audio input)→仮想オーディオデバイス→RVCと変更することで使えるようになりました。
