### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'loadModel'

### ISSUE THREAD

**Issue by Kenpromiz** [w-okada/voice-changer#254]
please I get this error whenever I try to upload any model.

(1) RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

(2) AttributeError: 'NoneType' object has no attribute 'loadModel'
[Voice Changer] Model Load Error! Check your model is valid. 'NoneType' object has no attribute 'loadModel'
[9036:0525/050128.034:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is

![Screenshot (5)](https://github.com/w-okada/voice-changer/assets/130807993/b6b43cd3-9560-48ee-913d-542958e87556)

![Screenshot (4)](https://github.com/w-okada/voice-changer/assets/130807993/eb1e0cac-4239-4783-a434-24b19209889f)

please how do I resolve it.

**Comment by w-okada** [comment]
What about trying out a sample model? If it works, there might be something wrong with your model.

**Comment by Kenpromiz** [comment]
I tried it and it doesn’t work. When I first loaded the model it worked but when I existed and reopened the model I started getting the error.

**Comment by w-okada** [comment]
Okay.
It looks like your model is invalid, so when you try to launch the app, it can't read the model.

Delete the "models" folder, which is in the same folder as the ".bat" file. 
Then, try to restart the app and use a sample model instead. I think that should work. However, in order to fix the issue you'll need to use a valid model.

**Comment by Kenpromiz** [comment]
Please where can I get an already trained model to use

**Comment by Kenpromiz** [comment]
Here's the full log for the error I'm receiving.

C:\Users\PrOmIz\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/checkpoint_best_legacy_500.onnx     --content_vec_500_onnx_on false     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --model_dir models     --samples samples.json
    Booting PHASE :__main__
    Voice Changerを起動しています。
+    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

Preparing your application. Please wait...
(node:13416) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
VoiceChanger Initialized (GPU_NUM:1, mps_enabled:False)
[2023-05-26 12:03:18] connet sid : 1aFvYqm8Qk2SR-UnAAAC
[2023-05-26 12:03:18] connet sid : XO2SUTrhKYE-x9x2AAAD
PytorchStreamReader failed reading zip archive: failed finding central directory
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 281, in switchModelType
  File "voice_changer\RVC\RVC.py", line 72, in __init__
  File "voice_changer\RVC\RVC.py", line 166, in loadSlots
  File "voice_changer\RVC\ModelSlotGenerator.py", line 50, in generateModelSlot
  File "voice_changer\RVC\ModelSlotGenerator.py", line 55, in _setInfoByPytorch
  File "torch\serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

[Voice Changer] update configuration: dstId 1
[Voice Changer] update configuration: crossFadeEndRate 1
[Voice Changer] update configuration: crossFadeOverlapSize 1024
[Voice Changer] update configuration: framework PyTorch
[Voice Changer] update configuration: onnxExecutionProvider CPUExecutionProvider
[Voice Changer] update configuration: serverOutputAudioBufferSize 24576
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: serverOutputDeviceId -1
[Voice Changer] update configuration: serverReadChunkSize 256
[Voice Changer] update configuration: serverInputDeviceId -1
[Voice Changer] update configuration: extraConvertSize 32768
[Voice Changer] update configuration: diffMethod dpm-solver
[Voice Changer] update configuration: diffSpkId 1
[Voice Changer] update configuration: kStep 120
[Voice Changer] update configuration: inputSampleRate 48000
[Voice Changer] update configuration: diffAcc 20
[Voice Changer] update configuration: threshold -45
[Voice Changer] update configuration: f0Detector harvest
[Voice Changer] update configuration: serverInputAudioSampleRate 48000
[Voice Changer] update configuration: modelSamplingRate 48000
[Voice Changer] update configuration: serverInputAudioBufferSize 24576
[Voice Changer] update configuration: serverOutputAudioSampleRate 48000
[Voice Changer] update configuration: silenceFront 1
[Voice Changer] update configuration: useDiff 1
[Voice Changer] update configuration: f0Factor 1
[15664:0526/120336.791:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 299, in loadModel
AttributeError: 'NoneType' object has no attribute 'loadModel'

[Voice Changer] Model Load Error! Check your model is valid. 'NoneType' object has no attribute 'loadModel'



The model settings
![Screenshot (6)](https://github.com/w-okada/voice-changer/assets/130807993/13605771-da33-42e4-b71c-c63a3fa2b1ea)

**Comment by w-okada** [comment]
any update?
