### ISSUE TITLE
I open and there is no config.json file, and I don’t know where to import it. What’s the problem?

### ISSUE THREAD

**Issue by jiangxiaohuai520** [w-okada/voice-changer#256]
![Snipaste_2023-05-25_14-33-07](https://github.com/w-okada/voice-changer/assets/104884804/a59af0ff-91f5-40e8-810a-5252a132b429)

**Comment by w-okada** [comment]
Do you want to use MMVC? not RVC?

**Comment by w-okada** [comment]
no res
