### ISSUE TITLE
Voice Changer issue

### ISSUE THREAD

**Issue by benc1221** [w-okada/voice-changer#257]
When I use my rvc voice sometimes it sounds like it has auto tune   like a swallowed a mini PC, and im trying to figure out how to fix this issue. I made sure my dataset was clean from reverb, but I did built the voice using crepe. whenever I ran the model inference on the trainer it did not go out of pitch with that auto tuned sounding pitch voice cracks. It's only when I start to use the voice changer it does this. My chunk rate is at 768 and 32k extra data rate and I'm using server device exp along with DirectML.

**Comment by w-okada** [comment]
What GPU do you use?

**Comment by benc1221** [comment]
Rtx 2060 and im also having an issue where my voices sometimes sound like they have autotune enabled

**Comment by w-okada** [comment]
The version has been updated a lot already, so I cannot apologize enough, but could you please try it again with the newest version?

**Comment by w-okada** [comment]
no res close
