### ISSUE TITLE
モデルを読み込んでも声は出るが変な感じに変換される

### ISSUE THREAD

**Issue by suguriechan** [w-okada/voice-changer#259]
Vc Clientで学習させたデータを使って声を出しても声は出るのですが元の声にそぐわないおかしな声になってしまいます（例:あいうえおと発音すると変換先でははひふふほのような原型をとどめていない発音になる）。どうすれば治すことができるでしょうか？

**Comment by w-okada** [comment]
TwitterでDMいただいた方だと思います。input chunk numとextra data lengthの値をかえることで　ひとまず解決したという理解です。closeします。もし違った場合は再度オープンしてください。
