### ISSUE TITLE
Failed to run

### ISSUE THREAD

**Issue by pz9k** [w-okada/voice-changer#260]
Hey guys, the vc server is correctly running before. 
But it got errors since I reclone it today, and it can not show any traceback info.
I clicked the buttons to restart it, but the same problem and no traceback.
![1](https://github.com/w-okada/voice-changer/assets/128797321/446c853d-d1a7-4621-acc7-28ce79ced820)
![2](https://github.com/w-okada/voice-changer/assets/128797321/d41e2f83-6652-4225-b819-ab0a8f330c0d)

**Comment by pz9k** [comment]
the project run properly with last version, but after the latest update, it can not be used anymore.

**Comment by w-okada** [comment]
I'll check it

**Comment by pz9k** [comment]
Sry, maybe it was my problem. 
The vc server can not lunched cause it failed to download weight models. 
I copied the models from my local PC, and the server run properly.
It seems the urls in the code has invalidated, check it plz.
The issue has been solved, thank you author.

**Comment by pz9k** [comment]
Sry, maybe it was my problem. 
The vc server can not lunched cause it failed to download weight models. 
I copied the models from my local PC, and the server run properly.
It seems the urls in the code has invalidated, check it plz.
The issue has been solved, thank you author.
