### ISSUE TITLE
downloadしたモデルの種類がunknownだとGPUが使用されない

### ISSUE THREAD

**Issue by nadare881** [w-okada/voice-changer#264]
Model Settingでfrom netのall > 下の方のVCモデルを選択すると、modelの種類がunknownで表示される
例: [f0, 40k, 768, unknown]
これを実行するとGPUが使われずCPUですごい負荷がかかってresが重くなる

自分の手元のv1モデルは5/28/17:27時点のmasterで動いています

**Comment by nadare881** [comment]
だだっこぱんださんのwebuiで学習したモデルをonnxに出力するとunknownになってgpuが使えませんでした
5/29時点のmasterで動かしてます

**Comment by w-okada** [comment]
v.1.5.3.4で対応していると思います。ご確認ください。
