### ISSUE TITLE
[再現方法特定?]音声変換時，やけに音が速い&途切れ途切れになる

### ISSUE THREAD

**Issue by cantflykite** [w-okada/voice-changer#265]
PS4のコントローラーをPCにUSBで接続しているときにこの症状が発生することがわかりました．
そのほかのUSBオーディオデバイスでも同様の問題が発生するかは環境がないのでできていません．

#####
以下の動画のような症状です．
初期状態で撮っています．どのモデルでもこの症状が出ます．
"Output Record"で録音した音声では途切れることはないものの，やはり速いです．
https://youtu.be/5e6t9W7kmTw

実行環境:
windows 11 Pro 22H2
MMVCServerSIO_win_onnxgpu-cuda_v.1.5.2.9e
R7 5800X3D
RTX 2080Ti 11GB
DDR4 8GBx4 32GB

**Comment by w-okada** [comment]
情報ありがとうございます！
どういう理屈でそうなっているのか全く想像でいませんが、
おそらくＡＩの変換部分というより、音声のサンプリング部部で問題が起こっているのではないかと推測します。

お手数ですが、
https://github.com/w-okada/voice-changer/blob/master/tutorials/trouble_shoot_communication_ja.md
を参考にして、モデルへのinputとoutputがどのようになっているか確認していただけあないでしょうか。

**Comment by w-okada** [comment]
すみません。アップデートがないのでいったん閉じます。もし何かあればお気軽に再オープンしてください。
