### ISSUE TITLE
The problem of not being able to change the voice normally

### ISSUE THREAD

**Issue by Windows1122H2** [w-okada/voice-changer#267]
Hay

May I ask why the translated voice cannot be output normally when I use it normally, that is, it cannot be used normally, and I cannot hear normal voices, only fragmentary voices.

I'm more than happy to provide a video if needed

**Comment by Windows1122H2** [comment]
The actual situation is that it can be used normally when it is turned on for the first time, but it cannot be used normally after restarting, and only fragmentary sounds can be heard. This has caused me a lot of trouble, because it means that every time I use it, I need to reinstall the system

**Comment by w-okada** [comment]
Which version are you using?
What is your gpu?
What is your CPU?

**Comment by Windows1122H2** [comment]
> 您使用的是哪個版本？您的 GPU 是什麼？您的CPU是什麼？

Hello

I am currently using Windows 11 Pro system, the CPU used is 5800X GPU is 3060Ti GDDR6 8G

**Comment by Windows1122H2** [comment]
> 您使用的是哪個版本？您的 GPU 是什麼？您的CPU是什麼？
The latest version and the old version are also used, they are not started on the same system, and there is no mixed use

**Comment by Windows1122H2** [comment]
Even if it is used in combination, it can still be used normally without shutting down the computer until the system is restarted.

**Comment by Monodesu** [comment]
I have the same issue as well, using the latest driver, lastest windows11 pro and the latest build of voice-changer
Hardware info: RTX4070ti with i7-12700k
I have confirmed that after reinstalling the operating system, the voice-changer worked fine before the system restart.

**Comment by Windows1122H2** [comment]
> 我也有同樣的問題，使用最新的驅動程式，最新的windows11 pro和最新版本的語音轉換器硬體資訊：RTX4070ti與i7-12700k 我已經確認重新安裝作業系統後，語音轉換器在系統重新啟動之前工作正常。
> 
> 我還注意到“res（ms）”的值不斷增加，表明可能存在口吃或其他導致此問題的原因。 [BUF（毫秒） 80 解析度（毫秒）40528]

I think the problem is the following

[15164] Failed to execute script 'MMVCServerSIO' due to unhandled exception!
ERROR:    Traceback (most recent call last):
  File "starlette\routing.py", line 674, in lifespan
  File "uvicorn\lifespan\on.py", line 137, in receive
  File "asyncio\queues.py", line 159, in get
asyncio.exceptions.CancelledError

**Comment by w-okada** [comment]
I'm sorry, I'm thoroughly confused about what issue is . Would you please reorganize the problem and create a new issue? I apologize for the inconvenience, but I'm going to have to close this issue.
