### ISSUE TITLE
client for RVC で model setting が開けない

### ISSUE THREAD

**Issue by oniatsu** [w-okada/voice-changer#269]
client for RVC で model setting が開けない症状が発生しています

症状としては、クライアントから
/model_type
にアクセスできない時点で処理が止まってしまっているようです。（Chrome Dev Tools で見ると pending から進まない）
RVC以外でのVCでは model setting を開けます。
結果的に model の指定ができないため音声変換ができません。

参考: 以下のUIのように model setting の詳細欄が表示されない
![image](https://github.com/w-okada/voice-changer/assets/5919569/6f398037-68dc-4050-8dff-9e7236a41875)

事前ビルド済みのバイナリーでは実行できているのですが、変更を加えたいため、環境構築した上で実行したい状況です。

原因に心当たりなどあれば助言ください。よろしくお願いします。

## 環境
[Docker の annaconda 環境](https://hub.docker.com/u/continuumio)
```bash
docker pull continuumio/anaconda3
```

必要なパッケージをインストール（pip install 時にビルド時に要求されたりスクリプト実行時に要求されるため）
```bash
# cmake (apt install では cmake のバージョンが古いため新しいバージョンをインストール）
cd /opt
wget https://github.com/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4-linux-aarch64.sh
chmod +x /opt/cmake-cmake-3.26.4-linux-aarch64.sh
bash /opt/cmake-cmake-3.26.4-linux-aarch64.sh
ln -s /opt/cmake-cmake-3.26.4-linux-aarch64/bin/* /usr/local/bin

apt update
apt install build-essential # gcc
apt install libportaudio2 # PortAudio
apt install libsndfile-dev # libsndfile.so
```

その後、以下に従って環境構築して起動
https://github.com/w-okada/voice-changer/blob/master/README_dev_ja.md

ただし、requirements.txt で以下のように変更しました。
onnxruntime-gpu が pip install できなかったため。
```diff
+ onnxruntime==1.14.1
- onnxruntime-gpu==1.14.1
```

**Comment by oniatsu** [comment]
どこで止まっているかを追ってみたところ、以下の onnxruntime.InferenceSession() で止まっているように見え、requirements.txt の差分が悪さしているかもしれません…
GPUがない環境では onnxruntime-gpu の代わりに onnxruntime で良いのではと考えていたのですが、これが誤りだったのかもしれません
https://github.com/w-okada/voice-changer/blob/master/server/voice_changer/RVC/ModelSlotGenerator.py#L141-L143
```python
    tmp_onnx_session = onnxruntime.InferenceSession(
        slot.modelFile, providers=["CPUExecutionProvider"]
    )
```

**Comment by w-okada** [comment]
onnx 1.14.1はバグが入っているので、1.13.1をお使いください。

**Comment by w-okada** [comment]
https://github.com/microsoft/onnxruntime/issues/15745
