### ISSUE TITLE
Everything is working properly, but the sound will continue to stutter.

### ISSUE THREAD

**Issue by cancanlcanl** [w-okada/voice-changer#270]
May I ask what the problem is.And is there a solution to this problem.

**Comment by w-okada** [comment]
Set the input chunk num to roughly 512, and the extra data length to 4096 first. If that works well, gradually decrease the extra data length until it feels comfortable. Next, decrease the input chunk num until a comfortable setting is reached. That should be close to the optimum setting for your environment.

**Comment by w-okada** [comment]
no res close

**Comment by cancanlcanl** [comment]
Thank you very much!!!
