### ISSUE TITLE
protect対応 + crepe修正

### ISSUE THREAD

**Issue by nadare881** [w-okada/voice-changer#271]
serverサイドでのprotectの引数・機能の追加と、crepeの対応であれば軽く実装できそうなので巻き取れると思います。
一時間もせずサクッと移植できると思うので、対応まだであれば書いてPR出します。

https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/c2f402d7d19dcb58f30d8eafeaf4551d4868d5ba/Changelog_EN.md?plain=1#L3

**Comment by w-okada** [comment]
すみませんが、全く手を付けておりませんので、お願いできますでしょうか。
