### ISSUE TITLE
failed in preparing you r application

### ISSUE THREAD

**Issue by shum-elli** [w-okada/voice-changer#273]
![image](https://github.com/w-okada/voice-changer/assets/79710429/a485c213-032f-44a1-93da-24886c523acc)
i run the start_http.bat and i get such  message, i run it successfully in another computer,but i don't know why it happened,we are in same internet environment,model can be downloaded properly.
Please give me some advice to solve it

**Comment by w-okada** [comment]
I'm not sure, but if it's working on other PCs, I think it might be a problem specific to this PC. Maybe take a look at the OS settings like firewall, etc.?

**Comment by w-okada** [comment]
no res close
