### ISSUE TITLE
Upload stops 97.3%

### ISSUE THREAD

**Issue by netis90** [w-okada/voice-changer#274]

**Comment by netis90** [comment]
i uploaded pth file to rvc and upload stops 97.3% 
![캡처_2023_05_31_22_04_27_903](https://github.com/w-okada/voice-changer/assets/135132404/392ebb2b-a541-41d4-bc94-e3b31057ba83)
![캡처_2023_05_31_22_04_40_192](https://github.com/w-okada/voice-changer/assets/135132404/736bc104-3cc7-46e9-a920-8b398150a78c)
please check attach files

**Comment by w-okada** [comment]
This is the first time I have seen the file path delimiter that you presented in the logs. It may be the cause. What is the language setting for your operating system?

**Comment by netis90** [comment]
korean and i solve problem to use 1.5.2.3 version thank you for fast reply

**Comment by w-okada** [comment]
OK! 💯
