### ISSUE TITLE
DirectML not available on Win10 21H2

### ISSUE THREAD

**Issue by DJRaov** [w-okada/voice-changer#277]
When attempting to enable DirectML, the console spits out a note that "DML is not available."
Installed DirectML via pip on the local system, to no avail.
Running Win10 21H2 IoT LTSC with AMD's RX 580, precompiled archive from the downloads in README.
![image](https://github.com/w-okada/voice-changer/assets/29620190/39e38915-c99c-4c36-86c3-78a8a71828ee)

What can I try to get it to work? If DirectML won't be an option, how do I enable ONNX GPU acceleration?

**Comment by w-okada** [comment]
I released software with onnxruntime-directml experimentaly, try it. v.1.5.3.4

**Comment by DJRaov** [comment]
Thank you, seems to work slightly faster now. GPU_NUM is still zero but I think that is due to how DirectML works.
Also noticed the new F0 detector, very accurate but quite slow and needs some tuning. Nice addition.
Looking forward to a stable DirectML version!
