### ISSUE TITLE
Docker build failing due to incompatible pytorch version

### ISSUE THREAD

**Issue by shep920** [w-okada/voice-changer#278]
I was using a fresh install of aws linux. 

My steps where the following:

```
git clone https://github.com/w-okada/voice-changer.git

cd voice-changer

npm install
npm run build:docker:vcclient

```

The error occurred during 
npm run build:docker:vcclient

The error was:

 => [ 5/41] RUN pip install numpy==1.23.5                                                                                                                              5.0s
 => ERROR [ 6/41] RUN pip install torch==1.13.1                                                                                                                       24.3s
------
 > [ 6/41] RUN pip install torch==1.13.1:
#9 1.254 Collecting torch==1.13.1
#9 1.343   Downloading torch-1.13.1-cp310-cp310-manylinux1_x86_64.whl (887.5 MB)
#9 23.99      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━        734.4/887.5 MB 6.2 MB/s eta 0:00:25
#9 24.04 ERROR: Exception:
#9 24.04 Traceback (most recent call last):
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
#9 24.04     yield
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py", line 519, in read
#9 24.04     data = self._fp.read(amt) if not fp_closed else b""
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_vendor/cachecontrol/filewrapper.py", line 94, in read
#9 24.04     self.__buf.write(data)
#9 24.04   File "/usr/lib/python3.10/tempfile.py", line 622, in func_wrapper
#9 24.04     return func(*args, **kwargs)
#9 24.04 OSError: [Errno 28] No space left on device
#9 24.04 
#9 24.04 During handling of the above exception, another exception occurred:
#9 24.04 
#9 24.04 Traceback (most recent call last):
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
#9 24.04     status = run_func(*args)
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
#9 24.04     return func(self, options, args)
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 339, in run
#9 24.04     requirement_set = resolver.resolve(
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
#9 24.04     result = self._result = resolver.resolve(
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
#9 24.04     state = resolution.resolve(requirements, max_rounds=max_rounds)
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
#9 24.04     self._add_to_criteria(self.state.criteria, r, parent=None)
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
#9 24.04     if not criterion.candidates:
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
#9 24.04     return bool(self._sequence)
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
#9 24.04     return any(self)
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
#9 24.04     return (c for c in iterator if id(c) not in self._incompatible_ids)
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
#9 24.04     candidate = func()
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 215, in _make_candidate_from_link
#9 24.04     self._link_candidate_cache[link] = LinkCandidate(
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 288, in __init__
#9 24.04     super().__init__(
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
#9 24.04     self.dist = self._prepare()
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
#9 24.04     dist = self._prepare_distribution()
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 299, in _prepare_distribution
#9 24.04     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 487, in prepare_linked_requirement
#9 24.04     return self._prepare_linked_requirement(req, parallel_builds)
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 532, in _prepare_linked_requirement
#9 24.04     local_file = unpack_url(
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 214, in unpack_url
#9 24.04     file = get_http_url(
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 94, in get_http_url
#9 24.04     from_path, content_type = download(link, temp_dir.path)
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_internal/network/download.py", line 146, in __call__
#9 24.04     for chunk in chunks:
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_internal/cli/progress_bars.py", line 304, in _rich_progress_bar
#9 24.04     for chunk in iterable:
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_internal/network/utils.py", line 63, in response_chunks
#9 24.04     for chunk in response.raw.stream(
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py", line 576, in stream
#9 24.04     data = self.read(amt=amt, decode_content=decode_content)
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py", line 512, in read
#9 24.04     with self._error_catcher():
#9 24.04   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
#9 24.04     self.gen.throw(typ, value, traceback)
#9 24.04   File "/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py", line 455, in _error_catcher
#9 24.04     raise ProtocolError("Connection broken: %r" % e, e)
#9 24.04 pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: OSError(28, 'No space left on device')", OSError(28, 'No space left on device'))
------
executor failed running [/bin/sh -c pip install torch==1.13.1]: exit code: 2

**Comment by grimoire-vc** [comment]
You probably have to run
> sudo apt-get install npm
I also found that I had to run these:
> distribution=$(. /etc/os-release;echo $ID$VERSION_ID)       && curl -s -L https://nvidia.github.io/libnvidia-container/gpgkey | sudo apt-key add -       && curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
> sudo apt-get update
> sudo apt-get install -y nvidia-docker2
> sudo systemctl restart docker
Then try running it again.
The docker version seems to be quite outdated though, like over a month outdated. I wasn't able to run RVC v2 models on it because it wasn't a version of voice-changer that supported v2 models. It did seem like it was more GPU efficient though, but it's hard to know for sure since conditions were different.

**Comment by shep920** [comment]
> You probably have to run
> 
> 
> 
> > sudo apt-get install npm
> 
> 
> 
> I also found that I had to run these:
> 
> 
> 
> > distribution=$(. /etc/os-release;echo $ID$VERSION_ID)       && curl -s -L https://nvidia.github.io/libnvidia-container/gpgkey | sudo apt-key add -       && curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
> 
> 
> 
> > sudo apt-get update
> 
> 
> 
> > sudo apt-get install -y nvidia-docker2
> 
> 
> 
> > sudo systemctl restart docker
> 
> 
> 
> Then try running it again.
> 
> 
> 
> The docker version seems to be quite outdated though, like over a month outdated. I wasn't able to run RVC v2 models on it because it wasn't a version of voice-changer that supported v2 models. It did seem like it was more GPU efficient though, but it's hard to know for sure since conditions were different.

Thanks for the heads up, im pretty new to Docker. Have you had any luck getting a successful container built? And what voice cloner repo are you having the most luck with if this one's not being updated?

**Comment by grimoire-vc** [comment]
Yes, I got voice-changer running okay on Docker. It just needs some updating I think.

I haven't looked for any repo that can run in Docker, I just tested it out with this one because it seemed interesting. The regular Windows executable version serves my needs fine enough, so I didn't bother looking for an alternative.

**Comment by grimoire-vc** [comment]
I should add: this repo is being updated constantly, just not the Docker portions of it. For other platforms it is updated all the time and supports newer features of all the open source voice changing platforms I'm aware of.

**Comment by w-okada** [comment]
I updated Dockerfile yesterday. Please try it.
