### ISSUE TITLE
uploading feature index to rvc

### ISSUE THREAD

**Issue by benc1221** [w-okada/voice-changer#279]
i realized when i upload this file and use 1 index ratio the voice pitch sounds all warbly and when i set it to 0.4 it sounds fine  but when i just upload the pth or onnx file it sounds great. anything that can cause this issue to happen?

**Comment by w-okada** [comment]
I'm not sure. Does the preset model work fine? If so, then there could be some issues with the model.

**Comment by benc1221** [comment]
no it suffers the same issue with the pitch warbling when i use feature index ratio

**Comment by w-okada** [comment]
Using an Index will take up CPU power. As long as you don't set the value to 0, the same amount of load should still remain. If there is an issue when it's not 0, it's possible the CPU is being overloaded. Increasing the input chunk num value might help to resolve the problem.

**Comment by benc1221** [comment]
what does silence supposed to do?

**Comment by benc1221** [comment]
i noticed that its is not using my cpu at all for both server device and client device i also see when i use crepe its using my gpu as intended but my cpu is never being utilized even when i upped the chunk number and i used harvest mode and its not using my cpu it 3%-5%

**Comment by benc1221** [comment]
will you implement mangio's hyrbid f0 detection to the voice changer? im quite intrested in seeing how it would work there

**Comment by benc1221** [comment]
is there a way for me to also use realtime rvc coversion via paperspace or that is not supported?
