### ISSUE TITLE
when i run MMVCServerSIO.app，i get below error 

### ISSUE THREAD

**Issue by xvm03** [w-okada/voice-changer#280]
~ /var/folders/cc/86zzy2413gxcrb9lkq4g5sx80000gn/T/AppTranslocation/B8719269-2E1B-49D4-912D-186DD644D3BE/d/MMVCServerSIO.app/Contents/MacOS/MMVCServerSIO ; exit;  (base) 10:11:21
    Booting PHASE :__main__
    Voice Changerを起動しています。
Traceback (most recent call last):
  File "MMVCServerSIO.py", line 231, in <module>
  File "MMVCServerSIO.py", line 122, in downloadWeight
  File "genericpath.py", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
[53450] Failed to execute script 'MMVCServerSIO' due to unhandled exception: stat: path should be string, bytes, os.PathLike or integer, not NoneType
[53450] Traceback:
Traceback (most recent call last):
  File "MMVCServerSIO.py", line 231, in <module>
  File "MMVCServerSIO.py", line 122, in downloadWeight
  File "genericpath.py", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by w-okada** [comment]
Have you read Readme?

**Comment by xvm03** [comment]
sorry, my english is  not very good 

i follow this https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md


i click the startHttp.command,and see this page,then click the rvc,but get :

<img width="1033" alt="image" src="https://github.com/w-okada/voice-changer/assets/1897543/30521014-a6af-4cc9-8932-52d5f4a49f80">

when i click first button

<img width="727" alt="image" src="https://github.com/w-okada/voice-changer/assets/1897543/6b48ca11-2d78-4f21-9c53-54fb8bd64ddf">

the terminal have these error

**Comment by xvm03** [comment]
my rvc running on a cloud GPU service platform,i want to use your client to connect

**Comment by w-okada** [comment]
If you want to use client from remote, use https.command instead of http.command.

**Comment by xvm03** [comment]
thanks，my computer is mac pro (Apple M1 Max)  , i use startHttps.command，also meet these error:
1.visit localhost:1888
![image](https://github.com/w-okada/voice-changer/assets/1897543/96e748b8-24c2-41f4-a9b5-3b9bbbe3f726)

2.
![image](https://github.com/w-okada/voice-changer/assets/1897543/843d51c4-1656-4c3b-aa16-db123a2df216)

3.the localhost:1888，can't visit

terminal have these error 


[2023-06-06 13:43:46] connet sid : SMKHBXGJz3JkwKILAAAC
[2023-06-06 13:43:46] connet sid : tj7jXT6HFR4SZuvHAAAD
/Users/xumingming/Downloads/MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.4/startHttps.command: line 31: 66448 Killed: 9               PYTORCH_ENABLE_MPS_FALLBACK=1 ${curdir}/MMVCServerSIO.app/Contents/MacOS/MMVCServerSIO --https on -p 18888 --content_vec_500 ${curdir}/pretrain/checkpoint_best_legacy_500.pt --content_vec_500_onnx ${curdir}/pretrain/checkpoint_best_legacy_500.onnx --content_vec_500_onnx_on false --hubert_base ${curdir}/pretrain/hubert_base.pt --hubert_base_jp ${curdir}/pretrain/rinna_hubert_base_jp.pt --hubert_soft ${curdir}/pretrain/hubert-soft-0d54a1f4.pt --nsf_hifigan ${curdir}/pretrain/nsf_hifigan/model --model_dir ${curdir}/models --samples ${curdir}/samples.json

**Comment by w-okada** [comment]
What browser do you use? Only chrome is supported.

**Comment by xvm03** [comment]
i use chrome

**Comment by xvm03** [comment]
i try use docker ,but also meet some error : 

#14 55.91   Downloading python_multipart-0.0.6-py3-none-any.whl (45 kB)
#14 55.92      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 KB 5.1 MB/s eta 0:00:00
#14 56.19 ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.15.0 (from versions: none)
#14 56.20 ERROR: No matching distribution found for onnxruntime-gpu==1.15.0
------
executor failed running [/bin/sh -c pip install -r requirements.txt]: exit code: 1

**Comment by w-okada** [comment]
how about just run

``` 
bash start_docker.sh
```

**Comment by pirahtays** [comment]
I get a similar issue on my mac running 1.5.3.4 with the electron client suddenly not connecting.  When running HTTPS I can see that the backend process dies for some reason.

<img width="1001" alt="image" src="https://github.com/w-okada/voice-changer/assets/35934562/e0f6ee43-02b0-47fa-99d5-8b1d1b6a6b81">

1.5.3.3b seems to work but does throw a ton of `WARNING:  Invalid HTTP request received.` errors when using the native client

**Comment by w-okada** [comment]
@xvm03

no response, I will close.

@pirahtays 
I need more information in order to guess the problem. Please provide more details about what behavior is occurring. It doesn't appear that any error message is being displayed on the console.  This may not be the same as the original issue. Please open a new issue.
