### ISSUE TITLE
Index ratio Increases Res

### ISSUE THREAD

**Issue by benc1221** [w-okada/voice-changer#288]
i had been keeping an eye on the monitor and when ever i use the feature index file the res number goes up i am wondering if something is wrong with these files

**Comment by w-okada** [comment]
Using a Feature file requires additional processing, so it is normal for CPU usage and response time to increase. It cannot be said for sure if there is a problem with the Feature file. 

Try out the latest version (v.1.5.3.4c), which has been slightly lightened up.

**Comment by benc1221** [comment]
what does directml do here?

**Comment by w-okada** [comment]
use onnx-directml instead of onnx-cuda.

https://onnxruntime.ai/

If you have no plan to use onnx, use cuda version.
