### ISSUE TITLE
Sound problems after restarting the desktop

### ISSUE THREAD

**Issue by Windows1122H2** [w-okada/voice-changer#292]
After reinstalling the system, everything is normal, but the sound is intermittent after restarting the system, and the sound cannot be changed normally

**Comment by w-okada** [comment]
This is a phenomenon that I have never heard of before. It cannot be replicated. Are there any other people with the same phenomenon?

**Comment by Windows1122H2** [comment]
> This is a phenomenon that I have never heard of before. It cannot be replicated. Are there any other people with the same phenomenon?

I use the Windows 11 Pro system, it was normal when I used it for the first time, and the sound was intermittent after restarting, but the latest version seems to have solved this problem. But now you need to solve the problem of system resource scheduling, because he will not regularly increase the CPU load to 100% and cause system overload problems

**Comment by w-okada** [comment]
Your problem is solved?
If there are other issue, please open new issue.
