### ISSUE TITLE
Discord/dev community?

### ISSUE THREAD

**Issue by shep920** [w-okada/voice-changer#294]
No technical problem, but is there any community like a discord for this project yet? I'd like to understand it better.

**Comment by Foul-Tarnished** [comment]
+1

Also can somebody upload some examples ? I don't really get what this can actually do

**Comment by marrie** [comment]
I’ll add my voice to this.

**Comment by w-okada** [comment]
this server has the thread for vcclient. Mainly japanese, but english is ok.

https://discord.gg/bmNezxjCq2
