### ISSUE TITLE
The Start Voice Conversion Keeps On Stopping And Starting

### ISSUE THREAD

**Issue by tomas122727** [w-okada/voice-changer#296]
### Issue Type

Bug Report

### vc client version number

v.1.5.3.3.4c

### OS

Windows 11 Pro

### GPU

NVIDIA GeForce MX330

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Voice Changer type

RVC v.1.5.3.3.4c

### Model type

RVC

### Situation

starting the voice changer just like is stops then starts again

**Comment by tomas122727** [comment]
additional info this doesent do this on so vits

**Comment by w-okada** [comment]
same?

https://github.com/w-okada/voice-changer/issues/270#issuecomment-1577874569

**Comment by tomas122727** [comment]
it doesent do it on so vits svc 4.0 models just on rvc section voice changer it starts and stops

**Comment by w-okada** [comment]
1. The problem won't occur with so-vits-svc4.0.
2. The problem occurs with RVC.

Is this understanding correct?

If yes, this is natural because RVC is diffrent from so-vis-svc4.0.
One way to prevent audio conversion from breaking is to increase the input chunk num.

**Comment by w-okada** [comment]
no res close
