### ISSUE TITLE
The RVC voice conversion is chopping

### ISSUE THREAD

**Issue by Monodesu** [w-okada/voice-changer#297]
### Issue Type

Bug Report

### vc client version number

1.5.3.4d

### OS

windows11 pro

### GPU

rtx4070ti

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

The real-time voice conversion effect is very poor. #267  This issue has been previously reported as an issue, but there are no error prompts, and the voice is extremely choppy.

screenshots
https://imgur.com/kBXVleN
https://imgur.com/H9LM6Gi
https://imgur.com/7TNYdqg

As you can see, res(ms) is continue increase when im speaking, the output voice is extremely choppy, after the engine completed processing, the value will become normal.

I have no knowledge in this area and unable to debugging it.  Sorry about that. However, If there's any information you need, I can provide it to the best of my ability.

**Comment by w-okada** [comment]
Have you tried set input chunk num large value? for example 512 or more.

**Comment by Monodesu** [comment]
> 

^Yes, I have tried everything I can do.

**Comment by w-okada** [comment]
The main cause  res(ms) is continue increase  Generally, the higher the res value is, the lower the input chunk num is. If this value is increased and it causes audio stutters, it's usually because the CPU or GPU is not performing sufficiently.

What is the usage rate of the CPU and GPU?
Is there any other heavy app running if it is at 100%?

**Comment by Monodesu** [comment]
No, only voice-changer runs, and when not running it, my GPU usage is only 1% -2%. But when I run it, the GPU will remain at 40-70% until the audio starts to input, and it will directly become 100%. CPU usage not changed much.

**Comment by Monodesu** [comment]
I mentioned before that during the first fresh installation of the operation system, it ran perfectlly until system was restarted

**Comment by Monodesu** [comment]
weird. After I switched to microphone input, the GPU usage rate actually decreased, and the CPU usage began to 100%

here's screenshot
https://imgur.com/siv7P74

**Comment by w-okada** [comment]
increase input chunk num.

**Comment by Monodesu** [comment]
“res" is not keep increasing, but voice still extremely choppy

also fresh installation of the operation system, it can set to 32 chunk num without issue.

https://imgur.com/UTV8DzY

**Comment by w-okada** [comment]
set index ratio to 0
set silet threshold to 0

**Comment by Monodesu** [comment]
https://imgur.com/ZRVRnuE
No. Same as before, If possible, you can directly check for the problem on my pc, I don't really mind it

**Comment by Monodesu** [comment]
I remember it's after restart, and confirm voice-changer is not working well, after that I go install Nvidia Boardcast to see if it's my microphone's issue or not. I could do another fresh install but it takes time, I'll post the result here later, about 20min

**Comment by Monodesu** [comment]
Ok Here's fresh new system, Installed all of drivers and rebooted, this is the first time i run voice-changer, everything works well.
https://imgur.com/ZmFuIQb

**Comment by Monodesu** [comment]
And before next restart, No matter how many times I reopen voice-changer, it's just run perfectlly.
Now I'm going to restart pc one more time.

**Comment by Monodesu** [comment]
After few times of reboot, the voice-changer still works well, so It's not about voice-changer itself,I'm trying to find out what is causing it to not work properly

**Comment by w-okada** [comment]
OK. Great! Please let me know if you get any hints.

**Comment by Monodesu** [comment]
I set up Nvidia Boardcast, Virtual Audio devices, and other software i need, it still works properly....
I'm confuse right now

**Comment by w-okada** [comment]
No problem. Let me know if you figure anything out. Also, if you like using it, please introduce it to your friends.

Let's close the issue for now.

**Comment by Monodesu** [comment]
Sure thing! Thanks for the help!  It's very late, Thanks.

**Comment by Monodesu** [comment]
Ok, Got the problem.
Can't set your playback audio device's bit and frequency too high, or it cause this problem.
I set it to 24bits and 192000Hz, the problem has arisen again.
See the screenshot.
https://imgur.com/U6DkTwe

Hope this could help. @Windows1122H2

**Comment by Monodesu** [comment]
Maybe it's a bug, so you might need to reopen this issue.

**Comment by w-okada** [comment]
For now, that's how it's designed - Chrome's default is to only handle 48K and the same goes for other browsers.

**Comment by Monodesu** [comment]
Oh.. sad to hear that

**Comment by w-okada** [comment]
You might be able to make it work using a server device mode. Have you tried it yet?

**Comment by Monodesu** [comment]
I did not, trying now.

**Comment by Monodesu** [comment]
Yes it works well!
By using server device mode and set my playback device to 24bits and 192000Hz, no issue at all.
Thanks a lot!
