### ISSUE TITLE
How to compile the React JS application to a window executable?

### ISSUE THREAD

**Issue by sunset1234321** [w-okada/voice-changer#298]
### Issue Type

Others

### vc client version number

na

### OS

Windows 10

### GPU

none

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Voice Changer type

NA

### Model type

NA

### Situation

May I know how you packaged  Frontend application to a window executable               I believe you use Electron.

**Comment by shep920** [comment]
Bumping

**Comment by w-okada** [comment]
same

https://github.com/w-okada/voice-changer/issues/282
