### ISSUE TITLE
Can't find "start_http.bat"

### ISSUE THREAD

**Issue by Ryuujitoraz** [w-okada/voice-changer#300]
Hello, sorry for my bad english but I tried to run "start_http.bat" but it doesn't appears in my file, I downloaded "https://github.com/w-okada/voice-changer/archive/refs/heads/master.zip" but there is no "start_http.bat" see : 

![image](https://github.com/w-okada/voice-changer/assets/132905023/7bf95cdd-1224-4145-8e99-0d88c4db2161)

If someone can help me please !

**Comment by w-okada** [comment]
Download from the link in README.

**Comment by w-okada** [comment]
no res close

**Comment by g-l-i-t-c-h-o-r-s-e** [comment]
Terrible documentation.
