### ISSUE TITLE
Crepe Inference Hop Length

### ISSUE THREAD

**Issue by Mojobones** [w-okada/voice-changer#304]
Hi there, I have a question about using Crepe inference with RVC models in real time. What hop length is used for the inference? Is there a way to tweak it, even if manually in the code?

**Comment by w-okada** [comment]
here. 
https://github.com/w-okada/voice-changer/blob/328ea461613a191157f44d6ba512abc288c412cf/server/voice_changer/RVC/pipeline/Pipeline.py#LL109C21-L109C33


And there is no way to change value currently.

**Comment by w-okada** [comment]
no res close
