### ISSUE TITLE
Can't upload model

### ISSUE THREAD

**Issue by Timtaran** [w-okada/voice-changer#307]
### Issue Type

Bug Report

### vc client version number

1.5.3.5

### OS

Windows 10

### GPU

RTX 3060

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Voice Changer type

MMVC 1.3

### Model type

IDK

### Situation

uploading stops at 99.3%

**Comment by Timtaran** [comment]
> what is IDK?
> 
> tell me how to reproduce.

Svc probably


https://mega.nz/file/nYpAiTpK#2o8SxEOw6SyTnOMFRYrzlvC9skafcx8Mc40SsSBYZxg this is model

**Comment by w-okada** [comment]
?
MMVC is no SVC. 
Use the appropriate file.

**Comment by Timtaran** [comment]
so if I try SVC this model also doesn't uploads

**Comment by w-okada** [comment]
That's right. We don't support SVC.
I believe that the so-vits-svc4.0 model should work.

This issue will be closed.
