### ISSUE TITLE
Fail to run start_http.bat

### ISSUE THREAD

**Issue by C1oudust** [w-okada/voice-changer#308]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.5

### OS

Windows 10

### GPU

TRX 3070

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Voice Changer type

MMVC

### Model type

ONNX

### Situation

<img width="660" alt="Snipaste_2023-06-12_19-50-39" src="https://github.com/w-okada/voice-changer/assets/29059054/1ed7d4dc-2fe4-44a3-aa62-90fbaf5115a6">

**Comment by w-okada** [comment]
same?

https://github.com/w-okada/voice-changer/issues/240

**Comment by C1oudust** [comment]
> same?
> 
> #240

yes,but I use the newest version

**Comment by ArEnSc** [comment]
same issue

**Comment by w-okada** [comment]
I think the issue is that the name of your microphone is not in Unicode. If you have another microphone, try taking out your current one and using that one.

**Comment by C1oudust** [comment]
> I think the issue is that the name of your microphone is not in Unicode. If you have another microphone, try taking out your current one and using that one.
I'm using the microphone of ATH-LS70iS headset, I don't know if its name is Unicode, I tried other headsets like Sony MDR-XB55AP, still the same problem...

**Comment by C1oudust** [comment]
> I think the issue is that the name of your microphone is not in Unicode. If you have another microphone, try taking out your current one and using that one.

I'm using the microphone of ATH-LS70iS headset, I don't know if its name is Unicode, I tried other headsets like Sony MDR-XB55AP, still the same problem...

**Comment by w-okada** [comment]
I don't have a mic device that doesn't return unicode, so it's a problem that I can not reproduce. However, I have implemented logic to skip when I can't decode unicode, so it might be improving. If you like, please give it a try.

Try v.1.5.3.5a.

**Comment by C1oudust** [comment]
> I don't have a mic device that doesn't return unicode, so it's a problem that I can not reproduce. However, I have implemented logic to skip when I can't decode unicode, so it might be improving. If you like, please give it a try.
> 
> Try v.1.5.3.5a.

start successful, but run into another Unicode problem...
<img width="720" alt="Snipaste_2023-06-22_08-50-56" src="https://github.com/w-okada/voice-changer/assets/29059054/65aafb1c-ee3c-4e10-b2e3-3c5eedc635e6">

**Comment by w-okada** [comment]
same

https://github.com/w-okada/voice-changer/issues/329
