### ISSUE TITLE
Can't read file

### ISSUE THREAD

**Issue by yi1134** [w-okada/voice-changer#310]
### Issue Type

Others

### vc client version number

1.5.3.5

### OS

Windows 10

### GPU

GTX1650

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

RuntimeError: Error in __cdecl faiss::FileIOReader::FileIOReader(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:68: Error: 'f' failed: could not open C:\Users\零七\AppData\Local\Temp\tmpoqy1yjzy\upload_dir\0\added_IVF2930_Flat_nprobe_1_nanaqi_v2.index for reading: No such file or directory
but the file is exist.

**Comment by w-okada** [comment]
I have absolutely no idea what the cause is. Since there are no other similar reports, it doesn't seem like it can be reproduced.

**Comment by w-okada** [comment]
no update close
