### ISSUE TITLE
start_server.sh has \r and not working in Linux

### ISSUE THREAD

**Issue by m96-chan** [w-okada/voice-changer#311]
### Issue Type

Bug Report

### vc client version number

main

### OS

Window10, Ubuntu 22.x

### GPU

RTX3090Ti

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Voice Changer type

RVC`

### Model type

pyTorch

### Situation

rewrite enter to CRLF to LF

**Comment by w-okada** [comment]
which is start_server.sh?

**Comment by m96-chan** [comment]
@w-okada 
sorry. 
https://github.com/w-okada/voice-changer/blob/master/start_docker.sh
this one.

**Comment by w-okada** [comment]
`bash start_docker.sh` doesn't work?
in my environment, it works fine.

**Comment by m96-chan** [comment]
ok, may be i have a mistake.
close this.

**Comment by w-okada** [comment]
OK
