### ISSUE TITLE
Amd Gpu is not supporting in audio processing

### ISSUE THREAD

**Issue by DarkenHunter** [w-okada/voice-changer#312]
### Issue Type

Others, Bug Report

### vc client version number

v.1.5.3.5

### OS

Windows 10

### GPU

RX 6800XT

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

I have an RX 6800XT GPU but all the processing is being done by my R7 5700x processor. I can't find a way to use my GPU for processing.

Image of the software: https://ibb.co/3BZKFtS
Cpu usage Task manager: https://ibb.co/Th6mZY1

If there is a way to process this with GPU would be really great.

**Comment by ABagOfPotato** [comment]
Just to add to this that I've tried the directML version on both an RX 6600 and an Arc A770 and it has not detected any GPU's for the last few versions at least, I can't speak for previous versions.

The new UI for RVC has a GPU selection now too which does not show any GPU's available.

**Comment by DarkenHunter** [comment]
@w-okada Yes, I have used the directML version. but it doesn't work.

**Comment by w-okada** [comment]
It appears that AMD GPUs detect differently from Nvidia GPUs. This could be the cause for not being detected. Even if it looks like AMD GPUs are not detected in the directML version, they could still be using the GPU.

**Comment by ABagOfPotato** [comment]
> It appears that AMD GPUs detect differently from Nvidia GPUs. This could be the cause for not being detected. Even if it looks like AMD GPUs are not detected in the directML version, they could still be using the GPU.

I'm not sure, when using it I still have 100% CPU usage and struggle to run it, it did seem slightly better on one of the older versions also, I also don't see any GPU usage while using it.

Appreciate the work to make things more open, it is however early days.

**Comment by w-okada** [comment]
try to set index to 0.

**Comment by LunarCake** [comment]
> try to set index to 0.

I am facing similar issues, I tried searching but I couldn't find where you can change the index to 0. 
Thank you for taking the time to answer these

**Comment by ABagOfPotato** [comment]
I have been able to get it to work partly using DirectML now, performance is definitely a bit better with index set to 0, it does tend to use like 20% GPU usage and max out the CPU though.

**Comment by LunarCake** [comment]
> I have been able to get it to work partly using DirectML now, performance is definitely a bit better with index set to 0, it does tend to use like 20% GPU usage and max out the CPU though.
Could you please tell me how you did that?
I've been struggling with it myself for the past few hours

**Comment by ABagOfPotato** [comment]
> > I have been able to get it to work partly using DirectML now, performance is definitely a bit better with index set to 0, it does tend to use like 20% GPU usage and max out the CPU though.
> 
> Could you please tell me how you did that? I've been struggling with it myself for the past few hours

My understanding is that DirectML only works for RVC, on the latest version I use that, upload a model and convert it to ONNX format, you can then set index to 0 and it seems to work a bit better too.

It still maxes out CPU quite a lot but not as much as before and GPU usage is up a little bit. Not ideal but it definitely uses the GPU a bit now.

**Comment by LunarCake** [comment]
> My understanding is that DirectML only works for RVC, on the latest version I use that, upload a model and convert it to ONNX format, you can then set index to 0 and it seems to work a bit better too.
> 
> It still maxes out CPU quite a lot but not as much as before and GPU usage is up a little bit. Not ideal but it definitely uses the GPU a bit now.

Oh I see, I didn't think to convert the model. I just tried an ONNX model, it works better. Around 80% CPU and 15% GPU usage but it works way better.
Thank you so much. While not perfect it works, now i have to figure out how to convert the model i want from PTH to ONNX..

**Comment by w-okada** [comment]
Oh, Yes. DirectML is only for ONNX. not for pytorch.

**Comment by LunarCake** [comment]
Using an ONNX model only slightly improved performance, it still uses CPU and does not detect the GPU. I have been unable to find what causes this issue. I am currently using the RX 570 which is supported by DirectML, I also tested the previous version and tried going between GPU -1 and 0, did not work. Still I am amazed by this project, from what i've seen working it's pretty good!

**Comment by DarkenHunter** [comment]
> > > I have been able to get it to work partly using DirectML now, performance is definitely a bit better with index set to 0, it does tend to use like 20% GPU usage and max out the CPU though.
> > 
> > 
> > Could you please tell me how you did that? I've been struggling with it myself for the past few hours
> 
> My understanding is that DirectML only works for RVC, on the latest version I use that, upload a model and convert it to ONNX format, you can then set index to 0 and it seems to work a bit better too.
> 
> It still maxes out CPU quite a lot but not as much as before and GPU usage is up a little bit. Not ideal but it definitely uses the GPU a bit now.

How did you convert a pth model to ONNX model?

**Comment by w-okada** [comment]
here. If you upload torch model, you can see this button.

![image](https://github.com/w-okada/voice-changer/assets/48346627/ed0e453d-a847-48cb-ae89-19ac98476ea8)

**Comment by w-okada** [comment]
no response. close
