### ISSUE TITLE
MMVCServerSIO文件下载出现问题

### ISSUE THREAD

**Issue by chuan6v** [w-okada/voice-changer#314]
### Issue Type

Bug Report

### vc client version number

VC_redist.x64.exe

### OS

window 10

### GPU

2060 6g

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Voice Changer type

MMVCServerSIO v.1.5.3.3

### Model type

cmd python pytorch

### Situation

MMVCServerSIO文件下载出现问题后面出现以下字符串：amples_0003_t.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))
+[Voice Changer] loading sample info error: [Errno 2] No such file or directory: 'samples_0003_t.json'
    Internal_Port:18888
    protocol: HTTPS(self-signed), key:C:\Users\v\AppData\Local\Temp\tmpn2fmhi7i\keys\20230614_173340.key, cert:C:\Users\v\AppData\Local\Temp\tmpn2fmhi7i\keys\20230614_173340.cert
    -- ---- --
    ブラウザで次のURLを開いてください.
    https://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    https://localhost:18888/
    https://192.168.2.19:18888/
    Booting PHASE :MMVCServerSIO
VoiceChanger Initialized (GPU_NUM:1, mps_enabled:False)

**Comment by w-okada** [comment]
how to reproduce?

**Comment by chuan6v** [comment]
> 如何繁殖？
我就是在解压后打开start_https.bat第一次打开后是下载数据后面就停止了我感觉是网络的问题我就连接了vpn然后第一次下载了数据后后面有几个下载条看着也是下载数据，然后全部下载好后就不跑了直接显示失败或者是上面的子符串，我也试过断开vpn裸连也是差不多的甚至第一次跑完数据后后面的几个下载条也不现实直接显示失败

**Comment by w-okada** [comment]
Sorry, I don't understand Chinese. Even if I use DeepL to translate, it just becomes incomprehensible Japanese.

**Comment by chuan6v** [comment]
> 对不起，我不懂中文。就算我用DeepL翻译，也只会变成看不懂的日文。

 After decompressing and opening start_https.bat, it stopped after downloading data for the first time. I felt it was a network problem so I connected to a VPN. Then, after downloading the data for the first time, there were several download bars behind it that seemed to be downloading data. And after all the data was downloaded, it didn’t run and either showed failure directly or showed the above substring. I also tried disconnecting the VPN and connecting nakedly, which was almost the same. Even after running the data for the first time, the several download bars behind it did not show up and directly showed failure.

**Comment by chuan6v** [comment]
> 对不起，我不懂中文。就算我用DeepL翻译，也只会变成看不懂的日文。

フォルダー全体を削除し、新しいファイルを再抽出して、start_https.bat を実行しました。 このプロセスを5回試し、さまざまな方法を試し、デバイスを変更しました。 これまでのところ何の進展もありませんが、次のメッセージがまだ表示されています: Booting PHASE: main VoiceChanger を開始しています。 ++ 内部ポート: 18888 プロトコル: HTTPS (自己署名)、キー: C:\Users\v\AppData\Local\Temp\tmpc6o0qjwa\keys\20230616_100215.key、証明書: C:\Users\v\AppData\Local \Temp\tmpc6o0qjwa\keys \20230616_100215.cert – ---- – URLをブラウザでご覧ください。 https://<IP>:<ポート>/ ほとんどの場合、次のいずれかの URL にアクセスすると開始されます。 https://localhost:18888/ https://192.168.2.19:18888/ ブートフェーズ: MMVCServerSIO VoiceChanger が初期化されました (GPU_NUM:1、mps_enabled:False)。

**Comment by chuan6v** [comment]
> 对不起，我不懂中文。就算我用DeepL翻译，也只会变成看不懂的日文。

新しい解決策があれば、喜んで試してみたいと思いますが、コミュニティにオンラインで参加することがあまりありません。可能であれば、メールでご連絡ください。よろしくお願いします: 2539299097@qq.com

**Comment by chuan6v** [comment]
> 对不起，我不懂中文。就算我用DeepL翻译，也只会变成看不懂的日文。

我这边给你发截图吧
![image](https://github.com/w-okada/voice-changer/assets/91829182/72dd88b4-3bb8-4a24-937e-f48873f65674)

**Comment by chuan6v** [comment]
> 对不起，我不懂中文。就算我用DeepL翻译，也只会变成看不懂的日文。

私はプロジェクトを使用するために必死です、私はプロセスのビデオを送信するか、私はあなたが私に連絡するための私のgmailを送信します、あなたのgmailを持つことができますか？ 本当にありがとうございます：gucang50@gmail.com真的谢谢

**Comment by w-okada** [comment]
How about trying start_http.bat? If that works properly, it's possible your network isn't properly configured for this application.

**Comment by chuan6v** [comment]
This is the full status of start_http.bat, I have no way to use the database to change the sound
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "w-okada/voice-changer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月18日(星期天) 晚上7:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [w-okada/voice-changer] MMVCServerSIO文件下载出现问题 (Issue #314)





 
How about trying start_http.bat? If that works properly, it's possible your network isn't properly configured for this application.

**Comment by pz9k** [comment]
截图里是没有报错的，看起来启动正常。
你有没有试过用start_http.bat启动？

我看了最开始的提问，里面显示
No such file or directory: 'samples_0003_t.json'，缺少了这个json文件。
旧的版本可能有未知的bug，里面预设的下载地址可能已经失效了，或许你可以试试使用v.1.5.3.3之上的最新的一两个版本，见
https://huggingface.co/wok000/vcclient000/tree/main

**Comment by chuan6v** [comment]
All my actions are the first in the list in the picture. Which one should I download to continue the operation
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "w-okada/voice-changer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月19日(星期一) 晚上7:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [w-okada/voice-changer] MMVCServerSIO文件下载出现问题 (Issue #314)





 
截图里是没有报错的，看起来启动正常。
 你有没有试过用start_http.bat启动？
 
我看了最开始的提问，里面显示
 No such file or directory: 'samples_0003_t.json'，缺少了这个json文件。
 旧的版本可能有未知的bug，里面预设的下载地址可能已经失效了，或许你可以试试使用v.1.5.3.3之上的最新的一两个版本，见
 https://huggingface.co/wok000/vcclient000/tree/main

**Comment by chuan6v** [comment]
Maybe it's the version, do you have version 1.5.3.3, I'd like to try it





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "w-okada/voice-changer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月19日(星期一) 晚上7:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [w-okada/voice-changer] MMVCServerSIO文件下载出现问题 (Issue #314)





 
截图里是没有报错的，看起来启动正常。
 你有没有试过用start_http.bat启动？
 
我看了最开始的提问，里面显示
 No such file or directory: 'samples_0003_t.json'，缺少了这个json文件。
 旧的版本可能有未知的bug，里面预设的下载地址可能已经失效了，或许你可以试试使用v.1.5.3.3之上的最新的一两个版本，见
 https://huggingface.co/wok000/vcclient000/tree/main

**Comment by ivastsky** [comment]
Sorry, unable to run

**Comment by w-okada** [comment]
Since there have not been any updates, I will close this now. Please check if it works with the latest version and post a new issue if there are any problems.
