### ISSUE TITLE
Performance Degradation From v.1.5.3.4d -> v.1.5.3.5

### ISSUE THREAD

**Issue by Mojobones** [w-okada/voice-changer#316]
### Issue Type

Bug Report

### vc client version number

v.1.5.3.5

### OS

Windows 11

### GPU

Nvidia 4080

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Voice Changer type

RVC v2

### Model type

pyTorch, f0 Harvest

### Situation

I've noticed that the voice changer is performing quite a bit worse for me on v.1.5.3.5 compared to v.1.5.3.4d. Normally I run in server mode with a chunk num of 80 & extra data length of 32k and have no issues with a stable performance. 

Those same settings in server mode on 1.5.3.5 gives me a lot of sound repetition (like a broken record) that is distinctive and means my computer isn't keeping up with inference. I tried moving up to a higher chunk num of 96 instead, but the issue is still happening. 

This is a fairly notable difference, as I tried to re-run 1.5.3.4d as a test and 80/32k is again stable for me on that version with no broken record sound. 

Specs:
Intel i7-10700k
Nvidia 4080 with the most recent drivers
64gb RAM
Windows 11 with all updates

**Comment by grimoire-vc** [comment]
I've noticed the same. I didn't measure it out as clearly, but performance on my system is also noticeably poorer than 1.5.3.4d

**Comment by w-okada** [comment]
tell your setting.

**Comment by Mojobones** [comment]
> tell me your setting.

Model type: .pth (issue also occurs with .onxx version)
Tune 11, index ratio: .3
F0 detection: harvest
S.Thresh: .00001
Chunk 80
Extra: 32768
GPU: 2080
Audio mode: server
Input: MME - MME USB microphone
Output: MME - MME Voicemeeter Aux Input
Protocol: sio
Crossfade: 1024 start: 0.4 end: 1
Truncate: 100
SilenceFront: on
Protect: 0.5
RVC Quality: low

**Comment by Mojobones** [comment]
> set index ratio to 0 index processing is very heavy.

Just to be safe I wiped out my GPU drivers and reinstalled them. That combined with index ratio at 0 seemed to help, but I still ended up getting the broken record sound, it just took longer before it happened. 

I'll try to play around with more factors to see if I can reduce it, or get a better comparison between 1.5.3.5 and 1.5.3.4d.

**Comment by Hoshiyomis35P** [comment]
why my voice keep repeating?, how to fix that issue?
