### ISSUE TITLE
M1 Mac "Unknown message" error when selecting RVC

### ISSUE THREAD

**Issue by alexledd** [w-okada/voice-changer#317]
### Issue Type

Others

### vc client version number

1.5.3.5

### OS

M1 Mac

### GPU

none

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Voice Changer type

RVC

### Model type

none

### Situation

![Screenshot 2023-06-15 at 20 16 11](https://github.com/w-okada/voice-changer/assets/78063260/d54aca96-c5b9-481d-8d8a-799bf5db50fb)

![Screenshot 2023-06-15 at 20 26 29](https://github.com/w-okada/voice-changer/assets/78063260/859fc29a-0e7c-4517-9768-5e496eef5a5c)

Mainly i got a problem when selecting RVC
I tried both http and https, which are not working on my machine. Help please, thank you.

Sorry i don't really know much about codes

**Comment by alexledd** [comment]
update: it's not only RVC that got this problem, everytime i tried to access the local url, it has the same message with: 

no error name
no error message
no error stack

**Comment by Jeffrey-deng** [comment]
same error

**Comment by Jeffrey-deng** [comment]
m1 mac  wrok on 1.5.3.3, don't work in 1.5.3.5
i'll try v.1.5.3.4d

**Comment by mazeltov7** [comment]
same error on M1 mac

**Comment by KCGD** [comment]
Same error on linux (x86). Switched to a chromium based browser (brave in my case) and the error went away

**Comment by MrUbun2** [comment]
i have the same issue on M2 with version 1.5.3.5, it doesn't work on chrome or any other browser

**Comment by Canderson8495** [comment]
I'm also getting the same error on my m1 mac

**Comment by ZhichGaming** [comment]
I am also getting the same issue.

**Comment by TakashiSugie** [comment]
I'm also getting the same error on my m1 mac

**Comment by l68728** [comment]
I think that if the author can download and install some new versions on his m1mac and successfully run some new versions, he can package the entire folder of the file, or publish the md5 check code of the folder, so that we can confirm whether something is missing Component or system environment problems.

**Comment by w-okada** [comment]
one question, how about run this command? 
```
install_name_tool
```

**Comment by w-okada** [comment]
And give me full log on terminal. maybe there is some clue.

**Comment by w-okada** [comment]
We've received a report that version 1.5.3.8a runs smoothly on M2 Mac Venture. Would you like to give it a try?

https://github.com/w-okada/voice-changer/issues/368

**Comment by w-okada** [comment]
no update, similar issue is [here.](https://github.com/w-okada/voice-changer/issues/339) merge this issue to there,
