### ISSUE TITLE
Support for RVC version 2

### ISSUE THREAD

**Issue by MysteryPancake** [w-okada/voice-changer#325]
### Issue Type

Feature Request

### vc client version number

1.5.3.5

### OS

Windows 10

### GPU

Nvidia 3080 GPU

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Voice Changer type

RVC

### Model type

ONNX

### Situation

Recently RVC version 2 has come out, here are some example collabs:

https://colab.research.google.com/drive/1Gj6UTf2gicndUW_tVheVhTXIIYpFTYc7?usp=sharing
https://colab.research.google.com/drive/1TU-kkQWVf-PLO_hSa2QCMZS1XF5xVHqs?usp=sharing

It seems version 2 models don't work with the current RVC.

It would be good to have support for RVC version 2.

**Comment by w-okada** [comment]
Already supported.
please try
