### ISSUE TITLE
nadare's RVC v3 Compatibility

### ISSUE THREAD

**Issue by grimoire-vc** [w-okada/voice-changer#328]
### Issue Type

Feature Request

### vc client version number

v.1.5.3.5a

### OS

Windows 11

### GPU

3080 Ti

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Voice Changer type

RVC

### Model type

ONNX f0

### Situation

Just putting this on your radar in case you haven't seen it: nadare, one of the RVC devs, is working on (currently unofficial) v3 RVC models and training files: https://github.com/nadare881/rvc-webui/tree/model_v2/lib/rvc_v3 https://huggingface.co/datasets/nadare/rvc-v3j/tree/main

I'm not certain if these are the final versions of these files or not, and I think there's other aspects of RVC that need updating for v3 models, but it's apparently a good improvement. They clarified on Discord just now that the pre-trained models are only trained for 20 epochs, so probably not ready yet. Thanks for all your good work!

**Comment by nanowell** [comment]
Thank you for this

**Comment by Mojobones** [comment]
Looks like the person making it has a fork to try and implement it. Could be useful to watch! https://github.com/nadare881/voice-changer

**Comment by ozhenn** [comment]
Oh god. Someone implement this for directML.

**Comment by w-okada** [comment]
nadare are contributing in this repo. Now work in progress. please wait.
(name is not v3, but "voras")

Close this issue, If you want nadare's v3 reopen.
