### ISSUE TITLE
Cannot read properties of null (reading 'enableServerAudio')

### ISSUE THREAD

**Issue by xfkun233** [w-okada/voice-changer#329]
### Issue Type

Others

### vc client version number

1.5.3.5a

### OS

Windows 10

### GPU

Nvidia RTX 3070 Laptop

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Voice Changer type

RVC

### Model type

ONNX

### Situation

![image](https://github.com/w-okada/voice-changer/assets/126741063/88ce8c66-2fc8-465c-9054-224baf28de25)

**Comment by w-okada** [comment]
Thanks, I reproduced it. It will be fixed by next release.

**Comment by w-okada** [comment]
try the latest version v.1.5.3.6

**Comment by w-okada** [comment]
no res close.

**Comment by ZHANGclassmate** [comment]
I also had this problem. The latest version appears
