### ISSUE TITLE
resの爆増現象により通常使用が不可能な問題を解決することができません

### ISSUE THREAD

**Issue by Caligula587** [w-okada/voice-changer#330]
### Issue Type

Question

### vc client version number

v.1.5.3.5a (MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.5a.zip)

### OS

Windows 10

### GPU

NVIDIA GeForce RTX 3070 (8GB)

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Voice Changer type

RVC

### Model type

pyTorch (pth)

### Situation

![issue](https://github.com/w-okada/voice-changer/assets/137215411/c3693703-8585-4440-aca6-0bd8f597db40)

ValueError: invalid literal for int() with base 10: b'\xe5'
ValueError: Too many packets in payload
初めてプログラムを使用したとき、音声の変換自体には異常はなかったのですが、このようなエラーが継続的に発生し、正常に使用できず、音声の変換が途切れたり、止まったりする現象が発生しました。 そのため、その原因を探しましたが、その原因がbuf値に対してres値が高いことが原因であることが分かりました。

そのゆえチュートリアルでの案内を参考にchunkとextraの基本値／適正値／最小値／最大値を設定して何とかres値をbuf数値より低く設定しようとしましたが、なぜか有効な調整ができませんでした。
そのせいで正しく出力されず、音声が途切れる現象、音声が遅く出る現象などが続いています。
pthファイルのonnx変換も試しましたが、エラーが発生し、変換できませんでした。

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorboard 2.11.0 requires protobuf<4,>=3.9.2, but you have protobuf 4.23.3 which is incompatible.
tensorflow-intel 2.11.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.23.3 which is incompatible.

（おそらくonnxをpip installする時に発生したこのエラーが原因だと思います。 RVC内でonnx変換を試みた時にも同様に失敗したので、これはおそらく本プログラム自体の問題ではないと思います）

ですがこの問題に対する解決方法を見つけることができなかったので、結果的にchunkとextraを通じた調整も、onnxへの変換も不可能な状況です。
chunkとextraの値を一つ一つ全て手動で調整しましたが、効果がなく、GPUをcpuに変えたり、harvest以外のものを使ってみましたが、それでもres値が爆発的に増加するのを解決することはできませんでした。

![issue2](https://github.com/w-okada/voice-changer/assets/137215411/850df434-692a-4686-be95-5ec6081d0f5e)
最新ではありませんが、私が現在使用しているパソコン環境が本プログラムを使用できない環境とか、性能が悪くて発生しているとはまず考えられないです。実際に本プログラムを使用しているときに、GPUやメモリーの数値の暴騰や異常な温度上昇などの現象も確認されでないです。ですが、なぜか他の使用者たちは問題なく使用しているのが確認されており、私の環境でのみこのような問題が発生するので、このような現象が発生することに対する問題の原因と解決方法を正確に知りたいです。どうぞよろしくお願いします。

実行環境:
Windows 10 Pro 22H2 19045.3086
MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.5a.zip
NVIDIA GeForce RTX 3070 (8GB)
12th Gen Intel(R) Core(TM) i7-12700F   2.10 GHz

**Comment by bcube8565** [comment]
私もrtx3070を使用していますが初回以降、まともに変換されていない状態です。また見に来るのでアンカー置いておきます。⚓

**Comment by w-okada** [comment]
show me log on terminal.

**Comment by w-okada** [comment]
no res close
