### ISSUE TITLE
What kind of audio file do you support?

### ISSUE THREAD

**Issue by kenzron** [w-okada/voice-changer#332]
### Issue Type

Question

### vc client version number

v.1.5.3.4d

### OS

Windows 11

### GPU

NVIDIA GeForce RTX 3060 Laptop GPU

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Voice Changer type

RVC

### Model type

pth

### Situation

I tried upload my audio file to Device Setting --> AudioInput --> file, instead of use my microphone.

I tried .wav and .mp3 yet the client said error happened and it never tell me why the error happened.

Could you please tell us what kind of audio file do RVCC supported? I could not find this information at all in document.

**Comment by w-okada** [comment]
Wav is support. 
Try [this file](https://drive.google.com/file/d/1iCErRzCt5-6ftALcic9w5zXWrzVXryIA/view).



from https://sites.google.com/site/shinnosuketakamichi/research-topics/jvs_music

**Comment by w-okada** [comment]
no res clise
