### ISSUE TITLE
v.1.5.3.5a using AMD. voice changer no output sound/ sounds glitchy

### ISSUE THREAD

**Issue by vFenris** [w-okada/voice-changer#333]
### Issue Type

Bug Report, Question, Others

### vc client version number

v.1.5.3.5a

### OS

Windows 10

### GPU

AMD Radeon RX 6600 XT

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Voice Changer type

RVC

### Model type

tsukuyomi_v2_40k_e100_simple (ONNX)

### Situation

It may be because I am using AMD but the voice changer's voice does not come out sometimes. When it does come out, it sounds very choppy and is usually very delayed/does not even pick up the input. Does not show AMD option under GPU input

below are the settings I use 

![image](https://github.com/w-okada/voice-changer/assets/87515757/2b23c8c1-d352-4fcd-bae6-19f15f050144)
![image](https://github.com/w-okada/voice-changer/assets/87515757/eba2350f-6e72-400b-8265-1870c94fdf03)

**Comment by w-okada** [comment]
try directml version.

**Comment by w-okada** [comment]
If DirectML version of the app does not improve your situation, unfortunately, it might be an unsupported GPU. Please try using a CPU instead. You should also set the chunksize to a large value when doing so.

**Comment by Mohizuki** [comment]
it doesnt support amd gpu ? since im using RX 6600 aswell

**Comment by Urahana** [comment]
> it doesnt support amd gpu ? since im using RX 6600 aswell

im using the same and it work smoothly on i3 12f 6600 ram 16

**Comment by Urahana** [comment]
> > it doesnt support amd gpu ? since im using RX 6600 aswell
> 
> im using the same and it work smoothly on i3 12f 6600 ram 16

export to onyx and reupload, it was said there to do so
