### ISSUE TITLE
issue with selecting vc

### ISSUE THREAD

**Issue by titgfggggh** [w-okada/voice-changer#334]
### Issue Type

Bug Report, Question, Others

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.5a.zip

### OS

windows 1-

### GPU

rtx 2070 super

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Voice Changer type

RVC

### Model type

ONNX

### Situation

i want to use the vc but when i select what type of vc to use i select RVC and when i choose that , i get this error:
![image](https://github.com/w-okada/voice-changer/assets/62062399/eedb8f36-d75f-4016-9cc8-a68e4360af50) can someone tell me what is wrong

**Comment by w-okada** [comment]
No similar phenomenon has been reported. If the same phenomenon occurs after you try the latest version, please raise another issue.
