### ISSUE TITLE
glitchy, static, or weird out of breath sounds.

### ISSUE THREAD

**Issue by Cr7pt0nic** [w-okada/voice-changer#336]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.5

### OS

Windows 11

### GPU

NVIDIA GeForce GTX 980 Ti (6GB)

### Clear setting

no

### Sample model

yes

### Input chunk num

yes

### Voice Changer type

RVC

### Model type

PyTorch

### Situation

I'm not sure if this is a limitation or an issue with the voice changer but whenever I speak into the microphone it would sound okay but I changed my chunk to 384 which sounds okay but the response from the voice changer itself is very delayed. When I changed the chunk to a lower chunk it had a faster response but it had a much more choppy sound output than if I put it at higher chunks. I want to have a faster response but also have a clear sounding voice when using the voice changer. any solutions for this issue?

**Comment by mairzu** [comment]
I have the same problem any fix?

**Comment by Cr7pt0nic** [comment]
I've been dealing with this issue as well and I was wondering if there was any way to mitigate this issue.

**Comment by w-okada** [comment]
I think the symptom may be due to the performance of the PC. The latest version is slightly but it does improve, so please try it out. If it still does not resolve, I recommend replacing the PC.
