### ISSUE TITLE
More Model Slot Configurations その他のモデルスロット構成

### ISSUE THREAD

**Issue by Maclean-D** [w-okada/voice-changer#337]
### Issue Type

Feature Request

### vc client version number

15.3.5a

### OS

Windows 11 Pro

### GPU

RTX 3070

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Voice Changer type

RVC

### Model type

f0

### Situation

Can we get the ability to add more than 10 model presets?
モデル スロット構成は 10 個のみです。 さらに追加したり、総数を増やすことはできますか?

**Comment by w-okada** [comment]
Unfortunately, we cannot increase it with the current version.
