### ISSUE TITLE
I would like to know how to convert code, including the Python code, into an .exe file.

### ISSUE THREAD

**Issue by g0m40** [w-okada/voice-changer#338]
### Issue Type

Question

### vc client version number

1.5.3.5

### OS

Windows 11

### GPU

RTX 3070

### Clear setting

yes

### Sample model

yes

### Input chunk num

no

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

I don't have an issue with your code, I just have a simple question.

I'm interested in building the source code to obtain pre-compiled binaries. However, I'm not very familiar with the build process and I'm looking for detailed instructions.

I found that "_MEIPASS" is being used in the code. Are you using tools like PyInstaller to convert the Python code into an .exe file? If you are using PyInstaller, it would be helpful if you could share the .spec file and the steps involved.
If PyInstaller is not being used, I would appreciate it if you could let me know what tools you are using for this purpose.

Thank you in advance for your time and assistance.

**Comment by w-okada** [comment]
same

https://github.com/w-okada/voice-changer/issues/282
