### ISSUE TITLE
Unable to load voices that are 500MB in size.

### ISSUE THREAD

**Issue by AOVTuber** [w-okada/voice-changer#341]
### Issue Type

Question

### vc client version number

v.1.5.3.5a 

### OS

Win10

### GPU

RTX 3060

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Voice Changer type

RVC

### Model type

pytorch

### Situation

Most .pth voices I find that are around 57MB in size work really well with the RVC section of your app, but the ones that are about 500MB in size, do not work at all (they don't even load). Do you know why this might be?

**Comment by Fasteroid** [comment]
Reproduced with a 523MB model of Wrecking Ball's Mech from OW2:
```
loadModel {'defaultTune': 0, 'defaultIndexRatio': 1, 'defaultProtect': 0.5, 'sampleId': '', 'rvcIndexDownload': True, 'files': {'rvcModel': 'C:\\Users\\Faste\\AppData\\Local\\Temp\\tmpieo3j0l6\\upload_dir\\4\\WreckingBall.pth'}}
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 334, in loadModel
  File "voice_changer\RVC\RVC.py", line 158, in loadModel
  File "voice_changer\RVC\ModelSlotGenerator.py", line 11, in _setInfoByPytorch
KeyError: 'config'

[Voice Changer] Model Load Error! Check your model is valid. 'config'
```

**Comment by AOVTuber** [comment]
Well, just discovered those 500MB files arent's for RVC, they're for So-vits-svc-4.0, so no wonder it wasn't working for me.
