### ISSUE TITLE
Client closed error

### ISSUE THREAD

**Issue by Ancell14** [w-okada/voice-changer#342]
### Issue Type

Bug Report

### vc client version number

1.5.3.5

### OS

Windows 10

### GPU

RTX 2060

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Voice Changer type

MMVC

### Model type

-

### Situation

Everything just been fine since first startup and download. Everything worked without issues, but now, when i open bat file, it shows only this 
![Screenshot_4](https://github.com/w-okada/voice-changer/assets/113716091/d3e45bcc-068f-4ec8-8b53-49860fb38cd8)
And then, opens up exe
![image](https://github.com/w-okada/voice-changer/assets/113716091/3967b0e8-f543-4d72-8d21-85b37f025814)
Just as it. Nothing comes after. Any help, please?

**Comment by w-okada** [comment]
No similar phenomenon has been reported. If the same phenomenon occurs after you try the latest version, please raise another issue.

**Comment by azmi1111** [comment]
same here, already using latest version.

first launch its working but now its client closed

**Comment by kareuxs** [comment]
![Screenshot_2](https://github.com/w-okada/voice-changer/assets/45550141/2b58c5d3-84d8-4598-84ea-4d0ee5621f77)
like this
