### ISSUE TITLE
Voice Changer is not selected. update configuration: modelSlotIndex 1687641836002

### ISSUE THREAD

**Issue by jurassicjordan** [w-okada/voice-changer#344]
### Issue Type

Bug Report

### vc client version number

v.1.5.3.3 (from git clone)

### OS

Arch Linux server (EndeavourOS 6.3.8-zen1-1-zen)

### GPU

NVIDIA GeForce RTX 3060 Lite Hash Rate

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Voice Changer type

RVC

### Model type

RVC (the models that come with the tool

### Situation

RVC errors when selecting voice changer. "[Voice Changer] update configuration: modelSlotIndex 1687641989000. [Voice Changer] Voice Changer is not selected."

this occurs with both self made and built in voice models.

server is running on an anaconda instance

**Comment by w-okada** [comment]
It's possible that this is a problem unique to Arch Linux. Since I don't have Arch Linux, I can't replicate it. Please let me know if there are any updates.
