### ISSUE TITLE
Sounds problems and gpu not recognized

### ISSUE THREAD

**Issue by Pepito2555** [w-okada/voice-changer#347]
### Issue Type

Feature Request, Bug Report, Question

### vc client version number

v.1.5.3.5a

### OS

Windows 11

### GPU

AMD rx 6800xt

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Voice Changer type

RVC

### Model type

pyTorch and ONNX

### Situation

Hi. I just tested this voice changer and it's been a week or so that i'm struguling with some performance issues.
First of all, is it normal that my gpu is not recognized? Maybe it's because I have an amd gpu but still, I don't have the weakest cpu on the planet (ryzen 7 5700x)
![image](https://github.com/w-okada/voice-changer/assets/91200889/e57624f0-9cac-45c9-b5e0-f93e6c388e12)
Here is my settings for those who wants and I've twicked them a lot to have the best quality I can possibly find: 
![image](https://github.com/w-okada/voice-changer/assets/91200889/678d43a3-0393-4307-8ad7-5eb330e0fd4d)
![image](https://github.com/w-okada/voice-changer/assets/91200889/dccb413d-4aea-4e54-b4e6-706174f5a67a)
![image](https://github.com/w-okada/voice-changer/assets/91200889/65111e19-6685-4d62-94dc-5df22abf8c1c)
(the last screen is the voice changer using all my cpu when i'm talking and returning a glitching sound in my ears)

If anyone can help me to have better results or have any idea to use my gpu instead of my cpu, it will be wonderfull
Oh and btw thx you for doing this project. My post might sounds ruff or toxic and don't take it personally. You're doing an awsome job and keep it up!

**Comment by LeLenoch** [comment]
Same problem here :/

**Comment by EGGaming** [comment]
It looks like you're using the CUDA version of the program, which is not compatible with systems that do not have an NVIDIA gpu. For AMD GPUs, you should be using the [directml](https://huggingface.co/wok000/vcclient000/tree/main) version instead (listed as **MMVCServerSIO_win_onnxdirectML-cuda**)

Also, `crepe` seems to not have the best compatibility with AMD GPUs (based on my experience) as it introduces choppiness and higher latency. For best results, you should use `harvest`.

Do keep in mind that **GPU(dml)** has to be set to `on` to use your GPU:
![image](https://github.com/w-okada/voice-changer/assets/26177786/b1eaed0d-ee72-4bbc-855d-23506bea94be)

**Comment by w-okada** [comment]
AMD GPUs may only be used with DirectML-version ONNX in some cases (as it is an experimental implementation).

**Comment by Pepito2555** [comment]
I've also try this version but it keeps using my cpu for some reason

**Comment by w-okada** [comment]
If you're using a version of DirectML and the GPU isn't being used, it could be an unsupported GPU. If necessary, please check the compatibility information on onnxruntime.

**Comment by MikeMong** [comment]
Can you tell me which GPU is compatible because I have an Rx6500 XT and the program does not detect it.
