### ISSUE TITLE
Sound is overly loud and static

### ISSUE THREAD

**Issue by muddzy** [w-okada/voice-changer#348]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.5a.zip

### OS

Windows 10

### GPU

AMD Radeon RX 6600

### Clear setting

no

### Sample model

no

### Input chunk num

yes

### Voice Changer type

RVC

### Model type

pyTorch and ONNX

### Situation

Whenever i use a voice changer nothing comes out because the audio coming in is so loud and static that it cant pick anything up. I've tried reinstalling and changing settings, lowering the input volume to the lowest possible, i even used multiple microphones. all help is appreciated.

![setting2](https://github.com/w-okada/voice-changer/assets/137847750/23ef3492-f434-4315-aa16-2419433f84c5)
![setting](https://github.com/w-okada/voice-changer/assets/137847750/4b2fa96d-ebe5-47c3-bbca-41cc2a8304e3)

**Comment by w-okada** [comment]
How about client device?
How about cpu usage?

**Comment by w-okada** [comment]
no res close
