### ISSUE TITLE
Program not starting after clicking start_http

### ISSUE THREAD

**Issue by NierlyDying** [w-okada/voice-changer#350]
### Issue Type

Bug Report

### vc client version number

v.1.5.3.6

### OS

Windows 10

### GPU

nvidia

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Voice Changer type

RVC

### Model type

onnx

### Situation

The program does not start after clicking start_http, it only pulls up the terminal and stays on the terminal instead of closing it immediately after launch. I have already downloaded this and it has been doing this since yesterday, I assumed that it would work on the new version.

**Comment by w-okada** [comment]
Is there a virus checker running? Wait until it finishes as it is important for your safety. Or, turn it off at your own risk.

**Comment by w-okada** [comment]
no res close
