### ISSUE TITLE
TUNEがずれることがある。

### ISSUE THREAD

**Issue by straight-tamago** [w-okada/voice-changer#351]
### Issue Type

Bug Report

### vc client version number

全てのバージョン

### OS

windows 10

### GPU

rtx2080ti

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Voice Changer type

RVC

### Model type

わかりません

### Situation

windowsをサーバーにしてmacosで使っています。
macosのみのバグだと思いますが、TUNEを12にしていても、実際に出力される音声は13と14の間？になることが頻繁にあります。(どこに設定しても+1.5)色々操作していると急に直ったりします。(macosの設定で出力を変えたり）

ブラウザへの音声の入力は正常です。
https://online-voice-recorder.com/ja/
このサイトで確認しました。

不思議な現象です。

**Comment by w-okada** [comment]
すみません、私がそこまで音感がないので、ピッチが1.5ずれるという現象が認知できません。。。
Windowsのバイナリを使った場合とは違う音が出るということでしょうか？
マイクの性能が違うという可能性はありませんか？試しに同一の音声ファイルをインプットとして、Windows版とMac版で違いが出るのか確認いただけませんか？（デジタル信号になった時点で処理が変わるとは思えない。(MacのChromeが変な処理していなければ。)）

**Comment by w-okada** [comment]
レスがないのでクローズします。もし何かあればお気軽に再オープンしてください。

**Comment by straight-tamago** [comment]
再現方法を見つけました。

WindowsPCでvc clientを立ち上げます。
ローカルのmacからhttps://192.168.10.xxx:18888/で接続します
これだと普通なのですが、

GarageBandを起動して、閉じます。
https://192.168.10.xxx:18888/を開きます。
ズレてます。
