### ISSUE TITLE
プライバシーに関する質問

### ISSUE THREAD

**Issue by gitihobo** [w-okada/voice-changer#353]
### Issue Type

Question

### vc client version number

new windows release

### OS

windows

### GPU

rtx

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Voice Changer type

rvc

### Model type

onnx

### Situation

このソフトウェアをオフラインで使用したいのですが、プライバシーを重視しており、コンテンツをサーバーに移す危険を冒したくないのですが、オフラインで適切に動作するようにこのソフトウェアを確実に構成するにはどうすればよいですか?

**Comment by w-okada** [comment]
必要なファイルは初回起動時にダウンロードされるので、2回目以降はネットワークにつながなくても動くと思います。

**Comment by w-okada** [comment]
no res close
