### ISSUE TITLE
Models missing until "F0 Det" is changed to harvest or crepe

### ISSUE THREAD

**Issue by JarodMica** [w-okada/voice-changer#355]
### Issue Type

Bug Report

### vc client version number

1.5.3.6

### OS

Windows 11

### GPU

RTX 4090

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Voice Changer type

RVC

### Model type

全部

### Situation

The latest package introduces a GUI bug where the models do not show on **initial startup** after having successfully ran start_http.bat.  See attached image.

![load_screen_issue](https://github.com/w-okada/voice-changer/assets/76232114/2a1d4d45-34df-452e-8fef-f6fffcaed6c9)

This gets resolved upon selecting either harvest or crepe, after which you are now able to see the models you have loaded in or the 4 that you have provided.

**Comment by w-okada** [comment]
try v.1.5.3.6a

**Comment by JarodMica** [comment]
Resolved :d!
