### ISSUE TITLE
Program not starting after clicking start_http.bat or start_https.bat file

### ISSUE THREAD

**Issue by cyberhero23** [w-okada/voice-changer#356]
specs:
device: HP Pavilion 360 convertible 2015
CPU: Intel core i5 5200u @ 2.20ghz
GPU: Intel(R) HD graphics 5500
RAM: 8GB
OS: Windows 10 Home 22H2

the command prompt initializes and shows the following text

start_http.bat:
C:\Users\Aik\Downloads\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/checkpoint_best_legacy_500.onnx     --content_vec_500_onnx_on false     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --model_dir model_dir     --samples samples.json

start_https.bat:
C:\Users\Aik\Downloads\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https true     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/checkpoint_best_legacy_500.onnx     --content_vec_500_onnx_on false     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --model_dir model_dir     --samples samples.json

but it doesn't start downloading the additional assets and stays in place

**Comment by LaRevoltage** [comment]
Had the same problem, just wait for a while, it started downloading in 2 minutes for me

**Comment by cyberhero23** [comment]
I waited for 15 minutes and also tried both versions for windows

**Comment by cyberhero23** [comment]
I took your advice and left it running for an hour it started to download
