### ISSUE TITLE
Not bug - so-vits-svc v.1.5.3.4b

### ISSUE THREAD

**Issue by Tobe2d** [w-okada/voice-changer#357]
Where can I download previews version before 1.5.34 as on the change log it show v.1.5.3.4 remove support of so-vits-svc 4.0v2

I came to download and test with so-vits-svc model but I find out it is removed in the latest release ;-(

Can you give me link to download the release that support so-vits-svc please?

**Comment by w-okada** [comment]
https://github.com/w-okada/voice-changer/tree/297cf319f112a4e7e39393ef318dd8b093dc8f27
