### ISSUE TITLE
Program using CPU instead of GPU despite the option enabled

### ISSUE THREAD

**Issue by abysshtml** [w-okada/voice-changer#358]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.6

### OS

Windows 11

### GPU

RX5700

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

When I try to use the software, it works fine, but it runs on the CPU in my system instead of the GPU
![image](https://github.com/w-okada/voice-changer/assets/63281580/d4fb4a29-2901-44a1-b7c1-f2f58b7525e7)
![image](https://github.com/w-okada/voice-changer/assets/63281580/8b15c75a-bd9e-4b15-82d3-4771565ab98b)

How can I get it to actually run on the GPU instead?

**Comment by nanowell** [comment]
Try choosing Crepe instead harvest. Crepe utilize GPU and can improve latency.

**Comment by abysshtml** [comment]
> Consider choosing Crepe instead of Harvest. Crepe utilizes the GPU and can improve latency.

Using Crepe just doesn't work, at least for me.

**Comment by abysshtml** [comment]
Issue I'm having with now is that the program stutters, glitches, rarely outputting an audible voice.

**Comment by w-okada** [comment]
crepe is torch model and use gpu. AMD is not supported and fallback to using cpu.
use dio instead harvest and crepe

**Comment by abysshtml** [comment]
> crepe is torch model and use gpu. AMD is not supported and fallback to using cpu. use dio instead harvest and crepe

dio does in fact work better, although I have one question, are the stutters only there due to AMD incompatibility>

**Comment by w-okada** [comment]
You can check AMD GPU is used or not by performance monitor of Windows. If not used, onnxruntime not support your AMD GPU.
