### ISSUE TITLE
MMVCServerSIO does not start - TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by jurassicjordan** [w-okada/voice-changer#359]
### Issue Type

Bug Report

### vc client version number

1.5.3.6 (master)

### OS

Arch Linux server (EndeavourOS 6.3.8-zen1-1-zen)

### GPU

NVIDIA GeForce RTX 3060 Lite Hash Rate

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Voice Changer type

N/A

### Model type

N/A

### Situation

$ python3 MMVCServerSIO.py -p 18888 --https true
    Booting PHASE :__main__
    Voice Changerを起動しています

Traceback (most recent call last):
  File "/home/jordancruz/Tools/voice-changer/server/MMVCServerSIO.py", line 123, in <module>
    downloadWeight(voiceChangerParams)
  File "/home/jordancruz/Tools/voice-changer/server/downloader/WeightDownloader.py", line 17, in downloadWeight
    if os.path.exists(hubert_base) is False:
  File "/home/jordancruz/anaconda3/envs/mmvc-server/lib/python3.10/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

Model downloader script "WeightDownloader.py" fails to execute, causing the whole tool to fail the booting phase

**Comment by w-okada** [comment]
https://github.com/w-okada/voice-changer/blob/master/README_dev_en.md

**Comment by jurassicjordan** [comment]
> https://github.com/w-okada/voice-changer/blob/master/README_dev_en.md

thank you, you might want to have the README_en.md in master/server/ refer to that one

**Comment by w-okada** [comment]
Oh definitely! I completely forgot about that README!! Thank you so much!
