### ISSUE TITLE
Increasing Model Slots

### ISSUE THREAD

**Issue by HunterAced** [w-okada/voice-changer#360]
### Issue Type

Feature Request, Question

### vc client version number

v.1.5.3.5a

### OS

Windows 11

### GPU

980ti

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

I was wondering if there was any way to change the max amount of slots you have to store models in? 9 is pretty limiting and swapping them out for eachother if you have more than 9 models can get tedious very quickly. I tried searching trough any config files but I might have just missed the parameter. If there is no way to change this number then I suppose this is a feature request.
Ty for your time.

**Comment by w-okada** [comment]
The reason why we shouldn't increase the number of slots is that we can already anticipate that it will involve a lot of transition work if the version changes. If someone could create a transition tool, that might change the situation.


Unless a solution to this issue becomes visible, we will not be planning to increase the number of slots.
