### ISSUE TITLE
ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by jurassicjordan** [w-okada/voice-changer#361]
### Issue Type

Bug Report

### vc client version number

v.1.5.3.6 (Master)

### OS

Arch Linux server (EndeavourOS 6.3.8-zen1-1-zen)

### GPU

NVIDIA GeForce RTX 3060 Lite Hash Rate

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Voice Changer type

N/A

### Model type

N/A

### Situation

the website certificate and key are detected as unsafe by firefox, warn me in chromium browsers and refuse to load in electron nativefier.

node:128940) electron: Failed to load URL: https://192.168.1.186:18888/ with error: ERR_CERT_AUTHORITY_INVALID
(node:128940) electron: Failed to load URL: https://192.168.1.186:18888/ with error: ERR_CERT_AUTHORITY_INVALID
(node:128940) electron: Failed to load URL: https://192.168.1.186:18888/ with error: ERR_CERT_AUTHORITY_INVALID
[128940:0628/215208.426878:ERROR:CONSOLE(1)] "Request Network.loadNetworkResource failed. {"code":-32602,"message":"Unsupported URL scheme"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)

**Comment by w-okada** [comment]
I don't think it's a bug. If you want to avoid SSL errors, you can set the appropriate cert and key in the startup options.

--httpsKey, --httpsCert, --httpsSelfSigned

**Comment by jurassicjordan** [comment]
Oh thank you I was unaware of those arguments
