### ISSUE TITLE
[ERROR] [Voice Changer] Model Load Error! Check your model is valid. local variable 'inferencer' referenced before assignment

### ISSUE THREAD

**Issue by peepeepeepoopoopoo** [w-okada/voice-changer#363]
### Issue Type

Bug Report

### vc client version number

2

### OS

Windows 10

### GPU

GTX 1660 6GB

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Voice Changer type

RVC 2

### Model type

PTH + INDEX

### Situation

**I have tried with different models and I get this error, they are RVC 2 models**

[Voice Changer] update configuration: onnxExecutionProvider CPUExecutionProvider
onnxExecutionProvider is not mutable variable or unknown variable!
[Voice Changer] update configuration: f0Factor 1
[Voice Changer] update configuration: f0Detector harvest
f0Factor is not mutable variable or unknown variable!
[Voice Changer] update configuration: serverInputAudioSampleRate 48000
[Voice Changer] update configuration: serverOutputAudioSampleRate 48000
[Voice Changer] update configuration: serverInputAudioBufferSize 24576
[Voice Changer] update configuration: serverOutputAudioBufferSize 24576
[Voice Changer] update configuration: serverInputDeviceId -1
[Voice Changer] update configuration: serverOutputDeviceId -1
[Voice Changer] update configuration: serverReadChunkSize 256
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: silentThreshold 0.00001
[Voice Changer] update configuration: extraConvertSize 32768
[Voice Changer] update configuration: clusterInferRatio 0.1
clusterInferRatio is not mutable variable or unknown variable!
[Voice Changer] update configuration: modelSamplingRate 48000
[Voice Changer] update configuration: silenceFront 1
[Voice Changer] update configuration: modelSlotIndex -1
[Voice Changer] update configuration: useDiff 1
useDiff is not mutable variable or unknown variable!
[Voice Changer] update configuration: diffMethod dpm-solver
diffMethod is not mutable variable or unknown variable!
[Voice Changer] update configuration: diffAcc 20
diffAcc is not mutable variable or unknown variable!
[Voice Changer] update configuration: diffSpkId 1
diffSpkId is not mutable variable or unknown variable!
[Voice Changer] update configuration: kStep 120
kStep is not mutable variable or unknown variable!
[Voice Changer] update configuration: threshold -45
[Voice Changer] update configuration: inputSampleRate 48000
threshold is not mutable variable or unknown variable!
paramDict {'trans': 0, 'files': {'mmvcv13Config': '', 'mmvcv13Model': '', 'mmvcv15Config': '', 'mmvcv15Model': '', 'soVitsSvc40Config': '', 'soVitsSvc40Model': '', 'soVitsSvc40Cluster': '', 'soVitsSvc40v2Config': '', 'soVitsSvc40v2Model': '', 'soVitsSvc40v2Cluster': '', 'rvcModel': 'cdawgva.pth', 'rvcIndex': 'added_IVF1819_Flat_nprobe_1_cdawgva_v2.index', 'rvcFeature': '', 'ddspSvcModel': '', 'ddspSvcModelConfig': '', 'ddspSvcDiffusion': '', 'ddspSvcDiffusionConfig': ''}}
[Voice Changer] RVC new model is uploaded,0 {'modelFile': 'C:\\Users\\USUARIO\\AppData\\Local\\Temp\\tmp34rlssw_\\upload_dir\\0\\cdawgva.pth', 'featureFile': None, 'indexFile': 'C:\\Users\\USUARIO\\AppData\\Local\\Temp\\tmp34rlssw_\\upload_dir\\0\\added_IVF1819_Flat_nprobe_1_cdawgva_v2.index', 'defaultTrans': 0, 'isONNX': False, 'modelType': <EnumInferenceTypes.pyTorchRVC: 'pyTorchRVC'>, 'samplingRate': 40000, 'f0': True, 'embChannels': 256, 'deprecated': False, 'embedder': <EnumEmbedderTypes.hubert: 'hubert_base'>}
[Voice Changer] Prepare Model of slot: 0
load inf C:\Users\USUARIO\AppData\Local\Temp\tmp34rlssw_\upload_dir\0\cdawgva.pth
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] exception! loading inferencer Error(s) in loading state_dict for SynthesizerTrnMs256NSFsid:
        size mismatch for enc_p.emb_phone.weight: copying a param with shape torch.Size([192, 768]) from checkpoint, the shape in current model is torch.Size([192, 256]).
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 24, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 20, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 31, in loadInferencer
  File "voice_changer\RVC\inferencer\RVCInferencer.py", line 19, in loadModel
  File "torch\nn\modules\module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrnMs256NSFsid:
        size mismatch for enc_p.emb_phone.weight: copying a param with shape torch.Size([192, 768]) from checkpoint, the shape in current model is torch.Size([192, 256]).
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 301, in loadModel
  File "voice_changer\RVC\RVC.py", line 84, in loadModel
  File "voice_changer\RVC\RVC.py", line 153, in prepareModel
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 54, in createPipeline
UnboundLocalError: local variable 'inferencer' referenced before assignment

[Voice Changer] Model Load Error! Check your model is valid. local variable 'inferencer' referenced before assignment
Generated Strengths: for prev:(1024,), for cur:(1024,)
[Voice Changer] wait for loading model... -1 -1
[Voice Changer] [Exception] 'No model for model_common loaded. Please confirm the model uploaded.'
[Voice Changer] wait for loading model... -1 -1
[Voice Changer] [Exception] 'No model for model_common loaded. Please confirm the model uploaded.'
[Voice Changer] wait for loading model... -1 -1
[Voice Changer] [Exception] 'No model for model_common loaded. Please confirm the model uploaded.'
[Voice Changer] wait for loading model... -1 -1
[Voice Changer] [Exception] 'No model for model_common loaded. Please confirm the model uploaded.'
[Voice Changer] wait for loading model... -1 -1
[Voice Changer] [Exception] 'No model for model_common loaded. Please confirm the model uploaded.'
[Voice Changer] wait for loading model... -1 -1
[Voice Changer] [Exception] 'No model for model_common loaded. Please confirm the model uploaded.'
[Voice Changer] wait for loading model... -1 -1
[Voice Changer] [Exception] 'No model for model_common loaded. Please confirm the model uploaded.'
[Voice Changer] wait for loading model... -1 -1
[Voice Changer] [Exception] 'No model for model_common loaded. Please confirm the model uploaded.'
[Voice Changer] wait for loading model... -1 -1
[Voice Changer] [Exception] 'No model for model_common loaded. Please confirm the model uploaded.'
[Voice Changer] wait for loading model... -1 -1
[Voice Changer] [Exception] 'No model for model_common loaded. Please confirm the model uploaded.'
[Voice Changer] wait for loading model... -1 -1
[Voice Changer] [Exception] 'No model for model_common loaded. Please confirm the model uploaded.'
[Voice Changer] wait for loading model... -1 -1
[Voice Changer] [Exception] 'No model for model_common loaded. Please confirm the model uploaded.'
[Voice Changer] wait for loading model... -1 -1
[Voice Changer] [Exception] 'No model for model_common loaded. Please confirm the model uploaded.'
[Voice Changer] wait for loading model... -1 -1
[Voice Changer] [Exception] 'No model for model_common loaded. Please confirm the model uploaded.'
[Voice Changer] wait for loading model... -1 -1
[Voice Changer] [Exception] 'No model for model_common loaded. Please confirm the model uploaded.'

**Comment by w-okada** [comment]
use the latest version

**Comment by w-okada** [comment]
no res close
