### ISSUE TITLE
I got so much ms

### ISSUE THREAD

**Issue by N2K2021** [w-okada/voice-changer#364]
### Issue Type

Question

### vc client version number

1.5.3.6a

### OS

Windows 10

### GPU

None

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

i got so much ms and my sound is not coming correctly
![image](https://github.com/w-okada/voice-changer/assets/76765667/9157b2f8-b685-45b7-9c1c-74d653051a18)

**Comment by w-okada** [comment]
Please increase the value of A. For example, let's make it 1024.

**Comment by N2K2021** [comment]
What is "A" you mean chunk?

**Comment by w-okada** [comment]
Yes. "A" is Typo. I meant chunk.

**Comment by LeHungryBoi** [comment]
> Please increase the value of A. For example, let's make it 1024.

but there is no option in the ui for 1024

**Comment by w-okada** [comment]
no res close
