### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'on_request'

### ISSUE THREAD

**Issue by peepeepeepoopoopoo** [w-okada/voice-changer#365]
### Issue Type

Bug Report

### vc client version number

2

### OS

windows 10

### GPU

gtc 1660 tgb

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Voice Changer type

RVC

### Model type

PTH + INDEX

### Situation

when I give START this comes out:

AttributeError: 'NoneType' object has no attribute 'on_request'
Task exception was never retrieved
future: <Task finished name='Task-519' coro=<AsyncServer._handle_event_internal() done, defined at socketio\asyncio_server.py:522> exception=AttributeError("'NoneType' object has no attribute 'on_request'")>
Traceback (most recent call last):
  File "socketio\asyncio_server.py", line 524, in _handle_event_internal
  File "socketio\asyncio_server.py", line 569, in _trigger_event
  File "socketio\asyncio_namespace.py", line 37, in trigger_event
  File "sio\MMVC_Namespace.py", line 52, in on_request_message
  File "voice_changer\VoiceChangerManager.py", line 257, in changeVoice
AttributeError: 'NoneType' object has no attribute 'on_request'

**Comment by w-okada** [comment]
Shouldn't there be another error further up? Could you please show me the log around it?

**Comment by w-okada** [comment]
no res close

**Comment by edde746** [comment]
You get this error if you don't pick a voice/model thus the `voiceChanger` in the `VoiceChangerManager.py` is not yet initialised when you try to start it.
