### ISSUE TITLE
Index ratio is using huge CPU resource

### ISSUE THREAD

**Issue by gengzhichen** [w-okada/voice-changer#366]
![20230630-152422](https://github.com/w-okada/voice-changer/assets/787424/870e3bc5-3b0d-4230-b4e0-b8c6e710b3b7)
My env is I9-13900+ nvidia 4090
After switch index to 0.1, CPU would be used 100%.
Response time would be a very long time.
Is there any option to force index to use GPU?
Thank you

**Comment by w-okada** [comment]
use issue template
