### ISSUE TITLE
Index ratio is using huge CPU resource

### ISSUE THREAD

**Issue by gengzhichen** [w-okada/voice-changer#367]
### Issue Type

Bug Report

### vc client version number

1.5.3.6

### OS

win 11

### GPU

nvidia 4090

### Clear setting

yes

### Sample model

yes

### Input chunk num

no

### Voice Changer type

RVC

### Model type

pth index

### Situation

After set index to 0.1, CPU would be used 100%.
Response time would be a very long time.
The sample RVC model works fine.
Reproduce step:
1 train a model with Retrieval-based-Voice-Conversion-WebUI (**choose version v2**)
2 upload RVC model from rvc/weights/testname.pth  logs/testname/added_IVF3545_Flat_nprobe_1_testname_v2.index
3 use the uploaded model and set index ratio to 0.1 or more

![20230630-152422](https://github.com/w-okada/voice-changer/assets/787424/d3d3984b-584d-4729-b66c-b8c306c87d3d)

**Comment by w-okada** [comment]
It is not bug. Retrieving is very heavy process. Currently no workaround. If you want to less the load, use version 1 or not use index.

**Comment by w-okada** [comment]
no res close
