### ISSUE TITLE
M1 Macでの初回起動でダウンロードが開始しないままプロセスが完了してしまう

### ISSUE THREAD

**Issue by SakamotoBenki** [w-okada/voice-changer#368]
### Issue Type

Question

### vc client version number

1.5.3.6a

### OS

MacOS Big Sur 11.7.8, M1

### GPU

none

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Voice Changer type

none

### Model type

none

### Situation

ImportError: dlopen(/private/var/folders/sk/v0gsv6k93q1gbw9jpvrq73sw0000gn/T/AppTranslocation/9A1D0FD9-F6C0-410A-80A1-EEA4DD0FA59C/d/MMVCServerSIO.app/Contents/MacOS/scipy/special/_ufuncs_cxx.cpython-310-darwin.so, 2): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /private/var/folders/sk/v0gsv6k93q1gbw9jpvrq73sw0000gn/T/AppTranslocation/9A1D0FD9-F6C0-410A-80A1-EEA4DD0FA59C/d/MMVCServerSIO.app/Contents/MacOS/scipy/special/_ufuncs_cxx.cpython-310-darwin.so (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib

[18486] Failed to execute script 'MMVCServerSIO' due to unhandled exception: dlopen(/private/var/folders/sk/v0gsv6k93q1gbw9jpvrq73sw0000gn/T/AppTranslocation/9A1D0FD9-F6C0-410A-80A1-EEA4DD0FA59C/d/MMVCServerSIO.app/Contents/MacOS/scipy/special/_ufuncs_cxx.cpython-310-darwin.so, 2): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /private/var/folders/sk/v0gsv6k93q1gbw9jpvrq73sw0000gn/T/AppTranslocation/9A1D0FD9-F6C0-410A-80A1-EEA4DD0FA59C/d/MMVCServerSIO.app/Contents/MacOS/scipy/special/_ufuncs_cxx.cpython-310-darwin.so (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib

タイトルの通り、上記のエラーが出たのち、
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[プロセスが完了しました]
と表示されダウンロードが開始しません。1.5.3.5もダウンロードし試しましたが、全く同じ症状が出ました。

**Comment by l68728** [comment]
おそらく上記では macos12 が必要ですが、あなたのものは macos11.7.8 なのでアップグレードする必要があります。

**Comment by SakamotoBenki** [comment]
macOS12にアップデート後インストールはできましたが、一度だけ正常に起動できたのち、つくよみちゃんのアイコンを選択した後エラーが出て、リロードをしたらターミナルの方でこのエラーが永遠に出続けました。一度再起動しましたが、今度は起動時にこのエラーが出続けて起動されません。
<img width="571" alt="スクリーンショット 2023-06-30 23 13 48" src="https://github.com/w-okada/voice-changer/assets/138202457/ccca2f29-694f-49a7-a35a-a7483246b16f">

**Comment by SakamotoBenki** [comment]
初回起動でダウンロードされたファイルを全削除すると起動するようにはなりますが、つくよみちゃんに限らずいずれかのキャラを選択するとスクショの画面になり、アプリを初期化か初期化せずリロードのどちらを選択してもターミナルの方でエラーを吐き続けるようです。
<img width="759" alt="スクリーンショット 2023-06-30 23 35 37" src="https://github.com/w-okada/voice-changer/assets/138202457/eb4f1e75-30c9-4f01-9e6f-74a688e60719">

**Comment by l68728** [comment]
ほとんどの Mac ユーザーはあなたと同じ問題を抱えていますが、十分に解決されていません ➡️#339

**Comment by l68728** [comment]
I redeployed it with my colleague's m1mac, but it still runs to the model slot change and then stops
<img width="517" alt="截屏2023-07-01 09 09 22" src="https://github.com/w-okada/voice-changer/assets/46189956/2765d59b-ce65-4dfb-9217-b6275f2a8776">

**Comment by w-okada** [comment]
@SakamotoBenki 
もう少し上の方で別のエラーが出ていませんか？

**Comment by l68728** [comment]
@w-okada 
Report: 1.5.3.8a can be successfully opened and used on mac m2. System version macOS Ventura13.4.1. After downloading and decompressing, I first ran ```MMVCServerSIO```, then closed it, and then opened ```startHttp.command```, the previous problem did not appear #317 #339. First of all thanks for being able to run successfully. But still need more Mac user to verify.

Performance: run https to access through another pc Edge. When using the pth model, the minimum setting of the m2 chip chunk is 96. If it is lower than 96, the res will increase sharply (不明）. The delay is about buf256ms+ res230-270. Activity Monitor shows that the gpu 90% and the cpu 70%; when using the onnx model The minimum setting of the m2 chip chunk is 80. If it is lower than 80, the res will increase sharply (不明). The delay is about buf213ms+ res200-230. Activity Monitor shows that the gpu  60%, and the cpu takes up 280%

Extra: If you change RVC Quality to high in Advanced Setting, there will be no sound.
```[Voice Changer] VC PROCESSING EXCEPTION!!! tuple index out of range
Traceback (most recent call last):
  File "voice_changer/VoiceChanger.py", line 228, in on_request_sola
  File "voice_changer/RVC/RVC.py", line 175, in inference
  File "voice_changer/RVC/pipeline/Pipeline.py", line 106, in exec
IndexError: tuple index out of range```

**Comment by w-okada** [comment]
@l68728 
Thank you for your report.

I'm guessing Nvidia GPUs in M1/M2 Macs are significantly lower in performance compared to others, so that might be it.

@SakamotoBenki 

Would you like to give it a try?

**Comment by SakamotoBenki** [comment]
@w-okada 
すいません、返信遅れました。
1.5.3.7にアップデート後、解決しました。1.5.3.8aでも問題なく動作しています。

**Comment by w-okada** [comment]
OKey, close this issue,

similar issue remains [here](https://github.com/w-okada/voice-changer/issues/339)

**Comment by minimoonleaf** [comment]
> @w-okada 報告：1.5.3.8a在mac m2上可以成功打開並使用。系統版本macOS Ventura13.4.1。下載解壓後，我先運行`MMVCServerSIO`，然後關閉，再打開`startHttp.command`，沒有出現之前的問題[#317 ](https://github.com/w-okada/voice-changer/issues/317) #339。首先感謝您能夠成功運行。但仍需要更多Mac用戶來驗證。
> 
> 性能：運行https通過另一台PC Edge訪問。使用pth模型時，m2晶片chunk的最小設置為96。如果低於96，res會急劇增加（不清楚）。延遲約為buf256ms+ res230-270。Activity Monitor顯示gpu 90% cpu 70%；使用onnx型號時，m2晶片chunk最小設置為80，低於80，res會急劇增加（不明），延遲約為buf213ms+ res200-230，Activity Monitor顯示GPU佔60%，CPU佔280%
> 
> 額外：如果您在高級設置中將 RVC 質量更改為高，則不會有聲音。
> 
> ```
> Traceback (most recent call last):
>   File "voice_changer/VoiceChanger.py", line 228, in on_request_sola
>   File "voice_changer/RVC/RVC.py", line 175, in inference
>   File "voice_changer/RVC/pipeline/Pipeline.py", line 106, in exec
> IndexError: tuple index out of range```
> ```

I have the same problem.
