### ISSUE TITLE
Issues with App Functionality and Audio Quality on Various Systems

### ISSUE THREAD

**Issue by Marcelo-blip** [w-okada/voice-changer#372]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.6a 

### OS

Windows 11

### GPU

RX 7900 XTX

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

*I'm unable to get the app to function properly no matter what. The audio output is extremely limited, and the quality is poor with noticeable lag. I went as far as using it on my CPU, an i9 12900KS, but the issue persisted or even worsened. I have a strong desire to utilize this app effectively*. 
![Screenshot_25](https://github.com/w-okada/voice-changer/assets/84885144/542ee4d2-dae7-4d47-bc94-fbe8daf7664d)

**Comment by w-okada** [comment]
increase chunk size. your PC is not adequate for you setting.

**Comment by Marcelo-blip** [comment]
but he looks bad anyway , I've tried several things and still

**Comment by Marcelo-blip** [comment]
sound comes out but it's like I didn't say anything because only a few stutters come out

**Comment by w-okada** [comment]
increase chunk value to more large number and set F0Det to dio.

**Comment by Marcelo-blip** [comment]
the audio keeps repeating and stuttering 
![Screenshot_26](https://github.com/w-okada/voice-changer/assets/84885144/dbabb148-b267-4053-a1ec-e1fd7f49e789)
![Screenshot_27](https://github.com/w-okada/voice-changer/assets/84885144/3de54598-aaa8-441f-a0c1-9a8a59bde0e7)

**Comment by Marcelo-blip** [comment]
very much delay

**Comment by w-okada** [comment]
So your voice is converted?

You can adjust the Chunks within the range of proper audio conversion.

**Comment by Marcelo-blip** [comment]
any voice I select is the same

**Comment by w-okada** [comment]
You can adjust the "Chunks" within the range of proper audio conversion for delay.

**Comment by Marcelo-blip** [comment]
same thing very bad , Is there any way for me to use the program even if it's with the cpu I've tried and I can't

**Comment by Marcelo-blip** [comment]
it's a shame it doesn't work for me at least :(

**Comment by Marcelo-blip** [comment]
I tried chunck 1024 and more , but i get a same thing Very delay and stuttering

**Comment by Marcelo-blip** [comment]
My GPU is the best of AMD and my CPU is one of the best in intel
