### ISSUE TITLE
what should i do，I don't know much about programming

### ISSUE THREAD

**Issue by ricardosxx** [w-okada/voice-changer#374]
### Issue Type

Question

### vc client version number

v.1.5.3.6a

### OS

windows 11

### GPU

rtx 3050ti

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Voice Changer type

MMVC v1.3, RVC

### Model type

pyTorch

### Situation

When I started the http.bat program, he kept prompting me：[MMVC v1.3, RVC](electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED)

**Comment by w-okada** [comment]
more log.

**Comment by ricardosxx** [comment]
Booting PHASE :__main__
    Voice Changerを起動しています。
HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /wok000/vcclient_model/raw/main/samples_0003_t2.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B3981AC0A0>: Failed to resolve 'huggingface.co' ([Errno 11001] getaddrinfo failed)"))
HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /wok000/vcclient_model/raw/main/samples_0003_o2.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B3981AC220>: Failed to resolve 'huggingface.co' ([Errno 11001] getaddrinfo failed)"))
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] model slot is changed -1 -> 2
................RVC
Preparing your application. Please wait...
(node:17164) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
[Voice Changer] [RVC] Creating instance
[Voice Changer] [RVC] Initializing...
inferencerTypeinferencerTypeinferencerTypeinferencerType pyTorchRVC
[Voice Changer] exception! loading inferencer [Errno 2] No such file or directory: 'model_dir\\2\\kikoto_mahiro_v2_40k_simple.onnx'
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 19, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 24, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 36, in loadInferencer
  File "voice_changer\RVC\inferencer\RVCInferencer.py", line 16, in loadModel
  File "torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'model_dir\\2\\kikoto_mahiro_v2_40k_simple.onnx'
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer]  exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 26, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 25, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 45, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 12, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] Loading index...
Preparing your application. Please wait...
(node:17164) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:17164) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:17164) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:17164) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED

**Comment by Billy2000k** [comment]
mine too

Booting PHASE :__main__
    Voice Changerを起動しています。
    RVC用のモデルファイルのダウンロードに失敗しました。
    failed to download weight for rvc
[Errno 2] No such file or directory: 'samples_0003_t2.json'
[Errno 2] No such file or directory: 'samples_0003_o2.json'
[Voice Changer] loading sample failed [Errno 2] No such file or directory: 'samples_0003_t2.json'
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] Web Server Launch Exception Directory 'model_dir' does not exist
Preparing your application. Please wait...
(node:18140) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
Preparing your application. Please wait...
(node:18140) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:18140) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:18140) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:18140) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:18140) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:18140) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED

**Comment by w-okada** [comment]
> failed to download weight for rvc
App said failed to download weight. Your pc is conneted to internet?

**Comment by ricardosxx** [comment]
Since I am in China, I successfully downloaded the component using a proxy tool and it still prompted me to refuse access to port 18888. I have previously successfully downloaded several hundred megabytes of components from the hugging interface, which was automatically downloaded by the program

**Comment by w-okada** [comment]
same

https://github.com/w-okada/voice-changer/issues/379
