### ISSUE TITLE
使用RVC切换模型时候音调出现了问题

### ISSUE THREAD

**Issue by yuanqiyinpin** [w-okada/voice-changer#375]
### Issue Type

Bug Report, Question

### vc client version number

1.5.3.6a

### OS

win10

### GPU

4090

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

你好作者。我在使用RVC区块的AUDIO时候，使用server 类型作为输入输出。切换模型时候，音调都变化了，需要重新启动该软件才正常，我需要修改那一列的代码？但是用 AUDIO的client 方式，切换模型使用，音色都是没有问题的。

**Comment by w-okada** [comment]
TUNEの値を変更しても音程が変わりませんか？変更後はsave settingを行わないと設定は保存されません。設定を保存すると再度同じモデルを選択するとその値が反映されると思います。

**Comment by yuanqiyinpin** [comment]
![60CEDBEC-003B-4B84-A108-C58D705AFC0B](https://github.com/w-okada/voice-changer/assets/107650954/420c5482-1646-4ebc-81cc-43c4e28fcc9a)
这是我自己做了汉化中文，使用AUDIO的client默认，切换模型，音调都是没有问题的，打上✓就是没问题，如果使用server ，切换模型时候声音会很奇怪，我不知道那里出现了问题。我很抱歉，打扰您，我想知道哪里出了问题。

**Comment by yuanqiyinpin** [comment]
即使save setting存储参数了。也一样的。只有切换AUDIO的client，才会正常。

**Comment by yuanqiyinpin** [comment]
及时用您的原版没有汉化修改过的客户端也一样的问题。

**Comment by yuanqiyinpin** [comment]
> TUNEの値を変更しても音程が変わりませんか？変更後はsave settingを行わないと設定は保存されません。設定を保存すると再度同じモデルを選択するとその値が反映されると思います。

不行
