### ISSUE TITLE
Docker Model stuck on "Booting PHASE :MMVCServerSIO"

### ISSUE THREAD

**Issue by PixGuy** [w-okada/voice-changer#377]
### Issue Type

Bug Report

### vc client version number

v.1.5.3.7 (just git cloned the repo)

### OS

Gentoo Linux

### GPU

AMD RX 6600

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### Voice Changer type

doesn't even load up

### Model type

default with the docker model

### Situation

As I mentioned in the title, upon running
`USE_GPU=off bash start_docker.sh`
(I use it with the GPU turned off since running with the GPU gives me an error which I will not bother fixing since AMD is not officially supported)

It keeps stuck at: `Booting PHASE :MMVCServerSIO` (I've left it running for about an hour)
please help me fix this as I believe this is a really interesting project!

**Comment by PixGuy** [comment]
UPDATE: Upon running with Conda I get the same results, I'm not sure if this is a me error or if this project has compatibility issues with Gentoo

**Comment by Orbsa** [comment]
I am also experiencing this at the moment running the docker container on ArchLinux

RTX2080 with Nvidia-Container-Toolkit installed

**Comment by TheTrustedComputer** [comment]
I'm having the same problem running the Docker container on Arch as well. For now, I'm currently running it through Wine, and it works there.

**Comment by Eidenz** [comment]
Same issue trying to run it on UNRAID (Linux Slackware) with Nvidia-Container and an RTX 2080.

Tried in CPU mode and the anaconda version but always end up stuck on "Booting PHASE :MMVCServerSIO".

**Comment by Phoenix7767** [comment]
Same here... just having it stuck in the booting phase. I had alread installed it a couple weeks ago but now nothing works

**Comment by w-okada** [comment]
uuu,mmm.

I test on ubuntu, debian, wsl2. But I have no environment of arch, gentoo.
I have no idea.

**Comment by PixGuy** [comment]
> uuu,mmm.
> 
> 
> 
> I test on ubuntu, debian, wsl2. But I have no environment of arch, gentoo.
> 
> I have no idea.
> 
> 

Try to setup an Arch vm or run on top of WSL.
If it works on Arch, chances are it will also work on Gentoo.

**Comment by w-okada** [comment]
One possibility could be that freeze_support() is causing this issue. For those who can try it on conda, could you please open the file and try to comment out the code?

https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support

**Comment by w-okada** [comment]
no res close
