### ISSUE TITLE
說話時會有回音

### ISSUE THREAD

**Issue by newhand22207807** [w-okada/voice-changer#378]
### Issue Type

Question

### vc client version number

1.5.3.5a

### OS

windows 10

### GPU

RTX 3070

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### Voice Changer type

rvc

### Model type

default

### Situation

請問說話時會有回音，會重複說2~3三次，每次聲音都不太一樣。
是耳機品質的關係嗎?還是哪裡沒設定好呢?

**Comment by w-okada** [comment]
ヘッドセットが出力音を拾っているのだと思います。残念ながらアプリ側で回避策はないと思います。

**Comment by newhand22207807** [comment]
わかりました、もう一度テストしてみます、ありがとう~

**Comment by w-okada** [comment]
no update close
