### ISSUE TITLE
Cannot running GUI，(node:20352) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by hpx502766238** [w-okada/voice-changer#379]
### Issue Type

Bug Report

### vc client version number

1.5.3.7

### OS

Windows 11 Home

### GPU

RTX 3060 Laptop

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### Voice Changer type

RVC

### Model type

f0,pyTorch,ONNX

### Situation

I have tried MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.7 and MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.7,both of them have the same issue.

[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] ONNX Model: Official v2 like
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

Preparing your application. Please wait...
(node:20352) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] model slot is changed -1 -> 1
................RVC
[Voice Changer] [RVC] Creating instance
[Voice Changer] [RVC] Initializing...
inferencerTypeinferencerTypeinferencerTypeinferencerType onnxRVC
[Voice Changer] generate new embedder. (no embedder)
Preparing your application. Please wait...
(node:20352) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[Voice Changer]  exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 26, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 25, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 45, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 12, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] Loading index...
[Voice Changer] Web Server Launch Exception local variable 'embedder' referenced before assignment
Preparing your application. Please wait...
(node:20352) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:20352) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:20352) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:20352) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...

**Comment by hpx502766238** [comment]
ok,I have resolved by myself.I reinstalled the VoiceChanger， and downloaded all package needed successfully using Internet proxy,and now I can use it normally.Why the issue occured,I guess it may be that I have a Internet connection issue when first launch,then I use"control+c"termination command and launch again,so some step cannot back to normal,reported an error.

**Comment by hpx502766238** [comment]
Another question,I have two GPUs,one is RTX 3060,the other is AMD R7 5800H Radeon Graphics.I want to use AMD to infer,how to?

**Comment by w-okada** [comment]
> I guess it may be that I have a Internet connection issue when first launch,then I use"control+c"termination command and launch again,so some step cannot back to normal,reported an error.

This is very useful information. I didn't know what would happen if the download got interrupted in the middle. Thank you!

**Comment by w-okada** [comment]
> Another question,I have two GPUs,one is RTX 3060,the other is AMD R7 5800H Radeon Graphics.I want to use AMD to infer,how to do?

Currently there is no way to select Nvida and AMD.

**Comment by w-okada** [comment]
Okey, Original Issue is resolved. I close this.
