### ISSUE TITLE
electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED Preparing your application. Please wait...

### ISSUE THREAD

**Issue by cyberrin** [w-okada/voice-changer#382]
### Issue Type

Question

### vc client version number

1.5.3.7

### OS

Windows 11

### GPU

GTX 770

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### Voice Changer type

RVC

### Model type

None yet

### Situation

The GUI started, but just as an empty window, electron cannot connect to port, both GUI app and server app are allowed in firewall, so where is a problem? 
![image](https://github.com/w-okada/voice-changer/assets/47496727/08994aff-95d1-4546-9a22-b6f4fdc9d396)
![image](https://github.com/w-okada/voice-changer/assets/47496727/634c58a2-780a-4fe3-a321-e57f297bfd18)

**Comment by w-okada** [comment]
CUBLAS_STATUS_ALLOC_FAILED occured. It looks like there isn't enough memory on the GPU.

https://ohtayo.hatenablog.com/entry/2019/05/05/110417

**Comment by cyberrin** [comment]
Oh, I see, can I somehow launch it using only CPU then?

**Comment by w-okada** [comment]
For now, no. It may work if you use the directML version which does not access CUDA.

**Comment by cyberrin** [comment]
Got it, thank you

**Comment by LeleGaming** [comment]
i have the same issue how to solve the problem?
![image](https://github.com/w-okada/voice-changer/assets/97451047/7d84093b-d79e-4450-8ef1-f82172c398ad)

**Comment by w-okada** [comment]
@Ardelle-1 
Is that the same phenomenon? It doesn't seem to be producing a traceback.

**Comment by Ardelle-1** [comment]
> @Ardelle-1 Is that the same phenomenon? It doesn't seem to be producing a traceback.

I can't say if it's the exact same issue as OP because the only reference to a traceback is that "--trace-warnings' thing. However I do have the issue mentioned in the title: that being the "CONNECTION_REFUSED" thing and I have no idea how to fix it because nothing has worked. I'm trying to run the AMD version on my 6950xt if that matters.

**Comment by w-okada** [comment]
OK, If the same problem, answer is "CUBLAS_STATUS_ALLOC_FAILED occured. It looks like there isn't enough memory on the GPU."


https://ohtayo.hatenablog.com/entry/2019/05/05/110417

**Comment by finnskull** [comment]
im having the same issue, i got an 8gb rtx 3070ti, what could be causing this? please help!

**Comment by adigarst** [comment]
I also have this problem, i am using Macbook Pro M1, MacOs Ventura 13.4.1

At first, I installed the latest version. v.1.5.3.10a. But it failed to install because the GUI Apps didn't appear at all.

I read the suggestions, to downgrade to version 1.5.3.9, and I did it.

In the version 1.5.3.9, The GUI had successfully appeared, but there was no response at all.

And then, I closed, then reopened, the GUI appears a white screen as above, with the same error confirmation as above.

Is it possible that the problem is a lack of GPU memory? i have restarted the mac and made sure no other apps are running.

Please help me sir. Thanks

**Comment by atrutlebtw** [comment]
i have the same issue as above, mac running 1.5.3.9, if i open without saved settings, it opens but will ask to initialise when i pick a voice, from there its just a repeating string of 
Preparing your application. Please wait...
(node:3907) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED


heres the full text

    Booting PHASE :__main__
    PYTHON:3.10.9 (main, Jan 15 2023, 23:00:56) [Clang 14.0.0 (clang-1400.0.29.202)]
    Voice Changerを起動しています。
++[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- -- 
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/
2023-07-25 14:23:52.013 voice-changer-native-client[3907:62960] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
[3909:0725/142352.354300:ERROR:simple_file_enumerator.cc(58)] Could not get file info for /Users/solomonannetts/Library/Application Support/voice-changer-native-client/Cache/Cache_Data/6c0030b8e783852f_0
Preparing your application. Please wait...
(node:3907) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
Preparing your application. Please wait...
(node:3907) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:3907) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
    Booting PHASE :__main__
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
mac model_dir: /Users/solomonannetts/Downloads/MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.9/model_dir
[2023-07-25 14:24:27] connet sid : vXBFHVCYNKgjERp0AAAC
[2023-07-25 14:24:27] connet sid : X93RcPDo-EzJEtjKAAAD
[Voice Changer] update configuration: modelSlotIndex 1690259068000
[Voice Changer] model slot is changed -1 -> 0
................RVC
Preparing your application. Please wait...
(node:3907) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:3907) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:3907) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:3907) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:3907) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
P

**Comment by ImMX96** [comment]
Hey, this app was working perfectly for a few days, then it stopped working, Restarted it and receive this issue.

Nothing has changed on my system, but I thought the event log would be helpful

GPU: Nvidia RTX 3050 
Windows 11

`The description for Event ID 0 from source nvlddmkm cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

\Device\Video9
Error occurred on GPUID: 100

The message resource is present but the message was not found in the message table`

**Comment by PewPew06ProYT** [comment]
I have the same problems, i can't use the app and i have rtx 4050 on my windows 11. 
The first time i opened the file everything worked fine, after the reboot it didn't work anymore.
Plis help me
![image](https://github.com/w-okada/voice-changer/assets/92674862/4241139c-e3db-462f-b29f-8c3981fa9f68)

**Comment by Shiiroex** [comment]
So i have this issue, never got it to even start and the client is white blank, any solution? please help i'm using the latest version
 "MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11"
[VCClient] Access http://localhost:18888/
(node:17188) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:18888
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
(node:17188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
    
    
![image](https://github.com/w-okada/voice-changer/assets/140978940/d7266bde-ff11-49e9-8e68-4ff99bd65628)
![image](https://github.com/w-okada/voice-changer/assets/140978940/ff258122-2856-4dcf-a657-97d5f4d17cc1)
![image](https://github.com/w-okada/voice-changer/assets/140978940/920c580b-b14b-4289-a55c-1cd5cf7335e0)
