### ISSUE TITLE
AMD顯卡無法被檢測到，皆是以CPU運行

### ISSUE THREAD

**Issue by llamasensei7746** [w-okada/voice-changer#383]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.7-001

### OS

win10 21H2 19044.3086

### GPU

RX6600

### Clear setting

yes

### Sample model

yes

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### Voice Changer type

RVC

### Model type

ONNX

### Situation

I downloaded the directML version, but I can't run with gpu, when I start using cpu all run with cpu and used 90%
The sound became spike and the latency was very high
have confirmed that the rx6600 is supported by onnxruntime
The graphics card driver is also the latest, and supports directML
What is the solution?

btw,im using transtlator.

**Comment by w-okada** [comment]
How about gpu usage displayed in performance monitor? 
Of course, not all processing runs on onnxruntime. If the usage of AMD GPUs is increasing, then onnxruntime dirctML should be working. The rest of the parts running outside of onnxruntime are making CPU usage go up. For example F0 estimation, retrieving features, or so.

**Comment by x1207349263** [comment]
same,my gpu is 6700xt and also run with my cpu.
![image](https://github.com/w-okada/voice-changer/assets/110819542/574ba0af-7efa-496d-880e-401b67ef517f)

**Comment by llamasensei7746** [comment]
> 
I tested
this is no running VC
[https://media.discordapp.net/attachments/606063911896088581/1125330884539719760/image.png?width=731&height=676](url)

This is running VC
[https://cdn.discordapp.com/attachments/606063911896088581/1125331855755976824/image.png](url)

Yes,it still using GPU but very low usage and make it so lagging

**Comment by w-okada** [comment]
Set index to zero. Processing index is very heavy.

**Comment by w-okada** [comment]
no res close

**Comment by ProFFs** [comment]
What the index? i have same problem

**Comment by Katze719** [comment]
Issue is still there with index set to 0

**Comment by llamasensei7746** [comment]
> no res close

Sorry, I've been a little busy lately, even if I set it to 0, it's the same

**Comment by x1207349263** [comment]
> > no res close
> 
> Sorry, I've been a little busy lately, even if I set it to 0, it's the same

I upgraded the latest version and the max GPU load is about 30%.Besides,I upload other model,but it cant run normally.I try exporting the model to onnx but the software reported an error.
![image](https://github.com/w-okada/voice-changer/assets/110819542/7ce8c114-0a33-4fcf-8efa-61c138768f9d)

**Comment by w-okada** [comment]
As I mention above, it's being processed by the GPU alone.

**Comment by dudostka228** [comment]
RX 580 is not included. please add it

**Comment by SankiruKun** [comment]
> RX 580 в комплект не входит. Пожалуйста, добавьте его
still not added?

**Comment by StoneCentaur2** [comment]
I have an rx 5500 xt 8GB and it doesn't detect the gpu

**Comment by Kuuko-fokkusugaru** [comment]
> I have an rx 5500 xt 8GB and it doesn't detect the gpu

Try v2 of RVC https://huggingface.co/wok000/vcclient000/tree/main

**Comment by binplatin** [comment]
> ### Issue Type
> Question
> 
> ### vc client version number
> MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.7-001
> 
> ### OS
> win10 21H2 19044.3086
> 
> ### GPU
> RX6600
> 
> ### Clear setting
> yes
> 
> ### Sample model
> yes
> 
> ### Input chunk num
> no
> 
> ### Wait for a while
> The GUI successfully launched.
> 
> ### Voice Changer type
> RVC
> 
> ### Model type
> ONNX
> 
> ### Situation
> I downloaded the directML version, but I can't run with gpu, when I start using cpu all run with cpu and used 90% The sound became spike and the latency was very high have confirmed that the rx6600 is supported by onnxruntime The graphics card driver is also the latest, and supports directML What is the solution?
> 
> btw,im using transtlator.

did u fixec it? if yes pls tell me how i got the same problem my gpu is not getting used and my cpu is always on like 90% if i activate the vc.
