### ISSUE TITLE
GPU模式下如何强制只用AMD显卡推理？

### ISSUE THREAD

**Issue by hpx502766238** [w-okada/voice-changer#384]
### Issue Type

Feature Request, Question

### vc client version number

1.5.3.7

### OS

Windows 11

### GPU

RTX 3060，5800H Radeon Graphics

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### Voice Changer type

RVC

### Model type

ONNX

### Situation

GPU模式下如何强制只用AMD显卡推理？我尝试在设备管理器禁用RTX3060，仅靠AMD 5800H核显可以独立运行（在DirectML模式下可完成推理，GPU占用40%，显存100%，CPU30%），但我只要将3060独显解除禁用，3060立马被占用1.5G的显存，即使此时依然用核显进行推理。试过在windows首选图形处理器、NVIDIA控制面板中修改程序的首选处理器，但是并不起作用。因为我只要开启独显，独显的编号就会替代核显变成GPU0，核显变成GPU1，软件好像就去默认识别GPU0了.

**Comment by w-okada** [comment]
onnxruntime-directml of python desn't support to select gpu. Please send feature request to onnxruntime community.

**Comment by hpx502766238** [comment]
import os
import onnxruntime

# Set the desired GPU device ID
os.environ["CUDA_VISIBLE_DEVICES"] = "0"  # Set to 0 to use the first GPU device

# Create the ONNX Runtime Session
session = onnxruntime.InferenceSession("model.onnx", providers=["DirectML"])

# Run inference
input_data = ...  # Prepare input data
output = session.run([], {'input': input_data})

# Process the output
...

**Comment by hpx502766238** [comment]
在上述示例中，通过设置 CUDA_VISIBLE_DEVICES 环境变量为 "0"，我们指定了要使用的 GPU 设备为第一个 GPU。您可以根据实际情况修改该值来选择其他 GPU 设备，例如 "1" 表示第二个 GPU，依此类推。

请注意，这里使用了 "CUDA_VISIBLE_DEVICES" 环境变量，即使我们使用的是 DirectML 运行提供程序。这是因为 ONNX Runtime-DirectML 在内部使用了 CUDA 运行时来与 GPU 交互，所以我们使用了 CUDA 相关的环境变量来指定要使用的 GPU。

另外，如果您希望在代码中动态选择 GPU 设备，可以使用第三方库，如 torch.cuda（适用于 PyTorch）或 tensorflow.config（适用于 TensorFlow），来设置当前使用的 GPU 设备。

**Comment by hpx502766238** [comment]
这是ChatGPT给出的答案，请参考。

**Comment by hpx502766238** [comment]
当系统中存在多个支持 DirectML 的 GPU，并且您希望在这些 GPU 中选择特定的一个进行推理时，您可以使用 ONNX Runtime 的 set_providers 方法来指定所需的执行提供程序和设备。

以下是一种选择特定 GPU 进行推理的示例代码：
import onnxruntime

# 获取可用的执行提供程序
available_providers = onnxruntime.get_available_providers()
print("可用的执行提供程序:", available_providers)

# 创建 ONNX Runtime 会话，并设置执行提供程序和设备
providers = ['DirectMLExecutionProvider']
options = onnxruntime.SessionOptions()
options.set_providers(providers)
options.set_cuda_device_id(1)  # 设置所需的 GPU 设备索引

# 加载模型并创建会话
model_path = "model.onnx"
session = onnxruntime.InferenceSession(model_path, options)

# 运行推理
input_data = ...  # 准备输入数据
output = session.run([], {'input': input_data})

# 处理输出
...
在上述示例中，我们首先使用 onnxruntime.get_available_providers() 函数获取可用的执行提供程序列表，并打印出来以确认 DirectML 执行提供程序存在。

然后，我们创建了一个 SessionOptions 对象，并使用 set_providers 方法指定执行提供程序为 'DirectMLExecutionProvider'。接下来，使用 set_cuda_device_id 方法设置所需的 GPU 设备索引，其中 1 是您要选择的 GPU 设备的索引。您可以根据您的实际情况设置正确的设备索引。

最后，我们加载模型、创建会话，并使用指定的执行提供程序和设备进行推理。

请确保系统中同时存在支持 DirectML 的多个 GPU，并且已正确安装和配置相应的驱动程序和运行时环境。在运行代码之前，建议使用示例代码中的打印语句来验证可用的执行提供程序，并适当调整代码中的设备索引以选择正确的 GPU。


diectml和cuda是什么关系呢？为什么使用的是set_cuda_device_id呢？
在使用 ONNX Runtime-DirectML 进行推理时，我们使用 set_cuda_device_id 方法来设置所需的 GPU 设备索引是因为 ONNX Runtime 在实现 DirectML 支持时采用了与 CUDA 相似的编程模型和接口，这样做有助于代码的一致性和可移植性。即使我们使用的是支持 DirectML 的 AMD GPU，我们仍然使用 set_cuda_device_id 方法来指定设备索引，因为 ONNX Runtime 在这方面保持了一致的命名和接口

**Comment by hpx502766238** [comment]
import onnxruntime

# 获取可用的执行提供程序
available_providers = onnxruntime.get_available_providers()
print("可用的执行提供程序:", available_providers)

# 加载模型并创建会话
model_path = "model.onnx"
session = onnxruntime.InferenceSession("model.onnx",providers=['DmlExecutionProvider'])
session.set_providers(['DmlExecutionProvider'], [ {'device_id': 0}])
# 运行推理
input_data =... # 准备输入数据
output = session.run([], {'input': input_data})

**Comment by hpx502766238** [comment]
用set_providers修改device_id就行了，用pycharm试过了应该不会错了

**Comment by hpx502766238** [comment]
https://blog.csdn.net/weixin_41449637/article/details/116486847
