### ISSUE TITLE
rvc切换模型出现报错

### ISSUE THREAD

**Issue by yuanqiyinpin** [w-okada/voice-changer#387]
### Issue Type

Bug Report, Question

### vc client version number

1.5.3.7

### OS

win

### GPU

4090

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### Voice Changer type

RVC

### Model type

onnx

### Situation

![C6EA3009-A691-4CC3-A50F-EEB68863396D](https://github.com/w-okada/voice-changer/assets/107650954/07210a85-ffd7-4b9b-b82b-91541b35d946)
出现报错

**Comment by w-okada** [comment]
no info to reproduce. close
