### ISSUE TITLE
gpu not detected ?

### ISSUE THREAD

**Issue by acewins727** [w-okada/voice-changer#388]
### Issue Type

Bug Report

### vc client version number

1.5.3.7

### OS

windows 10 pro N

### GPU

Nvidia GeForce RTX 2070 SUPER

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

my gpu is not detected by the voice changer even though I have an nvidia gpu 
![image](https://github.com/w-okada/voice-changer/assets/120285704/dec03660-cc99-40b6-b4f7-7a45bc4eca07)

**Comment by w-okada** [comment]
which file did you download?

**Comment by acewins727** [comment]
the second windows one 
![image](https://github.com/w-okada/voice-changer/assets/120285704/a3e84177-2549-4485-82e1-f6254d3dcc89)
if I remember correctly the other one didn't even work

**Comment by w-okada** [comment]
show me log in the terminal. Are there the message like this? if GPU_NUM is zero, no gpu detected by python and pytorch. 

```
VoiceChanger Initialized (GPU_NUM:1, mps_enabled:False)
```

**Comment by w-okada** [comment]
no res close.

**Comment by acewins727** [comment]
i forgor

**Comment by acewins727** [comment]
but yes pytorch  doesn't detect cuda and by extension my gpu

**Comment by ElenoreAlkirara** [comment]
i have same issue how i can fix thatt

**Comment by MumeiHiganbana** [comment]
same here, my gpu is Radeon Vega 8

**Comment by Neplex42** [comment]
same here, my gpu is AMD Radeon RX 6800 XT

**Comment by Thomas5636** [comment]
same issue my gpu is the Geforce GTX 1660 Super

**Comment by Thomas5636** [comment]
[Voice Changer] [RVC] Initializing... done
VoiceChanger Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:CPU-DML)
[Voice Changer][RVC]: update_settings gpu -1
[Voice Changer] [RVC] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)

**Comment by w-okada** [comment]
> VoiceChanger Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:CPU-DML)

your gpu is detected

**Comment by DeadEli** [comment]
How can i Fix it?

**Comment by afafontes** [comment]
I have same issue, my gpu is not detected (updated pytorch)

VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:False, onnx_device:GPU)

**Comment by XtraviVolume** [comment]
I have the same problem, can't find a solution anywhere.

**Comment by XtraviVolume** [comment]
Ah, guys look, if you have an error on NVIDIA card, download version ONNX(cpu,DirectML), PyTorch(cpu,cuda).And vice versa, read the framework

**Comment by Costalito12** [comment]
same here, my gpu is RX 5700 XT also im using the DIRECTML, then why???

**Comment by ElenoreAlkirara** [comment]
What about amd gpu?

**Comment by Bengeecore** [comment]
I have the same problem, but I have a graphics card from Intel (discrete) - Intel Arc A310

**Comment by alviowo** [comment]
help, the voice changer recognize gpu how cpu, help me, i have RX 6600
