### ISSUE TITLE
will amd gpu support be added?

### ISSUE THREAD

**Issue by sasuniki** [w-okada/voice-changer#389]
### Issue Type

Feature Request, Question

### vc client version number

1.5.3.6a

### OS

Windows 10

### GPU

rx5700 xt

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

yes

### Voice Changer type

RVC

### Model type

onnx

### Situation

Will support for amd graphics cards be added, it is partially there, but almost not felt and the program runs mostly on the CPU, which affects the slow performance. ROCm maybe

**Comment by w-okada** [comment]
What happens to the load if the index value is set to zero?

**Comment by sasuniki** [comment]
> What happens to the load if the index value is set to zero?

Yep its work better, but not fine any way, and crepe mode working very slow

**Comment by w-okada** [comment]
I guess there's nothing we can do.
