### ISSUE TITLE
Cannot select input microphone

### ISSUE THREAD

**Issue by DoonielVC** [w-okada/voice-changer#390]
### Issue Type

Bug Report

### vc client version number

1.5.3.7

### OS

Windows 11

### GPU

MSI 4090

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

I can't select an input device, when I select any input device it results in the screenshot below. Is there a setting I'm missing?
(Where I'm selecting the input device, so there's no confusion): 
![image](https://github.com/w-okada/voice-changer/assets/138523172/8d5eefa1-7ea2-4774-9138-89dd43e40511)

The resulting error screen: 
![image](https://github.com/w-okada/voice-changer/assets/138523172/1aa4a9c9-59fd-4159-a73e-66711d0cd334)

Any help would be much appreciated.

**Comment by w-okada** [comment]
Any logs in terminal？

**Comment by DoonielVC** [comment]
nothing happens in the terminal when this happens.

**Comment by w-okada** [comment]
I can not reproduce it.  Are there any others with the same phenomenon?

**Comment by w-okada** [comment]
no res close

**Comment by DarakuTenshi** [comment]
Yup, I have the same problem. Output can be selected without issue but input cannot. Also after testing the mic everything seems fine from the windows side of things.

**Comment by DarakuTenshi** [comment]
Ok, I think I may have figured it out. My security settings on Windows was set to block usage of my microphone on desktop apps.

**Comment by TechChris334** [comment]
> Ok, I think I may have figured it out. My security settings on Windows was set to block usage of my microphone on desktop apps.

it didnt work i have this problem

**Comment by Kuuko-fokkusugaru** [comment]
Try uninstalling Nvidia broadcast

**Comment by tur4ick** [comment]
> Try uninstalling Nvidia broadcast

Does it help? Have same problem((
