### ISSUE TITLE
意味の分からない囁きや唸り声のような音声になります。

### ISSUE THREAD

**Issue by ChineeseMafia** [w-okada/voice-changer#391]
### Issue Type

Question

### vc client version number

1.5.3.7and1.5.3.6a

### OS

Windows 11

### GPU

RTX 3070

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

起動した後、上手く動作したことを確認し次の日にコンピューターを起動してまたすぐに試してみると、パーセルタングや意味の分からない囁きのような音声になって再生されるようになった。start_http.bat及びstart_https.batのどちらも初回起動時だけうまく動作し、その後は同じ現象が起きるようになった。マイクは正常に動作しており問題はありません。
MANLIというメーカーのコンデンサーマイクをSteinbergUR22に繋いで使用しています。

以下はログになります。

C:\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/checkpoint_best_legacy_500.onnx     --content_vec_500_onnx_on false     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    Voice Changerを起動しています。
++[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] model slot is changed -1 -> 4
................RVC
Preparing your application. Please wait...
(node:1992) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
[Voice Changer] [RVC] Creating instance
[Voice Changer] [RVC] Initializing...
inferencerTypeinferencerTypeinferencerTypeinferencerType pyTorchRVCv2
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
GENERATE INFERENCER <voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x0000022CC4241570>
GENERATE EMBEDDER <voice_changer.RVC.embedder.FairseqHubert.FairseqHubert object at 0x0000022D92CF5CC0>
GENERATE PITCH EXTRACTOR <voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x0000022D92CF5D20>
[Voice Changer] [RVC] Initializing... done
VoiceChanger Initialized (GPU_NUM:1, mps_enabled:False)
[Voice Changer][RVC]: update_settings serverReadChunkSize 512
[Voice Changer][RVC]: update_settings extraConvertSize 32768
[Voice Changer][RVC]: update_settings modelSlotIndex 1688411842004
[Voice Changer][RVC]: update_settings serverReadChunkSize 512
[Voice Changer][RVC]: update_settings extraConvertSize 32768
[2023-07-04 04:26:19] connet sid : BlOg7SBYbQgI968TAAAB
[2023-07-04 04:26:19] connet sid : 0aSRuJrwrxgWM-m3AAAD
[Voice Changer] update configuration: tran 2
[Voice Changer][RVC]: update_settings tran 2
[Voice Changer] update configuration: tran 3
[Voice Changer][RVC]: update_settings tran 3
[Voice Changer] update configuration: tran 4
[Voice Changer][RVC]: update_settings tran 4
[Voice Changer] update configuration: tran 5
[Voice Changer][RVC]: update_settings tran 5
[Voice Changer] update configuration: tran 6
[Voice Changer][RVC]: update_settings tran 6
[Voice Changer] update configuration: tran 7
[Voice Changer][RVC]: update_settings tran 7
[Voice Changer] update configuration: tran 8
[Voice Changer][RVC]: update_settings tran 8
[Voice Changer] update configuration: tran 8
[Voice Changer][RVC]: update_settings tran 8
[Voice Changer] update configuration: tran 9
[Voice Changer][RVC]: update_settings tran 9
[Voice Changer] update configuration: tran 10
[Voice Changer][RVC]: update_settings tran 10
[Voice Changer] update configuration: tran 11
[Voice Changer][RVC]: update_settings tran 11
[Voice Changer] update configuration: tran 12
[Voice Changer][RVC]: update_settings tran 12
[Voice Changer] update configuration: tran 13
[Voice Changer][RVC]: update_settings tran 13
[Voice Changer] update configuration: tran 14
[Voice Changer][RVC]: update_settings tran 14
[Voice Changer] update configuration: tran 14
[Voice Changer][RVC]: update_settings tran 14
[Voice Changer] update configuration: tran 13
[Voice Changer][RVC]: update_settings tran 13
[Voice Changer] update configuration: tran 12
[Voice Changer][RVC]: update_settings tran 12
[Voice Changer] update configuration: indexRatio 0.1
[Voice Changer][RVC]: update_settings indexRatio 0.1
[Voice Changer] update configuration: indexRatio 0.1
[Voice Changer][RVC]: update_settings indexRatio 0.1
[Voice Changer] update configuration: indexRatio 0.2
[Voice Changer][RVC]: update_settings indexRatio 0.2
[Voice Changer] update configuration: indexRatio 0.3
[Voice Changer][RVC]: update_settings indexRatio 0.3
[Voice Changer] update configuration: indexRatio 0.4
[Voice Changer][RVC]: update_settings indexRatio 0.4
[Voice Changer] update configuration: indexRatio 0.6
[Voice Changer][RVC]: update_settings indexRatio 0.6
[Voice Changer] update configuration: indexRatio 0.7
[Voice Changer][RVC]: update_settings indexRatio 0.7
[Voice Changer] update configuration: indexRatio 0.9
[Voice Changer][RVC]: update_settings indexRatio 0.9
[Voice Changer] update configuration: indexRatio 1
[Voice Changer][RVC]: update_settings indexRatio 1
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] warming up... generating sola buffer.
[13520:0704/042813.660:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is

**Comment by w-okada** [comment]
Show me setting in window.

**Comment by macmurp** [comment]
I am also getting this "Passthrough is not supported, GL is disabled" error. If there is anything I can provide to help as well, let me know

**Comment by ChineeseMafia** [comment]
![17e6a32c4b22cb0b79f79c0c650b0bbb](https://github.com/w-okada/voice-changer/assets/138525412/e3c33f35-8b54-476e-8207-fa994e69c1c5)

Are you sure this is the right screen?

**Comment by ChineeseMafia** [comment]
元々1周辺で試してダメだったので、声が小さいのかなと思って一時的に上げていたものでした。
TUNE、INDEXの方も値を段階的に分けて試しましたがうまくいきませんでした。

**Comment by w-okada** [comment]
例えば、ファイルをインプットするとどうなりますか。
下記のやつとか。
https://drive.google.com/open?id=1iCErRzCt5-6ftALcic9w5zXWrzVXryIA

**Comment by ChineeseMafia** [comment]
こんな感じですね。音声入力の方と同じ状況です。

https://drive.google.com/file/d/1aJlZwnJZxTF8-YH5Kz9TT3hcjlSM5YB1/view

**Comment by w-okada** [comment]
アクセス権をください

**Comment by ChineeseMafia** [comment]
更新しました、よろしくお願いします。

**Comment by w-okada** [comment]
ありがとうございます。これは、変ですね。。。開発時にバグで出てしまうような声ですね。

こちらで、処理プロセスのどの部分まで動いていそうか確認いただけますか。
https://github.com/w-okada/voice-changer/blob/master/tutorials/trouble_shoot_communication_ja.md

**Comment by ChineeseMafia** [comment]
(1)の段階でこのような音声になっていますね。
地声とは遥かに低い声になっています。また速度も遅くなっています。
ページ最下部にある姉妹品サイトでは問題なく録音されていました。

https://drive.google.com/file/d/1f-fbe-uyJI4jy3My6T6Qngt5qSlZvxj8/view?usp=sharing

**Comment by w-okada** [comment]
ありがとうございます。
サンプリングレートがおかしくなっているようですね。
ちょっと試しに強制的にサンプルレートを変更する処理を入れてみました。
お手数ですが、下記のバージョンをダウンロードして試していただけますでしょうか。

v.1.5.3.8a

**Comment by w-okada** [comment]
おー、ご協力ありがとうございます。
いままでは問題おこってない部分だったのですが、ライブラリのバージョンをどこかで上げてしまったのかもしれません。

とりあえず、closeします。
