### ISSUE TITLE
gpu not showing up

### ISSUE THREAD

**Issue by ovahpawer** [w-okada/voice-changer#393]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.7.zip

### OS

windows 11

### GPU

rtx5700xt

### Clear setting

yes

### Sample model

yes

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### Voice Changer type

RVC

### Model type

defaults

### Situation

![Screenshot 2023-07-03 195609](https://github.com/w-okada/voice-changer/assets/95159136/5170779b-cbb0-46b5-a884-b4e34374cb7d)
my gpu is not showing up

**Comment by w-okada** [comment]
use DirectML version.
