### ISSUE TITLE
Too many ms bug

### ISSUE THREAD

**Issue by Shararashik** [w-okada/voice-changer#395]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.7

### OS

Windows 10

### GPU

Nvidia 1660 TI

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

My card: Nvidia 1660 TI. I have tried directml and gpu version. The first time everything worked for me, but after restarting a problem appeared: i have too much ms in "res" section. 
![изображение](https://github.com/w-okada/voice-changer/assets/31408053/7565dca2-1111-4f31-8ba1-bfeb711cece7)
ms just skyrockets when i click start button. I tried to clear settings, reinstalling and both versions, but problem still there. Also the server type of audio device doesn't work at all anymore.

**Comment by Hikimiko01** [comment]
As this have been discussed before on https://github.com/w-okada/voice-changer/issues/364
Try to increase your chunk, for example 1024 or any other.

**Comment by w-okada** [comment]
no update close
