### ISSUE TITLE
Is iMac on intel supported? - MMVCServerSIO.app/Contents/MacOS/MMVCServerSIO: Bad CPU type in executable

### ISSUE THREAD

**Issue by ZeroDelusions** [w-okada/voice-changer#396]
### Issue Type

Question

### vc client version number

MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.7.zip

### OS

Ventura 13.0.1

### GPU

Radeon Pro 580 8GB

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Voice Changer type

.

### Model type

.

### Situation

Running startHttp.command on iMac 2017 Core i5 results in error: MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.7/startHttp.command: line 21: MMVCServerSIO.app/Contents/MacOS/MMVCServerSIO: Bad CPU type in executable
Read trough tutorial, documentation a couple of times, and couldn't find if mac on intel is supported, only about M1

**Comment by w-okada** [comment]
not supported
