### ISSUE TITLE
When deploying on colanb, a message is displayed indicating that the model is missing

### ISSUE THREAD

**Issue by beilove** [w-okada/voice-changer#397]
### Issue Type

Question

### vc client version number

voice-changer master

### OS

Colab

### GPU

NONE

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

Frequent errors occur. Please check if the model of the framework being targeted is loaded.

**Comment by w-okada** [comment]
check if the model of the framework being targeted is loaded.
