### ISSUE TITLE
Can never sound so normal

### ISSUE THREAD

**Issue by UseUrSk1lz** [w-okada/voice-changer#400]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.5a

### OS

Windows 10 

### GPU

RTX 3060, RX 580

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Voice Changer type

RVC

### Model type

Pytorch

### Situation

Working, however can never sound normal, either like a robot or a man lol.
I install pytorch and try with precompile repo and always sounding weird, maybe my british accent?

maybe am stupid hahahaha

**Comment by w-okada** [comment]
Show me your setting. capture window and share.

**Comment by UseUrSk1lz** [comment]
![image](https://github.com/w-okada/voice-changer/assets/132624275/2e8b9ec8-a96b-4125-9dd5-2160d9e1b370)

Bro, please don't worry to help as I was only testing for fun.

**Comment by w-okada** [comment]
This might be the same. Try it out with the latest version.
v.1.5.3.8a

https://github.com/w-okada/voice-changer/issues/391

**Comment by w-okada** [comment]
no res close
