### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by just-iida** [w-okada/voice-changer#401]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.8

### OS

Windows 10

### GPU

AMD Radeon RX 6800 XT

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Voice Changer type

N/A

### Model type

N/A

### Situation

```
C:\Users\iida\Desktop\MMVCServerSIO>MMVCServerSIO.exe    -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/checkpoint_best_legacy_500.onnx     --content_vec_500_onnx_on false     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    Voice Changerを起動しています。
++[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

Preparing your application. Please wait...
(node:13184) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
Preparing your application. Please wait...
(node:13184) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:13184) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:13184) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:13184) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:13184) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:13184) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:13184) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:13184) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:13184) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:13184) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:13184) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:13184) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:13184) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:13184) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:13184) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:13184) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Traceback (most recent call last):
  File "MMVCServerSIO.py", line 229, in <module>
  File "subprocess.py", line 1209, in wait
  File "subprocess.py", line 1506, in _wait
KeyboardInterrupt
[660] Failed to execute script 'MMVCServerSIO' due to unhandled exception!
Terminate batch job (Y/N)? N/A
```

GUI opens, nothing shows up. Fails to load URL

Have tried:

- Restarting
- Other versions(1.5.3.5a, 1.5.3.6a, 1.5.3.7)
- Adding exception to firewall
- Disabling firewall
- Reinstalling

**Comment by w-okada** [comment]
have you read tutorial?

**Comment by just-iida** [comment]
I have read the tutorial, it does not mention the issue.

**Comment by w-okada** [comment]
how log are you waiting?

**Comment by just-iida** [comment]
If I don't interrupt it with CTRL+C, the error continues until the program stops responding and quits itself.

**Comment by w-okada** [comment]
(*3) If unpacking or starting is slow, there is a possibility that virus checking is running on your antivirus software. Please try running it with the file or folder excluded from the target. (At your own risk)

**Comment by just-iida** [comment]
Issue remains even with the folder excluded from Windows Defender.

**Comment by betterftr** [comment]
same for me, it was fine before yesterday

**Comment by w-okada** [comment]
It's possible that the port numbers are overlapping. Why don't you try opening up the batch file and changing the port numbers to see if that helps?

**Comment by just-iida** [comment]
Changing the port number did not fix the issue.

**Comment by w-okada** [comment]
if you access http://localhost:18888/ with browser, what happen?

**Comment by just-iida** [comment]
![image](https://github.com/w-okada/voice-changer/assets/110291512/03c97c62-c315-4165-9148-d825d8b05d5b)

**Comment by ukushu** [comment]
Same problem on macos.
Same result from browser.

**Comment by sekillra** [comment]
MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.8a 遇到了同样的问题，
但是我找到了解决问题的方法：在biso关闭CPU虚拟化
![1647418805163914](https://github.com/w-okada/voice-changer/assets/17966327/c1939cc7-da65-499e-8e68-427ee3c1e75c)

**Comment by betterftr** [comment]
Re-download the application, extract it somewhere new, start it, window will pop up again that you allow or don't allow the connection, click yes, and its working again, then just copy your model_dir again.

**Comment by hodlerx** [comment]
i have the same problem and the windows with allow or dont allow dont even pop up, tried to reinstall all versions, always in excluded from antivirus. also loads very long till the error appears. any resoultions?

**Comment by hodlerx** [comment]
i had to deinstall avira antivirus. excluding the files and stopping the antivirus wasnt enough. If someone still have the same problem this may works

**Comment by betterftr** [comment]
I think I've found the cause for this issue, I deleted some models from the model_dir, cuz I trained an updated version of the voice, restarted the app then it started giving this error. After restoring the folder from the recycle bin, the app started without the connection refused error again.

**Comment by w-okada** [comment]
No, manually editing model_dir is not supported. Doing so could cause the program to run incorrectly.

**Comment by gooose09009** [comment]
> 
May I ask how can I delete a model. I didn't find a way to delete a model except deleting it in model_dir

**Comment by w-okada** [comment]
Officially there is no way to delete, but you can overwrite.

Unofficially you can delete model_dir and stored_setting.json. However, please note that this action is not supported officially, and it will result in the deletion of all models within model_dir. Please proceed at your own risk.

**Comment by w-okada** [comment]
no res close
