### ISSUE TITLE
再次进去就进不去了

### ISSUE THREAD

**Issue by yuanqiyinpin** [w-okada/voice-changer#403]
### Issue Type

Bug Report, Question

### vc client version number

1.5.3.8a

### OS

win

### GPU

4070

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Voice Changer type

rvc

### Model type

onnx

### Situation

![3B4F6763-944C-452D-BADE-6CF54EA42446](https://github.com/w-okada/voice-changer/assets/107650954/ddcc493b-e962-42bc-9ebe-feb6d007239b)
无法进去

**Comment by w-okada** [comment]
hiw to reproduce?

**Comment by yuanqiyinpin** [comment]
> 如何繁殖？

不清楚原因。首次进入是可以进去的。并且1.5.3.7到这个版本都是进不去。第二次进去已经无法进去。两台电脑都是如此！

**Comment by du5** [comment]
same ....

**Comment by LeleGaming** [comment]
[2764:0705/183600.528:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is

what this line meaning?

**Comment by w-okada** [comment]
@LeleGaming 
Read tutorial

**Comment by w-okada** [comment]
@yuanqiyinpin 
The only part od error displayed in the captured image you posted.
Show me full logs.

**Comment by EnterFor** [comment]
same...

**Comment by yuanqiyinpin** [comment]
> 

怎么解决的

**Comment by w-okada** [comment]
no update close
