### ISSUE TITLE
Unknown message (cannot read properties of null(reading 'enableServer'))

### ISSUE THREAD

**Issue by Achi1ru** [w-okada/voice-changer#406]
### Issue Type

Bug Report, Question, Others

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.7

### OS

Windows 10

### GPU

GTX 1650

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

![Screenshot 2023-07-05 212448](https://github.com/w-okada/voice-changer/assets/138686531/5e21fab6-3fee-4a46-b181-79800ffad63a)
![Screenshot 2023-07-05 212807](https://github.com/w-okada/voice-changer/assets/138686531/8434ea9b-8591-4de3-bda3-b7383ab5c65d)
I cant seems to select any default models, it shows error as above.
Haven't tried any downloaded models.

**Comment by w-okada** [comment]
same
https://github.com/w-okada/voice-changer/issues/379
