### ISSUE TITLE
change model error

### ISSUE THREAD

**Issue by LeleGaming** [w-okada/voice-changer#407]
### Issue Type

Bug Report, Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.8a

### OS

Windows 11

### GPU

RTX 2060 6GB OC

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

yes

### read tutorial

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

at first client runs normally despite the "ERR_CONNECTION_REFUSED" error and the voice changer can be used normally.

![Screenshot 2023-07-05 203116](https://github.com/w-okada/voice-changer/assets/97451047/ea8e53e6-c280-4bef-a879-49e6b61a2e08)

then when I want to change the model, the cmd comes out like this picture, what should I do to fix it?

![Screenshot 2023-07-05 203348](https://github.com/w-okada/voice-changer/assets/97451047/2989ed5f-ba75-45cf-be23-4a48ea35b6d6)

I've used all the methods including the tutorial and still have the error. please give me a hint to fix this.

**Comment by w-okada** [comment]
try the latest version v.1.5.3.9. I close this issue, if you have still problem, open new issue.
