### ISSUE TITLE
Performance issue on AMD card

### ISSUE THREAD

**Issue by Absholem** [w-okada/voice-changer#408]
### Issue Type

Others

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.8a.zip

### OS

Windows 10 Pro version 22H2, build 19045.2311

### GPU

AMD RX 6600 XT

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

> [1632:0705/204137.824:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is

The GPU is not recognized and does not show in the GUI and the error above appeared when GPU(dml) is on.
When the RVC is running, there is no utilization on the GPU, and RVC fallback to running on CPU, Res time ranging from 1000ms (chunk 384) to 5000ms (chunk 1024).

F0 detector: dio makes the voice choppy, harvest works fine, crepe makes the voice choppy.

**Comment by w-okada** [comment]
read tutorial
