### ISSUE TITLE
DirectML use device_id to select GPU

### ISSUE THREAD

**Issue by hpx502766238** [w-okada/voice-changer#410]
### Issue Type

Feature Request

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.8a.zip

### OS

Windows11

### GPU

Radeon Vega8，RTX3060 6G

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Voice Changer type

RVC

### Model type

ONNX f0

### Situation

print(onnxruntime.get_available_providers())
model_path = "model.onnx"
session = onnxruntime.InferenceSession("model.onnx",providers=['DmlExecutionProvider'])
session.set_providers(['DmlExecutionProvider'], [ {'device_id': 0}])

we can change "device_id" to choose a GPU
can you add a feature to switch GPUs?

**Comment by w-okada** [comment]
Did you confirm that it works when I tried it with DmlExecutionProvider?
I know it can be done with Nvidia, and it has been implemented.

**Comment by w-okada** [comment]
How do I know which ID corresponds to which GPU?

**Comment by hpx502766238** [comment]
> How do I know which ID corresponds to which GPU?

windows taskmanager,GPU0 device_id 0,GPU1 device_id 1

**Comment by w-okada** [comment]
I apologize. I was not clear enough.

How do I know which ID corresponds to which GPU "in python script"?

**Comment by hpx502766238** [comment]
**I only find a C++ method at present.**
Creates a DirectML Execution Provider which executes on the hardware adapter with the given , also known as the adapter index. The device ID corresponds to the enumeration order of hardware adapters as given by [IDXGIFactory::EnumAdapters](https://docs.microsoft.com/windows/win32/api/dxgi/nf-dxgi-idxgifactory-enumadapters). A of 0 always corresponds to the default adapter, which is typically the primary display GPU installed on the system. Beware that in systems with multiple GPU’s, the primary display (GPU 0) is often not the most performant one, particularly on laptops with dual adapters where battery lifetime is preferred over performance.
**IDXGIFactory：：EnumAdapter**
https://learn.microsoft.com/zh-cn/windows/win32/api/dxgi/nf-dxgi-idxgifactory-enumadapters

**Comment by hpx502766238** [comment]
> I apologize. I was not clear enough.
> 
> How do I know which ID corresponds to which GPU "in python script"?



> I apologize. I was not clear enough.
> 
> How do I know which ID corresponds to which GPU "in python script"?

**I only find a C++ method at present.**
https://onnxruntime.ai/docs/execution-providers/DirectML-ExecutionProvider.html
Creates a DirectML Execution Provider which executes on the hardware adapter with the given , also known as the adapter index. The device ID corresponds to the enumeration order of hardware adapters as given by [IDXGIFactory::EnumAdapters](https://docs.microsoft.com/windows/win32/api/dxgi/nf-dxgi-idxgifactory-enumadapters). A of 0 always corresponds to the default adapter, which is typically the primary display GPU installed on the system. Beware that in systems with multiple GPU’s, the primary display (GPU 0) is often not the most performant one, particularly on laptops with dual adapters where battery lifetime is preferred over performance.
**IDXGIFactory：：EnumAdapter**
https://learn.microsoft.com/zh-cn/windows/win32/api/dxgi/nf-dxgi-idxgifactory-enumadapters

**Comment by hpx502766238** [comment]
I have submitted a feature request to the official ONNX Runtime.
https://github.com/microsoft/onnxruntime/issues/16644

**Comment by hpx502766238** [comment]
> I apologize. I was not clear enough.
> 
> How do I know which ID corresponds to which GPU "in python script"?

ok,**I have find a python solution now.We can use pytorch-directml**.I have tested that its(pytorch dml) running  result is the same as the official C++. Here is the python test script: 
import torch_directml

if torch_directml.is_available(): #显示是否有dml设备
    print('default device_id:',torch_directml.default_device())  # 显示缺省ＤＭＬ设备ｉｄ
    for i in range(torch_directml.device_count()):
        print(f'device_id:{i},device_name:{torch_directml.device_name(i)}')  # 显示第i个ＤＭＬ设备名称

else:
    print('directml is not available')

**Comment by w-okada** [comment]
Thank you for your cooperation and for providing information.

I think you'll probably need to set up a development environment on Windows to do that. I need to think a bit because I can't risk breaking my current development environment. By the way, as stated in the readme, I don't even have an AMD GPU, so I can't test it. In order to proceed, it's quite risky.

Well, for now, I can't get started on it right away, so please wait a bit.

**Comment by hpx502766238** [comment]
There is also a particularly important point: To use torch-directml，we must install **torch=2.0.0** torchvision**(cpuVersion)**，otherwise the pip may autoinstall other packages which depend on Nvidia.So I suggest to split the software into two version by 'directml and cuda',both of them support onnx and pth.

**Comment by w-okada** [comment]
select id will be in next release (not device name)

**Comment by vitpekarek** [comment]
I tested many different settings. You closed #485 , so I just wanted to update you that I have issue only with crepe. It's increasing res ms even if I set highest chunk. Crepe tiny and full is working for me perfectly. I only had to set a chunk to 128 and it seems good.

**Comment by w-okada** [comment]
use latest version v.1.5.3.10

**Comment by flipknight001** [comment]
Tested with RX 5700 AMD GPU, I was having issues unless settings is "Crepe tiny", other seem to cause high res ms.

**Comment by w-okada** [comment]
amd is used with onnx. crepe is not onnx. crepe tiny is onnx. so, It's operating as expected.

**Comment by zerrmarch248** [comment]
@vitpekarek ****

**Comment by binplatin** [comment]
Hello, im sorry but i didnt really understand something up there. So my Problem is i got a Rx 7800x GPU and i cant select her. Pls help

**Comment by Kuuko-fokkusugaru** [comment]
> Hello, im sorry but i didnt really understand something up there. So my Problem is i got a Rx 7800x GPU and i cant select her. Could you please say what i exactly have to type and where.

You haven't to type anything anywhere. Just click on the buttons that may say GPU0, GPU1, etc. One of them should be your 7800x

**Comment by binplatin** [comment]
> > Hello, im sorry but i didnt really understand something up there. So my Problem is i got a Rx 7800x GPU and i cant select her. Could you please say what i exactly have to type and where.
> 
> You haven't to type anything anywhere. Just click on the buttons that may say GPU0, GPU1, etc. One of them should be your 7800x

It doesnt matter which one i choose my cpu is always on 90%, so it is normal?

**Comment by Kuuko-fokkusugaru** [comment]
> > > Hello, im sorry but i didnt really understand something up there. So my Problem is i got a Rx 7800x GPU and i cant select her. Could you please say what i exactly have to type and where.
> > 
> > 
> > You haven't to type anything anywhere. Just click on the buttons that may say GPU0, GPU1, etc. One of them should be your 7800x
> 
> It doesnt matter which one i choose my cpu is always on 90%, so it is normal?

No, it should use the GPU. Make sure that you check the GPU usage regardless of the cpu usage. It should raise whenever you speak. You could also try the v2 of the software instead of the v1.

**Comment by binplatin** [comment]
> > > > Hello, im sorry but i didnt really understand something up there. So my Problem is i got a Rx 7800x GPU and i cant select her. Could you please say what i exactly have to type and where.
> > > 
> > > 
> > > You haven't to type anything anywhere. Just click on the buttons that may say GPU0, GPU1, etc. One of them should be your 7800x
> > 
> > 
> > It doesnt matter which one i choose my cpu is always on 90%, so it is normal?
> 
> No, it should use the GPU. Make sure that you check the GPU usage regardless of the cpu usage. It should raise whenever you speak. You could also try the v2 of the software instead of the v1.

how can i download the other software?

**Comment by Kuuko-fokkusugaru** [comment]
https://huggingface.co/wok000/vcclient000/tree/main
