### ISSUE TITLE
F0 Det type always reseting

### ISSUE THREAD

**Issue by Wakamu** [w-okada/voice-changer#411]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.8a.zip

### OS

Windows 10

### GPU

RTX 3080

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

Everytime i select another voice, the F0 Det goes back to harvest instead of staying to whatever i selected.
![image](https://github.com/w-okada/voice-changer/assets/67844443/56e76054-4461-4a7d-a186-0ba0684dd110)

**Comment by w-okada** [comment]
not bug, intended. If you want store the setting, It's a feature request.

**Comment by Wakamu** [comment]
It was staying in the previous versions, so we have to make a feature request to add back something that was removed i guess ...

**Comment by w-okada** [comment]
use the latest version(v.1.5.3.9a)

**Comment by w-okada** [comment]
no res close
