### ISSUE TITLE
Stuttery sounds while talking

### ISSUE THREAD

**Issue by xJuniper** [w-okada/voice-changer#412]
### Issue Type

Question, Others

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.8a

### OS

Windows

### GPU

RX 5700 XT

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

yes

### read tutorial

yes

### Voice Changer type

RVC

### Model type

f0

### Situation

It always sounds really stuttery. Increasing the chunk doesn't help much and setting it to dio makes it worse. I tried changing the settings multiple times but that didn't fix the problem

**Comment by w-okada** [comment]
read readme.md

**Comment by xJuniper** [comment]
Couldn't find an answer there sorry

**Comment by w-okada** [comment]
Why don't you use directML version?
