### ISSUE TITLE
Cannot read properties of null (reading 'enableServerAudio')

### ISSUE THREAD

**Issue by Robtboy** [w-okada/voice-changer#413]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.8.zip

### OS

Window 10

### GPU

Nvidia Geforce GT 1030

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

no

### Voice Changer type

RVC

### Model type

ONNX

### Situation

I just wanted to try the voicechanger and i have that just a little moment after i launch the voicechanger

![image_2023-07-05_203818488](https://github.com/w-okada/voice-changer/assets/99406394/54c0a2aa-bfa3-426a-a2dd-0c34901d5bc4)

Pls help me

**Comment by w-okada** [comment]
show me log in terminal

**Comment by MurdaCult** [comment]
> show me log in terminal

Same issue with me, 

![image](https://github.com/w-okada/voice-changer/assets/138741666/4cb29775-7010-4d1d-8190-dcfc979e27ad)


When I go to select a voice, It comes up with what the post is showing, when I try changing thresh it does this 

![image](https://github.com/w-okada/voice-changer/assets/138741666/9e6e0b14-ab27-455c-b702-bfae85ef0b08)


And it doesn't move the nob. 
Any help?

**Comment by w-okada** [comment]
There should be another error higher up; please search the traceback for it.

**Comment by MurdaCult** [comment]
> There should be another error higher up; please search the traceback for it.

Hold on let me find it.

**Comment by MurdaCult** [comment]
![image](https://github.com/w-okada/voice-changer/assets/138741666/dd6250f8-701a-44ff-b3df-f94f571175f7)
Wont open UI now, I've tried so many versions, and i've reinstalled it atleast 10 times now. Do u have a permanent fix. 

> There should be another error higher up; please search the traceback for it.

**Comment by w-okada** [comment]
same

https://github.com/w-okada/voice-changer/issues/382

**Comment by V01rvar** [comment]
I'm sorry, how do I solve the problem?
