### ISSUE TITLE
GPU not being used by voice changer

### ISSUE THREAD

**Issue by Callicraft** [w-okada/voice-changer#414]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.8a.zip

### OS

Windows

### GPU

RX 6600  XT

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Voice Changer type

RVC

### Model type

pyTorch,ONNX

### Situation

The Voice changer is only using my GPU instead it is using my CPU
![Screenshot 2023-07-05 211116](https://github.com/w-okada/voice-changer/assets/77324169/a894a8d6-31f4-424f-bd47-429ead3fbd59)

**Comment by w-okada** [comment]
same

https://github.com/w-okada/voice-changer/issues/383
