### ISSUE TITLE
 electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by Virusneko** [w-okada/voice-changer#415]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.8a.zip

### OS

Windows 10

### GPU

Intel(R) HD Graphics 530

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### read tutorial

yes

### Voice Changer type

RVC

### Model type

crepe

### Situation

Started using it some time ago, leaved it for some time and then I tried opening it and had the error TypeError
Cannot read properties of null (reading 'enableServerAudio'), I looked it up and I trtied unabling my windows defender, but then when opening I have  electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED, yes I already excluded it from my antivirus and even turned it off, I already waited 30 minutes and I still can't open it

**Comment by w-okada** [comment]
show me full log in your terminal.

` ERR_CONNECTION_REFUSED,` is only side effect of the root problem.

**Comment by Virusneko** [comment]
> 

Nvm, reinstalled v.1.5.3.8 without a and it works, Idk why it happened though, im 100% sure it was for windows, but the regular version works fine with me

**Comment by Virusneko** [comment]
Hi, try installing another version, it worked for me
