### ISSUE TITLE
Cannot read properties of null (reading 'enableServerAudio')

### ISSUE THREAD

**Issue by 1Ghir** [w-okada/voice-changer#417]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.8a

### OS

Windows 10

### GPU

none

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

I tried pressing on one of the images but it popped up with this error
![image](https://github.com/w-okada/voice-changer/assets/119836421/9f4a8bd8-3bdd-4b4c-b6a0-f6428f4242c8)

![image](https://github.com/w-okada/voice-changer/assets/119836421/69f6b9d1-1615-476e-a9eb-27d526302516)

**Comment by w-okada** [comment]
same
https://github.com/w-okada/voice-changer/issues/379
