### ISSUE TITLE
DirectML version doesn't recognize AMD GPU

### ISSUE THREAD

**Issue by Pixeljunk69** [w-okada/voice-changer#418]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.8

### OS

Windows 10

### GPU

Rx 7900 XTX

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

![image](https://github.com/w-okada/voice-changer/assets/129416418/c5499592-f10f-4864-a2de-a7b0452c1f01)
Program doesn't seem to recognize my GPU at all, I may just be stupid but even when trying to use v 1.5.3.5 where you could still select the GPU in a drop down menu, it doesn't show up. I am really not experienced with anything in this field and what I "found" may just be my stupidity overcoming my senses. I am sorry if I am just a nuisance.

**Comment by alfonso8878** [comment]
Same issue with a Rx 6700 XT 
I used the  directML-cuda_v.1.5.3.7 to v.1.5.3.8a  and still happening.

**Comment by sasuniki** [comment]
> Same issue with a Rx 6700 XT I used the directML-cuda_v.1.5.3.7 to v.1.5.3.8a and still happening.

> ### Issue Type
> Bug Report
> 
> ### vc client version number
> MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.8
> 
> ### OS
> Windows 10
> 
> ### GPU
> Rx 7900 XTX
> 
> ### Clear setting
> yes
> 
> ### Sample model
> no
> 
> ### Input chunk num
> yes
> 
> ### Wait for a while
> The GUI successfully launched.
> 
> ### read tutorial
> yes
> 
> ### Voice Changer type
> RVC
> 
> ### Model type
> ONNX
> 
> ### Situation
> ![image](https://user-images.githubusercontent.com/129416418/251331164-c5499592-f10f-4864-a2de-a7b0452c1f01.png) Program doesn't seem to recognize my GPU at all, I may just be stupid but even when trying to use v 1.5.3.5 where you could still select the GPU in a drop down menu, it doesn't show up. I am really not experienced with anything in this field and what I "found" may just be my stupidity overcoming my senses. I am sorry if I am just a nuisance.

try 1.5.3.6a version

**Comment by freddyguythe10th** [comment]
where can the 1.5.3.5a version be downloaded?

**Comment by Pixeljunk69** [comment]
> where can the 1.5.3.6a version be downloaded?
> 

You can see the update history on huggingface and download it there

**Comment by Katze719** [comment]
same issue here with a 7900XT

**Comment by Katze719** [comment]
same issue here using an 7900XT

**Comment by Katze719** [comment]
did using 1.5.3.6a work for you guys ? i had some python errors with that version

**Comment by aki-0929** [comment]
> did using 1.5.3.6a work for you guys ? i had some python errors with that version

1.5.3.6a not work, can't detect gpu.

**Comment by w-okada** [comment]
AMD GPU can not be countable in this process. So zero here is not wrong. (there is no way to count them as long as I know)

![image](https://github.com/w-okada/voice-changer/assets/48346627/23850769-a53b-4eaa-b291-271129b6b2a6)

If you want to know the gpu is used by this application, you should monitor performance monitor of windows.

**Comment by Katze719** [comment]
i cant see any load on the gpu, its all on the cpu

**Comment by w-okada** [comment]
same
https://github.com/w-okada/voice-changer/issues/383
