### ISSUE TITLE
Cannot read properties of null (reading 'enableServerAudio')

### ISSUE THREAD

**Issue by ravencodm** [w-okada/voice-changer#419]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.8a

### OS

Windows 10

### GPU

GTX 1650 GDDR6 Laptop

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Voice Changer type

RVC

### Model type

idk, i just have python installed on my pc

### Situation

i5-10300h
gtx 1650
16gb ram
windows 10 
![image](https://github.com/w-okada/voice-changer/assets/99584450/52575dd9-b8be-4980-926c-e2f50ddd5be0)
![image](https://github.com/w-okada/voice-changer/assets/99584450/46715117-d5ca-482d-afbc-0c3b688b9445)
![image](https://github.com/w-okada/voice-changer/assets/99584450/479fa707-0820-4dbf-b0a6-5eaa4294b774)
![image](https://github.com/w-okada/voice-changer/assets/99584450/f826bfd4-7e85-42b3-85c7-6ebc94b89de1)

**Comment by KenDoStudios** [comment]
have you restarted your computer?

**Comment by ravencodm** [comment]
> 

yes, but the problem is with the a version, downloaded 1.5.3.8 without a and worked

**Comment by w-okada** [comment]
Okey so I closed this issue
