### ISSUE TITLE
Internet connection went unstable after installation

### ISSUE THREAD

**Issue by PanterMan11** [w-okada/voice-changer#420]
### Issue Type

Others

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.7

### OS

Windows 11

### GPU

Nvidia Geforce RTX 3060

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

After I installed the voice changer and ran it a few times, several issues regarding my internet connection have arised. I would get disconnected randomly even though other devices would be connected just fine. 
The issue dissappeared after I removed the application from the Firewall Exceptions List.
Because the issue was fixed immediately after I took the Firewall permission and that it started the day I ran the application, it is likely the voice changer was the cause of this problem.

**Comment by w-okada** [comment]
I've never heard of this phenomenon. Are there others who have experienced the same situation?

**Comment by w-okada** [comment]
no update close
