### ISSUE TITLE
[6928:0707/142614.523:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -200

### ISSUE THREAD

**Issue by AkihikoIzuru** [w-okada/voice-changer#425]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.8-001_2.zip

### OS

windows 10

### GPU

none

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Voice Changer type

N/A

### Model type

N/A

### Situation

[6928:0707/142614.523:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -200

Have tried:

Restarting
Other versions

**Comment by w-okada** [comment]
Error message said "handshake failed". Maybe your network is something wrong. Did you firewall off?
And http (not https) work well?

**Comment by w-okada** [comment]
no res close

**Comment by blastkerbal** [comment]
i have same problem how do i fix
