### ISSUE TITLE
Onnx and Pth Issue

### ISSUE THREAD

**Issue by benc1221** [w-okada/voice-changer#428]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9

### OS

Windows 11

### GPU

RTX 4080

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

First, eveerytime i use any onnx file with any of the crepe settings, its sounds robotic and sounds like its whispering. In the previous version where i use my index files with .pth, it never made my models sound watery and muffled, but pth works with all crepe options, so the major issue with this version is onnx  is not working with any of the crepe options, the index files when you set it above 0.5 it makes the voice sound watery and muffled in both pth and onnx.

**Comment by NataIynn** [comment]
I have this too, index just sounds terrible, and all the new crepe options sounds really bad.

**Comment by w-okada** [comment]
Are all of the crepe incorrect? "crepe", "crepe_tiny", "crepe_full". 

I didn't modify "crepe" from the previous version, so there might be a problem with the other logic.

**Comment by benc1221** [comment]
none of the crepe options work with the onnx file

**Comment by w-okada** [comment]
tell me your onnx file's properties.
sample rate, f0, v1 or v2

**Comment by benc1221** [comment]
48k crepe v2

**Comment by w-okada** [comment]
Does the same issue occur with the sample model?

**Comment by benc1221** [comment]
yes

**Comment by w-okada** [comment]
Really??? 
According to reports from other people, they said that there were no issues with the sample model, but could this depend on the environment as well??

**Comment by benc1221** [comment]
the sample models only work for harvest and dio mode for me

**Comment by w-okada** [comment]
if you can share the output of sample model with this song. This is a famous Japanese children's song.

https://drive.google.com/file/d/1aJlZwnJZxTF8-YH5Kz9TT3hcjlSM5YB1/view

**Comment by benc1221** [comment]
which f0 detector i need to use?

**Comment by w-okada** [comment]
crepe

**Comment by benc1221** [comment]
https://drive.google.com/file/d/1WmGTOi74vVdJk4SSMNHoFtycqcZUE9lW/view?usp=sharing
![Screenshot 2023-07-08 054825](https://github.com/w-okada/voice-changer/assets/89867041/560e19e2-4c41-4e80-9732-a6eb4b4affbe)

**Comment by w-okada** [comment]
Thanks!! That's really strange. Let's investigate.

**Comment by nadare881** [comment]
This may be because crepe cannot be inferred unless the voice is longer than a certain length. Is your voice hoarse in the Tsukuyomi-chan model?

**Comment by benc1221** [comment]
only when i use crepe, crepe tiny, and crepe_full

**Comment by w-okada** [comment]
I released bugfixed version. try v.1.5.3.9a

**Comment by benc1221** [comment]
https://drive.google.com/file/d/1nkCpNua8SiZr7a5vivmLsTAT0Hzb1637/view?usp=drive_link
https://drive.google.com/file/d/1yycJjFV5Bz7eo0DHRY5is1cQaukH8xz9/view?usp=drive_link
the issues im now facing with the index file but all crepe options for both onnx and pth are working good

**Comment by w-okada** [comment]
OKey, 

And at which version you can use index correctly ?

**Comment by benc1221** [comment]
1.5.3.7

**Comment by w-okada** [comment]
no clue...

**Comment by w-okada** [comment]
no clue...
