### ISSUE TITLE
Exceptions.DeviceCannotSupportHalfPrecisionException: 'Device cannot support half precision.'

### ISSUE THREAD

**Issue by pieresimbolon** [w-okada/voice-changer#429]
### Issue Type

Bug Report, Others

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.8a.zip

### OS

Windows 11

### GPU

Mx550 2GB

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

?

### Situation

sooo.. So... my gpu doesn't support half precision. and i always get this error..
![image](https://github.com/w-okada/voice-changer/assets/129783861/7f2f2cc9-de48-40cf-bb65-1f92a826cb7f)
but I found an older version of MMVC, more precisely version 1.5.2.8. in this version I see there is choose float option.
![image](https://github.com/w-okada/voice-changer/assets/129783861/d30055f4-bc19-4478-80ff-e2b480ab1243)
![image](https://github.com/w-okada/voice-changer/assets/129783861/709a659c-b66d-4412-b430-254fbebe8590)

so I wanted to ask... is there still a link for that version... and also why did you remove that option. 
or is there another solution, besides downloading the old version to solve this error?

Thank you >_>

**Comment by w-okada** [comment]
Why => because I implemented auto detect. And if not available, fallback to not use half precision. But I notice, in some update, the implmentation doesn't work. I'll fix next release.

**Comment by w-okada** [comment]
I released fixed version. try v.1.5.3.9a

**Comment by pieresimbolon** [comment]
Wait, already?, Thanks for the work.

**Comment by w-okada** [comment]
no update close.
