### ISSUE TITLE
ONNX runtime supports windows 10 and above only

### ISSUE THREAD

**Issue by yunytuny** [w-okada/voice-changer#430]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9.zip

### OS

Windows 7 64 bit

### GPU

Geforce 8600 GT

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

 MMVC v1.5.3.9

### Model type

I dont know

### Situation

https://imgur.com/UopDbPW

**Comment by w-okada** [comment]
That's an onnxruntime requirement. Please consult with onnxruntime community.
