### ISSUE TITLE
Problem : ERR_CONNECTION_REFUSED 

### ISSUE THREAD

**Issue by ToyHugs** [w-okada/voice-changer#432]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.9.zip

### OS

Windows 10

### GPU

RX 6800 XT (and before GTX 1050)

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

I think you already know that problem, cause I have seen plenty of topic like this, and no one solve that problem :
![image](https://github.com/w-okada/voice-changer/assets/67203974/351fd355-cfbb-405b-a121-02e55a91a5f3)
By the way, I was before with a GTX 1050 and I haven't any problem.
I have tried : 
- 5 differents versions, including DirectML and Cura, and previous version in different folder
- I try to desactivate completly Windows Defender + FireWall (risky yeah)
- Reboot the system a lot
- Recreate a firewall rules based on the previous one (sorry for the french UI)
It's 2 private rules (I try with public too) one on TCP, and the other on UDP
![image](https://github.com/w-okada/voice-changer/assets/67203974/b49be71b-92bf-4890-b15c-992a758450d3)
![image](https://github.com/w-okada/voice-changer/assets/67203974/84450b0d-70b6-4423-ba67-b0cdd4a8f05f)
![image](https://github.com/w-okada/voice-changer/assets/67203974/6646858c-6ce2-4e3d-8d7a-ff130803ba53)
- I tried change the port 18888
- I was thinking the problem was maybe about the VT-x option in motherboard, because Z390 UD don't have that properties (but it was working before with my GTX 1050)
- And http://localhost:18888 don't work on chrome too

So, I'm stuck... After 6 hours on the problem, I can't see a solution, so I ask here !
Else, I can try to use Docker or Anaconda, but I don't know if I can use GPU on ???

Thanks for reading this <3

**Comment by cosmoslego** [comment]
Try reinstall in other location

**Comment by ToyHugs** [comment]
> Try reinstall in other location

I just did it like at least 3 times, on a SSD, on a HDD and on another HDD

**Comment by betterftr** [comment]
For me this error occurred when I deleted some models, after restoring them from recycle bin the error stopped.

**Comment by ToyHugs** [comment]
Yeah I have seen that in other post, I'm glad it work for you
For now, I'm trying the dev mode. I successfully installed all requirements, but there still some problems I need to fix (stat)

**Comment by w-okada** [comment]
Why not wait? If your virus scan running, it takes 1~2min to launch first time.

> Wait for a while
> no

**Comment by ToyHugs** [comment]
> Why not wait? If your virus scan running, it takes 1~2min to launch first time.
> 
> > Wait for a while
> > no

I waited for like 20 minutes :/
But now I'm trying the Anaconda on WSL

**Comment by w-okada** [comment]
> I waited for like 20 minutes :/
Okay, sorry, but you said no. Regardless, don't mind.

![image](https://github.com/w-okada/voice-changer/assets/48346627/1a67db24-b5e5-49fb-9d62-59c9f1a97e51)

**Comment by ToyHugs** [comment]
I will close that issue because I'm switching to WSL, but I still have issue on it
