### ISSUE TITLE
AMD dont work on the custom voice

### ISSUE THREAD

**Issue by ProFFs** [w-okada/voice-changer#435]
### Issue Type

Question

### vc client version number

v.1.5.3.9

### OS

Windows 10

### GPU

RX 6600

### Clear setting

no

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX maybe, idk

### Situation

In the custom voice my GPU dont work, i tryid many voices but not one dont use gpu. 
Preloaded voices work fine.
![image](https://github.com/w-okada/voice-changer/assets/71282562/fd6ce25d-13a1-484b-bd21-f7eb1179332d)

**Comment by ProFFs** [comment]
Model type PyTourchV2,
I found

**Comment by ProFFs** [comment]
How i can use onnx instead off PyTourch? I custom voice.

**Comment by w-okada** [comment]
Amd gpu used when onnx.
Use onnx model

**Comment by ProFFs** [comment]
Where me found onnx model?

**Comment by GrizlyyXd** [comment]
same problem

**Comment by Katze719** [comment]
dont forget that the task manager can not show you the usage of OpenCL on your AMD GPU, for monitoring I would recommend [GPU-Z](https://www.techpowerup.com/gpuz/) and check the clock speeds, if it ramps up your good
@ProFFs

**Comment by w-okada** [comment]
> Where me found onnx model?


The sample models that are downloaded upon the first launch are in ONNX format.

**Comment by ProFFs** [comment]
> 

I know, me need info, where i can found CUSTOM model in format onnx

**Comment by ProFFs** [comment]
> dont forget that the task manager can not show you the usage of OpenCL on your AMD GPU, for monitoring I would recommend [GPU-Z](https://www.techpowerup.com/gpuz/) and check the clock speeds, if it ramps up your good @ProFFs

Bro, my gpu dont work, i saw anywhere, clock is low, no noise heard. And peformance custom voices much worse than the performance of sample.

**Comment by pieresimbolon** [comment]
> > 
> 
> I know, me need info, where i can found CUSTOM model in format onnx

Hey there, 
I'm an amd user too, hopefully this reply can help 

-First you downloaded the wrong version, you need the directML version.

export to onnx
-First you need to select your model first. 
-Then just click the export to onnx button.
-Wait for a while, the export speed depends on your gpu.
-when finished, select the placement where the onnx file is saved
-finally add the voice model as usual, but use the onnx file instead of the pth one

**Comment by ProFFs** [comment]
> > > 
> > 
> > 
> > I know, me need info, where i can found CUSTOM model in format onnx
> 
> Hey there, I'm an amd user too, hopefully this reply can help
> 
> -First you downloaded the wrong version, you need the directML version.
> 
> export to onnx -First you need to select your model first. -Then just click the export to onnx button. -Wait for a while, the export speed depends on your gpu. -when finished, select the placement where the onnx file is saved -finally add the voice model as usual, but use the onnx file instead of the pth one

Bro, THX VERY MUCH, i so blind

**Comment by w-okada** [comment]
no update close
