### ISSUE TITLE
Messed up my computer. Cant hear any sound/output from my WHOLE windows, even when I restarted my pc and uninstalled the program.

### ISSUE THREAD

**Issue by V4ada** [w-okada/voice-changer#436]
### Issue Type

Bug Report, Question, Others

### vc client version number

MMVCServerSIO_win_onnxpu-cuda_v.1.5.3.5.zip

### OS

Windows 10

### GPU

Geforce GTX 1060 6ggb

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

idk

### Situation

I have ran the program for the first time, follownig the tutorial. It started and my audio cut off from my whole computer. My microphone worked fine, and I could hear my microphone through the headphones if I tried to. I could do the 'sound test' windows has in control panel, and it worked. When I restarted my computer and removed the folder, up to no avail. Now, the sound test wont run, giving me an error. When I go on Volume Mixer for my headphones, it shows NOTHING, even when apps that show audio are active (spotify,discord,youtube,etc).
Please, just help me fix my audio. I have to reformat my whole computer because of this.
![Screenshot_2](https://github.com/w-okada/voice-changer/assets/139022406/c89c2c8f-52ca-4940-b2f0-ce1a58999583)
![image](https://github.com/w-okada/voice-changer/assets/139022406/ccc33b23-d732-46b2-b81d-6e4dafbecdc4)

**Comment by grimoire-vc** [comment]
Make sure that your system output device is set as your regular speakers or headphones. You can also check in Windows sound settings

![image](https://github.com/w-okada/voice-changer/assets/132099036/462d9e76-433e-4c58-b8f0-d77bd2270559)
![image](https://github.com/w-okada/voice-changer/assets/132099036/f4246b7b-b570-4142-b3db-33198396953e)
![image](https://github.com/w-okada/voice-changer/assets/132099036/0e14a3f7-320e-4825-90a3-8b092bcc857f)

**Comment by w-okada** [comment]
Are you using an older version of the app? I don't think you can download it from this repository, but where did you get it?

**Comment by w-okada** [comment]
no res close
