### ISSUE TITLE
cannot download from Google Drive link

### ISSUE THREAD

**Issue by Avty1929** [w-okada/voice-changer#437]
every time when i click on the link i get the 
"Sorry, you can't view or download this file at this time."

"Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator."

do you perhaps know anything about this problem?

**Comment by w-okada** [comment]
use issue template
