### ISSUE TITLE
Dynamic chunking option to reduce latency and overhead

### ISSUE THREAD

**Issue by kalomaze** [w-okada/voice-changer#438]
### Issue Type

Feature Request

### vc client version number

N/A

### OS

N/A

### GPU

N/A

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

N/A

### Model type

N/A

### Situation

Instead of static chunk sizes, it should automatically splice and segment chunks based on the length of the input audio and slice where there is silence. 
You can then make the 'chunk size' a 'maximum chunk' option, where it can't go longer than that for a single chunk, and it will only apply in the case someone is speaking uninterrupted, at which point it will split the chunk. 
The hop size to detect dynamically doesn't need to be too high, so it shouldn't take too much computing power. The silence threshold for slicing can be a static value. 

Potentially, this could reduce latency/overheard for short pieces, while still allowing for higher chunk sizes.

This is based on my understanding of 'chunk sizes' representing the length of each piece that is sent to the voice changer pipeline for RVC.

A more advanced solution (to prevent mid-sentence artifacting, which is because it 'cuts' mid speech (a big problem right now), is, the more you approach the maximum chunk size, the db threshold for slicing could get lower and lower, to ensure it doesn't cut mid word, and instead at the silent parts.

So a 0.5s sample - can have -40db silence slicing, and then when the sample approaches lets say 1.5s, then it starts using -30db, and then whenever it's reached 90% of the chunk size and almost is gonna hit the limit, it it's a -10db silence threshold to force the chunk to slice by having a more aggressive detection period.

On top of that, if you're speaking a lot, this could artificially compensate for delay by not having a fixed delay, and instead shortening the silent fill periods a natural amount if there's a large 'queue' of chunks to go (much like how Discord calls do this already to optimize for network latency)

**Comment by w-okada** [comment]
Sorry, It's due to my limited English proficiency, but I wasn't able to understand what you're trying to solve.

What is the problem you want to solve?


 Is this a main problem you want to solve, 

> Potentially, this could reduce latency/overheard for short pieces, while still allowing for higher chunk sizes.

It seems like the delay might increase the longer you speak. In addition, even now, if there is no audio input within a chunk, the conversion process is skipped. As a result, periods of silence can help reduce latency. Could there be a different effect?

**Comment by kalomaze** [comment]
The idea is that dividing the input microphone streams into pieces without silence will help minimize artifacts due to the fixed chunk sizes, and a queue would enable you to 'artificially' remove silence and 'catch up' for the delay.

**Comment by kalomaze** [comment]
The delay could increase if there is long uninterrupted speaking. Which is why a 'maximum size' as a fallback could be beneficial.

**Comment by w-okada** [comment]
I believe I was able to understand most of it. What kind of value are you anticipating for the maximum size? Considering the delay when continuous speech is occurring, it looks like we have to keep it fairly small.

On the other hand, there's also a demand to keep the delay as minimal as possible, and this conflict is challenging.

**Comment by kalomaze** [comment]
The maximum size could be configured the same way the size is configured right now, with a fixed value, and if it approaches this value, it will forcibly divide the sample. 

Delay times would still be lower/very similar to existing speeds, if your maximum size is set to a similar size to what you used before.

This gives users the opportunity to maximize either quality or delay times while still reaping the benefits of a dynamic chunking solution.

Additionally, if you queued up multiple chunks concurrently, this could be very GPU/CPU heavy as it would process multiple at once. Instead there could be a mode that only queues up one extra at a time to not overuse GPU memory and stay at a constant usage rate (which should be fine). Therefore, while a chunk is being created, it can only append one more chunk to the queue.

Are my ideas fully understood now?

**Comment by w-okada** [comment]
As previously mentioned, if a chunk has no audio input, the conversion process is bypassed. So, if the chunk size is small enough, it's likely that most of your proposal can be achieved.

If the chunk size is large, your proposal proves to be very effective. However, for users who wish to reduce latency, the split process becomes an additional step. Therefore, if we implement this, we must carefully avoid creating unnecessary overhead. This is what I referred to as challenging.
