### ISSUE TITLE
How do I remove pre-exising voices from my voice changer?

### ISSUE THREAD

**Issue by LK72e** [w-okada/voice-changer#440]
### Issue Type

Question

### vc client version number

1.5.3.7

### OS

windows 11

### GPU

none

### Clear setting

no

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

Ive read through the other issues and tried to find one thats applicable, and even re-read through the tutorial and tried to find videos, but i could not find one that would show how to remove a voice from my voice changer, as i want a new voice  but i have no space for it, if anyone could help that would be greatly appreciated. tysm in advance <3

**Comment by Eidenz** [comment]
You can upload new voices on existing one, this will replace it.

If you really want the slot to be empty, the slots folders are located in the `model_dir` folder. If you wanted to delete slot 9, delete the content of the folder '9'.

**Comment by LK72e** [comment]
oh this helps, thanks! now i can use new voices, thanks again
