### ISSUE TITLE
Passthrough is not supported, GL is disabled, ANGLE is

### ISSUE THREAD

**Issue by Esingar98** [w-okada/voice-changer#441]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9

### OS

Windows 11

### GPU

NVIDIA GeForce GTX 1050

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

I am writing this issue on the behalf of a friend of mine, who's facing it. Upon startup, after the application finishes downloading all the dependencies, the UI starts, but it doesn't load (Only the japanese buttons show up), giving only the error mentioned in the title. I have attached a screenshot of what he's seeing in the terminal: 

![image](https://github.com/w-okada/voice-changer/assets/86374399/47a0509c-4769-4c41-920e-2800b4ced672)

I am not sure what is causing this. Help would be appreciated. Thanks.

**Comment by w-okada** [comment]
read tutorial

**Comment by Esingar98** [comment]
I have seen the tutorial. But it doesn't seem ignoring it is the solution.
The GUI is just blank, it doesn't show up.

Il dom 9 lug 2023, 17:51 w-okada ***@***.***> ha scritto:

**Comment by w-okada** [comment]
Wait for a while

**Comment by w-okada** [comment]
no res close
