### ISSUE TITLE
Higher CPU usage with 1.5.3.9a

### ISSUE THREAD

**Issue by NataIynn** [w-okada/voice-changer#445]
### Issue Type

Bug Report

### vc client version number

1.5.3.9a

### OS

Windows 11

### GPU

RTX 2080 TI

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

Crepe, Harvest

### Situation

I've tried using the latest version, but seems like there is a 5-10% more CPU usage with the same exact settings. I'm using 320 chunk, crepe, and 131,072 extra.

**Comment by w-okada** [comment]
really? 
so, open the `.bat` and edit
--content_vec_500_onnx_on true -> --content_vec_500_onnx_on false

**Comment by NataIynn** [comment]
Seem that helped a bit, around 5% cpu reduction idling around 18% on average about the same almost. On the version 1.5.3.8a, with my settings its around 13-17.5% cpu usage.

**Comment by w-okada** [comment]
Sorry but I have no idea.

**Comment by l68728** [comment]
確かにそうです 
1.5.3.8.a：
<img width="533" alt="截屏2023-07-10 05 00 01" src="https://github.com/w-okada/voice-changer/assets/46189956/1322459c-2ac1-45cb-8da6-f3d321ba4d14">
1.5.3.9.a：
<img width="533" alt="截屏2023-07-10 04 58 03" src="https://github.com/w-okada/voice-changer/assets/46189956/9441c2a9-5d62-4d6c-9cff-c2226cb85e71">

**Comment by w-okada** [comment]
@l68728 

Did you change the .command?

--content_vec_500_onnx_on true -> --content_vec_500_onnx_on false

**Comment by NataIynn** [comment]
I noticed something else, which hopefully should nail down the issue a bit more for you.  The "res" value, seems to instantly jump too 1k, then 5k, 10k, 50k, 100k, not sure if its an memory leak, or what in one of the F0 Dets. I've tried with and without vec_500_onxx and it still happened. This seem to occurred, or at-least I've noticed it when I exported model as onxx.

**Comment by w-okada** [comment]
If the issue is occurring even when using ONNX switched off, and only using Harvest or Crepe (but not Crepe Full or Crepe Tiny), I don't immediately recall any fixes from v.1.5.3.8a to v.1.5.3.9a that would cause that. So, I really have no clue about it.

Rises in CPU load or response time could be due to a variety of factors, such as updates to other applications or the OS, or the effects of a virus scan, among other things.

In the same environment, is the CPU load still lower when running v.1.5.3.8a compared to v.1.5.3.9a?


By the way, this is the difference.
https://github.com/w-okada/voice-changer/compare/v.1.5.3.8a...v.1.5.3.9a

**Comment by w-okada** [comment]
no clue..

**Comment by SirBitesalot** [comment]
Might have something to do that I have noticed.
In 1.5.3.9a NonF0 Inference Time is still affected by selected f0 so it seems that f0 is computed even if the model does not use f0.
Maybe some other calculations are also unnecessarily computed?

**Comment by SirBitesalot** [comment]
@w-okada I found part of the issue. For some reason in one of my NonF0 models in the json config. The Value for F0 was set to true. Which explains why the F0 was computed. I dont know how the config got "corrupted" in this way. But I would assume that it had something to do with loading different models in the slot to test them. So I dont think its a common issue

**Comment by w-okada** [comment]
no clue, and new version is released. try the latest version. If problem remains, open new issue. sorry.
