### ISSUE TITLE
ERR.CONNECTION_REFUSED 

### ISSUE THREAD

**Issue by MCCX1** [w-okada/voice-changer#446]
### Issue Type

Bug Report

### vc client version number

1.5.3.8a

### OS

windows 10

### GPU

gtx 1070

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI didn't launch.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

model that came with the software.

### Situation

![Screenshot (164)](https://github.com/w-okada/voice-changer/assets/139090607/6db18e26-c8dd-4279-bfd5-036fefc8be09)
I've reinstalled it 3 times tried different versions 8a,9,9a it worked once but I closed it and reopened it and it started spitting out the error in the picture. I've also looked into other people who had this issue but couldn't find any solutions. Any help would be appreciated thanks.

**Comment by w-okada** [comment]
Error message said file is not found.

Q1. Is there a model_dir in the folder where the .bat file is located?
Q2. Is there a model_dir/1 in the folder where the .bat file is located?
Q3. Is there a model_dir/1/amitaro....(snip)  in the folder where the .bat file is located?

**Comment by MCCX1** [comment]
Yes I see all of those
![Screenshot (167)](https://github.com/w-okada/voice-changer/assets/139090607/ae7be8d4-d9a6-4bdd-b45d-e3bb1f1d8727)

![Screenshot (166)](https://
![Screenshot (165)](https://github.com/w-okada/voice-changer/assets/139090607/ce9e6dc1-aa13-4cb9-9426-b598e591da3f)
![Screenshot (166)](https://github.com/w-okada/voice-changer/assets/139090607/71b7c3c9-f97d-41a6-85ee-9da6da2eaa13)

**Comment by w-okada** [comment]
No, You can not see amitaro...(snip).onnx in the `model_dir/1/`

Very strange....

Please delete model_dir and stored_setting.json in the folder including .bat file.
And run startHttp.bat.
