### ISSUE TITLE
gpu is not working

### ISSUE THREAD

**Issue by FreneZar** [w-okada/voice-changer#448]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9.zip

### OS

Windows 11 Pro

### GPU

RTX 3060 Ti

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

MMVCServerSIO

### Model type

All

### Situation

I select the voice changer to use my GPU. Then the GPU is not working but the CPU usage is 100% full.Someone help ;-;

**Comment by w-okada** [comment]
read tutorial.
