### ISSUE TITLE
Seems that sup2 is not working properly

### ISSUE THREAD

**Issue by szlsama** [w-okada/voice-changer#449]
### Issue Type

Bug Report

### vc client version number

1539a

### OS

win11

### GPU

3060 laptop

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pth

### Situation

When I enable sup2 it suppresses all sounds, I tried to disable it and VC works fine.

**Comment by ThrowawayAccount01** [comment]
Same here. Enabling Sup2 causes all sounds to stop converting, only outputting silence.

**Comment by w-okada** [comment]
OK, many user said so. I started researching..

**Comment by w-okada** [comment]
I found this is bug. The npm package version had been rolled back. It is expected to be fixed in the next version.

**Comment by w-okada** [comment]
use new version, v.1.5.3.10

**Comment by w-okada** [comment]
close
