### ISSUE TITLE
 electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by Iqmalhakim** [w-okada/voice-changer#450]
### Issue Type

Question, Others

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9a

### OS

windows 11

### GPU

GTX 1660 ti

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

ONNX

### Situation

i keep getting this error :

(node:3120) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)

i already add the folder to be excluded but the error still apear

log:

    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Voice Changerを起動しています。
++[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

getSwitchValue1
getSwitchValue2 file
Preparing your application. Please wait...
(node:15072) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] model slot is changed -1 -> 0
................RVC
[Voice Changer] [RVC] Creating instance
[Voice Changer] [RVC] Initializing...
Preparing your application. Please wait...
(node:15072) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
Try loading... model_dir\0\added_IVF7852_Flat_nprobe_1_v2.index.bin
GENERATE INFERENCER <voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x0000015EFF1AD990>
GENERATE EMBEDDER <voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000015E8FD32860>
GENERATE PITCH EXTRACTOR <voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x0000015E8FD332B0>
[Voice Changer] [RVC] Initializing... done
VoiceChanger Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings silentThreshold 0
[Voice Changer][RVC]: update_settings f0Detector crepe
[Voice Changer][RVC]: update_settings serverReadChunkSize 24
[Voice Changer][RVC]: update_settings extraConvertSize 4096
[Voice Changer][RVC]: update_settings gpu 0
[Voice Changer] [RVC] Initializing...
[Voice Changer] generate new embedder. (anyway)
Preparing your application. Please wait...
(node:15072) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[Voice Changer] Loading index...
Try loading... model_dir\0\added_IVF7852_Flat_nprobe_1_v2.index.bin
GENERATE INFERENCER <voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x0000015E8FD33B50>
GENERATE EMBEDDER <voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000015EC1034C40>
GENERATE PITCH EXTRACTOR <voice_changer.RVC.pitchExtractor.CrepePitchExtractor.CrepePitchExtractor object at 0x0000015EC1034D90>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings enableServerAudio 0
[Voice Changer][RVC]: update_settings modelSlotIndex 1688922652000
[Voice Changer][RVC]: update_settings silentThreshold 0
[Voice Changer][RVC]: update_settings f0Detector crepe
[Voice Changer][RVC]: update_settings serverReadChunkSize 24
[Voice Changer][RVC]: update_settings extraConvertSize 4096
[Voice Changer][RVC]: update_settings gpu 0
[Voice Changer] [RVC] Initializing...
Preparing your application. Please wait...
(node:15072) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\0\added_IVF7852_Flat_nprobe_1_v2.index.bin
GENERATE INFERENCER <voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x0000015EFF1AC940>
GENERATE EMBEDDER <voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000015EC10351B0>
GENERATE PITCH EXTRACTOR <voice_changer.RVC.pitchExtractor.CrepePitchExtractor.CrepePitchExtractor object at 0x0000015EC1035D50>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings enableServerAudio 0
[20012:0710/182051.202:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is

**Comment by xiaoxuan1231** [comment]
I also encountered the same problem! It was running successfully for a few times, but after I logged out and logged in a few more times, it stopped working. I'm using Windows 11 and the version is MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9a.zip.



D:\自用\Ai变声\MMVCServerSIO_yingwen>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --model_dir model_dir     --samples samples.json
2023-07-11 04:34:35.1748316 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1641 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Voice Changerを起動しています。
++[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

getSwitchValue1
getSwitchValue2 file
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] model slot is changed -1 -> 3
................RVC
[Voice Changer] [RVC] Creating instance
[Voice Changer] [RVC] Initializing...
[Voice Changer] exception! loading inferencer [Errno 2] No such file or directory: 'model_dir\\3\\tokina_shigure_v2_40k_e100_simple.onnx'
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 19, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 24, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 35, in loadInferencer
  File "voice_changer\RVC\inferencer\RVCInferencer.py", line 16, in loadModel
  File "torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'model_dir\\3\\tokina_shigure_v2_40k_e100_simple.onnx'
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
[Voice Changer] Web Server Launch Exception local variable 'inferencer' referenced before assignment
Preparing your application. Please wait...
(node:39152) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)

**Comment by w-okada** [comment]
error said 

No such file or directory: 'model_dir\3\tokina_shigure_v2_40k_e100_simple.onnx'

please check the file exists.


And maybe the same?? (very storage...)

https://github.com/w-okada/voice-changer/issues/446

**Comment by Iqmalhakim** [comment]
> error said
> 
> No such file or directory: 'model_dir\3\tokina_shigure_v2_40k_e100_simple.onnx'
> 
> please check the file exists.
> 
> And maybe the same?? (very storage...)
> 
> #446

i will try reinstall

**Comment by Iqmalhakim** [comment]
the error still apear any other way to fix it?

**Comment by w-okada** [comment]
Are there the file??

Please delete model_dir and stored_setting.json in the folder including .bat file.
And run startHttp.bat.

**Comment by Iqmalhakim** [comment]
> Are there the file??
> 
> Please delete model_dir and stored_setting.json in the folder including .bat file. And run startHttp.bat.
is this for the model problem ?

thats not my problem thats other people problem paste here

**Comment by Iqmalhakim** [comment]
if its about the error model ?

thats other people problem they put thier log into my error report

**Comment by w-okada** [comment]
The virus scanner might work and take some time during the initial startup. How long did you wait?
You can also exclude it from the virus checker at your own risk. 

And, what happens when you access http://localhost:18888/ through a browser?

**Comment by MikuNakano02** [comment]
Try deleting that folder,then re extract in "Documents",worked for me, Also download all don't close and think yiu can download rest later.

**Comment by Denis6902** [comment]
try disable antivirus

**Comment by w-okada** [comment]
no res close

**Comment by ArcZeus** [comment]
I gave permissions to the folder and it worked.
![image](https://github.com/w-okada/voice-changer/assets/108293311/b98d056b-de0a-4e8a-9ef0-a2fcd8af9337)
