### ISSUE TITLE
Voice transformation is laggy

### ISSUE THREAD

**Issue by AKazaBLK** [w-okada/voice-changer#452]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.9a.zip

### OS

Windows 11

### GPU

AMD RADEON RX 6700

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

When I use my own models, the converted voice cuts out for a moment and then continues to jerk and deteriorate.

**Comment by w-okada** [comment]
We haven't received any similar reports. Could it be that your model is broken? It would be disappointing to call this a bug under the current circumstances.

**Comment by AKazaBLK** [comment]
> We haven't received any similar reports. Could it be that your model is broken? It would be disappointing to call this a bug under the current circumstances.
I don't think it's coming from my models as a friend uses mine and it works perfectly on an Nvidia GPU, maybe it's a personal "bug".

**Comment by w-okada** [comment]
OKey, And sorry but as I said in readme, I have no amd gpu. I have no idea to fix it.

**Comment by w-okada** [comment]
no res close
