### ISSUE TITLE
client not working 

### ISSUE THREAD

**Issue by kyuunz** [w-okada/voice-changer#454]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.9a

### OS

win10 

### GPU

AMD Radeon RX 6500 xt

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

all defaults

### Situation

w-okada voice changer not working
i've used it once just now seem's to be working fine but after a crash when I'm streaming I restarted my PC and the client doesn't work at all the application is just a white screen. I've even tried redownloading everything from scratch 2 times and still the same after I restart multiple times.

**Comment by kyuunz** [comment]
it's kinda working rn but it doesnt have any sound.
I've already have the volume and input, output correctly

**Comment by w-okada** [comment]
same 
https://github.com/w-okada/voice-changer/issues/449
