### ISSUE TITLE
input and output issue

### ISSUE THREAD

**Issue by Czesio2347890** [w-okada/voice-changer#455]
### Issue Type

Question

### vc client version number

v.1.5.3.9

### OS

windows 11

### GPU

gtx 1650

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

rvc

### Model type

idk

### Situation

when im turning it on I can only hear ai's voice in the app not in the discord or somethinghow should i set input and output to hear it on discord. I set the same input and output on discord and the app so idk whats wrong.

**Comment by w-okada** [comment]
Would this be helpful as a reference? However, please note that Discord is not my app, so I can't provide detailed explanations.

https://www.youtube.com/watch?v=IS_SPQVv5iY

**Comment by w-okada** [comment]
no res close
