### ISSUE TITLE
Mac os error when opening

### ISSUE THREAD

**Issue by WapixelXD** [w-okada/voice-changer#456]
Hello, I have small issue with this. I have a macbook air 2017 and im trying to open the start script however i'm getting a error that states: 

zakariajarurattanon@ZackyJarattanon ~ % /Users/zakariajarurattanon/Desktop/MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.9a/startHttp.command ; exit;
/Users/zakariajarurattanon
/Users/zakariajarurattanon/Desktop/MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.9a/startHttp.command: line 21: MMVCServerSIO.app/Contents/MacOS/MMVCServerSIO: Bad CPU type in executable

![Schermafbeelding 2023-07-11 om 19 22 05](https://github.com/w-okada/voice-changer/assets/139261196/836b7984-40f2-44b0-8ab7-381b34ebe97f)

Welp, i hope it will be fixed someday.

**Comment by l68728** [comment]
Looks like it doesn't support intel cpu Mac(x86)

**Comment by w-okada** [comment]
Mac Intel is not supported
