### ISSUE TITLE
Error loading python DLL....../python310.dll

### ISSUE THREAD

**Issue by zzmadar4** [w-okada/voice-changer#457]
### Issue Type

Others

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.9

### OS

Windows 7

### GPU

AMD 8850m

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

i dont know

### Situation

when launching the http.bat 
it directly closes
and i screenshot the error it was a python310.dll 
i tried to download another one it didnt work 
![image](https://github.com/w-okada/voice-changer/assets/139271568/559c823b-737e-4874-af08-4d21b87aa702)

**Comment by w-okada** [comment]
Your windows is too old. not supported.

**Comment by te-ch** [comment]
hey @zzmadar4 were you ever able to fix this?
