### ISSUE TITLE
Failed to execute script 'MMVCServerSIO' due to unhandled exception: stat: path should be string, bytes, os.PathLike or integer, not NoneTyp

### ISSUE THREAD

**Issue by Kosazhra** [w-okada/voice-changer#458]
### Issue Type

Bug Report, Question

### vc client version number

MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.9a.zip

### OS

M1 Ventura 13.4.1

### GPU

M1 Max

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

none

### Model type

none

### Situation

I downloaded the file, expanded the zip, ran startHttp.command by right clicking on the file and selecting open, no new text appeared Terminal and then it said that MMVCServerSIO could be run because it was from unidentified developer, I went to system preferences and allowed for an exception to be made for the program, it tries to run, but it couldn't run because of multiple errors. I also downloaded Anaconda. I do not know what or how to clear settings or what and where the sample model is and what an input chunk num is, so I answered "no" to all of those, I also was never able to run the program so I listed Voice Changer type and Model type as "none". I don't know much(or anything rather) about this stuff so I'm probably be doing something stupid, forgive me if I am.
[Terminal Saved Output.txt](https://github.com/w-okada/voice-changer/files/12023138/Terminal.Saved.Output.txt)

**Comment by w-okada** [comment]
> I'm probably be doing something stupid, forgive me if I am.

No, maybe you're not that bad.
Mac Venture user have same trouble, And someone fixed the other have not fixed...

Please check this issue.
https://github.com/w-okada/voice-changer/issues/339

And this may be same issue above, So i close.

**Comment by Kosazhra** [comment]
I was unable to get the program to run, but thanks for helping anyways. I really like what you're doing with the project, and I wish you the best.

**Comment by kaktus229** [comment]
do anubody know a solusion of this problem on windows?

**Comment by OverLookk** [comment]
i get the same thing but on windows i have no idea whats wrong

**Comment by liinaliiis** [comment]
![image](https://github.com/w-okada/voice-changer/assets/157061076/3339389c-84b6-4d26-9bc8-fb7e3573870d)
