### ISSUE TITLE
Errors when opening start_http.bat

### ISSUE THREAD

**Issue by muratcansimsek** [w-okada/voice-changer#461]
### Issue Type

Others

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.9a.zip

### OS

Windows 8.1 Ghost Spectre Potato Edition

### GPU

Sapphire R7 265 Dual-X 2GB

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

-

### Model type

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.9a

### Situation

![image](https://github.com/w-okada/voice-changer/assets/25007736/f38de65d-83e6-4760-b417-4b8cba121301)
What should i do?

**Comment by w-okada** [comment]
Sorry, your windows is too old, maybe not supported. upgrade windows.
