### ISSUE TITLE
这个软件必须联网吗？有不需要联网的版本吗？

### ISSUE THREAD

**Issue by xypiaofei** [w-okada/voice-changer#463]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9a

### OS

WIN11

### GPU

GTX 4070

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

f0

### Situation

这个软件必须联网吗？有不需要联网的版本吗？

**Comment by w-okada** [comment]
初回起動時は必要です。２回目以降は接続しないでも動くかもしれません。

**Comment by w-okada** [comment]
no res close
