### ISSUE TITLE
Intel MacBook Pro support possible?

### ISSUE THREAD

**Issue by Naozumi520** [w-okada/voice-changer#464]
### Issue Type

Feature Request

### vc client version number

MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.9a.zip

### OS

Ventura 13/4 Intel (Intel is not supported)

### GPU

5500M

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

Never tried

### Situation

I'm an intel Mac user. I trained RVC model on my intel MacBook Pro (MPS supported on RVC). I also modified RVC realtime script to make it run on macOS (result was poor). So I think it is possible to run in intel Mac? (MPS available on both arm64 and x86_64). I'm happy to contribute to this project if there's needs to build or test on intel Mac.

**Comment by Naozumi520** [comment]
<img width="1792" alt="Screenshot 2023-07-13 at 3 55 15 PM" src="https://github.com/w-okada/voice-changer/assets/52615455/c6965aa9-b64e-4034-8989-236bc3420640">

I'm trying to figure out how to source code working. But I'm sticking at this page and I've no idea what's going on.

**Comment by northmoke** [comment]
Same in intel Mac, but worse in I can't even open it up

**Comment by Naozumi520** [comment]
> Same in intel Mac, but worse in I can't even open it up

I didn't use the prebuilt binary, instead I download the repo and start in command.

**Comment by w-okada** [comment]
no update close
