### ISSUE TITLE
No graphics card

### ISSUE THREAD

**Issue by Rosie119** [w-okada/voice-changer#465]
What should I download If I don't have graphics card? in the hugging face site?

**Comment by Katze719** [comment]
readd the README.md => `If you are not using a GPU on Windows, please download ONNX (cpu, cuda) and PyTorch (cpu, cuda).`

just for you, its `[MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9a.zip](https://huggingface.co/wok000/vcclient000/blob/main/MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9a.zip)`

**Comment by Rosie119** [comment]
thats what I downloaded, in the cmd it says when I start "ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is"

**Comment by w-okada** [comment]
use issue template
