### ISSUE TITLE
Cannot complete initial setup

### ISSUE THREAD

**Issue by PIndividual** [w-okada/voice-changer#466]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9

### OS

windows 10 22H2

### GPU

Nvidia GeForce RTX 3070 Ti

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

No Data

### Model type

No Data

### Situation

I tried launching the start_https bat* file several times and it seems that it cannot locate a folder called modles_dir, it simply stuck on the same line every time.
Here is what is shown on my cmd window:

C:\Users\Admin\Documents\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https true     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Voice Changerを起動しています。
('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

 13%|█████████▉                                                                    | 45.9M/361M [00:02<00:17, 19.4MB/s]    RVC用のモデルファイルのダウンロードに失敗しました。
    failed to download weight for rvc
('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
[Voice Changer] loading sample failed [Errno 2] No such file or directory: 'samples_0003_t2.json'
    Internal_Port:18888
    protocol: HTTPS(self-signed), key:C:\Users\GASP3D4L\AppData\Local\Temp\tmp7m_gfzm2\keys\20230713_220755.key, cert:C:\Users\GASP3D4L\AppData\Local\Temp\tmp7m_gfzm2\keys\20230713_220755.cert
    -- ---- --
    ブラウザで次のURLを開いてください.
    https://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    https://localhost:18888/
    https://192.168.10.15:18888/
    Booting PHASE :MMVCServerSIO
[Voice Changer] Web Server Launch Exception Directory 'model_dir' does not exist

**Comment by PIndividual** [comment]
By the way, using "start_http" does seem to push it a little further but it only comes to showing a blank window.
Here is what is shown on cmd:

C:\Users\Admin\Documents\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Voice Changerを起動しています。
('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
                                                                                                                           RVC用のモデルファイルのダウンロードに失敗しました。
    failed to download weight for rvc
('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
[Voice Changer] loading sample failed [Errno 2] No such file or directory: 'samples_0003_t2.json'
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] Web Server Launch Exception Directory 'model_dir' does not exist
Preparing your application. Please wait...
(node:15016) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
Preparing your application. Please wait...
(node:15016) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:15016) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:15016) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:15016) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:15016) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:15016) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...

**Comment by w-okada** [comment]
> ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
> RVC用のモデルファイルのダウンロードに失敗しました。

It seems like the model download has failed. Please review your network settings.

**Comment by w-okada** [comment]
no res close
