### ISSUE TITLE
哪个版本的内核是使用的RVC-0528v2版本？

### ISSUE THREAD

**Issue by xypiaofei** [w-okada/voice-changer#468]
### Issue Type

Others

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9a

### OS

WIN11

### GPU

GTX 4070

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

f0

### Situation

从哪里可以下载到包含RVC-0528v2的日本版？谢谢。

**Comment by w-okada** [comment]
I'm sorry, but I don't understand the purpose of your question.
