### ISSUE TITLE
When Start, voice not listening

### ISSUE THREAD

**Issue by tetsuki02** [w-okada/voice-changer#469]
Issue Type
Others

vc client version number
MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9a

OS
WIN11

GPU
GTX 1050Ti

Clear setting
yes

Sample model
yes

Input chunk num
yes

Wait for a while
The GUI successfully launched.

read tutorial
yes

Extract files to a new folder.
yes

Voice Changer type
RVC

Model type
f0

Situation
when start voice changer, i cant listening on mic and discord. and voice not out from microphone

**Comment by w-okada** [comment]
same
https://github.com/w-okada/voice-changer/issues/455
