### ISSUE TITLE
Where is start_http.bat?

### ISSUE THREAD

**Issue by YeloPartyHat** [w-okada/voice-changer#473]
### Issue Type

Documentation Feature Request

### vc client version number

N/A

### OS

Windows 10

### GPU

none

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

N/A

### Model type

N/A

### Situation

I don't get it. Where is this `start_http.bat` mentioned throughout the documentation? https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md#steps-up-to-startup

**Comment by rudolp-tmQ** [comment]
what version did you download? its in the root folder

**Comment by GuteKatze** [comment]
If I got it correctly, he just trying to use zip of git rep, instead of downloading version from the table on README.md

**Comment by w-okada** [comment]
no res close

**Comment by YeloPartyHat** [comment]
Yeah, it isn't clear on the wiki that the files should be from the huggingface download. That's what this issue is about.
