### ISSUE TITLE
with error: ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by YuHuaOcean** [w-okada/voice-changer#476]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.9a

### OS

Windows 10

### GPU

RX 6700 XT

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Voice Changerを起動しています。
++[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:16771
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:16771/

getSwitchValue1
getSwitchValue2 file
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
Preparing your application. Please wait...
(node:21376) electron: Failed to load URL: http://localhost:16771/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
Preparing your application. Please wait...
(node:21376) electron: Failed to load URL: http://localhost:16771/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:21376) electron: Failed to load URL: http://localhost:16771/ with error: ERR_CONNECTION_REFUSED
Traceback (most recent call last):
  File "MMVCServerSIO.py", line 235, in <module>
  File "subprocess.py", line 1209, in wait
  File "subprocess.py", line 1506, in _wait
KeyboardInterrupt
[21048] Failed to execute script 'MMVCServerSIO' due to unhandled exception!

**Comment by YuHuaOcean** [comment]
I turned off Windows Defender, but it didn't work

**Comment by w-okada** [comment]
The port number isn't the default, is it? If you've done any special operations, please let me know.

**Comment by littlestronomer** [comment]
> The port number isn't the default, is it? If you've done any special operations, please let me know.

What should be the default port number? Mine is 18888

**Comment by Ender261** [comment]
> 

me to

**Comment by w-okada** [comment]
Yes, 18888 is default. but this is not important. 
What I want to know is the procedure to reproduce. If you change the port, but not report, I this there are more thing you did.
So I said
> The port number isn't the default, is it? If you've done any special operations, please let me know.

**Comment by YuHuaOcean** [comment]
> Yes, 18888 is default. but this is not important. 
> What I want to know is the procedure to reproduce. If you change the port, but not report, I this there are more thing you did.
> So I said
> > The port number isn't the default, is it? If you've done any special operations, please let me know.
> 
> 
> 

I was just worried about port conflicts, so I changed the port without doing anything else

**Comment by YuHuaOcean** [comment]
> 

This is the error that I did not modify the port for the first time. I suspect that I changed the port because of a port conflict, but this error is still the same.

**Comment by YuHuaOcean** [comment]
> 是的，默认为18888。但这并不重要。 我想知道的是重置的过程。如果您更改端口，但不报告，我认为您还做了更多事情。 所以我说
> 
> > 端口号不是默认的，是吗？如果您有任何特殊操作，请告诉我。

This is the error that I did not modify the port for the first time. I suspect that I changed the port because of a port conflict, but this error is still the same.

**Comment by YuHuaOcean** [comment]
> Yes, 18888 is default. but this is not important. What I want to know is the procedure to reproduce. If you change the port, but not report, I this there are more thing you did. So I said
> 
> > The port number isn't the default, is it? If you've done any special operations, please let me know.

This is the error that I did not modify the port for the first time. I suspect that I changed the port because of a port conflict, but this error is still the same.

**Comment by Hyrmm** [comment]
I also have this problem, I am using the default port 1888, I have the same problem above

**Comment by kongo33334** [comment]
still having this problem til now, getting the err_connection_refused whenever trying to even open it up, tried deleting the model folder but it only loads the ui before i get a bunch of errors showing up on the client. i tried flushing my dns, fixing my internet, everything that should fix the error but it still remains. p disappointing to see so many people got it to work so well except me with problems after problems. still trying to find a work around tho

**Comment by w-okada** [comment]
How long did you wait?

**Comment by YuHuaOcean** [comment]
> How long did you wait?

I tried waiting an hour for loading

**Comment by skyemk** [comment]
Had the same error, delete "stored_setting.json", and "samples.json*" it works again.

Settings file was empty, so i'm assuming some kind of file corruption maybe. I remember saving settings while in client and reopening and getting the error.

**Comment by skyemk** [comment]
Had the same error, delete "stored_setting.json", and "samples.json*" it works again.

Settings file was empty, so I'm assuming some kind of file corruption maybe. I remember saving settings while in client and reopening and getting the error.

**Comment by skyemk** [comment]
Had the same error, delete "stored_setting.json", and "samples.json*" it works again.

Settings file was empty, so i'm assuming some kind of file corruption maybe. I remember saving settings while in client and reopening and getting the error.

**Comment by noersy** [comment]
On Mac-M1-RAM8

It crashes when I ever select the model.

![Screenshot 2023-07-22 at 7 55 31 PM](https://github.com/w-okada/voice-changer/assets/55045713/649b3c45-7024-4c26-bb03-8b262f70ea89)

And when I start again it won't open. 

![Screenshot 2023-07-22 at 7 58 02 PM](https://github.com/w-okada/voice-changer/assets/55045713/a6b0afbf-7322-4d92-a00e-c23edba0aff0)

Or if I start with HTTP its shows this error.

![Screenshot 2023-07-22 at 7 59 09 PM](https://github.com/w-okada/voice-changer/assets/55045713/336c0fd3-1600-48da-83ae-dc28164f3b15)

But it will open again if I delete `stored_setting.json`

---

What is the specification requirement for this program? I can't find it.

**Comment by lenexyyy** [comment]
Having a same problem as well
![image_2023-07-22_212611425](https://github.com/w-okada/voice-changer/assets/82310241/17638841-d6a3-41f6-a8c0-4b7ce298af9b)
Booting PHASE :__main__
PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Voice Changerを起動しています。
RVC用のモデルファイルのダウンロードに失敗しました。
failed to download weight for rvc
[Errno 13] Permission denied: 'samples_0003_t2.json'
[Errno 13] Permission denied: 'samples_0003_o2.json'
[Voice Changer] loading sample failed [Errno 2] No such file or directory: 'samples_0003_t2.json'
Internal_Port:18888
protocol: HTTP
-- ---- --
ブラウザで次のURLを開いてください.
http://:/
多くの場合は次のいずれかのURLにアクセスすると起動します。
http://localhost:18888/

getSwitchValue1
getSwitchValue2 file
[6412:0722/144256.257:ERROR:logging.cc(144)] Failed to init logging: Access is denied. (0x5)
[0722/144256.423:ERROR:logging.cc(144)] Failed to init logging: Access is denied. (0x5)
[0722/144256.489:ERROR:logging.cc(144)] Failed to init logging: Access is denied. (0x5)
[0722/144256.586:ERROR:logging.cc(144)] Failed to init logging: Access is denied. (0x5)
[0722/144258.964:ERROR:logging.cc(144)] Failed to init logging: Access is denied. (0x5)
Preparing your application. Please wait...
(node:6412) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use voice-changer-native-client --trace-warnings ... to show where the warning was created)
[0722/144300.111:ERROR:logging.cc(144)] Failed to init logging: Access is denied. (0x5)
Booting PHASE :main
Booting PHASE :MMVCServerSIO
[Voice Changer] Web Server Launch Exception Directory 'model_dir' does not exist
Preparing your application. Please wait...
(node:6412) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[0722/144303.456:ERROR:logging.cc(144)] Failed to init logging: Access is denied. (0x5)
Preparing your application. Please wait...
(node:6412) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[0722/144306.842:ERROR:logging.cc(144)] Failed to init logging: Access is denied. (0x5)
Preparing your application. Please wait...
(node:6412) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[0722/144310.208:ERROR:logging.cc(144)] Failed to init logging: Access is denied. (0x5)
Preparing your application. Please wait...
(node:6412) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[0722/144313.734:ERROR:logging.cc(144)] Failed to init logging: Access is denied. (0x5)
Preparing your application. Please wait...
(node:6412) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[0722/144316.950:ERROR:logging.cc(144)] Failed to init logging: Access is denied. (0x5)
Preparing your application. Please wait...
(node:6412) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED

**Comment by bobbyl140** [comment]
Same issue on macOS.

**Comment by ptar124** [comment]
![image](https://github.com/w-okada/voice-changer/assets/22909681/cedcaeae-c42c-43c3-a5ce-8d882f2d713f)

RTX 4060 Laptop GPU, Windows 11

Error messages and behavior are the same as @lenexyyy

I have tried both directml-cuda and gpu-cuda on versions 10a, 10 and 9a.

I was able to run the old Anaconda version through my browser, but the native client does not seem to start.

**Comment by w-okada** [comment]
permission denied. check your permission.

**Comment by ptar124** [comment]
> permission denied. check your permission.

Hello! I was able to solve it by moving it out of a directory that requires elevated permissions. Initially I had the .zip extracted to Program Files (x86) which requires Administrator permissions. Sorry!

**Comment by YuHuaOcean** [comment]
> @YuHuaOcean Has the problem not been resolved yet? A new version has been released, could you please give it a try? (v.1.5.3.10a)

[Voice Changer] matplotlib is dummied
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Voice Changerを起動しています。
                                                                                                                       +++[MODEL SLOT INFO] [ModelSlot(voiceChangerType=None, name='', description='', credit='', termsOfUseUrl='', iconFile='', speakers={}), ModelSlot(voiceChangerType=None, name='', description='', credit='', termsOfUseUrl='', iconFile='', speakers={}), ModelSlot(voiceChangerType=None, name='', description='', credit='', termsOfUseUrl='', iconFile='', speakers={}), ModelSlot(voiceChangerType=None, name='', description='', credit='', termsOfUseUrl='', iconFile='', speakers={}), ModelSlot(voiceChangerType=None, name='', description='', credit='', termsOfUseUrl='', iconFile='', speakers={}), ModelSlot(voiceChangerType=None, name='', description='', credit='', termsOfUseUrl='', iconFile='', speakers={}), ModelSlot(voiceChangerType=None, name='', description='', credit='', termsOfUseUrl='', iconFile='', speakers={}), ModelSlot(voiceChangerType=None, name='', description='', credit='', termsOfUseUrl='', iconFile='', speakers={}), ModelSlot(voiceChangerType=None, name='', description='', credit='', termsOfUseUrl='', iconFile='', speakers={}), ModelSlot(voiceChangerType=None, name='', description='', credit='', termsOfUseUrl='', iconFile='', speakers={})]
[Voice Changer] Downloading model files...
                                                                                                                       [Voice Changer] Generating metadata...
[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] ONNX Model: Official v2 like
 [Loading] model_dir\4\combo_spk5_nl3_dl20_k50_500ep.ptc.bin
 [Loading] model_dir\5\combo_spk5_nl3_dl1_k50_500ep.ptc.bin
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

[Voice Changer] matplotlib is dummied
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[MODEL SLOT INFO] [RVCModelSlot(voiceChangerType='RVC', name='つくよみちゃん(onnx)', description='', credit='つくよみち ゃん', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tsukuyomi-chan/terms_of_use.txt', iconFile='model_dir\\0\\tsukuyomi-chan.png', speakers={'0': 'target'}, modelFile='model_dir\\0\\tsukuyomi_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='Tsukuyomi-chan_o'), RVCModelSlot(voiceChangerType='RVC', name='あみたろ(onnx)', description='', credit='あみたろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/amitaro/terms_of_use.txt', iconFile='model_dir\\1\\amitaro.png', speakers={'0': 'target'}, modelFile='model_dir\\1\\amitaro_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='Amitaro_o'), RVCModelSlot(voiceChangerType='RVC', name='黄琴まひろ(onnx)', description='', credit='黄琴まひろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/kikoto_mahiro/terms_of_use.txt', iconFile='model_dir\\2\\kikoto_mahiro.png', speakers={'0': 'target'}, modelFile='model_dir\\2\\kikoto_mahiro_v2_40k_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='KikotoMahiro_o'), RVCModelSlot(voiceChangerType='RVC', name='刻鳴時雨(onnx)', description='', credit='刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tokina_shigure/terms_of_use.txt', iconFile='model_dir\\3\\tokina_shigure.png', speakers={'0': 'target'}, modelFile='model_dir\\3\\tokina_shigure_v2_40k_e100_simple.onnx', indexFile='model_dir\\3\\added_IVF2736_Flat_nprobe_1_v2.index.bin', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='TokinaShigure_o'), DiffusionSVCModelSlot(voiceChangerType='Diffusion-SVC', name='初期メン(3,20)', description='', credit='あみたろ,つくよみちゃん,黄琴海月,黄琴まひろ,刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/diffusion-svc/term_of_use.txt', iconFile='model_dir\\4\\diffusion-svc.png', speakers={'1': 'user1', '2': 'user2', '3': 'user3', '4': 'user4', '5': 'user5'}, modelFile='model_dir\\4\\combo_spk5_nl3_dl20_k50_500ep.ptc.bin', isONNX=False, modelType='combo', dstId=1, sampleId='diffusion_combo_spk5_nl3_dl20_k50_500ep', defaultTune=0, defaultKstep=50, defaultSpeedup=25, kStepMax=50, nLayers=20, nnLayers=3, embedder='hubert_base', samplingRate=44100, embChannels=768), DiffusionSVCModelSlot(voiceChangerType='Diffusion-SVC', name='初 期メン(3,1)', description='', credit='あみたろ,つくよみちゃん,黄琴海月,黄琴まひろ,刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/diffusion-svc/term_of_use.txt', iconFile='model_dir\\5\\diffusion-svc.png', speakers={'1': 'user1', '2': 'user2', '3': 'user3', '4': 'user4', '5': 'user5'}, modelFile='model_dir\\5\\combo_spk5_nl3_dl1_k50_500ep.ptc.bin', isONNX=False, modelType='combo', dstId=1, sampleId='diffusion_combo_spk5_nl3_dl1_k50_500ep', defaultTune=0, defaultKstep=50, defaultSpeedup=25, kStepMax=50, nLayers=1, nnLayers=3, embedder='hubert_base', samplingRate=44100, embChannels=768), ModelSlot(voiceChangerType=None, name='', description='', credit='', termsOfUseUrl='', iconFile='', speakers={}), ModelSlot(voiceChangerType=None, name='', description='', credit='', termsOfUseUrl='', iconFile='', speakers={}), ModelSlot(voiceChangerType=None, name='', description='', credit='', termsOfUseUrl='', iconFile='', speakers={}), ModelSlot(voiceChangerType=None, name='', description='', credit='', termsOfUseUrl='', iconFile='', speakers={})]
Preparing your application. Please wait...
(node:22672) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
Preparing your application. Please wait...
(node:22672) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:22672) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:22672) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:22672) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...
(node:22672) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Traceback (most recent call last):
  File "MMVCServerSIO.py", line 237, in <module>
  File "subprocess.py", line 1209, in wait
  File "subprocess.py", line 1506, in _wait
KeyboardInterrupt
[3516] Failed to execute script 'MMVCServerSIO' due to unhandled exception!

**Comment by w-okada** [comment]
@YuHuaOcean
I have absolutely no idea. Other people are able to run it.

You're saying you've done the network and antivirus software settings, right? You've been waiting for over an hour, right? You've accessed http://localhost:18888 through your browser, right? I have absolutely no clue. I am at a loss. Sorry.

**Comment by YuHuaOcean** [comment]
> @YuHuaOcean I have absolutely no idea. Other people are able to run it.
> 
> You're saying you've done the network and antivirus software settings, right? You've been waiting for over an hour, right? You've accessed http://localhost:18888 through your browser, right? I have absolutely no clue. I am at a loss. Sorry.

ok sorry for the trouble, thank you

**Comment by KatsuraHina** [comment]
> @YuHuaOcean I have absolutely no idea. Other people are able to run it.
> 
> You're saying you've done the network and antivirus software settings, right? You've been waiting for over an hour, right? You've accessed http://localhost:18888 through your browser, right? I have absolutely no clue. I am at a loss. Sorry.

My browser says that it cant reach the site

**Comment by KatsuraHina** [comment]
> @YuHuaOcean I have absolutely no idea. Other people are able to run it.
> 
> You're saying you've done the network and antivirus software settings, right? You've been waiting for over an hour, right? You've accessed http://localhost:18888 through your browser, right? I have absolutely no clue. I am at a loss. Sorry.

my says that the site cant be reached
