### ISSUE TITLE
electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by lempre** [w-okada/voice-changer#478]
### Issue Type

Question

### vc client version number

1.5.3.9a

### OS

MacOS Ventura (M1)

### GPU

M1

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

Default

### Model type

Default

### Situation

I started startHttp.command, everythink downloaded fine but after everything this happened and nothing is working.
![photo_2023-07-15 18 11 50](https://github.com/w-okada/voice-changer/assets/51452411/f5dcef03-5246-4fbd-be93-a0228c4d5b75)
![photo_2023-07-15 18 11 47](https://github.com/w-okada/voice-changer/assets/51452411/1286e2cd-970f-489c-9b5f-2d502b64cbd4)
![photo_2023-07-15 18 11 44](https://github.com/w-okada/voice-changer/assets/51452411/c7d391ba-e0d0-46c6-9e87-c0b21fd24167)

**Comment by MikuNakano02** [comment]
same issue here

**Comment by Nazaroadi** [comment]
same problem

**Comment by Ender261** [comment]
Same problem i deactivated my firewall nothing happened
