### ISSUE TITLE
(node:64601) electron: Failed to load URL: https://localhost:18888/ with error: ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by Ender261** [w-okada/voice-changer#480]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.9a.zip

### OS

MacOS 13.1 (22C65)

### GPU

none

### Clear setting

no

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

Not sure

### Situation

![image](https://github.com/w-okada/voice-changer/assets/139681292/269042f6-e367-4732-9b40-c736b9dda128)
This message pops up in Terminal when i try to pick a characters voice for some reason

**Comment by Ender261** [comment]
<img width="758" alt="Screenshot 2023-07-15 at 19 09 18" src="https://github.com/w-okada/voice-changer/assets/139681292/be6d78de-8aac-4435-a021-eb4189dbf49d">

**Comment by MikuNakano02** [comment]
same issue here,i get "Looks like there's abit of a problem when selecting mic

**Comment by Ender261** [comment]
> 
im not sure if im missing any files
<img width="914" alt="Screenshot 2023-07-16 at 11 40 08 1" src="https://github.com/w-okada/voice-changer/assets/139681292/36cfd94f-348e-43ba-a67a-c1202d8bee14">

**Comment by Ender261** [comment]
<img width="1568" alt="Screenshot 2023-07-16 at 15 13 14" src="https://github.com/w-okada/voice-changer/assets/139681292/550bbb3c-936a-492e-a7a8-f5ba90cd8b85">

**Comment by MaoGT** [comment]
I run successfully the first time and then quit, after running again I had the same problem

**Comment by w-okada** [comment]
same
https://github.com/w-okada/voice-changer/issues/339
