### ISSUE TITLE
exception! loading inferencer invalid load key, '\x08'.

### ISSUE THREAD

**Issue by Nazaroadi** [w-okada/voice-changer#481]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9a

### OS

win11

### GPU

4070laptop

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

OMNX

### Situation

![image](https://github.com/w-okada/voice-changer/assets/77767921/5f7520d5-af4e-4d8e-a84b-f9c33c9e833f)

**Comment by w-okada** [comment]
It seems like the model is failing to load. Please check if the model is appropriate.

**Comment by w-okada** [comment]
no res close

**Comment by rorosin** [comment]
I have same issue, all models is correctly working only if i restart server

**Comment by rorosin** [comment]
@w-okada
