### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'on_request'

### ISSUE THREAD

**Issue by Ender261** [w-okada/voice-changer#483]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.9a.zip

### OS

MacOS 13.1 (22C65)

### GPU

none

### Clear setting

no

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

Not sure

### Situation

![image_2023-07-16_133812481](https://github.com/w-okada/voice-changer/assets/139681292/4d5b0ff0-79fd-4200-8d33-6f1a9c52e5b1)

https://github.com/w-okada/voice-changer/assets/139681292/0e87a5bc-ee43-481a-b245-86b5a63cd855

As you can see in the video i am clicking it but nothing happens i tried talking but it doesnt do anything

**Comment by Ender261** [comment]
<img width="1680" alt="Screenshot 2023-07-16 at 14 04 52" src="https://github.com/w-okada/voice-changer/assets/139681292/d0e9cedf-283a-4889-877a-af86be510934">
this is currently what the folder looks like

**Comment by yukiqt** [comment]
how did you fix this
