### ISSUE TITLE
AMD RX 570 no dropdown option? and Very High MS on Res and buf

### ISSUE THREAD

**Issue by Rosetta-Rigor** [w-okada/voice-changer#485]
### Issue Type

Feature Request

### vc client version number

1.5.3.8a

### OS

win 10

### GPU

rx 570

### Clear setting

no

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

no

### Extract files to a new folder.

yes

### Voice Changer type

rvc

### Model type

onnx

### Situation

Following through youtube tutorials I cant seem to find my gpu nor any dropdown lists. I am using an rx 570 but when im using the vc the res ms is very high to the point that the output is choppy and by like 40 seconds delay. Someone said its because my machine is struggling but when i checked task manager, both cpu and gpu are running 0-10% as if its on idle.

**Comment by w-okada** [comment]
I have absolutely no idea. Let's see if anyone else is experiencing the same issue.

**Comment by angryisfat** [comment]
I also have this issue. The gpu i use is rx 6600 xt. My ms for res and buf is really high to the point where it breaks. I keep trying to close and open it again but the issue is still there.

**Comment by kinn24** [comment]
I have this issue as well, The gpu I use is rx 550. When I press start my ms for res and buf starts to rise up also to the point it breaks. I've tried things such as reinstalling and restarting, lowering chunk or extra but it didn't fix the problem.

**Comment by vitpekarek** [comment]
I have same issue with 7900XTX. After pressing start my res ms is continuing to increase.

**Comment by w-okada** [comment]
see
https://github.com/w-okada/voice-changer/issues/410

**Comment by ketho2517** [comment]
hi, has anyone fixed it? i have the same GPU (rx570) and it's pretty much unusable because of the lag and delay, would really appreciate it if someone finds a solution.

**Comment by kreindo** [comment]
had the same issue here, high MS on my rx570
