### ISSUE TITLE
Start_http not opening

### ISSUE THREAD

**Issue by deivanna** [w-okada/voice-changer#486]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9a.zip

### OS

Windows 11 pro

### GPU

NVIDIA RTX 3070 TI

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

I dont know...

### Situation

So i downloaded, extracted and moved the folder inside of the extracted folder outside (so its easier to access) and opened start_http.bat, theres the issue - it opens for a mere second, even less than that, so little i cant even see anything in the console it doesnt even have time to load, as i said it opens for a milisecond and closes itself, tried on start_https.bat too but the same thing, i turned off windows defender and added the file AND the folder into exclusions, also added folder and file in allow list in malware byte, rebooted pc and opened again still the same thing! but i have one suspicion, i dont have a microphone/headphone (or headset) plugged in so is it because of that? (i ordered a headset its arriving shortly i just wanted to set the software up to use later on)

**Comment by w-okada** [comment]
no res close

**Comment by deivanna** [comment]
i fixed the problem, i just had to install the different version without the **a** at the end

**Comment by Henikku** [comment]
> i fixed the problem, i just had to install the different version without the **a** at the end

How did you do this? I'm having the exact same problem but I don't see any versions without an A at the end

**Comment by NebiyevEmil** [comment]
I'm having the same problem. Can someone who knows the solution please reply? please 🥉
