### ISSUE TITLE
Initial Download failed

### ISSUE THREAD

**Issue by littlestronomer** [w-okada/voice-changer#488]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.9a.zip

### OS

Windows 11

### GPU

AMD Radeon(TM) Graphics

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

.

### Situation

When I run the start_http, it will not work and the output will be like that. I have deleted all of the files and re-downloaded but didn't work.
<img width="857" alt="Screenshot 2023-07-17 190340" src="https://github.com/w-okada/voice-changer/assets/102169014/1171c35e-75f1-4a44-845a-e114c473e373">

**Comment by littlestronomer** [comment]
> UPDATE

The current problem is the same with here[here](https://github.com/w-okada/voice-changer/issues/450) right now.

**Comment by w-okada** [comment]
File looks like invalid.
Are there `model_dir` folder and `pretrain` folder?
And both folder have some file? show me the file list in the folder with file size.

**Comment by Omega-Projekt** [comment]
Hello w-okada. I have exact the same issues that littlestronomer has. model_dir and the pretrain folders didn't exists.

**Comment by w-okada** [comment]
Okey, so your initialization process failed. Please re-install. And same problem occur, check your network setting.

**Comment by littlestronomer** [comment]
> File looks like invalid. Are there `model_dir` folder and `pretrain` folder? And both folder have some file? show me the file list in the folder with file size.

I checked the files that you had told me.
<img width="581" alt="Screenshot 2023-07-18 012421" src="https://github.com/w-okada/voice-changer/assets/102169014/11efcd98-c6cc-4856-bcf2-1e1a920220ad">
<img width="594" alt="Screenshot 2023-07-18 012515" src="https://github.com/w-okada/voice-changer/assets/102169014/9424f53d-bba3-48df-b483-1dcd03da7141">

**Comment by Omega-Projekt** [comment]
I have downloaded it from here https://drive.google.com/uc?id=1eKZCozh37QDfAr33ZG7lGFUOQv1tOooR&export=download and extracted it.

**Comment by littlestronomer** [comment]
> I have downloaded it from here https://drive.google.com/uc?id=1eKZCozh37QDfAr33ZG7lGFUOQv1tOooR&export=download and extracted it.

Hmm, your link seems "unable to view" from me. I tried it downloading from huggingface. Maybe you can give it a chance 🤷

**Comment by w-okada** [comment]
this is my pretrain folder.
File size is different. so your download process is not successully completed.
Check your network and retry.

![image](https://github.com/w-okada/voice-changer/assets/48346627/bedabce8-95d5-4418-bf91-ee75cd2a0977)

**Comment by littlestronomer** [comment]
Understood, I will re-install the file and report the results o7

**Comment by littlestronomer** [comment]
Umm, I am sorry but seems like the app cannot detect my voice, what should I do?

**Comment by w-okada** [comment]
no res close
