### ISSUE TITLE
Laggy and cutting out

### ISSUE THREAD

**Issue by milkdudman** [w-okada/voice-changer#489]
### Issue Type

Bug Report, Others

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9a

### OS

Windows 11

### GPU

NVIDIA Geforce RTX 2060

### Clear setting

no

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

Crepe, harvest, ONNX

### Situation

It launches fine but when i use the voices it lags and cuts out every so often maybe with a 1-2 seconds delay between every time it cuts out

**Comment by Wang2Ling** [comment]
What components you have in your PC? I have same problem .Like lugging and cutting delay . I just saw the Task manager and My CPU with GPU loaded on 50-100% (I5-8300H and GTX 1050(4GB)) .So I think you have same PC or Laptop or worser.

**Comment by milkdudman** [comment]
I have (i7-9700 CPU and RTX 2060(6 GB)) on my task manager it says my CPU is 38-80 but the GPU Doesn't change it stay's between 1-10.

**Comment by milkdudman** [comment]
Sorry for the wait,  for the chunk I use 256 and the f0 method is Crepe.

**Comment by Lunarisnia** [comment]
Same here, also RTX 2060

**Comment by Wang2Ling** [comment]
Did you try to change it? I have lags on every setting

**Comment by harun-ui** [comment]
saya juga mengalami masalah yang serupa

**Comment by milkdudman** [comment]
![Screenshot 2023-07-24 152254](https://github.com/w-okada/voice-changer/assets/76594535/4c3fac9d-5d24-453b-87cf-9fabbbe73143)
![Screenshot 2023-07-24 152304](https://github.com/w-okada/voice-changer/assets/76594535/d8b97732-27c8-4724-a9b9-d3b7ee29a7f2)
![Screenshot 2023-07-24 152311](https://github.com/w-okada/voice-changer/assets/76594535/c72e105e-3e72-4019-a25e-9af487d2f5ba)
 I've tried it and it still sounds a bit choppy

**Comment by Mokokimiki** [comment]
Me have the same prob its very delay voice lag and cut off gtx1660ti ryzen7 3750

**Comment by w-okada** [comment]
@milkdudman 
How about your cpu usage and gpu usage?

And If you open a lot of tab of windows, close them.

**Comment by w-okada** [comment]
no res close

**Comment by milkdudman** [comment]
Sorry it worked forgot to reply.
