### ISSUE TITLE
MS Delay keep climbing

### ISSUE THREAD

**Issue by Sylynt** [w-okada/voice-changer#490]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.8a

### OS

Windows 11

### GPU

NVIDIA Geforce RTX 3080 Ti

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

All

### Situation

MS  Delay keeps climbing in numbers no matter what I do. As of posting it's currently at "res: 26079 ms"

**Comment by w-okada** [comment]
show logs on the terminal

**Comment by ZerIing** [comment]
> 

Hi, I have exactly the same problem, here is the log

[log.txt](https://github.com/w-okada/voice-changer/files/12110202/gol.txt)

**Comment by w-okada** [comment]
@ZerIing 
your gpu is not nvidia. use onnx model not pytorch

**Comment by w-okada** [comment]
What is your GPU. You should describe it. Not same as @Sylynt 's, because he/she uses nvidia gpu. Don't create chaos in the situation.

**Comment by w-okada** [comment]
no res close
