### ISSUE TITLE
Crashes and failing to load voicechanger

### ISSUE THREAD

**Issue by vividsolar** [w-okada/voice-changer#491]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9a.zip

### OS

Windows 10

### GPU

NVIDIA Geforce GTX 1660 SUPER

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

Everytime I start the voicechanger, it always says it fails to load an url ((node:12012) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED)

2nd problem is that when everytime I start the voicechanger it says ([Voice Changer] processing, ex: 'ServerDevice' object has no attribute 'performance') and ([Voice Changer] VC PROCESSING EXCEPTION!!! local variable 'sola_offset' referenced before assignment). And then soon after, the app just crashes (no error stack, no error message, no error name)

log:
MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Voice Changerを起動しています。
++[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

getSwitchValue1
getSwitchValue2 file
Preparing your application. Please wait...
(node:12012) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] model slot is changed -1 -> 4
................RVC
Preparing your application. Please wait...
(node:12012) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
2023-07-18 21:40:14 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-07-18 21:40:14 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-07-18 21:40:14 | INFO | faiss.loader | Loading faiss.
2023-07-18 21:40:14 | INFO | faiss.loader | Successfully loaded faiss.
[Voice Changer] [RVC] Creating instance
[Voice Changer] [RVC] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
Preparing your application. Please wait...
(node:12012) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
2023-07-18 21:40:17.7526114 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-07-18 21:40:17.7605932 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
Preparing your application. Please wait...
(node:12012) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[Voice Changer] Loading index...
Try loading... model_dir\4\added_IVF353_Flat_nprobe_1.index
GENERATE INFERENCER <voice_changer.RVC.inferencer.RVCInferencer.RVCInferencer object at 0x0000026715ABDCC0>
GENERATE EMBEDDER <voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000026762980190>
GENERATE PITCH EXTRACTOR <voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x00000267629801C0>
[Voice Changer] [RVC] Initializing... done
VoiceChanger Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu 0
[Voice Changer] [RVC] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
Preparing your application. Please wait...
(node:12012) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
2023-07-18 21:40:24.4062307 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-07-18 21:40:24.4155770 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] Loading index...
Try loading... model_dir\4\added_IVF353_Flat_nprobe_1.index
GENERATE INFERENCER <voice_changer.RVC.inferencer.RVCInferencer.RVCInferencer object at 0x0000026715A37FD0>
GENERATE EMBEDDER <voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x000002675C2B2800>
GENERATE PITCH EXTRACTOR <voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x000002675C2B2860>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings enableServerAudio 1
[Voice Changer][RVC]: update_settings serverInputDeviceId 1
[Voice Changer][RVC]: update_settings serverOutputDeviceId 7
[Voice Changer][RVC]: update_settings serverInputAudioGain 0.9
[Voice Changer][RVC]: update_settings serverOutputAudioGain 1.4
[Voice Changer][RVC]: update_settings f0Detector harvest
[Voice Changer][RVC]: update_settings serverReadChunkSize 256
[Voice Changer][RVC]: update_settings extraConvertSize 16384
[Voice Changer][RVC]: update_settings modelSlotIndex 1689684118004
[Voice Changer][RVC]: update_settings enableServerAudio 1
[Voice Changer][RVC]: update_settings serverInputDeviceId 1
[Voice Changer][RVC]: update_settings serverOutputDeviceId 7
[Voice Changer][RVC]: update_settings serverInputAudioGain 0.9
[Voice Changer][RVC]: update_settings serverOutputAudioGain 1.4
[Voice Changer][RVC]: update_settings f0Detector harvest
[Voice Changer][RVC]: update_settings serverReadChunkSize 256
[Voice Changer][RVC]: update_settings extraConvertSize 16384
Preparing your application. Please wait...
(node:12012) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[16060:0718/214207.252:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
[2023-07-18 21:42:52] connet sid : 0TWumhNqIxbY5KyyAAAC
[2023-07-18 21:42:52] connet sid : gMfDVmUJ7kW1hkNSAAAD
[Voice Changer] update configuration: serverAudioStated 1
[Voice Changer][RVC]: update_settings serverAudioStated 1
Devices:
  [Input]: ServerAudioDevice(kind='audioinput', index=1, name='Microphone (3- USB PnP Audio De', hostAPI='MME', maxInputChannels=2, maxOutputChannels=0, default_samplerate=44100.0, available_samplerates=[]) None
  [Output]: ServerAudioDevice(kind='audiooutput', index=7, name='CABLE Input (VB-Audio Virtual C', hostAPI='MME', maxInputChannels=0, maxOutputChannels=2, default_samplerate=44100.0, available_samplerates=[]) None
  [Monitor]: None None
Sample Rate:
  [Model]: 40000
  [Input]: 44100 -> True
  [Output]: 44100 -> True
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] processing, ex: 'ServerDevice' object has no attribute 'performance'
Devices:
  [Input]: ServerAudioDevice(kind='audioinput', index=1, name='Microphone (3- USB PnP Audio De', hostAPI='MME', maxInputChannels=2, maxOutputChannels=0, default_samplerate=44100.0, available_samplerates=[]) None
  [Output]: ServerAudioDevice(kind='audiooutput', index=7, name='CABLE Input (VB-Audio Virtual C', hostAPI='MME', maxInputChannels=0, maxOutputChannels=2, default_samplerate=44100.0, available_samplerates=[]) None
  [Monitor]: None None
Sample Rate:
  [Model]: 40000
  [Input]: 44100 -> True
  [Output]: 44100 -> True
[Voice Changer] warming up... generating sola buffer.
[Voice Changer] warming up... generating sola buffer.
[Voice Changer] VC PROCESSING EXCEPTION!!! local variable 'sola_offset' referenced before assignment
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 249, in on_request_sola
UnboundLocalError: local variable 'sola_offset' referenced before assignment

**Comment by w-okada** [comment]
did you extract the files to new folder ?

**Comment by HidekoHaruna** [comment]
try deleting the C:\Users\[username]\AppData\Roaming\voice-changer-native-client folder and then reinstall

**Comment by w-okada** [comment]
no res close

**Comment by bebrasyuak** [comment]
Please open
the following URL in your browser.
http: //<IP>:<PORT>/
In many cases, it will launch when you access
http: //127.0.0.1:18888/
any of the following URLs.
