### ISSUE TITLE
voice changer can't work

### ISSUE THREAD

**Issue by ElestialHD** [w-okada/voice-changer#493]
### Issue Type

Others

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9a.zip

### OS

windows 11 pro 

### GPU

gt 710 2gb

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pyTorch, ONNX

### Situation

C:\Program Files\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Voice Changerを起動しています。
++[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

getSwitchValue1
getSwitchValue2 file
Preparing your application. Please wait...
(node:6164) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] model slot is changed -1 -> 4
................RVC
Preparing your application. Please wait...
(node:6164) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[Voice Changer] [RVC] Creating instance
[Voice Changer] [RVC] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
Preparing your application. Please wait...
(node:6164) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[Voice Changer] Loading index...
Try loading... model_dir\4\added_IVF353_Flat_nprobe_1.index
GENERATE INFERENCER <voice_changer.RVC.inferencer.RVCInferencer.RVCInferencer object at 0x0000027699A1D9F0>
GENERATE EMBEDDER <voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x00000276B3F9F520>
GENERATE PITCH EXTRACTOR <voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x00000276B3F9F550>
[Voice Changer] [RVC] Initializing... done
VoiceChanger Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings enableServerAudio 0
[Voice Changer][RVC]: update_settings f0Detector crepe
[Voice Changer][RVC]: update_settings silentThreshold 0.00001
[Voice Changer][RVC]: update_settings gpu 0
[Voice Changer] [RVC] Initializing...
Preparing your application. Please wait...
(node:6164) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
Preparing your application. Please wait...
(node:6164) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[Voice Changer] Loading index...
Try loading... model_dir\4\added_IVF353_Flat_nprobe_1.index
GENERATE INFERENCER <voice_changer.RVC.inferencer.RVCInferencer.RVCInferencer object at 0x00000276B3F9FE20>
GENERATE EMBEDDER <voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x00000276B9BC6500>
GENERATE PITCH EXTRACTOR <voice_changer.RVC.pitchExtractor.CrepePitchExtractor.CrepePitchExtractor object at 0x00000276B9BC6560>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings modelSlotIndex 1689688925004
[Voice Changer][RVC]: update_settings enableServerAudio 0
[Voice Changer][RVC]: update_settings f0Detector crepe
[Voice Changer][RVC]: update_settings silentThreshold 0.00001
[Voice Changer][RVC]: update_settings gpu 0
[Voice Changer] [RVC] Initializing...
Preparing your application. Please wait...
(node:6164) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
Preparing your application. Please wait...
(node:6164) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[Voice Changer] Loading index...
Try loading... model_dir\4\added_IVF353_Flat_nprobe_1.index
GENERATE INFERENCER <voice_changer.RVC.inferencer.RVCInferencer.RVCInferencer object at 0x00000276B3F38D60>
GENERATE EMBEDDER <voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x00000276B9BC6FE0>
GENERATE PITCH EXTRACTOR <voice_changer.RVC.pitchExtractor.CrepePitchExtractor.CrepePitchExtractor object at 0x00000276B9BC6F80>
[Voice Changer] [RVC] Initializing... done
[4560:0719/160731.896:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
[2023-07-19 16:10:52] connet sid : EhM5Vbuf9NZP5IcUAAAC
[2023-07-19 16:10:52] connet sid : 64GKK3Rpf1daGO7rAAAD
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] warming up... generating sola buffer.

**Comment by computer1up** [comment]
A) You didn't say what the problem is and B) A GT710 is probably gonna be wayyy too weak to do anything meaningful, most likely your VRAM is already full. Even onboard graphics in modern CPU's or modern CPU's themselves are going to be faster probably.

**Comment by w-okada** [comment]
no res close
