### ISSUE TITLE
The playback duration of the recorded file via client and server is 0 seconds.

### ISSUE THREAD

**Issue by wolasimo** [w-okada/voice-changer#495]
### Issue Type

Bug Report, Question, Others

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.9a

### OS

Windows 10

### GPU

NVIDIA GeForce GTX 1060 6GB

### Clear setting

yes

### Sample model

yes

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX(cpu, cuda), PyTorch(cpu, cuda)

### Situation

The program works fine.
However, when I save the recording via client, server, it creates a wav file with 0 seconds saved in the Downloads file.
I think the file location is the problem... Any help would be really appreciated!!!

[IORecorder] delete old analyze file. C:\Users\USER\AppData\Local\Temp\tmpowoept08\tmp_dir\in.wav
[IORecorder] delete old analyze file. C:\Users\USER\AppData\Local\Temp\tmpowoept08\tmp_dir\out.wav
[Voice Changer] update configuration: recordIO 0
![455555](https://github.com/w-okada/voice-changer/assets/66228668/000d60c6-41d3-4554-813d-356ca354b436)

**Comment by w-okada** [comment]
Where did you downalod from ? Media player in the app?
And can you play the audio with the media player in the application?
If you can, download is responsible for media player. (maybe cache or something causes.)

**Comment by w-okada** [comment]
no res close
