### ISSUE TITLE
Extremely slow ai generation

### ISSUE THREAD

**Issue by PythonDeployer** [w-okada/voice-changer#497]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9.zip

### OS

Windows 10

### GPU

RTX 2060 SUPER

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

The GUI shows the response time is around 500ms, while it takes at least 4 seconds to get to my headphones, and also through VB-Cable it takes 4 second, chunks depend on what model im running but somewhere around 128-512,

it is clearly using my gpu but it barely uses any of it, it uses around 3gb of v-ram (of the 8 that my card has), and my cpu is almost constantly hammered at 100%, 

the logs dont show any reason it should be using cpu and when i turn on cpu processing it gets much slower.

**Comment by w-okada** [comment]
The time lag exists not only in the voice changer but also in VBCable and Bluetooth and etc. The response time displayed refers to the processing time it takes for voice conversion, and it does not measure the time required for other cables or the OS. Please read the tutorial.

**Comment by PythonDeployer** [comment]
> The time lag exists not only in the voice changer but also in VBCable and Bluetooth and etc. The response time displayed refers to the processing time it takes for voice conversion, and it does not measure the time required for other cables or the OS. Please read the tutorial.

My headphones are wired, and it's not vb-cable since when I set the audio mode to server, and use the monitoring feature directly to my headphones the delay is also huge, vb-cable barely adds maybe 20-30ms. Also the voice seems to cut off at the end a lot.

**Comment by w-okada** [comment]
dont use index

**Comment by PythonDeployer** [comment]
> dont use index

I don't use index, Ive also tried converting to onmx

**Comment by PythonDeployer** [comment]
i found some errors, in the logs, here are some:

`faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")`

`Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.`
