### ISSUE TITLE
Selecting any model crashes the app

### ISSUE THREAD

**Issue by kelvin-zhao** [w-okada/voice-changer#499]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.9a

### OS

MacOS 12.6.6

### GPU

None

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

ONNX

### Situation

Following the instructions, everything seems to be loaded, the UI is up, but when I tried selecting any of the 4 default models, the app crashes and I get the following message in terminal,
[Voice Changer] update configuration: modelSlotIndex 1689825338003
[Voice Changer] model slot is changed -1 -> 3
................RVC
Preparing your application. Please wait...
(node:5034) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED

**Comment by w-okada** [comment]
only this?
I have no idea.

**Comment by w-okada** [comment]
no res close
