### ISSUE TITLE
Respond and cutting & lagging

### ISSUE THREAD

**Issue by Eri35** [w-okada/voice-changer#500]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.8a

### OS

Windows 10

### GPU

RX 6600

### Clear setting

no

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

onxdirectML-cuda

### Situation

![image](https://github.com/w-okada/voice-changer/assets/139981798/5c69f07c-9ffb-4623-b4dd-7e4cc3bc86c7)

the respond time was too big and i dont seem to see that it's using my gpu only my cpu  barely using my gpu 

![image](https://github.com/w-okada/voice-changer/assets/139981798/63ce485d-9bb2-4717-bcb9-1e24a6a8d9cf)

**Comment by w-okada** [comment]
use dio not crepe

**Comment by Eri35** [comment]
Thank for responding it did work is there anything I can do to lower the respond time for it?

**Comment by w-okada** [comment]
I guess I should prepare the good GPU.
