### ISSUE TITLE
The operator 'aten::_weight_norm_interface' is not currently implemented for the MPS device.

### ISSUE THREAD

**Issue by Dreamail** [w-okada/voice-changer#501]
### Issue Type

Bug Report

### vc client version number

git checkout v.1.5.3.9a

### OS

macOS 14 M1

### GPU

none

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

No

**Comment by w-okada** [comment]
how to reproduce

**Comment by Dreamail** [comment]
Click Start, and the error comes out in the terminal.

**Comment by w-okada** [comment]
show log and share capture of the window

**Comment by w-okada** [comment]
no res close
