### ISSUE TITLE
The res delay is increasing all the time

### ISSUE THREAD

**Issue by ZerIing** [w-okada/voice-changer#503]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9a.zip

### OS

Windows 10

### GPU

Radeon RX 560D 4 gb

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

The res delay is increasing all the time. Because of this, the application does not work
![image](https://github.com/w-okada/voice-changer/assets/140087155/3c332082-b3e4-43c8-84bd-1b4012d9cb86)

Here is the log from the console

[log.txt](https://github.com/w-okada/voice-changer/files/12111503/log.txt)

**Comment by w-okada** [comment]
read tutorial.
