### ISSUE TITLE
Client wont work saying "Passthrough is not supported, GL is disabled, Angel is. while also crashing

### ISSUE THREAD

**Issue by Kingfrogos** [w-okada/voice-changer#504]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9a.zip

### OS

Windows 11

### GPU

NVIDIA GeForce RTX 2060

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

no

### Situation

I was trying to get the client to work but i noticed even after i waited and changed the settings nothing was changing on top of that in the logs i say this error saying Passthrough is not supported, GL is disabled, ANGEL is. And the client would crash everytime i messed with the input and output setting

**Comment by w-okada** [comment]
show log on terminal

**Comment by harun-ui** [comment]
![ggggg](https://github.com/w-okada/voice-changer/assets/140186810/3a35a727-dd43-4158-b1f0-d8e81c5d2641)

**Comment by w-okada** [comment]
there is no error.
show all log in terminal

**Comment by harun-ui** [comment]
![image](https://github.com/w-okada/voice-changer/assets/140186810/e1efe49a-0d1a-4079-93a7-c0cc4c7ceb46)

**Comment by harun-ui** [comment]
![image](https://github.com/w-okada/voice-changer/assets/140186810/295e3dc7-a409-4dc5-9ee8-dc7de621990d)
sudah saya tunggu,tapi tetap tidak berfungsi

**Comment by w-okada** [comment]
?? no error and no crash report.

**Comment by harun-ui** [comment]
aku mencoba download versi terbaru,bisa berjalan,tapi suaranya delay dan terputus-putus

**Comment by w-okada** [comment]
no res close
