### ISSUE TITLE
It doesnt work.

### ISSUE THREAD

**Issue by yutsu2** [w-okada/voice-changer#505]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9a

### OS

Windows 11

### GPU

NVIDIA GeForce GTX 1660 SUPER

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

 ONNX (cpu, cuda), PyTorch (cpu, cuda)

### Situation

So it worked at first but when i restarted my computer it stopped working, so i wanna know how do i make it to work again, Also it shows on terminal this:

![image](https://github.com/w-okada/voice-changer/assets/140125130/3b7136f4-55f3-4e4f-8e20-fedc73588b06)

**Comment by yutsu2** [comment]
Update: its working now for some reason.

**Comment by w-okada** [comment]
okey close
