### ISSUE TITLE
The delay *res* increases infinitely

### ISSUE THREAD

**Issue by ZerIing** [w-okada/voice-changer#506]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.9a.zip

### OS

Windows 10

### GPU

Radeon RX 560D 4 gb

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

ONNX (cpu, DirectML)  PyTorch (cpu, cuda)

### Situation

Hello again :) this time I definitely read the readme, downloaded the correct version, but this problem has not disappeared anywhere. The delay *res* increases infinitely
![image](https://github.com/w-okada/voice-changer/assets/140087155/fde9d354-b735-4fa0-9805-3f7d0819620e)

Here is the console log
[log.txt](https://github.com/w-okada/voice-changer/files/12114887/log.txt)

Help please

**Comment by w-okada** [comment]
read tutorial
