### ISSUE TITLE
When selecting Suppression 2 Voice changer is not picking up mic voice but it picks up voice after I turn it off

### ISSUE THREAD

**Issue by Justarandimmboi** [w-okada/voice-changer#507]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9a

### OS

Windows 10

### GPU

Aorus RTX 3080 Extreme 

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

Ive been using suppression 2 on versions 1.5.3.7 which picks up my voice fine. Ive switched to the latest update 1.5.3.9a and suppression two does not pick up my voice any more. 

I've tried messing with S. Threshold, doesn't fix the issue. 

Turning off supression 2 fixes the issue but I need it on to prevent keyboard and mouse noise. 

 Cheers

**Comment by w-okada** [comment]
same
https://github.com/w-okada/voice-changer/issues/449
