### ISSUE TITLE
Open error: is JACK server running?

### ISSUE THREAD

**Issue by AceVonLaura** [w-okada/voice-changer#510]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9a

### OS

WIndows 11

### GPU

RTX 3070 (mobile)

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

Open error: is JACK server running?
numpy\core\getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
numpy\core\getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
numpy\core\getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
numpy\core\getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Voice Changerを起動しています。
++[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

Open error: is JACK server running?
Preparing your application. Please wait...
(node:3364) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] model slot is changed -1 -> 7
................RVC
[Voice Changer] [RVC] Creating instance
[Voice Changer] [RVC] Initializing...
Preparing your application. Please wait...
(node:3364) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
GENERATE INFERENCER <voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x000001C546F4D930>
GENERATE EMBEDDER <voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x000001C57F6C2980>
GENERATE PITCH EXTRACTOR <voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x000001C57F6C33D0>
[Voice Changer] [RVC] Initializing... done
VoiceChanger Initialized (GPU_NUM:1, mps_enabled:False)
[Voice Changer][RVC]: update_settings serverReadChunkSize 48
[Voice Changer][RVC]: update_settings silentThreshold 0
[Voice Changer][RVC]: update_settings enableServerAudio 0
[Voice Changer][RVC]: update_settings extraConvertSize 4096
[Voice Changer][RVC]: update_settings gpu 0
[Voice Changer] [RVC] Initializing...
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
GENERATE INFERENCER <voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x000001C57F6C3BE0>
GENERATE EMBEDDER <voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x000001C57F6DC8E0>
GENERATE PITCH EXTRACTOR <voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x000001C57F6DD7E0>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings serverInputDeviceId 1
[Voice Changer][RVC]: update_settings serverOutputDeviceId 6
[Voice Changer][RVC]: update_settings serverAudioSampleRate 48000
[Voice Changer][RVC]: update_settings serverInputAudioGain 1
[Voice Changer][RVC]: update_settings serverOutputAudioGain 6
[Voice Changer][RVC]: update_settings modelSlotIndex 1689932922007
[Voice Changer][RVC]: update_settings serverReadChunkSize 48
[Voice Changer][RVC]: update_settings silentThreshold 0
[Voice Changer][RVC]: update_settings enableServerAudio 0
[Voice Changer][RVC]: update_settings extraConvertSize 4096
[Voice Changer][RVC]: update_settings gpu 0
[Voice Changer] [RVC] Initializing...
[Voice Changer] generate new embedder. (anyway)
Preparing your application. Please wait...
(node:3364) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[Voice Changer] Loading index...
GENERATE INFERENCER <voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x000001C57F6C3430>
GENERATE EMBEDDER <voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x000001C57F6DC5B0>
GENERATE PITCH EXTRACTOR <voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x000001C57F6DF460>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings serverInputDeviceId 1
[Voice Changer][RVC]: update_settings serverOutputDeviceId 6
[Voice Changer][RVC]: update_settings serverAudioSampleRate 48000
[Voice Changer][RVC]: update_settings serverInputAudioGain 1
[Voice Changer][RVC]: update_settings serverOutputAudioGain 6
[2023-07-21 19:15:53] connet sid : jJ8_8f99angDA9t7AAAC
[2023-07-21 19:15:53] connet sid : 6iDye-hqXexOaAyyAAAD
[18956:0721/191741.760:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
[2023-07-21 19:18:18] connet sid : 8Hakn-X6WJbUgO9VAAAF

**Comment by w-okada** [comment]
What is issue? clarify

**Comment by AceVonLaura** [comment]
I'm getting a couple of error messages when starting voice changer, and the console also runs more lines/attempts affecting my launch time on my device compared to my friend's devices, I'm asking if is there a possible solution for this error : 
-Open error: is JACK server running?
numpy\core\getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
numpy\core\getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
numpy\core\getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
numpy\core\getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.

-(node:3364) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED

**Comment by w-okada** [comment]
Could it be that your PC's environment settings are causing the issue? I'm afraid we can't handle it from our end.
