### ISSUE TITLE
Diffusion SVC

### ISSUE THREAD

**Issue by benc1221** [w-okada/voice-changer#512]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10

### OS

Windows 11

### GPU

RTX 4080

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

Diffusion SVC

### Model type

Bin

### Situation

do you know where the git hub repository is? so can train a diffusion svc model so i can test the quality between rvc and diffusion? i am quite interested in testing. i see the sample ones are using the bin file format.

**Comment by w-okada** [comment]
https://github.com/CNChTu/Diffusion-SVC
