### ISSUE TITLE
cant get it working with a laptop with rtx 3050

### ISSUE THREAD

**Issue by TrippyGolem35307** [w-okada/voice-changer#518]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9a

### OS

Windows 11

### GPU

Nvidia RTX3050 

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

not the issue

### Model type

not the issue

### Situation

I have a nvidia RTX 3050 Laptop GPU but i cant run the voice changer made for nvidia cards. Just the AMD thing. How can i use the one what is made for Nvidia?

**Comment by TrippyGolem35307** [comment]
I dont know if this one helps but i get this when i start it:
2023-07-21 22:27:28.8507197 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1641 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.

**Comment by TrippyGolem35307** [comment]
![image](https://github.com/w-okada/voice-changer/assets/42010746/8faaa6bc-ee3c-4a1a-9e53-acd82ab71408)

**Comment by w-okada** [comment]
error message said CUDA_PATH is wrong. fix it.

**Comment by TrippyGolem35307** [comment]
im downloading cuda toolkit 12.2 right now

**Comment by TrippyGolem35307** [comment]
do i need the local or the network version of cuda?
or can i download and install both?

**Comment by TrippyGolem35307** [comment]
i still get that message :/

**Comment by w-okada** [comment]
error message said CUDA_PATH is wrong. fix it.

**Comment by TrippyGolem35307** [comment]
i fixed it in "enviroment variables"

**Comment by TrippyGolem35307** [comment]
![image](https://github.com/w-okada/voice-changer/assets/42010746/131f7722-b7a2-4cbb-b2b7-697c7486878a)

**Comment by TrippyGolem35307** [comment]
what am i doing wrong?

**Comment by TrippyGolem35307** [comment]
DirectML version is working fine but the nvidia one is not :/

**Comment by TrippyGolem35307** [comment]
i hope these are helping.
![image](https://github.com/w-okada/voice-changer/assets/42010746/86ad64a1-929a-414a-a5da-1ee325e0bccc)
![image](https://github.com/w-okada/voice-changer/assets/42010746/2203d5ec-5d5c-489e-9246-771fa0873df6)

**Comment by TrippyGolem35307** [comment]
![image](https://github.com/w-okada/voice-changer/assets/42010746/05a14c0c-f46a-47c4-8c85-b37580adf8ac)

**Comment by TrippyGolem35307** [comment]
i think i have everything

**Comment by w-okada** [comment]
Sorry, I am not onnxruntime developper. please consult with them.

![image](https://github.com/w-okada/voice-changer/assets/48346627/d79d506f-3898-45a5-b315-e47b9997627d)
