### ISSUE TITLE
(node:3632) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by aviatiq** [w-okada/voice-changer#519]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10

### OS

Windows 10

### GPU

Intel Arc A750 8GB ASROCK

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

MMVC

### Model type

pyTorch CUDA GPU

### Situation

It just refuses to connect. I've tried different wifis, I've turned off my anti-virus, I excluded it on my Firewall, etc.
![image](https://github.com/w-okada/voice-changer/assets/65436219/abb76f07-f103-4eef-9c2b-c76ab7f0c59b)

**Comment by TrippyGolem35307** [comment]
i have this issue too
![image](https://github.com/w-okada/voice-changer/assets/42010746/0f883175-0f34-49fc-b5f0-730328aacb9f)
![image](https://github.com/w-okada/voice-changer/assets/42010746/08fb15e5-e12c-4db3-a8f2-115dfdc11c51)

**Comment by aviatiq** [comment]
> i have this issue too

Hey seems to be fixed when I re-installed Windows 11 on my other drive! I think something in my Windows 10 drive is causing some sort of issue.
![image](https://github.com/w-okada/voice-changer/assets/65436219/00c5071f-b30c-4dfe-ac44-f45b2cd00007)

**Comment by aviatiq** [comment]
Update: Nope. It happened again. Why? I literally don't know.
![image](https://github.com/w-okada/voice-changer/assets/65436219/a9d0b506-0ca1-404e-901f-7c016298f8ef)

**Comment by aviatiq** [comment]
Ok, so I followed someone's idea that the settings were corrupt and not working, so I deleted the sample and the settings, then whenever I select a new model, it just gives me this now:
![image](https://github.com/w-okada/voice-changer/assets/65436219/eee308cd-6824-40a7-ae88-58404d07f52f)

**Comment by w-okada** [comment]
I believe I won't be able to respond efficiently if actions are taken that I did not anticipate. Please reinstall it again.

**Comment by aviatiq** [comment]
> I believe I won't be able to respond efficiently if actions are taken that I did not anticipate. Please reinstall it again.

If you meant for me, it didn't work. But it did work when I deleted the samples and settings JSON files (However it crashes when I try selecting a model), why's that?

**Comment by w-okada** [comment]
I'm sorry, but I'm not quite understanding the situation. Could you open the issue again and clear things up? Please refrain from adding any new work that may create further confusion.
