### ISSUE TITLE
Select vc missing

### ISSUE THREAD

**Issue by VCisNice** [w-okada/voice-changer#521]
As the title said, select vc doesn't show up. I tried tinkering with stuff but to no avail. I really wanna try this out but this problem is confusing me so any help would be appreciated

![image](https://github.com/w-okada/voice-changer/assets/140230526/ef47813c-4810-40df-8187-dc1584937091)

**Comment by w-okada** [comment]
use issue template

**Comment by VCisNice** [comment]
> use issue template

umm how do I do that? sorry I'm not really used to this yet
