### ISSUE TITLE
im facing with a error [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1641 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.

### ISSUE THREAD

**Issue by sepulturaqwe** [w-okada/voice-changer#528]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10.zip

### OS

Windows 11 Pro

### GPU

RTX 3050

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

![image](https://github.com/w-okada/voice-changer/assets/74799490/5e6fdaee-888b-470c-b373-7ced013ff656)

im facing with this error. i used this program 2 week ago, but after new versions, i can't use older versions too now. is there solution for this issue?

**Comment by sepulturaqwe** [comment]
i tried all versions, but im getting same issues.

**Comment by w-okada** [comment]
I dont know, but perhaps you can not use unicode in path.

https://github.com/microsoft/onnxruntime/issues/13499

**Comment by sepulturaqwe** [comment]
I changed the path, thank you for your help!

**Comment by w-okada** [comment]
Okey,
