### ISSUE TITLE
The gui wont download.

### ISSUE THREAD

**Issue by Kakakasilly** [w-okada/voice-changer#530]
### Issue Type

Others

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.9

### OS

Windows 11

### GPU

Geforce RTX 3060 Ti

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

?

### Situation

I was able to go to the gui but it wouldent install it.

**Comment by w-okada** [comment]
Please describe detail,

**Comment by Kakakasilly** [comment]
So the when i open the gui to download the voice changer it self it opens for a milisecond then closes so i dont know what is wrong
