### ISSUE TITLE
Mac - M1 Pro [Voice Changer] matplotlib is dummied

### ISSUE THREAD

**Issue by AkshayanSingla** [w-okada/voice-changer#532]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.10

### OS

macOS Ventura (13.4.1)

### GPU

None

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX CPU

### Situation

Executing `startHttp.command` results in the following error:
<img width="970" alt="Screenshot 2023-07-22 at 21 49 06" src="https://github.com/w-okada/voice-changer/assets/79436281/01f106a6-d180-47e8-9e81-9a83f9f6fe05">

Older version(MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.9a) did load, but then I encountered the following error(I did go to #339 but I didn't exactly understand what I'm supposed to do)
<img width="697" alt="Screenshot 2023-07-22 at 21 50 11" src="https://github.com/w-okada/voice-changer/assets/79436281/7ad01233-1415-4dfb-a74b-3fd4f36cbe59">

Any help would be appreciated :)

**Comment by Ghostkwebb** [comment]
Refer to (this)[https://github.com/w-okada/voice-changer/issues/516]

**Comment by Ghostkwebb** [comment]
Refer to [this](https://github.com/w-okada/voice-changer/issues/516)

**Comment by AkshayanSingla** [comment]
> Refer to [this](https://github.com/w-okada/voice-changer/issues/516)

Thanks for your reply :)
I did try to use 1.5.3.9, but then encountered [this bug](https://github.com/w-okada/voice-changer/issues/516#issuecomment-1646514164) (the same bug as you).

**Comment by w-okada** [comment]
OK same issue as https://github.com/w-okada/voice-changer/issues/516#issuecomment-1646514164
close
