### ISSUE TITLE
When switching gpus 3090 to 3070 load is still on the 3090

### ISSUE THREAD

**Issue by Picklesnickles420** [w-okada/voice-changer#533]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10

### OS

win 10

### GPU

3090, 3070

### Clear setting

no

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

tried multiple

### Situation

when selecting gpuid 1 for the 3070 it still defaults the workload to the 3090, i have also tried editing the nvidia gforce exp to have the 3070 be the default cuda processor for the programs server/client and still effect. my gpu ids is as follow id_0 is the 3090 and id_1 is the 3070 the terminal widow shows it switching gpus but the resource monitor proves otherwise. let me know if theres anything else i can provide or try to help solve this issue.

**Comment by w-okada** [comment]
GPU ID??
GUI shows name of gpu.
I am confusing.
