### ISSUE TITLE
CUDA Version not allowing me to use NVIDIA GPU

### ISSUE THREAD

**Issue by FestiveGears** [w-okada/voice-changer#535]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.9a.zip

### OS

Windows 11

### GPU

NVIDIA GeForce RTX 2070

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

f0

### Situation

So the voice changer only uses my CPU to run when I want it to use my GPU but instead of the usual dropdown menu for the GPU I have buttons:
![Proof](https://github.com/w-okada/voice-changer/assets/87826601/adcf9fd5-cb58-46f5-bd5e-024aba4d1fa7)

I'm not sure if this is a rendering bug or if my GPU isn't supported but if anyone has answers or a fix that would be greatly appreciated.

I'm on version 1.5.3.9a as of right now (Also I tried switching the f0 Det. to crepe_full to see if it changed anything but it still runs on my cpu and makes using it in games impossible)

**Comment by w-okada** [comment]
dont use index if your pc is not good.

**Comment by FestiveGears** [comment]
It's not that its bad (granted it is not great) but its just that it doesn't show an option to use my GPU instead of my CPU which I've seen in any videos I have seen for setup and use. My pc definitely isn't good but the voice changer still works really well its just that it uses my CPU and I'd like to use my GPU instead. Either way thank you for an amazing program!

**Comment by w-okada** [comment]
if you use nvidia, try ONNX(cpu,cuda) version

**Comment by FestiveGears** [comment]
ohhhhhh I see what the likely case is, I wont be able to tell for a while since I need to download it but I think when I downloaded it I wasn't looking at the file names on hugging face and I downloaded the file that has cpu in the name, now that I've taken another look I see there's one with GPU. That should allow me to run the voice changer off my GPU correct? Thanks for the help by the way

**Comment by FestiveGears** [comment]
Actually I now see that I downloaded the directML version by mistake so that would likely explain it. Thanks again, if you didn't help out I likely never would've noticed!

**Comment by w-okada** [comment]
ok resolved.
