### ISSUE TITLE
It is using my cpu when I want it to use my gpu.

### ISSUE THREAD

**Issue by Someone76p** [w-okada/voice-changer#536]
### Issue Type

Bug Report, Question

### vc client version number

v.1.5.3.10

### OS

Windows 11

### GPU

RTX 4060

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

MMVC v.1.5.x, MMVC v.1.3.x, so-vits-svc 4.0, RVC, DDSP-SVC, Diffusion-SVC

### Model type

ONNX(cpu,cuda), PyTorch(cpu,cuda)

### Situation

I switched it to use my gpu but when I start it it uses my cpu and then my cpu usage goes up to 100% and my gpu stays at like 10%. It's using my cpu instead of my gpu when I want it to use my gpu.

**Comment by Someone76p** [comment]
It also is very laggy even when I use the lowest CHUNK

**Comment by w-okada** [comment]
1. Use dio
2. Dont use index.

**Comment by Someone76p** [comment]
> * Use dio
> * Dont use index.

It’s still lagging like crazy and using up all the cpu

**Comment by w-okada** [comment]
show me log in the terminal and share screen shot of the window.

**Comment by Someone76p** [comment]
> show me log in the terminal and share screen shot of the window.
![Screenshot 2023-07-23 125424](https://github.com/w-okada/voice-changer/assets/136948036/85a76b24-4eb1-4768-90c7-755cb9bc2fae)

**Comment by w-okada** [comment]
???
Have you read the tutorial? 
Why is the chunk size 8? I can't understand why. Did my tutorial mislead you?
Please let us know what we could improve for the future.

**Comment by w-okada** [comment]
no res close
