### ISSUE TITLE
Multi GPUs performance test

### ISSUE THREAD

**Issue by hpx502766238** [w-okada/voice-changer#537]
### Issue Type

Bug Report, Question

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.10

### OS

Windows 11

### GPU

RTX 3060 6G Laptop,AMD Radeon(TM) Graphics[R7 5800H]

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

Diffusion-SVC

### Model type

f0 ,pyTorch

### Situation

GPU0 RTX3060,GPU1 AMD Radeon Graphics
CPU:AMD R7 5800H
My computer's test result,using the ‘Diffusion-SVC 初期 Sample model’:
1.F0 Detection:dio, GPUID:0  result:
【CPU】 40% 【GPU0】CoreUsage:40%,VRAMUsage:3GB 【GPU1】Usage:0%
2.F0 Detection:harvest result:
【CPU】 50% 【GPU0】CoreUsage:40%,VRAMUsage:3GB 【GPU1】Usage:0%
3.F0 Detection:crepe result:
【CPU】 50% 【GPU0】CoreUsage:60%,VRAMUsage:3.2-3.8GB 【GPU1】Usage:0%
4.F0 Detection:rmvpe result:
【CPU】 30% 【GPU0】CoreUsage:50%,VRAMUsage:3.6-3.7GB 【GPU1】Usage:0%
5.F0 Detection:dio, GPUID:1  result:

【CPU】 40% 【GPU0】CoreUsage:0%,VRAMUsage:2.2GB 【GPU1】CoreUsage:45%,VRAMUsage:0.2GB
6.F0 Detection:harvest, GPUID:1  result:
【CPU】 50% 【GPU0】CoreUsage:0%,VRAMUsage:2.2GB 【GPU1】CoreUsage:41%,VRAMUsage:0.2GB
7.F0 Detection:crepe, GPUID:1  result:
【CPU】 42% 【GPU0】CoreUsage:50%,VRAMUsage:2.2-2.8GB 【GPU1】CoreUsage:46%,VRAMUsage:0.2GB
8.F0 Detection:rmvpe, GPUID:1  result:
【CPU】 45% 【GPU0】CoreUsage:15%,VRAMUsage:2.6-2.7GB 【GPU1】CoreUsage:41%,VRAMUsage:0.2GB

**The problem is, although I chose GPU1, the program still uses about 2GB VRAM in GPU0. Is the 2GB for the voice model? Why not load all of them to GPU1?
Another question, does the 'F0 Detection' support choosing GPU? It seems to use GPU0 all the time.**

**Comment by hpx502766238** [comment]
In addition, sometimes the sound is choppy when I using GPU1,although the delay(res) is much less than chunk.I suspect it's caused by the model being loaded onto different GPUs.

**Comment by w-okada** [comment]
In v.1.5.3.10, model is loaded on gpu0 at first. Then, the app changes the gpu to selected one.
As you've noted, this isn't very efficient, so we plan to correct it in the next release.
But, the VRAM is released when changed to new gpu in program. I believe it's just that the garbage collection isn't running, in my opinion.

**Comment by w-okada** [comment]
> In addition, sometimes the sound is choppy when I using GPU1,although the delay(res) is much less than chunk.I suspect it's caused by the model being loaded onto different GPUs.

I couldn't reproduce it. This may also depends on the bus or something in your PC

**Comment by w-okada** [comment]
modified model loading process. try v.1.5.3.10a

**Comment by w-okada** [comment]
no res close
