### ISSUE TITLE
Voice Changer completely Disabled Audio Input

### ISSUE THREAD

**Issue by Manisa8338** [w-okada/voice-changer#538]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10.zip

### OS

Windows 10

### GPU

RX 560

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

MMVC

### Model type

Cannot use

### Situation

I Run the Start_http bat file, wait for it to install its stuff and when I wanted to Test the Voice Changer I noticed there is this Error: "Handshake Failed" After a while adjusting my Network I again started to test if it works and now I noticed I have no Audio Input in windows anymore, I Uninstalled and reinstalled the app, (Downloading the files again right now), Restarted my PC, Unpluged and pluged my Microphone, Nothing Works

**Comment by w-okada** [comment]
Any logs on terminal??

**Comment by Manisa8338** [comment]
> Any logs on terminal??

![image](https://github.com/w-okada/voice-changer/assets/87316948/49117a27-fa34-46d0-894a-57faef613f33)
the app does not pick up any audio from my mic since the app disabled my main input
