### ISSUE TITLE
Intel Arc A750 8GB is supported or not

### ISSUE THREAD

**Issue by aviatiq** [w-okada/voice-changer#540]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10

### OS

Windows 10 &  Windows 11

### GPU

Intel Arc A750 8GB

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

MMVC

### Model type

pyTorch CUDA GPU

### Situation

This is a follow-up since the dev for some apparent reason closed my issue as "completed'' when it isn't.

Very simple:
- Windows 10 gives me this error on the first attempt: (node:3632) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED 
- Windows 11 (Fresh install as well), however, does not give the error on the first attempt, but after re-launching it, it gives me the same error. (node:3632) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED 
- Antivirus (Windows Defender) and firewall already whitelisted but still no changes.
- I have also tried different wifis, different protocols, etc.. Nothing works.
- However, using someone else's solution, which was to delete the samples and the settings JSON files, I was able to get the GUI up but I can't change or pick the models since it just crashes the GUI.

![image](https://github.com/w-okada/voice-changer/assets/65436219/29c406e3-1072-4507-9bdc-29b92a68507a)

**Comment by w-okada** [comment]
Your gpu is not nvidia's. I have no idea of your gpu. but try directml version.

**Comment by Jason2464** [comment]
I have a gtx 1060 6gb,why do i get the error,and what do you mean by directml version where is that?

**Comment by w-okada** [comment]
@Jason2464 
I can not answer your question because I don’t know your situation.

**Comment by Jason2464** [comment]
thank you for replying so fast,I have a problem where it says device detection error fallback to cpu,and it only opens sometimes+if it does open,nothing seems to work and i dont see my gpu anymore

**Comment by w-okada** [comment]
@Jason2464
please open new issue. your conversion make chaos to @Jason2464's one.

**Comment by w-okada** [comment]
Maybe your gpu is not supported by onnxruntime.
And corei3 is lowend cpu. I think it probably doesn't have enough performance.

**Comment by aviatiq** [comment]
> Maybe your gpu is not supported by onnxruntime. And corei3 is lowend cpu. I think it probably doesn't have enough performance.

I3-12100F is still pretty decent to run stuff like Stable Diffusion. And yeah, I doubt that my GPU is able to run ONXRuntime, is AMD supported? I can pop out my RX580 and see if it works...

**Comment by w-okada** [comment]
Some AMD GPU is supported, but other is not.

for example, It is reported that RX5600XT is supported. I have no info of your gpu.

https://www.youtube.com/watch?v=FUTa7RnlV3w

**Comment by aviatiq** [comment]
> Some AMD GPU is supported, but other is not.
> 
> for example, It is reported that RX5600XT is supported. I have no info of your gpu.
> 
> https://www.youtube.com/watch?v=FUTa7RnlV3w

Yup, no changes. It still has the same error on both XML and CUDA versions.

**Comment by TeenyGlobe** [comment]
i have a rx 6600 and it is also starting up but refuses to connect.

**Comment by TeenyGlobe** [comment]
this isa what i get and it just keeps on going

(node:11004) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Preparing your application. Please wait...

**Comment by aviatiq** [comment]
> this isa what i get and it just keeps on going
> 
> (node:11004) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED Preparing your application. Please wait...

Try the DirectXML version. It may show that then it'll request the firewall to accept permissions (Only on the first install). Also, it might show the error serval times before it actually works. If it's your 2nd time, open the folder and delete the settings and samples JSON files.

**Comment by w-okada** [comment]
onnxruntime matter. close
