### ISSUE TITLE
Is Server a valid useable option?

### ISSUE THREAD

**Issue by Rexlambo** [w-okada/voice-changer#542]
### Issue Type

Question

### vc client version number

MMVCServerSIO v.1.5.3.9a

### OS

Windows 10

### GPU

2060

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

Any model

### Situation

Okay so so when i use  the "server" option for Audio, the models very clear and has littlie latency but what i realized is that it can be used for some time but after i close the program and open it back up the models sound very muffled and incoherent just wondering why that is?

**Comment by w-okada** [comment]
I have no idea. I have never met such situation.

**Comment by w-okada** [comment]
close
