### ISSUE TITLE
How do I launch MMVCServerSIO with voice changing ON by DEFAULT?

### ISSUE THREAD

**Issue by YeloPartyHat** [w-okada/voice-changer#543]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cudov.1.5.3.9

### OS

Windows 10

### GPU

GTX 1660

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

MMVCServer ONNX GPU-CUDA V1.5.3.9

### Situation

How do I get the voice changer to start on launch? I want option 3 in the image below to start in the _On_ position.

![labelled interface image](https://user-images.githubusercontent.com/48346627/250271355-883b296e-e5ca-4571-8fed-dcf7495ebb92.png)

To be clear, I just want to have the `http_start.bat` file launch the UI with the voice changer _On_.

**Comment by w-okada** [comment]
currently you can not.

**Comment by w-okada** [comment]
close

**Comment by thevolvoxo-arch** [comment]
hi dowload link where tank you
