### ISSUE TITLE
Docker Image isn't working

### ISSUE THREAD

**Issue by sweetbbak** [w-okada/voice-changer#544]
### Issue Type

Bug Report

### vc client version number

v.1.5.3.10

### OS

Arch Linux

### GPU

AMD RX 6700

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC/None

### Model type

None

### Situation

Running the docker container (DOCKER_IMAGE=dannadori/vcclient:20230710_031922) using the included "start_docker.sh" with GPU set to "off" will start the server but there is an unknown error with no extra info. 

There was also an error with "hostname -I" being an invalid option and testing it out it does not seem to be a valid option. hostname -i outputs 127.0.0.1 and I'm guessing that is what is wanted for EX_IP under both docker run commands.

![image](https://github.com/w-okada/voice-changer/assets/75046310/53350463-080f-4f9a-80da-c6845508e7f5)

Then the server opens, I open the webpage (which has an invalid certificates warning for some reason) and I see the above. Clicking either button does nothing. It also needs to redownload the models everytime that it is ran which seems wrong to me. Any advice?

**Comment by sweetbbak** [comment]
Im also having this exact same issue when using a venv or conda environment and running the server

**Comment by w-okada** [comment]
Arch linux is not supported officially. 

Disscuss in this thread. I would greatly appreciate it if you could contribute.

https://github.com/w-okada/voice-changer/issues/377
