### ISSUE TITLE
ONNXRuntime DirectML failed to load model.

### ISSUE THREAD

**Issue by FoxLust** [w-okada/voice-changer#545]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.10

### OS

Windows 10 22H2

### GPU

AsRock RX 590 GME 8GB

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX DirectML

### Situation

The Aplication start fine only the first time it launch, if close and try re open the app it will crash until you delete the whole folder and extrack from the zip and download again it will work, the bug is consistent.

1. Extrack .zip
2. run start_http.bat
3. downloading the necessary package
4. GUI Launch and GPU Detected and Voice Change work properly
5. Close the app
6. Try to ReLaunch
7. Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
8. delete the whole folder

Repeat from step 1 and it will work only the first time launch

I Tried to see if another aplication use the port 18888 using TCPView, only Voice Changer using that port

![Cuplikan layar 2023-07-24 104816](https://github.com/w-okada/voice-changer/assets/101542497/bdd8ec0b-ea48-4069-8832-21ae0cb65805)

My PC Spec : 
Windows 10 22H2 (Build OS 19045.2985)
AsRock RX 590 GME 8GB (Driver : AMD Adrenaline 23.5.2)
Intel Core I5 4590
12 GB RAM DDR3 1600MHz

**Comment by w-okada** [comment]
I have no idea what the cause is.

Could you try deleting the folders and files and restarting when a problem occurs to see what happens?
(1) the model_dir (folder)
(2) pretrain (folder)
(3) stored_setting.json (file)

**Comment by FoxLust** [comment]
delete stored_setting.json make the app launch only one time, the next time it launch still make the same error

**Comment by FoxLust** [comment]
Only delete stored_setting.json make the app launch again, model_dir and pretrain do not effect the bug. but still launch one time only, the next time it launch make the same error and need to delete stored_setting.json

**Comment by ChinHongTan** [comment]
Tested on v.1.5.3.9, v.1.5.3.9a, v.1.5.3.7, v.1.5.3.6a, v.1.5.3.6, v.1.5.3.5, v.1.5.3.5a on M2 MacBook Pro.
All with the same error.

**Comment by atrutlebtw** [comment]
Yep same problem on MacBook M1 Pro with 16 Gb ram

**Comment by TeenyGlobe** [comment]
i keep on getting this even when i move it to other drives or reinstal it. please give me a solution.

getSwitchValue1
getSwitchValue2 file
[2572:0725/143941.654:ERROR:logging.cc(144)] Failed to init logging: Access is denied. (0x5)
[0725/143941.717:ERROR:logging.cc(144)] Failed to init logging: Access is denied. (0x5)
[0725/143941.728:ERROR:logging.cc(144)] Failed to init logging: Access is denied. (0x5)
[0725/143941.745:ERROR:logging.cc(144)] Failed to init logging: Access is denied. (0x5)
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[0725/143944.128:ERROR:logging.cc(144)] Failed to init logging: Access is denied. (0x5)
Preparing your application. Please wait...
(node:2572) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
[0725/143945.163:ERROR:logging.cc(144)] Failed to init logging: Access is denied. (0x5)
Preparing your application. Please wait...

**Comment by IndraTensei** [comment]
> I have no idea what the cause is.
> 
> Could you try deleting the folders and files and restarting when a problem occurs to see what happens? (1) the model_dir (folder) (2) pretrain (folder) (3) stored_setting.json (file)

https://stackoverflow.com/questions/75004076/electron-failed-to-load-url-http-localhost3000-main-window-with-error-err

**Comment by w-okada** [comment]
@FoxLust 

I conducted some research, but in the end, wasn't able to discern much. However, I think there is no issue with the data or basic processing if it works by deleting the stored_setting.json. I suspect an error occurs due to the timing of model loading specific to onnxruntime-directML. 

In the next version, we plan to add a process to abort the loading when an exception occurs during the model load. While this doesn't directly solve the problem, it will eliminate the need to delete the json file every time.

**Comment by w-okada** [comment]
try v.1.5.3.10b

**Comment by FoxLust** [comment]
can you mirror 1.5.3.10b to Hugging face? google drive limit so i cant test

**Comment by w-okada** [comment]
uploaded.

**Comment by IndraTensei** [comment]
> uploaded.
![image](https://github.com/w-okada/voice-changer/assets/69427966/af784dc0-1797-4a73-9b1e-ad1446c70d06)
Tried the 1.5.2.10b,1.5.2.10a and 1.5.2.10 versions gives the same error

**Comment by w-okada** [comment]
no res close
