### ISSUE TITLE
Voice sounds diff in discord than obs recording

### ISSUE THREAD

**Issue by Keicho2** [w-okada/voice-changer#546]
### Issue Type

Bug Report, Question

### vc client version number

.9

### OS

Windows

### GPU

3090 desktop pc

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

yes

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

Rvc

### Model type

Idk

### Situation

Hello. I did set up my voice with obs recording till I liked it, but the voice in discord seems to be diff, not as good. I wanted know if there's a work around to get my voice sound the same.

Thanks

**Comment by w-okada** [comment]
I am not discord engineer. So I have no idea.

But This YouTube video might be helpful for you.

https://www.youtube.com/watch?v=r-pe804ky-Y


I don't understand any more than this.

**Comment by w-okada** [comment]
no res close
