### ISSUE TITLE
GPU showing as cpu 1 2 3???

### ISSUE THREAD

**Issue by senzata** [w-okada/voice-changer#548]
### Issue Type

Question

### vc client version number

 MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.10a.zip

### OS

Windows 10

### GPU

RTX 2060

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

MMVC

### Model type

the pre downloaded ones

### Situation

uh yteah i cant see my gpu there even though im usingf a RTX 2060

**Comment by w-okada** [comment]
directML version show so. It is not bug. If you want to show the GPU name, use cuda version.

**Comment by w-okada** [comment]
no res close
