### ISSUE TITLE
Key Error: useIndex

### ISSUE THREAD

**Issue by Iqmalhakim** [w-okada/voice-changer#549]
### Issue Type

Bug Report, Others

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10a

### OS

windows 11

### GPU

GTX 1660 ti

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

 get error when try to download sample voice 
 
 paramDict {'voiceChangerType': 'RVC', 'slot': 6, 'isSampleMode': True, 'sampleId': 'KikotoKurage_o', 'files': [], 'params': {'rvcIndexDownload': True}}
[Voice Changer] sample download.... LoadModelParams(voiceChangerType='RVC', slot=6, isSampleMode=True, sampleId='KikotoKurage_o', files=[], params={'rvcIndexDownload': True})
[Voice Changer] post_load_model ex: 'useIndex'
Traceback (most recent call last):
  File "restapi\MMVC_Rest_Fileuploader.py", line 92, in post_load_model
  File "voice_changer\VoiceChangerManager.py", line 123, in loadModel
  File "downloader\SampleDownloader.py", line 31, in downloadSample
  File "downloader\SampleDownloader.py", line 112, in _downloadSamples
KeyError: 'useIndex'

**Comment by w-okada** [comment]
Okey, I could reproduce. I’ll fix it in next release.
Thank you!

**Comment by w-okada** [comment]
new version is released. try v.1.5.3.10b

**Comment by w-okada** [comment]
no res close
