### ISSUE TITLE
amd gpu support

### ISSUE THREAD

**Issue by soggysocks9** [w-okada/voice-changer#550]
### Issue Type

Question

### vc client version number

n/a

### OS

windows 11

### GPU

rx 5500xt

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

just can't get it to show my gpu and was wondering which version to install

**Comment by w-okada** [comment]
directml

see https://github.com/w-okada/voice-changer/issues/410
