### ISSUE TITLE
dont have model_dir folder after launching start http

### ISSUE THREAD

**Issue by latifsvs** [w-okada/voice-changer#551]
### Issue Type

Bug Report, Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10a

### OS

Windows 10

### GPU

GTX 1080

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX Cuda

### Situation

Cant start after running the start http, im not an IT guy so I cant pinpoint what's wrong with it. things that I notice are:

- its always say ERR_Connection_refused
- seems i cant find the model_dir files after exracting and running the start http
- i got [Voice Changer] matplotlib is dummied

here my screenshot after i run the start http

![Screenshot (4)](https://github.com/w-okada/voice-changer/assets/140201498/02e3c26e-e14f-493e-a40a-41583e4d65b3)

**Comment by w-okada** [comment]
App cannot access to the web server. Check your network setting.

**Comment by latifsvs** [comment]
what do i do with the network setting? should i change the dns or using vpn or something else?

**Comment by w-okada** [comment]
sorry i have no idea about your network configuration. please consult with administrator.

**Comment by w-okada** [comment]
no res close
