### ISSUE TITLE
Voice changer crashes all other programs and drivers.

### ISSUE THREAD

**Issue by Hai-L9** [w-okada/voice-changer#552]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10a.zip

### OS

Windows 11

### GPU

3090

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

When running alongside other GPU intensive programs (Like Virtual Reality titles and other Tripple A games) The Voice Changer will crash during points of high GPU memory use. All other programs using the GPU and occasionally the nvidia graphics driver will also crash.

![d40c4d48d9a190b3266399d545ece1f9](https://github.com/w-okada/voice-changer/assets/94766501/30241563-47cd-4acb-be0b-01a8d09e7f23)

Note that VC runs fine for several minutes before encountering the crash.

**Comment by FelipeCODX** [comment]
I hava the same problem, but I have a RTX 4090. In my case the game is crashing with lots of VRAM to spare.

**Comment by beeforbacon** [comment]
Did you ever figure this out? Having same issue. 64gb ram 13900k rtx strix 4090

**Comment by Hai-L9** [comment]
> Did you ever figure this out? Having same issue. 64gb ram 13900k rtx strix 4090

Yes, increasing the size of my Windows paging file seems to have solved this issue.
