### ISSUE TITLE
Increasing Model Slots

### ISSUE THREAD

**Issue by UredNuubjuz** [w-okada/voice-changer#554]
### Issue Type

Feature Request

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10a.zip

### OS

Windows 10 home

### GPU

RTX 3090

### Clear setting

no

### Sample model

yes

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

pyTorch, ONNX

### Situation

This Question was allready asked but the Issue was closed: https://github.com/w-okada/voice-changer/issues/360

The answer was this:
"The reason why we shouldn't increase the number of slots is that we can already anticipate that it will involve a lot of transition work if the version changes. If someone could create a transition tool, that might change the situation.

Unless a solution to this issue becomes visible, we will not be planning to increase the number of slots."

I am not sure what you have planned for the existing 9 Models in terms of Transition but my Suggestion would be this:
Give People the Option to upload as many as they want but mark them as a possible Loss of some sort. For example you mark them with a small "X" or "!" and when you place your cursor on it, a little text box pops up that says: "This Model may not be transitioned for the next Update". This does a couple of Things. First, People know that they may have to upload the same Models again. Second you give People the Option to choose for themselfs. Lets say that someone has 100 Models. Its basically on him to upload this again. I dont think People are mad in the Case it would not transition automatically because they know it beforehand. And third, We dont have to upload Models again and again (in the current Version) to simply change to another Model.

Anyways this is just a Suggestion.

**Comment by w-okada** [comment]
I'll think about it for a moment.

**Comment by w-okada** [comment]
increase to 100 or 200 in next release

**Comment by UredNuubjuz** [comment]
thanks, thats amazing, the more the better…

**Comment by w-okada** [comment]
try v.1.5.3.11

**Comment by TobyBlessing** [comment]
> increase to 100 or 200 in next release

I have filled up all 200 available slots, but still plenty more voice models I want to add. Is there a way to manually increase the amount of slots?
