### ISSUE TITLE
GPU not showing

### ISSUE THREAD

**Issue by GawrShizu** [w-okada/voice-changer#555]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10a.zip

### OS

Windows 10

### GPU

RX570 8GB 

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

VoiceChanger Initialized (GPU_NUM(cuda):0, mps_enabled:False, onnx_device:GPU)
[4564:0725/033806.575:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is

**Comment by FoxLust** [comment]
CUDA is for Nvidia GPU, use DirectML version for AMD GPU

**Comment by w-okada** [comment]
your gpu is not detected by pyTorch. Please redo the setup cuda.

**Comment by w-okada** [comment]
no res close
