### ISSUE TITLE
how to add rmvpe to F0 Det 

### ISSUE THREAD

**Issue by inpico** [w-okada/voice-changer#556]
### Issue Type

Question

### vc client version number

v.1.5.3.10a

### OS

windows 11 

### GPU

amd 6800h 

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

rvc

### Model type

 pyTorch

### Situation

I want to use this model https://huggingface.co/lj1995/VoiceConversionWebUI/blob/main/rmvpe.pt
but I don't know  how to put this into this 
![image](https://github.com/w-okada/voice-changer/assets/34965409/47e1babf-d70d-4ede-9069-f505bd8aab9d)

**Comment by inpico** [comment]
sorry I don't know which folder to put the files in and then rmvpe can be displayed in the F0 Det list

**Comment by w-okada** [comment]
OKey, So delete previous version of the application. Then extract the zip.

**Comment by w-okada** [comment]
no res close
