### ISSUE TITLE
New issue idk what to do

### ISSUE THREAD

**Issue by myaurov** [w-okada/voice-changer#558]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10a.zip

### OS

Windows 10

### GPU

NVIDIA GeForce GTX 1660 SUPER

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

pyTouchRVCv2

### Situation

The app itsleft launches succesfully. But if I try to click any model, it just turns blank. 
![image](https://github.com/w-okada/voice-changer/assets/140498390/5399eb8e-9fb9-42bd-a778-b959462513ac)
I still can do CTRL+R but it happens again and again, I even tried re-installing. Can anyone help me?

**Comment by myaurov** [comment]
Also console says this
![image](https://github.com/w-okada/voice-changer/assets/140498390/1dbb6ccb-9835-42f0-88be-6a9c7e939db9)

**Comment by w-okada** [comment]
show me full log on the terminal. or find all exceptions.

**Comment by w-okada** [comment]
no res close
