### ISSUE TITLE
(node:18204) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by remanyy** [w-okada/voice-changer#559]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.10a

### OS

Windows 10

### GPU

RX 5700 XT

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX DirectML

### Situation

After downloading newest ONNX directML build and starting start_http.bat it keeps showing me this error message: "(node:18204) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED". I have tried everything possible. 

Reinstallation
Deactivate Windows Defender
Switched Internet Connection
Deleting model_dir
Switched Folder location
...

I really dont know what else to do. Maybe you can help ? Thank you very much.

PC Specs:
Windows 10
AMD RX 5700 XT 8GB
Ryzen 5600x
12 GB DDR4 3200MHz

![cmd_Ljuv2CmBro](https://github.com/w-okada/voice-changer/assets/140525130/e2373b24-f94e-464c-a08a-9280e00221d1)

**Comment by Hlebuw3k** [comment]
I also got ERR_CONNECTION_REFUSED but I don't know if this is the reason it happens, but I think it has to do with VoiceMeeter if you are using that. Just spamming "Restart Audio Engine" worked for Me and the program started.

**Comment by remanyy** [comment]
i dont use VoiceMeeter

**Comment by w-okada** [comment]
How long did you wait？

**Comment by josephjo3y** [comment]
i have this same problem

**Comment by remanyy** [comment]
i tried for 5 minutes but it was always the same error

**Comment by ramsemaj** [comment]
I got this same error after I hit cancel to the firewall popup asking about allowing access to a network.  To get this work, I had to redownload and rerun the application fresh to get the popup again to allow access.  Alternatively, you could go into the Windows settings to allow access to the application.

**Comment by w-okada** [comment]
if you have stored_setting.json in folder, try to delete.

**Comment by Harkyzera** [comment]
the same happens here
![image](https://github.com/w-okada/voice-changer/assets/43623598/e5e146a5-aad3-4ad9-884f-6f25770020bf)

**Comment by TaruMoore** [comment]
Good evening, I would like to know if this problem is solved. I have a 4070ti graphics card with 12 GB of memory and 24 GB of RAM. Tried to wait half an hour - the problem is not solved. Tried disabling the firewall - problem not solved. Tried both versions for Windows - no change. There is no "stored_setting.json" file.
I will be very grateful for your help
![cmd_wh7YZecJ7p](https://github.com/w-okada/voice-changer/assets/140758495/27919470-09e4-4140-9211-34bde2163ec5)

**Comment by Harkyzera** [comment]
I found a way to fix it, I used an nvidia video card before using this rx 5600 xt I downloaded the DDU and uninstalled the old gtx 1060 driver that I used in the past
![image](https://github.com/w-okada/voice-changer/assets/43623598/ec17ec86-af1d-4c4a-ae9e-ebe4e61fedcd)

**Comment by w-okada** [comment]
@TaruMoore 
you failed to download sample info, which is used in software. Check the right to read/write in folder. of check disk space.

**Comment by w-okada** [comment]
@ramsemaj 
Have you tried to delete sotred_setting.json?

**Comment by jogamer777** [comment]
For me, when I run the start http.bat, it looks like this:
![image](https://github.com/w-okada/voice-changer/assets/82082110/9d4463ae-16a5-482e-8583-72e79e64f0d6)
So I thought maybe the server was not starting, so I started the MMVCServerSIO.exe and this happened before it closed:
![image](https://github.com/w-okada/voice-changer/assets/82082110/6e7050a5-0d96-4d10-8f04-db36e4d4046c)
I also tried installing different versions and installing it on different drives and uninstalling and reinstalling python. but nothing got me further.
I'll be very grateful if you'd like to help.

**Comment by jogamer777** [comment]
[Log.txt](https://github.com/w-okada/voice-changer/files/12206951/Log.txt)
Here I have copied the text into a document for better research.

**Comment by w-okada** [comment]
@jogamer777 
I don't understand your situation because you did not follow the issue template to describe it.

But this might be helpful.
https://github.com/oobabooga/text-generation-webui/discussions/929

**Comment by w-okada** [comment]
no response from @remanyy. close
