### ISSUE TITLE
ONNX Installed, only utilizing CPU

### ISSUE THREAD

**Issue by cl500** [w-okada/voice-changer#560]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.10a

### OS

Win10

### GPU

6650XT

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

MMVC

### Model type

ONNX

### Situation

I followed the instructions and everything "works" except that its utilizing my CPU Instead of my GPU and this leads to my CPU being at 100% and the Voice being very choppy and very delayed

**Comment by w-okada** [comment]
increase chunk to avoid chippy. (but increase latency)

**Comment by w-okada** [comment]
Why do you think GPU is not used?
I have no info about you. Share information.

**Comment by cl500** [comment]
> you're trying to use cuda on AMD GPU that can't work afaik you downloaded the wrong package

I mean there are only two options for windows right? onnxgpu-cuda and onnxdirectML-cuda and since I have a AMD GPU I am using the onnxdirectML-cuda one

**Comment by cl500** [comment]
> Why do you think GPU is not used? I have no info about you. Share information.

CPU is between 70-100% usage while my GPU is at 0%, I have onnx installed, tried different voice changer versions. and after all its still not using my GPU at all and the voice changer is very slow and choppy no matter the chunk settings. I dont know what more info to give tbh

**Comment by w-okada** [comment]
So, 6650XT is supported by onnxruntime?
Consult with onnxruntime community.

And share the log in the terminal and screenshot of the window.

**Comment by longb1997** [comment]
i realized crepe-full uses GPU, Crepe-tiny uses CPU

**Comment by w-okada** [comment]
no res close
