### ISSUE TITLE
rvmpe no option for mps, runs on cpu only

### ISSUE THREAD

**Issue by kagayaki-7** [w-okada/voice-changer#561]
### Issue Type

Bug Report

### vc client version number

1.5.3.10a

### OS

MacOS Ventura 13.4.1 M2

### GPU

mps

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

f0 rvmpe 

### Situation

Expecting a drop-down for mps when using rvmpe (or any model).  There is no option available and it runs on cpu.

**Comment by w-okada** [comment]
The dropdown says CPU, but it should be using MPS.

**Comment by w-okada** [comment]
okey close
