### ISSUE TITLE
cant slide S-Threshhold

### ISSUE THREAD

**Issue by senzata** [w-okada/voice-changer#562]
### Issue Type

Bug Report, Question

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.10a.zip

### OS

Windows 10

### GPU

RTX 2060

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

MMVC

### Model type

the pre downloaded ones

### Situation

just cant slide it over

**Comment by w-okada** [comment]
how to reproduce?

**Comment by w-okada** [comment]
no res close
