### ISSUE TITLE
Why does it need a server connexion and why are we limited to 9 slots?

### ISSUE THREAD

**Issue by LuluViBritannia** [w-okada/voice-changer#564]
Hello,
First of all, thank you. While RVC has a real-time GUI, it just doesn't work for me. I tried your software, and this one works!

But I don't understand why it requires an online connexion. And given that we're limited to 9 slots, I assume you're storing the voices on your servers (which is a bit shady, by the way).
Why is it needed, and, in the ideal scenario, could you remove that necessity please? I have 20 voices, and with time, I'll likely have more than 50. No one wants a limited number of slots...

**Comment by w-okada** [comment]
use issue template
