### ISSUE TITLE
No sound output

### ISSUE THREAD

**Issue by Kryleer** [w-okada/voice-changer#566]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.10a

### OS

Windows 10

### GPU

Amd radeon 6600xt

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

It worked at the new installation like for 1sec but no real words, then i get no output. i tried like everything and every version. anyone got a solution ?

update: i get now really loud weird noises, its like its crashing or something

**Comment by Kryleer** [comment]
update: i get now really loud weird noises, its like its crashing or something

**Comment by w-okada** [comment]
Try run with cpu. Intel arc or some gpu is not supported.

**Comment by Mixxy3k** [comment]
I tried and issue stil remains. Also before formatting Windows it worked. Well, kind of, 80% CPU utilization and ~20% GPU with chunk set to 384

I'm fully aware that most of ML applications do not support/are unstable on Intel Arc so it's fine. If I find some way to fix it(or go back to how it worked before) I will let you know.

**Comment by Kryleer** [comment]
> Try run with cpu. Intel arc or some gpu is not supported.

already tried, not working

**Comment by w-okada** [comment]
not working? Give me more info if you want to solve this issue.

**Comment by Kryleer** [comment]
> not working? Give me more info if you want to solve this issue.

alright, what should i send :) ?

**Comment by w-okada** [comment]
when run with cpu, performance info(cpu usage, etc), and setting(capture screen).

**Comment by Kryleer** [comment]
![Screenshot 2023-07-27 023804](https://github.com/w-okada/voice-changer/assets/135225852/8ac3deb3-906a-4b97-a6a9-1ca0dc5f8205)
![Screenshot 2023-07-27 023808](https://github.com/w-okada/voice-changer/assets/135225852/dedffaa7-9396-4a3c-b572-d5271ee76088)

**Comment by w-okada** [comment]
ah... cpu usage is 100%. your cpu does not have enough power to convert voice.
try to use dio as f0 det. and decrease Extra to 4096.

**Comment by Kryleer** [comment]
> 

i get very loud squeak noises, after i did that

**Comment by w-okada** [comment]
OK, so try use cuda version with cpu. Directml onnxruntime  sometimes behaves in unpredictable ways.

**Comment by Kryleer** [comment]
> OK, so try use cuda version with cpu. Directml onnxruntime sometimes behaves in unpredictable ways.

working now, but its cutting off every word. but i think thats just because my cpu alone cant handle it with discord or something on

**Comment by w-okada** [comment]
show me setting. capture window

**Comment by Kryleer** [comment]
> show me setting. capture window

![image](https://github.com/w-okada/voice-changer/assets/135225852/8a3eba7c-2c76-448c-bb14-77dfc5e92e54)

**Comment by w-okada** [comment]
reached to CPU limit. increase chunk size.

**Comment by Kryleer** [comment]
> 

not really working, i think its my cpu because all alone on the cpu is too much. thank you anyways

**Comment by w-okada** [comment]
okay close.
