### ISSUE TITLE
can't import to ONNX

### ISSUE THREAD

**Issue by tian-ab** [w-okada/voice-changer#568]
### Issue Type

Bug Report, Others

### vc client version number

v.1.5.3.10 onnxdirectML - cuda

### OS

Windows 11

### GPU

AMD RX 6600

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

I have an AMD RX 6600 GPU and since it could only be utilized for ONNX models, i tried to export my existing PyTorch models to ONNX but for some reason, it always gives an error like the picture below

![image](https://github.com/w-okada/voice-changer/assets/88672404/d5a9ee59-8f62-4064-86ae-2cfe8bbd24d6)

Any idea how to fix this?
thanks in advance

**Comment by w-okada** [comment]
Use cpu to convert it

**Comment by tian-ab** [comment]
> Use cpu to convert it

okay, thanks a lot
