### ISSUE TITLE
res keeps going up

### ISSUE THREAD

**Issue by senzata** [w-okada/voice-changer#569]
### Issue Type

Bug Report

### vc client version number

 MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.10a.zip

### OS

Windows 10

### GPU

RTX 2060

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

MMVC

### Model type

Markiplier

### Situation

![image](https://github.com/w-okada/voice-changer/assets/140387024/24ea958e-7609-4f59-a25e-63a1ea0df603)

just keep going up even though i havent taked or anything yet

**Comment by w-okada** [comment]
read readme and tutorial
