### ISSUE TITLE
startHttp.command and startHttps.command script recommendations (paths with special characters/spaces, bug prevention)

### ISSUE THREAD

**Issue by nik312123** [w-okada/voice-changer#570]
### Issue Type

Bug Report

### vc client version number

Irrelevant to this issue. Though, this is specific to macOS.

### OS

Affects all macOS devices.

### GPU

Irrelevant to this issue.

### Clear setting

N/A

### Sample model

N/A

### Input chunk num

N/A

### Wait for a while

N/A

### read tutorial

yes

### Extract files to a new folder.

N/A

### Voice Changer type

N/A

### Model type

N/A

### Situation

The `startHttp.command` and `startHttps.command` shell variables do not use proper quoting of bash variables, which can cause issues with paths with special characters or spaces. See [SC2248](https://www.shellcheck.net/wiki/SC2248) for reference.

For example, instead of the following

```bash
cd ${curdir} && \
DYLD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${curdir}/MMVCServerSIO.app/Contents/MacOS/torchaudio/lib PYTORCH_ENABLE_MPS_FALLBACK=1 MMVCServerSIO.app/Contents/MacOS/MMVCServerSIO
...
```

do this

```bash
cd "${curdir}" && \
DYLD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${curdir}/MMVCServerSIO.app/Contents/MacOS/torchaudio/lib" PYTORCH_ENABLE_MPS_FALLBACK=1 MMVCServerSIO.app/Contents/MacOS/MMVCServerSIO \
...
```

Also, somewhat related since it is about shell formatting standards, I would recommend using `$(...)` notation over legacy backticked `` `...` `` as per [SC2006](https://www.shellcheck.net/wiki/SC2006).

So, that would change this

```bash
curdir=`dirname "$0"`
```

to this:

```bash
curdir="$(dirname "$0")"
```

Note: I also quoted the results of `$(...)` for the case in which the resulting path has special characters or spaces.

**Comment by w-okada** [comment]
Thanks! I'll fix next release

**Comment by w-okada** [comment]
try v.1.5.3.11
