### ISSUE TITLE
Output Audio sound chunky/laggy

### ISSUE THREAD

**Issue by KuroFBK** [w-okada/voice-changer#571]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10a.zip

### OS

Windows 10

### GPU

GTX 960M

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

RVC v2

### Situation

I tried to inccrease the chunk but it still sound chunky, or more like laggy, is that a problem or just my PC are weak?

**Comment by w-okada** [comment]
use cuda version

**Comment by w-okada** [comment]
show me a settings.

**Comment by KuroFBK** [comment]
> show me a settings.

What setting you mean? My PC or the app?

**Comment by w-okada** [comment]
yes

**Comment by w-okada** [comment]
no res close
