### ISSUE TITLE
Why my res so high?

### ISSUE THREAD

**Issue by nanamel1** [w-okada/voice-changer#572]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.10

### OS

Windows 10

### GPU

Radeon (TM) RX 470 Graphics

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

![image](https://github.com/w-okada/voice-changer/assets/140716549/3ec7fe5a-3e55-435c-b16b-479ea038a31e)

when I begin my res it start at 294ms and keep increasing as shown in fig.
Is this normal?
How I fix it?

**Comment by w-okada** [comment]
read readme and tutorial.
