### ISSUE TITLE
Noise sound output and high res

### ISSUE THREAD

**Issue by Zeroday42** [w-okada/voice-changer#573]
### Issue Type

Bug Report, Others

### vc client version number

v.1.5.3.10b

### OS

Windows 10

### GPU

RX 580

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

DirectML f0

### Situation

when I press start and the phrase is increased, and after that there is a very loud lagging noise, I tried to change all the settings that you can and put different combinations of them, 1 time with the settings as in the screenshot, my holo worked but it lagged very much
![Снимок](https://github.com/w-okada/voice-changer/assets/105718412/64932955-3dfd-48e4-bbf0-70a1be8a4954)
![2](https://github.com/w-okada/voice-changer/assets/105718412/0de16a47-2234-4223-8e31-8dbed70405ea)

**Comment by Zeroday42** [comment]
okay , thanks

**Comment by KersaArleta** [comment]
are you find how to fix it bro?
