### ISSUE TITLE
My changed voice's playback is recognized as my voice.

### ISSUE THREAD

**Issue by PeterGriffin654** [w-okada/voice-changer#574]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.10a

### OS

Windows 10

### GPU

RX 580

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

None

### Situation

When I speak the output audio gets repeated constantly.
I feel like any audio that is played on my pc is recognized as speaking into the mic, as a result, the playback of me speaking creates a constant loop of what I said and each time it gets more and more distorted.
This issue only happens while using the software it's so annoying and it makes the software unusable.

![Képernyőkép 2023-07-27 190320](https://github.com/w-okada/voice-changer/assets/140738133/bd698465-b701-48f8-9012-fc0b98787385)

**Comment by w-okada** [comment]
output to virtual cable os so

**Comment by w-okada** [comment]
no res close
