### ISSUE TITLE
"decryption failed or bad record mac" while downloading dependencies

### ISSUE THREAD

**Issue by Zetkut** [w-okada/voice-changer#575]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.10a

### OS

Windows 10

### GPU

AMD

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

-

### Model type

-

### Situation

C:\Users\User\Desktop\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
[Voice Changer] matplotlib is dummied
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Voice Changerを起動しています。
 26%|████████████████████▍                                                          | 46.7M/181M [01:09<02:49, 827kB/s][SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2578)                       | 35.1M/361M [01:07<12:40, 450kB/s]
                                                                                                                       [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2578)                       | 35.8M/361M [01:09<11:07, 511kB/s]
 47%|████████████████████████████████████▊                                         | 25.5M/54.1M [01:09<00:49, 601kB/s]
 13%|██████████▏                                                                    | 46.7M/361M [01:25<06:32, 841kB/s]
 19%|██████████████▋                                                               | 67.8M/361M [01:24<02:16, 2.25MB/s]

 67%|████████████████████████████████████████████████████▎                         | 36.3M/54.1M [01:24<00:27, 689kB/s]
 59%|█████████████████████████████████████████████▍                               | 50.1M/84.9M [01:25<00:22, 1.61MB/s]
 24%|██████████████████▊                                                            | 41.0M/173M [01:09<05:34, 413kB/s]
 10%|███████▋                                                                       | 35.1M/361M [01:24<08:51, 642kB/s]
 30%|███████████████████████                                                       | 51.0M/173M [01:24<02:07, 1.00MB/s]

**Comment by w-okada** [comment]
It's probably an issue with your network. Here's something for your reference.

https://stackoverflow.com/questions/41780517/python-ssl-error-decryption-failed-or-bad-record-mac

**Comment by w-okada** [comment]
no res close
