### ISSUE TITLE
exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cuda:0

### ISSUE THREAD

**Issue by GeneratedScript-RL** [w-okada/voice-changer#577]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.10

### OS

Win 10

### GPU

Nvidia GeForce GTX 960M

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

When trying to select a voice, this appears.

![image](https://github.com/w-okada/voice-changer/assets/61459573/9bd51ed9-e0dc-409f-a2c0-54d6bfd24548)

Terminal screenshot:

![Screenshot (565)](https://github.com/w-okada/voice-changer/assets/61459573/18b9aa72-96dd-4cf8-a5e3-8765046176d1)

Additional notes:

Once this screen pops up, rerunning the gui will only show a blank white window, and it will show this:

![image](https://github.com/w-okada/voice-changer/assets/61459573/97ba286c-7c92-4649-91d5-b90bdc0cc6ce)
 
the above issue is fixed by deleted stored_setting.json file, but the first issue will still persist.

**Comment by w-okada** [comment]
Your file is not correctly parsed. check you could download the files.

see
https://github.com/w-okada/voice-changer/issues/488#issuecomment-1638997533

**Comment by w-okada** [comment]
no res close
