### ISSUE TITLE
What is the difference between start_http and start_https?

### ISSUE THREAD

**Issue by PanterMan11** [w-okada/voice-changer#578]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.7

### OS

Windows 11

### GPU

Nvidia Geforce RTX 3060

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

ONNX

### Situation

When I try to use the start_http file, it launches. But when I use the https, it doesn't launch a GUI. In the readme file, it says the https is used for connecting remotely, what does this mean?

**Comment by w-okada** [comment]
You can use the browser(chrome only) of remote host with https.
