### ISSUE TITLE
My GPU is not detected please help me

### ISSUE THREAD

**Issue by Neplex42** [w-okada/voice-changer#580]
### Issue Type

Bug Report

### vc client version number

1.5.3.10b

### OS

Windows

### GPU

AMD Radeon RX 6800 XT

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

Hi, I have a problem with the detection of my GUP (AMD Radeon RX 6800 XT). I've tried several versions of the software (win_onnxgpu-cuda and win_onnxdirectML-cuda) and it's only the CPU that takes everything. My GPU is not used. On one of them I have 0, 1, 2, 3 icons but I still don't have any GPU overload but only CPU overload. I'll send you the photos with it.
![Capture d’écran 2023-07-28 152454](https://github.com/w-okada/voice-changer/assets/76078411/6b6927fb-6242-4450-ada8-5ade3bec5d45)
![Capture d’écran 2023-07-28 152515](https://github.com/w-okada/voice-changer/assets/76078411/fd27d43e-ecae-47e2-bda2-77c54d1dabf3)

**Comment by w-okada** [comment]
read tutorial. amd is available for directml version, and onnx model
