### ISSUE TITLE
Error unhandledrejection no error stack

### ISSUE THREAD

**Issue by CrunchBoi** [w-okada/voice-changer#581]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10a

### OS

Windows 10

### GPU

NVIDIA GeForce GT 730

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

what?
![image](https://github.com/w-okada/voice-changer/assets/140824884/a34a2940-55b2-4a3b-88d8-a9245beb01ca)

**Comment by w-okada** [comment]
how to reproduce??

**Comment by CrunchBoi** [comment]
I just open it and press start

**Comment by w-okada** [comment]
It appears to be a problem with your environment only at the moment. 
Let's observe the situation for a bit.

**Comment by w-okada** [comment]
no res close

**Comment by noobmaster2002** [comment]
same problem i have what i do now

**Comment by noobmaster2002** [comment]
![image](https://github.com/w-okada/voice-changer/assets/85995697/e1355b80-1f5d-409c-8d68-802cb0153e3b)

**Comment by Glebochka** [comment]
Exactly the same problem. Does anyone have a solution?
![image](https://github.com/w-okada/voice-changer/assets/107573757/a31400da-04ed-4fb4-b9f3-1e5d237b6f20)
