### ISSUE TITLE
Repeating at end of said said lines.

### ISSUE THREAD

**Issue by GDani31** [w-okada/voice-changer#583]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10.zip

### OS

Windows 10

### GPU

1050 ti

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

When i talk, there is a repeating in my lines i said at the end. I have changed everything, F0 Det., S.Thresh., Chunk, extra and changed from GPU to CPU and back. I still hav a repeating even after increasing the Chunk.

**Comment by w-okada** [comment]
I cannot understand your situation. please capture your sound and share,.

**Comment by jerohero** [comment]
In my case this happened because my headphone audio was leaking into my microphone, causing it to be captured and repeat what I said. If that could be the case you might try distancing yourself from the microphone or installing filter software like Krisp.

**Comment by w-okada** [comment]
no res close
