### ISSUE TITLE
GPU process exited unexpectedly?

### ISSUE THREAD

**Issue by AcreroYT** [w-okada/voice-changer#586]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11.zip

### OS

Windows 11

### GPU

RTX2060

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

none

### Model type

none

### Situation

no idea why this is happening
![ohno](https://github.com/w-okada/voice-changer/assets/126112250/df3ecb8b-88e9-4f5b-90ae-9a399ed63e98)

**Comment by w-okada** [comment]
I have no idea
