### ISSUE TITLE
TypeError: n.setSinkId is not a function

### ISSUE THREAD

**Issue by aquakenzie** [w-okada/voice-changer#587]
### Issue Type

Bug Report

### vc client version number

git clone master branch

### OS

Ubuntu 22.04

### GPU

1050 Ti

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

N/A

### Model type

N/A

### Situation

![image](https://github.com/w-okada/voice-changer/assets/138723298/83261f5a-c695-4e03-9024-9b52df571976)
Steps to reproduce:
- follow https://github.com/w-okada/voice-changer/blob/master/README_dev_en.md
- open localhost:18888
- instant error

**Comment by NMedvesky** [comment]
I also encountered this error, did a bit of research and it turns out not all browsers support this function. Here's a list of supported browsers. Changing to chrome fixed it for me.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId#browser_compatibility

**Comment by w-okada** [comment]
Yes. Thanks. Only chrome is supported. 

https://github.com/w-okada/voice-changer/issues/230

**Comment by w-okada** [comment]
no res close 

and see 
https://github.com/w-okada/voice-changer/issues/475
