### ISSUE TITLE
program didn't detect my gpu

### ISSUE THREAD

**Issue by nattawaskh** [w-okada/voice-changer#588]
### Issue Type

Bug Report

### vc client version number

https://huggingface.co/wok000/vcclient000/blob/main/MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11.zip

### OS

Windows 10

### GPU

AMD Radeon™ RX 570

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

MMVC

### Model type

 pyTorch

### Situation

program didn't detech my gpu(Radeon™ RX 570) ,I can use only cpu.

**Comment by w-okada** [comment]
read readme and tutorial
