### ISSUE TITLE
Pitch has dropped in v.1.5.3.11

### ISSUE THREAD

**Issue by holmesfems** [w-okada/voice-changer#592]
### Issue Type

Bug Report

### vc client version number

v.1.5.3.11

### OS

Windwos 10

### GPU

RTX 4070 Ti

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

Using the same setting, the pitch of voice-change has dropped in v.1.5.3.11, compares to v.1.5.3.10

v.1.5.3.10からv.1.5.3.11にバージョンを上げたところ、同じ設定(Tune+12)なのに声が低くなってしまいました

**Comment by w-okada** [comment]
I don't have a good ear for music, so I'm not sure, but is there a significant difference?

**Comment by holmesfems** [comment]
This video file is the comparison of the same line in different versions. The pitch of the latter(1.5.3.11) is clearly lower.

https://github.com/w-okada/voice-changer/assets/3482070/e1a018f6-5ca3-4359-95b3-9bcd1c3f18bd

**Comment by w-okada** [comment]
I'm sorry, but I can't really tell the difference. There might be slight variations... Could it be that the f0 det is different?

**Comment by w-okada** [comment]
no update
