### ISSUE TITLE
/client/demo/dist' does not exist

### ISSUE THREAD

**Issue by freyzamarshall02** [w-okada/voice-changer#593]
[Voice Changer] Generating metadata...
[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] ONNX Model: Official v2 like
 [Loading] model_dir/4/combo_spk5_nl3_dl20_k50_500ep.ptc.bin
 [Loading] model_dir/5/combo_spk5_nl3_dl1_k50_500ep.ptc.bin
    Internal_Port:18888
    protocol: HTTPS(self-signed), key:keys/20230729_122115.key, cert:keys/20230729_122115.cert
    -- ---- -- 
    ブラウザで次のURLを開いてください.
    https://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    https://localhost:18888/
    https://172.28.0.12:18888/
    Booting PHASE :__mp_main__
    サーバプロセスを起動しています。
    Booting PHASE :MMVCServerSIO
[MODEL SLOT INFO] [RVCModelSlot(voiceChangerType='RVC', name='つくよみちゃん(onnx)', description='', credit='つくよみちゃん', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tsukuyomi-chan/terms_of_use.txt', iconFile='model_dir/0/tsukuyomi-chan.png', speakers={'0': 'target'}, modelFile='model_dir/0/tsukuyomi_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='Tsukuyomi-chan_o'), RVCModelSlot(voiceChangerType='RVC', name='あみたろ(onnx)', description='', credit='あみたろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/amitaro/terms_of_use.txt', iconFile='model_dir/1/amitaro.png', speakers={'0': 'target'}, modelFile='model_dir/1/amitaro_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='Amitaro_o'), RVCModelSlot(voiceChangerType='RVC', name='黄琴まひろ(onnx)', description='', credit='黄琴まひろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/kikoto_mahiro/terms_of_use.txt', iconFile='model_dir/2/kikoto_mahiro.png', speakers={'0': 'target'}, modelFile='model_dir/2/kikoto_mahiro_v2_40k_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='KikotoMahiro_o'), RVCModelSlot(voiceChangerType='RVC', name='刻鳴時雨(onnx)', description='', credit='刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tokina_shigure/terms_of_use.txt', iconFile='model_dir/3/tokina_shigure.png', speakers={'0': 'target'}, modelFile='model_dir/3/tokina_shigure_v2_40k_e100_simple.onnx', indexFile='model_dir/3/added_IVF2736_Flat_nprobe_1_v2.index.bin', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='TokinaShigure_o'), DiffusionSVCModelSlot(voiceChangerType='Diffusion-SVC', name='初期メン(3,20)', description='', credit='あみたろ,つくよみちゃん,黄琴海月,黄琴まひろ,刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/diffusion-svc/term_of_use.txt', iconFile='model_dir/4/diffusion-svc.png', speakers={'1': 'user1', '2': 'user2', '3': 'user3', '4': 'user4', '5': 'user5'}, modelFile='model_dir/4/combo_spk5_nl3_dl20_k50_500ep.ptc.bin', isONNX=False, modelType='combo', dstId=1, sampleId='diffusion_combo_spk5_nl3_dl20_k50_500ep', defaultTune=0, defaultKstep=50, defaultSpeedup=25, kStepMax=50, nLayers=20, nnLayers=3, embedder='hubert_base', samplingRate=44100, embChannels=768), DiffusionSVCModelSlot(voiceChangerType='Diffusion-SVC', name='初期メン(3,1)', description='', credit='あみたろ,つくよみちゃん,黄琴海月,黄琴まひろ,刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/diffusion-svc/term_of_use.txt', iconFile='model_dir/5/diffusion-svc.png', speakers={'1': 'user1', '2': 'user2', '3': 'user3', '4': 'user4', '5': 'user5'}, modelFile='model_dir/5/combo_spk5_nl3_dl1_k50_500ep.ptc.bin', isONNX=False, modelType='combo', dstId=1, sampleId='diffusion_combo_spk5_nl3_dl1_k50_500ep', defaultTune=0, defaultKstep=50, defaultSpeedup=25, kStepMax=50, nLayers=1, nnLayers=3, embedder='hubert_base', samplingRate=44100, embChannels=768), ModelSlot(voiceChangerType=None, name='', description='', credit='', termsOfUseUrl='', iconFile='', speakers={}), ModelSlot(voiceChangerType=None, name='', description='', credit='', termsOfUseUrl='', iconFile='', speakers={}), ModelSlot(voiceChangerType=None, name='', description='', credit='', termsOfUseUrl='', iconFile='', speakers={}), ModelSlot(voiceChangerType=None, name='', description='', credit='', termsOfUseUrl='', iconFile='', speakers={})]
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 66, in serve
    config.load()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/voice-changer/server/MMVCServerSIO.py", line 120, in <module>
    app_fastapi = MMVC_Rest.get_instance(voiceChangerManager, voiceChangerParams)
  File "/content/voice-changer/server/restapi/MMVC_Rest.py", line 57, in get_instance
    StaticFiles(directory=f"{getFrontendPath()}", html=True),
  File "/usr/local/lib/python3.10/site-packages/starlette/staticfiles.py", line 57, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory '../client/demo/dist' does not exist

So i experimenting run this on collab but i get this problem, how to solve this?

**Comment by w-okada** [comment]
use issue template
