### ISSUE TITLE
How to select gpu with DirectML version

### ISSUE THREAD

**Issue by tmrzk** [w-okada/voice-changer#594]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.11

### OS

Windows 10

### GPU

RX 6600

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

![Screenshot 2023-07-29 194948](https://github.com/w-okada/voice-changer/assets/140896376/99414a52-ed5b-41a5-a676-df086805815f)

the option only cpu, 0, 1, 2, 3
there's no yes or no option on the GPU(dml)
RX 6600 on newest driver with newest directML version of the project

**Comment by w-okada** [comment]
see https://github.com/w-okada/voice-changer/issues/410
