### ISSUE TITLE
VC PROCESSING EXCEPTION!!! index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by ajaxxxxxxx** [w-okada/voice-changer#595]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10

### OS

Windows 10

### GPU

RTX 2070 Super

### Clear setting

no

### Sample model

yes

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

f0

### Situation

Hello! Error I'm having is with a voice model I've been using for a few days now. For some reason, it works less often than not, and occasionally starts working again. When it doesn't work, it spews out this error in the console.

`[Voice Changer] VC PROCESSING EXCEPTION!!! index -1 is out of bounds for axis 0 with size 0
Traceback (most recent call last):
  File "voice_changer\VoiceChanger.py", line 218, in on_request_sola
  File "voice_changer\RVC\RVC.py", line 176, in inference
  File "voice_changer\RVC\pipeline\Pipeline.py", line 169, in exec
IndexError: index -1 is out of bounds for axis 0 with size 0`

I'm not sure the cause, as other models work 100% fine all the time. This specific model only works after constantly restarting the program and readding the model to the program over and over, and eventually, works. I'd like to know if there's an actual solution.

**Comment by w-okada** [comment]
If other model work correctly, the model which can not be used might be an invalid model.

**Comment by ajaxxxxxxx** [comment]
> If other model work correctly, the model which can not be used might be an invalid model.

As I'm typing this the model all of a sudden works. What would determine if the model is invalid?

**Comment by ajaxxxxxxx** [comment]
Update with more clarification: the model works fine when "index" is set to 0. Any value above 0 causes above error.

**Comment by w-okada** [comment]
So, the index is broken. Anyway, it sounds great that you can convert voice accurately. Please close this issue.
