### ISSUE TITLE
GPU being detected but not being used

### ISSUE THREAD

**Issue by Softboi1** [w-okada/voice-changer#596]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.11.zip

### OS

windows 11

### GPU

RTX 3090

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

so far i have tested multiple versions of this software, MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.11.zip, MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11.zip and MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10.zip.. 

my issue is that no matter what settings i try and change, no matter what it doesnt use my GPU... it detects my GPU and i have it selected but no matter what it always uses my CPU in task manager and uses around 70+ percent of my 16core proccessor and uses only 2 percent of my gpu for what assume is to just display on my screen

i have manually downloaded python, pytorch and nvdia cuda to no avail.. please help me .. bare in mind it also does this with every model no matter the type

**Comment by w-okada** [comment]
GPU is used to 2% ? Your gpu is great, so it might be low.

**Comment by Softboi1** [comment]
No it's literally not using my GPU whatsoever, like I said my CPU is the only thing being used as it uses 70+ percent of it no matter what, I'm currently reinstalling my GPU drivers

**Comment by Softboi1** [comment]
![image](https://github.com/w-okada/voice-changer/assets/125677755/a112dabf-3873-4131-b40d-8ac1cffe5e47)




here, its not using my gpu what so ever and it does this on every version ive mentioned and ive just reinstalled my gpu drivers using ddu

**Comment by Softboi1** [comment]
it doesnt matter what settings i input whatsoever it detects my gpu but just never uses it

**Comment by Softboi1** [comment]
![image](https://github.com/w-okada/voice-changer/assets/125677755/a3354532-4218-4feb-93a0-5f51ea3ea6a7)

its only using my proccessor no matter what

**Comment by Softboi1** [comment]
tried all the different versions, tried reinstalling my gpu drivers, tried installing cuda, installing python, installing pytorch, messing with every setting imaginable to just get it to use my gpu and to no avail and ive also encountered others with this same issue

**Comment by w-okada** [comment]
are you using RTX 3090 aren't you? why use directml version?

**Comment by Softboi1** [comment]
> are you using RTX 3090 aren't you? why use directml version?

Because I've tried the other versions as I've mentioned.. I've used :
MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.11.zip, MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11.zip and MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10.zip

**Comment by w-okada** [comment]
OKay.

So, sorry but I cannot understand why do you think the app don't your gpu. 
Your gpu is great, so it might be low, I think.

,,, Okay use dio, and increase chunk.

**Comment by w-okada** [comment]
And use  MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11.zip

**Comment by Softboi1** [comment]
> And use MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11.zip

already used that version

**Comment by Softboi1** [comment]
> OKay.
> 
> So, sorry but I cannot understand why do you think the app don't your gpu. Your gpu is great, so it might be low, I think.
> 
> ,,, Okay use dio, and increase chunk.

already done that, yes my gpu is powerful but not powerful enough to run the app at 0 percent my guy

**Comment by Thespacemanfil** [comment]
Genuinely painful

**Comment by w-okada** [comment]
Okay,

PLEASE TRY 
(1) use MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11.zip
(2)  use dio, and increase chunk.
(3) share screen capture

If you don't want to do this, I can not comment.

**Comment by Softboi1** [comment]
okay just a second

**Comment by Softboi1** [comment]
im just re downloading it just a minute

**Comment by Thespacemanfil** [comment]
I have amd 6600xt and same issue
no gpu usage
using the correct, latest version

**Comment by w-okada** [comment]
@Thespacemanfil 
No. you are not using nvidia gpu. That is different situation, directml version is only experimental.

![image](https://github.com/w-okada/voice-changer/assets/48346627/834d0fc3-8583-458f-b04d-c5ca2a459467)

**Comment by Softboi1** [comment]
https://drive.google.com/file/d/1xmb3MwWFw5Rp3-22C5ea0_LOlB7bFLPO/view?usp=sharing

**Comment by Softboi1** [comment]
@w-okada

**Comment by Softboi1** [comment]
the only thing my gpu is being used for is to display it on my screen, i bet if i lowered the resolution of my monitor it would be close to 0 percent

**Comment by w-okada** [comment]
Thanks,
> Your gpu is great, so it might be low, 

I think. Indeed, that's the only way I can see it.
With only cpu, res should be more large. 200ms or more.

Try change gpu to cpu.

**Comment by Softboi1** [comment]
how can you explain the fact its not using my gpu at all and only using my proccessor exactly?

**Comment by w-okada** [comment]
TRY change gpu to cpu. 
AND TELL ME RESULT.

If you are right, CPU usage does not raise.

**Comment by Softboi1** [comment]
it works now, but holy moly why does it use so much of my proccessor

**Comment by w-okada** [comment]
I don't know. My environment, cpu usage only 10~15% with gpu.
Anyway, close this issue
