### ISSUE TITLE
Feature Request - Raw (null) Mic Passthrough

### ISSUE THREAD

**Issue by robbyschetlick** [w-okada/voice-changer#598]
### Issue Type

Feature Request

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11.zip

### OS

Windows 10

### GPU

N/A

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC v.1.5.3.11

### Model type

pyTorch, f0

### Situation

Hi w-Okada! Thanks for making this software, this is really cool technology and a lot of fun to use. Many people on the AI Hub server are having a good time experiment with the client and find it very useful -> those extra model slots in the newest version help a lot!

One suggestion that I have that I think would help a lot of people would be to have some sort of default passthrough option. At the moment, most of the users feed their output through a virtual audio cable, which is then fed into discord or another video game/software program. While changing the input audio source is simple on discord, in other games/programs it is not so easy. It would really improve the software to develop some sort of "null model" or base voice that just feeds raw input from your mic through to the output. Think of like a voice modifier "toggle" that allows your voice to be heard as it sounds naturally when you turn off the model.  That way, if the model isn't clear or they turn off voice changer (start mode), we can still hear them without them having to swap off of their virtual audio cable chains. 

I hope this makes sense!

**Comment by w-okada** [comment]
same

https://github.com/w-okada/voice-changer/issues/597
