### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by FuckingToasters** [w-okada/voice-changer#600]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.10.zip

### OS

Windows 10

### GPU

NVIDIA GTX 1660

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

It jas a few japan elements which i can't understand so i don't know, where i can change everything to english language.

![grafik](https://github.com/w-okada/voice-changer/assets/94435104/e46f4d42-0f47-4135-92f4-4cc4eaddccac)

**Comment by w-okada** [comment]
partially supported next release.

**Comment by w-okada** [comment]
try the latest version, v.1.5.3.12
