### ISSUE TITLE
Model Selection: Being able to sort the models alphabeticaly + Model selection view in its own scrollable area

### ISSUE THREAD

**Issue by Wakamu** [w-okada/voice-changer#601]
### Issue Type

Feature Request

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11.zip

### OS

Windows 11

### GPU

RTX 3080

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

With the new slot count i can finaly store all my models at the same time ( right now im at 60+ models)
i added all of them in the alphabetical order so its easier for me to qickly find the voice i want.
But now that i've finished training another model i can only add it to the latests open slot , or i would have to remove all the other models up to that letter then readd them.
So it would be good if we could easily display all the models in the alphabetical order in the main view.

Also having a lot of models can make the GUI a little annoying to use since you have to scroll up through all the models, thus hiding the main settings part ( tune index ratio etc) so having the models in its own div with a scrollbar could be a nice addition too

**Comment by Clutterbyte** [comment]
maybe adding differents, "sorting modes", alphabetically, by creation day, size, type.

**Comment by w-okada** [comment]
will be supported in next release

**Comment by w-okada** [comment]
try the latest version, v.1.5.3.12
