### ISSUE TITLE
lowest setting possible but still on good quality

### ISSUE THREAD

**Issue by Fzzra** [w-okada/voice-changer#604]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10

### OS

Windows 11

### GPU

RTX 3050 Laptop GPU ( 4 VRAM )

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

pls help me .. is there any setting for my specifications the most optimal one (if can), because I want to use it while playing gaming like overwatch etc.. currently this is my setting

if not possible while gaming with my spec, just give me the most optimal setting that i can get 
![Screenshot (232)](https://github.com/w-okada/voice-changer/assets/140985613/83a9299b-6d4a-40a4-b0fe-50531f1d5cc3)

i have i5-11400H 2.70Ghz and 16 GB RAM

**Comment by habib337** [comment]
its all vram, try using harvest or dio , chunk maybe you can set 1000 and extra 8000, you can try playing in 30-40 fps and see if still work

**Comment by w-okada** [comment]
I'm unable to advise on the optimal settings for individual situation. Generally, it's better not to use an index.
