### ISSUE TITLE
Load model pretrain/content_vec_500.onnx failed. File doesn't exist

### ISSUE THREAD

**Issue by xK4n3** [w-okada/voice-changer#606]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11

### OS

windows 10

### GPU

NVIDIA GeForce GTX 1060 6GB

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

f0

### Situation

First time using and when I press start nothing happens. But in the cmd it says:
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
idk what it means and couldn't find any solutions for it

**Comment by w-okada** [comment]
show full log on the terminal

**Comment by rayan135** [comment]
C:\Users\space\Desktop\VC\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Voice Changerを起動しています。
                                                                                                                       ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
                                                                                                                           RVC用のモデルファイルのダウンロードに失敗しました。
    failed to download weight for rvc
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] Downloading model files...
                                                                                                                       [Voice Changer] Generating metadata...
[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] custom matplotlib loaded successfully
 [Loading] model_dir\4\combo_spk5_nl3_dl20_k50_500ep.ptc.bin
 [Loading] model_dir\5\combo_spk5_nl3_dl1_k50_500ep.ptc.bin
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

[VCClient] Access http://localhost:18888/
(node:91508) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:18888
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
(node:91508) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[2023-08-02 04:56:59] connet sid : pe5OiDf00vatqB9YAAAB
[2023-08-02 04:56:59] connet sid : RGGNHWX3qmvenEsfAAAD
[Voice Changer] update configuration: modelSlotIndex 1690941454000
[Voice Changer] model slot is changed -1 -> 0
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVCr2] Initializing...
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec
[Voice Changer] exception! loading embedder Model file not found: pretrain/hubert_base.pt cpu
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from pretrain/content_vec_500.onnx failed:Load model pretrain/content_vec_500.onnx failed. File doesn't exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 28, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 423, in load_model_ensemble_and_task
    raise IOError("Model file not found: {}".format(filename))
OSError: Model file not found: pretrain/hubert_base.pt
[Voice Changer] pipeline create failed. check your model is valid.
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
2023-08-02 04:57:52.1647551 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-08-02 04:57:52.1759273 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec
[Voice Changer] exception! loading embedder Model file not found: pretrain/hubert_base.pt cuda:0
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from pretrain/content_vec_500.onnx failed:Load model pretrain/content_vec_500.onnx failed. File doesn't exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 28, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 423, in load_model_ensemble_and_task
    raise IOError("Model file not found: {}".format(filename))
OSError: Model file not found: pretrain/hubert_base.pt
[Voice Changer] pipeline create failed. check your model is valid.
[Voice Changer][RVC]: update_settings modelSlotIndex:1690941454000
[Voice Changer] update configuration: extraConvertSize 65536
[Voice Changer][RVC]: update_settings extraConvertSize:65536
[Voice Changer] update configuration: serverReadChunkSize 640
[Voice Changer][RVC]: update_settings serverReadChunkSize:640
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] update configuration: silentThreshold 0.00002
[Voice Changer] update configuration: silentThreshold 0.00003
[Voice Changer][RVC]: update_settings silentThreshold:0.00002
[Voice Changer] update configuration: silentThreshold 0.00003
[Voice Changer] update configuration: silentThreshold 0.00004
[Voice Changer][RVC]: update_settings silentThreshold:0.00003
[Voice Changer][RVC]: update_settings silentThreshold:0.00003
[Voice Changer][RVC]: update_settings silentThreshold:0.00004
[Voice Changer] update configuration: silentThreshold 0.00006
[Voice Changer] update configuration: silentThreshold 0.00008
[Voice Changer][RVC]: update_settings silentThreshold:0.00006
[Voice Changer][RVC]: update_settings silentThreshold:0.00008
[Voice Changer] update configuration: silentThreshold 0.0001
[Voice Changer] update configuration: silentThreshold 0.0001
[Voice Changer] update configuration: silentThreshold 0.00013
[Voice Changer] update configuration: silentThreshold 0.00015
[Voice Changer][RVC]: update_settings silentThreshold:0.0001
[Voice Changer][RVC]: update_settings silentThreshold:0.0001
[Voice Changer][RVC]: update_settings silentThreshold:0.00013
[Voice Changer][RVC]: update_settings silentThreshold:0.00015
[Voice Changer] update configuration: silentThreshold 0.00017
[Voice Changer][RVC]: update_settings silentThreshold:0.00017
[Voice Changer] update configuration: silentThreshold 0.00019
[Voice Changer][RVC]: update_settings silentThreshold:0.00019
[Voice Changer] update configuration: silentThreshold 0.00022
[Voice Changer] update configuration: silentThreshold 0.00023
[Voice Changer] update configuration: silentThreshold 0.00026
[Voice Changer][RVC]: update_settings silentThreshold:0.00022
[Voice Changer][RVC]: update_settings silentThreshold:0.00023
[Voice Changer] update configuration: silentThreshold 0.00028
[Voice Changer] update configuration: silentThreshold 0.00031
[Voice Changer][RVC]: update_settings silentThreshold:0.00026
[Voice Changer][RVC]: update_settings silentThreshold:0.00028
[Voice Changer][RVC]: update_settings silentThreshold:0.00031
[Voice Changer] update configuration: silentThreshold 0.00032
[Voice Changer][RVC]: update_settings silentThreshold:0.00032
[Voice Changer] update configuration: silentThreshold 0.00035
[Voice Changer][RVC]: update_settings silentThreshold:0.00035
[Voice Changer] update configuration: silentThreshold 0.00038
[Voice Changer][RVC]: update_settings silentThreshold:0.00038
[Voice Changer] update configuration: silentThreshold 0.0004
[Voice Changer] update configuration: silentThreshold 0.00042
[Voice Changer] update configuration: silentThreshold 0.00045
[Voice Changer][RVC]: update_settings silentThreshold:0.00042
[Voice Changer][RVC]: update_settings silentThreshold:0.0004
[Voice Changer][RVC]: update_settings silentThreshold:0.00045
[Voice Changer] update configuration: silentThreshold 0.00048
[Voice Changer] update configuration: silentThreshold 0.00051
[Voice Changer] update configuration: silentThreshold 0.00054
[Voice Changer][RVC]: update_settings silentThreshold:0.00048
[Voice Changer][RVC]: update_settings silentThreshold:0.00051
[Voice Changer] update configuration: silentThreshold 0.00056
[Voice Changer][RVC]: update_settings silentThreshold:0.00054
[Voice Changer][RVC]: update_settings silentThreshold:0.00056
[Voice Changer] update configuration: silentThreshold 0.00061
[Voice Changer] update configuration: silentThreshold 0.00058
[Voice Changer][RVC]: update_settings silentThreshold:0.00061
[Voice Changer][RVC]: update_settings silentThreshold:0.00058
[Voice Changer] update configuration: silentThreshold 0.00063
[Voice Changer][RVC]: update_settings silentThreshold:0.00063
[Voice Changer] update configuration: silentThreshold 0.00065
[Voice Changer] update configuration: silentThreshold 0.00067
[Voice Changer][RVC]: update_settings silentThreshold:0.00065
[Voice Changer][RVC]: update_settings silentThreshold:0.00067
[Voice Changer] update configuration: silentThreshold 0.0007
[Voice Changer][RVC]: update_settings silentThreshold:0.0007
[Voice Changer] update configuration: silentThreshold 0.00072
[Voice Changer] update configuration: silentThreshold 0.00074
[Voice Changer][RVC]: update_settings silentThreshold:0.00072
[Voice Changer][RVC]: update_settings silentThreshold:0.00074
[Voice Changer] update configuration: silentThreshold 0.00076
[Voice Changer] update configuration: silentThreshold 0.00078
[Voice Changer][RVC]: update_settings silentThreshold:0.00076
[Voice Changer][RVC]: update_settings silentThreshold:0.00078
[Voice Changer] update configuration: silentThreshold 0.00083
[Voice Changer] update configuration: silentThreshold 0.00081
[Voice Changer][RVC]: update_settings silentThreshold:0.00083
[Voice Changer][RVC]: update_settings silentThreshold:0.00081
[Voice Changer] update configuration: silentThreshold 0.00084
[Voice Changer] update configuration: silentThreshold 0.00085
[Voice Changer][RVC]: update_settings silentThreshold:0.00084
[Voice Changer][RVC]: update_settings silentThreshold:0.00085
[Voice Changer] update configuration: silentThreshold 0.00089
[Voice Changer] update configuration: silentThreshold 0.00088
[Voice Changer] update configuration: silentThreshold 0.0009
[Voice Changer][RVC]: update_settings silentThreshold:0.00089
[Voice Changer][RVC]: update_settings silentThreshold:0.0009
[Voice Changer][RVC]: update_settings silentThreshold:0.00088
[Voice Changer] update configuration: silentThreshold 0.00092
[Voice Changer][RVC]: update_settings silentThreshold:0.00092
[Voice Changer] update configuration: silentThreshold 0.00093
[Voice Changer][RVC]: update_settings silentThreshold:0.00093
[Voice Changer] update configuration: silentThreshold 0.00094
[Voice Changer][RVC]: update_settings silentThreshold:0.00094
[Voice Changer] update configuration: silentThreshold 0.00096
[Voice Changer] update configuration: silentThreshold 0.00097
[Voice Changer] update configuration: silentThreshold 0.00098
[Voice Changer][RVC]: update_settings silentThreshold:0.00096
[Voice Changer] update configuration: silentThreshold 0.00099
[Voice Changer][RVC]: update_settings silentThreshold:0.00097
[Voice Changer][RVC]: update_settings silentThreshold:0.00098
[Voice Changer][RVC]: update_settings silentThreshold:0.00099
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'

**Comment by rayan135** [comment]
my problem was fixed by it self I think there was a conflicted with the Kaspersky (Devender)

**Comment by w-okada** [comment]
OK, Thanks. I'll close this issue
