### ISSUE TITLE
ERR_CONNECTION_REFUSED and a bunch of pytorch files? and zips not being accessed im guessing

### ISSUE THREAD

**Issue by abuwude** [w-okada/voice-changer#609]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11

### OS

Windows 11

### GPU

NVidia GTX 1660 SUPER

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

OMNX

### Situation

[VCClient] Access http://localhost:18888/
(node:6428) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:18888
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
(node:6428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Preparing your application. Please wait...
(node:6428) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:6428) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:6428) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:6428) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:6428) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec
Preparing your application. Please wait...
(node:6428) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cpu
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 28, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:6428) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:6428) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:6428) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:6428) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:6428) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:6428) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:6428) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cuda:0
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 28, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
-102 ERR_CONNECTION_REFUSED http://localhost:18888/

this is just when launching the start-http.bat file, and after the gui renders this pops in the terminal
![image_2023-07-31_171055747](https://github.com/w-okada/voice-changer/assets/141044285/a53e334d-cf43-4237-be2f-cdc47c72a2cc)

Then the terminal stops and is completely empty, until i change a setting and thats it, pops up with an error that reads:

Frequent errors occurred (forgot the rest of it mb)"
![image_2023-07-31_171413506](https://github.com/w-okada/voice-changer/assets/141044285/7351826b-8f00-43a9-9301-091a1efc01d0)

And when i first opened the bat file, even after reinstallation, i didnt get a firewall or anti virus pop up, it is excluded from the firewall but nothing happens. what should i do? 
![image_2023-07-31_171452379](https://github.com/w-okada/voice-changer/assets/141044285/2aee0fb3-bbe7-4b1e-92a1-4452536b5ee5)

**Comment by w-okada** [comment]
same 
https://github.com/w-okada/voice-changer/issues/462
