### ISSUE TITLE
Sound either doesn't work or the voice changer voice doesn't input 

### ISSUE THREAD

**Issue by milkdudman** [w-okada/voice-changer#610]
### Issue Type

Bug Report, Others

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10b.zip

### OS

Windows 11

### GPU

NVIDIA Geforce RTX 2060

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

Crepe, harvest, Dio, ONNX,

### Situation

Input and output doesn't seem to work. In discord when I change the settings over to the voice changer I can't hear anything but the people talking and in games I can't hear the game or people talking I've tried somethings but it didn't seem to work.

**Comment by w-okada** [comment]
Which mode do you use, client or server as input.

**Comment by GAMY69** [comment]
Same here, I've been trying to use it for discord but no success so far, followed many tutorials where I set it up with VB-Audio Cable and also tried voicemeeter even though I found a comment saying it's not supported. The program works fine like I can record bits of audio but its that link between it and discord that its not happening and I really wish I can get it resolved. If there is anything else that needs to be clarified then I will clarify.

**Comment by milkdudman** [comment]
I use server and I've tried to restart the program and it didn't fix

**Comment by Mojobones** [comment]
> Same here, I've been trying to use it for discord but no success so far, followed many tutorials where I set it up with VB-Audio Cable and also tried voicemeeter even though I found a comment saying it's not supported. The program works fine like I can record bits of audio but its that link between it and discord that its not happening and I really wish I can get it resolved. If there is anything else that needs to be clarified then I will clarify.

I use the app through voicemeeter into discord and it works fine. 

Go into Control Panel -> Sound -> Recording tab, and while speaking watch for the device in there that lights up because it's getting output. That's what you should set as your microphone/input device in Discord.

**Comment by milkdudman** [comment]
I think my app goes through OBS before anything else but I could be very wrong

**Comment by Mojobones** [comment]
> I think my app goes through OBS before anything else but I could be very wrong

Specifically you should only be changing your microphone/input device on Discord, and *not* your speakers/output device. You saying you can no longer hear people after changing Discord sounds like you're changing both devices.

**Comment by milkdudman** [comment]
I do change discord I'm not even sure if it goes through OBS, I only change what I'm using like in discord I change my input to that virtual cable but it cuts out any background noises, I can only hear the voices of other people and in games when i change it all my audio cuts out and I can't hear anything.

**Comment by w-okada** [comment]
Your problem is `it cuts out any background noises` ? 
Currently, this voice changer can not avoid cutting noise. This is limitation and no way to fix currently.

**Comment by milkdudman** [comment]
I'm not sure if cut out is the word I think it might just be my sound settings.

**Comment by w-okada** [comment]
show me your screen to check your setting.

**Comment by milkdudman** [comment]
What pictures do you require?

**Comment by w-okada** [comment]
Please capture the application window. Refer to other issues for guidance.

**Comment by milkdudman** [comment]
![Screenshot 2023-08-05 170545](https://github.com/w-okada/voice-changer/assets/76594535/940d7718-1bee-404d-a550-7bccd333bc79)
![Screenshot 2023-08-05 170627](https://github.com/w-okada/voice-changer/assets/76594535/ee4b0824-49ef-4c81-a1c2-46fbe4fa3b3a)
![Screenshot 2023-08-05 170633](https://github.com/w-okada/voice-changer/assets/76594535/c4f503cf-75c0-4de3-ac1c-b558025ec500)

**Comment by w-okada** [comment]
Use rmvpe as f0 det.  　If it still seems heavy, you can use dio.

**Comment by milkdudman** [comment]
I'm pretty sure it's my input and output settings but regardless of the help i get it never seems to fix long-term.

**Comment by ChinatsuHS** [comment]
try forcing the microphone and virtual cable on a per app basis (if using windows 11 you can do this in the standard sound mixer settings).. as windows kept changing it to other devices (voice-changer also loves to switch to different devices per launch /model load too)

**Comment by milkdudman** [comment]
I do not follow sorry

**Comment by w-okada** [comment]
ok close
