### ISSUE TITLE
questioning

### ISSUE THREAD

**Issue by Egoist1233** [w-okada/voice-changer#615]
### Issue Type

Question

### vc client version number

newest

### OS

Windows 10

### GPU

gt 730 ddr3

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX,

### Situation

i just want to ask that my gpu gt 730 is supported or not?

**Comment by Egoist1233** [comment]
Well it seem not showing my gpu (maybe its was too old),also i tried the amd version and it showed cpu and 0 to 3.

**Comment by Egoist1233** [comment]
I really wanna troll my bro with this voice changer,any cpu optimize for lowest latency?(mine is i5-3570,ik its hella slow )

**Comment by w-okada** [comment]
I'm not sure. I think it would be best to have the most up-to-date CPU and GPU.

**Comment by w-okada** [comment]
no res close
