### ISSUE TITLE
Bug with input in Audio server

### ISSUE THREAD

**Issue by S4ulG00dman** [w-okada/voice-changer#617]
### Issue Type

Bug Report, Question, Others

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.10

### OS

Windows 10

### GPU

1660ti

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

This is all when I choose in the Audio client. 
If I select the same microphones in the Audio server, then there is no such error, but for some reason they still do not work

Audio client:
For some reason I can't select anything on the input, so if I select any microphone or virtual cable it will show error to me:
**no error name
no error message
no error stack**

After I will get only two options
**Initialize (Runs without the mic I selected while typing)
Reload without initialization (after reboot it gives the same error)**

What can fix this situation?

**Comment by w-okada** [comment]
Sorry, I have no idea. 
please try using the latest version.

**Comment by S4ulG00dman** [comment]
I tried the latest version and got another error when trying to put anything in input again
MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11


**Error
unhandledrejection
no error stack

NotAllowedError: Permission denied by system
no stack**

**Comment by w-okada** [comment]
> Permission denied by system

check your permission.

**Comment by S4ulG00dman** [comment]
When I try to run start_http.bat with admin rights, it just starts up and shuts down

voice-changer-native-client.exe with admin rights works but doesn't fix the same error about permission

Or what exactly needs to be run through admin rights?

**Comment by w-okada** [comment]
Sorry, I have no idea.

**Comment by w-okada** [comment]
no update close

**Comment by mohowebdev** [comment]
Hi i found the solution, you should go to settings > privacy & secuirty > microphone and turn on "let desktop apps acces your microphone". i hope this helps

**Comment by S4ulG00dman** [comment]
> Hi i found the solution, you should go to settings > privacy & secuirty > microphone and turn on "let desktop apps acces your microphone". i hope this helps

This really helped
