### ISSUE TITLE
Hi im Alai and i really need help i give my all information please help me

### ISSUE THREAD

**Issue by Alai786** [w-okada/voice-changer#618]
### Issue Type

Others

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11.zip

### OS

window 10

### GPU

nvidia geforce 730

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

system model is DQ77MK

### Situation

like i extract it and like its like show me that ( -102 ERR_CONNECTION_REFUSED http://localhost:18888/
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVCr2] Initializing...
Preparing your application. Please wait...
(node:5620) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[Voice Changer] generate new embedder. (no embedder)
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
[Voice Changer] Loading index...
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x0000024309808460>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000024321A56290>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x0000024321A56350>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
Preparing your application. Please wait...
(node:5620) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
[Voice Changer] generate new embedder. (anyway)
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
[Voice Changer] Loading index...
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x0000024321A56B00>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000024321A57640>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x0000024321A57700>
Pipeline has been deleted
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings silentThreshold:0.0006
[Voice Changer][RVC]: update_settings modelSlotIndex:1690965439000
[2023-08-02 15:37:57] connet sid : fkbOPlgXXl9KjShJAAAB
[2023-08-02 15:37:57] connet sid : L9z2TT2bvbMpwqVMAAAD 
![2023_08_01_09_30_IMG_9100](https://github.com/w-okada/voice-changer/assets/141223959/544548c5-f930-43dc-9d1f-362f9c8ef116)
now what i have to do please tell me 
![2023_08_02_15_40_IMG_9133](https://github.com/w-okada/voice-changer/assets/141223959/87c663b6-6024-4f14-ae14-9a1790e1630d)

**Comment by w-okada** [comment]
Sorry, What is problem??

**Comment by grimoire-vc** [comment]
I'm not sure if the photo of the resident status thing was intentional, but it doesn't have anything to do with voice-changer

If you're running start_http.bat it should open a second window along with that black window, and that second window is where you will upload a voice and choose your settings and stuff. If you're not seeing that second window, it's possible that you're running start_http**s**.bat by mistake. You should run start_http.bat, not start_https.bat

**Comment by Alai786** [comment]
> Sorry, What is problem??

like its very slow and didnt pick the gpu what should i do it show me in pannel this (  -102 ERR_CONNECTION_REFUSED http://localhost:18888/
[Voice Changer] [RVCr2] Creating instance ) and also this too ( VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:False, onnx_device:GPU) and this ( [Voice Changer][RVC]: update_settings gpu:0 ) like they didnt pick my graphic card pleas help me ......

**Comment by Alai786** [comment]
> I'm not sure if the photo of the resident status thing was intentional, but it doesn't have anything to do with voice-changer
> 
> If you're running start_http.bat it should open a second window along with that black window, and that second window is where you will upload a voice and choose your settings and stuff. If you're not seeing that second window, it's possible that you're running start_http**s**.bat by mistake. You should run start_http.bat, not start_https.bat

yes sir i open start_http.bat and also open second black window but it didnt pick my gpu sir

**Comment by w-okada** [comment]
I'm not sure. Maybe the GPU is not compatible.

**Comment by w-okada** [comment]
no res close
