### ISSUE TITLE
Sound doesn't work

### ISSUE THREAD

**Issue by JoleBole11** [w-okada/voice-changer#621]
### Issue Type

Bug Report, Others

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11

### OS

Windows 10

### GPU

RTX 3080

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

onnx

### Situation

After starting my headphones output stops working completely for other apps too, it works when I switch to digital output on my speakers, also doesn't work when GPU is selected only CPU.

**Comment by w-okada** [comment]
I've never heard of this issue before and was unable to replicate it. Let's see if any other users report the same phenomenon.

**Comment by JoleBole11** [comment]
I managed to fix it by going into realtek audio control, device advanced settings and turning disable front panel jack detection on and off again, that makes my sound come back for some reason and I have to do it every time I switch voice and GPU does work I just didn't realize it took a while to load hopefully if someone else gets this problem this could be a possible fix.

**Comment by w-okada** [comment]
Okay, Close
