### ISSUE TITLE
Stuck in endless loading.

### ISSUE THREAD

**Issue by RequirePants** [w-okada/voice-changer#622]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11

### OS

Windows 11

### GPU

ASUS RTX 2070 SUPER

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

onnx

### Situation

The bat file never starts installing the files necessary to run the program. It's just stuck at: MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json

I've let the pc on for a night, and nothing happened. 
I'm using CUDA 11.8, PyTorch '2.0.1+cu118'. Python 3.10.11 and also tried python 3.11.1.
I've tried installing it on my laptop, it worked, but it has no pytorch and it started giving different errors. But I'm not sure why it worked on my laptop and not my pc, as ive installed the same python and pytorch versions.

**Comment by w-okada** [comment]
I'm not entirely certain, but there's a possibility that your antivirus software might be interfering. You could try disabling it at your own risk.
