### ISSUE TITLE
Client closed.

### ISSUE THREAD

**Issue by olyng07** [w-okada/voice-changer#623]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu cuda_v.1.5.3.11.zip

### OS

Windows 10

### GPU

Nvidia geforce RTX 3060 ti

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

MMVC

### Model type

idk what this is asking for

### Situation

After having some problems with librosa where i had to copy files from the python lib site packages into the librosa folder in the MMVCserverSIO\librosa, i got the cmd to move past a crash. But now i get a new issue after it has finished installing stuff, the CMD says:
Microsoft Windows [Version 10.0.19045.3208]
(c) Microsoft Corporation. All rights reserved.

C:\Users\olyng\Documents\yoyoyo\MMVCServerSIO>start_http.bat

C:\Users\olyng\Documents\yoyoyo\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Voice Changerを起動しています。
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/
client closed.
C:\Users\olyng\Documents\yoyoyo\MMVCServerSIO>

i have no idea why this is happening and i dont see any crash log file or anything like that.

![image_2023-08-02_232819296](https://github.com/w-okada/voice-changer/assets/141279450/29ce564f-a8e5-40f8-a9c6-00920078040d)

**Comment by w-okada** [comment]
>  some problems with librosa where i had to copy files from the python lib site packages into the librosa folder in the MMVCserverSIO\libros

I don't know the problems you said. If the file configuration has been changed, I wouldn't understand anything.

**Comment by olyng07** [comment]
The only changes i made was to move files from 
C:\Users\olyng\AppData\Local\Programs\Python\Python310\Lib\site-packages\librosa 
to
C:\Users\olyng\Documents\yoyoyo\MMVCServerSIO\librosa
because i got error message when trying to launch the start_http.bat file which said the labrosa folder was missing necessary files
![image_2023-08-03_031950956](https://github.com/w-okada/voice-changer/assets/141279450/0333c122-2b75-4dda-8c03-859b63b59499)

**Comment by w-okada** [comment]
same

https://github.com/w-okada/voice-changer/issues/567
