### ISSUE TITLE
Default models work for me, downloaded models don't

### ISSUE THREAD

**Issue by Glazedhamster** [w-okada/voice-changer#625]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.11

### OS

Win 10

### GPU

Radeon RX 6600

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

The default voices work well, but every model I download sounds very choppy and delayed. Furthermore, the res value just builds up well into 5 digits of ms when trying to use those models. Any idea what I might be doing wrong here?

**Comment by w-okada** [comment]
download model is pytorch model. AMD GPU is supported only for onnx model.
Convert the model to onnx. 
How to convert is described in tutorial.

**Comment by Glazedhamster** [comment]
> download model is pytorch model. AMD GPU is supported only for onnx model. Convert the model to onnx. How to convert is described in tutorial.

Works like a charm now. Many thanks!
