### ISSUE TITLE
invalid memory

### ISSUE THREAD

**Issue by Peeman123456** [w-okada/voice-changer#630]
### Issue Type

Bug Report, Others

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11.zip

### OS

windows 11

### GPU

RTX 3060

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

It says that it had insufficient memory and then created a memory dump. i have the file of the memory dump but GitHub does not support TMP files.

**Comment by w-okada** [comment]
情報が少なすぎて対応ができません。コンソールに何も出ませんか？

**Comment by w-okada** [comment]
There isn't enough information to handle this. Is there nothing showing up on the console?

**Comment by w-okada** [comment]
no res close
