### ISSUE TITLE
the device didn't detect my gpu

### ISSUE THREAD

**Issue by pepperman-vic** [w-okada/voice-changer#632]
### Issue Type

Bug Report

### vc client version number

1.5.3.11

### OS

window 11

### GPU

intel(R) iris(R) xe graphic

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

I use the default setting

### Model type

I don't know I just boost up the app and use

### Situation

the app didn't detect the gpu on the gpu selection menu there's only one option that is cpu

**Comment by w-okada** [comment]
If so, intel xe graphic maybe not supported.

**Comment by w-okada** [comment]
Did you use directml version?

**Comment by w-okada** [comment]
no res close
