### ISSUE TITLE
Frequent errors occur. Please check if the model of the framework is being targeted is loaded.

### ISSUE THREAD

**Issue by Grace-CuteTaylor** [w-okada/voice-changer#635]
I have just installed this program for the first time on Windows 11 and got the "Frequent errors occur. Please check if the model of the framework is being targeted is loaded."

I have a RTX 2060, and I don't know what this issue means nor how I can fix it. Any help would be appreciated.

Thank you!

**Comment by w-okada** [comment]
use issue template
