### ISSUE TITLE
'MMVCServerSIO.exe' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by ShxckzGotIt** [w-okada/voice-changer#636]
### Issue Type

Bug Report

### vc client version number

1.5.3.11

### OS

Windows 10

### GPU

NVIDIA GeForce RTX 3070

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

no

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

*I click start_http and it doesn't open, it flashes for a second and then it closes, and then when I try to run it in command prompt it says *'MMVCServerSIO.exe* is not recognized as an internal or external command, operable program or batch file. and I don't know how to fix that.*

**Comment by w-okada** [comment]
There isn't enough information to handle this. Is there nothing showing up on the console?

**Comment by ShxckzGotIt** [comment]
no, nothings showing up. When I click the start file, command prompt opens for one second then closes, I don't know what's going on because it was working fine before to the point where I could use the voice changer and import my own Ai voices in it, it just stopped working after trying to use it for a 3rd time. I reset my computer and it started happening.

**Comment by ShxckzGotIt** [comment]
wait I didn't mean to close it lmao

**Comment by w-okada** [comment]
try to delete stored_setting.json

**Comment by ShxckzGotIt** [comment]
alright i'll try

**Comment by ShxckzGotIt** [comment]
I just downloaded the new version and replaced 11 for 12 and it seems to be working when I click start_https, but I get the same problem when I try to click start_http. Where would I find stored_setting.json because I didn't find it in files.

**Comment by lucaspwj** [comment]
Exact same issue can someone help me?
