### ISSUE TITLE
[Voice Changer] device detection error, fallback to cpu

### ISSUE THREAD

**Issue by hpx502766238** [w-okada/voice-changer#637]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.11

### OS

Windows11

### GPU

AMD Ryzen 7 5800H with Radeon(TM)Graphics

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC,DiffusionSVC

### Model type

f0,ONNX

### Situation

An error message in terminal when started：【[Voice Changer] device detection error, fallback to cpu】
I use dio for F0 detection.
The AMD GPU works,but it seems that only part of the tasks work on GPU,GPU usage is about 50%.There is a high CPU usage(about 50% up to 80%),and The CPU usage is 30% higher when use DiffusionSVC than RVC.

**Comment by w-okada** [comment]
use dio, don't use index, increase CHUNK, decrease EXTRA.

**Comment by hpx502766238** [comment]
> use dio, don't use index, increase CHUNK, decrease EXTRA.

I was actually testing under this setting,dio F0,0 index, 768 CHUNK,4096 EXTRA.
1.GPU AMD Radeon Vega 8,dio F0,0 index, 768 CHUNK,4096 EXTRA【CPU:up to 65%,GPU:up to 50%】
2.GPU Nvidia RTX 3060,dio F0,0 index, 768 CHUNK,4096 EXTRA【CPU:up to 40%,GPU:up to 30%】
3.Another issue,when I switch Nvidia to AMD,the VRAM on nvidia cannot be released,but in the contrary,switch AMD to Nvidia,the  VRAM on AMD can be released.

**Comment by w-okada** [comment]
> 1.GPU AMD Radeon Vega 8,dio F0,0 index, 768 CHUNK,4096 EXTRA【CPU:up to 65%,GPU:up to 50%,device detection error】


Have you use onnxdirectML version with onnx model? I didn't expect that message to come up.


https://github.com/w-okada/voice-changer/blob/56944ad594eb265eba813ab54afa5e1487d67f74/server/voice_changer/RVC/deviceManager/DeviceManager.py#L36

**Comment by hpx502766238** [comment]
> > 1.GPU AMD Radeon Vega 8,dio F0,0 index, 768 CHUNK,4096 EXTRA【CPU:up to 65%,GPU:up to 50%,device detection error】
> 
> Have you use onnxdirectML version with onnx model? I didn't expect that message to come up.
> 
> https://github.com/w-okada/voice-changer/blob/56944ad594eb265eba813ab54afa5e1487d67f74/server/voice_changer/RVC/deviceManager/DeviceManager.py#L36

Sorry,I forgot that DiffusionSVC is a pytorch model.
But can you add an feature to export it to onnx?
In additon,rmvpe need exported to onnx,it is quite faster than pytorch.

**Comment by w-okada** [comment]
At the moment, there are no plans. For now, the original issue has been resolved, so if needed, please open a new issue as a feature request.
