### ISSUE TITLE
don't want to start

### ISSUE THREAD

**Issue by AK2G00D** [w-okada/voice-changer#638]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11.zip

### OS

Windows 10

### GPU

NVIDIA GeForce GTX 1660

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

no

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

IDK

### Situation

I installed it the first time and ran it. when the it was installing the loading froze so I uninstalled it and reinstalled it now it don't want to run at all. other versions don't work also.

**Comment by w-okada** [comment]
There isn't enough information to handle this. Is there nothing showing up on the console?

**Comment by AK2G00D** [comment]
the console don't open

**Comment by AK2G00D** [comment]
is there a way to fix this?

**Comment by w-okada** [comment]
I have no idea. try re-install.

**Comment by pelsonmandela** [comment]
Nevermind, you just have to wait very long

**Comment by AK2G00D** [comment]
fixed it.it was just blocked

**Comment by help-needed** [comment]
@AK2G00D i have this problem and I'm not sure if the resident is blocked, how could i check if it is?
![Screenshot 2024-03-21 185454](https://github.com/w-okada/voice-changer/assets/164440084/fc75ff10-b746-44e6-bc13-94fa6abcc630)
 not sure if the resident is blocked, how could i check if it is?
