### ISSUE TITLE
Crashes immediately after launching

### ISSUE THREAD

**Issue by Kalamarnicaa** [w-okada/voice-changer#639]
### Issue Type

Others

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11.zip

### OS

Windows 10

### GPU

RTX 4070Ti

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

MMVC v.1.3

### Model type

pyTorch

### Situation

When I try to open  MMVCServerSIO.exe as an administrator it crashes immediately. 
I managed to take a sceenshot of the console before it dissapeared.

![crash](https://github.com/w-okada/voice-changer/assets/141530686/2476fbc1-14cd-4ee0-9033-7405bcaac20d)

### application window capture

![crash](https://github.com/w-okada/voice-changer/assets/141530686/e0d9442a-05d0-40d9-8d16-043a110baf30)

### logs on terminal

terminal closes immediately

**Comment by w-okada** [comment]
If your folder path include special character such as "space", eliminate them.

**Comment by Kalamarnicaa** [comment]
Yeah, figured out It doesn't like long, weird folder names. Moved files to simple path C:\MMVCServerSIO, still doesn't work.

**Comment by w-okada** [comment]
Okay great. So I'll close this issue

**Comment by Kalamarnicaa** [comment]
It's still not working.
