### ISSUE TITLE
Connection broken: IncompleteRead, PytorchStreamReader failed reading zip archive

### ISSUE THREAD

**Issue by bjork99fan** [w-okada/voice-changer#643]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12.zip

### OS

Windows 11

### GPU

NVIDIA GeForce GTX 1660 SUPER

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

The GUI loads fine but nothing works. I think I am missing dependencies whenever I install using the .bat

### logs on terminal

C:\Users\small\Documents\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
  4%|▎         | 6.69M/181M [00:01<00:39, 4.59MB/s]('Connection broken: IncompleteRead(12729152 bytes read, 365820999 more expected)', IncompleteRead(12729152 bytes read, 365820999 more expected))
  3%|▎         | 12.0M/361M [00:02<00:38, 9.46MB/s]('Connection broken: IncompleteRead(12518222 bytes read, 44307208 more expected)', IncompleteRead(12518222 bytes read, 44307208 more expected))
 14%|█▍        | 7.52M/54.1M [00:02<00:09, 5.13MB/s]('Connection broken: IncompleteRead(8049483 bytes read, 48674744 more expected)', IncompleteRead(8049483 bytes read, 48674744 more expected))
                                                    ('Connection broken: IncompleteRead(7277837 bytes read, 182230072 more expected)', IncompleteRead(7277837 bytes read, 182230072 more expected))
('Connection broken: IncompleteRead(10836156 bytes read, 368052697 more expected)', IncompleteRead(10836156 bytes read, 368052697 more expected))
('Connection broken: IncompleteRead(16427651 bytes read, 72557139 more expected)', IncompleteRead(16427651 bytes read, 72557139 more expected))

('Connection broken: IncompleteRead(8888183 bytes read, 172301504 more expected)', IncompleteRead(8888183 bytes read, 172301504 more expected))                           [Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] Downloading model files...
 84%|████████▍ | 44.5M/52.8M [00:08<00:01, 4.47MB/s]('Connection broken: IncompleteRead(43002241 bytes read, 294097738 more expected)', IncompleteRead(43002241 bytes read, 294097738 more expected))
 73%|███████▎  | 38.8M/52.8M [00:08<00:04, 3.61MB/s('Connection broken: IncompleteRead(31668427 bytes read, 204017770 more expected)', IncompleteRead(31668427 bytes read, 204017770 more expected))
 86%|████████▌ | 45.3M/52.8M [00:08<00:01, 5.16MB/s]('Connection broken: IncompleteRead(26066178 bytes read, 10055775 more expected)', IncompleteRead(26066178 bytes read, 10055775 more expected))
                                                    [Voice Changer] Generating metadata...
[Voice Changer] ONNX Model: Official v2 like73MB/s]
[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] custom matplotlib loaded successfully
    [Voice Changer] loading sample failed PytorchStreamReader failed reading zip archive: failed finding central directory
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
[VCClient] wait web server... done 200
[2023-08-05 22:08:58] connet sid : 7UgMQbymEE6U5AM9AAAB
[2023-08-05 22:08:58] connet sid : Uce6G9YSKcRhDAKkAAAD
[Voice Changer] update configuration: modelSlotIndex 1691291342000
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cpu
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 30, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cuda:0
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 30, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by w-okada** [comment]
It seems like the necessary files have not been downloaded. Please review your network settings.

**Comment by Rx1nCreations** [comment]
i think its our gpu man ive tested this on 2 computers with a gtx 1660 super when i switched to a 3080 it just worked so try using cpu idk

**Comment by bjork99fan** [comment]
> i think its our gpu man ive tested this on 2 computers with a gtx 1660 super when i switched to a 3080 it just worked so try using cpu idk

i ended up setting the command prompts priority to high and then it worked

**Comment by w-okada** [comment]
ok close
