### ISSUE TITLE
Server VS Client Inference

### ISSUE THREAD

**Issue by MrFelt** [w-okada/voice-changer#647]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12

### OS

Windows 11 build 22621

### GPU

RTX 3060

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC V2 48K

### Model type

pyTorch, f0

### Situation

When run natively on the host computer, audio is full. When run in client mode, audio is "muffled" sounding. The bass and treble of the output audio are a bit weak. There are no obvious errors, but audio quality is degraded when running on a remote computer. This especially affects the input to the program. Both computers are on the local network and are connected to each other by a 1 gigabit network switch. There is no possibility of firewall issues or dropouts.

//

ホストコンピュータでネイティブに実行すると、オーディオはフルです。クライアントモードで実行すると、オーディオは「こもった」音になる。出力オーディオの低音と高音が少し弱い。明らかなエラーはありませんが、リモートコンピューター上で実行するとオーディオの品質が低下します。これは特にプログラムへの入力に影響します。どちらのコンピューターもローカルネットワーク上にあり、1ギガビットのネットワークスイッチで互いに接続されています。ファイアウォールの問題やドロップアウトの可能性はありません。

私は日本語を話せませんが、もし参考になるのであれば、私の翻訳した説明を残しておこうと思いました。

### logs on terminal

No errors, running as normal

**Comment by MrFelt** [comment]
I think the bit rate or compression algorithm is too strong when sending the client's audio to the server for inference.

//

推論のためにクライアントの音声をサーバーに送るとき、ビットレートか圧縮アルゴリズムが強すぎると思う。

**Comment by w-okada** [comment]
I don't have a particularly good ear for music, so I'm having a hard time understanding what you're pointing out. If it's a problem with pitch, there could be issues with estimating F0. How about attempting to use RMVPE for F0 detection?

**Comment by MrFelt** [comment]
This is with RMVPE for both server and client usage. I'm 99% certain that it's a live audio compression thing because sending a file for inference using client mode does not replicate it.

**Comment by w-okada** [comment]
The handling of the microphone in client mode relies on Chrome's functionality, so it may be due to Chrome's restrictions. At the moment, we do not know how to address this issue.

**Comment by MrFelt** [comment]
I will look into it and see if I can find something regarding this. Thank you for the insight, I will post back if I find something.

**Comment by MrFelt** [comment]
So by my thoughts and logic:

https://github.com/w-okada/voice-changer/blob/56944ad594eb265eba813ab54afa5e1487d67f74/recorder/src/002_hooks/012_useMediaRecorder.ts#L182

Both echo cancellation and noise suppression are enabled by default using MediaRecorder? Or do the settings within the UI set these? 
![image](https://github.com/w-okada/voice-changer/assets/116107934/801581d6-0b25-4471-8e0b-b9996759d0ba)

**Comment by MrFelt** [comment]
Nevermind to the last, I believe this might have fixed it, below are the flags I changed.

![image](https://github.com/w-okada/voice-changer/assets/116107934/2f76c65f-bb90-4873-8615-abbfae2c969a)
