### ISSUE TITLE
Pressing Start hangs the application, stuck at "Generated strengths: for prev:(4096,), for cur:(4096,)"

### ISSUE THREAD

**Issue by tamayaren** [w-okada/voice-changer#662]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.12

### OS

Windows 10

### GPU

RTX 3060 Ti

### Clear setting

no

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

MMVC

### Model type

ONNX

### Situation

The application just wouldn't even work at all. I tried both DirectML and the CUDA version. Everything else runs fine, until I press start it just won't ever load at all. Pressing anything on the app doesn't do anything, afterwards. If I close the application, it won't start again unless I restart my computer.

### logs on terminal

C:\Users\wwwan\Documents\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
                                                                                                                       [Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] Downloading model files...
                                                                                                                       [Voice Changer] Generating metadata...
[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] custom matplotlib loaded successfully
 [Loading] model_dir\4\combo_spk5_nl3_dl20_k50_500ep.ptc.bin
 [Loading] model_dir\5\combo_spk5_nl3_dl1_k50_500ep.ptc.bin
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[VCClient] wait web server... done 200
[2023-08-07 23:43:41] connet sid : Md2LZFfQ_Y56l7MeAAAB
[2023-08-07 23:43:41] connet sid : X9XPV51HZQac_hv1AAAD
[Voice Changer] update configuration: gpu 0
[Voice Changer] update configuration: modelSlotIndex 1691423032000
[Voice Changer] model slot is changed -1 -> 0
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:CPU-DML)
[Voice Changer][RVCr2] Initializing...
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x00000227D91DE800>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x00000227F95386A0>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x00000227F9538730>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
2023-08-07 23:43:59.7471311 [W:onnxruntime:, session_state.cc:1169 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-08-07 23:43:59.7563295 [W:onnxruntime:, session_state.cc:1171 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] generate new embedder. (anyway)
2023-08-07 23:44:01.0612393 [W:onnxruntime:, session_state.cc:1169 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-08-07 23:44:01.0692128 [W:onnxruntime:, session_state.cc:1171 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x00000227D71E2D40>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x00000227D71E1FC0>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x00000227D71E25C0>
Pipeline has been deleted
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings modelSlotIndex:1691423032000
Generated Strengths: for prev:(4096,), for cur:(4096,)

**Comment by w-okada** [comment]
try cuda version.

**Comment by w-okada** [comment]
It takes some time to start up initially. How long did you wait?

**Comment by tamayaren** [comment]
How long do you have to initially wait? I tried waiting for 2 minutes.

**Comment by w-okada** [comment]
try this
https://github.com/w-okada/voice-changer/blob/master/tutorials/trouble_shoot_communication_ja.md

**Comment by w-okada** [comment]
no res close
