### ISSUE TITLE
[VCClient] wait web server...

### ISSUE THREAD

**Issue by Plexiate** [w-okada/voice-changer#664]
solved

**Comment by aaronjamt** [comment]
Will you please provide information on how you solved the issue? I've been having the exact same issue and that would be very helpful. Thanks!

**Comment by Draifu** [comment]
do you have the solution? i'm also stuck

**Comment by Plexiate** [comment]
Are you guys both on Mac? I found the solution was to use the command "sh HTTPS_FILE_PATH_HERE" and it would start fine after that.

**Comment by masondaniels** [comment]
delete stored_setting.json
