### ISSUE TITLE
When I open start_http it opens for a milisecond then closes immediately

### ISSUE THREAD

**Issue by OathMeal10** [w-okada/voice-changer#666]
### Issue Type

Bug Report

### vc client version number

1.5.3.11

### OS

Windows 11

### GPU

1650 TI

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

MMVC

### Model type

ONNXgpuCuda

### Situation

When I open the start_http bat file it opens for a milisecond then closes.
I dont know what step I could do to run it

### application window capture

![Screenshot (78)](https://github.com/w-okada/voice-changer/assets/112765583/76c74f07-9ebc-49fa-95ab-d85ae7d387fa)

### logs on terminal

![Screenshot (78)](https://github.com/w-okada/voice-changer/assets/112765583/76c74f07-9ebc-49fa-95ab-d85ae7d387fa)

**Comment by waSStyle** [comment]
same problem

**Comment by 1Hibiki1** [comment]
I don't know if this is related, but I'm having a similar issue with a fresh download of v1.5.3.12a. Running it in PS gives me this:

![image](https://github.com/w-okada/voice-changer/assets/43519087/bf33892c-702e-4928-abc6-10b0c8b82572)

Couldn't find anything about 'beatrice_internal_api' anywhere though.

**Comment by DashCee** [comment]
The program is trying to run without the necessary python dependences (beatrice_internal_api)

What worked for me:
1. Install python https://www.python.org/downloads/windows/
2. Run the start_http.bat file into a the CMD that you have ran as administrator (Should look like this C:\Users\Cee>"C:\Users\Username\Desktop\start_http.bat", with the path updated to wherever the file may be)

You don't happen to be the vtuber Oathmeal by chance? (─‿‿─)

**Comment by waSStyle** [comment]
it didnt worked to me

**Comment by w-okada** [comment]
run from temrinal and check error message.

**Comment by OathMeal10** [comment]
> run from temrinal and check error message.

Ooh it worked, I put it in C drive instead of my D drive and ran it on terminal and it worked.

I will now close the issue ty very much
