### ISSUE TITLE
Server Audio doesn't work

### ISSUE THREAD

**Issue by Babu-Chen** [w-okada/voice-changer#667]
### Issue Type

Question

### vc client version number

MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.12

### OS

Mac M1 Max

### GPU

none

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

Pth

### Situation

<img width="719" alt="截屏2023-08-08 23 53 04" src="https://github.com/w-okada/voice-changer/assets/90047244/7a9c3728-a98a-4da1-b7ce-23134698fb43">
My Server mode does not work. I connected my audio interface with an external microphone. 
The client mode is working fine, just very laggy in every setting. 
I wish to know if is normal or my mistake when setting up.

### logs on terminal

there is no error log in terminal, so that is quite weird

**Comment by Babu-Chen** [comment]
> use dio and increase chunk decreace extra
I have tried all the adjustments.... it seems the Server just doesn't work

**Comment by w-okada** [comment]
Use client mode

**Comment by w-okada** [comment]
no res close
