### ISSUE TITLE
How to change pth model to onnx model

### ISSUE THREAD

**Issue by DarkenHunter** [w-okada/voice-changer#668]
### Issue Type

Question

### vc client version number

v.1.5.3.12

### OS

Windows 11

### GPU

RX 6800XT

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC, so vits 40

### Model type

ONNX

### Situation

How to change pth model to onnx model. Pth models are much heavy and requires lots of processing in my mac m1 works fine on my PC. Need to convert pth model to onnx model for better performance,

### application window capture

.

### logs on terminal

.

**Comment by Mojobones** [comment]
Use the "export to onxx" button on the UI.

**Comment by w-okada** [comment]
no update close
