### ISSUE TITLE
localhost refused connection 

### ISSUE THREAD

**Issue by antho6k** [w-okada/voice-changer#669]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.12

### OS

windows 10

### GPU

RX 580 8G

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

onnx

### Situation

i can't open the app it's said wait web server http://127.0.0.1:18888 and on the navigator i got a error 127.0.0.1 refused the connection 

### application window capture

![image](https://github.com/w-okada/voice-changer/assets/141765341/c12af655-fdd0-4fa2-9440-6cbdb3257035)

### logs on terminal

[vvclient.log](https://github.com/w-okada/voice-changer/files/12294426/vvclient.log)

**Comment by antho6k** [comment]
i've try to  disable firewall and that's happened
![image](https://github.com/w-okada/voice-changer/assets/141765341/2f08f77c-0416-4860-a83f-e338ca4b0476)

**Comment by Uahn** [comment]
similar problem, antivirus is disabled, firewall settings do not affect the result, changing the port did not solve the issue either

**Comment by w-okada** [comment]
try delete stored_setting.json

**Comment by Misaki-Ki** [comment]
I had this issue briefly. I suspect it needs to be ran with administrator rights at least once.

**Comment by w-okada** [comment]
no res close
