### ISSUE TITLE
worked for a few mins then ran into an issue

### ISSUE THREAD

**Issue by itmc0** [w-okada/voice-changer#671]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12.zip

### OS

Windows 10

### GPU

nvidia 3080 10gb

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

rvc

### Model type

onnx

### Situation

can not use 32 chunk on any rvc model i think(including base models) i tried reinstalling and still doesn't work. it did work for a while beforehand but then it just suddenly started doing this.

spams into cmd-
 Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 252, in on_request
ValueError: operands could not be broadcast together with shapes (3840,) (4096,)
[Voice Changer] VC PROCESSING EXCEPTION!!! operands could not be broadcast together with shapes (3840,) (4096,)
operands could not be broadcast together with shapes (3840,) (4096,)

### application window capture

![image](https://github.com/w-okada/voice-changer/assets/71417050/0f690cac-b72d-4732-8a30-fb5a9dbf0178)

### logs on terminal

Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 252, in on_request
ValueError: operands could not be broadcast together with shapes (3840,) (4096,)
[Voice Changer] VC PROCESSING EXCEPTION!!! operands could not be broadcast together with shapes (3840,) (4096,)
operands could not be broadcast together with shapes (3840,) (4096,)
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 252, in on_request
ValueError: operands could not be broadcast together with shapes (3840,) (4096,)
[Voice Changer] VC PROCESSING EXCEPTION!!! operands could not be broadcast together with shapes (3840,) (4096,)
operands could not be broadcast together with shapes (3840,) (4096,)
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 252, in on_request
ValueError: operands could not be broadcast together with shapes (3840,) (4096,)
[Voice Changer] VC PROCESSING EXCEPTION!!! operands could not be broadcast together with shapes (3840,) (4096,)
operands could not be broadcast together with shapes (3840,) (4096,)
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 252, in on_request
ValueError: operands could not be broadcast together with shapes (3840,) (4096,)
[Voice Changer] VC PROCESSING EXCEPTION!!! operands could not be broadcast together with shapes (3840,) (4096,)
operands could not be broadcast together with shapes (3840,) (4096,)
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 252, in on_request
ValueError: operands could not be broadcast together with shapes (3840,) (4096,)
[Voice Changer] VC PROCESSING EXCEPTION!!! operands could not be broadcast together with shapes (3840,) (4096,)
operands could not be broadcast together with shapes (3840,) (4096,)
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 252, in on_request
ValueError: operands could not be broadcast together with shapes (3840,) (4096,)
[Voice Changer] VC PROCESSING EXCEPTION!!! operands could not be broadcast together with shapes (3840,) (4096,)
operands could not be broadcast together with shapes (3840,) (4096,)
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 252, in on_request
ValueError: operands could not be broadcast together with shapes (3840,) (4096,)
[Voice Changer] VC PROCESSING EXCEPTION!!! operands could not be broadcast together with shapes (3840,) (4096,)
operands could not be broadcast together with shapes (3840,) (4096,)
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 252, in on_request
ValueError: operands could not be broadcast together with shapes (3840,) (4096,)
[Voice Changer] VC PROCESSING EXCEPTION!!! operands could not be broadcast together with shapes (3840,) (4096,)
operands could not be broadcast together with shapes (3840,) (4096,)
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 252, in on_request
ValueError: operands could not be broadcast together with shapes (3840,) (4096,)
[Voice Changer] VC PROCESSING EXCEPTION!!! operands could not be broadcast together with shapes (3840,) (4096,)
operands could not be broadcast together with shapes (3840,) (4096,)
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 252, in on_request
ValueError: operands could not be broadcast together with shapes (3840,) (4096,)
[Voice Changer] VC PROCESSING EXCEPTION!!! operands could not be broadcast together with shapes (3840,) (4096,)
operands could not be broadcast together with shapes (3840,) (4096,)
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 252, in on_request
ValueError: operands could not be broadcast together with shapes (3840,) (4096,)
[Voice Changer] VC PROCESSING EXCEPTION!!! operands could not be broadcast together with shapes (3840,) (4096,)
operands could not be broadcast together with shapes (3840,) (4096,)
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 252, in on_request
ValueError: operands could not be broadcast together with shapes (3840,) (4096,)
[Voice Changer] VC PROCESSING EXCEPTION!!! operands could not be broadcast together with shapes (3840,) (4096,)
operands could not be broadcast together with shapes (3840,) (4096,)
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 252, in on_request
ValueError: operands could not be broadcast together with shapes (3840,) (4096,)

**Comment by Eidenz** [comment]
I believe you are trying to go way too low in chunks. It is not surprising to see errors if you set your chunk below 48/64 (even on a 3080).
Does it work well if you raise it to 48 or more?

**Comment by w-okada** [comment]
no update close
