### ISSUE TITLE
"TORCH_USE_CUDA_BSA"

### ISSUE THREAD

**Issue by Tabo71** [w-okada/voice-changer#672]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12.zip

### OS

Windows 10

### GPU

Nvidia GeForce GT 730

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

no

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

It keeps showing up everytime I start or stop the voice changer. I do not know how to fix this since I am very new to this kind of stuff. It keeps saying "TORCH_USE_CUDA_BSA" which I tried downloading cuda toolkit (I dont know if that relates to the problem or not) to see if itll work and it didnt. I also downloaded pyTorch which also did not fix the problem. I tried everything but nothing seems to work, I followed every step in the internet how to download this voice changer but they dont show how to fix this problem.

### application window capture

![image](https://github.com/w-okada/voice-changer/assets/81661075/700e0eac-ab96-4e23-8a16-26b574e276ff)

### logs on terminal

CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 212, in on_request
  File "voice_changer\RVC\RVCr2.py", line 197, in inference
  File "voice_changer\RVC\pipeline\Pipeline.py", line 107, in exec
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by Eidenz** [comment]
Your GPU seems to be too old to run the software. The GT 730 is incompatible with the latest CUDA versions.

**Comment by w-okada** [comment]
no update, close
