### ISSUE TITLE
After installing and using RVC my main mic has become lower in volume

### ISSUE THREAD

**Issue by darthwiper** [w-okada/voice-changer#673]
### Issue Type

Bug Report

### vc client version number

the newest

### OS

windows 10

### GPU

3080

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

the newest

### Situation

Greetings,

One evening, I decided to try out the RVC Voice Changer and spent some time experimenting with it. However, the following day when I logged onto Discord, I noticed that everyone was commenting on how my microphone audio had become significantly quieter compared to before. They mentioned that it sounded as if I were speaking from a distant room. Despite checking my Discord settings, I found that nothing had been altered; everything was configured just as it had always been. Remarkably, this issue only arose after I had used the RVC Voice Changer. Regrettably, I'm uncertain about the steps I should take to rectify this problem. Your guidance would be greatly appreciated.

### logs on terminal

i dont have any sorry

**Comment by Eidenz** [comment]
RVC does not alter your audio settings in any way.

Are you sure you didn't install an extra software to use it that changed your audio?

**Comment by Rafacasari** [comment]
Maybe your windows automatically decreased your microphone volume, some microphones/drivers do this to prevent extremely loud voices, check your device settings

https://answers.microsoft.com/en-us/windows/forum/all/prevent-3rd-party-applications-from-adjusting/52ab3c09-d850-4fd7-ba6d-1c97cf1639e2

**Comment by SmartDogo** [comment]
i have the exactly same problem im using only virtual cables and i tried to change alot of configs on it to solve it but nothing heçlps, i also download another virtual cable from other place but the same problem happens

**Comment by w-okada** [comment]
no res close.
