### ISSUE TITLE
Output is monitoring and if I put on monitor I can hear myself twice

### ISSUE THREAD

**Issue by highfiveghost12** [w-okada/voice-changer#675]
### Issue Type

Bug Report, Question, Others

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12

### OS

windows 11

### GPU

RTX 3050

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC I  Think

### Model type

pyTorch

### Situation

So I have my input as my mic and the output as my VB-Cable and it worked I tested it and everything with monitor, my obs and discord were working with it then I went to sleep and the next day I opened everything turned off monitor to none then started speaking to get things going but now I can hear my voice that I pick and when I turn on monitor I can hear myself twice now, How can I make it go back to the way it was where the output was my vb-cable and it wasn't monitoring it so I can just use the voice for discord and recording videos.
![img3](https://github.com/w-okada/voice-changer/assets/141593044/081e7233-73ab-4bfb-8dbc-5662bbde9b46)
![img4](https://github.com/w-okada/voice-changer/assets/141593044/902d34f5-a86b-42f2-8a60-bd56c802dc75)
![Img1](https://github.com/w-okada/voice-changer/assets/141593044/21083cba-2c4e-465c-a4d6-7515ea828a7b)
![img2](https://github.com/w-okada/voice-changer/assets/141593044/d4b43d0f-3d8c-431d-b527-a3db9fd14a8c)

### logs on terminal

C:\Zai Voice Changer\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
Pipeline has been deleted
[VCClient] wait web server... done 200
[2023-08-09 16:35:27] connet sid : MstsQCLbGeHdTQQ-AAAC
[2023-08-09 16:35:27] connet sid : rjjMY-7bLhqXi-pRAAAD

**Comment by w-okada** [comment]
I have no idea

**Comment by highfiveghost12** [comment]
fair enough

**Comment by napiquet** [comment]
That often happens when you install VB Virtual Audio Cable and don't restart your PC. Restart it first and see if it fixes it.

**Comment by w-okada** [comment]
ok close
