### ISSUE TITLE
wait web server infinite

### ISSUE THREAD

**Issue by Thanoszebi** [w-okada/voice-changer#678]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.12.zip

### OS

MAC m1

### GPU

apple m1

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

not lauching

### Model type

idk

### Situation

r

### application window capture

r

### logs on terminal

wait web server

**Comment by dogdie233** [comment]
same situation, but im windows;
i close my terminal and it cant run; wwwww
if i run `netstat -aon | findstr 18888` on cmd, i cant find any process

**Comment by dogdie233** [comment]
Ok, i find some clue in `vvclient.log`
> 2023-08-10 13:22:38,196 - vcclient - ERROR - 35216 - [Voice Changer] Web Server Launch Exception, 'gbk' codec can't decode byte 0xaa in position 82: illegal multibyte sequence
i change the model name that save in `params.json`

**Comment by w-okada** [comment]
show me log onthe terminal

**Comment by w-okada** [comment]
no res close
