### ISSUE TITLE
APO Equalizer doesn't work in Client AUDIO mode

### ISSUE THREAD

**Issue by Smokyyy** [w-okada/voice-changer#681]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12a.zip

### OS

Windows 10 pro, 22H2, 19045.3208

### GPU

RTX 4060

### Clear setting

no

### Sample model

yes

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

f0, pyTorchRVCv2

### Situation

While Voice Changer AUDIO is in Client mode, you can't process the input audio with an APO Equalizer. You can't remove background noise first to get a clearer AI voice out. This method works if you select Server mode and then any audio device under any driver other than MME. It seems like MME audio driver is unaffected by audio processing and it also seems like Client mode uses MME and the problem is that you can't select another in Client settings.

I'd use Server setting, but I can't use it since I run VC on my secondary PC and I connect from my main pc via the browser.

I've tested by using Passthru setting and by recording my voice in the application, compared to Windows recroding device playback and from discord mic test. Tested it with an another user who had the same result as me.

### logs on terminal

[Voice Changer] generate new embedder. (anyway)
2023-08-10 10:23:14.7392072 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-08-10 10:23:14.7446554 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] Loading index...
Try loading... model_dir\6\added_IVF256_Flat_nprobe_1_veibae_v2.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x0000027712677DC0>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x00000277031B1ED0>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x00000277031B1F30>
Pipeline has been deleted
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings f0Detector:rmvpe
[Voice Changer][RVC]: update_settings silentThreshold:0.00015
[Voice Changer][RVC]: update_settings extraConvertSize:65536
[Voice Changer][RVC]: update_settings serverReadChunkSize:112
[Voice Changer][RVC]: update_settings enableServerAudio:0
[Voice Changer][RVC]: update_settings serverAudioSampleRate:48000
[Voice Changer][RVC]: update_settings modelSlotIndex:1691651063006
[2023-08-10 10:24:50] connet sid : RzzJk_hc-TTxamjaAAAC
[2023-08-10 10:24:50] connet sid : u7gMdvFRtdr8QDHbAAAD
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] warming up... generating sola buffer.
[Voice Changer] update configuration: passThrough true
[Voice Changer][RVC]: update_settings passThrough:true
[Voice Changer] update configuration: passThrough false
[Voice Changer][RVC]: update_settings passThrough:false

**Comment by w-okada** [comment]
I'm not familiar with APO Equalizer.
The Client mode is using Chrome's microphone feature. Therefore, I believe that APO Equalizer probably can't be used in web conferences and such using Chrome. This means, I think it might be necessary to extend APO Equalizer.

**Comment by Rafacasari** [comment]
I use a separated computer to run the server and I access the client from my browser, so I can not confirm this issue. I'm using APO Equalizer with no problems. 

You can use a program like Voice Meeter to send your Microphone to a another Input device
Like **Your Microphone (with APO Equalizer)** -> **VoiceMeeter Output** -> **Voice Changer** -> VoiceMeeter Input Aux -> VoiceMeeter Output Aux

A small tutorial image, hope you understand!
![image](https://github.com/w-okada/voice-changer/assets/32463720/24e0b391-ca82-476c-bed6-2fceada35ba3)

**Comment by Rafacasari** [comment]
You can use a program like Voice Meeter to send your Microphone to a another Input device
Like **Your Microphone (with APO Equalizer)** -> **VoiceMeeter Output** -> **Voice Changer** -> VoiceMeeter Input Aux -> VoiceMeeter Output Aux

A small tutorial image, hope you understand!
![image](https://github.com/w-okada/voice-changer/assets/32463720/24e0b391-ca82-476c-bed6-2fceada35ba3)

**Comment by Smokyyy** [comment]
Ye I was just thinking of something similar to first process my input with APO EQ -> send it into virtual cable -> use that virtual cable as input in voice changer. That should work. I've tested if APO EQ worked in other chromium applications and from my small tests it seems like its browser problem. Not even EQ APO.

**Comment by w-okada** [comment]
So, this is not bug of this repo. close it.
