### ISSUE TITLE
ImportError: cannot import name 'TypeAlias' from 'typing' (/home/woody/anaconda3/envs/mmvc/lib/python3.9/typing.py)

### ISSUE THREAD

**Issue by RizeKishimaro** [w-okada/voice-changer#682]
### Issue Type

Bug Report

### vc client version number

From Anaconda

### OS

Ubuntu 20.04

### GPU

0000:00:02.0 VGA compatible controller: Intel Corporation Device 9a78 (rev 01)

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

VCClient

### Model type

none

### Situation

I'm sorry for another issue cuz my ubuntu 20.04 was on error after i installed the required packages i tried to run 
python3 MMVCServerSIO.py -p 18888 --https true     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt      --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
`` pip install typing

please help 

### application window capture

![image](https://github.com/w-okada/voice-changer/assets/75617768/95d9edb6-5e81-4c4e-9cdd-fd0939b7f846)

### logs on terminal

Traceback (most recent call last):
  File "/home/woody/voice-changer/server/MMVCServerSIO.py", line 10, in <module>
    from downloader.SampleDownloader import downloadInitialSamples
  File "/home/woody/voice-changer/server/downloader/SampleDownloader.py", line 7, in <module>
    from const import RVCSampleMode, getSampleJsonAndModelIds
  File "/home/woody/voice-changer/server/const.py", line 5, in <module>
    from typing import Literal, TypeAlias
ImportError: cannot import name 'TypeAlias' from 'typing' (/home/woody/anaconda3/envs/mmvc/lib/python3.9/typing.py)

**Comment by Rafacasari** [comment]
Try using Python 3.10 I think

**Comment by w-okada** [comment]
no res close
