### ISSUE TITLE
Can AMD graphics cards use this program?

### ISSUE THREAD

**Issue by Yuzu-io** [w-okada/voice-changer#684]
My computer graphics card is AMD RX6650XT, I don't know if this program can be used, can someone answer my questions?

##### Environment
- Operating System: Windows 11 pro 22h2 22621.1992

**Comment by Rafacasari** [comment]
It should support, but you have to download the correct version, if I'm not wrong its the DirectML version.
I have some friends that have AMD that tried to run but they have a pretty long time of wait to change the voice 🤔 

But it never hurts to try it yourself 😉

**Comment by Yuzu-io** [comment]
Thanks
