### ISSUE TITLE
Uploaded voices don't work properly

### ISSUE THREAD

**Issue by PeterGriffin654** [w-okada/voice-changer#685]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.12

### OS

Windows 10

### GPU

RX 580

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

RVC, ONNX

### Situation

So the default voices work perfectly but an uploaded voice has issues, Most of the time it doesn't even recognise me speaking, but when it does it has an extremely long delay, and also the output can be really choppy, and changing the chunk doesn't do anything.
Sometimes one or two words can be heard perfectly but most of the time it's unusable.
It only happens with uploaded voices as I said.

### application window capture

![Képernyőkép 2023-08-10 141402](https://github.com/w-okada/voice-changer/assets/140738133/25c7874f-2eec-46b0-b966-2ec9b75a21dc)
![Képernyőkép 2023-08-10 141348](https://github.com/w-okada/voice-changer/assets/140738133/f2e4431a-a7be-41fd-a2f6-e47efbadb54f)

### logs on terminal

Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x0000014B4E1B6EF0>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000014B0D0369E0>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x0000014B0D0377F0>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\6\added_IVF108_Flat_nprobe_1_Szili_v2.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x0000014B0A065C60>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000014B0CA02E30>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x0000014B0CA02DD0>
Pipeline has been deleted
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings serverReadChunkSize:640
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings f0Detector:harvest
[Voice Changer][RVC]: update_settings extraConvertSize:4096
[Voice Changer][RVC]: update_settings modelSlotIndex:1691669543006
[Voice Changer] warming up... generating sola buffer.
[Voice Changer] update configuration: serverReadChunkSize 960
[Voice Changer][RVC]: update_settings serverReadChunkSize:960
[Voice Changer] update configuration: modelSlotIndex 1691669603007
[Voice Changer] model slot is changed 6 -> 7
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:False, onnx_device:CPU-DML)
[Voice Changer][RVCr2] Initializing...
Pipeline has been deleted
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\7\added_IVF793_Flat_nprobe_1_EricCartmanV1_v2.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x0000014B0C8F0850>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000014B0A065C60>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x0000014B0A065660>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\7\added_IVF793_Flat_nprobe_1_EricCartmanV1_v2.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x0000014B09FD4190>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000014B0CA586A0>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x0000014B0CA58700>
Pipeline has been deleted
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings serverReadChunkSize:960
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings f0Detector:harvest
[Voice Changer][RVC]: update_settings extraConvertSize:4096
[Voice Changer][RVC]: update_settings modelSlotIndex:1691669603007

**Comment by Rafacasari** [comment]
Try to set F0 det. to **Crepe_Tiny** or **Crepe_Full** and also try to convert the models to onnx. 

![image](https://github.com/w-okada/voice-changer/assets/32463720/92082509-c9ac-4f71-9b99-b5fe45aceec6)

**Comment by w-okada** [comment]
no update close
