### ISSUE TITLE
Huge delay and lags on good GPU

### ISSUE THREAD

**Issue by pasta-pasta** [w-okada/voice-changer#686]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11

### OS

Windows 10

### GPU

RTX 3060 12gb

### Clear setting

no

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

Im trying to use voicechanger on my pc. The configuration is a bit lame, i have i5-4460 with 32gb of ddr3 RAM and RTX 3060 with 12 gb of VRAM. 

After launching the voicechanger, the delay between my words and converted ones are 10-20 seconds, and they are extremely laggy. On any chunk size. 

I'm guessing that there is a problem in my internet connection, bc my router died and i'm using my phone usb modem to share internet, but im not sure.

### application window capture

![image](https://github.com/w-okada/voice-changer/assets/122100177/f9cf2e48-a81b-42b0-a65a-1d3e1d6bbef2)

### logs on terminal

Preparing your application. Please wait...
(node:14896) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] model slot is changed -1 -> 3
................RVC
-102 ERR_CONNECTION_REFUSED http://localhost:18888/

**Comment by w-okada** [comment]
Is there anything running in the background?

Please check the Windows Performance Monitor to see how the load is being managed.

**Comment by pasta-pasta** [comment]
nothing serious. And on the first tests there were only two browsers present without all the other programs.
![image](https://github.com/w-okada/voice-changer/assets/122100177/e6c052cf-f7da-422a-bc1d-9f645474d6c3)

**Comment by w-okada** [comment]
try

https://github.com/w-okada/voice-changer/blob/master/tutorials/trouble_shoot_communication_ja.md

with audio file

**Comment by pasta-pasta** [comment]
somehow using models that are not preset fixes the problem. i will check default models later when i'll upgrade to new CPU. thx for help!
