### ISSUE TITLE
GUI only shows white screen

### ISSUE THREAD

**Issue by kunoichi-sorter** [w-okada/voice-changer#687]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.12a.zip

### OS

Windows 10

### GPU

AMD Radeon RX 6950 XT

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

None, I cannot see GUI

### Model type

None, I cannot see GUI

### Situation

When I run start_http.bat, client windows opens, but it's just white screen. Only the top dropdown menus are visible. They can be opened, but some buttons don't seem to do anything (Display->Reload, Force Reload, Show dev-tool, Reset zoom, Zoom in and Zoom out do nothing. Display->Full screen and Minimize, File->Quit and Window->Close work normally).

As I side note, two weeks ago I had Nvidia RTX 2060 and it all worked fine (slow and unusable, but it "worked"). The version back then was MMVCServerSIO_win_onnxgpu-cuda-v.1.5.3.10a. I deleted that directory (was there some sort of uninstall I should've done?)

Today I removed RTX 2060 and installed AMD Radeon RX 6950 XT into my PC and started getting white screens (as described above).

I have so far tried:
- Restarting computer many times (would usually restart between trying out different things).
- Using versions direct ML 12a, 12, 11 as well as Nvidia versions 12a and 11 - all of them show white screen. The only differences are that versions 11 have dropdown menus in japanese and console output keeps repeating "(node:6348) failed connection refused" errors (new versions DO NOT show any errors though, so I'm not sure how important is it to try and resolve errors from the old client versions).
- Using various monitor resolutions.
- Using two different monitors (used them as extended displays but also tried unplugging them and then use them alone).
- Using both the newest and one older version of AMD drivers (version from July).
- Adding exception to antivirus (Avira) as well as turning it off completely.
- Running command prompt as Administrator and starting start_http.bat from there.
- Letting it just run for 45 minutes

All of these attempts resulted in the same white screen behavior as described above.

### application window capture

![capture-okada](https://github.com/w-okada/voice-changer/assets/106999793/5e476066-17f3-490a-848b-61774a86c9af)

### logs on terminal

C:\Users\*******\Downloads\VOICE AI\MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.12a\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[VCClient] wait web server...10 http://127.0.0.1:18888/
[VCClient] wait web server...20 http://127.0.0.1:18888/

**Comment by kunoichi-sorter** [comment]
I also tried opening http://127.0.0.1:18888/ directly in Firefox but I get "Unable to connect - Firefox can’t establish a connection to the server at 127.0.0.1:18888." error. I also get similar error in Chrome.

**Comment by Esingar98** [comment]
A friend of mine is experiencing the same. Not sure what is causing it.

**Comment by smastars1014** [comment]
How did you fix it? Do you have a solution now

**Comment by kunoichi-sorter** [comment]
> How did you fix it? Do you have a solution now

I never fixed it and I still have the same problem. I just accidentally closed the issue for a second when  I was posting additional information.

**Comment by w-okada** [comment]
try to delete model_dir and stored_setting.json

**Comment by lolaluwu** [comment]
i am having the same issue. i've deleted both of those files, but there's only a white screen upon bootup regardless

**Comment by lolaluwu** [comment]
i just unplugged my microphone and and bluetooth headset adapter and it suddenly worked again.

**Comment by FixStars1014** [comment]
I deleted model_dir to no avail This file stored_setting.json is not found
[vvclient.log](https://github.com/w-okada/voice-changer/files/12329895/vvclient.log)
![图片](https://github.com/w-okada/voice-changer/assets/76475910/9a13eb0e-6b19-44d8-8ea4-5e53aba067d8)

**Comment by w-okada** [comment]
I have no idea

**Comment by FixStars1014** [comment]
All I can say is it doesn't work after trying too many times And I'd like to ask how the hell is this white screen when the model_dir file is there, but that's the problem

**Comment by FixStars1014** [comment]
So how does this display actually work in the way that you build a website or something

**Comment by w-okada** [comment]
no res close

**Comment by lolololdude** [comment]
still not working

**Comment by Kuuko-fokkusugaru** [comment]
> I had this problem on windows 11 24h2, downgrading to 23h2 fixed it.

The software works on 24H2 perfectly fine.
