### ISSUE TITLE
option to disable pass through confirmation dialogue

### ISSUE THREAD

**Issue by exciar** [w-okada/voice-changer#688]
### Issue Type

Feature Request

### vc client version number

v.1.5.3.12a

### OS

Windows 11

### GPU

NVIDIA GTX 1660 Super

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

having an option to disable pass through confirmation makes it a convenient feature since what if I want to quickly use the pass through feature without having to press confirmation

### logs on terminal

[Voice Changer] update configuration: passThrough true
[Voice Changer] update configuration: passThrough false
[Voice Changer] update configuration: passThrough true
[Voice Changer] update configuration: passThrough false

**Comment by w-okada** [comment]
Done.
Try the latest version v.1.5.3.13. And read tutorial.

**Comment by exciar** [comment]
thank you!

**Comment by w-okada** [comment]
ok close
