### ISSUE TITLE
can not find start_http.bat

### ISSUE THREAD

**Issue by Sparkythecat4u** [w-okada/voice-changer#689]
### Issue Type

Bug Report, Question

### vc client version number

MMVC v.1.5.x, MMVC v.1.3.x, so-vits-svc 4.0,

### OS

windows 11

### GPU

nividia 3060 laptop

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

rvc

### Model type

pytorch

### Situation

unable to find the main startup for the VC, start.http.bat i download from hugging face (https://huggingface.co/wok000/vcclient000/blob/main/MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.12a.zip) i have searched around for it still inable to find it.

### logs on terminal

N/A

**Comment by Rafacasari** [comment]
If you didn't find the file, open your notepad, paste this whole code and save as "start_http**.bat**"

```bat
MMVCServerSIO.exe ^
    -p 18888 ^
    --https false ^
    --content_vec_500 pretrain/checkpoint_best_legacy_500.pt ^
    --content_vec_500_onnx pretrain/content_vec_500.onnx ^
    --content_vec_500_onnx_on true ^
    --hubert_base pretrain/hubert_base.pt ^
    --hubert_base_jp pretrain/rinna_hubert_base_jp.pt ^
    --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt ^
    --nsf_hifigan pretrain/nsf_hifigan/model ^
    --crepe_onnx_full pretrain/crepe_onnx_full.onnx ^
    --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx ^
    --rmvpe pretrain/rmvpe.pt ^
    --model_dir model_dir ^
    --samples samples.json   
```

**Comment by Sparkythecat4u** [comment]
I shall try this as I get home thank you.

**Comment by Sparkythecat4u** [comment]
> start_http **.bat**

hey that does not seem to be working, i put in notepad++ and tried to run it. it just popped up white and closed.

**Comment by Sparkythecat4u** [comment]
fixed it, due to me not putting together a bat file is a batch file xD.
