### ISSUE TITLE
High memory usage after first launch

### ISSUE THREAD

**Issue by BalintXHD** [w-okada/voice-changer#693]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12a

### OS

Windows 10

### GPU

nVIDIA GTX 1660 SUPER

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

RMPVE

### Situation

When I downloaded this version and first launched it, it used 700mb of ram and the quality was really good. However, after every other launch it uses 2600mb of ram and quality is bad.

Second issue: I can't get any audio using GPU, i had to use CPU and start it. After that GPU worked perfectly. 

### logs on terminal

...

**Comment by w-okada** [comment]
In my environment, when application is closed, memory is released.

**Comment by BalintXHD** [comment]
Yes, memory is released after I close the application.

But my problem is not with that. My problem is when I use Voice Changer, memory usage is high. But that wasn't always the case. Previously, memory usage was low. How could I get that back?

**Comment by w-okada** [comment]
which version did you use?

**Comment by BalintXHD** [comment]
> which version did you use?

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12a

**Comment by w-okada** [comment]
no, previosus version, you watch the low memory usage.

**Comment by BalintXHD** [comment]
Every time there is a new update, I extract to a new folder and start it. That's the only time that memory usage is low. After that it's high all the time. Hope that helps.

**Comment by w-okada** [comment]
I'm sorry, but I don't quite understand the problem. After booting, memory consumption is low because the model has not been loaded. However, once the model is loaded, memory usage increases. I believe that is to be expected, but...

**Comment by w-okada** [comment]
no res close
