### ISSUE TITLE
Intel arc is currently unuseable on all versions past 1.5.3.11

### ISSUE THREAD

**Issue by dan9070** [w-okada/voice-changer#695]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.12a

### OS

Windows 11

### GPU

Intel Arc A770 Limited Edition

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

Intel arc, when attempting to use a converted ONNX model for DirectML, outputs an incredibly loud tube-like sound when attempting to do any form of voice input. This was not the case in previous DML versions (1.5.3.10a) and I'm genuinely unsure as to why this is occuring. 

### application window capture

![image](https://github.com/w-okada/voice-changer/assets/110506846/d4b4a544-4bdc-4026-b389-2a8ad8a97a14)

### logs on terminal

C:\Users\dbs_5\Downloads\Voice Cloner Models\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
Try loading... model_dir\1\added_IVF851_Flat_nprobe_1_VinnyV2_v2.index
[VCClient] wait web server... done 200
[2023-08-11 20:23:15] connet sid : vKB38TI0yJAP_Tk_AAAB
[2023-08-11 20:23:15] connet sid : kYOEIVdpbz7P3rTcAAAD
[Voice Changer] update configuration: gpu 0
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\1\added_IVF851_Flat_nprobe_1_VinnyV2_v2.index
[Voice Changer] update configuration: gpu 0
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\1\added_IVF851_Flat_nprobe_1_VinnyV2_v2.index
Pipeline has been deleted
Pipeline has been deleted
[Voice Changer] update configuration: gpu -1
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\1\added_IVF851_Flat_nprobe_1_VinnyV2_v2.index
Pipeline has been deleted
[Voice Changer] update configuration: gpu 0
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\1\added_IVF851_Flat_nprobe_1_VinnyV2_v2.index
Pipeline has been deleted
[Voice Changer] update configuration: gpu -1
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\1\added_IVF851_Flat_nprobe_1_VinnyV2_v2.index
Pipeline has been deleted
[Voice Changer] update configuration: f0Detector crepe_full
[Voice Changer] update configuration: gpu 0
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\1\added_IVF851_Flat_nprobe_1_VinnyV2_v2.index
Pipeline has been deleted

**Comment by w-okada** [comment]
how about samle model?

**Comment by dan9070** [comment]
I'm very certain that none of the model types converted over to ONNX work. Just .pth seems to operate when having GPU selected for DML.

**Comment by w-okada** [comment]
AMD is availabe only fir onnx. read readme, and tutorial

**Comment by dan9070** [comment]
Reopening this post.

"If you are using Windows and AMD/Intel GPU, please download ONNX(cpu,DirectML), PyTorch(cpu,cuda). AMD/Intel GPUs are enabled only when using onnx models."

**Comment by w-okada** [comment]
? 
I have not tested for Directml vesrion. only for experimental.
I look forward to your contributions.
