### ISSUE TITLE
Wait Web Server Loop

### ISSUE THREAD

**Issue by Djoeliejoes** [w-okada/voice-changer#696]
### Issue Type

Bug Report, Question

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.12.zip

### OS

Windows 10

### GPU

MSI RADEON RX 580 ARMOR 8G OC

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

-

### Situation

While trying to open the client the terminal gets stuck on wait web server...

### application window capture

![image](https://github.com/w-okada/voice-changer/assets/81112723/85d42252-9f68-4b73-a635-88a6237305e9)

### logs on terminal

![image](https://github.com/w-okada/voice-changer/assets/81112723/63ec1110-da3e-4cb8-a0ca-88d260d3376b)

**Comment by w-okada** [comment]
same
https://github.com/w-okada/voice-changer/issues/700

**Comment by echilk** [comment]
So no one found a solution? sucks.
