### ISSUE TITLE
[VCClient] wait web user...

### ISSUE THREAD

**Issue by Draifu** [w-okada/voice-changer#700]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.12a

### OS

Windows 10

### GPU

AMD RX580 205

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

So my GPU is an AMD, meaning I had to download the directML version. I've done the steps correctly but the problem is after the installation, it just does nothing. I check the cmd and all it says is "[VCClient] wait web user...10 http://127.0.0.1:18888/" while the 10 changes from 20-30-40 and so on. After that, nothing happens. It's just the same message over and over again. I don't know what to do, can anyone help pls?

### logs on terminal

C:\Program Files (x86)\AI Voice Changer\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[VCClient] wait web server...10 http://127.0.0.1:18888/
[VCClient] wait web server...20 http://127.0.0.1:18888/
[VCClient] wait web server...30 http://127.0.0.1:18888/
[VCClient] wait web server...40 http://127.0.0.1:18888/
[VCClient] wait web server...50 http://127.0.0.1:18888/
[VCClient] wait web server...60 http://127.0.0.1:18888/
[VCClient] wait web server...70 http://127.0.0.1:18888/
[VCClient] wait web server...80 http://127.0.0.1:18888/
[VCClient] wait web server...90 http://127.0.0.1:18888/
[VCClient] wait web server...100 http://127.0.0.1:18888/
[VCClient] wait web server...110 http://127.0.0.1:18888/
[VCClient] wait web server...120 http://127.0.0.1:18888/
[VCClient] wait web server...130 http://127.0.0.1:18888/
[VCClient] wait web server...140 http://127.0.0.1:18888/
[VCClient] wait web server...150 http://127.0.0.1:18888/
[VCClient] wait web server...160 http://127.0.0.1:18888/
[VCClient] wait web server...170 http://127.0.0.1:18888/
[VCClient] wait web server...180 http://127.0.0.1:18888/
[VCClient] wait web server...190 http://127.0.0.1:18888/
[VCClient] wait web server...200 http://127.0.0.1:18888/
[VCClient] wait web server...210 http://127.0.0.1:18888/
[VCClient] wait web server...220 http://127.0.0.1:18888/
[VCClient] wait web server...230 http://127.0.0.1:18888/
[VCClient] wait web server...240 http://127.0.0.1:18888/
[VCClient] wait web server...250 http://127.0.0.1:18888/
[VCClient] wait web server...260 http://127.0.0.1:18888/
[VCClient] wait web server...270 http://127.0.0.1:18888/
[VCClient] wait web server...280 http://127.0.0.1:18888/
[VCClient] wait web server...290 http://127.0.0.1:18888/
[VCClient] wait web server...300 http://127.0.0.1:18888/
[VCClient] wait web server...310 http://127.0.0.1:18888/
[VCClient] wait web server...320 http://127.0.0.1:18888/
[VCClient] wait web server...330 http://127.0.0.1:18888/
[VCClient] wait web server...340 http://127.0.0.1:18888/
[VCClient] wait web server...350 http://127.0.0.1:18888/
[VCClient] wait web server...360 http://127.0.0.1:18888/
[VCClient] wait web server...370 http://127.0.0.1:18888/
[VCClient] wait web server...380 http://127.0.0.1:18888/
[VCClient] wait web server...390 http://127.0.0.1:18888/
[VCClient] wait web server...400 http://127.0.0.1:18888/
[VCClient] wait web server...410 http://127.0.0.1:18888/
[VCClient] wait web server...420 http://127.0.0.1:18888/
[VCClient] wait web server...430 http://127.0.0.1:18888/
[VCClient] wait web server...440 http://127.0.0.1:18888/
[VCClient] wait web server...450 http://127.0.0.1:18888/
[VCClient] wait web server...460 http://127.0.0.1:18888/
[VCClient] wait web server...470 http://127.0.0.1:18888/
[VCClient] wait web server...480 http://127.0.0.1:18888/
[VCClient] wait web server...490 http://127.0.0.1:18888/
[VCClient] wait web server...500 http://127.0.0.1:18888/
[VCClient] wait web server...510 http://127.0.0.1:18888/
[VCClient] wait web server...520 http://127.0.0.1:18888/
[VCClient] wait web server...530 http://127.0.0.1:18888/
[VCClient] wait web server...540 http://127.0.0.1:18888/
[VCClient] wait web server...550 http://127.0.0.1:18888/
[VCClient] wait web server...560 http://127.0.0.1:18888/
[VCClient] wait web server...570 http://127.0.0.1:18888/
[VCClient] wait web server...580 http://127.0.0.1:18888/
[VCClient] wait web server...590 http://127.0.0.1:18888/
[VCClient] wait web server...600 http://127.0.0.1:18888/
[VCClient] wait web server...610 http://127.0.0.1:18888/
[VCClient] wait web server...620 http://127.0.0.1:18888/
[VCClient] wait web server...630 http://127.0.0.1:18888/
[VCClient] wait web server...640 http://127.0.0.1:18888/
[VCClient] wait web server...650 http://127.0.0.1:18888/
[VCClient] wait web server...660 http://127.0.0.1:18888/
[VCClient] wait web server...670 http://127.0.0.1:18888/
[VCClient] wait web server...680 http://127.0.0.1:18888/
[VCClient] wait web server...690 http://127.0.0.1:18888/
[VCClient] wait web server...700 http://127.0.0.1:18888/
[VCClient] wait web server...710 http://127.0.0.1:18888/
[VCClient] wait web server...720 http://127.0.0.1:18888/
[VCClient] wait web server...730 http://127.0.0.1:18888/
[VCClient] wait web server...740 http://127.0.0.1:18888/
[VCClient] wait web server...750 http://127.0.0.1:18888/
[VCClient] wait web server...760 http://127.0.0.1:18888/
[VCClient] wait web server...770 http://127.0.0.1:18888/
[VCClient] wait web server...780 http://127.0.0.1:18888/
[VCClient] wait web server...790 http://127.0.0.1:18888/
[VCClient] wait web server...800 http://127.0.0.1:18888/
[VCClient] wait web server...810 http://127.0.0.1:18888/
[VCClient] wait web server...820 http://127.0.0.1:18888/
[VCClient] wait web server...830 http://127.0.0.1:18888/
[VCClient] wait web server...840 http://127.0.0.1:18888/
[VCClient] wait web server...850 http://127.0.0.1:18888/
[VCClient] wait web server...860 http://127.0.0.1:18888/
[VCClient] wait web server...870 http://127.0.0.1:18888/
[VCClient] wait web server...880 http://127.0.0.1:18888/
[VCClient] wait web server...890 http://127.0.0.1:18888/
[VCClient] wait web server...900 http://127.0.0.1:18888/
[VCClient] wait web server...910 http://127.0.0.1:18888/
[VCClient] wait web server...920 http://127.0.0.1:18888/
[VCClient] wait web server...930 http://127.0.0.1:18888/
[VCClient] wait web server...940 http://127.0.0.1:18888/
[VCClient] wait web server...950 http://127.0.0.1:18888/
[VCClient] wait web server...960 http://127.0.0.1:18888/

**Comment by w-okada** [comment]
I said in readme, directml version is not tested, only experimental because I have no amd gpu.
I have no idea. However, chatgpt says
```
ONNX Runtime is a machine learning model inference engine developed by Microsoft and supports models in the Open Neural Network Exchange (ONNX) format.

ONNX execution on AMD GPUs uses HIP/ROCm technology. ROCm stands for Radeon Open Compute and is an open-source GPU computing framework that's developed by AMD.

Currently, ONNX Runtime supports ROCm 3.3 or higher and the following GPUs are supported by ROCm:

- AMD Radeon Instinct MI25
- AMD Radeon Instinct MI50
- AMD Radeon Instinct MI60
- AMD Radeon Instinct MI100
- AMD Radeon RX Vega Series
- AMD Radeon VII Series

Please note that the GPUs supported by ROCm and ONNX Runtime may change depending on the version. For more details, please refer to the official ROCm and ONNX Runtime documentation or their GitHub repositories.
```

Could you check this?

**Comment by Djoeliejoes** [comment]
I see you closed my issue and merged it in here, the vc worked for me before yesterday so I don’t see why now my graphics card wouldn’t be supported?

**Comment by w-okada** [comment]
@Djoeliejoes 
Is that so? I didn't know that. What version was it running on?

**Comment by Djoeliejoes** [comment]
> @Djoeliejoes
> Is that so? I didn't know that. What version was it running on?

v.1.5.3.12

**Comment by wokadasolver** [comment]
try delete stored_settings.json and run it

**Comment by AkiroDK** [comment]
im having the same issue and i just tried the delete stored_settings.json thing, did not work, still did the loop

**Comment by AkiroDK** [comment]
im having the same issue, did the delete stored_settings.json, even removed it from my paperbin but still does the loop

**Comment by Draifu** [comment]
where is that file located?

**Comment by w-okada** [comment]
the same folder as .bat

**Comment by vigreux8** [comment]
dell setting.json it is work thanks !

**Comment by Djoeliejoes** [comment]
> try delete stored_settings.json and run it

Worked for me, thanks.

**Comment by Draifu** [comment]
i don't see any file called stored_settings.json

**Comment by wokadasolver** [comment]
should be on the same directory as start_http.bat

**Comment by Kisamij** [comment]
hello I have the same problem, I tried to install different versions but it didn't work, and in all versions I can't find this json file

**Comment by KitsuneShan** [comment]
Me and my friend found this issue exactly today. It was working fine all this time then suddenly this happened to both of us, on the same day, at the exact time. I haven't updated windows or drivers. It's there are specific reason for this to happen exactly today?? We are using MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.18a

**Comment by YukiYuki123** [comment]
> Me and my friend found this issue exactly today. It was working fine all this time then suddenly this happened to both of us, on the same day, at the exact time. I haven't updated windows or drivers. It's there are specific reason for this to happen exactly today?? We are using MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.18a

we ran into this problem at the same second.
