### ISSUE TITLE
Old model and index files not removed after uploading or downloading new ones

### ISSUE THREAD

**Issue by TheTrustedComputer** [w-okada/voice-changer#701]
Somewhat related to #440.

I noticed when uploading or downloading new models over an existing one, the model and index files are copied to the slot number in the model_dir folder. The old files sit there unused, potentially wasting disk space if a user uploads many different models to the same slot; I have to delete them manually. It would be great to implement an automated one.

**Comment by w-okada** [comment]
use issue template
