### ISSUE TITLE
Old model and index files not removed after uploading or downloading new ones 

### ISSUE THREAD

**Issue by TheTrustedComputer** [w-okada/voice-changer#702]
### Issue Type

Feature Request

### vc client version number

Cloned via git using Anaconda environment (closest is 1.5.3.12a)

### OS

Arch Linux

### GPU

AMD Radeon RX 5500 XT

### Clear setting

no

### Sample model

yes

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

PyTorch, ONNX, RMVPE

### Situation

Somewhat related to #440.

I noticed when uploading or downloading new models over an existing one, the model and index files are copied to the slot number in the model_dir folder. The old files sit there unused, potentially wasting disk space if a user uploads many different models to the same slot; I have to delete them manually. It would be great to implement an automated one.

### logs on terminal

Not applicable.

**Comment by TheTrustedComputer** [comment]
Issue reopened to use template. As for the version, the closest match is 1.5.3.12a.

**Comment by w-okada** [comment]
OKay, thanks.

**Comment by w-okada** [comment]
Done.
Try the latest version v.1.5.3.13. And read tutorial.
