### ISSUE TITLE
Make editable the textboxes number of the sliders

### ISSUE THREAD

**Issue by Tefery** [w-okada/voice-changer#703]
### Issue Type

Feature Request

### Situation

When attempting to edit any of these parameters precisely, it becomes an almost impossible task to move forward or backward by a single number.

I suggest that the text box be changed to editable text.

### application window capture

![Screenshot_2](https://github.com/w-okada/voice-changer/assets/25052654/cb83970d-dca2-436f-9556-6ceb86ebbe45)

**Comment by w-okada** [comment]
use arrow button on your keyboard
