### ISSUE TITLE
Unable to use Voice Changer

### ISSUE THREAD

**Issue by kahtcw** [w-okada/voice-changer#705]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12a.zip

### OS

Windows 10 Pro

### GPU

none

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX(cpu,DirectML), PyTorch(cpu,cuda)

### Situation

This is the message that I receive:

C:\Users\Admin\Desktop\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https true     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
                                                                                                                       [Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='つくよみちゃん(onnx)', description='', credit='つくよみちゃん', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tsukuyomi-chan/terms_of_use.txt', iconFile='tsukuyomi-chan.png', speakers={0: 'target'}, modelFile='tsukuyomi_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='Tsukuyomi-chan_o')
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='あみたろ(onnx)', description='', credit='あみたろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/amitaro/terms_of_use.txt', iconFile='amitaro.png', speakers={0: 'target'}, modelFile='amitaro_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='Amitaro_o')
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='黄琴まひろ(onnx)', description='', credit='黄琴まひろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/kikoto_mahiro/terms_of_use.txt', iconFile='kikoto_mahiro.png', speakers={0: 'target'}, modelFile='kikoto_mahiro_v2_40k_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='KikotoMahiro_o')
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='刻鳴時雨(onnx)', description='', credit='刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tokina_shigure/terms_of_use.txt', iconFile='tokina_shigure.png', speakers={0: 'target'}, modelFile='tokina_shigure_v2_40k_e100_simple.onnx', indexFile='added_IVF2736_Flat_nprobe_1_v2.index.bin', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='TokinaShigure_o')
SlotInfo::: DiffusionSVCModelSlot(slotIndex=-1, voiceChangerType='Diffusion-SVC', name='初期メン(3,20)', description='', credit='あみたろ,つくよみちゃん,黄琴海月,黄琴まひろ,刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/diffusion-svc/term_of_use.txt', iconFile='diffusion-svc.png', speakers={1: 'user'}, modelFile='combo_spk5_nl3_dl20_k50_500ep.ptc.bin', isONNX=False, modelType='combo', dstId=1, sampleId='diffusion_combo_spk5_nl3_dl20_k50_500ep', defaultTune=0, defaultKstep=0, defaultSpeedup=0, kStepMax=0, nLayers=20, nnLayers=20, embedder='hubert_base', samplingRate=44100, embChannels=768)
SlotInfo::: DiffusionSVCModelSlot(slotIndex=-1, voiceChangerType='Diffusion-SVC', name='初期メン(3,1)', description='',                                                                                                                        [Voice Changer] Generating metadata....txt', iconFile='diffusion-svc.png', speakers={1: 'user'}, modelFile='combo_spk5_nl
[Voice Changer] ONNX Model: Official v2 like                                                                           d
SlotInfo::: RVCModelSlot(slotIndex=0, voiceChangerType='RVC', name='つくよみちゃん(onnx)', description='', credit='つくtよみちゃん', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tsukuyomi-chan/terms_of_use.txt', iconFile='tsukuyomi-chan.png', speakers={'0': 'target'}, modelFile='tsukuyomi_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='Tsukuyomi-chan_o')                                                                       | 3.00M/52.8M [00:03<01:05, 803kB/s]
[Voice Changer] ONNX Model: Official v2 like
SlotInfo::: RVCModelSlot(slotIndex=1, voiceChangerType='RVC', name='あみたろ(onnx)', description='', credit='あみたろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/amitaro/terms_of_use.txt', iconFile='amitaro.png', speakers={'0': 'target'}, modelFile='amitaro_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='Amitaro_o') [00:00<00:00, 405kB/s]
[Voice Changer] ONNX Model: Official v2 like                                        | 389k/34.4M [00:01<01:46, 337kB/s]
SlotInfo::: RVCModelSlot(slotIndex=2, voiceChangerType='RVC', name='黄琴まひろ(onnx)', description='', credit='黄琴まひ ろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/kikoto_mahiro/terms_of_use.txt', iconFile='kikoto_mahiro.png', speakers={'0': 'target'}, modelFile='kikoto_mahiro_v2_40k_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='KikotoMahiro_o')
[Voice Changer] ONNX Model: Official v2 like
SlotInfo::: RVCModelSlot(slotIndex=3, voiceChangerType='RVC', name='刻鳴時雨(onnx)', description='', credit='刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tokina_shigure/terms_of_use.txt', iconFile='tokina_shigure.png', speakers={'0': 'target'}, modelFile='tokina_shigure_v2_40k_e100_simple.onnx', indexFile='added_IVF2736_Flat_nprobe_1_v2.index.bin', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='TokinaShigure_o')
[Voice Changer] custom matplotlib loaded successfully
 [Loading] model_dir\4\combo_spk5_nl3_dl20_k50_500ep.ptc.bin
SlotInfo::: DiffusionSVCModelSlot(slotIndex=4, voiceChangerType='Diffusion-SVC', name='初期メン(3,20)', description='', credit='あみたろ,つくよみちゃん,黄琴海月,黄琴まひろ,刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/diffusion-svc/term_of_use.txt', iconFile='diffusion-svc.png', speakers={1: 'user1', 2: 'user2', 3: 'user3', 4: 'user4', 5: 'user5'}, modelFile='combo_spk5_nl3_dl20_k50_500ep.ptc.bin', isONNX=False, modelType='combo', dstId=1, sampleId='diffusion_combo_spk5_nl3_dl20_k50_500ep', defaultTune=0, defaultKstep=50, defaultSpeedup=25, kStepMax=50, nLayers=20, nnLayers=3, embedder='hubert_base', samplingRate=44100, embChannels=768)
 [Loading] model_dir\5\combo_spk5_nl3_dl1_k50_500ep.ptc.bin
SlotInfo::: DiffusionSVCModelSlot(slotIndex=5, voiceChangerType='Diffusion-SVC', name='初期メン(3,1)', description='', credit='あみたろ,つくよみちゃん,黄琴海月,黄琴まひろ,刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/diffusion-svc/term_of_use.txt', iconFile='diffusion-svc.png', speakers={1: 'user1', 2: 'user2', 3: 'user3', 4: 'user4', 5: 'user5'}, modelFile='combo_spk5_nl3_dl1_k50_500ep.ptc.bin', isONNX=False, modelType='combo', dstId=1, sampleId='diffusion_combo_spk5_nl3_dl1_k50_500ep', defaultTune=0, defaultKstep=50, defaultSpeedup=25, kStepMax=50, nLayers=1, nnLayers=3, embedder='hubert_base', samplingRate=44100, embChannels=768)
    Internal_Port:18888
    protocol: HTTPS(self-signed), key:C:\Users\Admin\AppData\Local\Temp\tmprg58ac80\keys\20230813_215021.key, cert:C:\Users\Admin\AppData\Local\Temp\tmprg58ac80\keys\20230813_215021.cert
    -- ---- --
    Please open the following URL in your browser.
    https://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    https://127.0.0.1:18888/
    https://192.168.50.139:18888/
    Booting PHASE :MMVCServerSIO
torch\cuda\__init__.py:152: UserWarning:
    Found GPU0 NVIDIA GeForce GTX 680 which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability supported by this library is 3.7.

  warnings.warn(old_gpu_warn % (d, name, major, minor, min_arch // 10, min_arch % 10))

### logs on terminal

logged on windows 10 pro

**Comment by w-okada** [comment]
> Found GPU0 NVIDIA GeForce GTX 680 which is of cuda capability 3.0.
PyTorch no longer supports this GPU because it is too old.
The minimum cuda capability supported by this library is 3.7.

check your gpu.

**Comment by w-okada** [comment]
no res close
