### ISSUE TITLE
Wont register my AMD GPU

### ISSUE THREAD

**Issue by juixioi** [w-okada/voice-changer#707]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12a.zip

### OS

W10

### GPU

RX 5700XT

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

rvc

### Model type

pyt

### Situation

won't register my gpu

### logs on terminal

[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)

**Comment by juixioi** [comment]
nvm figured out

**Comment by juixioi** [comment]
My friend also has this issue he is on a RX 6600XT

**Comment by w-okada** [comment]
use directml version
