### ISSUE TITLE
'MMVCServerSIO.exe' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Complex136** [w-okada/voice-changer#709]
### Issue Type

Others

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12.zip

### OS

Windows 11

### GPU

NVIDIA GeForce RTX 2060

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

I downloaded the above zip file using hugging face on Opera Gx browser, unzipped the folder into a different folder and tried to run start_http.bat. The file window reacted but nothing happened. I then attempted to run the path in cmd and had a similar output to the examples i've seen. However it gave me an error instead of starting downloads.
![image_2023-08-13_224157192](https://github.com/w-okada/voice-changer/assets/142151380/70de722f-92e3-4ade-82c2-926b9ee75ba6)

### logs on terminal

![image](https://github.com/w-okada/voice-changer/assets/142151380/7f2184da-e9dc-4ffb-a741-e013458d5fc5)

**Comment by Monmcgt** [comment]
Run the command in `C:\Users\pyth0\AI_voice_changer\MMVCServerSIO` directory.

**Comment by Rafacasari** [comment]
That's weird, you should be able to double click the batch file and run it automatically.
But you can try to use this command on cmd
```
cd C:\Users\pyth0\AI_voice_changer\MMVCServerSIO
start_http.bat
```

**Comment by Complex136** [comment]
> Run the command in `C:\Users\pyth0\AI_voice_changer\MMVCServerSIO` directory.

This seems to have worked, thank you.
