### ISSUE TITLE
Option to delete unused models

### ISSUE THREAD

**Issue by Rafacasari** [w-okada/voice-changer#710]
### Issue Type

Feature Request

### vc client version number

v1.5.3.11

### Voice Changer type

RVC

### Situation

Would be awesome to have a button to fully delete a model from the server, the way I'm doing right now is uploading a new model and overwriting the existing ones. But would be awesome to delete old models that we don't want to have.

Some button right here or idk
![image](https://github.com/w-okada/voice-changer/assets/32463720/83b872af-86ac-4fd6-a97b-fe7db28d6a23)

**Comment by Rafacasari** [comment]
I would like to reccommend adding a separeted **Feature Request** template on GitHub aswell, since most part of the fields of bug report template is useless for a Feature Request ^^

**Comment by TheTrustedComputer** [comment]
Have #702 a read. I've submitted a similar issue, where files to old models don't get deleted after uploading or downloading new models.
