### ISSUE TITLE
no amd recognition

### ISSUE THREAD

**Issue by ignrpb** [w-okada/voice-changer#711]
Hello , i recently downloaded the voice changer but i can't choose my gpu (i can only choose cpu) (my gpu is amd rx 580) also i downloaded  v.1.5.3.12a version on DirectML but in corner it says cuda (idk if it's supposed to say it) ,also when im starting the app wallpaper engine music stops playing and i get notificatiojns from voicemod that it disonnected

**Comment by w-okada** [comment]
use issue template
