### ISSUE TITLE
Same problem as other people: frequent error occur please check if the model of the framework being targeted is loaded (And yes, I readed all other  issues and can't find any solution, sorry)

### ISSUE THREAD

**Issue by H1deMyFace** [w-okada/voice-changer#715]
### Issue Type

Others

### vc client version number

1.5.3.12a

### OS

Windows

### GPU

GTX 1050TI

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

PTH, Index, ONNXX

### Situation

Hi, my problem is a little weird, I have the default voices and my own voices. The problem is the voice stopped working for no reason. I have made a new extraction of the software in another folder and nothing seems to work. Sometimes when I change the extraction folder the voices back to work but after some time stop. I also tryied another models, sample models, models without index...
I also whitelisted app on Kaspersky and tried with them disabled.

### application window capture

![image](https://github.com/w-okada/voice-changer/assets/59140135/52567e90-c65d-4f62-86c2-b0045b27c5b3)

### logs on terminal

![image](https://github.com/w-okada/voice-changer/assets/59140135/73d41b95-593f-4cf4-a731-3beda43aee1f)

**Comment by w-okada** [comment]
use cpu

**Comment by H1deMyFace** [comment]
I use Cuda, when I try to use GPU nothing work, the vol still on 0 but the buf and res keep working. On CPU mode the same thing happens. My GPU use like 50% to work only.

**Comment by w-okada** [comment]
No issues were found in the log. It could be a phenomenon dependent on your operating environment.　What's the CPU usage like? If it's near 100%, that might be the bottleneck, meaning the GPU isn't being used.

**Comment by H1deMyFace** [comment]
No, when I use CUDA with GPU my CPU works great. When I use CPU only the use goes to 80%. I think the problem is some custom models are braking the entire software, that could be possible right?
