### ISSUE TITLE
Suspiciously high CPU usage jump on 32k and over extra compared to 16k and under

### ISSUE THREAD

**Issue by Smokyyy** [w-okada/voice-changer#716]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12a

### OS

Windows 10 pro, 22H2, 19045.3208

### GPU

GTX 1080

### Clear setting

no

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

pyTorchRVCv2, f0

### Situation

PC specs;
CPU: i5-6600k
GPU: GTX 1080

Suspiciously high CPU usage jump on 32k and over extra compared to 16k and under.

The next test was for every extra setting and done with 112 chunks. CPU and GPU usage at peaks were as such:
4096 extra: 15% cpu, gpu sub 1%
8192 extra: 15% cpu, gpu sub 1%
16384 extra: 14% cpu, gpu sub 1%
32768 extra: 74% cpu, gpu sub 1%
65536 extra: 74% cpu, gpu 2.2%
131072 extra: 85% cpu, gpu 4%

I want to know what might be causing this jump. Is it because of my older hardware, or is there something funky going on in the background?

### application window capture

![VoiceChanger_Settings](https://github.com/w-okada/voice-changer/assets/23454820/3886a853-2498-459d-a67d-0c2e4cabbaf5)
_My settings_

![4k_extra](https://github.com/w-okada/voice-changer/assets/23454820/c40a7cf7-21be-42a4-9df8-1244155d235c)
_4k extra_

![8k_extra](https://github.com/w-okada/voice-changer/assets/23454820/85edc6a4-270c-452d-8ceb-de5e5f5834d0)
_8k extra_

![16k_extra](https://github.com/w-okada/voice-changer/assets/23454820/41384869-cdbe-4ef5-8022-bcae41f40c8c)
_16k extra_

![32k_extra](https://github.com/w-okada/voice-changer/assets/23454820/de564644-ea95-4ac2-a856-747dbf4f6461)
_32k extra_

![65k_extra](https://github.com/w-okada/voice-changer/assets/23454820/e253fa9e-fd3b-49d2-a757-e61cf6dc7df2)
_65k extra_

![131k_extra](https://github.com/w-okada/voice-changer/assets/23454820/e7f22b53-e70a-4f62-937e-279c9359474e)
_131k extra_

### logs on terminal

D:\Program Files\Voice Changer\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] model slot is changed -1 -> 199
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
2023-08-15 06:04:26.7298629 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-08-15 06:04:26.7373115 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x000002627CCDFD00>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x000002627FC8FBB0>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x000002627FC8FBE0>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings serverReadChunkSize:112
[Voice Changer][RVC]: update_settings f0Detector:rmvpe
[VCClient] wait web server...10 http://127.0.0.1:18888/
[VCClient] wait web server...20 http://127.0.0.1:18888/
[Voice Changer][RVC]: update_settings silentThreshold:0.00001
[Voice Changer][RVC]: update_settings enableServerAudio:1
[Voice Changer][RVC]: update_settings serverAudioSampleRate:48000
[Voice Changer][RVC]: update_settings serverInputDeviceId:14
[Voice Changer][RVC]: update_settings serverOutputDeviceId:13
[Voice Changer][RVC]: update_settings extraConvertSize:32768
[Voice Changer][RVC]: update_settings serverOutputAudioGain:2.8
[Voice Changer][RVC]: update_settings serverInputAudioGain:2.8
[Voice Changer][RVC]: update_settings serverMonitorDeviceId:12
[Voice Changer][RVC]: update_settings modelSlotIndex:1692064991199
[VCClient] wait web server... done 200
[2023-08-15 06:07:40] connet sid : ui0bObYVTQroFOKcAAAC
[2023-08-15 06:07:40] connet sid : _AnyH-zg0FZepRAbAAAD
[Voice Changer] update configuration: serverAudioStated 1
[Voice Changer][RVC]: update_settings serverAudioStated:1
Devices:
  [Input]: ServerAudioDevice(kind='audioinput', index=14, name='Mikrofoni (Realtek High Definition Audio)', hostAPI='Windows WASAPI', maxInputChannels=2, maxOutputChannels=0, default_samplerate=48000.0, available_samplerates=[]) None
  [Output]: ServerAudioDevice(kind='audiooutput', index=13, name='Line 1 (Virtual Audio Cable)', hostAPI='Windows WASAPI', maxInputChannels=0, maxOutputChannels=2, default_samplerate=48000.0, available_samplerates=[]) None
  [Monitor]: ServerAudioDevice(kind='audiooutput', index=12, name='Speakers (iFi (by AMR) HD USB Audio)', hostAPI='Windows WASAPI', maxInputChannels=0, maxOutputChannels=2, default_samplerate=48000.0, available_samplerates=[]) None
Sample Rate:
  [Model]: 40000
  [Input]: 48000 -> True
  [Output]: 48000 -> True
  [Monitor]: 48000 -> True
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] server audio performance []
                status: started:1, model_sr:40000, chunk:112
                input  : id:14, sr:48000, ch:2
                output : id:13, sr:48000, ch:2
                monitor: id:12, sr:48000, ch:2
[Voice Changer] warming up... generating sola buffer.
[Voice Changer] server audio performance [118, 0, 116, 0]
                status: started:1, model_sr:40000, chunk:112
                input  : id:14, sr:48000, ch:2
                output : id:13, sr:48000, ch:2
                monitor: id:12, sr:48000, ch:2
[Voice Changer] server audio performance [95, 0, 93, 0]
                status: started:1, model_sr:40000, chunk:112
                input  : id:14, sr:48000, ch:2
                output : id:13, sr:48000, ch:2
                monitor: id:12, sr:48000, ch:2
[Voice Changer] server audio performance [10, 0, 8, 0]
                status: started:1, model_sr:40000, chunk:112
                input  : id:14, sr:48000, ch:2
                output : id:13, sr:48000, ch:2
                monitor: id:12, sr:48000, ch:2

**Comment by ScikuVRC** [comment]
Recently started doing the same for me, going to 80%+, feels like it's not using my GPU at all anymore.

**Comment by w-okada** [comment]
same

https://github.com/w-okada/voice-changer/issues/511
