### ISSUE TITLE
cannot start the gui

### ISSUE THREAD

**Issue by audioses** [w-okada/voice-changer#717]
### Issue Type

Bug Report

### vc client version number

2a version with cuta

### OS

win11

### GPU

gtx1650

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

rvc

### Model type

torch

### Situation

      Wen I click start.bat I get the following error:
      ModuleNotFoundError: No module named 'beatrice_internal_api'                                                            
      how would I fix this? I searched but couldnt find such module anywhere to install myself

### application window capture

none

### logs on terminal

      ModuleNotFoundError: No module named 'beatrice_internal_api'

**Comment by w-okada** [comment]
no res close

**Comment by ttakasawa** [comment]
Hi there. Im running into same issue... I just cloned the master, so should be the latest. 
Steps I took are:
1. clone repo 
2.  npm run build:docker:vcclient
3.  USE_GPU=off bash start_docker.sh
4. Click on image and created container. 

Then 
File "/voice-changer/server/voice_changer/Beatrice/Beatrice.py", line 10, in <module>
    from beatrice_internal_api import BeatriceInternalAPI
ModuleNotFoundError: No module named 'beatrice_internal_api'

Please help! Thank you!
