### ISSUE TITLE
LOUD STATIC

### ISSUE THREAD

**Issue by xxIfaIxx** [w-okada/voice-changer#722]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.12a

### OS

WINDOWS 10

### GPU

none

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

MMVC

### Model type

pyTorch

### Situation

Verry loud static noise instantly after opening the starthttp file. Watched a video and have done everything correctly (installed pyTorch etc.). The loud static applies to what ever output device i used when i opened and the problem doesnt go away unless I restart my laptop or change output device.

### logs on terminal

idk what this means

**Comment by w-okada** [comment]
use cuda version.

**Comment by w-okada** [comment]
no res close
