### ISSUE TITLE
RVC has resolved some bugs with the latest version（v8.13）. Can we synchronize updates?

### ISSUE THREAD

**Issue by xypiaofei** [w-okada/voice-changer#723]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12

### OS

WIN11

### GPU

GTX 4070

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

f0

### Situation

https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/docs/Changelog_EN.md
2023-08-13
Solve the CPU consumption problem caused by faiss searching during real-time voice changes

The latest version has solved the problem of  high CPU usage caused by index rate.

### logs on terminal

2023-08-13
Solve the CPU consumption problem caused by faiss searching during real-time voice changes

The latest version has solved the problem of  high CPU usage caused by index rate.

**Comment by Rafacasari** [comment]
> ？there is no code updated. Do you find the commit relateted that?

I've searched and I didn't found the specific commit. Maybe asking on their Discord server?

**Comment by w-okada** [comment]
@Rafacasari 
Me too. I couldn't find it.

@xypiaofei
If you need, please ask them.

**Comment by benc1221** [comment]
> @Rafacasari Me too. I couldn't find it.
> 
> @xypiaofei If you need, please ask them.

https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/gui_v1.py i think its in there

**Comment by benc1221** [comment]
cd1d76a you can take a look there

**Comment by benc1221** [comment]
maybe this one too 85d0d70

**Comment by w-okada** [comment]
85d0d70 is not for faiss.
I could not find in cd1d76a. please tell me which line?

**Comment by benc1221** [comment]
Lines 121-131 take a look there

**Comment by w-okada** [comment]
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/cd1d76aac291c9980cd629e52142e80fb0aa81da/rvc_for_realtime.py#L220

Here?  Thanks! but this is already supported in my app.


https://github.com/w-okada/voice-changer/blob/8312189942066c4ca7158c3def6723dd3c2b49ea/server/voice_changer/RVC/pipeline/Pipeline.py#L198

(not rate but silence_front in my app)

**Comment by w-okada** [comment]
no update close
