### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by Unanalyzed** [w-okada/voice-changer#724]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.12a

### OS

Windows 11

### GPU

none

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

ONNX

### Situation

How would I uninstall this program and start fresh?

### logs on terminal

N/A

**Comment by w-okada** [comment]
You should just delete the folder.

**Comment by w-okada** [comment]
no res close

**Comment by QuantumVertic** [comment]
How would i uninstall W okada to reinstall it? would i delete the MMVCServerSIO folder? if not please tell me
