### ISSUE TITLE
Error messages on load up (m1 Mac running macOS venture)

### ISSUE THREAD

**Issue by EnderThatCodes** [w-okada/voice-changer#732]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.12.zip

### OS

M1 venture

### GPU

none

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

PyTorch

### Situation

After running the startHttp.command file, the terminal keeps showing error messages.

### application window capture

<img width="872" alt="image" src="https://github.com/w-okada/voice-changer/assets/139295348/b4a8ef30-d29a-4961-b879-e0dc7fda59a5">

### logs on terminal

<img width="1473" alt="image" src="https://github.com/w-okada/voice-changer/assets/139295348/4897a688-c95d-415a-bd71-6aa80715f88b">

**Comment by w-okada** [comment]
review your network

**Comment by EnderThatCodes** [comment]
is it a network issue? I don't get it
