### ISSUE TITLE
wait web server...

### ISSUE THREAD

**Issue by Kisamij** [w-okada/voice-changer#734]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.12a.zip

### OS

windows 10

### GPU

rx 6650xt

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

no

### Situation

every time I open the .bat , it loads the gui but with a fixed white screen and the conse says "wait server broswer" endlessly, I've tried different versions, deactivated various pc settings with poor results

### logs on terminal

\Desktop\Ai Voice\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='つくよみちゃん(onnx)', description='', credit='つくよみちゃん', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tsukuyomi-chan/terms_of_use.txt', iconFile='tsukuyomi-chan.png', speakers={0: 'target'}, modelFile='tsukuyomi_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='Tsukuyomi-chan_o')
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='あみたろ(onnx)', description='', credit='あみたろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/amitaro/terms_of_use.txt', iconFile='amitaro.png', speakers={0: 'target'}, modelFile='amitaro_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='Amitaro_o')
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='黄琴まひろ(onnx)', description='', credit='黄琴まひろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/kikoto_mahiro/terms_of_use.txt', iconFile='kikoto_mahiro.png', speakers={0: 'target'}, modelFile='kikoto_mahiro_v2_40k_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='KikotoMahiro_o')
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='刻鳴時雨(onnx)', description='', credit='刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tokina_shigure/terms_of_use.txt', iconFile='tokina_shigure.png', speakers={0: 'target'}, modelFile='tokina_shigure_v2_40k_e100_simple.onnx', indexFile='added_IVF2736_Flat_nprobe_1_v2.index.bin', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='TokinaShigure_o')
SlotInfo::: DiffusionSVCModelSlot(slotIndex=-1, voiceChangerType='Diffusion-SVC', name='初期メン(3,20)', description='', credit='あみたろ,つくよみちゃん,黄琴海月,黄琴まひろ,刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/diffusion-svc/term_of_use.txt', iconFile='diffusion-svc.png', speakers={1: 'user'}, modelFile='combo_spk5_nl3_dl20_k50_500ep.ptc.bin', isONNX=False, modelType='combo', dstId=1, sampleId='diffusion_combo_spk5_nl3_dl20_k50_500ep', defaultTune=0, defaultKstep=0, defaultSpeedup=0, kStepMax=0, nLayers=20, nnLayers=20, embedder='hubert_base', samplingRate=44100, embChannels=768)
SlotInfo::: DiffusionSVCModelSlot(slotIndex=-1, voiceChangerType='Diffusion-SVC', name='初期メン(3,1)', description='', credit='あみたろ,つくよみちゃん,黄琴海月,黄琴まひろ,刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/diffusion-svc/term_of_use.txt', iconFile='diffusion-svc.png', speakers={1: 'user'}, modelFile='combo_spk5_nl3_dl1_k50_500ep.ptc.bin', isONNX=False, modelType='combo', dstId=1, sampleId='diffusion_combo_spk5_nl3_dl1_k50_500ep', defaultTune=0, defaultKstep=0, defaultSpeedup=0, kStepMax=0, nLayers=20, nnLayers=20, embedder='hubert_base', samplingRate=44100, embChannels=768)
[Voice Changer] Downloading model files...
                                                                                                                       [Voice Changer] Generating metadata...
[Voice Changer] ONNX Model: Official v2 like
SlotInfo::: RVCModelSlot(slotIndex=0, voiceChangerType='RVC', name='つくよみちゃん(onnx)', description='', credit='つく よみちゃん', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tsukuyomi-chan/terms_of_use.txt', iconFile='tsukuyomi-chan.png', speakers={'0': 'target'}, modelFile='tsukuyomi_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='Tsukuyomi-chan_o')
[Voice Changer] ONNX Model: Official v2 like
SlotInfo::: RVCModelSlot(slotIndex=1, voiceChangerType='RVC', name='あみたろ(onnx)', description='', credit='あみたろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/amitaro/terms_of_use.txt', iconFile='amitaro.png', speakers={'0': 'target'}, modelFile='amitaro_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='Amitaro_o')
[Voice Changer] ONNX Model: Official v2 like
SlotInfo::: RVCModelSlot(slotIndex=2, voiceChangerType='RVC', name='黄琴まひろ(onnx)', description='', credit='黄琴まひ ろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/kikoto_mahiro/terms_of_use.txt', iconFile='kikoto_mahiro.png', speakers={'0': 'target'}, modelFile='kikoto_mahiro_v2_40k_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='KikotoMahiro_o')
[Voice Changer] ONNX Model: Official v2 like
SlotInfo::: RVCModelSlot(slotIndex=3, voiceChangerType='RVC', name='刻鳴時雨(onnx)', description='', credit='刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tokina_shigure/terms_of_use.txt', iconFile='tokina_shigure.png', speakers={'0': 'target'}, modelFile='tokina_shigure_v2_40k_e100_simple.onnx', indexFile='added_IVF2736_Flat_nprobe_1_v2.index.bin', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='TokinaShigure_o')
[Voice Changer] custom matplotlib loaded successfully
 [Loading] model_dir\4\combo_spk5_nl3_dl20_k50_500ep.ptc.bin
SlotInfo::: DiffusionSVCModelSlot(slotIndex=4, voiceChangerType='Diffusion-SVC', name='初期メン(3,20)', description='', credit='あみたろ,つくよみちゃん,黄琴海月,黄琴まひろ,刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/diffusion-svc/term_of_use.txt', iconFile='diffusion-svc.png', speakers={1: 'user1', 2: 'user2', 3: 'user3', 4: 'user4', 5: 'user5'}, modelFile='combo_spk5_nl3_dl20_k50_500ep.ptc.bin', isONNX=False, modelType='combo', dstId=1, sampleId='diffusion_combo_spk5_nl3_dl20_k50_500ep', defaultTune=0, defaultKstep=50, defaultSpeedup=25, kStepMax=50, nLayers=20, nnLayers=3, embedder='hubert_base', samplingRate=44100, embChannels=768)
 [Loading] model_dir\5\combo_spk5_nl3_dl1_k50_500ep.ptc.bin
SlotInfo::: DiffusionSVCModelSlot(slotIndex=5, voiceChangerType='Diffusion-SVC', name='初期メン(3,1)', description='', credit='あみたろ,つくよみちゃん,黄琴海月,黄琴まひろ,刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/diffusion-svc/term_of_use.txt', iconFile='diffusion-svc.png', speakers={1: 'user1', 2: 'user2', 3: 'user3', 4: 'user4', 5: 'user5'}, modelFile='combo_spk5_nl3_dl1_k50_500ep.ptc.bin', isONNX=False, modelType='combo', dstId=1, sampleId='diffusion_combo_spk5_nl3_dl1_k50_500ep', defaultTune=0, defaultKstep=50, defaultSpeedup=25, kStepMax=50, nLayers=1, nnLayers=3, embedder='hubert_base', samplingRate=44100, embChannels=768)
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[VCClient] wait web server...10 http://127.0.0.1:18888/
[VCClient] wait web server...20 http://127.0.0.1:18888/
[VCClient] wait web server...30 http://127.0.0.1:18888/
[VCClient] wait web server...40 http://127.0.0.1:18888/
[VCClient] wait web server...50 http://127.0.0.1:18888/
[VCClient] wait web server...60 http://127.0.0.1:18888/
[VCClient] wait web server...70 http://127.0.0.1:18888/
[VCClient] wait web server...80 http://127.0.0.1:18888/
[VCClient] wait web server...90 http://127.0.0.1:18888/
[VCClient] wait web server...100 http://127.0.0.1:18888/
[VCClient] wait web server...110 http://127.0.0.1:18888/
[VCClient] wait web server...120 http://127.0.0.1:18888/
[VCClient] wait web server...130 http://127.0.0.1:18888/
[VCClient] wait web server...140 http://127.0.0.1:18888/
[VCClient] wait web server...150 http://127.0.0.1:18888/
[VCClient] wait web server...160 http://127.0.0.1:18888/
[VCClient] wait web server...170 http://127.0.0.1:18888/
[VCClient] wait web server...180 http://127.0.0.1:18888/
[VCClient] wait web server...190 http://127.0.0.1:18888/
[VCClient] wait web server...200 http://127.0.0.1:18888/
[VCClient] wait web server...210 http://127.0.0.1:18888/
[VCClient] wait web server...220 http://127.0.0.1:18888/
[VCClient] wait web server...230 http://127.0.0.1:18888/
[VCClient] wait web server...240 http://127.0.0.1:18888/
[VCClient] wait web server...250 http://127.0.0.1:18888/
[VCClient] wait web server...260 http://127.0.0.1:18888/
[VCClient] wait web server...270 http://127.0.0.1:18888/
[VCClient] wait web server...280 http://127.0.0.1:18888/
[VCClient] wait web server...290 http://127.0.0.1:18888/
[VCClient] wait web server...300 http://127.0.0.1:18888/
[VCClient] wait web server...310 http://127.0.0.1:18888/
[VCClient] wait web server...320 http://127.0.0.1:18888/
[VCClient] wait web server...330 http://127.0.0.1:18888/
[VCClient] wait web server...340 http://127.0.0.1:18888/
[VCClient] wait web server...350 http://127.0.0.1:18888/
[VCClient] wait web server...360 http://127.0.0.1:18888/
[VCClient] wait web server...370 http://127.0.0.1:18888/
[VCClient] wait web server...380 http://127.0.0.1:18888/
[VCClient] wait web server...390 http://127.0.0.1

**Comment by MichaelChoco** [comment]
Same case, tried reboot or flush dns still don't work

**Comment by Kisamij** [comment]
i found a method for open the port, i opened it but now it said  me invalid request , what i do???

**Comment by Kisamij** [comment]
> Same case, tried reboot or flush dns still don't work

Listen, I tried to open the ports, disable the firewall etc... With poor results, as a last resort I upgraded Windows 10 to 11 and now it works

**Comment by Kisamij** [comment]
> Same case, tried reboot or flush dns still don't work

Listen, I tried to open the ports, disable the firewall etc... With poor results, as a last resort I upgraded Windows 10 to 11 and now it works

**Comment by w-okada** [comment]
try access with the chrome 
http://127.0.0.1:18888/
or
http://localhost:18888/

**Comment by Kisamij** [comment]
> try access with the chrome 
> http://127.0.0.1:18888/
> or
> http://localhost:18888/
> 

I resolved, i updated windows 10 to 11 and now works

**Comment by w-okada** [comment]
OK close

**Comment by William20** [comment]
The real resolution is to delete the stored_setting.json file

**Comment by weewoo-teehee** [comment]
So I kinda went to check on that updating solution and as it would turn out, I already have Windows 11 so I don't know now how to resolve this; I did try the "delete the stored_setting.json" thing too just because but no results.
