### ISSUE TITLE
Program doesnt open

### ISSUE THREAD

**Issue by mrbeastqw1** [w-okada/voice-changer#735]
### Issue Type

Bug Report

### vc client version number

vcclient000 / MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.12.zip

### OS

Windows 10

### GPU

Nvidea RTX 3070

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

idk

### Model type

pyTorch

### Situation

The program doesnt start if i click on the start_http folder, it shows up for like a second and closes. If i spam click the folder it sometimes opens but it isnt doing the download. I have Python and Pytorch (Anaconda) and i even excluded the folder from my firewall. Idk what to do

### logs on terminal

idk what i have to put in here

**Comment by Rafacasari** [comment]
You're using the AMD version. Use the **MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12** version

**Comment by mrbeastqw1** [comment]
but i have amd

**Comment by Rafacasari** [comment]
but you put nvidia rtx 3070 on your specs lol

**Comment by mrbeastqw1** [comment]
ah nvm i tought u meant cpu. I tried the version you recommended but it has the same problem

**Comment by mrbeastqw1** [comment]
ah nvm i tought u meant cpu. I tried the version you recommended but it has the same problem

**Comment by mrbeastqw1** [comment]
nvm it started
