### ISSUE TITLE
Voices dont work

### ISSUE THREAD

**Issue by mrbeastqw1** [w-okada/voice-changer#736]
### Issue Type

Bug Report

### vc client version number

Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.' [Voice Changer] Pipeline is not initialized. [Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.' 'Pipeline is not initialized.' Traceback (most recent call last):   File "voice_changer\VoiceChangerV2.py", line 228, in on_request   File "voice_changer\RVC\RVCr2.py", line 155, in inference Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.' [Voice Changer] Pipeline is not initialized. [Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.' 'Pipeline is not initialized.' Traceback (most recent call last):   File "voice_changer\VoiceChangerV2.py", line 228, in on_request   File "voice_changer\RVC\RVCr2.py", line 155, in inference Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.' [Voice Changer] Pipeline is not initialized. [Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.' 'Pipeline is not initialized.' Traceback (most recent call last):   File "voice_changer\VoiceChangerV2.py", line 228, in on_request   File "voice_changer\RVC\RVCr2.py", line 155, in inference Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'

### OS

Windows 10

### GPU

Nvidea RTX 3070

### Clear setting

no

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

idk

### Model type

pyTorch

### Situation

The voices dont work, it says PIpeline is not initialized 

### logs on terminal

Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'
[Voice Changer] Pipeline is not initialized.
[Voice Changer] VC PROCESSING EXCEPTION!!! 'Pipeline is not initialized.'
'Pipeline is not initialized.'
Traceback (most recent call last):
  File "voice_changer\VoiceChangerV2.py", line 228, in on_request
  File "voice_changer\RVC\RVCr2.py", line 155, in inference
Exceptions.PipelineNotInitializedException: 'Pipeline is not initialized.'

**Comment by mrbeastqw1** [comment]
?

**Comment by lohad** [comment]
Do you have pytorch installed?
If you are unsure, open Command prompt and copy-paste: 'pip show torch'
If you see a version number and don't get an error, then you have Pytorch, thus I can not help you any further.

 If you do get an error, copy-paste this command to start installing Pytorch: 'pip install torch'
This should fix your problem. I hope this helps.

**Comment by w-okada** [comment]
Show me further up the log.

**Comment by dedu94br** [comment]
dude my voices don't work too, is like the app is not detecting my microphone in my notebook

**Comment by w-okada** [comment]
no res close
