### ISSUE TITLE
programm doesn't start

### ISSUE THREAD

**Issue by wedunge** [w-okada/voice-changer#738]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12

### OS

windows11

### GPU

asus rgx 3070 ti oc edition

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

idk

### Model type

pyTorch

### Situation

The program doesnt start if i click on the start_http folder, it doesn't show up. If i spam click the folder it sometimes opens for a second but after it closes again. I have Python and Pytorch. Idk what to do

### logs on terminal

idk what to put here

**Comment by wedunge** [comment]
could someone help me this problem

**Comment by w-okada** [comment]
When you type "cmd" into the address bar of the Explorer, a black screen will appear. Please try to execute "start_http.bat" there.
![image](https://github.com/w-okada/voice-changer/assets/48346627/19dcd393-cf26-4181-bc0a-a724867c5953)
