### ISSUE TITLE
( PLEASE HELP )batch file is not recognized as an internal or external program

### ISSUE THREAD

**Issue by TrueNightedge** [w-okada/voice-changer#739]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12a

### OS

windows 10

### GPU

NVIDIA GeForce GTX 1050

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

MMVC

### Model type

pytorch Stable (2.0.1)

### Situation

whenever i run the .bat file in admin it just open the cmd and closes immediately, i added a "pause" at the end of the cmd and it just says "'MMVCServerSIO.exe' is not recognized as an internal or external command, if i don't run it in admin it just do another error (i uploaded a screenshot) operable program or batch file.''
This doesn't happen with just this file, every .batch file i try to run does this error.

Please help.

### application window capture

![Screenshot 2023-08-19 134759](https://github.com/w-okada/voice-changer/assets/105174287/1a1430c2-edcb-436f-b8e8-5b71c19f81a9)

### logs on terminal

C:\WINDOWS\system32>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
'MMVCServerSIO.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\WINDOWS\system32>pause
Press any key to continue . . .

**Comment by Rafacasari** [comment]
Are you opening the batch file by double clicking it? You don't need to use CMD to open a batch file

**Comment by TrueNightedge** [comment]
i tried every single way to open it, i double clicked, and used the cmd it doesn't work

**Comment by w-okada** [comment]
Why are you running it in C:\WINDOWS\system32>? It just seems like the path may not be correctly set.

**Comment by w-okada** [comment]
uuuummmm
I have no idea, but your log show this. I think this is the reason. But if you launch from desktop, I have no idea at all.

![image](https://github.com/w-okada/voice-changer/assets/48346627/ab8b9943-2c71-4806-8503-78de2cab85ec)

**Comment by w-okada** [comment]
no res close

**Comment by TrueNightedge** [comment]
damn, guess i just can't
