### ISSUE TITLE
Onnx version of rmvpe

### ISSUE THREAD

**Issue by 0RadicalLarry0** [w-okada/voice-changer#744]
### Issue Type

Feature Request

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.12a.zip

### OS

Windows 10

### GPU

AMD Radeon 5700 XT

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

This is going to come across as a possibly stupid question, but I see there is an onnx version of rmvpe out in the wild, would it be possible to implement it into the voice changer?

https://huggingface.co/lj1995/VoiceConversionWebUI/blob/main/rmvpe.onnx

### logs on terminal

N/A

**Comment by Rafacasari** [comment]
I think here is the implementation of rmvpe onnx, for amd users, maybe this can be useful for you @w-okada 
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/b83939ba048e22ed748b72484e450afe472dadf0/lib/rmvpe.py#L580

**Comment by w-okada** [comment]
Done.
Try the latest version v.1.5.3.13. And read tutorial.

**Comment by 0RadicalLarry0** [comment]
Nice! No issues with rmvpe_onnx so far, much better performance.

**Comment by Denis6902** [comment]
> Nice! No issues with rmvpe_onnx so far, much better performance.

what settings do you have please?
