### ISSUE TITLE
Multichannel Asio interface, how to select the desired channel(s) ?

### ISSUE THREAD

**Issue by Mozoloa** [w-okada/voice-changer#745]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.12.zip

### OS

Windows 11

### GPU

RTX3090FE

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

f0

### Situation

I'm trying to select which channel I want as input or output from my asio interface, which has 18 of them,
![image](https://github.com/w-okada/voice-changer/assets/20817233/0e8f4f79-8204-46cc-a8d5-a2fbb8d95f9e)
but as you can see there's only 1 available option, and I don't know what's it's supposed to, plenty of those asio channels are loopback so I'm even afraid of trying lmao. How come we can't select a single or couple of channels ?

### application window capture

![image](https://github.com/w-okada/voice-changer/assets/20817233/f8ecfa05-286f-497b-90b6-bb96cf727714)

### logs on terminal

    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
Try loading... model_dir\6\angele.index
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\6\angele.index
Pipeline has been deleted
[VCClient] wait web server... done 200
[2023-08-21 14:29:45] connet sid : haYvVHcnNhkxq9uFAAAC
[2023-08-21 14:29:45] connet sid : 8Dd6YFw4F7ZxhE4_AAAD
[Voice Changer] update configuration: serverInputDeviceId 20
[Voice Changer] update configuration: serverInputDeviceId -1
[2023-08-21 14:31:46] connet sid : DMC34c-h4n3gnPm4AAAF
[2023-08-21 14:31:46] connet sid : qfe6-PEo183XnvNoAAAH
[Voice Changer] update configuration: serverInputDeviceId 20
[Voice Changer] update configuration: serverInputDeviceId -1
[Voice Changer] update configuration: serverInputDeviceId 20
[Voice Changer] update configuration: serverOutputDeviceId 20

**Comment by w-okada** [comment]
I'm not very familiar with ASIO. If you want to use only specific channels for input, it's not supported at the moment. Please try to utilize a mixer or something similar to input only required channels.

**Comment by w-okada** [comment]
no res close

**Comment by cvillela** [comment]
I would be very interested in this feature also! @Mozoloa do you have a solution for this?
