### ISSUE TITLE
请问一下作者，您的客户端为什么可以自带降噪

### ISSUE THREAD

**Issue by yuanqiyinpin** [w-okada/voice-changer#749]
### Issue Type

Bug Report, Question

### vc client version number

15.3.8a

### OS

win10

### GPU

3090

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

onnx

### Situation

相比RVC。您这个客户端使用RVC模型，抑制噪音比直接启动RVC那个要好，直接启动的RVC收音非常大，您这个客户端启用RVC时候，收音会好很多！我想请问作者怎么做到的？如何实现收音功能

### application window capture

1

### logs on terminal

1

**Comment by w-okada** [comment]
I have no idea.
