### ISSUE TITLE
Cpu Freqencey

### ISSUE THREAD

**Issue by benc1221** [w-okada/voice-changer#752]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12a

### OS

Windows 10

### GPU

Rtx 4080

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

when i was messing around with the index file i noticed that my cpu frequency wont go above 4.2ghz and when i turned the index file to 0 it went up to 4.8ghz so is this a bug when using an index file?

### logs on terminal

![2](https://github.com/w-okada/voice-changer/assets/89867041/df1053d6-8fb2-4395-879a-4c52cb78179b)
![Capture](https://github.com/w-okada/voice-changer/assets/89867041/0c596b79-9ec3-4e6d-ac78-32e53a7e8af1)

**Comment by w-okada** [comment]
This is because the Windows version of Faiss does not support AVX. There would be no issue if you run it on Linux (WSL).

https://github.com/facebookresearch/faiss/issues/2872

Please contact the Faiss developers if necessary.
