### ISSUE TITLE
GPU Not Detecting

### ISSUE THREAD

**Issue by ThomasAlvenin** [w-okada/voice-changer#754]
### Issue Type

Bug Report, Question

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.12a

### OS

Windows 10, 64 bits

### GPU

RX 580 2048SP

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

Ok, so, i have tried the onnxgpu version but i only could select CPU, im using onnxdirectML version and i think it's only using my CPU, all models are very laggy and i have too increase the chunk a lot to hear it without lag, everytime i launch it it says: Initialized (GPU_NUM(cuda):0, mps_enabled:False, onnx_device:CPU-DML)

Wich i think it means that it isnt's detecting my GPU, i already tried updating drivers, reinstalling them, etc.

Any help?

### application window capture

![image](https://github.com/w-okada/voice-changer/assets/105067427/39a82f0f-2575-476e-9249-69bdf7ab62f0)
![image](https://github.com/w-okada/voice-changer/assets/105067427/c891faf1-7c66-490d-87f6-a9a7952cd662)

### logs on terminal

C:\Users\alven\3D Objects\Ai\MMVCServerSIODirect>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] model slot is changed -1 -> 2
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:False, onnx_device:CPU-DML)
[Voice Changer][RVC]: update_settings gpu:1
[Voice Changer][RVCr2] Initializing...
2023-08-24 18:37:56.2245161 [W:onnxruntime:, session_state.cc:1169 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-08-24 18:37:56.2531117 [W:onnxruntime:, session_state.cc:1171 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] generate new embedder. (no embedder)
[VCClient] wait web server...10 http://127.0.0.1:18888/
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x000002FE234BF340>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x000002FE23520310>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x000002FE235203A0>
[Voice Changer] [RVC] Initializing... done

**Comment by w-okada** [comment]
gpu usage is about 20%. Isn't the GPU being used?
And use dio. harverst is very heavy.

**Comment by ThomasAlvenin** [comment]
> gpu usage is about 20%. Isn't the GPU being used? And use dio. harverst is very heavy.

When i click start the GPU usage goes to 20% but CPU's goes up to 80%

**Comment by w-okada** [comment]
???
So, you could use gpu? what is problem?

> CPU's goes up to 80%

This is different issue?

**Comment by GatienDoesStuff** [comment]
Harvest pitch detection runs on CPU. You could put it to crepe_full or crepe_tiny instead, since both of those settings rely on onnx for GPU acceleration (rmvpe and crepe rely on pytorch, which doesn't work under directML on voice-changer)

Also, the GPU (dml) setting is not right, it's currently trying to use a GPU at index 1, which doesn't exist. You need to put gpu0, as that's what is reported by task manager. Hope this helps you getting this to run.

**Comment by w-okada** [comment]
no update close

**Comment by oleggong66** [comment]
I want to ask if I was able to solve the problem, because I have the same GPU and have a similar problem
thank you in advance

**Comment by oleggong66** [comment]
I want to know if you were able to solve the problem, because I have the same GPU and have a similar problem
thank you in advance
