### ISSUE TITLE
Voice not processing

### ISSUE THREAD

**Issue by DominicMinercraf** [w-okada/voice-changer#756]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_v.1.5.3.12a_onnxdirectML-cuda

### OS

Windows 11

### GPU

NVIDIA GeForce GTX 1660 Ti

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

MMVC v1.5.3.12a

### Model type

ONNX-cuda

### Situation

Ive downloaded the application following each step and everything loaded up without any problems, however whenever i hit the start button to test out voices nothing ever comes back at me. Ive tried changing many settings such as the chunk and extra, and changing output but nothing seems to have worked to get the app to process my voice. Ive made sure that it is registering my mic by using the passthrough option, and it can understand me just fine, but it doesnt change my voice and send the information back.

### application window capture

![app window capture](https://github.com/w-okada/voice-changer/assets/141518211/b408f56c-c606-4275-96e5-6f19728b607e)

### logs on terminal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 30, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] update configuration: serverReadChunkSize 960
[Voice Changer] update configuration: extraConvertSize 16384
[Voice Changer] update configuration: extraConvertSize 65536
[Voice Changer] update configuration: serverReadChunkSize 16
[Voice Changer] update configuration: extraConvertSize 4096
[Voice Changer] update configuration: serverReadChunkSize 960
[Voice Changer] update configuration: extraConvertSize 131072
[Voice Changer] update configuration: serverReadChunkSize 64
[Voice Changer] update configuration: extraConvertSize 4096
[Voice Changer] update configuration: modelSlotIndex 1692914445000
[Voice Changer] update configuration: tran 2
[Voice Changer] update configuration: tran 5
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: tran 15
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cuda:0
[Voice Changer] update configuration: tran 18
[Voice Changer] update configuration: tran 20
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 424, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 30, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] update configuration: tran 21
[Voice Changer] update configuration: tran 23
[Voice Changer] update configuration: tran 22
[Voice Changer] update configuration: tran 31
[Voice Changer] update configuration: tran 25
[Voice Changer] update configuration: tran 29
[Voice Changer] update configuration: tran 32
[Voice Changer] update configuration: tran 33
[Voice Changer] update configuration: tran 34
[Voice Changer] update configuration: tran 30
[Voice Changer] update configuration: tran 23
[Voice Changer] update configuration: tran 19
[Voice Changer] update configuration: tran 15
[Voice Changer] update configuration: tran 13
[Voice Changer] update configuration: tran 12
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: tran 12
[Voice Changer] update configuration: tran 13
[Voice Changer] update configuration: tran 14
[Voice Changer] update configuration: tran 15
[Voice Changer] update configuration: tran 14
[Voice Changer] update configuration: tran 13
[Voice Changer] update configuration: tran 12
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: tran 9
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: serverReadChunkSize 960
[Voice Changer] update configuration: extraConvertSize 131072
[2023-08-24 18:07:58] connet sid : CMmtv1wxRw7pnFFHAAAG
[2023-08-24 18:07:58] connet sid : s1Dz38L-rZhU3FBlAAAH
SlotInfo::: RVCModelSlot(slotIndex=0, voiceChangerType='RVC', name='つくよみちゃん(onnx)', description='', credit='つく
よみちゃん', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tsukuyomi-chan/terms_of_use.txt', iconFile='tsukuyomi-chan.png', speakers={'0': 'target'}, modelFile='tsukuyomi_v2_40k_e100_simple.onnx', indexFile='', defaultTune=8, defaultIndexRatio=0.0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='Tsukuyomi-chan_o')
SlotInfo::: RVCModelSlot(slotIndex=0, voiceChangerType='RVC', name='つくよみちゃん(onnx)', description='', credit='つく
よみちゃん', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tsukuyomi-chan/terms_of_use.txt', iconFile='tsukuyomi-chan.png', speakers={'0': 'target'}, modelFile='tsukuyomi_v2_40k_e100_simple.onnx', indexFile='', defaultTune=8, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='Tsukuyomi-chan_o')
SlotInfo::: RVCModelSlot(slotIndex=0, voiceChangerType='RVC', name='つくよみちゃん(onnx)', description='', credit='つく
よみちゃん', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tsukuyomi-chan/terms_of_use.txt', iconFile='tsukuyomi-chan.png', speakers={'0': 'target'}, modelFile='tsukuyomi_v2_40k_e100_simple.onnx', indexFile='', defaultTune=8, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='Tsukuyomi-chan_o')
[Voice Changer] update configuration: rvcQuality 1
[Voice Changer] update configuration: silenceFront 0
[Voice Changer] update configuration: enableServerAudio 1
[Voice Changer] update configuration: serverAudioStated 1
[Voice Changer] update configuration: serverAudioStated 0
[Voice Changer] update configuration: enableServerAudio 0
[Voice Changer] update configuration: rvcQuality 0
[Voice Changer] update configuration: silenceFront 1
[Voice Changer] update configuration: extraConvertSize 4096
[Voice Changer] update configuration: serverReadChunkSize 64

**Comment by Rafacasari** [comment]
wrong version, you're using AMD version

**Comment by Rafacasari** [comment]
Did u tried [MMVCServerSIO_win_**onnxgpu-cuda**_v.1.5.3.12a.zip](https://huggingface.co/wok000/vcclient000/blob/main/MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12a.zip) version? DirectML is for AMD GPUs

**Comment by DominicMinercraf** [comment]
ohhhh no i havent tried that one, ill try it thank you

**Comment by w-okada** [comment]
same
https://github.com/w-okada/voice-changer/issues/462
