### ISSUE TITLE
HELP i tried v1.5.3.11 1.5.3.12 and 1.5.3.12a

### ISSUE THREAD

**Issue by Raktos1030** [w-okada/voice-changer#759]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.11.zip

### OS

Windows 10

### GPU

rx 6700

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.11.zip

### Model type

???

### Situation

I don't know what should i say but it doesnt work. I tried to find someone with the same issue but that was on older versions, i tried to delete model_dir, i didnt find the stored_setting.json. Ask me if you need some info to help me. btw sorry for my english :') i

### logs on terminal

E:\MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.11\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Voice Changerを起動しています。
                                                                                                                       [Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] Downloading model files...
                                                                                                                       [Voice Changer] Generating metadata...
[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] ONNX Model: Official v2 like
[Voice Changer] custom matplotlib loaded successfully
 [Loading] model_dir\4\combo_spk5_nl3_dl20_k50_500ep.ptc.bin
 [Loading] model_dir\5\combo_spk5_nl3_dl1_k50_500ep.ptc.bin
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    ブラウザで次のURLを開いてください.
    http://<IP>:<PORT>/
    多くの場合は次のいずれかのURLにアクセスすると起動します。
    http://localhost:18888/

[VCClient] Access http://localhost:18888/
(node:4404) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:18888
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
(node:4404) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
-102 ERR_CONNECTION_REFUSED http://localhost:18888/
Preparing your application. Please wait...
(node:4404) electron: Failed to load URL: http://localhost:18888/ with error: ERR_CONNECTION_REFUSED
Traceback (most recent call last):
  File "MMVCServerSIO.py", line 241, in <module>
  File "subprocess.py", line 1209, in wait
  File "subprocess.py", line 1506, in _wait
KeyboardInterrupt
[23148] Failed to execute script 'MMVCServerSIO' due to unhandled exception!
Terminer le programme de commandes (O/N) ?

**Comment by Raktos1030** [comment]
ohhh model type: onnx i think

**Comment by w-okada** [comment]
I have no idea. But try start_https.bat (not start_http.bat ) and access https://localhost:18888/ with chrome.

**Comment by Raktos1030** [comment]
already tried :/

**Comment by w-okada** [comment]
sorry, I have no idea
