### ISSUE TITLE
Use a different PC to use the voice changer

### ISSUE THREAD

**Issue by AleX-michinnom** [w-okada/voice-changer#763]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12a

### OS

Window 11

### GPU

GPU

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

MMVC

### Model type

ONNX

### Situation

I've tried everything else to reduce the voice changer delay, but it didn't work, so I'm trying to use MMVC on my laptop to reduce the delay, but I'm asking because there's no specific video or explanation. Could you teach me a video that can reduce the delay by running a voice changer on this other PC.

### application window capture

![image](https://github.com/w-okada/voice-changer/assets/58246564/18ef859d-5ba6-4e91-a39d-d693ce84e823)

### logs on terminal

I've tried everything else to reduce the voice changer delay, but it didn't work, so I'm trying to use MMVC on my laptop to reduce the delay, but I'm asking because there's no specific video or explanation. Could you teach me a video that can reduce the delay by running a voice changer on this other PC.
![다른PC](https://github.com/w-okada/voice-changer/assets/58246564/f0c00296-7693-47c3-838f-bc0436bf4d5a)

**Comment by w-okada** [comment]
There is no video.
