### ISSUE TITLE
Docker - No GPU usable

### ISSUE THREAD

**Issue by PapaBones** [w-okada/voice-changer#764]
### Issue Type

Bug Report, Question

### vc client version number

I git-pulled

### OS

Arch Linux

### GPU

RTX 4080

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

Unsure

### Situation

I've been trying to get it to run, I can only ever get the docker image running without GPU, if I start with I get the a text output saying it's not capable. Am I missing something? I pulled the latest version, according to git pull command "Updating 46ff05b..48d6732" though I am not sure(I am not well versed in git yet).

### logs on terminal

```
bash start_docker.sh
VC Client start...(with gpu)
start_docker.sh: line 22: hostname: command not found
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

```

**Comment by w-okada** [comment]
https://github.com/w-okada/voice-changer/blob/master/docker_vcclient/README_en.md

**Comment by w-okada** [comment]
no res close
