### ISSUE TITLE
Voice Changer not starting

### ISSUE THREAD

**Issue by FzNdr** [w-okada/voice-changer#765]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12a

### OS

Windows 11

### GPU

GTX 1660 TI Max-Q design

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

mmvc

### Model type

none

### Situation

Terminal not opening

### application window capture

terminal not opening

### logs on terminal

Its not opening

**Comment by w-okada** [comment]
no info close
