### ISSUE TITLE
 ~ Client not working ~

### ISSUE THREAD

**Issue by lee0eun0woo** [w-okada/voice-changer#766]
### Issue Type

Bug Report, Question

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.11

### OS

Windows 11

### GPU

GPU 0 ~ NVIDIA GeForce GTX 1650  GPU 1 ~ AMD Radeon(TM) Graphics

### Clear setting

no

### Sample model

yes

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

~ I tried to open the client again after I downloaded it 1 year ago, in that time it worked well but now it suddenly had a problem...

~ I opened it and it wasn't working ( When I started the client it was showing three text boxes in the top left corner 
[ ファイル ][ 表示 ][ ウィンドウ ] with I don't know what that means and then a blank white screen) I closed the client and everything and nothing was working right and I deleted the client folder and restarted my laptop. I downloaded it again but a different version and It worked this time but when I pressed start to start speaking and It would happen the same thing, white screen but the three text boxes in the top left corner where in English not in Japanese.

~ Then it started to say this:

~ Not every time tho [ I tried many and many times ]

### application window capture

![~~~~~~~~~](https://github.com/w-okada/voice-changer/assets/143286325/283cc10c-17d9-4b60-8c72-bca4824e19ee)
![~~~~~~~~~~~~~~](https://github.com/w-okada/voice-changer/assets/143286325/06b115f9-1874-4698-90b1-0e8c121135c2)

### logs on terminal

![~~~~~~~~~~~~~~](https://github.com/w-okada/voice-changer/assets/143286325/2eabcd62-c34b-4c57-a8ce-a8fe3dfb6c55)

**Comment by w-okada** [comment]
same

https://github.com/w-okada/voice-changer/issues/382

**Comment by lee0eun0woo** [comment]
~ I noticed that when I open Google Chrome or a game it does that and then when I press reload and forced reload it starts to do that...
