### ISSUE TITLE
More f0 detections options

### ISSUE THREAD

**Issue by benc1221** [w-okada/voice-changer#768]
### Issue Type

Feature Request

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13

### OS

Windows 10

### GPU

Rtx 4080

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

is it possible to implement REAPER, RAPT, YIN, SPTK, Swipe if possible?

### logs on terminal

none

**Comment by w-okada** [comment]
Can you tell me the advantages of each?

**Comment by benc1221** [comment]
Forget about those outdated estimations the one you need to look into is PitchNet.
The main advantages of PitchNet over RMVPE for pitch estimation include an improved accuracy, increased resistance to noise, enhanced adaptability, real-time capabilities, no need for preprocessing, automated feature learning, decreased computational complexity, and continual advancements. As such, owing to its strong deep learning architecture based on huge data collections, PitchNet outperforms RMVPE in important areas such as precision, resistance, adaptability, and efficacy for utilization in numerous pitch evaluation scenarios.  here is the paper for it https://arxiv.org/abs/2308.07170

**Comment by w-okada** [comment]
This one?

https://tencent-ailab.github.io/pitch-net/

I'm not sure if it's better than rmvpe.
Is it written in the thesis?

**Comment by benc1221** [comment]
https://arxiv.org/pdf/2308.07170.pdf this one

**Comment by w-okada** [comment]
I couldn't find they say pitchnet is better than rmvpe. Why do you think so?

And do you know repo implments it and sample?

**Comment by benc1221** [comment]
after further reading the PitchNet Estimation had not been updated since 2021 so i will close.
