### ISSUE TITLE
Question: Some words consistently mispronounce across models

### ISSUE THREAD

**Issue by Mojobones** [w-okada/voice-changer#773]
### Issue Type

Question

### vc client version number

v.1.5.3.13

### OS

Windows 11

### GPU

Nvidia 2080ti 

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

v.1.5.3.13, RVC v2

### Model type

PyTorch, RMVPE 

### Situation

Hello! 

This isn't a recent issue, and may not be due to voice changer, but I've noticed that there's some words that never pronounce correctly when speaking English. This is consistent across all models, including the built-in models. 

One easy example is the word "coral". The correct english pronunciation can be heard here:
https://drive.google.com/file/d/1-2GILMz7-UbN1NDcaZ7JFaG8qPHcKaPO/view

But the pronunciation when I say "coral" using voice changer and RVC models (regardless of chunk num or extra data length) can be heard here:
https://drive.google.com/file/d/1jskEbUkE_hhZII3fHmKtGi-tAvtkRt3l/view?usp=sharing

It sounds really off! This is one of the few problems I run into when using real time voice changing, as I often have to keep in mind the words that cause problems and avoid saying them.

I'm positive it's not a configuration issue as I've verified others have the same problem, and I've attempted to tweak every option to see if it's something possible to fix. 

Interestingly, the same issue seems to happen using RVC's file conversion, so it's not limited to real-time. 

I know it goes a bit beyond just voice changer, but I was curious if there was any insight you could offer into why this could be happening? 

Thank you for any insight you can provide, and for all the hard work you put into this application! It's greatly appreciated 🥰

### logs on terminal

N/A

**Comment by w-okada** [comment]
Is that an RVC issue? I don't think there's anything we can do with this app. Perhaps increasing the chunk size might solve the problem.

**Comment by Mojobones** [comment]
> Is that an RVC issue? I don't think there's anything we can do with this app. Perhaps increasing the chunk size might solve the problem.

Unfortunately it doesn't seem like chunk num increasing helps any. You're right about it likely being an RVC issue. Using file conversion with RVC still has this same problem. I'll see if they can help any. Thank you!

**Comment by Mojobones** [comment]
Closing since it's likely an RVC issue.
