### ISSUE TITLE
Imported model no sound/ not working 

### ISSUE THREAD

**Issue by XuanRTS** [w-okada/voice-changer#779]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13

### OS

windows 10

### GPU

Quadro T 1000 (4gb)

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

The four sample model came with the download was working fine, but when I import the model files by myself the model doesn't work, not a single sound at all. Did I did something wrong?

### application window capture

![image](https://github.com/w-okada/voice-changer/assets/54313735/261a9838-5c3f-4056-bd2f-7ad2c8833260)

The model:
![image](https://github.com/w-okada/voice-changer/assets/54313735/83f2b731-07cb-4087-9955-e8eec19e0d75)

### logs on terminal

D:\VoiceAI\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] model slot is changed -1 -> 4
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
2023-09-01 02:03:24.0640624 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-09-01 02:03:24.0725816 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] Loading index...
Try loading... model_dir\4\added_IVF4130_Flat_nprobe_12.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencer.RVCInferencer object at 0x000001E854AFBFA0>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x000001E857AB3E80>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x000001E857AB3EB0>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings f0Detector:crepe_tiny
[Voice Changer][RVC]: update_settings extraConvertSize:4096
[Voice Changer][RVC]: update_settings serverReadChunkSize:256
[Voice Changer][RVC]: update_settings modelSlotIndex:1693504478004
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2023-09-01 02:03:28] connet sid : IRgvX8u2mT6rMpb6AAAB
[2023-09-01 02:03:28] connet sid : oMeEUiJs_aecZPgTAAAD
[Voice Changer] update configuration: modelSlotIndex 1693505095004
[Voice Changer] model slot is changed 4 -> 4
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
Pipeline has been deleted
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
2023-09-01 02:05:07.9226371 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-09-01 02:05:07.9279431 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] Loading index...
Try loading... model_dir\4\added_IVF4130_Flat_nprobe_12.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencer.RVCInferencer object at 0x000001E8D7C8EE90>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x000001E857AB0A30>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x000001E857AB3070>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings f0Detector:crepe_tiny
[Voice Changer][RVC]: update_settings extraConvertSize:4096
[Voice Changer][RVC]: update_settings serverReadChunkSize:256
[Voice Changer][RVC]: update_settings modelSlotIndex:1693505095004
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] warming up... generating sola buffer.
[Voice Changer] update configuration: tran 10
[Voice Changer][RVC]: update_settings tran:10
[Voice Changer] update configuration: f0Detector dio
[Voice Changer][RVC]: update_settings f0Detector:dio
[Voice Changer] update configuration: serverReadChunkSize 384
[Voice Changer][RVC]: update_settings serverReadChunkSize:384
[Voice Changer] update configuration: serverReadChunkSize 1024
[Voice Changer][RVC]: update_settings serverReadChunkSize:1024
[Voice Changer] update configuration: serverReadChunkSize 2048
[Voice Changer][RVC]: update_settings serverReadChunkSize:2048
[Voice Changer] update configuration: serverReadChunkSize 768
[Voice Changer][RVC]: update_settings serverReadChunkSize:768

**Comment by Rafacasari** [comment]
Did u tried rvmpe/rvmpe_onnx? Do the default models work?

**Comment by XuanRTS** [comment]
> Did u tried rvmpe/rvmpe_onnx? Try exporting your model to ONNX and import the onnx file

Can't export to ONMX it says CUDA out of memory, maybe my GPU can't handle it

Logs:
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
2023-09-02 15:11:11.0804868 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-09-02 15:11:11.0887571 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] Loading index...
Try loading... model_dir\4\added_IVF4130_Flat_nprobe_12.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencer.RVCInferencer object at 0x000002173EF376D0>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x000002174037AD10>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEPitchExtractor.RMVPEPitchExtractor object at 0x000002174037B130>
[Voice Changer] [RVC] Initializing... done
[Voice Changer] exporting onnx... gpu_id:0 gpu_mem:4294639616
gin_channels: 256 self.spk_embed_dim: 109
============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

[Voice Changer] get_onnx ex: CUDA out of memory. Tried to allocate 54.00 MiB (GPU 0; 4.00 GiB total capacity; 2.74 GiB already allocated; 0 bytes free; 2.90 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by AhegaHOE** [comment]
Maybe the model is not working at all, where did you get it from?

**Comment by w-okada** [comment]
use cpu

**Comment by w-okada** [comment]
no res close
