### ISSUE TITLE
In real time voice changer, my voice is either delayed or not coming through at all.

### ISSUE THREAD

**Issue by awarenessaspie** [w-okada/voice-changer#785]
### Issue Type

Feature Request

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.12.zip

### OS

Windows 10

### GPU

AMD Radeon RX 570

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

pyTorch, ONNX, directML

### Situation

Hello,
When I turn on the RVC, my voice comes in late or not at all. I also tried MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13 even though I have an AMD video card. What could be the reason?
My hardware
Intel Xeon E3-1220V3
AMD Radeon RX 570 8GB
8 GB DDR3 1600 Mhz RAM

### logs on terminal

none 

C:\Users\This-PC\Desktop\MMVCServerSIO cuda>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] model slot is changed -1 -> 1
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:False, onnx_device:CPU-DML)
[Voice Changer][RVCr2] Initializing...
[VCClient] wait web server...10 http://127.0.0.1:18888/
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x0000024E83274850>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000024E9B51E6B0>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x0000024E9B51E740>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings gpu:2
[Voice Changer][RVCr2] Initializing...
EP Error  when using ['DmlExecutionProvider']
Falling back to ['CPUExecutionProvider'] and retrying.
[Voice Changer] generate new embedder. (anyway)
[VCClient] wait web server...20 http://127.0.0.1:18888/
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x0000024E9B51F520>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000024E9B51F580>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x0000024E9B51F640>
Pipeline has been deleted
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings serverReadChunkSize:384
[Voice Changer][RVC]: update_settings extraConvertSize:131072
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings modelSlotIndex:1693662827001
[VCClient] wait web server... done 200
[2023-09-02 21:54:21] connet sid : wHMAu5wYYo_NTEy0AAAB
[2023-09-02 21:54:21] connet sid : kqSfOVVpAU7MwgpvAAAD
[Voice Changer] update configuration: tran 5
[Voice Changer][RVC]: update_settings tran:5
[Voice Changer] update configuration: tran 6
[Voice Changer][RVC]: update_settings tran:6
[Voice Changer] update configuration: tran 7
[Voice Changer][RVC]: update_settings tran:7
[Voice Changer] update configuration: tran 8
[Voice Changer][RVC]: update_settings tran:8
[Voice Changer] update configuration: tran 12
[Voice Changer][RVC]: update_settings tran:12
[Voice Changer] update configuration: tran 13
[Voice Changer][RVC]: update_settings tran:13
[Voice Changer] update configuration: tran 14
[Voice Changer] update configuration: tran 15
[Voice Changer][RVC]: update_settings tran:14
[Voice Changer][RVC]: update_settings tran:15
[Voice Changer] update configuration: tran 15
[Voice Changer] update configuration: tran 17
[Voice Changer] update configuration: tran 18
[Voice Changer][RVC]: update_settings tran:15
[Voice Changer][RVC]: update_settings tran:17
[Voice Changer][RVC]: update_settings tran:18
[Voice Changer] update configuration: tran 20
[Voice Changer][RVC]: update_settings tran:20
[Voice Changer] update configuration: tran 21
[Voice Changer][RVC]: update_settings tran:21
[Voice Changer] update configuration: tran 22
[Voice Changer][RVC]: update_settings tran:22
[Voice Changer] update configuration: tran 23
[Voice Changer][RVC]: update_settings tran:23
[Voice Changer] update configuration: tran 23
[Voice Changer][RVC]: update_settings tran:23
[Voice Changer] update configuration: tran 24
[Voice Changer][RVC]: update_settings tran:24
[Voice Changer] update configuration: tran 33
[Voice Changer][RVC]: update_settings tran:33
[Voice Changer] update configuration: tran 32
[Voice Changer][RVC]: update_settings tran:32
[Voice Changer] update configuration: tran 31
[Voice Changer][RVC]: update_settings tran:31
[Voice Changer] update configuration: tran 31
[Voice Changer][RVC]: update_settings tran:31
[Voice Changer] update configuration: tran 30
[Voice Changer][RVC]: update_settings tran:30
[Voice Changer] update configuration: tran 29
[Voice Changer][RVC]: update_settings tran:29
[Voice Changer] update configuration: tran 28
[Voice Changer][RVC]: update_settings tran:28
[Voice Changer] update configuration: tran 27
[Voice Changer][RVC]: update_settings tran:27
[Voice Changer] update configuration: tran 26
[Voice Changer][RVC]: update_settings tran:26
[Voice Changer] update configuration: tran 25
[Voice Changer][RVC]: update_settings tran:25
[Voice Changer] update configuration: tran 24
[Voice Changer][RVC]: update_settings tran:24
[Voice Changer] update configuration: tran 23
[Voice Changer][RVC]: update_settings tran:23
[Voice Changer] update configuration: tran 22
[Voice Changer][RVC]: update_settings tran:22
[Voice Changer] update configuration: tran 21
[Voice Changer][RVC]: update_settings tran:21
[Voice Changer] update configuration: tran 20
[Voice Changer][RVC]: update_settings tran:20
[Voice Changer] update configuration: tran 20
[Voice Changer][RVC]: update_settings tran:20
[Voice Changer] update configuration: tran 19
[Voice Changer][RVC]: update_settings tran:19
[Voice Changer] update configuration: tran 19
[Voice Changer][RVC]: update_settings tran:19
[Voice Changer] update configuration: tran 18
[Voice Changer][RVC]: update_settings tran:18
[Voice Changer] update configuration: tran 19
[Voice Changer][RVC]: update_settings tran:19
[Voice Changer] update configuration: tran 20
[Voice Changer][RVC]: update_settings tran:20
[Voice Changer] update configuration: passThrough true
[Voice Changer][RVC]: update_settings passThrough:true
[Voice Changer] update configuration: passThrough false
[Voice Changer][RVC]: update_settings passThrough:false
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] warming up... generating sola buffer.
[2023-09-02 21:58:37] connet sid : 04meYmOH85VCR7xEAAAF
[2023-09-02 22:00:10] connet sid : QyT6xGPcNhqOlb7mAAAH
[2023-09-02 22:01:44] connet sid : Tnz-8yZHxm6eTdx2AAAJ
[2023-09-02 22:03:15] connet sid : UPVzOSsh1V5XEgxfAAAL
[2023-09-02 22:04:47] connet sid : F9e7Mef8L2cq4aQ1AAAN
[2023-09-02 22:06:19] connet sid : Mu-NRXfVHhxBGE2RAAAP
[2023-09-02 22:07:50] connet sid : BPo-w1HrVMeU-z3pAAAR
[2023-09-02 22:09:23] connet sid : Y2llQGa5csQd9OQlAAAT
[2023-09-02 22:10:53] connet sid : 6TvpfoUc0I9kZb68AAAV
[2023-09-02 22:12:29] connet sid : r_HzFbNIzQr4Mk3tAAAX
[2023-09-02 22:14:01] connet sid : HY_D9h0DqK96hALpAAAZ
[2023-09-02 22:15:34] connet sid : 73kou3mBO3U91laJAAAb
[2023-09-02 22:17:09] connet sid : ZzI86m4qhbzx0YFLAAAd
[2023-09-02 22:18:42] connet sid : ClpVTF3cKsaEOIo2AAAf
[2023-09-02 22:20:14] connet sid : c_EdQG5PRjccV014AAAh
[2023-09-02 22:21:45] connet sid : Xc5UXtiTgKz5ortrAAAj
[2023-09-02 22:23:18] connet sid : nakap8d9Z0mqAXuMAAAl
[2023-09-02 22:24:51] connet sid : EFw5XEduhrYnhw8EAAAn
[2023-09-02 22:26:23] connet sid : gfB_Wgx5TOMF1jCKAAAp
[2023-09-02 22:27:56] connet sid : D-L-kxoohqtY8usoAAAr
[2023-09-02 22:29:30] connet sid : jO0Ngmv_b55DFsvsAAAt
[2023-09-02 22:31:03] connet sid : 3Bdg7_a_6gLyYAgwAAAv
[2023-09-02 22:32:37] connet sid : MwCMJ3B6yUoeBA2iAAAx
[2023-09-02 22:34:10] connet sid : 5QchMJ4P_z0Q9pheAAAz
[2023-09-02 22:35:43] connet sid : 1RIseeTIckrfYUb-AAA1

**Comment by exciar** [comment]
try Nvidia gpu

**Comment by Rafacasari** [comment]
Use the latest directML version and use f0 set to rvmpe_onnx, and use only onnx models

**Comment by awarenessaspie** [comment]
> exciar



> Use the latest directML version and use f0 set to rvmpe_onnx, and use only onnx models

How do I do it?

**Comment by w-okada** [comment]
share your window capture

**Comment by awarenessaspie** [comment]
> Owner

![image](https://github.com/w-okada/voice-changer/assets/143903572/2dcaa821-1391-4aba-86ac-943f3d0983d9)

**Comment by w-okada** [comment]
set f0 Det to dio
select gpu0

**Comment by awarenessaspie** [comment]
> set f0 Det to dio select gpu0

how can I find f0 det to dio ?

**Comment by awarenessaspie** [comment]
it worked, thanks!

**Comment by w-okada** [comment]
OK close
