### ISSUE TITLE
Dont use GPU

### ISSUE THREAD

**Issue by FireynSS** [w-okada/voice-changer#790]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13.zip

### OS

windows11

### GPU

GTX TITAN 6GB

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

When you start changing the voice from the video card, the res parameter does not change. From the processor, it works with lags.

### application window capture

![image](https://github.com/w-okada/voice-changer/assets/141076410/9803b7c6-ed38-4227-91d7-4fe7421c4e0e)

### logs on terminal

MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
[VCClient] wait web server... done 200
[2023-09-04 18:30:08] connet sid : _C2rW-ogGMGzEJJ6AAAB
[2023-09-04 18:30:08] connet sid : bGjdGB_hgqe1av-fAAAD
[Voice Changer] update configuration: gpu 0
[Voice Changer] update configuration: modelSlotIndex 1693841414003
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
Try loading... model_dir\3\added_IVF2736_Flat_nprobe_1_v2.index.bin
[Voice Changer] update configuration: modelSlotIndex 1693841416003
[Voice Changer] update configuration: modelSlotIndex 1693841416003
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] update configuration: modelSlotIndex 1693841416003
Pipeline has been deleted
[Voice Changer] update configuration: modelSlotIndex 1693841417003
[Voice Changer] Loading index...
Try loading... model_dir\3\added_IVF2736_Flat_nprobe_1_v2.index.bin
[Voice Changer] generate new embedder. (anyway)
Pipeline has been deleted
[Voice Changer] Loading index...
[Voice Changer] generate new embedder. (anyway)
Try loading... model_dir\3\added_IVF2736_Flat_nprobe_1_v2.index.bin
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\3\added_IVF2736_Flat_nprobe_1_v2.index.bin
[Voice Changer] Loading index...
Try loading... model_dir\3\added_IVF2736_Flat_nprobe_1_v2.index.bin
Pipeline has been deleted
Pipeline has been deleted
SlotInfo::: RVCModelSlot(slotIndex=3, voiceChangerType='RVC', name='刻鳴時雨(onnx)', description='', credit='刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tokina_shigure/terms_of_use.txt', iconFile='tokina_shigure.png', speakers={'0': 'target'}, modelFile='tokina_shigure_v2_40k_e100_simple.onnx', indexFile='added_IVF2736_Flat_nprobe_1_v2.index.bin', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='TokinaShigure_o')
SlotInfo::: RVCModelSlot(slotIndex=3, voiceChangerType='RVC', name='刻鳴時雨(onnx)', description='', credit='刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tokina_shigure/terms_of_use.txt', iconFile='tokina_shigure.png', speakers={'0': 'target'}, modelFile='tokina_shigure_v2_40k_e100_simple.onnx', indexFile='added_IVF2736_Flat_nprobe_1_v2.index.bin', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='TokinaShigure_o')
SlotInfo::: RVCModelSlot(slotIndex=3, voiceChangerType='RVC', name='刻鳴時雨(onnx)', description='', credit='刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tokina_shigure/terms_of_use.txt', iconFile='tokina_shigure.png', speakers={'0': 'target'}, modelFile='tokina_shigure_v2_40k_e100_simple.onnx', indexFile='added_IVF2736_Flat_nprobe_1_v2.index.bin', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='TokinaShigure_o')

**Comment by Rafacasari** [comment]
Try using **rmvpe** in f0 Det.

**Comment by FireynSS** [comment]
> Try using **rmvpe** in f0 Det.

[Voice Changer] update configuration: f0Detector rmvpe
[Voice Changer] post_update_settings ex: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "restapi\MMVC_Rest_Fileuploader.py", line 71, in post_update_settings
  File "voice_changer\VoiceChangerManager.py", line 321, in update_settings
  File "voice_changer\VoiceChangerV2.py", line 155, in update_settings
  File "voice_changer\RVC\RVCr2.py", line 79, in update_settings
  File "voice_changer\RVC\pitchExtractor\PitchExtractorManager.py", line 25, in getPitchExtractor
  File "voice_changer\RVC\pitchExtractor\PitchExtractorManager.py", line 43, in loadPitchExtractor
  File "voice_changer\RVC\pitchExtractor\RMVPEPitchExtractor.py", line 21, in __init__
  File "voice_changer\DiffusionSVC\pitchExtractor\rmvpe\rmvpe.py", line 353, in __init__
  File "torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "torch\nn\modules\rnn.py", line 202, in _apply
    self._init_flat_weights()
  File "torch\nn\modules\rnn.py", line 139, in _init_flat_weights
    self.flatten_parameters()
  File "torch\nn\modules\rnn.py", line 190, in flatten_parameters
    torch._cudnn_rnn_flatten_weight(
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by FireynSS** [comment]
no work

**Comment by w-okada** [comment]
error said 
> RuntimeError: CUDA error: no kernel image is available for execution on the device

check your cuda installation and cudnn.

**Comment by w-okada** [comment]
no res close
