### ISSUE TITLE
what is the best hardware configuration to have minimal latency?

### ISSUE THREAD

**Issue by Skalpha0ne** [w-okada/voice-changer#796]
### Issue Type

Question

### vc client version number

version 13

### OS

Windows 10

### GPU

RX6800XT

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

ONNX

### Situation

I am currently using the software on an i9 10900K, 32GB ram and RX6800XT. But it's impossible to make voice work in real time. Too much latency. Based on your experience, what is the best hardware configuration to achieve minimal latency?
(sorry for my english, Im french)

### logs on terminal

yes

**Comment by w-okada** [comment]
Using a better-performing GPU/CPU can further reduce latency. It's as simple as that.

**Comment by Rafacasari** [comment]
Check [this](https://github.com/YunaOneeChan/Voice-Changer-Settings), it have the better settings for AMD, NVidia, Colab, etc

**Comment by w-okada** [comment]
no res close.
