### ISSUE TITLE
gpu not showing

### ISSUE THREAD

**Issue by betus888** [w-okada/voice-changer#800]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13.zip

### OS

win 10

### GPU

gtx 1660 ti

### Clear setting

yes

### Sample model

no

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX, pyTorch

### Situation

i have a gtx 1160ti and my GPU is not showing only  i can select cpu , how i can fix this? or i need to download an older version?

### application window capture

![Screenshot_5](https://github.com/w-okada/voice-changer/assets/144283948/be721fe9-72d9-4003-8694-81c317cd67e5)

### logs on terminal

................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x00000217C2ECB730>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x00000217C2F30580>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x00000217C2F30640>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings serverReadChunkSize:384
[Voice Changer][RVC]: update_settings f0Detector:crepe
[Voice Changer][RVC]: update_settings modelSlotIndex:1694033589000
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2023-09-06 15:21:53] connet sid : vgk_UT4FxRjfpGvxAAAB
[2023-09-06 15:21:53] connet sid : Df3aTlvJZiFyPfKEAAAD

**Comment by w-okada** [comment]
> VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:False, onnx_device:GPU)

no gpu is found. check driver.

**Comment by betus888** [comment]
it works thanks you are amazing

**Comment by w-okada** [comment]
ok great.
