### ISSUE TITLE
It doesn't use my GPU

### ISSUE THREAD

**Issue by ralyx** [w-okada/voice-changer#803]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.13.zip

### OS

Winows 11 22H2

### GPU

AMD RX 6800 16GB

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

I tried every possible setting reinstalled it,updated my drivers, changed every possible setting but it just doesn't use my gpu.Index is at 0 too i tried using every type of setting there dio,harvest and such.

![Ekran görüntüsü 2023-09-07 232035](https://github.com/w-okada/voice-changer/assets/82971350/94a9217c-cd8a-47ae-94f9-fdf95d3039ce)
%0,5 usage of gpu is crazy .

### application window capture

![Ekran görüntüsü 2023-09-07 230603](https://github.com/w-okada/voice-changer/assets/82971350/aa726d61-e31c-4367-9a3d-7cd1f4d6d51d)

### logs on terminal

C:\Users\Ralyx\Desktop\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
Try loading... model_dir\7\Copy of added_IVF920_Flat_nprobe_1_Omen_v2.index
[VCClient] wait web server... done 200
[2023-09-07 22:57:02] connet sid : NmVbYJj62OqqHb4HAAAC
[2023-09-07 22:57:02] connet sid : w36O3qR4i5q7HVNIAAAD

**Comment by Rafacasari** [comment]
Set f0 det. to **rmvpe_onnx** and **export to onnx** (and use the onnx model instead of .pth)

**Comment by ralyx** [comment]
Thanks i solved it by accident 10 minute ago it works like a charm now :)
