### ISSUE TITLE
My video card does not appear in the application

### ISSUE THREAD

**Issue by Calanguinhouwu** [w-okada/voice-changer#804]
### Issue Type

Bug Report

### vc client version number

1.15.13

### OS

Windows

### GPU

RX 6600m

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

My video card does not appear in the application becausa of this the voice is blocking and with a lot of delay

### application window capture

..,

### logs on terminal

idk

**Comment by Rafacasari** [comment]
You have a AMD GPU. You have to download the DirectML version, use **.ONNX models only** and **set rmvpe_onnx in f0 det.**

**Comment by w-okada** [comment]
use directml version

**Comment by w-okada** [comment]
no res close.
