### ISSUE TITLE
Web server doesn't open with ipv4

### ISSUE THREAD

**Issue by Tarodictrl** [w-okada/voice-changer#805]
### Issue Type

Bug Report, Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13

### OS

Windows 10

### GPU

GTX 1650

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

After starting start_http.bat starts the web server and if you open it in the browser at the address localhost, the client opens correctly, but if you open it by ipv4 address, an error is returned.

## ipv4
![image](https://github.com/w-okada/voice-changer/assets/58367115/dde163f2-230e-46f3-a9cb-65e975c2e90e)
![image](https://github.com/w-okada/voice-changer/assets/58367115/d291dd5a-1ec0-44cf-9e85-bfac55957ba6)

## localhost
![image](https://github.com/w-okada/voice-changer/assets/58367115/07d39c3d-5901-4557-9634-0f3a3a9e59ec)
![image](https://github.com/w-okada/voice-changer/assets/58367115/01388330-7436-4018-bc11-08bd5c67258e)

### logs on terminal

![image](https://github.com/w-okada/voice-changer/assets/58367115/094680f7-b96e-4ff4-84c7-9341ccabb4b1)

**Comment by w-okada** [comment]
what is issue??

**Comment by Rafacasari** [comment]
Try using the **start_https.bat** instead

**Comment by w-okada** [comment]
no res close.
