### ISSUE TITLE
can't find microphone

### ISSUE THREAD

**Issue by talktomorrow** [w-okada/voice-changer#806]
when i choose any mic it immidiatly give me an error: 
"NotReadableError: Could not start audio source
no stack"
i tried to install previous version? but didn't do anything, other programms can see mic
![SharedScreenshot](https://github.com/w-okada/voice-changer/assets/144442370/de025c70-331d-4b7f-9296-17fef15ed2a6)
![image](https://github.com/w-okada/voice-changer/assets/144442370/e3d13026-ebe5-46b6-8a7e-d04bb33277ef)

**Comment by w-okada** [comment]
use issue template

**Comment by alonce007** [comment]
Hi. I have the same problem. When selecting any microphone in input, it gives this error. Explain in detail how to solve it.

**Comment by maksimka32924** [comment]
как решить эту проблему с выбором микрофона ?

**Comment by AMISAYUMI** [comment]
> use issue template

what did u mean?
