### ISSUE TITLE
How to convert audio file with this client?

### ISSUE THREAD

**Issue by Fyphen1223** [w-okada/voice-changer#807]
### Issue Type

Question

### vc client version number

1.5.3.13

### OS

Windows 11

### GPU

RTX 3050

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

RVC

### Model type

PyTorch

### Situation

How to convert audio file with this voice changer?

### logs on terminal

No error.

**Comment by w-okada** [comment]
set input to file and select file

**Comment by Fyphen1223** [comment]
Thanks
