### ISSUE TITLE
start_http.bat

### ISSUE THREAD

**Issue by Nyssi1989** [w-okada/voice-changer#808]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13.zip

### OS

Windows 11

### GPU

RTX 3090

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

MMVC

### Model type

ONNX

### Situation

Opening the start_http.bat makes the console open, load for a few seconds and close itself. I tried to open it with admin rights, same outcome. Opening it in the folder via poweshell (rightclick+ shift) runs the .bat but then creates te following error:

"PermissionError: [Errno 13] Permission denied"

### logs on terminal

<img width="892" alt="image" src="https://github.com/w-okada/voice-changer/assets/144448999/ec3835c0-f530-457a-9266-fe71cd9ee80b">

**Comment by w-okada** [comment]
change permission of folder or open in other folder.

**Comment by Rafacasari** [comment]
Try creating a folder on desktop then extracting the files to that folder

**Comment by Nyssi1989** [comment]
I transferred the whole folder to my Desktop and it finally worked. Thanks a lot.

**Comment by Rafacasari** [comment]
> I transferred the whole folder to my Desktop and it finally worked. Thanks a lot.

So please close the issue
