### ISSUE TITLE
sound problem vol:0 res:0 with the correct settings

### ISSUE THREAD

**Issue by zxckorobka** [w-okada/voice-changer#813]
### Issue Type

Feature Request

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.11.zip

### OS

win10

### GPU

nvidia ge force gtx 1650 4gb

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pytorch

### Situation

audio playback does not work res and vol - 0 indicators
![767b0e59-290a-4920-9abd-e55b2f802985](https://github.com/w-okada/voice-changer/assets/144537660/eba498d8-2b4a-477d-99f5-bd262d7bf788)

### application window capture

![2023-09-09_17-53-43](https://github.com/w-okada/voice-changer/assets/144537660/3e1ea5dd-f2a0-4ab0-9174-dcc4032dee22)

### logs on terminal

![2023-09-09_17-53-43](https://github.com/w-okada/voice-changer/assets/144537660/76fc4950-077b-4467-81bf-f48f7fede14f)

**Comment by Rafacasari** [comment]
Try using f0 det. **rmvpe** and please give a fullscreen of the application.

**Comment by w-okada** [comment]
no update close.
