### ISSUE TITLE
Not using my AMD graphics card. Only my CPU.

### ISSUE THREAD

**Issue by Repsej01** [w-okada/voice-changer#814]
Issue Type
Bug Report

vc client version number
MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13

OS
Windows 11

GPU
Radeon RX 5700x

Clear setting
yes

Sample model
yes

Input chunk num
yes

Wait for a while
The GUI successfully launched.

read tutorial
yes

Extract files to a new folder.
yes

Voice Changer type
RVC

Model type
pyTorch

Situation
I am only using my CPU. My graphics are is not being used at all. This leads to the voices being very slow and barely functional.
CPU is used at 99% while the graphics card stays at the same value.

Image attached.

**Comment by Rafacasari** [comment]
Use DirectML version. Use f0 met on rmvpe_onnx and use only .onnx models.

**Comment by w-okada** [comment]
no update close.
