### ISSUE TITLE
Nvidia GPU not showing

### ISSUE THREAD

**Issue by quiji4** [w-okada/voice-changer#816]
### Issue Type

Feature Request, Question, Others

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13

### OS

win 11

### GPU

geforce rtx 4090

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

F0

### Situation

You can't select a GPU, there's only a CPU. I tried reinstalling the drivers, it didn't help.

### application window capture

![image](https://github.com/w-okada/voice-changer/assets/136175177/c2c781a7-8abe-49c4-86ae-484df2e77f2e)

### logs on terminal

![image](https://github.com/w-okada/voice-changer/assets/136175177/0e57dff1-a76e-49c9-b877-4e48ce7128c9)

**Comment by Rafacasari** [comment]
Check your drivers

**Comment by quiji4** [comment]
> проверьте свои драйверы

I checked my drivers, nothing has changed

**Comment by Rafacasari** [comment]
Did you have the cuda drivers?
https://developer.nvidia.com/cuda-downloads

**Comment by quiji4** [comment]
> Did you have the cuda drivers? Not sure if is needed but you can try to install it. https://developer.nvidia.com/cuda-downloads
> 
> Double check if your NVidia driver is updated: https://www.nvidia.com/Download/index.aspx

did not help

**Comment by w-okada** [comment]
In many cases, there is a problem with the driver's settings, as in the next issue. 
https://github.com/w-okada/voice-changer/issues/479

This issue does not cover the proper installation or configuration of drivers.

**Comment by w-okada** [comment]
no res close
