### ISSUE TITLE
default microphone not working

### ISSUE THREAD

**Issue by jcma111** [w-okada/voice-changer#821]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.13

### OS

win 11

### GPU

none

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.13 (i think thats what it means)

### Model type

PYTHON 3 . 10 . 11 (i think)

### Situation

![Screenshot 2023-09-10 212228](https://github.com/w-okada/voice-changer/assets/144630162/e72ce889-f889-44f5-a335-cff434b7dd73)
when i try to set the input to default microphone this screen comes up 
if i press ''initialize'' it takes me to the page with chunk settings and all the other things
but if i press ''reload without initialize'' it loads then takes me back the screen shown in screenshot.

### logs on terminal

[Voice Changer] loading index...
[Voice Changer] Index file not found

(i think that has something to do with it but im not very experienced with coding)

**Comment by Rafacasari** [comment]
You don't have a GPU? If that's the case I don't recomend the local usage. Use on Google Colab instead

**Comment by w-okada** [comment]
check permisison for microphone.

**Comment by w-okada** [comment]
no res close
