### ISSUE TITLE
KeyError: 'config'

### ISSUE THREAD

**Issue by stokiasu** [w-okada/voice-changer#823]
### Issue Type

Bug Report, Others

### vc client version number

 MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13

### OS

windows 11

### GPU

gtx 1660

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

get error when try to download sample voice

paramDict {'voiceChangerType': 'RVC', 'slot': 7, 'isSampleMode': False, 'sampleId': None, 'files': [{'name': 'D_2333333.pth', 'kind': 'rvcModel', 'dir': ''}, {'name': 'added_IVF126_Flat_nprobe_1_My-Voice_v2 (1).index', 'kind': 'rvcIndex', 'dir': ''}], 'params': {}}
RVC:: slotInfo.modelFile D_2333333.pth
[Voice Changer] post_load_model ex: 'config'
Traceback (most recent call last):
  File "restapi\MMVC_Rest_Fileuploader.py", line 92, in post_load_model
  File "voice_changer\VoiceChangerManager.py", line 170, in loadModel
  File "voice_changer\RVC\RVCModelSlotGenerator.py", line 37, in loadModel
  File "voice_changer\RVC\RVCModelSlotGenerator.py", line 43, in _setInfoByPytorch

KeyError: 'config'

### logs on terminal

.

**Comment by w-okada** [comment]
Please use an appropriate model. Model is under weights folder.

**Comment by w-okada** [comment]
no res close
