### ISSUE TITLE
voice get stuck

### ISSUE THREAD

**Issue by Calanguinhouwu** [w-okada/voice-changer#824]
### Issue Type

Question

### vc client version number

1.15.13

### OS

Windows

### GPU

RX 6600m

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

My delay is great but the voice keeps getting stuck and eating words, I wanted to know what setting I can change to improve this

### application window capture

![Imagem do WhatsApp de 2023-09-11 à(s) 12 47 26](https://github.com/w-okada/voice-changer/assets/144393699/b78ff774-6732-4b00-b6f6-978e9a7bc534)

### logs on terminal

C:\Users\kauat\OneDrive\Área de Trabalho\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] model slot is changed -1 -> 4
................RVC
[VCClient] wait web server...10 http://127.0.0.1:18888/
[VCClient] wait web server...20 http://127.0.0.1:18888/
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:False, onnx_device:CPU-DML)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
[VCClient] wait web server...30 http://127.0.0.1:18888/
2023-09-11 12:36:06.5394111 [W:onnxruntime:, session_state.cc:1169 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-09-11 12:36:06.5457420 [W:onnxruntime:, session_state.cc:1171 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x000002009C70FAF0>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x000002009C70FB50>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x000002009C70FBE0>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings f0Detector:rmvpe_onnx
[Voice Changer][RVC]: update_settings extraConvertSize:16384
[Voice Changer][RVC]: update_settings serverReadChunkSize:256
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings modelSlotIndex:1694145838004
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2023-09-11 12:38:31] connet sid : Dj2ejHxIRC_oIbo3AAAC
[2023-09-11 12:38:31] connet sid : 9KeGl0YD8ps2G_uxAAAD
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] warming up... generating sola buffer.
[Voice Changer] update configuration: extraConvertSize 131072
[Voice Changer][RVC]: update_settings extraConvertSize:131072
[Voice Changer] update configuration: serverReadChunkSize 128
[Voice Changer][RVC]: update_settings serverReadChunkSize:128
[Voice Changer] update configuration: serverReadChunkSize 320
[Voice Changer][RVC]: update_settings serverReadChunkSize:320
[Voice Changer] update configuration: extraConvertSize 16384
[Voice Changer][RVC]: update_settings extraConvertSize:16384
[Voice Changer] update configuration: extraConvertSize 131072
[Voice Changer][RVC]: update_settings extraConvertSize:131072
[Voice Changer] update configuration: extraConvertSize 16384
[Voice Changer][RVC]: update_settings extraConvertSize:16384
[Voice Changer] update configuration: serverReadChunkSize 256
[Voice Changer][RVC]: update_settings serverReadChunkSize:256
[Voice Changer] update configuration: extraConvertSize 131072
[Voice Changer][RVC]: update_settings extraConvertSize:131072
[Voice Changer] update configuration: extraConvertSize 16384
[Voice Changer][RVC]: update_settings extraConvertSize:16384

**Comment by Rafacasari** [comment]
Are you using .onnx model? .pth models don't work on AMD.

**Comment by w-okada** [comment]
no update close
