### ISSUE TITLE
Export to ONNX error

### ISSUE THREAD

**Issue by Art34222** [w-okada/voice-changer#826]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.13

### OS

Windows 11

### GPU

RX 6500 XT

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC V2

### Model type

pyTorch

### application window capture

![image](https://github.com/w-okada/voice-changer/assets/127204156/21343f1c-7ffe-46d3-88b0-c7247471520d)

### logs on terminal

On the screenshot

**Comment by Art34222** [comment]
The RAM fills up to 12 GB out of 16 and this error pops up, although 4 GB are still free

**Comment by w-okada** [comment]
use cpu
