### ISSUE TITLE
Not detecting/using my AMD GPU

### ISSUE THREAD

**Issue by lilaethon** [w-okada/voice-changer#827]
### Issue Type

Others

### vc client version number

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.13

### OS

Windows 10

### GPU

Radeon RX 6700 XT

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

no

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

ONNX

### Situation

Not using my GPU at all. Only using my CPU. I tried dio, harvest, crepe, crepe_tiny and it still uses my CPU.

### logs on terminal

![image](https://github.com/w-okada/voice-changer/assets/144735673/03d8130f-d31d-40cf-bbd5-cad7c2eb769c)

**Comment by Rafacasari** [comment]
Select **GPU0**, use f0 det on **rmvpe_onnx** or **crepe_tiny** and use **ONNX MODELS ONLY** (.pth models don't work on amd, use the "Export to Onnx" to convert the .pth to .onnx)

**Comment by default868** [comment]
> Select **GPU0**, use f0 det on **rmvpe_onnx** or **crepe_tiny** and use **ONNX MODELS ONLY** (.pth models don't work on amd, use the "Export to Onnx" to convert the .pth to .onnx)

done all you said. dont work anyways

**Comment by void-c0de** [comment]
yea pls @w-okada check this i have massive delays and chopping etc i dont even have bad specs not using my amd gpu too

**Comment by Shrapnel01** [comment]
you can learn more about how and where to put GPU0?

**Comment by w-okada** [comment]
no res close
