### ISSUE TITLE
Doesn't see notebook 870M GPU

### ISSUE THREAD

**Issue by neelevaj** [w-okada/voice-changer#828]
The program doesn't see the 870M GPU 
Everything is configured in the Nvidia control panel, other games and applications work fine

**Comment by Rafacasari** [comment]
Maybe your GPU is too old. Check the console for errors.

**Comment by neelevaj** [comment]
> Maybe your GPU is too old. Check the console for errors.


C:\Users\neelevaj\Downloads\MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
torch\cuda\__init__.py:651: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ..\c10\cuda\CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() if nvml_count < 0 else nvml_count
[Voice Changer] model slot is changed -1 -> 4
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
Try loading... model_dir\4\added_IVF1131_Flat_nprobe_1_s1mple_v2.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x000001E9FFEB7EB0>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x000001E9B9FFFD90>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x000001E9B9FFFDC0>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings serverReadChunkSize:640
[Voice Changer][RVC]: update_settings f0Detector:dio
[Voice Changer][RVC]: update_settings extraConvertSize:131072
[Voice Changer][RVC]: update_settings modelSlotIndex:1694481259004
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2023-09-12 05:16:19] connet sid : XHqo4PxIZVXN9jaTAAAB
[2023-09-12 05:16:19] connet sid : 6ctuK50Z7RDEZQxhAAAD

**Comment by neelevaj** [comment]
> Maybe your GPU is too old. Check the console for errors.

Okay, i saw driver update message, but i'm already delete my driver with DDU and install the last version. Is it mean, that my GPU is not support?

**Comment by Rafacasari** [comment]
Maybe. You can also run "nvidia-smi" on cmd to check the driver and cuda version

**Comment by neelevaj** [comment]
> Maybe. You can also run "nvidia-smi" on cmd to check the driver and cuda version

Cuda 3.0

**Comment by Rafacasari** [comment]
So your GPU is too old. Min CUDA version is 3.7

**Comment by neelevaj** [comment]
> So your GPU is too old. Min CUDA version is 3.7

Got it, okay

**Comment by Rafacasari** [comment]
Use Colab
https://colab.research.google.com/drive/1Aqv5TXO8BWZnpbLh3uGJ76aw2rUZYcwZ?usp=sharing#scrollTo=iuf9pBHYpTn-

or Kaggle
https://www.kaggle.com/code/rafacasari/wokada-voice-changer

**Comment by neelevaj** [comment]
> Use Colab https://colab.research.google.com/drive/1Aqv5TXO8BWZnpbLh3uGJ76aw2rUZYcwZ?usp=sharing#scrollTo=iuf9pBHYpTn-
> 
> or Kaggle https://www.kaggle.com/code/rafacasari/wokada-voice-changer

Kk, i will try it
