### ISSUE TITLE
[Feature Request] Configurable Global Shortcuts

### ISSUE THREAD

**Issue by Mr-Foxtrot** [w-okada/voice-changer#829]
### Issue Type

Feature Request

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13.zip

### OS

Windows 10

### GPU

NVIDIA GeForce RTX 2070 Super (8GB)

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

f0

### Situation

The software is amazing, only problem I see with it though is for say streamers: there isn't any options to bind specific voices to a shortcut or hotkey (say via a Stream Deck or just Keyboard). You have to manually go through the GUI to do anything to the voice settings or which voice you want to use. Configurable keybinds would be extremely helpful.

A shortcut for selecting a voice could be something like CTRL + SHIFT + X, where X is a number on the keyboard.
Also a shortcut for tuning the pitch could be, CTRL + [ or CTRL + ] to decrease/increase the pitch on the fly by a configurable amount (+3 or -3 by default).

### logs on terminal

Why need a log for a feature request?

**Comment by Rafacasari** [comment]
same https://github.com/w-okada/voice-changer/issues/677
