### ISSUE TITLE
low ms on dota2/apex/valorant, high ms on roblox

### ISSUE THREAD

**Issue by chinyballs** [w-okada/voice-changer#830]
### Issue Type

Question

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13

### OS

windows 10

### GPU

NVIDIA GTX 1050 Ti

### Clear setting

yes

### Sample model

yes

### Input chunk num

yes

### Wait for a while

yes

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

RVC

### Model type

pyTorch

### Situation

i got no problems on high spec games but when i open roblox i somehow get high ms and my voice lags. i tried increasing chunks and lowered index and thresh. i tried to download the new version which was updtaed 17 days ago and yes i downloaded the right one for my pc but i get the same problem. well most of my streams are roblox im just a small streamer helping kids get new in game items and guides
![image](https://github.com/w-okada/voice-changer/assets/144736086/bf2d1784-8491-4d00-93b6-b82ca37907e4)

### logs on terminal

![image](https://github.com/w-okada/voice-changer/assets/144736086/8235ec2b-537d-44d9-bfdc-137b395a3bba)

**Comment by chinyballs** [comment]
i forgot to mention yes i placed rvc quality low. increased the rvc priority to high on task manager the same issue.

**Comment by Rafacasari** [comment]
Use RMVPE on F0 Det, decrease the chunk size. If you want to play games and use voice changer I recommend trying the Colab/Kaggle version. 

https://colab.research.google.com/drive/1Aqv5TXO8BWZnpbLh3uGJ76aw2rUZYcwZ?usp=sharing
https://www.kaggle.com/code/rafacasari/wokada-voice-changer

**Comment by chinyballs** [comment]
the same result. i really dont know why because on valorant where we all
open mic and like its a heavy game my ms is stable and smooth. but when i
play low spec games like roblox it kicks in with 800 ms and starts lagging
the voice. i can relive my avatar anime on game on roblox because of rvc.
it really helped me a lot to gain not much of followers. im not so proud of
my voice because its rough and manly. sometimes when i talk i get told im a
guy hahahahah but i dont mind. its just being an anime character you wanted
so much is like living my own fantasy. thank you for helping me out tho.
its just too bad i have the same result

**Comment by w-okada** [comment]
check cpu/gpu usage at performance monitor.

**Comment by w-okada** [comment]
no res close
