### ISSUE TITLE
fully uninstall, can't starrt because clicked on startHttps instead of .app

### ISSUE THREAD

**Issue by shirowayfy** [w-okada/voice-changer#831]
### Issue Type

Question

### vc client version number

MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.13

### OS

mac

### GPU

arm

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

MMVC

### Model type

ONNX

### logs on terminal

“MMVCServerSIO” can’t be opened because (null) is not allowed to open documents in Terminal.

**Comment by w-okada** [comment]
please describe issue more clearly.
