### ISSUE TITLE
model_dir' does not exist

### ISSUE THREAD

**Issue by danya-scam** [w-okada/voice-changer#833]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.13

### OS

mac

### GPU

mq

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

The GUI successfully launched.

### read tutorial

yes

### Extract files to a new folder.

yes

### Voice Changer type

roc

### Model type

f0

### Situation

[Voice Changer] Web Server Launch Exception, Directory '/private/var/folders/2h/jhpwt9yj7vd_zm0mxbsfhrd00000gn/T/AppTranslocation/6E808D72-B0DD-4D44-BE35-86FBDDC893E4/d/model_dir' does not exist

### application window capture

<img width="1440" alt="Снимок экрана 2023-09-12 в 19 27 19" src="https://github.com/w-okada/voice-changer/assets/144829369/54ea0885-13a1-446b-98fd-1755b332e15e">

### logs on terminal

mac model_dir: /private/var/folders/2h/jhpwt9yj7vd_zm0mxbsfhrd00000gn/T/AppTranslocation/6E808D72-B0DD-4D44-BE35-86FBDDC893E4/d/model_dir
[Voice Changer] Web Server Launch Exception, Directory '/private/var/folders/2h/jhpwt9yj7vd_zm0mxbsfhrd00000gn/T/AppTranslocation/6E808D72-B0DD-4D44-BE35-86FBDDC893E4/d/model_dir' does not exist
[VCClient] wait web server...10 http://127.0.0.1:18888/

**Comment by lwigga** [comment]
use .command files to run

**Comment by w-okada** [comment]
no res close
