### ISSUE TITLE
Init provider bridge failed

### ISSUE THREAD

**Issue by SunnexGB** [w-okada/voice-changer#834]
### Issue Type

Bug Report

### vc client version number

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13.zip

### OS

Windows 11 Pro ver.21H2

### GPU

Palit GeForce GTX 1050 Ti StormX 4GB

### Clear setting

yes

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

yes

### Extract files to a new folder.

no

### Voice Changer type

idk

### Model type

 pyTorch

### Situation
Having unpacked all the contents I decided to check the performance of the application I ran the "bat" file later I installed all the necessary components via cmd through the open "bat" well and finally launched the client itself it worked, but I decided to leave it for later I looked at the tutorials on configuration and making my own notes wanted to configure the client, but at the second launch I got an error associated with a certain library all the problems I clearly described below.

### logs on terminal

So to begin with, when I run the "bat" file I get a command line (as everyone who has run it naturally) after which I get the error " 2023-09-12 23:37:00.0943160 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1641 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.". then I skip downloading samples and open the client window and then I have an infinite connection to the server or the following error "[VCClient] Access http://localhost:18888/".
[8992:0912/233835.968:ERROR:network_service_instance_impl.cc(521)] Network service crashed, restarting service.
(node:8992) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:18888
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
(Use `voice-changer-native-client --trace-warnings ...` to show where the warning was created)
(node:8992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) ".I understand that this error is caused by some bibliothec but I have no idea how to solve this problem
![photo_2023-09-12_23-44-08](https://github.com/w-okada/voice-changer/assets/144198043/a3b4e699-77c3-4b71-b4ed-955e6aa7493e)
P.S the first run of the application was successful but after the second run these problems occurred (at the same time I did not configure the application and did not even try it out just started the application and closed it)

**Comment by w-okada** [comment]
It might be because the folder name is using unicode.

see.
https://github.com/microsoft/onnxruntime/issues/13499

**Comment by w-okada** [comment]
no res close
