### ISSUE TITLE
Newer pyworld version (currently 0.3.4) is needed to build wheels on Google Colab

### ISSUE THREAD

**Issue by D0656146** [w-okada/voice-changer#835]
### Issue Type

Bug Report

### vc client version number

N/A

### OS

Google Colab

### GPU

Tesla T4

### Clear setting

no

### Sample model

no

### Input chunk num

no

### Wait for a while

no

### read tutorial

no

### Extract files to a new folder.

no

### Voice Changer type

N/A

### Model type

N/A

### logs on terminal

What the title says.
Use pyworld>=0.3.3 instead of pyworld==0.3.4 to solve it once and for all.

**Comment by Rafacasari** [comment]
Some have updated the colab files, can you try again and test if the issue persists?

**Comment by D0656146** [comment]
It's working well!

**Comment by w-okada** [comment]
resolved close
