### ISSUE TITLE
[ISSUE]: 'MMVCServerSIO.exe' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Divail** [w-okada/voice-changer#838]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13.zip

### Operational System

Windows 10

### GPU

3070

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

MMVC

### Issue Description

whenever i try to run start_http nothing happens, if i run it from CMD it says " 'MMVCServerSIO.exe' is not recognized as an internal or external command, operable program or batch file." 

### Application Screenshot

![image](https://github.com/w-okada/voice-changer/assets/48029316/e8ce2a21-aeca-4852-bafe-f30a331a2c68)

### Logs on console

C:\Users\Dima\Desktop\MMVCServerSIO>start_http.bat

C:\Users\Dima\Desktop\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
'MMVCServerSIO.exe' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Rafacasari** [comment]
Double clicking the .bat file didn't work?

**Comment by Divail** [comment]
> Double clicking the .bat file didn't work?

No, it launchs something and closes it immediately

**Comment by Rafacasari** [comment]
Try editing the batch file and putting a **pause** at the end (in a new link)

**Comment by w-okada** [comment]
How about execute dir command at C:\Users\Dima\Desktop\MMVCServerSIO?
Is there MMVCServerSIO.exe?

If there is MMVCServerSIO.exe, try execute MMVCServerSIO.exe.

**Comment by w-okada** [comment]
no res close
