### ISSUE TITLE
[ISSUE]: Stuck on MMVC_SocketIOApp initializing... done.

### ISSUE THREAD

**Issue by DaUnknow1** [w-okada/voice-changer#840]
### Voice Changer Version

v.1.5.3.13

### Operational System

Colab/Kaggle

### GPU

P100

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [x] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RCV

### Issue Description

It is stuck on [Voice Changer] MMVC_SocketIOApp initializing... done.

### Logs on console

/kaggle/working/voice-changer/server/MMVCServerSIO.py:3: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.util import strtobool
<frozen importlib._bootstrap>:241: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
    Booting PHASE :__main__
    PYTHON:3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- -- 
    Please open the following URL in your browser.
    [http://<IP>:<PORT>/](http://%3Cip%3E:<PORT>/%3C/span%3E)
    In many cases, it will launch when you access any of the following URLs.
    [http://127.0.0.1:18888/](http://127.0.0.1:18888/%3C/span%3E)
<frozen importlib._bootstrap>:241: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
    Booting PHASE :__mp_main__
    The server process is starting up.
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] model slot is changed -1 -> 16
................RVC
[Voice Changer] [RVCr2] Creating instance 
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing... 
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec Not implemented
[Voice Changer] Loading index...
Try loading... model_dir/16/added_IVF337_Flat_nprobe_1_v2.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x79aa997c1270>
GENERATE EMBEDDER<voice_changer.RVC.embedder.FairseqHubert.FairseqHubert object at 0x79aa9981bb80>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x79aa9981bd00>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings f0Detector:crepe_tiny
[Voice Changer][RVC]: update_settings serverReadChunkSize:128
[Voice Changer][RVC]: update_settings extraConvertSize:16384
[Voice Changer][RVC]: update_settings silentThreshold:0.00053
[Voice Changer][RVC]: update_settings modelSlotIndex:1694336325016
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.

**Comment by Rafacasari** [comment]
Try adding `!pip install fairseq` on the first cell. For some reason fairseq was removed from the [requirements.txt](https://github.com/w-okada/voice-changer/blob/master/server/requirements.txt)

It will be fixed soon, for now use the manual command that I've said

**Comment by DaUnknow1** [comment]
It was already placed into the code

**Comment by DaUnknow1** [comment]
It is my first time opening a issue so srry

**Comment by Rafacasari** [comment]
Is it fixed? Please close the issue if you have no more issue

**Comment by DaUnknow1** [comment]
It is not fixed. I just didn't know how to comment

**Comment by Rafacasari** [comment]
Try using this version: 
https://colab.research.google.com/gist/Rafacasari/8775c6065e1290e6e20e80a6ed96d575/voice-changer-dev-2.ipynb

**Comment by DaUnknow1** [comment]
It is working now thank you
