### ISSUE TITLE
[ISSUE]: Experiencing Import Errors while Running Okada RVC on Kaggle

### ISSUE THREAD

**Issue by bennett-krubakar** [w-okada/voice-changer#841]
### Voice Changer Version

Not sure

### Operational System

Kaggle

### GPU

T4

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

**Description of the Issue:**
I am currently trying to run the Okada RVC (Real-time Voice Cloning) project on Kaggle, but I have encountered import errors that are preventing the project from running successfully.

**Error Messages:**
I received the following error messages while attempting to run the project:

1. `ModuleNotFoundError: No module named 'pyworld'`
2. `ImportError: cannot import name 'RVCr2' from 'voice_changer.RVC.RVCr2' (/kaggle/working/voice-changer/server/voice_changer/RVC/RVCr2.py)`

**Request for Assistance:**
I am seeking assistance in resolving these import errors and ensuring that the Okada RVC project can run smoothly on Kaggle. Any guidance or solutions would be greatly appreciated.

**Submission:**
I kindly request assistance in resolving the import errors I've encountered while running the Okada RVC project on Kaggle. Your help in finding a solution to these issues would be highly valuable. Thank you in advance.

### Logs on console

[Voice Changer] post_update_settings ex: No module named 'pyworld'
[Voice Changer] post_update_settings ex: cannot import name 'RVCr2' from 'voice_changer.RVC.RVCr2' (/kaggle/working/voice-changer/server/voice_changer/RVC/RVCr2.py)
Traceback (most recent call last):
  File "/kaggle/working/voice-changer/server/restapi/MMVC_Rest_Fileuploader.py", line 71, in post_update_settings
    info = self.voiceChangerManager.update_settings(key, val)
  File "/kaggle/working/voice-changer/server/voice_changer/VoiceChangerManager.py", line 311, in update_settings
    self.generateVoiceChanger(newVal)
  File "/kaggle/working/voice-changer/server/voice_changer/VoiceChangerManager.py", line 243, in generateVoiceChanger
    from voice_changer.RVC.RVCr2 import RVCr2
ImportError: cannot import name 'RVCr2' from 'voice_changer.RVC.RVCr2' (/kaggle/working/voice-changer/server/voice_changer/RVC/RVCr2.py)
Traceback (most recent call last):
  File "/kaggle/working/voice-changer/server/restapi/MMVC_Rest_Fileuploader.py", line 71, in post_update_settings
    info = self.voiceChangerManager.update_settings(key, val)
  File "/kaggle/working/voice-changer/server/voice_changer/VoiceChangerManager.py", line 311, in update_settings
    self.generateVoiceChanger(newVal)
  File "/kaggle/working/voice-changer/server/voice_changer/VoiceChangerManager.py", line 243, in generateVoiceChanger
    from voice_changer.RVC.RVCr2 import RVCr2
  File "/kaggle/working/voice-changer/server/voice_changer/RVC/RVCr2.py", line 15, in <module>
    from voice_changer.RVC.pitchExtractor.PitchExtractorManager import PitchExtractorManager
  File "/kaggle/working/voice-changer/server/voice_changer/RVC/pitchExtractor/PitchExtractorManager.py", line 4, in <module>
    from voice_changer.RVC.pitchExtractor.DioPitchExtractor import DioPitchExtractor
  File "/kaggle/working/voice-changer/server/voice_changer/RVC/pitchExtractor/DioPitchExtractor.py", line 1, in <module>
    import pyworld
ModuleNotFoundError: No module named 'pyworld'

**Comment by InsanEagle** [comment]
You can try adding pyworld manually adding `!pip install pyworld` in dependencies cell. 

![pyworld](https://github.com/w-okada/voice-changer/assets/67074517/ad7e1616-7ea6-4712-a521-57c943e16110)

**Comment by bennett-krubakar** [comment]
@InsanEagle That worked. Thanks for helping at a short notice. I'm closing the issue now.

**Comment by RakeshChowdhury** [comment]
@bennett-krubakar can you share the link to your kaggle? would be awesome

**Comment by razzytest61** [comment]
https://www.kaggle.com/code/razzytest/public-w-okada-voice-changer

100 working voice changers

**Comment by razzytest61** [comment]
> @bennett-krubakar can you share the link to your kaggle? would be awesome

https://www.kaggle.com/code/razzytest/public-w-okada-voice-changer

**Comment by razzytest61** [comment]
> You can try adding pyworld manually adding `!pip install pyworld` in dependencies cell.
> 
> ![pyworld](https://private-user-images.githubusercontent.com/67074517/267784602-ad7e1616-7ea6-4712-a521-57c943e16110.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDA1NTEsIm5iZiI6MTcyMDYwMDI1MSwicGF0aCI6Ii82NzA3NDUxNy8yNjc3ODQ2MDItYWQ3ZTE2MTYtN2VhNi00NzEyLWE1MjEtNTdjOTQzZTE2MTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA4MzA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkYTA5NTk0ZWFlZmIxOWRkNTViODM5M2YzYzFjYTAzMzc1NzVkYjdkOGRlNzJiMzFmODIwM2JhYTMyNzMzOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VIve3yt8sdYCcXeV6V9a9C2khI-XgnLAOKgUCW4I7Oo)
https://www.kaggle.com/code/razzytest/public-w-okada-voice-changer
