### ISSUE TITLE
[ISSUE]: PROBLEM WHEN DELETING THE PROGRAM

### ISSUE THREAD

**Issue by Rodrir13** [w-okada/voice-changer#845]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13.zip

### Operational System

Windows 10

### GPU

none

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [ ] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

The program itself apparently did not have any kind of uninstall option, so I looked at some post and according to the creator, at first deleting the original folder of the program itself would already be done, but when it came time to turn on the computer once I deleted that folder, it still starts 5 cmd windows quickly and they put the memory at 50%. Any explanation or because of the program do I have to format?

### Logs on console

When the consoles start up, they do not show text and only appear for a micro second.

**Comment by Rodrir13** [comment]
Console Window Host appears, if I knew the name of the service it runs I could search for it, but the fact is that I don't even have time to see it, this started after starting the http option, I entered the program, I deleted it because something strange was working for me and I I deleted it almost immediately, restarted the PC after a while and that Windows CMD spam started. I have no idea if it's the program's fault, but the fact that it installs with the computer's CMD and every time I turn on the computer after downloading it, several CMD tabs appear, launching and bloating memory..

**Comment by w-okada** [comment]
I'm sorry, I don't quite understand. 
This software is used by many people, but we haven't received such feedback from other users. We suspect the issue may be specific to @Rodrir13's environment.

Did you install any other software? Perhaps another Voice Changer software or something like that. I've seen some Voice Changer software behave in various ways.

**Comment by w-okada** [comment]
no res close
