### ISSUE TITLE
[ISSUE]: White Window

### ISSUE THREAD

**Issue by Dikeydevil** [w-okada/voice-changer#846]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13.zip

### Operational System

WIN 11

### GPU

3070ti

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

MMVC

### Issue Description

White window, how to solve this problem?

### Application Screenshot

![chrome_BppgPanZUJ](https://github.com/w-okada/voice-changer/assets/60939588/f67eedc4-d6d9-4472-bcda-d8f87f0b5cd8)

### Logs on console

I dont have a log

**Comment by w-okada** [comment]
Are there any log on console?

**Comment by w-okada** [comment]
no res close
