### ISSUE TITLE
[ISSUE]: Real Time Delay

### ISSUE THREAD

**Issue by ItKazoo** [w-okada/voice-changer#849]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.12a.zip

### Operational System

Windows 10

### GPU

Nvidia GTX 1660 (6GB)

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

I was wondering on how some people were able to have no real time delay when using the software. However, whenever I talk in mine, there is a delay for like 20 ms/30 ms delay, so I been wondering on how do I get the voice changer to match my mouth when I'm talking

### Logs on console

The console is completely fine, I don't see any issues in it, it's just the delay that I wanna get rid of

**Comment by w-okada** [comment]
The technology to process without any delay is not yet realized in this software. A delay of about 20 milliseconds/30 milliseconds is quite close to real-time, I believe.

**Comment by ItKazoo** [comment]
You think you could try to get it to have no delay in a update?
