### ISSUE TITLE
[ISSUE]: MMVCServer does not start

### ISSUE THREAD

**Issue by XtraviVolume** [w-okada/voice-changer#850]
### Voice Changer Version

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.11.zip

### Operational System

Windows 11

### GPU

no

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [ ] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Application Screenshot

![image](https://github.com/w-okada/voice-changer/assets/98639497/aaeca699-1846-4b9a-b6a5-4f479ced7c39)

### Logs on console

Booting PHONE
: ＿main＿
PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr 5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Voice Changer&2 LTl.
Traceback (most recent call last):
File "MMVCServerSIO.py", line 138, in <module>
File "downloader\WeightDownloader.py", line 27, in download Weight
File "genericpath.py", line 19, in exists
TypeError: stat: path should be string, bytes, os.Path Like or integer, not NoneType
[процесс завершил работу с кодом 1 (0х00000001)]
Теперь вы можете закрыть этот терминал с помощью клавиш CTRL+D. Или нажмите клавишу ВВОД для перезапуска.

**Comment by w-okada** [comment]
read tutorial
