### ISSUE TITLE
[ISSUE]: Pipeline is not initialized. & Waiting generate pipeline...

### ISSUE THREAD

**Issue by otu30t** [w-okada/voice-changer#851]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13

### Operational System

Windows 10

### GPU

RTX 3060

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

Any

### Issue Description

[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
it keeps going like that when i start, and when i stop it stops

### Logs on console

C:\Users\Roma\Desktop\Инструменты\AI\VoiceChanger>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
2023-09-16 03:21:47.1416149 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1641 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
2023-09-16 03:21:52.8397154 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1641 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] model slot is changed -1 -> 0
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
2023-09-16 03:21:55.9612924 [E:onnxruntime:Default, provider_bridge_ort.cc:1266 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1018 onnxruntime::ProviderSharedLibrary::Ensure [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\Roma\Desktop\¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤ \AI\VoiceChanger\onnxruntime\capi\onnxruntime_providers_shared.dll"

2023-09-16 03:21:55.9759776 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:578 onnxruntime::python::CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cuda:0
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 30, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
[Voice Changer] pipeline create failed. check your model is valid.
[Voice Changer][RVC]: update_settings serverReadChunkSize:384
[Voice Changer][RVC]: update_settings modelSlotIndex:1694812847000
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2023-09-16 03:22:01] connet sid : ulJKzqOc2xc7IsscAAAB
[2023-09-16 03:22:01] connet sid : 2F9F3WEXkkR6IGkmAAAD
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...
[Voice Changer] Pipeline is not initialized.
[Voice Changer] Waiting generate pipeline...

**Comment by w-okada** [comment]
same

https://github.com/w-okada/voice-changer/issues/462
https://github.com/w-okada/voice-changer/issues/488

or

https://github.com/w-okada/voice-changer/issues/528

**Comment by danidany** [comment]
this litearlly doesnt help me man ive extracted and everything pleased help

**Comment by TokyoSummerDays** [comment]
same problem here...plz help

**Comment by Kokomi-sangonomiyaa** [comment]
I fixed it by using a vpn (dns but i don't think is different for this). If you connected at least once with the extracted folder, then you have to extract to a fresh folder again, then turn on vpn and run start_http.bat, if it started downloading 52 MB files and 1 372MB file or something like that then you are failed probably. if it started downloading many 372MB files then you are doing great. many many other files download after that. at least that was my case. this is photo of successful connect (not a bad connect.) 
![aaaaa](https://github.com/w-okada/voice-changer/assets/153341810/7a7e1bb1-5d74-4e4b-b500-5bd1746c73ab)

**Comment by SuperName228** [comment]
this litearlly doesnt help me

**Comment by devil-mo** [comment]
Is there any solution??

**Comment by YMLeeo** [comment]
![Screenshot 2024-06-27 151136](https://github.com/w-okada/voice-changer/assets/89425386/dd20a2c2-d160-43dc-b06f-c294a0331a36)

Am I a success or a failure? I have re-unzipped it for the third time.

**Comment by KuukoShan** [comment]
> ![Screenshot 2024-06-27 151136](https://private-user-images.githubusercontent.com/89425386/343668377-dd20a2c2-d160-43dc-b06f-c294a0331a36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODMxMzYsIm5iZiI6MTcxOTQ4MjgzNiwicGF0aCI6Ii84OTQyNTM4Ni8zNDM2NjgzNzctZGQyMGEyYzItZDE2MC00M2RjLWIwNmYtYzI5NGEwMzMxYTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEwMDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5MDQ4MmM5OWM3MDQzMjU2NDdmZjhiOThlYjdkYzIyMjQyM2ZhY2Y1ZjA3MDE4OWFhYjk5MzJhNjJmNjQ4MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LeeFM5niRImB9nCPXEkPEtF7wu1BE6YZbUL8wh2CpZs)
> 
> Am I a success or a failure? I have re-unzipped it for the third time.

Well, it's downloading the necessary files. Wait until it download everything. Check that it shows that the files downloaded successfully without errors. This only is done once but it shouldn't be interrupted or you will need to start over with a clean installation (new unzipped file on a clean folder). If your internet connection isn't too fast, it may take a while but it doesn't means that the software stuck. Be patient and let's see if it works fine after everything finish downloading and the UI loads.

**Comment by josepephph** [comment]
b
