### ISSUE TITLE
[ISSUE]: 

### ISSUE THREAD

**Issue by coolshaeds** [w-okada/voice-changer#854]
### Voice Changer Version

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.11

### Operational System

Windows 10 pro

### GPU

NVIDIA GeForce RTX 3060

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

before the updates i was able to use the voice changer on around 80 - 94 chunks with minimun delay, but now when i try and use those chunks i get up to 4k - 40k ms delay? i 've tried reinstalling and refreshing the settings and it keeps doing this

### Application Screenshot

![help](https://github.com/w-okada/voice-changer/assets/132325197/7786172a-607e-49e7-85de-d8027b1f5e07)

### Logs on console

C:\Users\Ethan\Downloads\MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.12a\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] model slot is changed -1 -> 5
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:CPU-DML)
[Voice Changer][RVC]: update_settings gpu:1
[Voice Changer][RVCr2] Initializing...
[Voice Changer] device detection error, fallback to cpu
Invalid device id
[Voice Changer] device detection error, fallback to cpu
Invalid device id
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
Try loading... model_dir\5\added_IVF904_Flat_nprobe_1_ShirakamiFubuki_v2.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x0000028AB4A33520>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000028AC1FB8310>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x0000028AC1FB8340>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings extraConvertSize:131072
[Voice Changer][RVC]: update_settings f0Detector:dio
[Voice Changer][RVC]: update_settings serverReadChunkSize:96
[Voice Changer][RVC]: update_settings modelSlotIndex:1694820269005
[VCClient] wait web server... done 200
[2023-09-15 16:27:00] connet sid : H5kLE7VHQCwA1d5cAAAC
[2023-09-15 16:27:00] connet sid : RkbwfCL3oU7uictmAAAD
[Voice Changer] update configuration: tran 2
[Voice Changer][RVC]: update_settings tran:2
[Voice Changer] update configuration: tran 3
[Voice Changer][RVC]: update_settings tran:3
[Voice Changer] update configuration: tran 4
[Voice Changer][RVC]: update_settings tran:4
[Voice Changer] update configuration: tran 5
[Voice Changer][RVC]: update_settings tran:5
[Voice Changer] update configuration: tran 5
[Voice Changer][RVC]: update_settings tran:5
[Voice Changer] update configuration: tran 7
[Voice Changer][RVC]: update_settings tran:7
[Voice Changer] update configuration: tran 14
[Voice Changer] update configuration: tran 14
[Voice Changer][RVC]: update_settings tran:14
[Voice Changer][RVC]: update_settings tran:14
[Voice Changer] update configuration: tran 15
[Voice Changer][RVC]: update_settings tran:15
[Voice Changer] update configuration: tran 16
[Voice Changer][RVC]: update_settings tran:16
[Voice Changer] update configuration: tran 17
[Voice Changer][RVC]: update_settings tran:17
[Voice Changer] update configuration: tran 16
[Voice Changer][RVC]: update_settings tran:16
[Voice Changer] update configuration: tran 16
[Voice Changer][RVC]: update_settings tran:16
[Voice Changer] update configuration: tran 15
[Voice Changer][RVC]: update_settings tran:15
[Voice Changer] update configuration: tran 14
[Voice Changer][RVC]: update_settings tran:14
[Voice Changer] update configuration: tran 14
[Voice Changer][RVC]: update_settings tran:14
[Voice Changer] update configuration: tran 15
[Voice Changer][RVC]: update_settings tran:15
[Voice Changer] update configuration: tran 16
[Voice Changer][RVC]: update_settings tran:16
[Voice Changer] update configuration: tran 16
[Voice Changer][RVC]: update_settings tran:16
[Voice Changer] update configuration: tran 17
[Voice Changer][RVC]: update_settings tran:17
[Voice Changer] UPDATE MODEL INFO, {"key": "defaultTune", "val": 17, "slot": 5}
SlotInfo::: RVCModelSlot(slotIndex=5, voiceChangerType='RVC', name='ShirakamiFubuki_e300_s11700', description='', credit='', termsOfUseUrl='', iconFile='', speakers={'0': 'target'}, modelFile='ShirakamiFubuki_e300_s11700.pth', indexFile='added_IVF904_Flat_nprobe_1_ShirakamiFubuki_v2.index', defaultTune=17, defaultIndexRatio=0, defaultProtect=0.5, isONNX=False, modelType='pyTorchRVCv2', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='')
[Voice Changer] UPDATE MODEL INFO, {"key": "defaultIndexRatio", "val": 0, "slot": 5}
SlotInfo::: RVCModelSlot(slotIndex=5, voiceChangerType='RVC', name='ShirakamiFubuki_e300_s11700', description='', credit='', termsOfUseUrl='', iconFile='', speakers={'0': 'target'}, modelFile='ShirakamiFubuki_e300_s11700.pth', indexFile='added_IVF904_Flat_nprobe_1_ShirakamiFubuki_v2.index', defaultTune=17, defaultIndexRatio=0, defaultProtect=0.5, isONNX=False, modelType='pyTorchRVCv2', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='')
[Voice Changer] UPDATE MODEL INFO, {"key": "defaultProtect", "val": 0.5, "slot": 5}
SlotInfo::: RVCModelSlot(slotIndex=5, voiceChangerType='RVC', name='ShirakamiFubuki_e300_s11700', description='', credit='', termsOfUseUrl='', iconFile='', speakers={'0': 'target'}, modelFile='ShirakamiFubuki_e300_s11700.pth', indexFile='added_IVF904_Flat_nprobe_1_ShirakamiFubuki_v2.index', defaultTune=17, defaultIndexRatio=0, defaultProtect=0.5, isONNX=False, modelType='pyTorchRVCv2', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='')
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] warming up... generating sola buffer.
[2023-09-15 16:27:49] connet sid : UCrZiNTI9QhPgNjIAAAF
[Voice Changer] update configuration: gpu 2
[Voice Changer][RVC]: update_settings gpu:2
[Voice Changer][RVCr2] Initializing...
[Voice Changer] device detection error, fallback to cpu
Invalid device id
[Voice Changer] device detection error, fallback to cpu
Invalid device id
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\5\added_IVF904_Flat_nprobe_1_ShirakamiFubuki_v2.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x0000028A944942E0>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000028ABAB63CD0>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.DioPitchExtractor.DioPitchExtractor object at 0x0000028ABAB62EC0>
[Voice Changer] [RVC] Initializing... done
Pipeline has been deleted
[Voice Changer] update configuration: gpu 3
[Voice Changer][RVC]: update_settings gpu:3
[Voice Changer][RVCr2] Initializing...
[Voice Changer] device detection error, fallback to cpu
Invalid device id
[Voice Changer] device detection error, fallback to cpu
Invalid device id
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\5\added_IVF904_Flat_nprobe_1_ShirakamiFubuki_v2.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x0000028AB4B0C9D0>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000028AB4ACD450>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.DioPitchExtractor.DioPitchExtractor object at 0x0000028AB4ACD1B0>
[Voice Changer] [RVC] Initializing... done
Pipeline has been deleted
[Voice Changer] update configuration: gpu 0
[2023-09-15 16:28:32] connet sid : 5JhfGtfdWzowm-moAAAH
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
2023-09-15 16:28:38.7424601 [W:onnxruntime:, session_state.cc:1169 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-09-15 16:28:38.7547524 [W:onnxruntime:, session_state.cc:1171 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] Loading index...
Try loading... model_dir\5\added_IVF904_Flat_nprobe_1_ShirakamiFubuki_v2.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x0000028ABAACFC10>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000028ABAB40A30>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.DioPitchExtractor.DioPitchExtractor object at 0x0000028ABAC27310>
[Voice Changer] [RVC] Initializing... done
Pipeline has been deleted
[Voice Changer] update configuration: gpu 1
[Voice Changer][RVC]: update_settings gpu:1
[Voice Changer][RVCr2] Initializing...
[Voice Changer] device detection error, fallback to cpu
Invalid device id
[Voice Changer] device detection error, fallback to cpu
Invalid device id
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\5\added_IVF904_Flat_nprobe_1_ShirakamiFubuki_v2.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x0000028AD5909AB0>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000028AB5DADD80>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.DioPitchExtractor.DioPitchExtractor object at 0x0000028AB5DAFA00>
[Voice Changer] [RVC] Initializing... done
Pipeline has been deleted
[Voice Changer] update configuration: gpu -1
[Voice Changer][RVC]: update_settings gpu:-1
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\5\added_IVF904_Flat_nprobe_1_ShirakamiFubuki_v2.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x0000028A944942E0>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000028ABAB0E0E0>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.DioPitchExtractor.DioPitchExtractor object at 0x0000028ABAB0DFF0>
[Voice Changer] [RVC] Initializing... done
Pipeline has been deleted
[Voice Changer] update configuration: gpu 0
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
2023-09-15 16:29:20.2255286 [W:onnxruntime:, session_state.cc:1169 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-09-15 16:29:20.2380471 [W:onnxruntime:, session_state.cc:1171 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] Loading index...
Try loading... model_dir\5\added_IVF904_Flat_nprobe_1_ShirakamiFubuki_v2.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x0000028AB4AB5750>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000028ABAA43A30>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.DioPitchExtractor.DioPitchExtractor object at 0x0000028ABAA407F0>
[2023-09-15 16:29:20] connet sid : LnTc3Tvn35DTnk3uAAAJ
Pipeline has been deleted
[Voice Changer] [RVC] Initializing... done
[Voice Changer] update configuration: tran 1
[Voice Changer][RVC]: update_settings tran:1
[Voice Changer] update configuration: tran 2
[Voice Changer][RVC]: update_settings tran:2
[Voice Changer] update configuration: tran 3
[Voice Changer] update configuration: tran 4
[Voice Changer][RVC]: update_settings tran:3
[Voice Changer][RVC]: update_settings tran:4
[Voice Changer] update configuration: tran 5
[Voice Changer][RVC]: update_settings tran:5
[Voice Changer] update configuration: tran 5
[Voice Changer][RVC]: update_settings tran:5
[Voice Changer] update configuration: tran 5
[Voice Changer] update configuration: tran 7
[Voice Changer][RVC]: update_settings tran:5
[Voice Changer] update configuration: tran 9
[Voice Changer][RVC]: update_settings tran:7
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: tran 7
[Voice Changer] update configuration: tran 7
[Voice Changer][RVC]: update_settings tran:7
[Voice Changer][RVC]: update_settings tran:9
[Voice Changer][RVC]: update_settings tran:8
[Voice Changer][RVC]: update_settings tran:7
[Voice Changer] update configuration: tran 9
[Voice Changer] update configuration: tran 11
[Voice Changer][RVC]: update_settings tran:9
[Voice Changer] update configuration: tran 12
[Voice Changer] update configuration: tran 10
[Voice Changer][RVC]: update_settings tran:12
[Voice Changer] update configuration: tran 14
[Voice Changer][RVC]: update_settings tran:11
[Voice Changer][RVC]: update_settings tran:10
[Voice Changer] update configuration: tran 12
[Voice Changer][RVC]: update_settings tran:12
[Voice Changer][RVC]: update_settings tran:14
[Voice Changer] update configuration: tran 14
[Voice Changer] update configuration: tran 16
[Voice Changer] update configuration: tran 18
[Voice Changer][RVC]: update_settings tran:16
[Voice Changer] update configuration: tran 15
[Voice Changer][RVC]: update_settings tran:14
[Voice Changer] update configuration: tran 18
[Voice Changer][RVC]: update_settings tran:18
[Voice Changer] update configuration: tran 17
[Voice Changer][RVC]: update_settings tran:18
[Voice Changer][RVC]: update_settings tran:17
[Voice Changer][RVC]: update_settings tran:15
[Voice Changer] update configuration: tran 18
[Voice Changer] update configuration: tran 18
[Voice Changer] update configuration: tran 18
[Voice Changer][RVC]: update_settings tran:18
[Voice Changer][RVC]: update_settings tran:18
[Voice Changer][RVC]: update_settings tran:18
[Voice Changer] update configuration: tran 17
[Voice Changer] update configuration: tran 17
[Voice Changer] update configuration: tran 17
[Voice Changer][RVC]: update_settings tran:17
[Voice Changer] update configuration: tran 17
[Voice Changer][RVC]: update_settings tran:17
[Voice Changer][RVC]: update_settings tran:17
[Voice Changer][RVC]: update_settings tran:17
[Voice Changer] update configuration: tran 17
[Voice Changer] update configuration: tran 16
[Voice Changer][RVC]: update_settings tran:17
[Voice Changer][RVC]: update_settings tran:16
[Voice Changer] update configuration: tran 16
[Voice Changer] update configuration: tran 15
[Voice Changer][RVC]: update_settings tran:16
[Voice Changer][RVC]: update_settings tran:15
[Voice Changer] update configuration: tran 16
[Voice Changer] update configuration: tran 17
[Voice Changer] update configuration: tran 18
[Voice Changer] update configuration: tran 17
[Voice Changer][RVC]: update_settings tran:16
[Voice Changer][RVC]: update_settings tran:17
[Voice Changer][RVC]: update_settings tran:18
[Voice Changer][RVC]: update_settings tran:17
[Voice Changer] update configuration: tran 18
[Voice Changer][RVC]: update_settings tran:18
[Voice Changer] update configuration: tran 19
[Voice Changer][RVC]: update_settings tran:19
[Voice Changer] update configuration: tran 17
[Voice Changer] update configuration: tran 17
[Voice Changer][RVC]: update_settings tran:17
[Voice Changer][RVC]: update_settings tran:17
[Voice Changer] update configuration: tran 17
[Voice Changer] update configuration: tran 17
[Voice Changer][RVC]: update_settings tran:17
[Voice Changer][RVC]: update_settings tran:17
[Voice Changer] update configuration: serverReadChunkSize 32
[Voice Changer][RVC]: update_settings serverReadChunkSize:32
[Voice Changer] update configuration: serverReadChunkSize 2048
[Voice Changer][RVC]: update_settings serverReadChunkSize:2048
[2023-09-15 16:31:01] connet sid : pKPfQYm3sAhxLry3AAAL
[Voice Changer] update configuration: serverReadChunkSize 96
[Voice Changer][RVC]: update_settings serverReadChunkSize:96
[2023-09-15 16:33:43] connet sid : YWWTaw5al-oI95BgAAAN
[2023-09-15 16:34:54] connet sid : -TLkHKY2xaf9oyg7AAAP
[2023-09-15 16:36:05] connet sid : wsjC3-nQ1C5vkwHdAAAR
[2023-09-15 16:37:35] connet sid : UK6UVKee-0Dss10FAAAT
[2023-09-15 16:39:05] connet sid : LRC9icUikHzTLK8UAAAV
[2023-09-15 16:40:36] connet sid : _kESNLqhxNeg4MWSAAAX
[2023-09-15 16:42:07] connet sid : L4L2_qNPrYuduscVAAAZ
[2023-09-15 16:43:19] connet sid : f2egradYJXuw2troAAAb

**Comment by Rafacasari** [comment]
You're using the wrong version. Download the gpu_cuda version. DirectML is for AMD.
https://huggingface.co/wok000/vcclient000/blob/main/MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13.zip
After you downloaded it, select your gpu and use rmvpe in f0 det.

**Comment by w-okada** [comment]
@coolshaeds 
If resolved, close this issue
