### ISSUE TITLE
[ISSUE]: Not even opening when i click start_http.bat

### ISSUE THREAD

**Issue by antipsychoticc** [w-okada/voice-changer#864]
### Voice Changer Version

v.1.5.3.13

### Operational System

windows 11

### GPU

rtx 3050

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

idk what that is rvc i think

### Issue Description

So i downloaded it and did everything right and extracted it to a different folder after making sure i downloaded the right thing and i click start_http and a window opens for a split second and closes and i can click it as much as i want but the same window just opens and closes in a split second

### Application Screenshot

none

### Logs on console

none

**Comment by Rafacasari** [comment]
Add a `pause` at the end of the start_http.bat file, this should keep the console open and you'll be able to see what is the error.

Make sure that you have downloaded **onnxgpu_cuda.zip** version.

**Comment by antipsychoticc** [comment]
it says this
![image](https://github.com/w-okada/voice-changer/assets/114691100/edb857f0-fe7a-4fdc-82b7-070c4baf16ab)

**Comment by w-okada** [comment]
Run the start_http.bat file in the folder where you extracted the files.

**Comment by antipsychoticc** [comment]
didnt worj

**Comment by antipsychoticc** [comment]
didnt work

**Comment by w-okada** [comment]
ummm, I have no idea.

**Comment by antipsychoticc** [comment]
finally installed it but when i use it i hear my actual voice and then i hear the ai voice because im trying to use it to troll my friends i test it on discord and it shows my voice playing before the ai

**Comment by w-okada** [comment]
So, you solved the launch problem. close this issue
