### ISSUE TITLE
[ISSUE]: I am unable to launch the http server via start_http.bat or start_https.bat.

### ISSUE THREAD

**Issue by eyehack84** [w-okada/voice-changer#869]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13.zip

### Operational System

Windows 10

### GPU

RTX 3070 TI

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

N/A

### Issue Description

I am unable to launch the http server via start_http.bat or start_https.bat. 

I have attempted the following:
- Added pause to start_http.bat
- Attempted to run via CMD started inside the folder.
- Attempted to run via PowerShell started inside the folder.
- Reinstalled Python, Pytorch, Updated CUDA, Updated NVIDIA Drivers
- Attempted launch from C:/.../Desktop/MMVCServerSIO, C:/.../Downloads/MMVCServerSIO, and C:/MMVCServerSIO
- - I have added an exception for the folder for my AV software
- Attempted to launch directly from power shell with: 
> & C:\MMVCServerSIO\MMVCServerSIO.exe -p 18888 --https false --content_vec_500 pretrain/checkpoint_best_legacy_500.pt --content_vec_500_onnx pretrain/content_vec_500.onnx --content_vec_500_onnx_on true --hubert_base pretrain/hubert_base.pt --hubert_base_jp pretrain/rinna_hubert_base_jp.pt --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt --nsf_hifigan pretrain/nsf_hifigan/model --crepe_onnx_full pretrain/crepe_onnx_full.onnx --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx --rmvpe pretrain/rmvpe.pt --model_dir model_dir --samples samples.json

### Application Screenshot

![image](https://github.com/w-okada/voice-changer/assets/145516925/5fd33e9e-6c5c-479d-85a7-e7e1b106f4c6)
![image](https://github.com/w-okada/voice-changer/assets/145516925/85cc568f-c305-40ec-a9fb-d4a66e27a8e8)

### Logs on console

When launching with the batch file, the window closes immediately however if I add pause to the end then the cmd window displays: 
> C:\...\MMVCServerSIO\MMVCServerSIO.exe -p 18888 --https false --content_vec_500 pretrain/checkpoint_best_legacy_500.pt --content_vec_500_onnx pretrain/content_vec_500.onnx --content_vec_500_onnx_on true --hubert_base pretrain/hubert_base.pt --hubert_base_jp pretrain/rinna_hubert_base_jp.pt --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt --nsf_hifigan pretrain/nsf_hifigan/model --crepe_onnx_full pretrain/crepe_onnx_full.onnx --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx --rmvpe pretrain/rmvpe.pt --model_dir model_dir --samples samples.json
C:\...\MMVCServerSIO>pause
Press Any Key To Continue...

When launching via powershell ./start_http.bat:
> C:\...\MMVCServerSIO\MMVCServerSIO.exe -p 18888 --https false --content_vec_500 pretrain/checkpoint_best_legacy_500.pt --content_vec_500_onnx pretrain/content_vec_500.onnx --content_vec_500_onnx_on true --hubert_base pretrain/hubert_base.pt --hubert_base_jp pretrain/rinna_hubert_base_jp.pt --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt --nsf_hifigan pretrain/nsf_hifigan/model --crepe_onnx_full pretrain/crepe_onnx_full.onnx --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx --rmvpe pretrain/rmvpe.pt --model_dir model_dir --samples samples.json
PS C:\MMVCServerSIO

**Comment by cxoio** [comment]
yeah it happened to me too idk how to fix it

**Comment by w-okada** [comment]
no res close

**Comment by eyehack84** [comment]
Thanks for nothing, just keep closing every help request..And windows 11 is
ass
