### ISSUE TITLE
[REQUEST]: F0 Det. depending on version

### ISSUE THREAD

**Issue by Rafacasari** [w-okada/voice-changer#870]
### In a few words, describe your idea

What if we show f0 det. methods depending on which version the user is on? Like, for NVidia I think all options are good, but for DirectML/AMD just crepe_tiny and rmvpe_onnx are necessary. Also make some alert for .pth models in DirectML, since it only works with .onnx

### More information

This would make easier for AMD users to understand the program and prevent people from spamming the Issues Tab with the same question.

**Comment by w-okada** [comment]
OK. 
will be implemented in next release.

**Comment by w-okada** [comment]
try the latest version.(v.1.5.3.14)

![image](https://github.com/w-okada/voice-changer/assets/48346627/8c0fdaf3-b4b6-41ad-be7c-508f0a57c635)

**Comment by w-okada** [comment]
no res close
