### ISSUE TITLE
[ISSUE]: Res keep increasing

### ISSUE THREAD

**Issue by RichterPyre** [w-okada/voice-changer#871]
### Voice Changer Version

v.1.5.3.13

### Operational System

windows 11

### GPU

rtx 3050

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

I downloaded the changer and did everything correctly when I selected the voice and started speaking res begins to rise higher and higher up to 125000, after which it remains at this value and lower

### Application Screenshot

![image](https://github.com/w-okada/voice-changer/assets/145543532/6bcf97b2-5b09-495d-9a66-39c36ce1787d)

### Logs on console

C:\Users\cryni\OneDrive\Рабочий стол\rcv models\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
2023-09-20 14:03:21.8938057 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1641 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
[VCClient] wait web server...10 http://127.0.0.1:18888/
[Voice Changer] generate new embedder. (no embedder)
[VCClient] wait web server...20 http://127.0.0.1:18888/
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
[VCClient] wait web server... done 200
[2023-09-20 14:03:54] connet sid : yxdAxtk81-8iZ6_CAAAB
[2023-09-20 14:03:54] connet sid : t6rWcpgrQ4IG-cHYAAAD
[Voice Changer] update configuration: modelSlotIndex 1695197037003
Pipeline has been deleted
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\3\added_IVF2736_Flat_nprobe_1_v2.index.bin
[Voice Changer] update configuration: passThrough true
[Voice Changer] update configuration: passThrough false
[2023-09-20 14:05:50] connet sid : zCFTiZs-xllePnnAAAAF
[2023-09-20 14:06:38] connet sid : Ek3Vn7fsxqGpw9RrAAAH
[Voice Changer] update configuration: f0Detector harvest
[Voice Changer] update configuration: extraConvertSize 32768

**Comment by Mojobones** [comment]
What CPU do you have? 

Try swapping to RMVPE that should use your GPU more, or try raising your chunk num if you're staying on Harvest.

**Comment by RichterPyre** [comment]
My CPU is Amd A7 and swapping and raising chunks or smh not helping on any

> What CPU do you have?
> 
> Try swapping to RMVPE that should use your GPU more, or try raising your chunk num if you're staying on Harvest.

**Comment by w-okada** [comment]
use dio as f0 det. decrease extra.

**Comment by RichterPyre** [comment]
> use dio as f0 det. decrease extra.

Same, still rising by no reason

**Comment by w-okada** [comment]
check performance monitor. bottle neck is cpu or gpu?

**Comment by RichterPyre** [comment]
> check performance monitor. bottle neck is cpu or gpu?

Both about the same

**Comment by w-okada** [comment]
??
Which is the bottleneck, CPU or GPU?

**Comment by RichterPyre** [comment]
> ?? Which is the bottleneck, CPU or GPU?

in new version res stop increasing but, now vol is 0 always, but in passthru mode is normal

**Comment by w-okada** [comment]
This is a new phenomenon, isn't it? If it's a completely different phenomenon, please start a new issue. 

I'll be closing this now.

**Comment by RichterPyre** [comment]
> This is a new phenomenon, isn't it? If it's a completely different phenomenon, please start a new issue.
> 
> I'll be closing this now.

Yeah but, you're silent for someone with same problem rn
