### ISSUE TITLE
[ISSUE]: the server does not start

### ISSUE THREAD

**Issue by deathless66** [w-okada/voice-changer#872]
### Voice Changer Version

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.13

### Operational System

Windows 11

### GPU

RX580

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

MMVC

### Issue Description

Hello. I'm trying to run the program, but I get an eternal attempt to access 127.0.0.1:18888. Nothing changes. Played with hosts and cleaned DNS. I read on other branches that you need to delete the settings file, but I don't have any, a screenshot is attached, as is the log from the console. If you just ping 127.0.0.1 in the terminal, then there are no problems. And with the port there is no access anymore. I also tried version 1.5.3.12а and what can I do?

### Application Screenshot

![Снимок экрана 2023-09-20 142504](https://github.com/w-okada/voice-changer/assets/96599918/367eb27b-ff1f-49cf-aff5-aa2f47ec5321)

### Logs on console

C:\MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.12a\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
[VCClient] wait web server...10 http://127.0.0.1:18888/
[VCClient] wait web server...20 http://127.0.0.1:18888/
[VCClient] wait web server...30 http://127.0.0.1:18888/
[VCClient] wait web server...40 http://127.0.0.1:18888/
[VCClient] wait web server...50 http://127.0.0.1:18888/
[VCClient] wait web server...60 http://127.0.0.1:18888/
[VCClient] wait web server...70 http://127.0.0.1:18888/
[VCClient] wait web server...80 http://127.0.0.1:18888/
[VCClient] wait web server...90 http://127.0.0.1:18888/
[VCClient] wait web server...100 http://127.0.0.1:18888/
[VCClient] wait web server...110 http://127.0.0.1:18888/
[VCClient] wait web server...120 http://127.0.0.1:18888/
[VCClient] wait web server...130 http://127.0.0.1:18888/
[VCClient] wait web server...140 http://127.0.0.1:18888/
[VCClient] wait web server...150 http://127.0.0.1:18888/
[VCClient] wait web server...160 http://127.0.0.1:18888/
[VCClient] wait web server...170 http://127.0.0.1:18888/
[VCClient] wait web server...180 http://127.0.0.1:18888/
[VCClient] wait web server...190 http://127.0.0.1:18888/
[VCClient] wait web server...200 http://127.0.0.1:18888/
[VCClient] wait web server...210 http://127.0.0.1:18888/
[VCClient] wait web server...220 http://127.0.0.1:18888/
[VCClient] wait web server...230 http://127.0.0.1:18888/
[VCClient] wait web server...240 http://127.0.0.1:18888/
[VCClient] wait web server...250 http://127.0.0.1:18888/
[VCClient] wait web server...260 http://127.0.0.1:18888/

**Comment by w-okada** [comment]
check windows firewall

**Comment by deathless66** [comment]
> check windows firewall
![image](https://github.com/w-okada/voice-changer/assets/96599918/b33392e2-12c9-4cad-840d-d6b82f5a52c6)
it doesn't work

**Comment by w-okada** [comment]
access http://localhost:18888 with chrome.

**Comment by masondaniels** [comment]
try deleting (or renaming) your stored_setting.json

**Comment by deathless66** [comment]
> access http://localhost:18888 with chrome.

![image](https://github.com/w-okada/voice-changer/assets/96599918/e463e83d-60a0-41f8-a1e9-a27aeb1738fc)

**Comment by deathless66** [comment]
> try deleting (or renaming) your stored_setting.json

I just don't have such a file

**Comment by deathless66** [comment]
> I'm not sure about the exact cause. One possibility could be that antivirus software is running. You could try turning it off on your own responsibility and see if that works.

![image](https://github.com/w-okada/voice-changer/assets/96599918/99df3374-adaf-4076-9964-e759459e4659)

Still not working, unfortunately. From the antivirus, I had only a built-in defender from Windows. Even after turning everything off, he doesn't care. The only solution I see is to try reinstalling the system. I think I can do it soon. Then I will tell you whether the problem has been solved or not. Thanks for the tips, I'm not closing the topic yet

**Comment by w-okada** [comment]
no update close.
