### ISSUE TITLE
[ISSUE]: Wrong model selected. (KeyError: 'config')

### ISSUE THREAD

**Issue by whoamigod** [w-okada/voice-changer#873]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13

### Operational System

Windows 10

### GPU

3070

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

MMVC

### Issue Description

get error when i try upload my model

### Logs on console

RVC:: slotInfo.modelFile D_2333333.pth
[Voice Changer] post_load_model ex: 'config'
Traceback (most recent call last):
  File "restapi\MMVC_Rest_Fileuploader.py", line 92, in post_load_model
  File "voice_changer\VoiceChangerManager.py", line 170, in loadModel
  File "voice_changer\RVC\RVCModelSlotGenerator.py", line 37, in loadModel
  File "voice_changer\RVC\RVCModelSlotGenerator.py", line 43, in _setInfoByPytorch
KeyError: 'config'

**Comment by w-okada** [comment]
use correct model. that is in weights folder.

**Comment by whoamigod** [comment]
Thanks a lot !!

**Comment by whoamigod** [comment]
Thanks a lot !!
