### ISSUE TITLE
[ISSUE]: Start_http.bat executable cannot find 'win32api' module

### ISSUE THREAD

**Issue by RSJMatt** [w-okada/voice-changer#880]
### Voice Changer Version

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.13

### Operational System

Windows 10

### GPU

Intel(R) HD Graphics 630 (also a second NVIDIA GeForce GTX 1050 Ti)

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

I've tried skimming through the already solved issued but didn't have much luck. On startup it closes nearly instantly, even if ran through Powershell. To get the error message it was run through command prompt (attachment 1). After checking the downloaded files I did see the folder pywin32_system32 and found the same files (attachment 2) one would 'pip install' in command prompt for Python v 3.11. Spent a few hours trying to find any solution but with no luck. So I came asking for help, sorry to bother you with this situation. (Please note that I'm at best an amateur with programming, it's not my profession and mostly a pass time activity to help with my other hobbies. So while I do understand a handful of terms and know how to do a few things, in reality I'm a layman in this situation and not an incredibly smart one at that. Sorry if I suck at this or missed something or take a bit longer to respond correctly.)

### Application Screenshot

![image](https://github.com/w-okada/voice-changer/assets/145767110/88e6c6cd-b37f-4028-8b49-3cafb0d9f464)
![image](https://github.com/w-okada/voice-changer/assets/145767110/503ee1b1-9c4a-40e8-95bc-dabeeb7c3ab5)

### Logs on console

C:\Users\rache\Desktop\Voice\MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.13\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 58, in <module>
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 42, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "win32com\__init__.py", line 9, in <module>
ModuleNotFoundError: No module named 'win32api'
[16980] Failed to execute script 'pyi_rth_win32comgenpy' due to unhandled exception!

**Comment by w-okada** [comment]
This is a phenomenon I've never heard of. I can't reproduce it, so I don't know how to resolve it. Sorry.

**Comment by RSJMatt** [comment]
I understand, thanks for replying so fast anyway. I'll close the thread and search around a bit more to see what can be done. Shame things didn't work out, but c'est la vie.

**Comment by sub4rl** [comment]
You must extract the files from the zip file entirely. That's why.
