### ISSUE TITLE
Output in microfone

### ISSUE THREAD

**Issue by whoamigod** [w-okada/voice-changer#883]
### Description

I have a question regarding the voice-changing feature on the platform. Currently, when I use voice-changing, the output is directed to my speakers. However, I'm wondering if it's possible to redirect the output to my microphone instead. This would allow me to use the microphone with the altered voice, which could be really useful for my needs.

Is there a way to configure the platform to send the voice-changing output to my microphone input instead of the speakers? I'd appreciate any guidance or assistance on this matter.

Thank you!

**Comment by exciar** [comment]
use a virtual audio cable like VB audio cable or this one[]( https://software.muzychenko.net/freeware/vac470lite.zip)

**Comment by exciar** [comment]
also next time please read the manual (there is a manual)
