### ISSUE TITLE
AI accelerator pcie card

### ISSUE THREAD

**Issue by AlexNikMak** [w-okada/voice-changer#885]
### Description

Hello everyone, I’m quite new to this topic, so forgive me in advance if the question is posted in the wrong way or is off topic.

I'm wondering if it's possible to use M.2 Accelerator with Dual Edge TPU(https://coral.ai/products/m2-accelerator-dual-edgetpu/) instead of or together with a regular video card. Also, will this bring a performance increase or will it significantly reduce the use of the video card? Or will replace it altogether. This question interests me greatly since these devices are relatively inexpensive compared to video cards.

Thank you very much for your answer.

**Comment by w-okada** [comment]
Sorry, I have no idea...

**Comment by exciar** [comment]
I have seen this M.2 Accelerator before but I don't think that small of a chip can handle this type of thing, I have seen that in use with CCTV facial and movement detection but I doubt that would work here

**Comment by w-okada** [comment]
no update close
