### ISSUE TITLE
[ISSUE]:  GPU is not used because of CPU bottleneck. (Nvidia video card not working)

### ISSUE THREAD

**Issue by xxxiaomixxx** [w-okada/voice-changer#886]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.14

### Operational System

Windows 10 22H2

### GPU

RTX 3070 Laptop (Peladn)

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [x] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

My video card doesn't load even though I choose to use it. The video card is not being used on both the stock and my trained model
My system:
CPU - Intel Xeon E5-2696 v3
GPU - NVIDIA GeForce RTX 3070 Laptop (from Peladn, a Chinese desktop PC card)

### Application Screenshot

![image](https://github.com/w-okada/voice-changer/assets/70484784/aaf941d9-abab-48fd-9fc5-9525af37f46f)
![image](https://github.com/w-okada/voice-changer/assets/70484784/ce8b23ee-60ee-402d-8c2f-1c609d9870a6)

### Logs on console

D:\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
                                                                                                                       [Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='つくよみちゃん(onnx)', description='', credit='つくよみちゃん', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tsukuyomi-chan/terms_of_use.txt', iconFile='tsukuyomi-chan.png', speakers={0: 'target'}, modelFile='tsukuyomi_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='Tsukuyomi-chan_o', version='v2')
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='あみたろ(onnx)', description='', credit='あみたろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/amitaro/terms_of_use.txt', iconFile='amitaro.png', speakers={0: 'target'}, modelFile='amitaro_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='Amitaro_o', version='v2')
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='黄琴まひろ(onnx)', description='', credit='黄琴まひろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/kikoto_mahiro/terms_of_use.txt', iconFile='kikoto_mahiro.png', speakers={0: 'target'}, modelFile='kikoto_mahiro_v2_40k_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='KikotoMahiro_o', version='v2')
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='刻鳴時雨(onnx)', description='', credit='刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tokina_shigure/terms_of_use.txt', iconFile='tokina_shigure.png', speakers={0: 'target'}, modelFile='tokina_shigure_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='TokinaShigure_o', version='v2')
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='あみたろ 16k(onnx)', description='', credit='あみたろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/amitaro16k/terms_of_use.txt', iconFile='amitaro.png', speakers={0: 'target'}, modelFile='amitaro_v2_16k.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='Amitaro_16k_o', version='v2')
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='あみたろ 16k(onnx)', description='', credit='あみたろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/amitaro16k/terms_of_use.txt', iconFile='amitaro_nof0.png', speakers={0: 'target'}, modelFile='amitaro_v2_16k_nof0.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='Amitaro_16k_nof0_o', version='v2')
[Voice Changer] Downloading model files...
                                                                                                                                                             [Voice Changer] Generating metadata...
[Voice Changer] ONNX Model: Official v2 like
SlotInfo::: RVCModelSlot(slotIndex=0, voiceChangerType='RVC', name='つくよみちゃん(onnx)', description='', credit='つくよみちゃん', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tsukuyomi-chan/terms_of_use.txt', iconFile='tsukuyomi-chan.png', speakers={'0': 'target'}, modelFile='tsukuyomi_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='Tsukuyomi-chan_o', version='v2')
[Voice Changer] ONNX Model: Official v2 like
SlotInfo::: RVCModelSlot(slotIndex=1, voiceChangerType='RVC', name='あみたろ(onnx)', description='', credit='あみたろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/amitaro/terms_of_use.txt', iconFile='amitaro.png', speakers={'0': 'target'}, modelFile='amitaro_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='Amitaro_o', version='v2')
[Voice Changer] ONNX Model: Official v2 like
SlotInfo::: RVCModelSlot(slotIndex=2, voiceChangerType='RVC', name='黄琴まひろ(onnx)', description='', credit='黄琴まひろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/kikoto_mahiro/terms_of_use.txt', iconFile='kikoto_mahiro.png', speakers={'0': 'target'}, modelFile='kikoto_mahiro_v2_40k_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='KikotoMahiro_o', version='v2')
[Voice Changer] ONNX Model: Official v2 like
SlotInfo::: RVCModelSlot(slotIndex=3, voiceChangerType='RVC', name='刻鳴時雨(onnx)', description='', credit='刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tokina_shigure/terms_of_use.txt', iconFile='tokina_shigure.png', speakers={'0': 'target'}, modelFile='tokina_shigure_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='TokinaShigure_o', version='v2')
[Voice Changer] ONNX Model: Official v2 like
SlotInfo::: RVCModelSlot(slotIndex=4, voiceChangerType='RVC', name='あみたろ 16k(onnx)', description='', credit='あみたろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/amitaro16k/terms_of_use.txt', iconFile='amitaro.png', speakers={'0': 'target'}, modelFile='amitaro_v2_16k.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=16000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='Amitaro_16k_o', version='v2.1')
[Voice Changer] ONNX Model: Official v2 like
SlotInfo::: RVCModelSlot(slotIndex=5, voiceChangerType='RVC', name='あみたろ 16k(onnx)', description='', credit='あみたろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/amitaro16k/terms_of_use.txt', iconFile='amitaro_nof0.png', speakers={'0': 'target'}, modelFile='amitaro_v2_16k_nof0.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVCNono', samplingRate=16000, f0=False, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='Amitaro_16k_nof0_o', version='v2.1')
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2023-09-25 21:55:18] connet sid : WRgqq46YiePZZUAPAAAC
[2023-09-25 21:55:18] connet sid : Xr54ypM_A_vPp8qGAAAD
paramDict {'voiceChangerType': 'RVC', 'slot': 6, 'isSampleMode': False, 'sampleId': None, 'files': [{'name': 'Maxemo4kaV3.1.pth', 'kind': 'rvcModel', 'dir': ''}, {'name': 'added_IVF579_Flat_nprobe_1_Maxemo4kaV3.1_v2.index', 'kind': 'rvcIndex', 'dir': ''}], 'params': {}}
FILE: LoadModelParamFile(name='Maxemo4kaV3.1.pth', kind='rvcModel', dir='')
move to C:\Users\Diana\AppData\Local\Temp\tmptfx1bsq6\upload_dir\Maxemo4kaV3.1.pth -> model_dir\6\Maxemo4kaV3.1.pth
FILE: LoadModelParamFile(name='added_IVF579_Flat_nprobe_1_Maxemo4kaV3.1_v2.index', kind='rvcIndex', dir='')
move to C:\Users\Diana\AppData\Local\Temp\tmptfx1bsq6\upload_dir\added_IVF579_Flat_nprobe_1_Maxemo4kaV3.1_v2.index -> model_dir\6\added_IVF579_Flat_nprobe_1_Maxemo4kaV3.1_v2.index
RVC:: slotInfo.modelFile Maxemo4kaV3.1.pth
[Voice Changer] Official Model(pyTorch) : v2
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='Maxemo4kaV3.1', description='', credit='', termsOfUseUrl='', iconFile='', speakers={0: 'target'}, modelFile='Maxemo4kaV3.1.pth', indexFile='added_IVF579_Flat_nprobe_1_Maxemo4kaV3.1_v2.index', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=False, modelType='pyTorchRVCv2', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='', version='v2')
params, LoadModelParams(voiceChangerType='RVC', slot=6, isSampleMode=False, sampleId=None, files=[LoadModelParamFile(name='Maxemo4kaV3.1.pth', kind='rvcModel', dir=''), LoadModelParamFile(name='added_IVF579_Flat_nprobe_1_Maxemo4kaV3.1_v2.index', kind='rvcIndex', dir='')], params={})
SlotInfo::: RVCModelSlot(slotIndex=6, voiceChangerType='RVC', name='Maxemo4kaV3.1', description='', credit='', termsOfUseUrl='', iconFile='model_dir\\6\\_maxemo4ka-12-08-2023-0001.jpg', speakers={'0': 'target'}, modelFile='Maxemo4kaV3.1.pth', indexFile='added_IVF579_Flat_nprobe_1_Maxemo4kaV3.1_v2.index', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=False, modelType='pyTorchRVCv2', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='', version='v2')
[Voice Changer] update configuration: modelSlotIndex 1695668165006
[Voice Changer] model slot is changed -1 -> 6
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] update configuration: gpu 0
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
2023-09-25 21:56:09.6713610 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-09-25 21:56:09.6801556 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] Loading index...
Try loading... model_dir\6\added_IVF579_Flat_nprobe_1_Maxemo4kaV3.1_v2.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x000002170AC06380>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x00000218D2B24310>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x00000218D2B24400>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings modelSlotIndex:1695668165006
[Voice Changer] generate new embedder. (anyway)
2023-09-25 21:56:12.4113833 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-09-25 21:56:12.4204979 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] Loading index...
Try loading... model_dir\6\added_IVF579_Flat_nprobe_1_Maxemo4kaV3.1_v2.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x00000217153F34F0>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x0000021717444BB0>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x000002170ABCB010>
Pipeline has been deleted
[Voice Changer] [RVC] Initializing... done
[Voice Changer] update configuration: serverReadChunkSize 96
[Voice Changer][RVC]: update_settings serverReadChunkSize:96
[Voice Changer] update configuration: extraConvertSize 65536
[Voice Changer][RVC]: update_settings extraConvertSize:65536
[Voice Changer] update configuration: tran 11
[Voice Changer][RVC]: update_settings tran:11
[Voice Changer] update configuration: tran 10
[Voice Changer][RVC]: update_settings tran:10
[Voice Changer] update configuration: tran 9
[Voice Changer][RVC]: update_settings tran:9
[Voice Changer] update configuration: tran 8
[Voice Changer][RVC]: update_settings tran:8
[Voice Changer] update configuration: tran 8
[Voice Changer][RVC]: update_settings tran:8
[Voice Changer] update configuration: tran 7
[Voice Changer] update configuration: tran 6
[Voice Changer][RVC]: update_settings tran:7
[Voice Changer][RVC]: update_settings tran:6
[Voice Changer] update configuration: tran 5
[Voice Changer][RVC]: update_settings tran:5
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] warming up... generating sola buffer.
[Voice Changer] update configuration: f0Detector harvest
[Voice Changer][RVC]: update_settings f0Detector:harvest
[Voice Changer] update configuration: f0Detector crepe_tiny
[Voice Changer][RVC]: update_settings f0Detector:crepe_tiny
[Voice Changer] update configuration: f0Detector harvest
[Voice Changer][RVC]: update_settings f0Detector:harvest
[Voice Changer] update configuration: f0Detector rmvpe_onnx
[Voice Changer][RVC]: update_settings f0Detector:rmvpe_onnx
[Voice Changer] update configuration: f0Detector crepe_full
[Voice Changer][RVC]: update_settings f0Detector:crepe_full

**Comment by w-okada** [comment]
Could you explain the situation when using the sample model? Also, aren't GPU used?

**Comment by xxxiaomixxx** [comment]
> Could you explain the situation when using the sample model? Also, aren't GPU used?

All sample models don't use gpu either
![image](https://github.com/w-okada/voice-changer/assets/70484784/a5e60f2e-bd53-4077-8b3a-83aa028ac66f)

**Comment by w-okada** [comment]
Is GPU used??

![image](https://github.com/w-okada/voice-changer/assets/48346627/10d7d27b-cdce-4ab7-9630-8d6062e2eef8)

**Comment by xxxiaomixxx** [comment]
> Is GPU used??

Mostly from Steam in the background, MMVCServer loads the GPU by 1-2%, while the CPU is loaded at 70-80%

**Comment by w-okada** [comment]
use dio, decrease extra

**Comment by xxxiaomixxx** [comment]
> use dio, decrease extra

When using dio, the CPU is practically not loaded, but the voice quality becomes too low
![image](https://github.com/w-okada/voice-changer/assets/70484784/5c2416ed-584b-4339-ad63-3674a504999a)

**Comment by w-okada** [comment]
Perhaps your CPU isn't powerful enough to run Harvest.
Use dio or rmvpe_onnx.

**Comment by xxxiaomixxx** [comment]
> Perhaps your CPU isn't powerful enough to run Harvest. Use dio or rmvpe_onnx.

In multithreaded performance my processor outperforms the i9 9900k, Harvest runs stable only on the processor at chunks 80

**Comment by w-okada** [comment]
I see.
Anyway, I recommend using rmvpe_onnx, not harvest.

And if resolved, close issue.
