### ISSUE TITLE
[ISSUE]: Whenever i try to use the app with a game open the voices start lagging a bunch

### ISSUE THREAD

**Issue by Rafdegus** [w-okada/voice-changer#888]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13.zip

### Operational System

Windows 10

### GPU

NVIDIA GeForce RTX 3060 Ti

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

Well first of all sometimes the voices cut or don't work that well
Whenever i boot up a game and try to use the program the voices start lagging.
At first i tought it might be a problem with space but i have alot of space left and when i check my task manager no app seems to be having a big impact on my pc's performance.

Maybe im doing something wrong but i don't think so
Also sorry if im not being clear since im not really used to this stuff

### Application Screenshot

![Capture](https://github.com/w-okada/voice-changer/assets/106196710/360da284-706d-490c-9bfb-002608d0d343)

### Logs on console

    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] model slot is changed -1 -> 7
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
2023-09-26 02:21:34.7575891 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-09-26 02:21:34.7666367 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[VCClient] wait web server...10 http://127.0.0.1:18888/
[Voice Changer] Loading index...
Try loading... model_dir\7\added_IVF1243_Flat_nprobe_1_NuxTaku2_v2.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x0000025172C5B880>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x00000251DF100580>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x00000251DF1005B0>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings extraConvertSize:4096
[Voice Changer][RVC]: update_settings silentThreshold:0.00042
[Voice Changer][RVC]: update_settings f0Detector:crepe
[Voice Changer][RVC]: update_settings enableServerAudio:0
[Voice Changer][RVC]: update_settings serverReadChunkSize:48
[Voice Changer][RVC]: update_settings serverOutputDeviceId:12
[Voice Changer][RVC]: update_settings serverInputDeviceId:1
[Voice Changer][RVC]: update_settings serverMonitorDeviceId:-1
[Voice Changer][RVC]: update_settings serverAudioSampleRate:48000
[Voice Changer][RVC]: update_settings serverInputAudioGain:4
[Voice Changer][RVC]: update_settings serverOutputAudioGain:4.4
[Voice Changer][RVC]: update_settings modelSlotIndex:1695691207007
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200

**Comment by w-okada** [comment]
increase chunk

**Comment by Rafdegus** [comment]
Well it's still a bit laggy but i think it's working!
Is there any way for me to know what chunk i need to put it on?

**Comment by w-okada** [comment]
OK great.

set very large value as chunk, then reduce the value until just before the sound cuts out.
