### ISSUE TITLE
its not working 

### ISSUE THREAD

**Issue by TaKeZo0o** [w-okada/voice-changer#890]
![Screenshot 2023-09-26 140059](https://github.com/w-okada/voice-changer/assets/146086293/1b736456-a7c6-433b-ac61-11937333783d)
### Description

hi i downloaded the app and went thro a tutorial and did everything but when i try to record the vol stays at 0.00000 hope u will reply asap and thanks in advance

**Comment by exciar** [comment]
what gpu are you using?

**Comment by w-okada** [comment]
no res close
