### ISSUE TITLE
what about amd gpu ?

### ISSUE THREAD

**Issue by ALEX5402** [w-okada/voice-changer#895]
### Description

- i unable to use my amd gpu in it ?

**Comment by Rafacasari** [comment]
You can use AMD on the DirectML version. Download the latest **DirectML VERSION** and use f0 det: crepe_tiny/rmvpe_onnx (whatever runs better on your end); **And use ONLY .onnx models!**

**Comment by ALEX5402** [comment]
I am on Linux can I do it ?

**Comment by hiimgush** [comment]
> You can use AMD on the DirectML version. Download the latest **DirectML VERSION** and use f0 det: crepe_tiny/rmvpe_onnx (whatever runs better on your end); **And use ONLY .onnx models!**

Where do you get ".onnx" models?

**Comment by w-okada** [comment]
@ALEX5402 

This might be helpful.

https://github.com/w-okada/voice-changer/issues/868

**Comment by ALEX5402** [comment]
Thanks

**Comment by exciar** [comment]
> > You can use AMD on the DirectML version. Download the latest **DirectML VERSION** and use f0 det: crepe_tiny/rmvpe_onnx (whatever runs better on your end); **And use ONLY .onnx models!**
> 
> Where do you get ".onnx" models?
> 
> Found this! For anyone in future its on the main screen of the Voice changer application.

you can convert your pth models to onnx 
there is a convert to onnx button when the loaded model is pth

**Comment by ALEX5402** [comment]
can you better explain me where do i put the onnx files and where do i get the onnx files i am on windows right now so how can i get the gpu id can you explain that a little bit ?

**Comment by exciar** [comment]
ohh you're on Linux yeah just read the guide they sent

**Comment by w-okada** [comment]
no update close
