### ISSUE TITLE
[ISSUE]: 

### ISSUE THREAD

**Issue by kirinlovelove** [w-okada/voice-changer#898]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.14（.zip）

### Operational System

Windows 11

### GPU

GeForce RTX 3070(8GB)

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

音声が入力されず使うことができない状況です
startを押すとcmdに画像のような文字がずっと流れていきます
再ダウンロードや設定をいろいろといじっても治らないです
よろしければアドバイスお願いします

### Application Screenshot

![スクリーンショット 2023-09-29 002618](https://github.com/w-okada/voice-changer/assets/146362376/660d7731-218f-4046-b068-6b0569a4446b)

### Logs on console

![スクリーンショット 2023-09-29 002549](https://github.com/w-okada/voice-changer/assets/146362376/9bf55889-8660-4349-8190-5a6e8288374f)

**Comment by w-okada** [comment]
クライアントモードでも動かないですか？

**Comment by kirinlovelove** [comment]
> クライアントモードでも動かないのですか？

動かないですがcmdに画像のような文字は出なくなりました。

**Comment by w-okada** [comment]
https://github.com/w-okada/voice-changer/blob/master/tutorials/trouble_shoot_communication_ja.md

**Comment by kirinlovelove** [comment]
おそらく(1)での音声の状態がおかしいのですが解決方法をご提示していただけると幸いです
音声ファイルの変換ができませんでした
音は聞こえるのですが変換できませんでした

**Comment by w-okada** [comment]
もしほかのマイクを持っているようでしたら、ほかのものを試してみてください。
また、だいぶ昔にマイクの性能が高いと動かないという現象はありました。サンプリングレートを48Khzになっていなかったら48Khzに変更してみてください。

**Comment by w-okada** [comment]
no res close
