### ISSUE TITLE
[ISSUE]: 

### ISSUE THREAD

**Issue by alphaatm2** [w-okada/voice-changer#899]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13.zip

### Operational System

Windows 10

### GPU

Rtx 3060

### Read carefully and check the options

- [x] I've tried to Clear Settings
- [x] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

MMVC

### Issue Description

before i factor resetted my pc i used this voice changer for months running at 96 chunk and 16384 with no problem then after the factor reset i can barely even run 128 chunk and 16384 extra. i have to run 192 chunk and 8192 extra for it to not repeat its self and i dont know why. i have a rtx 3060 and a intel core i7 9700k and 64 gb of ram and hdd memory it should be able to run with no problem

### Application Screenshot

![image](https://github.com/w-okada/voice-changer/assets/146376918/73df7fcf-f715-462f-b069-7372e47bdfed)

### Logs on console

D:\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] model slot is changed -1 -> 2
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:GPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[VCClient] wait web server...10 http://127.0.0.1:18888/
2023-09-28 13:50:46.5829880 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-09-28 13:50:46.5886731 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] Loading index...
Try loading... model_dir\2\added_IVF661_Flat_nprobe_1_meeky_v2.index
GENERATE INFERENCER<voice_changer.RVC.inferencer.RVCInferencerv2.RVCInferencerv2 object at 0x000002847B63BA30>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x000002847F8E4730>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.HarvestPitchExtractor.HarvestPitchExtractor object at 0x000002847F8E4760>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings enableServerAudio:1
[Voice Changer][RVC]: update_settings f0Detector:rmvpe
[Voice Changer][RVC]: update_settings serverInputDeviceId:1
[Voice Changer][RVC]: update_settings serverOutputDeviceId:8
[Voice Changer][RVC]: update_settings serverMonitorDeviceId:7
[Voice Changer][RVC]: update_settings serverReadChunkSize:192
[Voice Changer][RVC]: update_settings extraConvertSize:8192
[Voice Changer][RVC]: update_settings serverAudioSampleRate:48000
[Voice Changer][RVC]: update_settings serverInputAudioGain:1.4
[Voice Changer][RVC]: update_settings serverOutputAudioGain:1.6
[Voice Changer][RVC]: update_settings modelSlotIndex:1695870704002
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2023-09-28 13:51:07] connet sid : KSkVnDOldEgUhF8yAAAC
[2023-09-28 13:51:07] connet sid : rXrcQ2zJDUTS55pmAAAD
[Voice Changer] update configuration: serverAudioStated 1
[Voice Changer][RVC]: update_settings serverAudioStated:1
Devices:
  [Input]: ServerAudioDevice(kind='audioinput', index=1, name='VoiceMeeter Output (VB-Audio Vo', hostAPI='MME', maxInputChannels=2, maxOutputChannels=0, default_samplerate=44100.0, available_samplerates=[]) None
  [Output]: ServerAudioDevice(kind='audiooutput', index=8, name='CABLE Input (VB-Audio Virtual C', hostAPI='MME', maxInputChannels=0, maxOutputChannels=2, default_samplerate=44100.0, available_samplerates=[]) None
  [Monitor]: ServerAudioDevice(kind='audiooutput', index=7, name='VoiceMeeter Aux Input (VB-Audio', hostAPI='MME', maxInputChannels=0, maxOutputChannels=2, default_samplerate=44100.0, available_samplerates=[]) None

**Comment by w-okada** [comment]
If it was working before, it could be an issue related to the environment. I'm not sure about individual environments.

**Comment by alphaatm2** [comment]
im confused do u mind explaining that better? like do you think factor resetting my pc again would fix it

**Comment by w-okada** [comment]
Sorry, I have no idea. If it was working before, I think there must be some way to get it working again.

**Comment by w-okada** [comment]
no update close
