### ISSUE TITLE
read this

### ISSUE THREAD

**Issue by D3s71NY** [w-okada/voice-changer#901]
### Description

the voice changer It doesn't listen to the microphone of my headsets while other applications do without problem, Can it be solved or find another alternative?

**Comment by w-okada** [comment]
It depends on your environment.

By the way, have you granted permission to use the microphone in Chrome?

**Comment by D3s71NY** [comment]
> It depends on your environment.
> 
> By the way, have you granted permission to use the microphone in Chrome?

yes, i can, why?

**Comment by w-okada** [comment]
If you don't give permission for microphone access, the microphone may not be listed.

**Comment by w-okada** [comment]
no res close
