### ISSUE TITLE
Gpu not being found?

### ISSUE THREAD

**Issue by ToasterToucan** [w-okada/voice-changer#902]
### Description

I'm pretty sure my GPU isn't connected/ isn't being found. Not sure how to fix. 

"VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:CPU-DML)" 

![Capture](https://github.com/w-okada/voice-changer/assets/132066490/1aa3c66a-d636-47e4-93a1-32aed9db6458)

**Comment by w-okada** [comment]
use cuda version.

**Comment by ToasterToucan** [comment]
I've downloaded the MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.14.zip version. Is that not the cuda version?

**Comment by w-okada** [comment]
MMVCServerSIO_win_gpu-cuda_v.1.5.3.14.zip

**Comment by ToasterToucan** [comment]
Thank you! Although I cant seem to find the download for it :/

**Comment by exciar** [comment]
> Thank you! Although I cant seem to find the download for it :/

win | ONNX(cpu,cuda), PyTorch(cpu,cuda) its this one

**Comment by w-okada** [comment]
![Uploading image.png…]()

**Comment by w-okada** [comment]
![image](https://github.com/w-okada/voice-changer/assets/48346627/d0447a25-be59-4339-8470-b2be0d888de3)

**Comment by w-okada** [comment]
no res close
