### ISSUE TITLE
Do I buy a Quadro or GTX for this?

### ISSUE THREAD

**Issue by Visconomy** [w-okada/voice-changer#906]
### Description

I mostly use AMD since it meets all my needs at a lower price generally, but it seems like stuff like this is better if not made for the cuda cores Nvidia provide. I was having extreme trouble using my Rx 6700 XT with this, and I tried the solutions from many other posts to no avail. I want to buy a new gpu for this, should I expect better results if I get a Quadro M4000 over a GTX 1080? I know the 1080 is more performant when gaming but for something like this I think the Quadro would be more fit and perform better.

**Comment by exciar** [comment]
get the 1080 its 263% more powerful than the Quadro

**Comment by Rafacasari** [comment]
If you can, I would go for a RTX 3060 12GB. The extra VRAM can help you alot in another AI programs, like RVC training and Stable Diffusion.

**Comment by w-okada** [comment]
no update close
