### ISSUE TITLE
[ISSUE]: [Mac] w-okada's RVC does not work on or after Sonoma 14.0 

### ISSUE THREAD

**Issue by SWAGATRON** [w-okada/voice-changer#909]
### Voice Changer Version

MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.14.zip

### Operational System

MacOS Sonoma 14.0

### GPU

none

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

I have updated to Mac OS Sonoma (v 14.0) and now my RVC doesn't work, it worked when it was on Mac OS Monterrey v13.4 but it did have audio that chopped out at times (this could be attributed to something else but I am unsure of if the software itself have interference with something, I checked if my bluetooth was impeded by other signals and ensured my wi-fi was on 5Ghz. 

Essentially what happens is that upon launching the software using the 'startHttp.command' shell executable, the application launches and everything seems and appears to work just as fine except for the models/actual production of the altered voice. So for instance (and I will attach a clip to show you what I mean), if I set the input as my Yeti Blue mic, then the output to be either my speakers/headphones, or Virtual Cable, then put the monitor for my headphones, and I speak into the input, it reproduces a completely incoherent sound. 

I used other versions of w-okada's RVC for mac, and used different models and still nothing worked after I had made the update to go from MacOS Monterrey 13.4 to Sonoma 14.0. 

I uninstalled and reinstalled w-okada's open source RVC but still, nothing works, and tried restarting and resetting multiple other potential factors but nothing works post-update of my OS. It just launches and I can't get the voices to actually output my voice with the filter. Does anybody else experience something alike?

### Application Screenshot

![Screenshot 2023-09-30 at 9 07 53 PM](https://github.com/w-okada/voice-changer/assets/10934599/637bcdba-9286-4646-be7b-bd2e6ffb3b0f)

https://github.com/w-okada/voice-changer/assets/10934599/19a0551b-eb87-4e05-835d-2b8057d68ea9

### Logs on console

Last login: Sat Sep 30 05:20:06 on ttys000
/Users/user/Desktop/Voice\ Changer/MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.14/startHttp.command ; exit;
user@user's_computer ~ % /Users/user/Desktop/Voice\ Changer/MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.14/startHttp.command ; exit;
    Booting PHASE :__main__
    PYTHON:3.10.9 (main, Jan 15 2023, 23:00:56) [Clang 14.0.0 (clang-1400.0.29.202)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- -- 
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/
2023-09-30 21:05:42.901 voice-changer-native-client[20873:493338] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] model slot is changed -1 -> 4
................RVC
    Booting PHASE :__main__
[Voice Changer] [RVCr2] Creating instance 
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:True, onnx_device:CPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing... 
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x143b22e00>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x143b22800>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x143b22e60>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings extraConvertSize:32768
[Voice Changer][RVC]: update_settings silentThreshold:0.00026
[Voice Changer][RVC]: update_settings modelSlotIndex:1696063293004
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
mac model_dir: /Users/brianmarinruiz/Desktop/Voice Changer/MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.14/model_dir
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2023-09-30 21:05:47] connet sid : iBJ9rggnFdh9MTFpAAAB
[2023-09-30 21:05:47] connet sid : W4FmCnruXkD4jqjLAAAD
[Voice Changer] update configuration: tran 4
[Voice Changer][RVC]: update_settings tran:4
[Voice Changer] update configuration: tran 4
[Voice Changer][RVC]: update_settings tran:4
[Voice Changer] update configuration: tran 4
[Voice Changer][RVC]: update_settings tran:4
[Voice Changer] update configuration: tran 4
[Voice Changer][RVC]: update_settings tran:4
[Voice Changer] update configuration: tran 5
[Voice Changer][RVC]: update_settings tran:5
[Voice Changer] update configuration: tran 5
[Voice Changer][RVC]: update_settings tran:5
[Voice Changer] update configuration: tran 6
[Voice Changer][RVC]: update_settings tran:6
[Voice Changer] update configuration: tran 7
[Voice Changer][RVC]: update_settings tran:7
[Voice Changer] update configuration: tran 7
[Voice Changer][RVC]: update_settings tran:7
[Voice Changer] update configuration: tran 8
[Voice Changer][RVC]: update_settings tran:8
[Voice Changer] update configuration: tran 9
[Voice Changer][RVC]: update_settings tran:9
[Voice Changer] update configuration: tran 9
[Voice Changer] update configuration: tran 10
[Voice Changer][RVC]: update_settings tran:9
[Voice Changer][RVC]: update_settings tran:10
[Voice Changer] update configuration: tran 11
[Voice Changer][RVC]: update_settings tran:11
[Voice Changer] update configuration: tran 11
[Voice Changer][RVC]: update_settings tran:11
[Voice Changer] update configuration: tran 12
[Voice Changer][RVC]: update_settings tran:12
[Voice Changer] update configuration: tran 12
[Voice Changer][RVC]: update_settings tran:12
[Voice Changer] update configuration: tran 12
[Voice Changer][RVC]: update_settings tran:12
[Voice Changer] update configuration: tran 13
[Voice Changer][RVC]: update_settings tran:13
[Voice Changer] update configuration: tran 13
[Voice Changer][RVC]: update_settings tran:13
[Voice Changer] update configuration: tran 14
[Voice Changer][RVC]: update_settings tran:14
[Voice Changer] update configuration: tran 14
[Voice Changer][RVC]: update_settings tran:14
[Voice Changer] update configuration: tran 15
[Voice Changer][RVC]: update_settings tran:15
[Voice Changer] update configuration: tran 15
[Voice Changer][RVC]: update_settings tran:15
[Voice Changer] update configuration: tran 15
[Voice Changer][RVC]: update_settings tran:15
[Voice Changer] update configuration: tran 16
[Voice Changer][RVC]: update_settings tran:16
[Voice Changer] update configuration: tran 16
[Voice Changer] update configuration: tran 16
[Voice Changer][RVC]: update_settings tran:16
[Voice Changer][RVC]: update_settings tran:16
[Voice Changer] update configuration: tran 17
[Voice Changer][RVC]: update_settings tran:17
[Voice Changer] update configuration: tran 17
[Voice Changer][RVC]: update_settings tran:17
[Voice Changer] update configuration: tran 17
[Voice Changer][RVC]: update_settings tran:17
[Voice Changer] update configuration: tran 18
[Voice Changer][RVC]: update_settings tran:18
[Voice Changer] update configuration: tran 18
[Voice Changer][RVC]: update_settings tran:18
[Voice Changer] update configuration: tran 19
[Voice Changer][RVC]: update_settings tran:19
[Voice Changer] update configuration: tran 19
[Voice Changer][RVC]: update_settings tran:19
[Voice Changer] update configuration: tran 20
[Voice Changer][RVC]: update_settings tran:20
[Voice Changer] update configuration: tran 20
[Voice Changer][RVC]: update_settings tran:20
[Voice Changer] update configuration: tran 21
[Voice Changer][RVC]: update_settings tran:21
[Voice Changer] update configuration: tran 21
[Voice Changer][RVC]: update_settings tran:21
[Voice Changer] update configuration: tran 21
[Voice Changer][RVC]: update_settings tran:21
[Voice Changer] update configuration: tran 22
[Voice Changer][RVC]: update_settings tran:22
[Voice Changer] update configuration: tran 22
[Voice Changer][RVC]: update_settings tran:22
[Voice Changer] update configuration: tran 23
[Voice Changer][RVC]: update_settings tran:23
[Voice Changer] update configuration: tran 23
[Voice Changer][RVC]: update_settings tran:23
[Voice Changer] update configuration: tran 22
[Voice Changer][RVC]: update_settings tran:22
[Voice Changer] update configuration: tran 22
[Voice Changer] update configuration: tran 22
[Voice Changer][RVC]: update_settings tran:22
[Voice Changer][RVC]: update_settings tran:22
[Voice Changer] update configuration: tran 21
[Voice Changer][RVC]: update_settings tran:21
[Voice Changer] update configuration: serverReadChunkSize 512
[Voice Changer][RVC]: update_settings serverReadChunkSize:512
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] warming up... generating sola buffer.
[2023-09-30 21:13:03] connet sid : SIRuSQzgwP5MoKZwAAAF
[2023-09-30 21:13:03] connet sid : aGaxEFFPHsehr6LiAAAH
[Voice Changer] update configuration: modelSlotIndex 1696122834000
[Voice Changer] model slot is changed 4 -> 0
................RVC
[Voice Changer] [RVCr2] Creating instance 
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:True, onnx_device:CPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing... 
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x143c99a80>
[Voice Changer] update configuration: modelSlotIndex 1696122834000
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x143c98a00>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x143c9b490>
[Voice Changer] [RVC] Initializing... done
Pipeline has been deleted
[Voice Changer] model slot is changed 4 -> 0
................RVC
[Voice Changer] [RVCr2] Creating instance 
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:True, onnx_device:CPU)
Pipeline has been deleted
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing... 
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x148a1bb50>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x148a19270>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x148a18880>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings extraConvertSize:32768
[Voice Changer][RVC]: update_settings extraConvertSize:32768
[Voice Changer][RVC]: update_settings silentThreshold:0.00026
[Voice Changer][RVC]: update_settings silentThreshold:0.00026
[Voice Changer][RVC]: update_settings serverReadChunkSize:512
[Voice Changer][RVC]: update_settings serverReadChunkSize:512
[Voice Changer][RVC]: update_settings modelSlotIndex:1696122834000
[Voice Changer][RVC]: update_settings modelSlotIndex:1696122834000
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] warming up... generating sola buffer.
[2023-09-30 21:14:26] connet sid : gDA7QWzVp0u9OK_7AAAJ
[2023-09-30 21:14:26] connet sid : rgCiAoMqplibfPXeAAAL
[Voice Changer] update configuration: modelSlotIndex 1696122870002
[Voice Changer] model slot is changed 0 -> 2
................RVC
[Voice Changer] [RVCr2] Creating instance 
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:True, onnx_device:CPU)
Pipeline has been deleted
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing... 
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] update configuration: modelSlotIndex 1696122870002
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x1489eb250>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x14451cc70>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x148ab9930>
[Voice Changer] [RVC] Initializing... done
[Voice Changer] model slot is changed 0 -> 2
................RVC
[Voice Changer] [RVCr2] Creating instance 
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:True, onnx_device:CPU)
Pipeline has been deleted
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing... 
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x14456dc90>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x1489eb250>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x14451cc40>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings extraConvertSize:32768
[Voice Changer][RVC]: update_settings extraConvertSize:32768
[Voice Changer][RVC]: update_settings silentThreshold:0.00026
[Voice Changer][RVC]: update_settings silentThreshold:0.00026
[Voice Changer][RVC]: update_settings serverReadChunkSize:512
[Voice Changer][RVC]: update_settings serverReadChunkSize:512
[Voice Changer][RVC]: update_settings modelSlotIndex:1696122870002
[Voice Changer][RVC]: update_settings modelSlotIndex:1696122870002
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] warming up... generating sola buffer.
[Voice Changer] update configuration: modelSlotIndex 1696122893003
[Voice Changer] model slot is changed 2 -> 3
................RVC
[Voice Changer] [RVCr2] Creating instance 
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:True, onnx_device:CPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing... 
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x148a18730>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x14456f0d0>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x14456df30>
[Voice Changer] [RVC] Initializing... done
[Voice Changer] update configuration: modelSlotIndex 1696122893003
[Voice Changer] model slot is changed 2 -> 3
................RVC
[Voice Changer] [RVCr2] Creating instance 
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:True, onnx_device:CPU)
Pipeline has been deleted
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing... 
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x143b414b0>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x14456ed10>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x14456f0d0>
[Voice Changer] [RVC] Initializing... done
Pipeline has been deleted
[Voice Changer][RVC]: update_settings extraConvertSize:32768
[Voice Changer][RVC]: update_settings extraConvertSize:32768
[Voice Changer][RVC]: update_settings silentThreshold:0.00026
[Voice Changer][RVC]: update_settings silentThreshold:0.00026
[Voice Changer][RVC]: update_settings serverReadChunkSize:512
[Voice Changer][RVC]: update_settings serverReadChunkSize:512
[Voice Changer][RVC]: update_settings modelSlotIndex:1696122893003
[Voice Changer][RVC]: update_settings modelSlotIndex:1696122893003
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] warming up... generating sola buffer.
[Voice Changer] update configuration: modelSlotIndex 1696122907005
[Voice Changer] model slot is changed 3 -> 5
................RVC
[Voice Changer] [RVCr2] Creating instance 
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:True, onnx_device:CPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing... 
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencerNono.OnnxRVCInferencerNono object at 0x1465bcf40>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x143d02200>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x143c99270>
[Voice Changer] [RVC] Initializing... done
[Voice Changer] update configuration: modelSlotIndex 1696122908005
[Voice Changer] model slot is changed 3 -> 5
................RVC
[Voice Changer] [RVCr2] Creating instance 
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:True, onnx_device:CPU)
Pipeline has been deleted
Pipeline has been deleted
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing... 
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencerNono.OnnxRVCInferencerNono object at 0x148a19150>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x143b239a0>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x14456e470>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings extraConvertSize:32768
[Voice Changer][RVC]: update_settings extraConvertSize:32768
[Voice Changer][RVC]: update_settings silentThreshold:0.00026
[Voice Changer][RVC]: update_settings silentThreshold:0.00026
[Voice Changer][RVC]: update_settings serverReadChunkSize:512
[Voice Changer][RVC]: update_settings serverReadChunkSize:512
[Voice Changer][RVC]: update_settings modelSlotIndex:1696122907005
[Voice Changer][RVC]: update_settings modelSlotIndex:1696122908005
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] warming up... generating sola buffer.
[2023-09-30 21:15:18] connet sid : qyGmQy8KktHdX_SxAAAN
[2023-09-30 21:15:18] connet sid : s-GWQpn5e-TXxI9BAAAP
[Voice Changer] update configuration: modelSlotIndex 1696122932003
[Voice Changer] model slot is changed 5 -> 3
................RVC
[Voice Changer] [RVCr2] Creating instance 
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:True, onnx_device:CPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing... 
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x143c99270>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x148ab9f90>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x1489eaf80>
[Voice Changer] [RVC] Initializing... done
[Voice Changer] update configuration: modelSlotIndex 1696122932003
[Voice Changer] model slot is changed 5 -> 3
................RVC
[Voice Changer] [RVCr2] Creating instance 
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:True, onnx_device:CPU)
Pipeline has been deleted
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing... 
[Voice Changer] generate new embedder. (anyway)
Pipeline has been deleted
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x1489eaf20>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x148af43d0>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x14456f100>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings extraConvertSize:32768
[Voice Changer][RVC]: update_settings extraConvertSize:32768
[Voice Changer][RVC]: update_settings silentThreshold:0.00026
[Voice Changer][RVC]: update_settings silentThreshold:0.00026
[Voice Changer][RVC]: update_settings serverReadChunkSize:512
[Voice Changer][RVC]: update_settings serverReadChunkSize:512
[Voice Changer][RVC]: update_settings modelSlotIndex:1696122932003
[Voice Changer][RVC]: update_settings modelSlotIndex:1696122932003
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] warming up... generating sola buffer.
[Voice Changer] update configuration: modelSlotIndex 1696122945005
[Voice Changer] model slot is changed 3 -> 5
................RVC
[Voice Changer] [RVCr2] Creating instance 
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:True, onnx_device:CPU)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing... 
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencerNono.OnnxRVCInferencerNono object at 0x143c67c70>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x148abb880>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x148ab9060>
[Voice Changer] [RVC] Initializing... done
[Voice Changer] update configuration: modelSlotIndex 1696122945005
[Voice Changer] model slot is changed 3 -> 5
................RVC
[Voice Changer] [RVCr2] Creating instance 
VoiceChangerV2 Initialized (GPU_NUM(cuda):0, mps_enabled:True, onnx_device:CPU)
Pipeline has been deleted
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing... 
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencerNono.OnnxRVCInferencerNono object at 0x148abb7f0>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x143c67c70>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x148abb5e0>
[Voice Changer] [RVC] Initializing... done
Pipeline has been deleted
[Voice Changer][RVC]: update_settings extraConvertSize:32768
[Voice Changer][RVC]: update_settings extraConvertSize:32768
[Voice Changer][RVC]: update_settings silentThreshold:0.00026
[Voice Changer][RVC]: update_settings silentThreshold:0.00026
[Voice Changer][RVC]: update_settings serverReadChunkSize:512
[Voice Changer][RVC]: update_settings serverReadChunkSize:512
[Voice Changer][RVC]: update_settings modelSlotIndex:1696122945005
[Voice Changer][RVC]: update_settings modelSlotIndex:1696122945005

**Comment by sandlotie** [comment]
#591

**Comment by w-okada** [comment]
same

https://github.com/w-okada/voice-changer/issues/591
