### ISSUE TITLE
[ISSUE]: 

### ISSUE THREAD

**Issue by zwl2828596** [w-okada/voice-changer#912]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.14

### Operational System

win11

### GPU

4090

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Application Screenshot

![微信截图_20231002121839](https://github.com/w-okada/voice-changer/assets/104117549/cb0ced01-2036-43d5-9bef-8acc286ec26c)

### Logs on console

![微信截图_20231002123901](https://github.com/w-okada/voice-changer/assets/104117549/03cbb768-fc68-4f8a-a660-507739d73296)

**Comment by w-okada** [comment]
Use at your own risk, but stopping the antivirus may allow it to start up.

**Comment by zwl2828596** [comment]
After closing the antivirus software, the system still fails to start

**Comment by w-okada** [comment]
so, I have no idea

**Comment by w-okada** [comment]
Your system failed to download weight for rvc. check your network

![image](https://github.com/w-okada/voice-changer/assets/48346627/a6601ad3-d001-419d-814e-b6f1381552cc)

**Comment by w-okada** [comment]
no res close
