### ISSUE TITLE
 [ISSUE]: GPU not detected 

### ISSUE THREAD

**Issue by GODDFATHER07** [w-okada/voice-changer#913]
### Voice Changer Version

MMVCSereverSIO_ONNX(cpu,cuda), PyTorch(cpu,cuda)

### Operational System

Windows 10 

### GPU

GT 750M

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [X] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [ ] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

When i launch okada rvc i get a error [: The NVIDIA driver on your system is too old (found version 10010)] and i dont get the option to select my gpu even though my drivers are up to date and i even checked in geforce experience 

### Application Screenshot

![Screenshot 2023-10-02 132631](https://github.com/w-okada/voice-changer/assets/146707935/8bf1fa79-c1a9-47e5-9049-90cbc5f1207e)

### Logs on console

![Screenshot 2023-10-02 132356](https://github.com/w-okada/voice-changer/assets/146707935/b7923091-4595-48c8-9bb5-d323b6b735c6)

**Comment by Rafacasari** [comment]
You're using the cpu version, ofc it will not show lol. Download the gpu-cuda version, but I think your gpu is too old to run it.

**Comment by w-okada** [comment]
no update close

**Comment by GODDFATHER07** [comment]
I was kinda busy sry but can u send a screen shot of gpu cuda version I can’t find it

**Comment by w-okada** [comment]
maybe this one.

![image](https://github.com/w-okada/voice-changer/assets/48346627/917291c5-e5f0-4341-9667-f807ba42e557)


But 
>  but I think your gpu is too old to run it.
this comment is true.

**Comment by GODDFATHER07** [comment]
Thx
