### ISSUE TITLE
[ISSUE]: MacM2 white screen.

### ISSUE THREAD

**Issue by petsimxeazy** [w-okada/voice-changer#914]
### Voice Changer Version

MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.12a

### Operational System

MacBook Air (M2, 2022)

### GPU

no idea

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [ ] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

MMVC

### Issue Description

Hello. While i am lunching the GUI. It became white. And i try to reach the web :  https://127.0.0.1:18888/ , This site can’t be reached. Please help Thankyou.

### Application Screenshot

<img width="1470" alt="Screenshot 2023-10-02 at 7 19 17 PM" src="https://github.com/w-okada/voice-changer/assets/127602631/6fc956f2-dd31-4df5-92ab-a9c42c332f28">
<img width="1470" alt="Screenshot 2023-10-02 at 7 20 17 PM" src="https://github
<img width="1470" alt="Screenshot 2023-10-02 at 7 20 37 PM" src="https://github.com/w-okada/voice-changer/assets/127602631/8d256d96-857b-4971-9afa-6c273ab81070">
.com/w-okada/voice-changer/assets/127602631/e920a2e5-8e3c-43fd-bbe6-f2d531cba4b6">

### Logs on console

    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/
[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
mac model_dir: /private/var/folders/61/3byn2x053hq1mvgfj2w36d940000gp/T/AppTranslocation/F46CF29B-7810-42AC-8389-37F797B590B4/d/model_dir
[Voice Changer] Web Server Launch Exception, Directory '/private/var/folders/61/3byn2x053hq1mvgfj2w36d940000gp/T/AppTranslocation/F46CF29B-7810-42AC-8389-37F797B590B4/d/model_dir' does not exist
[VCClient] wait web server...10 http://127.0.0.1:18888/
[VCClient] wait web server...20 http://127.0.0.1:18888/
[VCClient] wait web server...30 http://127.0.0.1:18888/
[VCClient] wait web server...40 http://127.0.0.1:18888/
[VCClient] wait web server...50 http://127.0.0.1:18888/
[VCClient] wait web server...60 http://127.0.0.1:18888/
[VCClient] wait web server...70 http://127.0.0.1:18888/
[VCClient] wait web server...80 http://127.0.0.1:18888/
[VCClient] wait web server...90 http://127.0.0.1:18888/
[VCClient] wait web server...100 http://127.0.0.1:18888/
[VCClient] wait web server...110 http://127.0.0.1:18888/
[VCClient] wait web server...120 http://127.0.0.1:18888/
[VCClient] wait web server...130 http://127.0.0.1:18888/
[VCClient] wait web server...140 http://127.0.0.1:18888/
[VCClient] wait web server...150 http://127.0.0.1:18888/
[VCClient] wait web server...160 http://127.0.0.1:18888/
[VCClient] wait web server...170 http://127.0.0.1:18888/
[VCClient] wait web server...180 http://127.0.0.1:18888/
[VCClient] wait web server...190 http://127.0.0.1:18888/
[VCClient] wait web server...200 http://127.0.0.1:18888/
[VCClient] wait web server...210 http://127.0.0.1:18888/
[VCClient] wait web server...220 http://127.0.0.1:18888/
[VCClient] wait web server...230 http://127.0.0.1:18888/
[VCClient] wait web server...240 http://127.0.0.1:18888/
[VCClient] wait web server...250 http://127.0.0.1:18888/
[VCClient] wait web server...260 http://127.0.0.1:18888/
[VCClient] wait web server...270 http://127.0.0.1:18888/
[VCClient] wait web server...280 http://127.0.0.1:18888/
[VCClient] wait web server...290 http://127.0.0.1:18888/
[VCClient] wait web server...300 http://127.0.0.1:18888/
[VCClient] wait web server...310 http://127.0.0.1:18888/
[VCClient] wait web server...320 http://127.0.0.1:18888/
[VCClient] wait web server...330 http://127.0.0.1:18888/
[VCClient] wait web server...340 http://127.0.0.1:18888/
[VCClient] wait web server...350 http://127.0.0.1:18888/
[VCClient] wait web server...360 http://127.0.0.1:18888/
[VCClient] wait web server...370 http://127.0.0.1:18888/
[VCClient] wait web server...380 http://127.0.0.1:18888/
[VCClient] wait web server...390 http://127.0.0.1:18888/
[VCClient] wait web server...400 http://127.0.0.1:18888/
[VCClient] wait web server...410 http://127.0.0.1:18888/
[VCClient] wait web server...420 http://127.0.0.1:18888/
[VCClient] wait web server...430 http://127.0.0.1:18888/
[VCClient] wait web server...440 http://127.0.0.1:18888/
[VCClient] wait web server...450 http://127.0.0.1:18888/
[VCClient] wait web server...460 http://127.0.0.1:18888/
[VCClient] wait web server...470 http://127.0.0.1:18888/
[VCClient] wait web server...480 http://127.0.0.1:18888/
[VCClient] wait web server...490 http://127.0.0.1:18888/
[VCClient] wait web server...500 http://127.0.0.1:18888/
[VCClient] wait web server...510 http://127.0.0.1:18888/
[VCClient] wait web server...520 http://127.0.0.1:18888/
[VCClient] wait web server...530 http://127.0.0.1:18888/
[VCClient] wait web server...540 http://127.0.0.1:18888/
[VCClient] wait web server...550 http://127.0.0.1:18888/
[VCClient] wait web server...560 http://127.0.0.1:18888/
[VCClient] wait web server...570 http://127.0.0.1:18888/
[VCClient] wait web server...580 http://127.0.0.1:18888/
[VCClient] wait web server...590 http://127.0.0.1:18888/
[VCClient] wait web server...600 http://127.0.0.1:18888/
[VCClient] wait web server...610 http://127.0.0.1:18888/
[VCClient] wait web server...620 http://127.0.0.1:18888/
[VCClient] wait web server...630 http://127.0.0.1:18888/
[VCClient] wait web server...640 http://127.0.0.1:18888/
[VCClient] wait web server...650 http://127.0.0.1:18888/

**Comment by madhavchamp** [comment]
Im getting the same issue but on my windows pc.

**Comment by w-okada** [comment]
read tutorial

**Comment by petsimxeazy** [comment]
> read tutorial

where?
