### ISSUE TITLE
[ISSUE]: 

### ISSUE THREAD

**Issue by bel1221** [w-okada/voice-changer#916]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.14.zip

### Operational System

Windows 10

### GPU

RTX 2060

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [ ] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

MMVC

### Issue Description

cant find the stored_settings.json file anywhere

### Logs on console

C:\Users\Administrator\Desktop\MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.14\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[VCClient] wait web server...10 http://127.0.0.1:18888/
[VCClient] wait web server...20 http://127.0.0.1:18888/
[VCClient] wait web server...30 http://127.0.0.1:18888/
[VCClient] wait web server...40 http://127.0.0.1:18888/
[VCClient] wait web server...50 http://127.0.0.1:18888/
[VCClient] wait web server...60 http://127.0.0.1:18888/
[VCClient] wait web server...70 http://127.0.0.1:18888/
[VCClient] wait web server...80 http://127.0.0.1:18888/
[VCClient] wait web server...90 http://127.0.0.1:18888/
[VCClient] wait web server...100 http://127.0.0.1:18888/
[VCClient] wait web server...110 http://127.0.0.1:18888/
[VCClient] wait web server...120 http://127.0.0.1:18888/
[VCClient] wait web server...130 http://127.0.0.1:18888/
[VCClient] wait web server...140 http://127.0.0.1:18888/
[VCClient] wait web server...150 http://127.0.0.1:18888/

**Comment by bel1221** [comment]
i've read similar bug report but i can't find the stored_settings file to delete

**Comment by Rafacasari** [comment]
Check your GPU drivers and CUDA drivers

**Comment by 2blackbar** [comment]
Where are models in portable version? This soft is getting crashess all the damn time and once it stuck i cant run it again cause its stuck on certain model loading it over and over , if i knew where models are stored i just boot the F out the one that causes issues, devs should at least put up some info where models arre stored so we can remove them if they make software stuck at boot

**Comment by w-okada** [comment]
no update close.
