### ISSUE TITLE
Newbie Trouble

### ISSUE THREAD

**Issue by HollowJK** [w-okada/voice-changer#917]
### Description

I've been waiting for too long, but there's been no progress. Can you please explain why and how to resolve this?
![Screenshot 2023-10-03 182735](https://github.com/w-okada/voice-changer/assets/146834699/3f880047-ac45-4d38-b9a9-7e0f26515f7f)

**Comment by HollowJK** [comment]
If I enable passthru, it run without changing my voice, still my real voice

**Comment by HollowJK** [comment]
> ### Description
> I've been waiting for too long, but there's been no progress. Can you please explain why and how to resolve this? ![Screenshot 2023-10-03 182735](https://user-images.githubusercontent.com/146834699/272244211-3f880047-ac45-4d38-b9a9-7e0f26515f7f.png)

I think I'm wrong download version let me change it  first

**Comment by HollowJK** [comment]
![Uploading image.png…]()
Is the result still like this? Did I miss something?

**Comment by 2blackbar** [comment]
This soft , portable version is crashing and crashing all the time, it was not like this few months ago, i wish it was not flipping out all the time whenever i want to change pic or output device

**Comment by w-okada** [comment]
same

https://github.com/w-okada/voice-changer/issues/488
