### ISSUE TITLE
[ISSUE]: any time the microphone is turned on, it gives an error

### ISSUE THREAD

**Issue by MrRendy100** [w-okada/voice-changer#920]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.14.zip

### Operational System

Windows 10

### GPU

Geforce GTX 1660

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

I installed the application, all settings work stably, but when selecting any microphone it gives an error

### Application Screenshot

![image](https://github.com/w-okada/voice-changer/assets/146920433/cd199702-7770-44e1-a703-b87947ecb704)
![image](https://github.com/w-okada/voice-changer/assets/146920433/0062da71-4926-45b3-b66b-742425a2d3a3)
![image](https://github.com/w-okada/voice-changer/assets/146920433/f437f6ea-76bc-496e-bebb-f5fd48f11d2d)

### Logs on console

C:\Ai voice changer\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2023-10-04 09:29:18] connet sid : tVrxdyeBOTb3kD6HAAAB
[2023-10-04 09:29:18] connet sid : nQCg-Tuz-PcW1DCTAAAD
[Voice Changer] update configuration: f0Detector crepe_tiny
[Voice Changer] update configuration: gpu 0
[Voice Changer] update configuration: enableServerAudio 1
[Voice Changer] update configuration: serverInputDeviceId 0
[Voice Changer] update configuration: enableServerAudio 0
[Voice Changer] update configuration: protect 0.1
[Voice Changer] update configuration: protect 0.1
[Voice Changer] update configuration: protect 0.2
[Voice Changer] update configuration: protect 0.2
[Voice Changer] update configuration: protect 0.3
[Voice Changer] update configuration: protect 0.3
[Voice Changer] update configuration: protect 0.4
[Voice Changer] update configuration: protect 0.4
[Voice Changer] update configuration: protect 0.3
[Voice Changer] update configuration: protect 0.3
[Voice Changer] update configuration: protect 0.3
[Voice Changer] update configuration: protect 0.3
[Voice Changer] update configuration: protect 0.1
[Voice Changer] update configuration: protect 0.1
[Voice Changer] update configuration: protect 0.1
[Voice Changer] update configuration: protect 0.1
[Voice Changer] update configuration: protect 0.1
[Voice Changer] update configuration: protect 0.1
[Voice Changer] update configuration: protect 0.1
[Voice Changer] update configuration: protect 0.1
[Voice Changer] update configuration: protect 0.1
[2023-10-04 09:31:19] connet sid : EAAaE34XNYAWRgSRAAAF
[2023-10-04 09:31:19] connet sid : woVRYmPKdJnqXPEuAAAH
[2023-10-04 09:42:43] connet sid : Wda2vvsdhfnLdY3lAAAJ
[2023-10-04 09:42:43] connet sid : ncE0dzLNdt7WFo3VAAAL

**Comment by w-okada** [comment]
Can you select file as input? If you can, you might not have permission to access the microphone. Please check your settings.

sorry japanese.
![image](https://github.com/w-okada/voice-changer/assets/48346627/cfdae12f-0b53-41a9-b134-41be364b7718)

**Comment by MrRendy100** [comment]
![image](https://github.com/w-okada/voice-changer/assets/146920433/b6f5b6c4-5220-4551-96b5-f99be91e7e8c)
did as you said it still doesn't work

**Comment by w-okada** [comment]
So, I have no idea.

**Comment by w-okada** [comment]
no update close
