### ISSUE TITLE
[ISSUE]: low chunk make res going higher

### ISSUE THREAD

**Issue by juanra932** [w-okada/voice-changer#922]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13.zip

### Operational System

windows 10

### GPU

Nvidia Geforce 920MX

### Read carefully and check the options

- [x] I've tried to Clear Settings
- [x] Sample/Default Models are working
- [x] I've tried to change the Chunk Size
- [x] GUI was successfully launched
- [x] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

i launch the http.bat file and everything works normally apparently but when y choose a model and click start it sounds a choppy audio and the res highes up very fast

### Application Screenshot

![Captura de pantalla 2023-10-04 183357](https://github.com/w-okada/voice-changer/assets/146977912/390638b1-de28-42a7-8521-40281517e5b1)

### Logs on console

[log_voice_changer.txt](https://github.com/w-okada/voice-changer/files/12805985/log_voice_changer.txt)

**Comment by w-okada** [comment]
increase chunk and use dio

**Comment by exciar** [comment]
try 256 chunk or higher

**Comment by juanra932** [comment]
> increase chunk and use dio

i increased the chunk at 512 and used dio and the choppy audio fixed but every second i was talking the res went up more and more up as well as the delay

**Comment by juanra932** [comment]
> increase chunk and use dio

I increased chunk and put dio, the choppy audio fixed but the res keeps going higher and higher every second i talk

**Comment by exciar** [comment]
get new machine better nvidia gpu goodluck godspeed buddy

**Comment by w-okada** [comment]
no update close
