### ISSUE TITLE
[ISSUE]: There is no sound from the program monitor, but you will hear a trial voice when using the virtual cable with another program.

### ISSUE THREAD

**Issue by hoshdf3344** [w-okada/voice-changer#926]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.14.zip

### Operational System

win11

### GPU

nvdia 3080

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [X] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.14.zip

### Issue Description

[ISSUE]: There is no sound from the program monitor, but you will hear a trial voice when using the virtual cable with another program. 
[녹음.zip](https://github.com/w-okada/voice-changer/files/12831046/default.zip)

### Application Screenshot

![스크린샷 2023-10-06 213104](https://github.com/w-okada/voice-changer/assets/147162233/85e4560c-eb89-42a6-b8d8-70fd48d9fbd1)

### Logs on console

index.js:2 AUDIO_CONTEXT null
index.js:2 serverSetting.serverSetting.passThrough character-area-control-passthru-button-stanby false
index.js:2 initializedRef.current false
index.js:2 [voiceChangerClient] is not ready for set audio output.
setAudioOutputElementId @ index.js:2
index.js:2 initializedRef.current false
index.js:2 [voiceChangerClient] is not ready for set audio output.
setAudioMonitorElementId @ index.js:2
index.js:2 AUDIO_CONTEXT null
index.js:2 AUDIO_CONTEXT null
index.js:2 Sample rate: default(48000)
index.js:2 AudioContext
index.js:2 AUDIO_CONTEXT AudioContext
index.js:2 AUDIO_CONTEXT AudioContext
index.js:2 [worklet_node][voice-changer-worklet-processor] created.
index.js:2 audio out: AudioContext
index.js:2 [worklet_node][voice-changer-worklet-processor] created.
index.js:2 [SIO] connect to 
index.js:2 [SIO] 50pYsVVL1-E8bS5LAAAa
index.js:2 [SIO] connect to 
index.js:2 [SIO] BsladLZUt-JtK1dZAAAb
index.js:2 [useClient] client initialized
index.js:2 serverSetting.serverSetting.passThrough character-area-control-passthru-button-stanby false
 [worklet] worklet configured Object
47f424a2-e68a-47c3-96dd-9aa8af2d6ecb:1 [worklet] worklet configured Object
index.js:2 AUDIO_CONTEXT AudioContext
index.js:2 AUDIO_CONTEXT AudioContext
index.js:2 initializedRef.current true
index.js:2 initializedRef.current true
index.js:2 [WorkletNode] Updating WorkletNode Setting, Object Object
index.js:2 [WorkletNode] Updating WorkletNode Setting, Object Object
 [worklet] worklet configured Object
47f424a2-e68a-47c3-96dd-9aa8af2d6ecb:1 [worklet] worklet configured Object
index.js:2 Input Setup=> echo: false, noise1: false, noise2: false
index.js:2 AUDIO_CONTEXT AudioContext
index.js:2 serverSetting.serverSetting.passThrough character-area-control-passthru-button-stanby false
index.js:2 AUDIO_CONTEXT AudioContext
index.js:2 serverSetting.serverSetting.passThrough character-area-control-passthru-button-stanby false
index.js:2 Input Setup=> success
index.js:2 serverSetting.serverSetting.passThrough character-area-control-passthru-button-stanby false
index.js:2 AUDIO_CONTEXT AudioContext
index.js:2 serverSetting.serverSetting.passThrough character-area-control-passthru-button-stanby false
index.js:2 AUDIO_CONTEXT AudioContext
index.js:2 serverSetting.serverSetting.passThrough character-area-control-passthru-button-stanby false
index.js:2 AUDIO_CONTEXT AudioContext
index.js:2 serverSetting.serverSetting.passThrough character-area-control-passthru-button-stanby false
index.js:2 AUDIO_CONTEXT AudioContext
index.js:2 serverSetting.serverSetting.passThrough character-area-control-passthru-button-stanby false
index.js:2 AUDIO_CONTEXT AudioContext
index.js:2 serverSetting.serverSetting.passThrough character-area-control-passthru-button-stanby false
index.js:2 AUDIO_CONTEXT AudioContext
index.js:2 serverSetting.serverSetting.passThrough character-area-control-passthru-button-stanby false
index.js:2 AUDIO_CONTEXT AudioContext
index.js:2 serverSetting.serverSetting.passThrough character-area-control-passthru-button-stanby false
index.js:2 AUDIO_CONTEXT AudioContext
index.js:2 serverSetting.serverSetting.passThrough character-area-control-passthru-button-stanby false
index.js:2 AUDIO_CONTEXT AudioContext
index.js:2 serverSetting.serverSetting.passThrough character-area-control-passthru-button-stanby false
index.js:2 AUDIO_CONTEXT AudioContext
index.js:2 serverSetting.serverSetting.passThrough character-area-control-passthru-button-stanby false
index.js:2 AUDIO_CONTEXT AudioContext
index.js:2 serverSetting.serverSetting.passThrough character-area-control-passthru-button-stanby false
index.js:2 AUDIO_CONTEXT AudioContext
index.js:2 serverSetting.serverSetting.passThrough character-area-control-passthru-button-stanby false
DevTools failed to load source map: Could not load content for http://127.0.0.1:18888/worker-v1.js.map: Fetch through target failed: Target not supported; Fallback: Unknown error

**Comment by w-okada** [comment]
I'm not quite understanding the issue. The attached audio seems to be converted as I hear it.

**Comment by w-okada** [comment]
no res close
