### ISSUE TITLE
not working on discord, no audio, does not show any mic signs

### ISSUE THREAD

**Issue by Hackcool2** [w-okada/voice-changer#927]
### Voice Changer Version

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.14.zip

### Operational System

windows 11

### GPU

idk

### Read carefully and check the options

- [x] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [x] I've tried to change the Chunk Size
- [x] GUI was successfully launched
- [x] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [x] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

idk how to chck

### Issue Description

 correct mic is attached along with virtual cable along in discord but no audio comes to the person in the call, even though voice changer is on and speaking loudly

### Application Screenshot

<img width="531" alt="image" src="https://github.com/w-okada/voice-changer/assets/122718126/1e24e764-0cd4-4a6e-8a29-70644bc2e6c5">

### Logs on console

idk

**Comment by exciar** [comment]
try turning off echo cancellation on discord
![image](https://github.com/w-okada/voice-changer/assets/139718583/86e8bf85-463d-45c3-b001-e6883071945d)

**Comment by w-okada** [comment]
no update close
