### ISSUE TITLE
When I directly click on "Start_http.bat", a window pops up and immediately closes. 

### ISSUE THREAD

**Issue by skyetang** [w-okada/voice-changer#929]
### Description

When I directly click on "Start_http.bat", a window pops up and immediately closes. The same thing happens when I click on "MMVCServerSIO.exe". So I tried entering "start_http.bat" in the command line interface, but encountered the following issues. How can I resolve them?

DERROR:
D:\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 58, in <module>
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 42, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "win32com\__init__.py", line 9, in <module>
ModuleNotFoundError: No module named 'win32api'
[2400] Failed to execute script 'pyi_rth_win32comgenpy' due to unhandled exception!

**Comment by w-okada** [comment]
Sorry, no information to research. use issue report.

![image](https://github.com/w-okada/voice-changer/assets/48346627/04d38a21-3457-47b9-8fc2-c396303d8c49)

**Comment by w-okada** [comment]
no update close
