### ISSUE TITLE
[REQUEST]: Update RMVPE to the latest checkpoint

### ISSUE THREAD

**Issue by yxlllc** [w-okada/voice-changer#930]
### In a few words, describe your idea

The RVC official repository has updated the RMVPE checkpoint , which is in the author's huggingface . I am responsible for training this new RMVPE model. The performance of this checkpoint is better when I test it. You can test it and update it if there is no problem.

**Comment by yxlllc** [comment]
Another thing is that the number of mel frames required to be input during the RMVPE inference process is an integer multiple of 32. If it is not an integer multiple of 32, using pad will degrade the effect (may cause frequency doubling error). In other words, considering that 1 frame is 10ms, it is recommended that the audio sampling point of rmvpe inference (under 16khz sampling rate) is 160 * (32*n - 1), where n is an integer (minus 1 because mel analysis will have one more frame).

**Comment by w-okada** [comment]
Thank you for reaching out. I am willing to give it a try.

**Comment by w-okada** [comment]
done.

**Comment by w-okada** [comment]
close
