### ISSUE TITLE
[ISSUE]: RES is crazy high

### ISSUE THREAD

**Issue by Stimzx** [w-okada/voice-changer#931]
### Voice Changer Version

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.13

### Operational System

Windows 11

### GPU

NVIDIA GeForce GTX 1050

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [X] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

RES goes from a cool like 500 to 20000 pretty fast which makes the voice changer quite unusable and nothing is showing up on logs

### Application Screenshot

![image](https://github.com/w-okada/voice-changer/assets/147249204/c72e9d2d-c5d3-4271-b9c9-c963881dc1c5)

### Logs on console

![image](https://github.com/w-okada/voice-changer/assets/147249204/75edd9c2-caab-4f67-8278-340f039d0bca)

**Comment by Stimzx** [comment]
and if it works fine, it only works fine for like abit, then it starts rising

**Comment by Stimzx** [comment]
btw my gpu n stuff arent going to like 100% or anything, its just like ona  cool 40-60%

**Comment by Stimzx** [comment]
nvm i fixed it, how do i close this ;-;

**Comment by Stimzx** [comment]
nvmmm its still doing it

**Comment by w-okada** [comment]
OK Cose.

**Comment by retr0j12** [comment]
set chunk to 192 and extra to 16k. export model to onnx and re-upload
