### ISSUE TITLE
[ISSUE]: "Pipeline has been deleted" no voice models work

### ISSUE THREAD

**Issue by cheesecake46** [w-okada/voice-changer#934]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.14.zip

### Operational System

windows 11

### GPU

NVIDIA GeForce GTX 1060 6GB

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

With all custom and default models they have the error "Pipeline has been deleted" none of the voices work at all. All I hear is my own voice. I've tried everything I can think of to fix it.

### Logs on console

C:\AI Voice changer\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] Loading index...
Try loading... model_dir\7\added_IVF103_Flat_nprobe_1_necoarc_v2.index
[VCClient] wait web server... done 200
[2023-10-08 15:09:04] connet sid : iBwOnsYOpOaVNAcPAAAC
[2023-10-08 15:09:04] connet sid : cd4CdztBj66d2qIWAAAD
[Voice Changer] update configuration: passThrough true
[Voice Changer] update configuration: indexRatio 0.1
[Voice Changer] update configuration: indexRatio 0.2
[Voice Changer] update configuration: indexRatio 0.3
[Voice Changer] update configuration: indexRatio 0.4
[Voice Changer] update configuration: indexRatio 0.6
[Voice Changer] update configuration: indexRatio 0.9
[Voice Changer] update configuration: indexRatio 1
[Voice Changer] update configuration: indexRatio 1
[Voice Changer] update configuration: tran 4
[Voice Changer] update configuration: tran 7
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: tran 13
[Voice Changer] update configuration: tran 13
[Voice Changer] update configuration: tran 16
[Voice Changer] update configuration: tran 19
[Voice Changer] update configuration: modelSlotIndex 1696792190007
Pipeline has been deleted
gin_channels: 256 self.spk_embed_dim: 109
[Voice Changer] generate new embedder. (anyway)
[Voice Changer] Loading index...
Try loading... model_dir\7\added_IVF103_Flat_nprobe_1_necoarc_v2.index

**Comment by w-okada** [comment]
"Pipeline has been deleted" this message is not error.

> All I hear is my own voice.

Isn't it in pass-through mode?

**Comment by cheesecake46** [comment]
Yes, I assumed that was how you tested to see if the voice changer was working correctly. Was I mistaken?

**Comment by cheesecake46** [comment]
I guess I just overlooked that in the tutorial, I'm sorry for wasting your time.
