### ISSUE TITLE
[REQUEST]: nocuda_v.1.5.3.15、低品質です。

### ISSUE THREAD

**Issue by noba1968** [w-okada/voice-changer#939]
### In a few words, describe your idea

不具合報告

### More information

OS：Ventura 13.6
Apple M1Max
メモリ64G

MMVCServerSIO_mac_onnxcpu-nocuda_v.1.5.3.15インストールし起動確認後、
音声入力すると、以前のバージョンと比較すると、言葉が聞き取れない程度の品質低下あり。

**Comment by w-okada** [comment]
すみません。こちらを使用してさいどissueを開いてください。

![image](https://github.com/w-okada/voice-changer/assets/48346627/e3e2859f-f3b1-4fcf-87d8-339fd4ca10ed)
