### ISSUE TITLE
The network cannot be connected

### ISSUE THREAD

**Issue by zwl2828596** [w-okada/voice-changer#942]
After 1.5.3.13, the network problem cannot be used, and the problem cannot be solved for a long time.
A version that can be opened without a network connection
![QQ截图20231011210500](https://github.com/w-okada/voice-changer/assets/104117549/4e2b40fe-0929-47a5-a166-b5511befc99a)

**Comment by w-okada** [comment]
use this one. thanks

![image](https://github.com/w-okada/voice-changer/assets/48346627/e3e2859f-f3b1-4fcf-87d8-339fd4ca10ed)
