### ISSUE TITLE
[REQUEST]: 

### ISSUE THREAD

**Issue by rodri01027** [w-okada/voice-changer#944]
### In a few words, describe your idea

No Voice works and no Sound coming out

### More information

When I try to use a Voice it just doesn't work like there's no sound coming out. I have tried the other voices but same issue and I hope that someone can help me with this I watched so many tutorials but it just won't work.

**Comment by Rafacasari** [comment]
🤦‍♂️ That's not a feature request. Use the right template issue.

**Comment by w-okada** [comment]
use this one. thanks

![image](https://github.com/w-okada/voice-changer/assets/48346627/e3e2859f-f3b1-4fcf-87d8-339fd4ca10ed)
