### ISSUE TITLE
[REQUEST]: 

### ISSUE THREAD

**Issue by Byanov** [w-okada/voice-changer#945]
VOICE CHANGER 

win 11

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.13

Voice changer downloaded, but doesnt work 

### More information

C:\Games\Neironnay BAZA>MMVCServerSIO.exe     -p 18888     --https true     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTPS(self-signed), key:C:\Users\Admin\AppData\Local\Temp\tmp3ewboo4o\keys\20231011_215047.key, cert:C:\Users\Admin\AppData\Local\Temp\tmp3ewboo4o\keys\20231011_215047.cert
    -- ---- --
    Please open the following URL in your browser.
    https://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    https://127.0.1.1:18888/
    https://192.168.0.113:18888/
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
![image](https://github.com/w-okada/voice-changer/assets/147656257/af7105e6-524f-4eaa-af49-a574f36fcabe)

**Comment by Byanov** [comment]
DirectML doesnt work to

**Comment by w-okada** [comment]
use this one. thanks

![image](https://github.com/w-okada/voice-changer/assets/48346627/e3e2859f-f3b1-4fcf-87d8-339fd4ca10ed)
