### ISSUE TITLE
[ISSUE]: Can't Open start_bat and suddenly close everytime

### ISSUE THREAD

**Issue by BangJancoks123** [w-okada/voice-changer#957]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.15

### Operational System

Windows 11

### GPU

RTX 3060 Laptop

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

MMVC

### Issue Description

I can't open the star_bat file, every time I open it a command will appear and it will close itself. and i try open using cmd and powershell and get massage like this : MMVCServerSIO.exe' is not recognized as an internal or external command,
operable program or batch file.

### Application Screenshot

<img width="861" alt="image" src="https://github.com/w-okada/voice-changer/assets/148349421/dcd66f14-2b6e-4005-9cfb-0473b553d539">

### Logs on console

C:\Users\Naqee>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
'MMVCServerSIO.exe' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\Naqee>C:\Users\Naqee\Desktop\MMVCServerSIO\start_http.bat

**Comment by w-okada** [comment]
use `.bat`

**Comment by w-okada** [comment]
no res close
