### ISSUE TITLE
[ISSUE]: MMVCServerSIO doesn't receive sounds from my mic

### ISSUE THREAD

**Issue by ADMIPO** [w-okada/voice-changer#958]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.15.zip

### Operational System

Windows 11

### GPU

4060 Laptop

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

Tried many times unzipping the file and run the "start http" bat, like #643 the connection broke and it seems I missed some necessary file. However the GUI was launched. But when I started to talk, the "vol" remained 0. So I assume the MMVCServerSIO doesn't receive any sound from my mic. I want to know if the problem stated above will cause the no sound problem.

### Application Screenshot

<img width="249" alt="屏幕截图 2023-10-18 221619" src="https://github.com/w-okada/voice-changer/assets/66743669/5e81179d-90c0-4fe7-bf53-c7a69ad5669a">

### Logs on console

D:\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
 14%|█▍        | 25.6M/181M [00:40<04:03, 669kB/s]('Connection broken: IncompleteRead(23309477 bytes read, 338693697 more expected)', IncompleteRead(23309477 bytes read, 338693697 more expected))
 16%|█▌        | 28.5M/181M [00:45<05:08, 517kB/s]('Connection broken: IncompleteRead(23283923 bytes read, 355604930 more expected)', IncompleteRead(23283923 bytes read, 355604930 more expected))
  8%|▊         | 30.6M/361M [00:45<08:38, 668kB/s]('Connection broken: IncompleteRead(32226549 bytes read, 24598881 more expected)', IncompleteRead(32226549 bytes read, 24598881 more expected))
 17%|█▋        | 29.9M/181M [00:47<03:27, 761kB/s]('Connection broken: IncompleteRead(33365038 bytes read, 345070919 more expected)', IncompleteRead(33365038 bytes read, 345070919 more expected))
 17%|█▋        | 30.2M/181M [00:48<03:07, 843kB/s]  ('Connection broken: IncompleteRead(31042416 bytes read, 57942374 more expected)', IncompleteRead(31042416 bytes read, 57942374 more expected))
 17%|█▋        | 31.5M/181M [00:49<02:37, 993kB/s] ('Connection broken: IncompleteRead(33088474 bytes read, 156419435 more expected)', IncompleteRead(33088474 bytes read, 156419435 more expected))
                                                  s('Connection broken: IncompleteRead(75674878 bytes read, 105509394 more expected)', IncompleteRead(75674878 bytes read, 105509394 more expected))
 65%|██████▌   | 35.3M/54.1M [00:49<00:07, 2.49MB/[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='つくよみちゃん(onnx)', description='', credit='つくよみちゃん', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tsukuyomi-chan/terms_of_use.txt', iconFile='tsukuyomi-chan.png', speakers={0: 'target'}, modelFile='tsukuyomi_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='Tsukuyomi-chan_o', version='v2')
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='あみたろ(onnx)', description='', credit='あみたろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/amitaro/terms_of_use.txt', iconFile='amitaro.png', speakers={0: 'target'}, modelFile='amitaro_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='Amitaro_o', version='v2')
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='黄琴まひろ(onnx)', description='', credit='黄琴まひろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/kikoto_mahiro/terms_of_use.txt', iconFile='kikoto_mahiro.png', speakers={0: 'target'}, modelFile='kikoto_mahiro_v2_40k_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='KikotoMahiro_o', version='v2')
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='刻鳴時雨(onnx)', description='', credit='刻鳴時雨', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tokina_shigure/terms_of_use.txt', iconFile='tokina_shigure.png', speakers={0: 'target'}, modelFile='tokina_shigure_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='TokinaShigure_o', version='v2')
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='あみたろ 16k(onnx)', description='', credit='あみたろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/amitaro16k/terms_of_use.txt', iconFile='amitaro.png', speakers={0: 'target'}, modelFile='amitaro_v2_16k.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='Amitaro_16k_o', version='v2')
SlotInfo::: RVCModelSlot(slotIndex=-1, voiceChangerType='RVC', name='あみたろ 16k(onnx)', description='', credit='あみたろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/amitaro16k/terms_of_use.txt', iconFile='amitaro_nof0.png', speakers={0: 'target'}, modelFile='amitaro_v2_16k_nof0.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='pyTorchRVC', samplingRate=-1, f0=True, embChannels=256, embOutputLayer=9, useFinalProj=True, deprecated=False, embedder='hubert_base', sampleId='Amitaro_16k_nof0_o', version='v2')
[Voice Changer] Downloading model files...
 43%|████▎     | 22.6M/52.8M [00:30<00:36, 863kB/s] ('Connection broken: IncompleteRead(34755248 bytes read, 31770029 more expected)', IncompleteRead(34755248 bytes read, 31770029 more expected))
 46%|████▌     | 24.2M/52.8M [00:32<00:31, 946kB/s] ('Connection broken: IncompleteRead(27267176 bytes read, 28115235 more expected)', IncompleteRead(27267176 bytes read, 28115235 more expected))
 47%|████▋     | 25.0M/52.8M [00:32<00:22, 1.29MB/s]('Connection broken: IncompleteRead(30571721 bytes read, 24810690 more expected)', IncompleteRead(30571721 bytes read, 24810690 more expected))
[Voice Changer] Generating metadata...
[Voice Changer] ONNX Model: Official v2 like
SlotInfo::: RVCModelSlot(slotIndex=0, voiceChangerType='RVC', name='つくよみちゃん(onnx)', description='', credit='つく
よみちゃん', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tsukuyomi-chan/terms_of_use.txt', iconFile='tsukuyomi-chan.png', speakers={'0': 'target'}, modelFile='tsukuyomi_v2_40k_e100_simple.onnx', indexFile='', defaultTune=0, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='Tsukuyomi-chan_o', version='v2')
    [Voice Changer] loading sample failed [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from model_dir\1\amitaro_v2_40k_e100_simple.onnx failed:Protobuf parsing failed.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

**Comment by v1tzeennn** [comment]
Have you solved this problem? If so, tell me how
