### ISSUE TITLE
[ISSUE]: Both my voice and the AI voice are coming through on chat programs (Discord)

### ISSUE THREAD

**Issue by Tornado219** [w-okada/voice-changer#961]
### Voice Changer Version

https://huggingface.co/wok000/vcclient000/blob/main/MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.15.

### Operational System

Windows 10

### GPU

NVIDIA GEForce GTX 1050

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [ ] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

Pretty much what's in the title! Both my voice and the AI voice are coming through at once for some reason. Not sure if it was me messing up the digital cable or what, but trying to have it so only the AI voice comes through on Discord, and not my own voice.

### Logs on console

N/A

**Comment by exciar** [comment]
are you sure you just don't have the audio monitor on?

**Comment by Tornado219** [comment]
Where would I see if I did? I tried the app in Discord, people could hear both me and the AI after a small delay.

**Comment by Tornado219** [comment]
Ok, I see what you mean. Nope, it's coming through with the Monitor on or off.

**Comment by w-okada** [comment]
If you're using Voicemeter, I suggest testing the audio on the Voicemeter interface.

**Comment by exciar** [comment]
try another audio cable like this one https://software.muzychenko.net/freeware/vac470lite.zip

**Comment by w-okada** [comment]
no res close
