### ISSUE TITLE
[ISSUE]: Voice doesnt change

### ISSUE THREAD

**Issue by adharidwan** [w-okada/voice-changer#967]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.15

### Operational System

Windows 11

### GPU

RTX 4050

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

MMVC

### Issue Description

voice doesnt change

### Application Screenshot

![Screenshot (36)](https://github.com/w-okada/voice-changer/assets/140234882/f2ca22cb-004e-41d9-abea-a51be204abe3)

### Logs on console

[Voice Changer] update configuration: modelSlotIndex 1698255699003
[Voice Changer] generate new embedder. (no embedder)
[Voice Changer] use torch contentvec [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.
[Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cuda:0
Traceback (most recent call last):
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder
  File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 30, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by EliceMoo** [comment]
I have the same problem

**Comment by EliceMoo** [comment]
> ### Voice Changer Version
> MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.15
> 
> ### Operational System
> Windows 11
> 
> ### GPU
> RTX 4050
> 
> ### Read carefully and check the options
> * [ ]  I've tried to Clear Settings
> * [ ]  Sample/Default Models are working
> * [ ]  I've tried to change the Chunk Size
> * [x]  GUI was successfully launched
> * [x]  I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
> * [x]  I've tried to extract to another folder (or re-extract) the .zip file
> 
> ### Model Type
> MMVC
> 
> ### Issue Description
> voice doesnt change
> 
> ### Application Screenshot
> ![Screenshot (36)](https://user-images.githubusercontent.com/140234882/278100486-f2ca22cb-004e-41d9-abea-a51be204abe3.png)
> 
> ### Logs on console
> [Voice Changer] update configuration: modelSlotIndex 1698255699003 [Voice Changer] generate new embedder. (no embedder) [Voice Changer] use torch contentvec [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed. [Voice Changer] exception! loading embedder PytorchStreamReader failed reading zip archive: failed finding central directory cuda:0 Traceback (most recent call last): File "voice_changer\RVC\embedder\EmbedderManager.py", line 47, in loadEmbedder File "voice_changer\RVC\embedder\OnnxContentvec.py", line 17, in loadModel File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in **init** File "onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from pretrain/content_vec_500.onnx failed:Protobuf parsing failed.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 30, in createPipeline File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task state = load_checkpoint_to_cpu(filename, arg_overrides) File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu state = torch.load(f, map_location=torch.device("cpu")) File "torch\serialization.py", line 797, in load with _open_zipfile_reader(opened_file) as opened_zipfile: File "torch\serialization.py", line 283, in **init** super().**init**(torch._C.PyTorchFileReader(name_or_buffer)) RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

Try to reinstall without antivirus, it helped for me.
