### ISSUE TITLE
[REQUEST + ISSUE]: Double conversion problem

### ISSUE THREAD

**Issue by yukiarimo** [w-okada/voice-changer#968]
### In a few words, describe your idea

My idea is to improve voice conversion on custom models

### More information

Hi devs. I have a problem with a voice changer. For example, if I’m using Siri voice, and convert it from female to male (using my custom model), I’m getting that perfect voice I like (-12 octave). But if I’m going from Male to Male, tune parameters can’t help me, and it sounds weird. So, I think I need a double conversion Male -> Female -> Male to make it work. Or suggest different approach if you have some ideas about that!

Note: my model is Male trained on my own voice

**Comment by exciar** [comment]
huhh
