### ISSUE TITLE
[ISSUE]: Wait web server took so long

### ISSUE THREAD

**Issue by adharidwan** [w-okada/voice-changer#970]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.15

### Operational System

Windows 11

### GPU

RTX 4050

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

MMVC

### Issue Description

after i uploaded a hu tao voice model it suddenly took so long for wait web server

### Application Screenshot

![Screenshot (37)](https://github.com/w-okada/voice-changer/assets/140234882/5484648d-9756-46b3-8782-19e5d2d40b47)

### Logs on console

VCClient] wait web server...220 http://127.0.0.1:18888/
[VCClient] wait web server...230 http://127.0.0.1:18888/
[VCClient] wait web server...240 http://127.0.0.1:18888/
[VCClient] wait web server...250 http://127.0.0.1:18888/
[VCClient] wait web server...260 http://127.0.0.1:18888/
[VCClient] wait web server...270 http://127.0.0.1:18888/
[VCClient] wait web server...280 http://127.0.0.1:18888/
[VCClient] wait web server...290 http://127.0.0.1:18888/
[VCClient] wait web server...300 http://127.0.0.1:18888/
[VCClient] wait web server...310 http://127.0.0.1:18888/
[VCClient] wait web server...320 http://127.0.0.1:18888/
[VCClient] wait web server...330 http://127.0.0.1:18888/
[VCClient] wait web server...340 http://127.0.0.1:18888/
[VCClient] wait web server...350 http://127.0.0.1:18888/
[VCClient] wait web server...360 http://127.0.0.1:18888/
[VCClient] wait web server...370 http://127.0.0.1:18888/
[VCClient] wait web server...380 http://127.0.0.1:18888/
[VCClient] wait web server...390 http://127.0.0.1:18888/
[VCClient] wait web server...400 http://127.0.0.1:18888/
[VCClient] wait web server...410 http://127.0.0.1:18888/
[VCClient] wait web server...420 http://127.0.0.1:18888/
[VCClient] wait web server...430 http://127.0.0.1:18888/
[VCClient] wait web server...440 http://127.0.0.1:18888/
[VCClient] wait web server...450 http://127.0.0.1:18888/
[VCClient] wait web server...460 http://127.0.0.1:18888/
[VCClient] wait web server...470 http://127.0.0.1:18888/
[VCClient] wait web server...480 http://127.0.0.1:18888/
[VCClient] wait web server...490 http://127.0.0.1:18888/
[VCClient] wait web server...500 http://127.0.0.1:18888/
#it keeps goinggg

**Comment by w-okada** [comment]
no res close
