### ISSUE TITLE
[ISSUE]: cant launch client got eror Client Closed

### ISSUE THREAD

**Issue by Punten10** [w-okada/voice-changer#971]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.15.zip

### Operational System

Windows 10

### GPU

GTX 1660 SUPER

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

after I start "start_http.bat" it will automatically close cmd and open the program "MMVCServerSIO.exe" after opening it gets the error "Client Closed" and nothing else happens

### Application Screenshot

![Screenshot (393)](https://github.com/w-okada/voice-changer/assets/64400801/943ab734-9f10-400c-a3c4-9c036771aa8c)

### Logs on console

after I start "start_http.bat" it will automatically close cmd and open the program "MMVCServerSIO.exe" after opening it gets the error "Client Closed" and nothing else happens

**Comment by w-okada** [comment]
Please try accessing http://localhost:18888 through your Chrome browser.

**Comment by w-okada** [comment]
no res close
