### ISSUE TITLE
[ISSUE]: 

### ISSUE THREAD

**Issue by YunoStoleMySyntax** [w-okada/voice-changer#972]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.15

### Operational System

windows 11

### GPU

gtx4090

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

-

### Issue Description

MMVCServerSIO.exe is not included in the latest zipfile. It is in MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.14, not in the MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.15 however.

### Logs on console

MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
'MMVCServerSIO.exe' is not recognized as an internal or external command,
operable program or batch file.

**Comment by w-okada** [comment]
I can find it. Check again.

![image](https://github.com/w-okada/voice-changer/assets/48346627/f3164a41-18c0-4cff-bb68-c658fd087647)

**Comment by w-okada** [comment]
no res close

**Comment by khushboo2000s** [comment]
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 30, in createPipeline
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 26, in getEmbedder
  File "voice_changer\RVC\embedder\EmbedderManager.py", line 51, in loadEmbedder
  File "voice_changer\RVC\embedder\FairseqHubert.py", line 11, in loadModel
  File "fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central direct
