### ISSUE TITLE
[ISSUE]: 

### ISSUE THREAD

**Issue by benilyasss** [w-okada/voice-changer#982]
### Voice Changer Version

MMVCServerSIO_win_onnxdirectML-cuda_v.1.5.3.16

### Operational System

Windows 10

### GPU

RTX 3060

### Read carefully and check the options

- [x] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [x] GUI was successfully launched
- [ ] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

Well, i setting my chunk 8 (21.3 ms, 1024) and i having more response ms pls help

### Application Screenshot

![image](https://github.com/w-okada/voice-changer/assets/101053605/4f5aaec0-8273-4388-a828-d1c7e2382929)

### Logs on console

C:\Users\PC\Desktop\Masaüstü\beyinli ses değiştirici\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
    Booting PHASE :__main__
    Booting PHASE :MMVCServerSIO
[Voice Changer] VoiceChangerManager initializing...
[Voice Changer] model slot is changed -1 -> 1
................RVC
[Voice Changer] [RVCr2] Creating instance
VoiceChangerV2 Initialized (GPU_NUM(cuda):1, mps_enabled:False, onnx_device:CPU-DML)
[Voice Changer][RVC]: update_settings gpu:0
[Voice Changer][RVCr2] Initializing...
2023-11-05 00:22:04.1449266 [W:onnxruntime:, session_state.cc:1169 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-11-05 00:22:04.1484269 [W:onnxruntime:, session_state.cc:1171 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] generate new embedder. (no embedder)
2023-11-05 00:22:04.6419245 [W:onnxruntime:, session_state.cc:1169 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-11-05 00:22:04.6459731 [W:onnxruntime:, session_state.cc:1171 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[Voice Changer] Loading index...
[Voice Changer] Index file is not found
GENERATE INFERENCER<voice_changer.RVC.inferencer.OnnxRVCInferencer.OnnxRVCInferencer object at 0x00000292C9100A30>
GENERATE EMBEDDER<voice_changer.RVC.embedder.OnnxContentvec.OnnxContentvec object at 0x00000292C9100370>
GENERATE PITCH EXTRACTOR<voice_changer.RVC.pitchExtractor.RMVPEOnnxPitchExtractor.RMVPEOnnxPitchExtractor object at 0x00000292C9100A90>
[Voice Changer] [RVC] Initializing... done
[Voice Changer][RVC]: update_settings serverReadChunkSize:48
[Voice Changer][RVC]: update_settings silentThreshold:0.001
[Voice Changer][RVC]: update_settings extraConvertSize:4096
[Voice Changer][RVC]: update_settings f0Detector:crepe_tiny
[Voice Changer][RVC]: update_settings enableServerAudio:0
[Voice Changer][RVC]: update_settings modelSlotIndex:1699132497001
[Voice Changer] VoiceChangerManager initializing... done.
[Voice Changer] MMVC_Rest initializing...
[Voice Changer] MMVC_Rest initializing... done.
[Voice Changer] MMVC_SocketIOApp initializing...
[Voice Changer] MMVC_SocketIOApp initializing... done.
[VCClient] wait web server... done 200
[2023-11-05 00:26:10] connet sid : IOaFhfrndz7om6-9AAAC
[2023-11-05 00:26:10] connet sid : V1ZoVRjWYJD8xbpXAAAD
Generated Strengths: for prev:(4096,), for cur:(4096,)
[Voice Changer] warming up... generating sola buffer.
[Voice Changer] update configuration: serverReadChunkSize 8
[Voice Changer][RVC]: update_settings serverReadChunkSize:8
Generated Strengths: for prev:(1024,), for cur:(1024,)
[Voice Changer] warming up... generating sola buffer.

**Comment by exciar** [comment]
you are using DirectML version which is for AMD GPU and please use chunk 40 at best 

[CUDA version](https://huggingface.co/wok000/vcclient000/commit/eb8ba3655fdc31fe20228c375de53a7506dac86e)

**Comment by benilyasss** [comment]
no im using intel i5 12400F 12. gen

**Comment by exciar** [comment]
no you are using the wrong version for your gpu

**Comment by benilyasss** [comment]
What version should i use??

**Comment by exciar** [comment]
the [onnxgpu-cuda_v.1.5.3.16a.zip](https://huggingface.co/wok000/vcclient000/commit/eb8ba3655fdc31fe20228c375de53a7506dac86e#d2h-070343)

**Comment by benilyasss** [comment]
Alright. ill try.

**Comment by benilyasss** [comment]
okay i downloaded what is best settings for me?

**Comment by exciar** [comment]
![image](https://github.com/w-okada/voice-changer/assets/139718583/78d87da7-88c8-4bba-92e0-733c231b9473)

**Comment by benilyasss** [comment]
thanks

**Comment by benilyasss** [comment]
it working thank you so much

exciar ***@***.***>, 13 Kas 2023 Pzt, 22:25 tarihinde şunu
yazdı:

**Comment by benilyasss** [comment]
i closed.
