### ISSUE TITLE
[ISSUE]: Converted voice not being able to be played + in browser recording program not working

### ISSUE THREAD

**Issue by bruce-w1** [w-okada/voice-changer#986]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.14.zip

### Operational System

Windows 11

### GPU

GTX 1660 Super

### Read carefully and check the options

- [X] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [X] I've tried to change the Chunk Size
- [X] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

The play-through feature works fine. However, I can not hear the converted voice nor use either of the recording features.

### Application Screenshot

![image](https://github.com/w-okada/voice-changer/assets/149994139/0685b7a7-162e-4ac4-83c7-4e1c775b8e58)

### Logs on console

C:\Users\xiao\OneDrive\桌面\aivoicechanger\MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.14\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
2023-11-05 21:22:00.0457513 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1641 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
    Booting PHASE :__main__
    PYTHON:3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
    Activating the Voice Changer.
[Voice Changer] download sample catalog. samples_0003_t2.json
[Voice Changer] download sample catalog. samples_0003_o2.json
[Voice Changer] download sample catalog. samples_0003_d2.json
[Voice Changer] model_dir is already exists. skip download samples.
    Internal_Port:18888
    protocol: HTTP
    -- ---- --
    Please open the following URL in your browser.
    http://<IP>:<PORT>/
    In many cases, it will launch when you access any of the following URLs.
    http://127.0.0.1:18888/

[VCClient] Access http://127.0.0.1:18888/
[VCClient] wait web server...0 http://127.0.0.1:18888/
[Voice Changer] exception! loading inferencer D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:574 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 25, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 55, in loadInferencer
  File "voice_changer\RVC\inferencer\OnnxRVCInferencer.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 395, in _create_inference_session
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:574 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

[VCClient] wait web server... done 200
[2023-11-05 21:26:29] connet sid : fmlDk8sxRXowWWC2AAAC
[2023-11-05 21:26:29] connet sid : vQpfDUYW9xFSD2XrAAAD
[Voice Changer] update configuration: silentThreshold 0.00091
[Voice Changer] update configuration: silentThreshold 0.0009
[Voice Changer] update configuration: silentThreshold 0.0009
[Voice Changer] update configuration: silentThreshold 0.00089
[Voice Changer] update configuration: silentThreshold 0.00088
[Voice Changer] update configuration: silentThreshold 0.00085
[Voice Changer] update configuration: silentThreshold 0.00081
[Voice Changer] update configuration: silentThreshold 0.00076
[Voice Changer] update configuration: silentThreshold 0.00076
[Voice Changer] update configuration: silentThreshold 0.00071
[Voice Changer] update configuration: silentThreshold 0.00069
[Voice Changer] update configuration: silentThreshold 0.00068
[Voice Changer] update configuration: silentThreshold 0.00065
[Voice Changer] update configuration: silentThreshold 0.00064
[Voice Changer] update configuration: silentThreshold 0.00063
[Voice Changer] update configuration: silentThreshold 0.00062
[Voice Changer] update configuration: silentThreshold 0.0006
[Voice Changer] update configuration: f0Detector crepe
[Voice Changer] update configuration: passThrough true
[Voice Changer] update configuration: passThrough false
SlotInfo::: RVCModelSlot(slotIndex=2, voiceChangerType='RVC', name='黄琴まひろ(onnx)', description='', credit='黄琴まひ ろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/kikoto_mahiro/terms_of_use.txt', iconFile='kikoto_mahiro.png', speakers={'0': 'target'}, modelFile='kikoto_mahiro_v2_40k_simple.onnx', indexFile='', defaultTune=12, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='KikotoMahiro_o', version='v2')
SlotInfo::: RVCModelSlot(slotIndex=2, voiceChangerType='RVC', name='黄琴まひろ(onnx)', description='', credit='黄琴まひ ろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/kikoto_mahiro/terms_of_use.txt', iconFile='kikoto_mahiro.png', speakers={'0': 'target'}, modelFile='kikoto_mahiro_v2_40k_simple.onnx', indexFile='', defaultTune=12, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='KikotoMahiro_o', version='v2')
SlotInfo::: RVCModelSlot(slotIndex=2, voiceChangerType='RVC', name='黄琴まひろ(onnx)', description='', credit='黄琴まひ ろ', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/kikoto_mahiro/terms_of_use.txt', iconFile='kikoto_mahiro.png', speakers={'0': 'target'}, modelFile='kikoto_mahiro_v2_40k_simple.onnx', indexFile='', defaultTune=12, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='KikotoMahiro_o', version='v2')
[Voice Changer] update configuration: silentThreshold 0.00061
[Voice Changer] update configuration: silentThreshold 0.00063
[Voice Changer] update configuration: silentThreshold 0.00065
[Voice Changer] update configuration: silentThreshold 0.00072
[Voice Changer] update configuration: silentThreshold 0.00073
[Voice Changer] update configuration: silentThreshold 0.00074
[Voice Changer] update configuration: silentThreshold 0.00076
[Voice Changer] update configuration: silentThreshold 0.00077
[Voice Changer] update configuration: silentThreshold 0.00078
[Voice Changer] update configuration: silentThreshold 0.00079
[Voice Changer] update configuration: recordIO 1
[Voice Changer] update configuration: recordIO 0
[Voice Changer] update configuration: recordIO 1
[Voice Changer] update configuration: recordIO 0
[Voice Changer] update configuration: modelSlotIndex 1699246058000
[Voice Changer] exception! loading inferencer D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:574 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 25, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 55, in loadInferencer
  File "voice_changer\RVC\inferencer\OnnxRVCInferencer.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 395, in _create_inference_session
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:574 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

[Voice Changer] update configuration: recordIO 1
[Voice Changer] update configuration: recordIO 0
SlotInfo::: RVCModelSlot(slotIndex=0, voiceChangerType='RVC', name='つくよみちゃん(onnx)', description='', credit='つく よみちゃん', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tsukuyomi-chan/terms_of_use.txt', iconFile='tsukuyomi-chan.png', speakers={'0': 'target'}, modelFile='tsukuyomi_v2_40k_e100_simple.onnx', indexFile='', defaultTune=12, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='Tsukuyomi-chan_o', version='v2')
SlotInfo::: RVCModelSlot(slotIndex=0, voiceChangerType='RVC', name='つくよみちゃん(onnx)', description='', credit='つく よみちゃん', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tsukuyomi-chan/terms_of_use.txt', iconFile='tsukuyomi-chan.png', speakers={'0': 'target'}, modelFile='tsukuyomi_v2_40k_e100_simple.onnx', indexFile='', defaultTune=12, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='Tsukuyomi-chan_o', version='v2')
SlotInfo::: RVCModelSlot(slotIndex=0, voiceChangerType='RVC', name='つくよみちゃん(onnx)', description='', credit='つく よみちゃん', termsOfUseUrl='https://huggingface.co/wok000/vcclient_model/raw/main/rvc_v2_alpha/tsukuyomi-chan/terms_of_use.txt', iconFile='tsukuyomi-chan.png', speakers={'0': 'target'}, modelFile='tsukuyomi_v2_40k_e100_simple.onnx', indexFile='', defaultTune=12, defaultIndexRatio=0, defaultProtect=0.5, isONNX=True, modelType='onnxRVC', samplingRate=40000, f0=True, embChannels=768, embOutputLayer=12, useFinalProj=False, deprecated=False, embedder='hubert_base', sampleId='Tsukuyomi-chan_o', version='v2')
[Voice Changer] update configuration: indexRatio 0.1
[Voice Changer] update configuration: indexRatio 0.1
[Voice Changer] update configuration: indexRatio 0.1
[Voice Changer] update configuration: indexRatio 0.2
[Voice Changer] update configuration: indexRatio 0.2
[Voice Changer] update configuration: indexRatio 0.2
[Voice Changer] update configuration: enableServerAudio 1
[Voice Changer] update configuration: enableServerAudio 0
[Voice Changer] update configuration: recordIO 1
[Voice Changer] update configuration: recordIO 0
[Voice Changer] update configuration: recordIO 1
[Voice Changer] update configuration: passThrough true
[Voice Changer] update configuration: silentThreshold 0.00081
[Voice Changer] update configuration: silentThreshold 0.00086
[Voice Changer] update configuration: silentThreshold 0.00092
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: silentThreshold 0.001
[Voice Changer] update configuration: tran 14
[Voice Changer] update configuration: tran 17
[Voice Changer] update configuration: tran 23
[Voice Changer] update configuration: tran 32
[Voice Changer] update configuration: tran 45
[Voice Changer] update configuration: tran 50
[Voice Changer] update configuration: tran 50
[Voice Changer] update configuration: tran 50
[Voice Changer] update configuration: tran 50
[Voice Changer] update configuration: recordIO 0
[Voice Changer] update configuration: recordIO 1
[Voice Changer] update configuration: passThrough false
[Voice Changer] update configuration: recordIO 0
[Voice Changer] update configuration: recordIO 1
[Voice Changer] update configuration: recordIO 0
[2023-11-05 21:59:44] connet sid : FqPQbIoSuamYB2J1AAAF
[2023-11-05 21:59:44] connet sid : KeKBv1N9RgA9dRniAAAH
[Voice Changer] update configuration: tran 46
[Voice Changer] update configuration: tran 45
[Voice Changer] update configuration: tran 43
[Voice Changer] update configuration: tran 40
[Voice Changer] update configuration: tran 38
[Voice Changer] update configuration: tran 38
[Voice Changer] update configuration: tran 37
[Voice Changer] update configuration: tran 35
[Voice Changer] update configuration: tran 33
[Voice Changer] update configuration: tran 31
[Voice Changer] update configuration: tran 27
[Voice Changer] update configuration: tran 23
[Voice Changer] update configuration: tran 22
[Voice Changer] update configuration: tran 19
[Voice Changer] update configuration: tran 17
[Voice Changer] update configuration: tran 15
[Voice Changer] update configuration: tran 13
[Voice Changer] update configuration: tran 12
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: tran 9
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: tran 6
[Voice Changer] update configuration: tran 5
[Voice Changer] update configuration: tran 3
[Voice Changer] update configuration: tran 2
[Voice Changer] update configuration: tran 1
[Voice Changer] update configuration: tran 1
[Voice Changer] update configuration: tran 0
[Voice Changer] update configuration: tran 1
[Voice Changer] update configuration: tran 2
[Voice Changer] update configuration: tran 3
[Voice Changer] update configuration: tran 4
[Voice Changer] update configuration: tran 5
[Voice Changer] update configuration: tran 6
[Voice Changer] update configuration: tran 7
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: tran 9
[Voice Changer] update configuration: tran 9
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: tran 12
[Voice Changer] update configuration: tran 12
[Voice Changer] update configuration: tran 13
[Voice Changer] update configuration: tran 12
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: tran 9
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: tran 7
[Voice Changer] update configuration: tran 3
[Voice Changer] update configuration: tran -1
[Voice Changer] update configuration: tran -8
[Voice Changer] update configuration: tran -23
[Voice Changer] update configuration: tran -34
[Voice Changer] update configuration: tran -40
[Voice Changer] update configuration: tran -50
[Voice Changer] update configuration: tran -50
[Voice Changer] update configuration: tran -50
[Voice Changer] update configuration: tran -50
[Voice Changer] update configuration: tran -43
[Voice Changer] update configuration: tran -27
[Voice Changer] update configuration: tran -12
[Voice Changer] update configuration: tran 3
[Voice Changer] update configuration: tran 17
[Voice Changer] update configuration: tran 25
[Voice Changer] update configuration: tran 27
[Voice Changer] update configuration: tran 26
[Voice Changer] update configuration: tran 20
[Voice Changer] update configuration: tran 5
[Voice Changer] update configuration: tran -10
[Voice Changer] update configuration: tran -26
[Voice Changer] update configuration: tran -35
[Voice Changer] update configuration: tran -35
[Voice Changer] update configuration: tran -31
[Voice Changer] update configuration: tran -23
[Voice Changer] update configuration: tran -8
[Voice Changer] update configuration: tran -3
[Voice Changer] update configuration: tran 4
[Voice Changer] update configuration: tran 7
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: tran 8
[Voice Changer] update configuration: tran 9
[Voice Changer] update configuration: tran 10
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: tran 12
[Voice Changer] update configuration: tran 13
[Voice Changer] update configuration: tran 14
[Voice Changer] update configuration: tran 15
[Voice Changer] update configuration: tran 15
[Voice Changer] update configuration: tran 15
[Voice Changer] update configuration: tran 16
[Voice Changer] update configuration: tran 17
[Voice Changer] update configuration: tran 18
[Voice Changer] update configuration: tran 19
[Voice Changer] update configuration: tran 20
[Voice Changer] update configuration: tran 21
[Voice Changer] update configuration: tran 20
[Voice Changer] update configuration: tran 19
[Voice Changer] update configuration: tran 18
[Voice Changer] update configuration: tran 17
[Voice Changer] update configuration: tran 16
[Voice Changer] update configuration: tran 15
[Voice Changer] update configuration: tran 14
[Voice Changer] update configuration: tran 13
[Voice Changer] update configuration: tran 12
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: tran 11
[Voice Changer] update configuration: tran 12
[Voice Changer] update configuration: passThrough true
[Voice Changer] update configuration: passThrough false
[Voice Changer] update configuration: recordIO 1
[Voice Changer] update configuration: recordIO 0
[Voice Changer] update configuration: passThrough true
[Voice Changer] update configuration: serverReadChunkSize 320
[Voice Changer] update configuration: passThrough false
[Voice Changer] update configuration: serverReadChunkSize 256
[Voice Changer] update configuration: modelSlotIndex 1699247351001
[Voice Changer] exception! loading inferencer D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:574 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 25, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 55, in loadInferencer
  File "voice_changer\RVC\inferencer\OnnxRVCInferencer.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 395, in _create_inference_session
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:574 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

[Voice Changer] update configuration: modelSlotIndex 1699247353002
[Voice Changer] exception! loading inferencer D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:574 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 25, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 55, in loadInferencer
  File "voice_changer\RVC\inferencer\OnnxRVCInferencer.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 395, in _create_inference_session
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:574 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

[Voice Changer] update configuration: modelSlotIndex 1699247354003
[Voice Changer] exception! loading inferencer D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:574 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

Traceback (most recent call last):
  File "voice_changer\RVC\pipeline\PipelineGenerator.py", line 22, in createPipeline
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 25, in getInferencer
  File "voice_changer\RVC\inferencer\InferencerManager.py", line 55, in loadInferencer
  File "voice_changer\RVC\inferencer\OnnxRVCInferencer.py", line 17, in loadModel
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 395, in _create_inference_session
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:574 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

[Voice Changer] update configuration: serverReadChunkSize 448
[Voice Changer] update configuration: recordIO 1
[Voice Changer] update configuration: indexRatio 0.1
[Voice Changer] update configuration: indexRatio 0.1
[Voice Changer] update configuration: indexRatio 0.2
[Voice Changer] update configuration: indexRatio 0.2
[Voice Changer] update configuration: indexRatio 0.2
[Voice Changer] update configuration: indexRatio 0.2
[Voice Changer] update configuration: indexRatio 0.3
[Voice Changer] update configuration: indexRatio 0.5
[Voice Changer] update configuration: indexRatio 0.8
[Voice Changer] update configuration: indexRatio 1
[Voice Changer] update configuration: indexRatio 1
[Voice Changer] update configuration: serverReadChunkSize 2048
[Voice Changer] update configuration: extraConvertSize 131072
[Voice Changer] update configuration: recordIO 0
[Voice Changer] update configuration: enableServerAudio 1
[Voice Changer] update configuration: serverInputDeviceId 21
[Voice Changer] update configuration: serverOutputDeviceId 17
[Voice Changer] update configuration: enableServerAudio 0

**Comment by exciar** [comment]
use my settings (same gpu)
![image](https://github.com/w-okada/voice-changer/assets/139718583/498f0e47-7b75-433e-a138-7d536694b478)

**Comment by w-okada** [comment]
no update close
