### ISSUE TITLE
[ISSUE]: delaying voice and repeating voice

### ISSUE THREAD

**Issue by mrokadaai** [w-okada/voice-changer#988]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.15

### Operational System

Windows 11 Home

### GPU

NVIDIA GeForce RTX 3070

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [ ] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

There is always a second or two delaying time when I speak. Also, voices repeating after I speak.

### Logs on console

C:\Users\User\Desktop\Mangio-RVC-v23.7.0_INFER_TRAIN\Mangio-RVC-v23.7.0>runtime\python.exe infer-web.py --pycmd runtime\python.exe --port 7897
Found GPU NVIDIA GeForce RTX 3070
Set fp16_run to true in 32k.json
Set fp16_run to true in 40k.json
Set fp16_run to true in 48k.json
Use Language: en_US
Running on local URL:  http://0.0.0.0:7897

To create a public link, set `share=True` in `launch()`.

**Comment by exciar** [comment]
of course there will be always delay you cant process data instantaneously
please elaborate on how your voice repeats after speaking

**Comment by w-okada** [comment]
no update close
