### ISSUE TITLE
[ISSUE]: [4344] Failed to execute script 'MMVCServerSIO' due to unhandled exeption!

### ISSUE THREAD

**Issue by youlikememb** [w-okada/voice-changer#991]
### Voice Changer Version

MMVCServerSIO_win_onnxgpu-cuda_v.1.5.3.16.zip

### Operational System

Windows 10

### GPU

GTX 1080

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

MMVC

### Issue Description

error with start_http.bat , when I run the error appears for a moment and the window closes. Thanks in advance

### Application Screenshot

![Screenshot_345](https://github.com/w-okada/voice-changer/assets/150375858/e2bd7e3d-8acf-4a1f-9022-466953ddb72c)
![Screenshot_346](https://github.com/w-okada/voice-changer/assets/150375858/5e2112d3-3efa-4508-848d-25bca4d90193)

### Logs on console

C:\Program Files\MMVCServerSIO>MMVCServerSIO.exe     -p 18888     --https false     --content_vec_500 pretrain/checkpoint_best_legacy_500.pt     --content_vec_500_onnx pretrain/content_vec_500.onnx     --content_vec_500_onnx_on true     --hubert_base pretrain/hubert_base.pt     --hubert_base_jp pretrain/rinna_hubert_base_jp.pt     --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt     --nsf_hifigan pretrain/nsf_hifigan/model     --crepe_onnx_full pretrain/crepe_onnx_full.onnx     --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx     --rmvpe pretrain/rmvpe.pt     --model_dir model_dir     --samples samples.json
Traceback (most recent call last):
  File "MMVCServerSIO.py", line 33, in <module>
  File "mods\log_control.py", line 63, in initialize
  File "logging\__init__.py", line 1169, in __init__
  File "logging\__init__.py", line 1201, in _open
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\MMVCServerSIO\\vcclient.log'
[12728] Failed to execute script 'MMVCServerSIO'  due unhandled exeption!

**Comment by exciar** [comment]
reinstall

**Comment by w-okada** [comment]
no update close
